### ISSUE TITLE
on_client_gone

### ISSUE THREAD

**Issue by medaboub** [vernemq/vernemq#1002]
### To help us save time and help you faster

"on_client_gone" plugin method :  haw to know if client has disconnected gracefully (has sent disconnect request) or forced disconnect (connexion browken).

**Comment by larshesel** [comment]
Hi @medaboub 

There is at the moment no way to see the difference here - but this is a great idea and I'll tag this for VerneMQ 2.0. Thanks!

**Comment by larshesel** [comment]
Closing this until we start work on VerneMQ 2.0.
