### ISSUE TITLE
VerneMQ hangs and clients are not unable to connect

### ISSUE THREAD

**Issue by HsiaoH** [vernemq/vernemq#1007]
**Setup**
VerneMQ: 1.6.1 running on docker 18.09
Ubuntu: 16.04.5

**Problem**

It seems that VerneMQ randomly hangs with the following symptoms:
1) The command "docker exec vernemq vmq-admin cluster show" shows that the cluster is up and running
2) MQTT clients cannot (re)connect with timeout errors
3) The cluster cannot receive any messages
4) Seems to happen with high and low load

VerneMQ is runned with the following options:

    -e "DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES=0" \
    -e "DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES=-1" \
    -e "DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES=-1" \
    -e "DOCKER_VERNEMQ_MAX_CLIENT_ID_SIZE=100" \
    -e "DOCKER_VERNEMQ_MAX_MESSAGE_RATE=0" \
    -e "DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION=never" \
    -e "DOCKER_VERNEMQ_LEVELDB__MAXIMUM_MEMORY__PERCENT=50" \
    -e "DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT=on" \
    -e "DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT=on" \
    -e "DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT=on" \
    -e "DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT=on" \

The logging shows the following:

    2018-12-14 11:38:38 =CRASH REPORT====
      crasher:
    initial call: vmq_ranch:init/5
    pid: <0.2710.0>
    registered_name: []
    exception error: {{case_clause,{{case_clause,{badrpc,{'EXIT',{badarg,[{ets,lookup,[vmq_queue_tab_33,{[],<<"CPG_Client_T_0">>}],[]},{vmq_queue_sup,get_queue_pid,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_queue_sup.erl"},{line,69}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,197}]}]}}}},[{vmq_reg,'-register_subscriber/5-fun-0-',2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,179}]},{vmq_reg,block_until_migrated,4,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,246}]},{vmq_reg,register_subscriber,5,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,191}]},{vmq_reg_sync_action,'-init/1-fun-0-',1,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg_sync_action.erl"},{line,52}]}]}},[{vmq_mqtt_fsm,check_user,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,522}]},{vmq_mqtt_fsm,init,3,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,144}]},{vmq_mqtt_pre_init,data_in,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_mqtt_pre_init.erl"},{line,63}]},{vmq_ranch,handle_message,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,174}]},{vmq_ranch,loop_,1,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,117}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.2549.0>,<0.2548.0>,ranch_sup,<0.108.0>]
    message_queue_len: 0
    messages: []
    links: [<0.2549.0>]
    dictionary: [{bytes_received,#Ref<0.1126650390.423755778.189143>},{max_msg_size,0},{mqtt_connect_received,#Ref<0.1126650390.423755778.189141>},{socket_open,#Ref<0.1126650390.423755778.189146>},{rand_seed,{#{jump => #Fun<rand.16.15449617>,max => 288230376151711743,next => #Fun<rand.15.15449617>,type => exsplus},[284712418363154205|72698933591383572]}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 4635
      neighbours:
    2018-12-14 11:38:38 =ERROR REPORT====
    Ranch listener {{0,0,0,0},8883} had connection process started with vmq_ranch:start_link/4 at <0.2710.0> exit with reason: {{case_clause,{{case_clause,{badrpc,{'EXIT',{badarg,[{ets,lookup,[vmq_queue_tab_33,{[],<<"CPG_Client_T_0">>}],[]},{vmq_queue_sup,get_queue_pid,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_queue_sup.erl"},{line,69}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,197}]}]}}}},[{vmq_reg,'-register_subscriber/5-fun-0-',2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,179}]},{vmq_reg,block_until_migrated,4,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,246}]},{vmq_reg,register_subscriber,5,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,191}]},{vmq_reg_sync_action,'-init/1-fun-0-',1,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg_sync_action.erl"},{line,52}]}]}},[{vmq_mqtt_fsm,check_user,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,522}]},{vmq_mqtt_fsm,init,3,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,144}]},{vmq_mqtt_pre_init,data_in,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_mqtt_pre_init.erl"},{line,63}]},{vmq_ranch,handle_message,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,174}]},{vmq_ranch,loop_,1,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,117}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    2018-12-14 11:38:38 =ERROR REPORT====
    Error in process <0.2712.0> on node 'VerneMQ@10.2.0.5' with exit value:
    {{case_clause,{badrpc,{'EXIT',{badarg,[{ets,lookup,[vmq_queue_tab_33,{[],<<"CPG_Client_T_0">>}],[]},{vmq_queue_sup,get_queue_pid,2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_queue_sup.erl"},{line,69}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,197}]}]}}}},[{vmq_reg,'-register_subscriber/5-fun-0-',2,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,179}]},{vmq_reg,block_until_migrated,4,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,246}]},{vmq_reg,register_subscriber,5,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,191}]},{vmq_reg_sync_action,'-init/1-fun-0-',1,[{file,"/opt/vernemq/distdir/1.6.1/_build/default/lib/vmq_server/src/vmq_reg_sync_action.erl"},{line,52}]}]}

**Comment by larshesel** [comment]
Hi, thanks for reporting.

The crash you provide looks like a side-effect, not the root cause. I would expect there to be some other crashes before this one (as this one basically says that something which should be there isn't there, and the reason for that is usually because something went wrong earlier).

So what are the first errors / crashes you see?

**Comment by HsiaoH** [comment]
Hello,

Before the crash, the following entry shows up a lot:

    2018-12-14 11:37:46.874 [error] <0.2238.0>@vmq_metrics:incr_item:259 invalid counter queue_setup

The complete logs of that day:
- Error log: https://pastebin.com/VgNcPc76
- Crash log: https://pastebin.com/nStW7LAC  

Thanks!

**Comment by larshesel** [comment]
Thanks - the invalid counter isn't relevant - but something I have to fix... I've put that onto the backlog. 

I'm afraid there isn't much to go on in the logs. Is the crash in the logs the absolute earliest since the node was started? Is there a set of steps to reproduce this starting from a freshly started node - you mention it's reproducible with low load as well?

**Comment by larshesel** [comment]
> Thanks - the invalid counter isn't relevant - but something I have to fix... I've put that onto the backlog.

This actually looks like an effect of an earlier partial systems crash - the resource for the counter isn't there anymore - so this seems to confirm that something happened earlier than indicated in the logs provided and we therefore need to know more the steps leading up to this situation.

**Comment by HsiaoH** [comment]
These logs are the earliest available.  Too bad, I guess the only action left is to upgrade the cluster to 1.6.2 and see if the problem occurs again. Thanks for the help.

**Comment by larshesel** [comment]
> Anytime these partial crashes occur, is there a way to make the cluster "healthy" again other than start/stop it?

Well, it might be possible to just restart a single node in the cluster, but other than that and understanding what the root cause is I don't think there's any sensible recommendation to give.

Do you have monitoring in place? memory/cpu usages as well as all the VerneMQ metrics? It would be interesting to see how this looks over time and especially when this issue occurs.
