### ISSUE TITLE
Clients can't authenticate after postgres connection failed

### ISSUE THREAD

**Issue by darath** [vernemq/vernemq#1008]
### Environment
- VerneMQ Version: 1.6.1
- Docker version: 1.13.1, build 8633870/1.13.1
- OS: CentOS Linux release 7.5.1804 (Core)
- VerneMQ configuration (vernemq.conf) or the changes from the default
DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "on"
DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED: "on"
DOCKER_VERNEMQ_ALLOW_MULTIPLE_SESSIONS: "on"
DOCKER_VERNEMQ_QUEUE_DELIVER_MODE: "balance"
DOCKER_VERNEMQ_SHARED_SUBSCRIPTION_POLICY: "prefer_local"

### Expected behavior

- VerneMQ connects to postgres and all mqttclients can connect and publish/subscribe data.
- If the connection to the postgresdb gets rejected, it should reconnect properly.

### Actual behaviour

- The Expected behaviour actually works in one of our test systems. But in our production System after some time vernemq crahses and all clients get authentication errors. (before the crash all clients are able to connect to vernemq and publish messages)

- If we restart vernemq everything works fine again.
- After some time the following log messages occur:
`13:16:12.565 [error] can't execute query <<"SELECT publish_acl::TEXT, subscribe_acl::TEXT \n FROM vmq_auth_acl\n WHERE \n mountpoint=$1 AND\n client_id=$2 AND\n username=$3 AND\n password=crypt($4, password)\n ">> due to {exit,{timeout,{gen_server,call,[<0.377.0>,{apply,epgsql,equery,[<<"SELECT publish_acl::TEXT, subscribe_acl::TEXT \n FROM vmq_auth_acl\n WHERE \n mountpoint=$1 AND\n client_id=$2 AND\n username=$3 AND\n password=crypt($4, password)\n ">>,[<<>>,<<"my-client-id-1">>,<<"my-client-user-name-1">>,<<"my-client-pwd-1">>]]}]}}}
13:16:12.565 [error] can't call function auth_on_register with args [{addr,<<"some-ip-addr-1">>},{port,12345},{mountpoint,<<>>},{client_id,<<"my-client-id-1">>},{username,<<"my-client-username-1">>},{password,<<"my-client-pwd-1">>},{clean_session,false}] in "/usr/share/vernemq/lua/auth/postgres.lua" due to {badarg,execute_equery,[<<"auth_postgres">>,<<"SELECT publish_acl::TEXT, subscribe_acl::TEXT \n FROM vmq_auth_acl\n WHERE \n mountpoint=$1 AND\n client_id=$2 AND\n username=$3 AND\n password=crypt($4, password)\n ">>,<<>>,<<"my-client-id-1">>,<<"my-client-username-1">>,<<"my-client-pwd-1">>]}
13:16:12.565 [warning] can't authenticate client {[],<<"my-client-id-1">>} due to lua_script_error`

- This message occurs a multiple times. After about 15 minutes the following messages occur in our log:

`13:31:38.380 [error] gen_server <0.398.0> terminated with reason: {sock_error,etimedout}
13:31:38.380 [error] CRASH REPORT Process <0.398.0> with 0 neighbours exited with reason: {sock_error,etimedout} in gen_server:handle_common_reply/8 line 726
13:31:38.382 [error] gen_server <0.381.0> terminated with reason: no function clause matching vmq_diversity_script_state:handle_info({#Ref<0.1339570510.254803969.111369>,{error,not_connected}}, {state,4,{luerl,{array,26,100,undefined,{{{table,{array,0,10,nil,10},{{{{{empty,<<"_G">>,{...},...},...},...},...},...},...},...},...}},...},...}) line 162
13:31:38.389 [error] Supervisor {<0.365.0>,vmq_diversity_script_sup_sup} had child {vmq_diversity_script_state,3} started with vmq_diversity_script_state:start_link(3, "/usr/share/vernemq/lua/auth/postgres.lua") at <0.380.0> exit with reason no function clause matching vmq_diversity_script_state:handle_info({#Ref<0.1339570510.254803969.110721>,{error,not_connected}}, {state,3,{luerl,{array,26,100,undefined,{{{table,{array,0,10,nil,10},{{{{{empty,<<"_G">>,{...},...},...},...},...},...},...},...},...}},...},...}) line 162 in context child_terminated`

- After that, our clients are not able to publish or subscribe anymore:

`13:31:41.570 [error] can't auth publish [<<"my-client-username-1">>,{[],<<"my-client-id-1">>},0,[<<"topicprefix">>,<<"my-client-id-1">>,<<"topicsuffix">>],<<"my-payload">>,false] due to no_matching_hook_found`

We think this may happen, because a firewal reject open(idle) connections (vernemq -> postgres) after some timout. And the postgres lua plugin does not reconnect properly to the postgresdb again without a restart. (if we stop the postgresdb and restart it after some time, it reconnects wihtout any issues. its just if the open connection gets rejected)

side note: I was also able to reproduce this behaviour and log-messages with rejecting an open connection within the VM where the postgresdocker container is running. (via iptables REJECT)

**Comment by ioolkos** [comment]
@darath thanks for reporting!
I think you're right with your analysis.
@dergraf @larshesel can we add automatic re-connection to the Lua plugin? where should it be done exactly?

**Comment by larshesel** [comment]
Yes, of course - I actually thought we'd done this a while back - but maybe we just did some work on the mongo driver. We'll look into it

**Comment by darath** [comment]
thanks for your promp reply.
looking forward to version 1.6.3 ;)

**Comment by larshesel** [comment]
So there seem to be two issues here. One is that the `{error,not_connected}` tuple is propagated to the `vmq_diversity_script_state:handle_info` function which it shouldn't, but secondly we have an issue because when that happens the `vmq_diversity_script_state` gen_server exits and the supervisor restarts all the other children as well (one_for_all). Unfortunately are the new processes not registered with the plugin as ready to handle requests (`ets:tab2list(vmq_diversity_hooks)` returns `[]`).

I have to think a bit about best to handle this. Maybe @dergraf has a good idea here.

**Comment by larshesel** [comment]
Hi @darath 

We've created a fix for this in : https://github.com/vernemq/vernemq/pull/1031

It would be great if you could help verify the fix before we merge to master.
