### ISSUE TITLE
[Question] Improve config validation and throw warnings if the files can't be accessed

### ISSUE THREAD

**Issue by farizadp** [vernemq/vernemq#1024]
Oh, ok - great you found it! Maybe we can improve our config validation and throw warnings if the files don't exist?

_Originally posted by @larshesel in https://github.com/vernemq/vernemq/issues/405#issuecomment-306891657_

Gents,

Is there logging that says "hey, vernemq cannot access file(s) you have specified".
It took me one day to figure out that the permission of my private key is ```-rw-------```

Cheers,
Dion

**Comment by larshesel** [comment]
Hi, thanks for bringing this up again, and sorry you had to run into that issue. We haven't found the time yet to add checks and logs for this, unfortunately.

**Comment by larshesel** [comment]
Noticed there's already an issue open for this, namely #849, so closing this as a duplicate
