### ISSUE TITLE
docker swarm help needed

### ISSUE THREAD

**Issue by nachten** [vernemq/vernemq#1025]
I've been wrapping my head around this issue now for more then 2 days and I can't figure out why I can't get a docker swarm stack with following 2 nodes working:

- DOCKERM1: 10.51.102.100 (master)
- DOCKERW1: 10.51.102.110 (worker)

I'm using the following YAML file:

```
version: "3.2"
services:
  vernemq01:
    image: "erlio/docker-vernemq"
    ports:
      - "1883:1883"
      - "8883:8883"
    environment: 
      - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
    deploy:
      placement:
        constraints: [node.role == manager]  
  vernemq02:
    image: "erlio/docker-vernemq"
    environment: 
      - "DOCKER_VERNEMQ_DISCOVERY_NODE=mqtt_vernemq01"
    depends_on: 
      - "vernemq01"
```
And to install the stack i used the following command (on the leader of course):

**docker stack deploy -c docker-compose.yml mqtt**

After installation is finished I see the following:

Creating network mqtt_default
Creating service mqtt_vernemq01
Creating service mqtt_vernemq02

To check if everything is running i execute the command:

**docker stack services mqtt**

and get the following result

```
ID                  NAME                MODE                REPLICAS            IMAGE                         PORTS
aqp38ugv2ky5        mqtt_vernemq01      replicated          1/1                 erlio/docker-vernemq:latest   *:1883->1883/tcp, *:8883->8883/tcp
gz3tb00fgh3t        mqtt_vernemq02      replicated          1/1                 erlio/docker-vernemq:latest
```
Then to check if the cluster is created I execute the following command:

**docker exec <CONTAINER_ID> vmq-admin cluster show**

and I get the following result

`Node 'VerneMQ@10.255.1.249' not responding to pings.`

Maybe this is my problem ? I don't know ... 

But I think the problem lays in the fact that the cluster is simple not created, because when I execute the following command **** on the docker node which runs my "vernemq02" container I see the following:

```
19:53:08.743 [info] Application plumtree started on node 'VerneMQ@10.0.28.6'
19:53:08.755 [info] Application vmq_plumtree started on node 'VerneMQ@10.0.28.6'
19:53:08.808 [info] Try to start vmq_plumtree: ok
19:53:09.913 [info] loaded 0 subscriptions into vmq_reg_trie
19:53:09.933 [info] cluster event handler 'vmq_cluster' registered
19:53:10.778 [info] Application vmq_acl started on node 'VerneMQ@10.0.28.6'
19:53:10.973 [info] Application vmq_passwd started on node 'VerneMQ@10.0.28.6'
19:53:11.195 [info] Application vmq_server started on node 'VerneMQ@10.0.28.6'
19:53:11.195 [info] Application eldap started on node 'VerneMQ@10.0.28.6'
19:53:11.195 [info] Application poolboy started on node 'VerneMQ@10.0.28.6'
19:53:11.209 [info] Application luerl started on node 'VerneMQ@10.0.28.6'
19:53:11.239 [info] Application emysql started on node 'VerneMQ@10.0.28.6'
19:53:11.239 [info] Application epgsql started on node 'VerneMQ@10.0.28.6'
19:53:11.239 [info] Application bson started on node 'VerneMQ@10.0.28.6'
19:53:11.261 [info] Application mongodb started on node 'VerneMQ@10.0.28.6'
19:53:11.261 [info] Application pbkdf2 started on node 'VerneMQ@10.0.28.6'
19:53:11.261 [info] Application eredis started on node 'VerneMQ@10.0.28.6'
19:53:11.262 [info] Application unicode_util_compat started on node 'VerneMQ@10.0.28.6'
19:53:11.262 [info] Application idna started on node 'VerneMQ@10.0.28.6'
19:53:11.262 [info] Application mimerl started on node 'VerneMQ@10.0.28.6'
19:53:11.263 [info] Application certifi started on node 'VerneMQ@10.0.28.6'
19:53:11.263 [info] Application ssl_verify_fun started on node 'VerneMQ@10.0.28.6'
19:53:11.263 [info] Application metrics started on node 'VerneMQ@10.0.28.6'
19:53:11.330 [info] Application hackney started on node 'VerneMQ@10.0.28.6'
19:53:11.366 [info] Application bcrypt started on node 'VerneMQ@10.0.28.6'
19:53:11.366 [info] Application dht_ring started on node 'VerneMQ@10.0.28.6'
19:53:11.393 [info] Sent join request to: 'VerneMQ@mqtt_vernemq01'
19:53:11.398 [error] ** System running to use fully qualified hostnames **
** Hostname mqtt_vernemq01 is illegal **
19:53:11.402 [info] Unable to connect to 'VerneMQ@mqtt_vernemq01'
```
I really have no clue why it's not able to connect to mqtt_vernemq01 server ... I even tried to set the environment variable "DOCKER_VERNEMQ_DISCOVERY_NODE=mqtt_vernemq01" of the vernemq02 container to the exact ip address of the vernemq01 which where poth part of the same overlay network ... 

Please help me out or point me in an direction ... google did not do the trick for me .. or my google skills are to poor ;)

If you guys need any more information please let me know ...

**Comment by larshesel** [comment]
Hi - the nodename in the log above is `VerneMQ@10.0.28.6` (and I presume it's similar on the other node). You can only join nodes using the nodenames - and if the other nodename is on the form `VerneMQ@a.b.c.d` and you're trying to join with `VerneMQ@mqtt_vernemq01` then it won't work.

I think there may be some help in other issues over on https://github.com/vernemq/docker-vernemq where other people got docker swarm + VerneMQ to work.

**Comment by nachten** [comment]
Well i've just reinstalled my docker stack to check if you were correct, yes you are correct both showed an IP address ... but I thought that docker network would map the hostname to the internal IP of the docker container  ... guess I was wrong.

But still even if I would change my DOCKER_VERNEMQ_DISCOVERY_NODE to the IP address of the master node I still get this message.

Below the logs of my 2 nodes:

**Log: Master node**

```
19:19:21.470 [info] Application plumtree started on node 'VerneMQ@10.255.2.115'
19:19:21.482 [info] Application vmq_plumtree started on node 'VerneMQ@10.255.2.115'
19:19:21.534 [info] Try to start vmq_plumtree: ok
19:19:22.569 [info] loaded 0 subscriptions into vmq_reg_trie
19:19:22.586 [info] cluster event handler 'vmq_cluster' registered
19:19:23.507 [info] Application vmq_acl started on node 'VerneMQ@10.255.2.115'
19:19:23.731 [info] Application vmq_passwd started on node 'VerneMQ@10.255.2.115'
19:19:23.947 [info] Application vmq_server started on node 'VerneMQ@10.255.2.115'
19:19:23.947 [info] Application eldap started on node 'VerneMQ@10.255.2.115'
19:19:23.947 [info] Application poolboy started on node 'VerneMQ@10.255.2.115'
19:19:23.965 [info] Application luerl started on node 'VerneMQ@10.255.2.115'
19:19:23.998 [info] Application emysql started on node 'VerneMQ@10.255.2.115'
19:19:23.998 [info] Application epgsql started on node 'VerneMQ@10.255.2.115'
19:19:23.999 [info] Application bson started on node 'VerneMQ@10.255.2.115'
19:19:24.048 [info] Application mongodb started on node 'VerneMQ@10.255.2.115'
19:19:24.048 [info] Application pbkdf2 started on node 'VerneMQ@10.255.2.115'
19:19:24.049 [info] Application eredis started on node 'VerneMQ@10.255.2.115'
19:19:24.049 [info] Application unicode_util_compat started on node 'VerneMQ@10.255.2.115'
19:19:24.049 [info] Application idna started on node 'VerneMQ@10.255.2.115'
19:19:24.050 [info] Application mimerl started on node 'VerneMQ@10.255.2.115'
19:19:24.050 [info] Application certifi started on node 'VerneMQ@10.255.2.115'
19:19:24.050 [info] Application ssl_verify_fun started on node 'VerneMQ@10.255.2.115'
19:19:24.051 [info] Application metrics started on node 'VerneMQ@10.255.2.115'
19:19:24.153 [info] Application hackney started on node 'VerneMQ@10.255.2.115'
19:19:24.196 [info] Application bcrypt started on node 'VerneMQ@10.255.2.115'
19:19:24.196 [info] Application dht_ring started on node 'VerneMQ@10.255.2.115'

```

**Log: Node 2 connected to master node using DOCKER_VERNEMQ_DISCOVERY_NODE=10.255.2.115**

```
19:20:34.933 [info] Application plumtree started on node 'VerneMQ@10.0.33.8'
19:20:34.943 [info] Application vmq_plumtree started on node 'VerneMQ@10.0.33.8'
19:20:34.996 [info] Try to start vmq_plumtree: ok
19:20:35.991 [info] loaded 0 subscriptions into vmq_reg_trie
19:20:36.016 [info] cluster event handler 'vmq_cluster' registered
19:20:36.854 [info] Application vmq_acl started on node 'VerneMQ@10.0.33.8'
19:20:37.030 [info] Application vmq_passwd started on node 'VerneMQ@10.0.33.8'
19:20:37.240 [info] Application vmq_server started on node 'VerneMQ@10.0.33.8'
19:20:37.240 [info] Application eldap started on node 'VerneMQ@10.0.33.8'
19:20:37.240 [info] Application poolboy started on node 'VerneMQ@10.0.33.8'
19:20:37.256 [info] Application luerl started on node 'VerneMQ@10.0.33.8'
19:20:37.290 [info] Application emysql started on node 'VerneMQ@10.0.33.8'
19:20:37.291 [info] Application epgsql started on node 'VerneMQ@10.0.33.8'
19:20:37.291 [info] Application bson started on node 'VerneMQ@10.0.33.8'
19:20:37.316 [info] Application mongodb started on node 'VerneMQ@10.0.33.8'
19:20:37.317 [info] Application pbkdf2 started on node 'VerneMQ@10.0.33.8'
19:20:37.317 [info] Application eredis started on node 'VerneMQ@10.0.33.8'
19:20:37.318 [info] Application unicode_util_compat started on node 'VerneMQ@10.0.33.8'
19:20:37.318 [info] Application idna started on node 'VerneMQ@10.0.33.8'
19:20:37.319 [info] Application mimerl started on node 'VerneMQ@10.0.33.8'
19:20:37.319 [info] Application certifi started on node 'VerneMQ@10.0.33.8'
19:20:37.320 [info] Application ssl_verify_fun started on node 'VerneMQ@10.0.33.8'
19:20:37.320 [info] Application metrics started on node 'VerneMQ@10.0.33.8'
19:20:37.387 [info] Application hackney started on node 'VerneMQ@10.0.33.8'
19:20:37.420 [info] Application bcrypt started on node 'VerneMQ@10.0.33.8'
19:20:37.420 [info] Application dht_ring started on node 'VerneMQ@10.0.33.8'
19:20:37.443 [info] Sent join request to: 'VerneMQ@10.255.2.115'
19:20:37.452 [info] Unable to connect to 'VerneMQ@10.255.2.115'
```

When I look at the IP addresses 10.255.2.115 and 10.0.33.8 it's not strange that they cannot connect with each other because there not even in the same subnet. 

When I follow the tutorial on the [https://github.com/vernemq/docker-vernemq](https://github.com/vernemq/docker-vernemq) with the subjects:

- Start a VerneMQ cluster node
- Autojoining a VerneMQ cluster

Everything works fine .. but then again ... there not in a swarm so my MQTT cluster nodes are not divided over multiple physical nodes in my docker swarm (which I want).

If you guys want I can re-ask my question on [https://github.com/vernemq/docker-vernemq](https://github.com/vernemq/docker-vernemq) so this repo keeps clean ?

**Comment by MrSpark2591** [comment]
@nachten [this might be the same problem](https://github.com/vernemq/docker-vernemq/issues/43).

Even I am looking for similar kind of setup.

**Comment by dergraf** [comment]
@nachten I think you should look at Docker swarm overlay networks which provide the routing layer between mutliple Docker hosts. https://docs.docker.com/network/overlay/

**Comment by AmnaSnene** [comment]
I'm trying to create a vernemq cluster using docker swarm. The cluster contains 4 nodes distributed on 4 physical raspberry pi's. For that, I'm using this docker-compose file: 
`version: "3.7"
services:
  vmq0:
    image: timbrand/vernemq-rpi
    environment:
      DOCKER_VERNEMQ_SWARM: 1
  vmq:
    image: timbrand/vernemq-rpi
    depends_on:
      - vmq0
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker` 
      
When i check my vernemq cluster on the manager node, I find only one node (the same on the other nodes) :

+-----------------+-------+
|      Node       |Running|
+-----------------+-------+
|VerneMQ@10.0.12.3| true  |
+-----------------+-------+

The stack is creating an new overlay network: 
 NAME                          DRIVER             SCOPE
vernemq-stack_default   overlay             swarm

When I try to  `vmq-admin cluster join discovery-node=VerneMQ@10.0.12.3` I get: 
Couldn't join cluster due to not_reachable .

What should I do ?
