### ISSUE TITLE
vmq_ql_query Subquery timeout

### ISSUE THREAD

**Issue by davionxiang** [vernemq/vernemq#1033]
### Environment

- VerneMQ Version: 1.5.0
- OS: CentOS Linux release 7.5.1804
- Erlang/OTP version (if building from source): Erlang/OTP 19
- Cluster size/standalone: standalone

### Expected behavior
   I've implemented a method in my elixir plugin which invokes vmq_ql_query:fold_query and will be called in on_register, on_client_gone and on_client_offline hook
   ```
def online_clients(app_id, username) do
    username_size = byte_size(username)
    func = fn
      %{ 
         client_id:  <<^app_id::binary-size(64), ":", ^username::binary-size(username_size), ":", client_id::binary>>,
      }, acc -> [client_id | acc]
      _, acc -> acc
    end
    :vmq_ql_query_mgr.fold_query(
      func, [], 'SELECT client_id FROM sessions WHERE is_online=true'
    )
  end
```
  And I've tested this method in vernemq console, it returns immediately.

### Actual behaviour
  When I try to connect with websocket connection, it works.
  But when I try to connect with TCP connection, client disconnects every time.
  I observed something in crash.log
  ```
2019-01-15 23:05:33 =ERROR REPORT====
** Generic server <0.4052.0> terminating
** Last message in was timeout
** When Server state == {state,<0.4051.0>,"SELECT client_id FROM sessions WHERE is_online=true",undefined,undefined}
** Reason for termination ==
** {{error,badarg},[{vmq_ql_query,select,6,[{file,"/mnt/log/dechao/vernemq-1.5.0/_build/default/lib/vmq_ql/src/vmq_ql_query.erl"},{line,213}]},{vmq_ql_query,handle_info,2,[{file,"/mnt/log/dechao/vernemq-1.5.0/_build/default/lib/vmq_ql/src/vmq_ql_query.erl"},{line,88}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2019-01-15 23:05:33 =CRASH REPORT====
  crasher:
    initial call: vmq_ql_query:init/1
    pid: <0.4052.0>
    registered_name: []
    exception exit: {{error,badarg},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,812}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [vmq_ql_query_sup,vmq_ql_sup,<0.70.0>]
    messages: [{'DOWN',#Ref<0.0.2.42583>,process,<0.4051.0>,shutdown}]
    links: [<0.72.0>]
    dictionary: [{{parse_memo_table,vmq_ql_parser},128188569},{{vmq_ql_query,row_data},#{'__mountpoint' => [],clean_session => false,client_id => <<"c3b715490fffb4e38c7235e6761d24602124447e9ffad298f2c2ca37ad5f19c1:1539112805762:web_d1ec2f5c-c5">>,deliver_mode => fanout,is_offline => true,is_online => false,is_plugin => false,mountpoint => <<>>,node => <<"VerneMQ@127.0.0.1">>,num_sessions => 0,offline_messages => 0,online_messages => 0,queue_pid => <0.367.0>,statename => offline}}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 12398
  neighbours:
2019-01-15 23:05:33 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_ql_query_sup}
     Context:    child_terminated
     Reason:     {error,badarg}
     Offender:   [{pid,<0.4052.0>},{id,vmq_ql_query},{mfargs,{vmq_ql_query,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]
```
  also something in console.log
```
2019-01-14 21:38:30.414 [warning] <0.1405.0>@vmq_ql_query:select:203 Subquery failed due to timeout
2019-01-14 21:38:30.473 [warning] <0.1418.0>@vmq_ql_query:spawn_initialize_row:310 Subquery failed.
Stacktrace:
    vmq_ql_query:spawn_initialize_row/4 line 307
    vmq_ql_query:initialize_rows/3 line 325
    vmq_info:queue_row_init/1 line 121
    gen_fsm:sync_send_all_state_event/3 line 257
exit:{normal,{gen_fsm,sync_send_all_state_event,[<0.1398.0>,info,infinity]}}
```
I also found that this method returns correct client_ids in on_register hook, but after that client got disconnected and triggered on_client_gone hook.

**Comment by larshesel** [comment]
Calling `vmq_ql_query_mgr:fold_query` from within a session context (i.e. `on_register`) will result in timeouts as the query cannot query the calling session to extract information. So `vmq_ql` queries should always be done outside a session context for it to work. This should explain why it works from the console but no from within a hook.

I don't see why it should work for websockets but not for tcp connections. Are you sure you did the exact same experiment for tcp and websockets?

**Comment by davionxiang** [comment]
@larshesel Thanks for explaining. I see timeout for both websocket and tcp connections, the difference is websocket client doesn't get disconnected but tcp client does. Also my function return correct result in on_register hook for both connections.

Basically what I want to do is to get online clients count with a list of specific client ids, is there any recommended way to achieve that?

**Comment by larshesel** [comment]
> websocket client doesn't get disconnected but tcp client does.

That's interesting - not sure why that is so.



> Basically what I want to do is to get online clients count with a list of specific client ids after a client connects, is there any recommended way to achieve that?

No recommended way, I think it's the first time I heard about a requirement like this. If this is what needed I'd do something like what you do or simply push connect/disconnect data to some other service like a database and then query that instead.
