### ISSUE TITLE
How to load status page remotely

### ISSUE THREAD

**Issue by Crouxie** [vernemq/vernemq#1041]
Hello guys,

I am wondering if there is possible to load "/status" page with ajax. I have 3 nodes so every node has his own status page. So I tried to create page on another web server which could join these 3 status pages into one. Because of this another web server, browser is returning CORS error.

What can I do with it? Somehow alter status page on node with adding 
`header("Access-Control-Allow-Origin: *");`

or can I get status page data through API?

Thanks for advices

**Comment by cmnstmntmn** [comment]
hey there @Crouxie 

you could make a proxy to `status.json` endpoint 
and consume the way you need in your app

**Comment by cmnstmntmn** [comment]
also, if nodes are part of a cluster, `/status.json` will have data about each node, 
so you don't need to acces them individually.

**Comment by Crouxie** [comment]
@cmnstmntmn 
Big thanks! I didnt notice, that there is something such as status.json. And I want to access them individually, because when something happens with server (node) I will not have info about another nodes. (I hope that my logic is right :D )

**Comment by Crouxie** [comment]
Response is not containing header: `Access-Control-Allow-Origin` so jquery ends up in error: `....8888/status.json: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by cmnstmntmn** [comment]
@Crouxie indeed, that's why you should implement a proxy that consume `/status.json` endpoint (serverside) node, go, php doesn't really matter.

a super naive implementation of a proxy

```elixir
## myproxyurl.com/get_cluster_status

status.json
|> add_CORS_headers
|> serve_with_headers
```

after that you can make an ajax call to `myproxyurl.com/get_cluster_status` 
and get the data you need.

**Comment by cmnstmntmn** [comment]
no. if ypu’re using nginx, here’s a startung point https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

**Comment by Crouxie** [comment]
I have checked all three nodes....without sign of web server 👎 (nginx, tomcat, apache...) I will try to install web server and I will get back with result.

**Comment by Crouxie** [comment]
Problem solved by installation of nginx, configuration of reverse proxy.
Instructions if anybody interested: (/etc/nginx/conf.d/default.conf)

1. add `add_header 'Access-Control-Allow-Origin' '*';` under server name line
2. server_name replace with IP
3. comment first section "location"
4. uncomment "location" with proxy pass
5. replace server in proxy with source of requested data
6. restart nginx (service nginx restart)

**Comment by cmnstmntmn** [comment]
@Crouxie i'm curious how you make it work. I'm trying to do a similar thing, with this config

```nginx
location /verne {
  proxy_pass http://127.0.0.1:8888;
  
  proxy_http_version  1.1;
  proxy_cache_bypass  $http_upgrade;
  proxy_set_header Upgrade      $http_upgrade;
  proxy_set_header Connection     "upgrade";
  proxy_set_header Host       $host;
  proxy_set_header X-Real-IP      $remote_addr;
  proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto  $scheme;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Port $server_port;
}
```

but i can't see the status page for https://domain.tld/verne/status

**Comment by iamgbsmith** [comment]
This is a late response but it should help others in future.

The following configuration works for me running a local Docker deployment. You need to proxy the status.json to prevent an HTTP 404 on the XHR request to get the status data.

```
server {
    listen       80;
    server_name  localhost;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /vernemq/status {
      proxy_pass http://vmq0:8888/status;
    }

    location /status.json {
      proxy_pass http://vmq0:8888/status.json;
    }

    error_page   500 502 503 504  /50x.html;

    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

You should then be able to load the status page at http://localhost/vernemq/status
