### ISSUE TITLE
single Node crach (restore after restart)

### ISSUE THREAD

**Issue by medaboub** [vernemq/vernemq#1051]
I have signle vernemq node that manage devices presence status using retained online message when device connect and offline will message when device disconnect.
every thing work fine when node is live. but when node system crach or stoped. devices disconnected with no WILL message send and then they stays in status online.
Haw can I reset all devices status when node restart and then remove all retained message in leveldb database?

**Comment by larshesel** [comment]
I'm not sure I understand how deleting the retained messages would help - the retained messages are replicated to all other nodes - and I suppose you'd might want to set the retained message value for the cilent to `offline`?

In any case, we don't yet have a mechanism to delete all retained messages in one go. You could  delete them by manually publishing an empty retained message to each topic in question (this is the MQTT spec way of clearing a retained message).

Hope this helps.
