### ISSUE TITLE
very frequent client disconnections with K8s cluster

### ISSUE THREAD

**Issue by nickm** [vernemq/vernemq#1060]
### Environment

- VerneMQ Version: Tried 1.5.0, 1.6.0, 1.6.2
- OS: Kubernetes (erlio/docker-vernemq) running in AWS
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: tried 1 and 3.

Hi there, 

We are struggling with an issue running a VerneMQ cluster inside Kubernetes on AWS.
The cluster appears to be running fine and accepting messages, but our clients appear to be getting disconnected from the server every 2-3 seconds.  Stepping through the MQTT client library code every time it waits for a new message to come in (before able to trigger a PING message task), the socket is disconnected by the server which results on getting EOFException inside the code.

CLIENT:
Android application using the Paho MQTT library with the following version
org.eclipse.paho:org.eclipse.paho.android.service v1.1.1
org.eclipse.paho:org.eclipse.paho.client.mqttv3   v1.2.0

SERVER:
VerneMQ cluster inside Kubernetes on AWS.
When running VerneMQ on a dedicated VM we don't experience this issue.
When running inside K8 with an ELB as service load balancer it creates the issue - even if we reduce the cluster to a single instance.

Server logs have lots of:
`[warning] session stopped abnormally due to '{error,unexpected_message,{mqtt_connect,4,<<"USER">>,<<"PASS">>,0,60,<<"LONG_HASH">>,undefined,undefined,undefined,undefined}}'`

We've looked around, googled and tried various configurations (tried allow anonymous) but nothing has worked.

Thanks for you help.

**Comment by nickm** [comment]
Ok thanks @larshesel we'll try that out

**Comment by larshesel** [comment]
ok - as the issue doesn't point to any defects in VerneMQ I'll close it for now. Feel free to re-open if needed.

**Comment by nickm** [comment]
Thanks @larshesel - as a followup for anyone who experiences a similar problem, your diagnosis was correct.  Switching from a classic ELB to a newer Network Load Balancer fixed the issue.

Thanks for the great product.
