### ISSUE TITLE
Webinterface shows stats only of current node

### ISSUE THREAD

**Issue by TheOneValen** [vernemq/vernemq#1066]
### Environment

- VerneMQ Version: 1.7.0
- OS: debian 9.x
- Cluster size/standalone: 2

### Expected behavior

- The webinterface should show the cluster health on top and stats for each node on the bottom.

### Actual behaviour

- The bottom part just shows stats for the current node (the node that serves the webinterface)
- The json output still has the infos of all nodes of the cluster

**Comment by codeadict** [comment]
Can you please post some screenshot, or are you referring to only change the order? AFIK we show both the current node and the other cluster nodes on that interface.

**Comment by larshesel** [comment]
I just checked with a local two node cluster and the table at the bottom (Node Status) where there used to be an entry for each node there is now only one:

![image](https://user-images.githubusercontent.com/679187/52059492-496aae00-256a-11e9-8637-e24363fdf78d.png)

I would expect it to show a row for `dev1@127.0.0.1` and for `dev2@127.0.0.1`. But maybe I misunderstand something.

**Comment by codeadict** [comment]
ohh weird, i'll check that and submit any fix, maybe when i did the redesign something was lost, it should present both nodes

**Comment by codeadict** [comment]
I was able to find what caused this bug over the weekend, working on a fix...

**Comment by dergraf** [comment]
Fixed in current master
