### ISSUE TITLE
There is a metric that tell me how many messages are inside online and offline queues?

### ISSUE THREAD

**Issue by davideicardi** [vernemq/vernemq#1069]
There is a metric that tell me how many messages are inside online and offline queues?

There is `counter.queue_message_out` and `counter.queue_message_in` but it is not very clear what it is. I think that you have a counter based on all subscribers and topics.

My goal is to understand if my subscriber is able to receive all messages that are sent to VerneMQ without accumulating messages inside a queue.

### Environment
- VerneMQ Version: 1.4.1

**Comment by ioolkos** [comment]
Look at the help command for vmq-admin session.
Something like `sudo vmq-admin session show --online_messages --offline_messages --client_id` might be of use.

**Comment by larshesel** [comment]
You can see detailed information about the metrics by adding the `-d/--with-descriptions` flag to learn a bit more about the precise definition of the metrics. I would expect that `counter.queue_message_in - counter.queue_message_out` should in normal cases be expressing the number of queued messages.

**Comment by dometec** [comment]
Sorry to comment on an old issue, but is correct this behavior?

I have 6 total offline messages (4 for a topic and 2 for another one) but I can't see this details:

```
vernemq@localhost:~$ vmq-admin session show --online_messages --offline_messages --client_id
+------------------+------------------+-----------------+
| client_id        | offline_messages | online_messages |
+------------------+------------------+-----------------+
| mqtt2kafka       | 6                | 0               |
+------------------+------------------+-----------------+
| dometec155135756 | 0                | 0               |
+------------------+------------------+-----------------+
vernemq@localhost:~$ vmq-admin session show --online_messages --offline_messages --client_id --topic
+------------------+------------------+-----------------+-------------------------+
| client_id        | offline_messages | online_messages | topic                   |
+------------------+------------------+-----------------+-------------------------+
| mqtt2kafka       | 6                | 0               | +/+/TH700/+/runtime     |
+------------------+------------------+-----------------+-------------------------+
| mqtt2kafka       | 6                | 0               | +/+/TH700WALL/+/runtime |
+------------------+------------------+-----------------+-------------------------+
| mqtt2kafka       | 6                | 0               | +/+/TH800/+/runtime     |
+------------------+------------------+-----------------+-------------------------+
| mqtt2kafka       | 6                | 0               | +/+/gateway             |
+------------------+------------------+-----------------+-------------------------+
| dometec155135756 | 0                | 0               | #                       |
+------------------+------------------+-----------------+-------------------------+
vernemq@localhost:~$
```

As you can see, I get always 6 offline messages for each line of each topic.

**Comment by ioolkos** [comment]
@dometec it's expected behaviour. Offline messages belong to a queue and that queue belongs to the clientid `mqtt2kafka` exclusively. The queue collects all the messages from all the matching topic filters.
A topic is never a queue!

Note that the rows, of course, repeat information, due to the topic column. There's no better way to do this in a table format, I guess.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by dometec** [comment]
Understand, thanks!
