### ISSUE TITLE
Persistent client expiration does not work for clients that went inactive before node has been restarted

### ISSUE THREAD

**Issue by madvadik** [vernemq/vernemq#1071]
### Environment
- VerneMQ Version: 1.6.2
- OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Erlang/OTP version (if building from source):N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default: persistent_client_expiration=1h
- Cluster size/standalone: standalone node

### Expected behavior
After setting persistent_client_expiration to some value it is expected to that all clients inactive during that period are removed even after the node restarts.

### Actual behaviour
Clients that went inactive before vernemq has been restarted are not removed after the period set in persistent_client_expiration had passed.

Example:
![image](https://user-images.githubusercontent.com/47420185/52418294-fbb3ef80-2aed-11e9-8c49-ce3810d80ad7.png)

Maybe it is working as intended (in which case it would be nice to have it mentioned in the docu), but I would be very thankful if it was working even after the restart.

Thanks!

**Comment by dergraf** [comment]
@madvadik thanks for opening the issue. This is a bug. 

@larshesel We should do something similar like https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_queue.erl when starting up the queue process, maybe here https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_queue.erl#L421?

**Comment by larshesel** [comment]
Hi @madvadik I just created a PR for this (see #1079 ). Would you be able to test if it works for you? Note, we now simply initialize the expiration timeout with the value from the configuration file, so after a broker restart a queue will start the expiration timeout from scratch.
