### ISSUE TITLE
Can't compile VerneMQ on Mac OS X

### ISSUE THREAD

**Issue by volkrass** [vernemq/vernemq#1077]
### Environment

- VerneMQ Version: Master Branch
- OS: Mac OS X Mojave
- Erlang/OTP version 21.2.4 (installed via Homebrew)
- VerneMQ configuration (vernemq.conf): default
- Cluster size/standalone: standalone

### Expected behavior

- Compilation works like described in README.md

### Actual behaviour

Command:  make rel

Error appears:
===> Compiling lager
./mqtt/vernemq/_build/default/lib/lager/src/lager_util.erl: redefining predefined macro 'FUNCTION_NAME'
===> Compiling _build/default/lib/lager/src/lager_util.erl failed
_build/default/lib/lager/src/lager_util.erl:none: redefining predefined macro 'FUNCTION_NAME'

**Comment by larshesel** [comment]
Since this seems to come from lager, could you try to upgrade the lager version by changing the version here https://github.com/vernemq/vernemq/blob/master/rebar.config#L15 from 3.6.3 to 3.6.8 and, remove the old build, then do a `./rebar3 upgrade lager` and then rebuild and post the result here. No idea if that will work (not using macosx), but worth a shot.

**Comment by volkrass** [comment]
Thanks for your advice. Yes, it seems it is related to lager. Unfortunately upgrading to 3.6.8 doesn't solve the problem.

**Comment by larshesel** [comment]
I did hear someone say that there was some issue with OTP 21 but it worked with OTP 20, so maybe you could try that. Sorry for not being of more help.

**Comment by codeadict** [comment]
One thing to note is that you need to upgrade to latest rebar3 `3.9.0`, there was a bug in the previous version that broke my OSX compilation. Maybe is not the same but worth a shot @volkrass

**Comment by volkrass** [comment]
Ok, I switched to OTP 20, using lager 3.6.8, like mentioned by @larshesel, but I'm still not able to compile it.

Here my output:
...
===> Compiling vernemq_dev
===> Compiling recon
===> Compiling node_package
===> Compiling syslog
cc -O3 -std=c99 -arch x86_64 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/Cellar/erlang@20/20.3.8.20/lib/erlang/erts-9.3.3.9/include/ -I /usr/local/Cellar/erlang@20/20.3.8.20/lib/erlang/lib/erl_interface-3.10.2.1/include  -c -o /Users/<name>/Projects/experiments/mqtt/vernemq/_build/default/lib/syslog/c_src/syslog_drv.o /Users/<name>/Projects/experiments/mqtt/vernemq/_build/default/lib/syslog/c_src/syslog_drv.c
cc /Users/<name>/Projects/experiments/mqtt/vernemq/_build/default/lib/syslog/c_src/syslog_drv.o -arch x86_64 -flat_namespace -undefined suppress -shared -L /usr/local/Cellar/erlang@20/20.3.8.20/lib/erlang/lib/erl_interface-3.10.2.1/lib -lerl_interface -lei -o /Users/<name>/Projects/experiments/mqtt/vernemq/_build/default/lib/syslog/c_src/../priv/syslog_drv.so
===> Compiling goldrush
===> Compiling lager
/Users/<name>/Projects/experiments/mqtt/vernemq/_build/default/lib/lager/src/lager_util.erl: redefining predefined macro 'FUNCTION_NAME'
===> Compiling _build/default/lib/lager/src/lager_util.erl failed
_build/default/lib/lager/src/lager_util.erl:none: redefining predefined macro 'FUNCTION_NAME'


More Details: Mac OS X, 10.14.3, Erlang/OTP 20 [erts-9.3.3.9], Lager 3.6.8

**Comment by larshesel** [comment]
And with lager 3.9.0 as proposed by codeadict?

**Comment by volkrass** [comment]
@larshesel, sorry that I missed to tell you the rebar version.
Output: rebar 3.9.0 on Erlang/OTP 20 Erts 9.3.3.9

**Comment by larshesel** [comment]
ok - the only thing I can think of is the erlang installation itself. How did you install that? @codeadict how do you install Erlang?

Otherwise I'm out of suggestions....

**Comment by codeadict** [comment]
I installed 21 with homebrew `brew install erlang`. OSX behaves so weird most of the time that we need to get those releases out from travis IMO.

**Comment by volkrass** [comment]
@larshesel, I installed OPT 21 and OTP 20 via Homebrew. 
'brew install erlang' to get latest version or 'brew install erlang@20'

What I would like to mention is, that I also compiled EMQ without any hassle.

**Comment by larshesel** [comment]
ok - when you're compiling VerneMQ do you start from scratch? I mean, did you start from a fresh clone or removed the `_build` directory?

As I'm not on OSX I'm afraid I don't have any ideas how to help more besides what @codeadict said: we should get travis to build osx releases for us - but of course that doesn't solve the problem for those who want to develop and compile vernemq on osx.

**Comment by volkrass** [comment]
I tried first from scratch, later on I removed only _build directory and has started build again. I will double check everything again.

**Comment by bieniusa** [comment]
I was fighting with the same problem for a month (with a different project) and have just figured out a solution that works for me after following your discussion!
Setup:

- rebar 3.9.0 on Erlang/OTP 21 Erts 10.2.5
- lager 3.6.8 from Hex

The trick was to add lager as a top level dependency in the project's rebar.config. Then use `rebar3 upgrade lager` to bump it to 3.6.8 despite other dependencies on prior versions. Apparently, the old lager version was creeping in through some dependencies.

**Comment by cmnstmntmn** [comment]
@bieniusa this is great! i was having the same issue.

**Comment by volkrass** [comment]
I'm Erlang newbie, can somebody give me an advice what I have to change in rebar.config?

**Comment by cmnstmntmn** [comment]
@volkrass 

```
{deps, [
        {lager, "3.6.8"},
        ..
```

and then then

```shell
rm rebar.lock
rm -rf _build
rm -rf ~/.cache/rebar3
rebar3 upgrade lager

make rel
```

**Comment by volkrass** [comment]
A big thank you to everybody who has support me with my newbie problem. 
Compilation works now like a charm.

**Comment by volkrass** [comment]
Thanks @bieniusa and @cmnstmntmn for your support. Now I'm a step further...But unfortunately it looks like the compiling of eleveldb is not working here on my Mac.

         ^~~~~~~~
1 warning and 1 error generated.
cc  -I /Users/<user>/Projects/experiments/mqtt/vernemq/_build/default/lib/eleveldb/c_src/system/include -I. -I./include -mmacosx-version-min=10.8 -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -DSNAPPY  -O2 -g -DNDEBUG     -fPIC -MM -E -MT db/builder.d -MT db/builder.o -MF db/builder.d db/builder.cc
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from db/builder.cc:8:
In file included from ./db/builder.h:8:
./include/leveldb/status.h:16:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
g++  -I /Users/<user>/Projects/experiments/mqtt/vernemq/_build/default/lib/eleveldb/c_src/system/include -I. -I./include -mmacosx-version-min=10.8 -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -DSNAPPY  -O2 -g -DNDEBUG     -fPIC -c db/builder.cc -o db/builder.o
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from db/builder.cc:8:
In file included from ./db/builder.h:8:
./include/leveldb/status.h:16:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
make[1]: *** [db/builder.o] Error 1
===> Hook for compile failed!

make: *** [rel] Error 1

**Comment by bieniusa** [comment]
Seems that you are reproducing all the issues that I ran into several months ago. I will take care next time to document it somewhere properly.

The problem with the C++ headers is related to an upgrade on Xcode a couple of months ago.
You should try to install the most recent version of the Xcode command line tools from
[the apple developer resources](https://developer.apple.com/download/more/)

This resolved it for me, I think.

**Comment by larshesel** [comment]
In the meantime I'll create a PR to upgrade lager so at least that shouldn't be a problem in the future.

**Comment by cmnstmntmn** [comment]
@volkrass there's an article on this subject - [vernemq viki - Building-VerneMQ-on-OS-X](https://github.com/vernemq/vernemq/wiki/Building-VerneMQ-on-OS-X)

**Comment by volkrass** [comment]
I would say it is done :)

===> release successfully created!

Thanks again for all your support here, guys.
