### ISSUE TITLE
Problems bridging VerneMQ to AWS IoT

### ISSUE THREAD

**Issue by Fettuccine-Alfredo** [vernemq/vernemq#1084]
### Environment

- VerneMQ Version: 1.7.0
- OS: Fedora 29 running docker-vernemq 1.7.0
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
[vernemq.conf.txt](https://github.com/vernemq/vernemq/files/2892818/vernemq.conf.txt)
- Cluster size/standalone: standalone

### Expected behavior

- Expected bridging to AWS IoT to work.

### Actual behaviour

- After each message is bridged/published to AWS IoT, the VerneMQ client disconnects.  After a few cycles of connect/disconnect, AWS IoT refused to accept new connections.

Here's the log output: [vernemq.log.txt](https://github.com/vernemq/vernemq/files/2892828/vernemq.log.txt)

**Comment by dergraf** [comment]
The no case clause match error is here: https://github.com/vernemq/vernemq/blob/master/apps/vmq_commons/src/gen_mqtt_client.erl#L455. But instead of the `#mqtt_publish` it tries to match a tuple likely coming from here https://github.com/vernemq/vernemq/blob/master/apps/vmq_commons/src/gen_mqtt_client.erl#L605

**Comment by dergraf** [comment]
@larshesel bug identified, working on a fix

**Comment by Fettuccine-Alfredo** [comment]
The crash has gone away, but the vmq_bridge no longer attempts to send the message to AWS IoT:

01:26:48.679 [warning] dropped message {deliver,0,undefined,{vmq_msg,<<70,185,60,216,186,180,209,154,199,73,165,184,90,181,145,230>>,[<<"test">>],<<"test2">>,false,false,0,[],false,prefer_local,#{},undefined}} for plugin vmq_bridge

**Comment by larshesel** [comment]
Hi @Fettuccine-Alfredo I think this is due to an otherwise unrelated refactoring I was doing - I'll investigate and get back later today. Sorry for the inconvenience.

**Comment by larshesel** [comment]
Hi @Fettuccine-Alfredo I created a PR (#1087) to address this problem - it's in review now.

**Comment by larshesel** [comment]
Hi @Fettuccine-Alfredo the PR #1087 was merged, it would be great if you could retry the bridge and report if it works! Thanks!

**Comment by Fettuccine-Alfredo** [comment]
Seems to be working now.

**Comment by larshesel** [comment]
Great! thanks for the feedback!

**Comment by saqib-cielo** [comment]
Need to use this $aws/things/+ topic i.e `vmq_bridge.ssl.br0.topic.1 = $aws/things/+ both 0`, but couldn't able to publish message with a topic prefix as '$', please guide.

**Comment by ioolkos** [comment]
@saqib-cielo VerneMQ does not allow PUBLISHS to topics starting with '$'. Context:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718108

**Comment by ioolkos** [comment]
Look whether you find a combination of topic filter, remote prefix, local prefix that allows you to publish out messages on $aws/ in the bridge

**Comment by saqib-cielo** [comment]
I tried one mentioned in the documentation, didn't work either i.e 
`pattern[wildcard topic] direction[in|out|both] Qos[0|1|2] local_prefix remote_prefix`
`$aws/things/+ both 0 $aws/things/ $aws/things/`

**Comment by saqib-cielo** [comment]
@ioolkos same case working with Mosquitto as bridge with is config
`topic => both 0  $aws/things/ $aws/things`

**Comment by ioolkos** [comment]
Yes, Mosquitto allows publishing to $ topics. Verne does not.

This is about the out direction, for which you need to subscribe to a topic without $, and then prefix it.

**Comment by saqib-cielo** [comment]
@ioolkos like this 
`vmq_bridge.ssl.br0.topic.1 = $aws/things/+ in 0 
vmq_bridge.ssl.br0.topic.2 = aws/things/+ out 0 aws/things/ $aws/things/
`

**Comment by saqib-cielo** [comment]
@ioolkos But devices/apps will publish messages to bridge this $aws/things/+ topic, will AWS Iot broker receive message with above configs? 

Sorry to bothering you that much.
