### ISSUE TITLE
vmq-passwd -U command does not take colon in password

### ISSUE THREAD

**Issue by vnejindal** [vernemq/vernemq#1086]
### Environment

- VerneMQ Version: 1.6.2
- OS: Ubuntu 16
- Erlang/OTP version (if building from source): NA
- VerneMQ configuration (vernemq.conf) or the changes from the default: File Auth enabled
- Cluster size/standalone: Standalone

### Expected behavior

When ':' colon character is specified in password file and vmq-passwd -U option is used, then authentication does not work. If same password is entered using vmq-passwd -c option, it works. 

Following are the traces: 
$ cat vmq.passwd
user1::password

$ vim vmq.passwd
$ cat vmq.passwd
user1::password
$ vmq-passwd -U vmq.passwd
$ cat vmq.passwd
user1:$6$JvCpgOIadlgYwVGl$LIw2ZiZvVZcf83cmzmzp8z1JwoUz6vkNBLOn48YUXk6uTKS+epqTCHzq0eng4Xk7SLmwFkAVH+i4PYIPPTI1mw==
$ sudo cp vmq.passwd /etc/vernemq/vmq.passwd
$ sudo vernemq stop
ok
$ sudo vernemq start

$ ./mosquitto_sub.exe -d -h <broker_ip> -p 1883 -u user1 -P :password -t '/hello'
Connection Refused: bad user name or password.
Connection Refused: bad user name or password.

vernemq logs: 
2019-02-22 10:28:58.428 [warning] <0.1422.0>@vmq_mqtt_fsm:check_user:542 can't authenticate client {[],<<"mosqsub|36484-DESKTOP-Q">>} due to
                              invalid_credentials

### Actual behaviour
The behavior should be consistent with both vmq-passwd options (-c and -U), i.e. ':' colon character should be allowed in password field.

**Comment by larshesel** [comment]
I quickly looked into this and this and the problems seems to be that `strtok` is used to scan the password entries for `:`s: https://github.com/vernemq/vernemq/blob/master/apps/vmq_passwd/c_src/vmq_passwd.c#L205

In the first call to `strtok` the username is retrieved, the second time for retrieving the password the empty string is returned. I'm sure we could work around this by using something else than `strtok`, but do we want to or should we simply document that updating files with `:` in the password doesn't work (exactly as we have with usernames)? What do you think @dergraf ?

**Comment by vnejindal** [comment]
But password as empty string will open a authentication security hole if it allows any password for that user.

**Comment by larshesel** [comment]
As I understand it the problem is that if one uses a `:` in the plaintext password and upgrades the password file, then the password hash becomes whatever is between the username password `:` delimiter on the `:` in the password - and if `:` is the first character of the password the resulting password is the empty string - but it doesn't mean that any password is accepted.

Anyway, we're considering what to do about this.

**Comment by larshesel** [comment]
I don't think we'll spend time trying to improve `vmq-passwd -U` but will rather deprecate that feature and remove it completely in VerneMQ 2.0 - I'll add a note in the docs about this pitfall.

**Comment by vnejindal** [comment]
Does 'vmq-passwd -c' is removed  as well in 2.0? We are using this feature to add/edit passwords at run-time.

**Comment by larshesel** [comment]
`vmq-passwd -c` will remain.
