### ISSUE TITLE
Client doesn't receive messages while in cluster under load (or takes over 2 mins), does receive all messages under load on single node

### ISSUE THREAD

**Issue by mikestov** [vernemq/vernemq#1090]
### Environment

- VerneMQ Version: 1.7.0
- OS: Kubernetes Docker using Azure AKS 16CPU/64GB machines (other services on them too)
- Erlang/OTP version (if building from source): Using docker image defaults
- VerneMQ configuration (vernemq.conf) or the changes from the default

        - name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
          value: "0"
        - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
          value: "-1"
        - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
          value: "-1"

- Cluster size/standalone:

3 Brokers

### Expected behavior

Messages are all received while clustered (QOS1)

### Actual behaviour

This may be similar to this issue: https://github.com/vernemq/vernemq/issues/919

I'm doing some load testing of our VMQ in clustered mode (all QOS1 messages) and I'm running into a problem. When the test hits around 30k connected clients, things start breaking down badly and response times go insane and messages start getting "lost" or delayed over 2 minutes. Each client is sending about 4 messages every 60 seconds and receiving a reply on a subscription topic unique to that client, so around 4k messages a sec total ingress/egress. I see response times go crazy and some, but not all, messages get "lost" (or delayed beyond 2 minutes since thats my timeout for waiting on a message). The following also starts showing up in the VerneMQ logs:

02:35:33.219 [info] monitor got {suppressed,port_events,80}
02:35:33.247 [info] monitor busy_dist_port <0.28538.78> [{initial_call,{erlang,apply,2}},{almost_current_function,{erlang,bif_return_trap,2}},{message_queue_len,0}] {#Port<0.21>,unknown}
02:35:34.238 [info] monitor got {suppressed,port_events,9}
02:36:05.203 [info] monitor busy_dist_port <0.225.0> [{name,plumtree_broadcast},{initial_call,{plumtree_broadcast,init,1}},{almost_current_function,{erlang,bif_return_trap,2}},{message_queue_len,244}] {#Port<0.21>,unknown}
02:36:05.286 [info] monitor busy_dist_port <0.320.0> [{name,vmq_reg_sync},{initial_call,{vmq_reg_sync,init,1}},{almost_current_function,{erlang,bif_return_trap,2}},{message_queue_len,0}] {#Port<0.21>,unknown}
02:36:06.216 [info] monitor got {suppressed,port_events,37}
02:37:11.238 [warning] Broadcast overloaded, 918ms mailbox traversal, schedule next lazy broadcast in 55059ms, the min interval is 10000ms

It seems when I start seeing messages like these is when things get really bad and break down. The cpu use is nowhere near 100% for each worker node and each VMQ broker has 6GB of ram allocated. The odd thing is when I use a single VMQ broker, it never loses messages. I can't use a single broker though since our target is 100k connected devices with around 50k msg/sec total thruput and I don't think we can achieve that with just one.

My gut feeling is it has to do something with intra-broker communication, but I'm not really sure what to tweak to get it to behave. The next thing I was going to try was to spin up 6 brokers and see what happens. Also, the connections to the broker from the client are websockets+ssl, not sure if that affects anything. Let me know what more I can provide or any things I can try.  Thanks!

**Comment by dergraf** [comment]
I can't analyze the full issue here, as this is what our commercial services are made for. Please feel free to also get in touch with others from the community on our Slack channel.

My initial feeling is that VerneMQ isn't using all available CPU cores, and therefore can't handle the load, especially the connection setup rate. We've heard of a bug in the Docker image that it isn't cgroups aware and therefore VerneMQ isn't using all the provided CPU cores. Additionally TLS (if terminated directly in VerneMQ) isn't very performant, so this could be another performance hog.

I hope this helps.

**Comment by mikestov** [comment]
Thanks for the reply. I don't think I can proceed with the commercial service since this is a pretty big failure of the product and completely contradicts VerneMQ's front page of a million connections and "This enables VerneMQ to scale horizontally and vertically by fully utilizing multicore architectures." I will close out this ticket and evaluate other products.

**Comment by ioolkos** [comment]
@mikestov thanks for the effort you put in and thanks for your feedback (sorry to hear). 

When doing a loadtest you are testing your full stack, not just VerneMQ. It's hard to spot within a second where the problem lies, there can be quite some work required to set up all properly. That's what @dergraf meant.

I acknowledge your frustration and effort. I'm not sure what we as open source implementors and maintainers can do. Let me know if you have an idea. What we're pretty sure about is that this is not about VerneMQ product quality :)

@ anyone with ideas: feel free to chime in

**Comment by richard-scott** [comment]
Don't know if you've seen this great [video](https://youtu.be/gaq2Jmjrugg?t=1252) about VerneMQ usage. They say they had issues with Erlang/OTP Scheduler not knowing about cgroups and detecting an incorrect number of CPU's.
