### ISSUE TITLE
Check TLS Certificate Before Starting Secure Listeners

### ISSUE THREAD

**Issue by sleman** [vernemq/vernemq#1096]
I was setting up vernemq for the first time, generated letsencrypt certificates, updated vernemq.conf file, however could not connect over tcp ssl or wss listeners. I checked the vernemq logs and there were no errors. It turns out to be a simple permission issues with the certificates where the `vernemq` user could not read ther certificates. Was surprised that there was no check or errors that certificates were not readable. Certificate in conf were all symlinks so maybe that's why error was not caught?

### Environment

- VerneMQ Version: 1.7.1
- OS: Centos 7

### Expected behavior

Application should check if certificate files are readable before starting secure listeners.

### Actual behaviour

ssl and wss listeners start and do not log any errors

**Comment by larshesel** [comment]
Hi @sleman thanks for reporting. We're aware of the issue and it has already been reported before, see #849 - unfortunately we haven't had time to prioritize this yet. I'll close this as a duplicate.
