### ISSUE TITLE
VerneMQ fails to deliver a message sent by MQTT v5 publisher

### ISSUE THREAD

**Issue by manifest** [vernemq/vernemq#1101]
VerneMQ fails to deliver a message sent by MQTT v5 publisher.

### Environment

- VerneMQ Version: 1.7.1
- OS: macOS

### Expected behavior

A message is delivered to MQTT v5 subscriber.

### Actual behaviour

Client subscribes and send a message
```erlang
1> {ok, C} = emqx_client:start_link([{proto_ver, v5}, {host, {192,168,99,100}}, {port, 1883}, {client_id, <<"v1.mqtt5/agents/test-emqx-1.john-doe.usr.example.net">>}]),
1> emqx_client:connect(C),
1> emqx_client:subscribe(C, <<"foo">>, qos1).
{ok,#{},[1]}
2> emqx_client:publish(C, <<"foo">>, <<"bar">>).
ok
** exception error: {shutdown,tcp_closed}
```

VerneMQ Log
```bash
2019-03-04 19:39:25.469 [info] <0.630.0> Agent = 'test-emqx-1.john-doe.usr.example.net' connected: protocol = 'mqtt5', mode = 'default'
2019-03-04 19:39:25.472 [info] <0.630.0> Agent = 'test-emqx-1.john-doe.usr.example.net' subscribed: protocol = 'mqtt5', mode = 'default', topics = [{[<<"foo">>],{1,#{no_local => false,rap => false,retain_handling => send_retain}}}]
2019-03-04 19:39:29.916 [error] <0.630.0>@vmq_parser_mqtt5:enc_properties:591 CRASH REPORT Process <0.630.0> with 0 neighbours crashed with reason: no function clause matching vmq_parser_mqtt5:enc_properties([{p_user_property,[]}]) line 591
2019-03-04 19:39:29.921 [error] <0.630.0>@vmq_parser_mqtt5:enc_properties:591 Ranch listener {{0,0,0,0},1883} terminated with reason: no function clause matching vmq_parser_mqtt5:enc_properties([{p_user_property,[]}]) line 591
```

**Comment by larshesel** [comment]
Thanks for reporting. Could you include the report from the crash.log file as well?

**Comment by larshesel** [comment]
I wonder, is there a plugin involved which manipulate the user property along the way? In the parser I see we wrote a specific check that there is at least one entry in the user property and otherwise we just let it crash: https://github.com/vernemq/vernemq/blob/master/apps/vmq_commons/src/vmq_parser_mqtt5.erl#L647 which I think is correct according to the spec. So I was thinking maybe a map `#{p_user_property => []}` is returned from a plugin hook? I suppose we should handle that internally by removing the user property completely before handing it to the parser (or document that the list has to be non-empty).

**Comment by manifest** [comment]
@larshesel Yes, I'm using `#{user_property => []}` modifier from the plugin. It should be acceptable. Otherwise, there won't be any way to reset the user properties.

**Comment by manifest** [comment]
Maybe, it's a question to modifier format itself. I mean if we were using `#{properties => ...}` instead of `#{user_property => ...}` we would have set or erased any property including `user_property`, `correlation_data`, etc.

**Comment by manifest** [comment]
Do you still need a `crash.log`? It seems that we already know the reason.

**Comment by larshesel** [comment]
> It should be acceptable. Otherwise, there won't be any way to reset the user properties.

yep - forgot about that case



> I mean if we were using `#{properties => ...}` instead of `#{user_property => ...}` we would have set or erased any property including `user_property`, `correlation_data`, etc.

Good point, I think we did something like that when we started out but it felt a bit too nested... it would be quite a large change to the MQTT 5.0 hooks at this point, though (even though they are still in Beta), will have to think a bit about it.

For now I think we'll just handle the case where the list is empty.



> Do you still need a `crash.log`? It seems that we already know the reason.

no crash log needed, thanks!

**Comment by larshesel** [comment]
> I mean if we were using `#{properties => ...}` instead of `#{user_property => ...}` we would have set or erased any property including `user_property`, `correlation_data`, etc.

I of course later realized that this is an issue not just for user properties, the current design makes it impossible to drop properties in general. So I think we have to change it to sth like `#{properties => #{...}}`  instead of embedding them directly in the returned modifier map. For some reason dropping modifiers was never on our radar, so it's great you pointed it out and uncovered this problem before we went out of beta! We'll hopefuilly make an update one of the next days with this fixed. Thanks for bringing this to our attention!

**Comment by manifest** [comment]
Great, thanks.

**Comment by larshesel** [comment]
Hi @manifest 

I've created a first PR for the change, see https://github.com/vernemq/vernemq/pull/1104

I need to go over it again and check if I forgot something - but the changes so far are:

- The MQTT 5.0 plugin hooks have been updated so:
  - The `Payload` and `Properties` arguments to the `on_deliver_m5` hook have
    been swapped to be consistent with all the other `_m5` hooks.
  - property modifiers are now using the same names as the properties in the
    incoming properties, for example the `user_property` is now
    `p_user_property`.
  - property modifiers have been moved into a `property` modifier map. So for
    example instead of returning `{ok, #{user_property => ...}}` one now returns
    `{ok, #{property => #{user_property => ...}}}`. This change makes it
    possible to omit enables the removal of properties from a plugin hook.

See also the changes to the hook specs in the pr vernemq/vernemq_dev#11

How does this look to you?

**Comment by manifest** [comment]
@larshesel  Looks good to me. Thanks!

As soon as it gets to master, it will be accessible from `erlio/docker-vernemq:latest-alpine`, right?

**Comment by larshesel** [comment]
I'm actually not completely sure how that works these days - perhaps @dergraf can answer that?

**Comment by larshesel** [comment]
This was just merged to master. Regarding the docker image then we do not rebuild the docker images on each commit, only on tags.

**Comment by manifest** [comment]
@larshesel Any plans on release in the near future?

**Comment by larshesel** [comment]
We haven't planned one at the moment. Perhaps within the next weeks.
