### ISSUE TITLE
VerneMQ fails to establish MQTT5 connection over WebSockets

### ISSUE THREAD

**Issue by manifest** [vernemq/vernemq#1103]
VerneMQ closes connection for WebSocket clients using MQTT v5. The `Error: Connection refused: Unsupported Protocol Version` is returned while v5 support is enabled for the broker.

1. MQTT v5 over WebSockets – Connection closed with "Unsupported Protocol Version" error
```js
let mqtt = require('mqtt')
let client  = mqtt.connect(
  'ws://localhost:8080/mqtt',
  {clientId: 'test', protocolVersion: 5}
)
```
```js
client.on('close', function (err) {
  console.log(`close = ${err}`)
})

client.on('error', function (err) {
  console.log(`error = ${err}`)
})

client.on('connect', function () {
  client.subscribe('foo', function (err) {
    console.log(`subscribed to 'foo' topic...`)
  })
})
 
client.on('message', function (topic, message) {
  console.log(`topic = ${topic.toString()}, message = ${message.toString()}`)
})
```
```
Error: Connection refused: Unsupported Protocol Version
```

2. MQTT v5 – Works
```js
let mqtt = require('mqtt')
let client  = mqtt.connect(
  'mqtt://localhost:1883/mqtt',
  {clientId: 'test', protocolVersion: 5}
)
```

3. MQTT v4 over WebSockets – Works
```js
let mqtt = require('mqtt')
let client  = mqtt.connect(
  'ws://localhost:8080/mqtt',
  {clientId: 'test', protocolVersion: 4}
)
```

### Environment

- VerneMQ Version: 1.7.1
- OS: macOS, Linux
- VerneMQ configuration (vernemq.conf) or the changes from the default
```bash
listener.tcp.allowed_protocol_versions = 3,4,5
```

### Expected behavior

The connection is established.

### Actual behaviour

The connection is closed.

**Comment by larshesel** [comment]
Hi, 

I think your config `listener.tcp.allowed_protocol_versions = 3,4,5` should be `listener.ws.allowed_protocol_versions = 3,4,5` instead (or a line like that should be added)

**Comment by manifest** [comment]
Yes, that is the reason. Thanks!
