### ISSUE TITLE
Add VerneMQ to the list of software exposing Prometheus metrics

### ISSUE THREAD

**Issue by francois-travais** [vernemq/vernemq#1113]
Prometheus keeps track of software exposing Prometheus metrics : https://prometheus.io/docs/instrumenting/exporters/#software-exposing-prometheus-metrics. It would be great to see VerneMQ in the list.

**Comment by larshesel** [comment]
Great idea. Shall I create a PR or are you already on it?

**Comment by francois-travais** [comment]
I just noticed VerneMQ isn't in the list, I leave you to the rest.

**Comment by larshesel** [comment]
Done: https://github.com/prometheus/docs/pull/1307
