### ISSUE TITLE
ernemq on RaspberryPi Unable to copy from /home/pi/vernemq/_build/default/bin/cuttlefish to /home/pi/vernemq/_build/rpi32/rel/vernemq/erts-9.2/bin/cuttlefish because of {copy_failed,enoent}

### ISSUE THREAD

**Issue by agenteDserrano** [vernemq/vernemq#1115]
- VerneMQ Version: not shure I install with this command: 
time sh -c "$(curl -sSL https://raw.githubusercontent.com/suiluj/pi-adhoc-mqtt-cluster/master/install_scripts/vernemqinstall.txt)"

- OS: raspbedian 4.14.98-v7+

Try to isntall on raspberry using command: 
time sh -c "$(curl -sSL https://raw.githubusercontent.com/suiluj/pi-adhoc-mqtt-cluster/master/install_scripts/vernemqinstall.txt)"

Install fail with:
===> Unable to copy from /home/pi/vernemq/_build/default/bin/cuttlefish to /home/pi/vernemq/_build/rpi32/rel/vernemq/erts-9.2/bin/cuttlefish because of {copy_failed,enoent}

Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 127

**Comment by larshesel** [comment]
Hi, 

please try to simple clone and do a `make rpi32` on the rpi. The recipe in that script is old.

Good luck!
