### ISSUE TITLE
Allow auth_on_register hook with enabled anonymous 

### ISSUE THREAD

**Issue by vytasmk** [vernemq/vernemq#1116]
### Environment

- VerneMQ Version: 1.7.1
- OS: Docker `erlio/docker-vernemq:1.7.1-1-alpine`

### Expected behavior

Call auth_on_register hook with `allow_anonymous=on`

### Introduction

I am trying to migrate old project from Mosquitto broker and found that VerneMQ almost perfectly fits our needs and has perfect flexibility to use webhooks, LUA plugins etc. Easy to start and configure.  But there is one "but". 

The project that we support was started 4-5 years ago and now has lots (few thousands) of devices in the field all over the world. Devices communicate with central controller using MQTT protocol. But communication needs both methods: anonymous and normal username/password authentication. When users configure those devices to connect to our controller they set URL and account ID then device connects anonymously to MQTT and posts to one topic, server responses with some information including CA certificate, then device connects again using SSL connection anonymously. After connection is made it posts to another topic so that system puts that device in status  "waiting confirmation". Customers in our system admin panel confirms that device and assigns it to some group that has specific set of configuration. When device gets assigned it receives specific configuration and username/password for MQTT authentication. After that device applies configuration reboots and connects to MQTT broker using those credentials and starts normal communication to specified topics with periodic statistics etc. 

We can't change that communication quickly as there are lots of devices with different firmware and that is not easy. We are starting to work on the new system version, but that will take time to. So currently is not possible to set username/password to those devices.

### Requested behavior

If the `auth_on_register` hook can be enabled with anonymous clients that will give more flexibility. For example we can filter "anonymous" by clientID as our devices have simple pattern for it (MAC address without colons). So if that is anonymous connection with such clientID pattern we allow to connect and sub/pub only to few topics. 

Even more another enhancement could be to have some flag to identify if client connected using SSL or nonSSL connection but that should be available on other `auth_on_` hooks. Also it should work when using proxy. 

I do not know the reason why that hook can not be used with anonymous connections may be it breake some logic so then there could be workaround like setting default username for such anonymous users and that name could be configured in config file let say `anonymous_set_username=anonymous` and in plugins I will know that this username is for anonymous connections...

Sorry for long story, I hope that this could be implemented and we can start using VerneMQ broker in our system. Btw. I have read in some forums that people also are looking for similar functionality. Thanks!

**Comment by vytasmk** [comment]
OK, I think I was not paying enough with this broker. Also I think there is missing some notes in [Session Lifecycle documentation](https://vernemq.com/docs/plugindevelopment/sessionlifecycle.html) about the `allow_anonymous=on` and how it changes the flow. 

I have today set `allow_anonymous=off` and got `auth_on_register` hook called even when client does not provide username and/or password. I have also disabled `plugins.vmq_passwd=off` and 
`plugins.vmq_acl=off` and using Lua script as a plugin. That is exactly what I need... :)  

So with `allow_anonymous=off` client session will go thru `auth_on_register` state while `allow_anonymous=on` will just skip it. In both cases connecting client can have empty credentials (username/password) and here I was thinking that VerneMQ broker will reject immediately clients with empty username/password when `allow_anonymous=off`. I have tried one broker that did exactly that so i was thinking that VerneMQ is behaving the same.

So I think small updade to the documentation will help a lot to not get in to such situation.

Regarding the client connection type (SSL or nonSSL) flag it would be nice to have including proxy/load balancer support but may be this should go in to separate issue/request.

**Comment by larshesel** [comment]
Hi @vytasmk great you figured it out. Regarding being able to distinguish SSL and non-SSL there is a small trick in that you can start listeners on different mountpoints which is then part of the subscriber-id (mountpoint + client-id) in the plugin callback hooks. It is possible to rewrite the mountpoints back to the default in the `auth_on_register` so those clients can still communicate on the same topic trees (here's a discussion about mounpoints: https://github.com/vernemq/vernemq/issues/533).

Regarding the documentation we'd be happy to accept pull requests. The documentation is open source and hosted in this repo: https://github.com/vernemq/vmq-docs

**Comment by vytasmk** [comment]
@larshesel thank You!

**Comment by vytasmk** [comment]
Just if someone else willbe looking this is direct link to the documentation where it is mentioned about `allow_anonymous` behavior

https://docs.vernemq.com/configuring-vernemq/introduction
