### ISSUE TITLE
怎样挂载etc?

### ISSUE THREAD

**Issue by myVictor** [vernemq/vernemq#1118]
挂载 /vernemq/etc 时，启动不了。只生成了一个文件，其他文件都没出来，如：vm.args
![image](https://user-images.githubusercontent.com/7285684/54694359-148ad880-4b63-11e9-85a8-938a14bee750.png)
容器也起步来。

![image](https://user-images.githubusercontent.com/7285684/54694383-1fde0400-4b63-11e9-9ea8-6cdcafdaca73.png)

**Comment by myVictor** [comment]
docker run -d -v /e/vernemq/node1-1/data:/vernemq/data -v /e/vernemq/node1-1/log:/vernemq/log -v /e/vernemq/node1-1/etc:/vernemq/etc -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" -p 1883:1883 -p 8080:8080 -p 8888:8888 --name vernemq1 erlio/docker-vernemq

**Comment by myVictor** [comment]
忘记贴命令了
docker run -d -v /e/vernemq/node1-1/data:/vernemq/data -v /e/vernemq/node1-1/log:/vernemq/log -v /e/vernemq/node1-1/etc:/vernemq/etc -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" -p 1883:1883 -p 8080:8080 -p 8888:8888 --name vernemq1 erlio/docker-vernemq

**Comment by larshesel** [comment]
Hi there,

I'm afraid none of us understand chinese. Can I ask you to create a new issue and fill in the template there in english? Thanks.
