### ISSUE TITLE
VerneMQ crash when using publish_acl modifiers for MQTT 5 packets

### ISSUE THREAD

**Issue by m-naruniec** [vernemq/vernemq#1123]
Hello, this is my first post here, I will be very thankful for any help.
I am trying to use Redis-based auth to modify message topics in MQTT5 messages, but I am getting an error. The same config works correct with other protocol versions. I have not found any information that modifiers are unsupported for protocol version 5. I was going to add user properties, but now I'm having a problem with basic modifiers from docs.

The error looks like a pattern matching failure which should not occur in a production code, but I do not know either Erlang language or Verne sources, so I decided to ask for some help here.
I have tried using 1.7.0 and 1.7.1-1 Docker images and I have modified 1.7.1-1 Dockerfile to compile sources from master branch. The error reproduced in every container. Modifying payload instead of topic gives analogous crash reports.

### Environment

- VerneMQ Version: erlio/docker-vernemq:{1.7.0,1.7.1-1,master-SNAPSHOT(custom)}
- OS: Linux 4.9.0-7-amd64 (Debian 4.9.110-3)
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default:

Dockerfile config lines:
```
ENV DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS 3,4,5
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY on
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD off
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_ACL off
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED on
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST 172.17.0.1
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PORT 6379
```
Redis rule insertion command:
```
SET "[\"\",\"publisher\",\"publisher\"]" "{\"passhash\":\"<bcrypt_passhash>\",\"publish_acl\":[{\"pattern\":\"publisher\", \"modifiers\":{\"topic\":\"new/topic\"}}]}"
```
- Cluster size/standalone: standalone

### Expected behavior

MQTT5 message from authenticated user "publisher" on topic "publisher" should be redirected to topic "new/topic".

### Actual behaviour

The message is not published to subscribers at all, this output is visible in docker logs.

>=CRASH REPORT==== 22-Mar-2019::14:06:37.263378 ===                                                                                                                                                          
  crasher:                                                                                                                                                                                                  
    initial call: vmq_ranch:init/5                                                                                                                                                                          
    pid: <0.638.0>                                                                                                                                                                                          
    registered_name: []
    exception error: no case clause matching
                     {ok,[{topic,[<<"new">>,<<"topic">>]}]}
      in function  vmq_mqtt5_fsm:auth_on_publish/4 (/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl, line 1139)
      in call from vmq_mqtt5_fsm:maybe_apply_topic_alias_in/5 (/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl, line 990)
      in call from vmq_mqtt5_fsm:dispatch_publish_qos1/4 (/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl, line 1254)
      in call from vmq_mqtt5_fsm:connected/2 (/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl, line 411)
      in call from vmq_mqtt5_fsm:in/3 (/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl, line 237)
      in call from vmq_mqtt5_fsm:data_in/3 (/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl, line 211)
      in call from vmq_ranch:handle_message/2 (/vernemq-build/_build/default/lib/vmq_server/src/vmq_ranch.erl, line 174)
      in call from vmq_ranch:loop_/1 (/vernemq-build/_build/default/lib/vmq_server/src/vmq_ranch.erl, line 117)
    ancestors: [<0.329.0>,<0.328.0>,ranch_sup,<0.124.0>]
    message_queue_len: 0
    messages: []
    links: [<0.329.0>,#Port<0.57>]
    dictionary: [{{mqtt5_connack_sent,success},
                   #Ref<0.2845207287.2457993218.147866>},
                  {mqtt5_connect_received,
                      #Ref<0.2845207287.2457993218.147951>},
                  {bytes_sent,#Ref<0.2845207287.2457993218.147985>},
                  {bytes_received,#Ref<0.2845207287.2457993218.147986>},
                  {mqtt5_publish_received,
                      #Ref<0.2845207287.2457993218.147939>},
                  {request_problem_information,true},
                  {max_outgoing_msg_size,undefined},
                  {max_incoming_msg_size,0},
                  {guid,
                      {{'VerneMQ@172.17.0.3',<0.638.0>,{1553,263597,263282}},
                       0}},
                  {rand_seed,
                      {#{jump => #Fun<rand.16.10897371>,
                         max => 288230376151711743,
                         next => #Fun<rand.15.10897371>,type => exsplus},
                       [70898588958660044|73673029741302675]}},
                  {socket_open,#Ref<0.2845207287.2457993218.147989>}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 5607
  neighbours:

> =ERROR REPORT==== 22-Mar-2019::14:06:37.264773 ===
Ranch listener {{172,17,0,3},1883} had connection process started with vmq_ranch:start_link/4 at <0.638.0> exit with reason: {{case_clause,{ok,[{topic,[<<"new">>,<<"topic">>]}]}},[{vmq_mqtt5_fsm,auth_on_publish,4,[{file,"/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,1139}]},{vmq_mqtt5_fsm,maybe_apply_topic_alias_in,5,[{file,"/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,990}]},{vmq_mqtt5_fsm,dispatch_publish_qos1,4,[{file,"/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,1254}]},{vmq_mqtt5_fsm,connected,2,[{file,"/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,411}]},{vmq_mqtt5_fsm,in,3,[{file,"/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,237}]},{vmq_mqtt5_fsm,data_in,3,[{file,"/vernemq-build/_build/default/lib/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,211}]},{vmq_ranch,handle_message,2,[{file,"/vernemq-build/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,174}]},{vmq_ranch,loop_,1,[{file,"/vernemq-build/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,117}]}]}

> 14:06:37.263 [error] CRASH REPORT Process <0.638.0> with 0 neighbours crashed with reason: no case clause matching {ok,[{topic,[<<"new">>,<<"topic">>]}]} in vmq_mqtt5_fsm:auth_on_publish/4 line 1139
> 14:06:37.266 [error] Ranch listener {{172,17,0,3},1883} terminated with reason: no case clause matching {ok,[{topic,[<<"new">>,<<"topic">>]}]} in vmq_mqtt5_fsm:auth_on_publish/4 line 1139

**Comment by larshesel** [comment]
Hi @m-naruniec 

Thanks for opening the issue. I'll look into it immediately as we're anyway working on giving the MQTT 5.0 support in the `vmq_diversity` plugin an overhaul. From your description it looks like a general oversight regarding modifiers in the MQTT 5 state machine.

**Comment by larshesel** [comment]
I see two separate issues here:

1. Ensure that we can use the documented ACL modifiers from the MQTT 5.0 client sessions
2. Support MQTT 5.0 properties in the ACL modifiers (none are explicitly supported at the moment)

The first step will be to handle 1 which we're working on now.

**Comment by m-naruniec** [comment]
Hello, thank you for looking into the issue so quickly!

I have follow up questions related to my use case.
I am trying to enrich inbound MQTT5 messages with some information depending on the topic, at the same time preserving (almost) everything from original message. In particular, I would like to change topic and attach old one and the username to the message.
I would also like to achieve it configuratively, not programmatically, and the ACL modifiers look very promising.
As I understand, by using a database the payload can only be substituted and not extended.
I know I could translate topic to something like newtopic/oldtopic/username, but this not clean enough for my usage.
User properties seem perfect for this kind of task, but the most desirable effect would be to only attach new properties and leave original ones intact (except maybe for the overwritten ones).

Is it something that's going to be implemented for Verne MQTT5 support? Or would you be able to suggest alternative solution?

Appreciate the feedback.

**Comment by larshesel** [comment]
> As I understand, by using a database the payload can only be substituted and not extended.
> I know I could translate topic to something like newtopic/oldtopic/username, but this not clean enough for my usage.

That is correct.



> User properties seem perfect for this kind of task, but the most desirable effect would be to only attach new properties and leave original ones intact (except maybe for the overwritten ones).

How to support and add MQTT 5.0 properties in the modifiers in the `vmq_diversity` plugin is still completely open - we try to create something which is simple and (relatively) easy to use - that sometimes means tradeoffs in terms of how flexible it is - so exactly how properties from modifiers should merge with properties from a published message is something we'd have to think about.

Another approach is to use the webhooks plugin which just got much better MQTT 5.0 support (merged to master last week), so maybe it would be interesting to check that out the endpoint handler from the test suite to get an overview: https://github.com/vernemq/vernemq/blob/master/apps/vmq_webhooks/test/webhooks_handler.erl (we still need to document the properties properly)
