### ISSUE TITLE
Write-protecting a single topic while keeping others read-write using ACL

### ISSUE THREAD

**Issue by ptesavol** [vernemq/vernemq#1126]
Hi

Is there a way of write-protecting a single topic while keeping all the others read-write using ACL? I tried this ACL:

topic #
topic read publishers/#

But I can still publish to topic "publishers/test".

**Comment by ioolkos** [comment]
It probably doesn't make sense to block publishs on a topic for *all* users. (no messages will ever arrive on those topics).

Still, yes, you're example should work, giving it a quick thought. @dergraf , @larshesel do you see anything I don't?

**Comment by ptesavol** [comment]
I am running VerneMq as a 2-node cluster, with one node that intranet users connect to, and another one that Internet users connect to. The ACL is from the Internet node, and the idea is that none of the users connecting to the Internet node should be able to publish to the "publishers/#" topics.

**Comment by larshesel** [comment]
That should be possible - note the ACL doesn't enable you to specify what you *cannot* do, only what is *allowed* and anything else isn't. So you should be able to achieve this if you have do not have a rule allowing publishing to `publisher/#` on the internet node but have that rule configured on the intranet node.
