### ISSUE TITLE
Proposal: ability to remove retained messages

### ISSUE THREAD

**Issue by Niek** [vernemq/vernemq#1127]
We have the ability to see & filter for retained messages with ``vmq-admin retain show``, but it doesn't seem to be possible to (selectively) remove certain retained messages. It would be great to have something like ``vmq-admin retain remove`` with the usual ``--topic`` and ``--payload`` flags.

**Comment by ioolkos** [comment]
thanks for the proposal @Niek!
A command like this could make sense as a convenience, I guess, although the standard way of deleting retained messages by sending an empty payload wouldn't do any less here. (look up the -n and -r options in `mosquitto_pub --help` on how to do that)
We'll see what to do about it.

**Comment by Niek** [comment]
Thanks! A quick workaround for now is: ``vernemq attach`` and ``ets:delete_all_objects(vmq_retain_srv).``

**Comment by mrm** [comment]
And to also remove the retained messages from disk storage (keep them removed after a restart):
```erlang
vmq_metadata:fold({vmq, retain},
  fun({Key, V}, _) ->
          case V =/= '$deleted' of
              true ->
                  vmq_metadata:delete({vmq, retain}, Key);
              _ ->
                  ok  
          end 
end, ok).
```

**Comment by LeeWong** [comment]
what release this enhancement might be in?

**Comment by quaddan** [comment]
Any news ?

**Comment by nate-thirdwave** [comment]
I believe this is currently available right now as `vmq-admin retain delete ...`

```
$ vmq-admin retain delete --help
Usage: vmq-admin retain delete

  Delete the retained MQTT message for a topic and mountpoint.

Default options:
  --mountpoint --topic

If --mountpoint is not set, the default empty mountpoint
is assumed.

  --topic
  --mountpoint
```
