### ISSUE TITLE
MQTT 5 sessions always have clean session flag on

### ISSUE THREAD

**Issue by m-naruniec** [vernemq/vernemq#1129]
Hello, I think I might have found another issue connected to the protocol version 5.

### Environment

- VerneMQ Version:
erlio/docker-vernemq:1.7.1-1
- OS: Linux 4.15.0-46-generic x86_64 (Ubuntu 18.04) 
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default
ENV DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS 3,4,5
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY on
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD off
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_ACL off
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED on
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST 172.17.0.1
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PORT 6379

- Cluster size/standalone: Standalone

### Expected behavior

MQTT 5 session should have a disabled clean start flag when when the flag is unset in CONNECT packet.

### Actual behaviour

Session has clean start on despite correct CONNECT packet with flag off. I tried both mosquitto_sub and own Paho-based tool. I checked the packet in Wireshark, so it's not the client's fault.
vmq-admin session show displays clean_session as true and it corresponds to the broker's behaviour.
Analogous packets for MQTT 3.1 and 3.1.1 work as intended.

**Comment by ioolkos** [comment]
Hello @m-naruniec 
can you make sure there is a correct understanding of the "clean start" feature as per: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901039
(clean start doesn't work exactly like the old clean session)

Does this explain the behaviour to you, or do you still think there's an issue?
/cc @larshesel

**Comment by m-naruniec** [comment]
Hello @ioolkos 

thank you very much for the answer. Although I didn't know that clean start works differently than clean session, I still think the behaviour of Verne is incorrect.
I connect to Verne from my custom client using recent version of Paho with MQTT 5 support and subscribe to # with qos 1. Clean start is off and I set manual acknowledgements to true not to send any PUBRECs.
Then I send a qos 1 message from other client to some topic and receive it in the first client.
Wireshark shows settings are consistent with packets - there is no ack, client id is present and clean start (or clean session, as Wireshark still calls it) is false.
When I disconnect from the server (without disconnect packet), the session is no longer visible in vmq-admin session show. After reconnection, session present flag is false and the message is not redelivered.

Is there some mistake in my experiment and understanding of the protocol, or is this a bug?
Looking forward to hearing from you.

**Comment by ioolkos** [comment]
Hi @m-naruniec thanks for further help & testing, much appreciated!

I'm still a little unclear what exactly is bothering you here. Where do you actually think the bug would be... in Session Present or Clean Start or QoS 1 or message redelivery?

**Comment by larshesel** [comment]
Hi @m-naruniec 

If you want an offline session in MQTT 5.0 you *must* set the session expiry interval property to something different than 0. See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901048. The clean start flag has nothing to do with if the session is persisted or not - only if an existing session is discarded or not - i.e., if the new clients should get a clean start.

So in MQTT 5.0 to emulate the clean session false behaviour from MQTT 3.1.1 you'd have to set clean start to false and set the session expiry interval to infinite (0xFFFFFFFF).

Hope his helps.

**Comment by m-naruniec** [comment]
Hello @larshesel 

than you very much for your answer.
You are right, lack of session expiry interval was the problem. I have wrongly assumed that default behaviour is to have infinite interval, and the actual description was in the property's section and not the clean start one.
I think Paho have a mistake in their documentation, but that is a different topic.

Thank you both for making it clear :)

**Comment by larshesel** [comment]
great you got it to work and thank for using VerneMQ. MQTT 5.0 is still new so any feedback is always appreciated.
