### ISSUE TITLE
due to keepalive expired

### ISSUE THREAD

**Issue by yama0615** [vernemq/vernemq#1132]
I keep getting the following logs for a client

client [warning] <>@vmq_mqtt_fsm:connected:420 client {[],<>>} with username <<"">> stopped due to keepalive expired

Is this due to configuration on my end or does the client for some reason just lose connection? How can I see what keeplive values each client is using when they connect

Thanks

**Comment by ioolkos** [comment]
Hi @yama0615 thanks, I think it's either the client dropping the connection or the client not honoring it's own keepalive window (ie not sending pings).
@larshesel can you think of a way to show the keepalive of a session? (I think it's not in the session command, see `vmq-admin session show --help`)

**Comment by larshesel** [comment]
> @larshesel can you think of a way to show the keepalive of a session?

No, the keepalive isn't exposed via the command line. The only way I know of seeing the keepalive is if a trace is active when the client connects, see: https://docs.vernemq.com/administration/tracing

> Is this due to configuration on my end or does the client for some reason just lose connection?

Hard to say - the only fact known at this point is that the client set some keepalive timeout but no keepalive PINGREQ was received before 1.5*keepalive time expired.
