### ISSUE TITLE
mqtt_connack_sent - Out of Date Prometheus Metric Docs

### ISSUE THREAD

**Issue by JohnCMcDonough** [vernemq/vernemq#1133]
### Environment

- VerneMQ Version: 1.7.1-1 (`vernemq version` returns empty)
- OS: 16.04.1-Ubuntu (Docker Container Base)

### Expected behavior

- The metrics match the docs: https://docs.vernemq.com/monitoring/introduction
- The dashboards we've tied into the following reported metrics are correct
   - mqtt_connack_accepted_sent
   - mqtt_connack_bad_credentials_sent
   - mqtt_connack_not_authorized_sent
   - mqtt_server_unavailable_sent
   - mqtt_connack_unacceptable_protocol_sent
   - mqtt_connack_identifier_rejected_sent

### Actual behaviour

- They don't match the docs
- The metrics we've tied our dashboards into always report 0.
- It looks like the metrics were changed to be labels on a single metric, called mqtt_connack_sent. I'm not sure if this was the intended behavior, and if the previously collected metrics were supposed to be updated as well as this new one, or if the intent was to replace the previously existing metrics.
- It looks like the same thing is true for `mqtt_puback_sent` and `mqtt_pubcomp_sent`. All the metrics have been condensed into a single metric. There's a ton of labels on it that we were unaware existed as they weren't documented.
- It would also be nice to have documentation around what each of the metrics mean, as we're just guessing right now.

**Comment by JohnCMcDonough** [comment]
Looking more into it, it seems like even the `mqtt_connack_sent` has two sets of labels, one used and one unused. The `return_code` labeled metrics seems to be returning correctly, but the `reason_code` labeled ones all seem to be returning 0.

**Comment by ioolkos** [comment]
@JohnCMcDonough thanks for reporting!
Just for reference: it's in the changelog of release 1.6: https://github.com/vernemq/vernemq/releases/tag/1.6.0

Maybe @larshesel can comment on the intended behaviour related to the switch to labels, and/or confirm there are possibly issues with the `reason_code`s returned for those metrics.
As a miminum, I guess the documentation needs some love & attention.

**Comment by JohnCMcDonough** [comment]
Thanks for the quick response @ioolkos! For now I'm rebuilding based on the `mqtt_connack_sent` with the `return_code` label. Let me know if I should be using something else though!

**Comment by larshesel** [comment]
Hi, 

The change with mapping the `mqtt_connack_xxxx_sent` to `mqtt_connack_sent` with labels happened in VerneMQ 1.6.0, as mentioned above. For MQTT 3.1.1 the they are mapped to `return_code` (as that's what they're called in that version) all the ones with `reason_code` are for MQTT v5.0.

We've completely forgotten to update the metrics in the docs and I'll do that in a short while. Notice that you can use `vmq-admin metrics show -d` to output all metrics with as short description about what they are about.

I've just updated the docs to mention the old metrics and the new labels as well as removed the list of metrics (as this will almost always be outdated).
