### ISSUE TITLE
Prefix prometheus metrics with vernemq_

### ISSUE THREAD

**Issue by francois-travais** [vernemq/vernemq#1134]
The convention for Prometheus metric is to prefix all metrics with the application name , e.g. `rabbitmq_queue_messages` or `grafana_stat_total_users`.

### Environment

- VerneMQ Version: 1.7.1-2-alpine

### Expected behavior

Have all metrics prefixed with `vernemq_`, like `vernemq_queue_messages_in`

### Actual behavior

Metrics don't have an explicit prefix, e.g. `queue_messages_in` or `bytes_received`

**Comment by larshesel** [comment]
Sounds like a good idea -  though I don't think it would be feasible to rename them at this point as that would break existing setups. Marked for 2.0

**Comment by larshesel** [comment]
Closing this until we start work on VerneMQ 2.0
