### ISSUE TITLE
Metrics do not expose clients sessions information 

### ISSUE THREAD

**Issue by francois-travais** [vernemq/vernemq#1135]
There are no metrics exposing client sessions information, there is no way to easily monitor the number of active sessions for example.

### Environment

- VerneMQ Version: 1.7.1-2-alpine

### Expected behavior

Have metrics exposing session information like `vmq-admin session show`.

### Actual behaviour

Sessions information is only available with `vmq-admin` command-line.

**Comment by larshesel** [comment]
You can do that with `socket_open - socket_close`

**Comment by francois-travais** [comment]
Yes that would be the trick for the number of sessions but it would be great to have more precises information like which client_id is in use and whether or not each is online.

**Comment by larshesel** [comment]
I don't think that's easy to express as metrics. You can use `vmq-admin session show` to query a lot of things about sessions (and online/offline status). See `vmq-admin session show --help`.
