### ISSUE TITLE
Mountpoint config lost

### ISSUE THREAD

**Issue by kellycampbell** [vernemq/vernemq#1136]
### Environment

- VerneMQ Version: erlio/docker-vernemq:1.7.1-2-alpine
- OS: Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64 (kubernetes 1.11.7)
- VerneMQ configuration (vernemq.conf) : see below
- Cluster size/standalone: 1

### Expected behavior

I configure a mountpoint on the ssl listener, but clients connecting to that listener don't have the mountpoint.

`cat /vernemq/etc/vernemq.conf | grep listener.ssl`: (not including ## commented lines)
```
listener.ssl.mountpoint=gw_secure
listener.ssl.default=0.0.0.0:8883
listener.ssl.keyfile=/ssl/key.pem
listener.ssl.require_certificate=on
listener.ssl.certfile=/ssl/cert.pem
listener.ssl.cafile=/ssl/ca_roots.pem
listener.ssl.max_connections=100000
listener.ssl.use_identity_as_username=on
```

### Actual behaviour

Looking at the generated config:
`cat /vernemq/data/generated.configs/app.2019.04.04.18.05.05.config`

```
      {listeners,
          [{mqtt,
               [{{{127,0,0,1},1883},
                 [{max_connections,10000},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {proxy_protocol,false},
                  {allowed_protocol_versions,[3,4,131]}]},
                {{{100,115,194,108},1883},
                 [{max_connections,10000},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {proxy_protocol,false},
                  {allowed_protocol_versions,[3,4,131]}]}]},
           {mqtts,
               [{{{0,0,0,0},8883},
                 [{max_connections,10000},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {cafile,"/ssl/ca_roots.pem"},
                  {depth,1},
                  {certfile,"/ssl/cert.pem"},
                  {keyfile,"/ssl/key.pem"},
                  {require_certificate,true},
                  {tls_version,'tlsv1.2'},
                  {use_identity_as_username,true},
                  {allowed_protocol_versions,[3,4,131]}]}]},
           {mqttws,
               [{{{100,115,194,108},8080},
                 [{max_connections,10000},
                  {nr_of_acceptors,10},
                  {mountpoint,[]},
                  {proxy_protocol,false},
                  {allowed_protocol_versions,[3,4,131]}]}]},
```

**Comment by ioolkos** [comment]
@kellycampbell thanks for documenting the issue!

Does `sudo vmq-admin listener show` the same information? Does any mountpoint show up when you configure the SSL listener options on a per listener level, instead of protocol level? (adding a listener name like in this pattern: `listener.ssl.my_listener.mountpoint=gw_secure` to *all* the SSL options?

I'll try to test it myself these days too.

**Comment by kellycampbell** [comment]
Making it a named listener does work as expected.

before:
|mqtts |running|    0.0.0.0    |8883 |          |  10000  |

after:
|mqtts |running|   0.0.0.0    |8883 |gw_secure | 100000  |

**Comment by larshesel** [comment]
Looks like a bug

**Comment by ioolkos** [comment]
Protocol level vs. listener level config:
Should we properly implement protocol level support, or complete take it away (and enforce named listener level configuration for everything)?

**Comment by larshesel** [comment]
I guess that's a consideration for VerneMQ 2.0 as we couldn't remove this functionality now (it works for other stuff, just not mountpoints for some reason). What would be the pros and cons of having it on the listener level configuration only?

**Comment by larshesel** [comment]
Hi, there's a PR for this issue over at #1189, it would be great if you could test if it solves your issue. Thanks.
