### ISSUE TITLE
Cannot configure ssl

### ISSUE THREAD

**Issue by tomasol** [vernemq/vernemq#1138]
### Environment

- VerneMQ Version: 1.7.0
- OS: centos 7.6
- vernemq.conf:
```
listener.ssl.foo = 0.0.0.0:8883
listener.ssl.cafile = /etc/ssl/certs/ca-bundle.crt
listener.ssl.certfile = /etc/letsencrypt/live/mydomain/fullchain.pem
listener.ssl.keyfile = /etc/letsencrypt/live/mydomain/privkey.pem
```
- standalone

### Issue
I try to configure vernemq with letsencrypt. After applying the configuration above, I observe that vernemq listens on 8883 however tls is not working:
```
openssl s_client -showcerts -connect myip:8883
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 289 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1554472864
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```
What strikes me as odd is that I don't see anything ssl related in the logs (console is set to debug), even if I change the configuration to point to non-existing pem files.
I have checked file permissions.  I am not using client certs.
Using mosquitto_sub just hangs after writing CONNECT.

**Comment by larshesel** [comment]
Hi

Unfortunately Erlang isn't very chatty about what goes on in its TLS stack.

Could you perhaps try like this:

```
listener.ssl.foo = 127.0.0.1:8883
listener.ssl.foo.cafile = ...
listener.ssl.foo.certfile = ...
listener.ssl.foo.keyfile = ...
```

so you specify the files on the specific listener?

**Comment by tomasol** [comment]
Hi,
I got it working with letsencrypt: it was a permission issue on a parent dir. With docker, setting these env.vars worked:
```
        - DOCKER_VERNEMQ_listener.ssl.default = 0.0.0.0:8883
        - DOCKER_VERNEMQ_listener.ssl.cafile = /etc/letsencrypt/live/mydomain/fullchain.pem
        - DOCKER_VERNEMQ_listener.ssl.certfile = /etc/letsencrypt/live/mydomain/cert.pem
        - DOCKER_VERNEMQ_listener.ssl.keyfile = /etc/letsencrypt/live/mydomain/privkey.pem
```

**Comment by himadrinath** [comment]
@tomasol what permission did u gave to the parent dir so that docker could read cert dir.
i am running with non root privilege. i added user to the docker ground also install letencrypt cert in my user account (not in root). still not able to access
