### ISSUE TITLE
Adding MFLN (Maximum Fragment Length Negotiation) extension

### ISSUE THREAD

**Issue by Niek** [vernemq/vernemq#1140]
TLS 1.2/RFC6066 includes the MFLN extension, which allows small-memory (IoT) clients to use smaller fragments for transmission. When Mosquitto is built against a recent OpenSSL version, it supports this out of the box. Since Vernemq has its own TLS implementation (CMIIW), this extension is not working.

Example:
```bash
$ testssl -S 127.0.0.1:8883 | grep extensions # vernemq server
 TLS extensions (standard)    "EC point formats/#11" "renegotiation info/#65281"
$ testssl -S 127.0.0.1:18883 | grep extensions # mosquitto pre-built binary
 TLS extensions (standard)    "renegotiation info/#65281" "EC point formats/#11" "session ticket/#35" "heartbeat/#15"
$ testssl -S 127.0.0.1:28883 | grep extensions # mosquitto built from source against OpenSSL 1.1
 TLS extensions (standard)    "renegotiation info/#65281" "EC point formats/#11" "session ticket/#35" "extended master secret/#23" "encrypt-then-mac/#22" "max fragment length/#1"
```
Would it be possible to add support for this?

**Comment by larshesel** [comment]
Hi @Niek 

VerneMQ has no TLS implementation, rather Erlang/OTP which VerneMQ is built upon has. So the question is if Erlang/OTP supports this already or will in the future. I tried googling for this `Erlang MFLN TLS support` but came up empty handed, I'm afraid. You could perhaps ask on the Erlang questions mailing list: http://erlang.org/mailman/listinfo/erlang-questions, usually they are quick to respond.

Alternatively you could terminate TLS in HAProxy or similar instead of in VerneMQ.

**Comment by Niek** [comment]
Ah, I see now. There is a patch for Erlang/OTP that adds something like this, but it was never accepted: https://github.com/rlipscombe/otp/commit/71c53d20191d3ddf43fc0aa87fabf5ac84ef70f3

I will be closing this issue now.

**Comment by ioolkos** [comment]
Ha, interesting, maybe we should inquire why that patch wasn't accepted back then. 
Thanks for digging this up, and thanks for documenting the HAProxy test!

**Comment by arihantdaga** [comment]
@Niek  Thank for sharing the Haproxy config. I had a doubt, will it work with any other broker also which does not support MFLN, i am using emqx (based on erlang too). I have haproxy setup too, but when i tested with testsh, i did not get max fragment length in output. 
Can you share something ? Am i missing something ?

**Comment by Niek** [comment]
@arihantdaga I think it's a bit out of the scope of this issue - but yes, you need to compile HAProxy against OpenSSL 1.1.1 or higher (released in Sep 2018), see https://github.com/openssl/openssl/commit/cf72c7579201086cee303eadcb60bd28eff78dd9
