### ISSUE TITLE
neighbours exited with reason: no match of right hand value {error,invalid_binary}

### ISSUE THREAD

**Issue by robie2011** [vernemq/vernemq#1143]
### Environment

- VerneMQ Version: 1.5.0
- OS: Docker Image `erlio/docker-vernemq`, Image-Id: `a6211e855667` (created 5 months before)
- Erlang/OTP version (if building from source):
- VerneMQ configuration: Only default configuration and using SSL Cert
- Cluster size/standalone: Standalone

### Expected behavior
- can start container after freeing up diskspace (hostsystem disk was full before)

### Actual behaviour
- container exit with same error even after restarting hostsystem

Disk on hostsystem was running out of space (other issues) therefore all containers on host system stopped working correctly. 

After freeing up diskspace tried to restart container but ran into same issue (see log below).

```
debian@docker01:~$ docker logs --tail 20 vernemq02
06:48:23.859 [error] CRASH REPORT Process <0.201.0> with 0 neighbours exited with reason: no match of right hand value {error,invalid_binary} in plumtree_peer_service_manager:maybe_load_state_from_disk/0 line 130 in application_master:init/4 line 134
06:48:23.859 [info] Application plumtree exited with reason: no match of right hand value {error,invalid_binary} in plumtree_peer_service_manager:maybe_load_state_from_disk/0 line 130
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,plumtree,{bad_return,{{plumtree_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,invalid_binary}},[{plumtree_peer_service_manager,maybe_load_state_from_disk,0,[{file,\"/opt/vernemq/distdir/1.5.0/_build/default/lib/plumtree/src/plumtree_peer_service_manager.erl\"},{line,130}]},{plumtree_peer_service_manager,init,0,[{file,\"/opt/vernemq/distdir/1.5.0/_build/default/lib/plumtree/src/plumtree_peer_service_manager.erl\"},{line,32}]},{plumtree_app,start,2,[{file,\"/opt/vernemq/distdir/1.5.0/_build/default/lib/plumtree/src/plumtree_app.erl\"},{line,28}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,plumtree,{bad_return,{{plumtree_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,invalid_binary}},[{plumtree_peer_service_man

Crash dump is being written to: /erl_crash.dump...config is OK
-config /var/lib/vernemq/generated.configs/app.2019.04.12.06.49.29.config -args_file /etc/vernemq/vm.args -vm_args /etc/vernemq/vm.args
Exec:  /usr/lib/vernemq/erts-8.3.5.3/bin/erlexec -boot /usr/lib/vernemq/releases/1.5.0/vernemq               -config /var/lib/vernemq/generated.configs/app.2019.04.12.06.49.29.config -args_file /etc/vernemq/vm.args -vm_args /etc/vernemq/vm.args              -pa /usr/lib/vernemq/lib/erlio-patches -- console -noshell -noinput
Root: /usr/lib/vernemq
06:49:30.951 [info] Application lager started on node 'VerneMQ@172.21.0.100'
06:49:30.955 [info] Application vmq_plugin started on node 'VerneMQ@172.21.0.100'
06:49:30.955 [info] Application ssl_verify_fun started on node 'VerneMQ@172.21.0.100'
06:49:30.955 [info] Application epgsql started on node 'VerneMQ@172.21.0.100'
06:49:30.969 [error] CRASH REPORT Process <0.201.0> with 0 neighbours exited with reason: no match of right hand value {error,invalid_binary} in plumtree_peer_service_manager:maybe_load_state_from_disk/0 line 130 in application_master:init/4 line 134
06:49:30.969 [info] Application plumtree exited with reason: no match of right hand value {error,invalid_binary} in plumtree_peer_service_manager:maybe_load_state_from_disk/0 line 130
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```

**Comment by ioolkos** [comment]
@robie2011 thanks for reporting this issue. 
So my guess is that the disk state was somehow corrupted? and I guess you did try to keep the VerneMQ data files?
Can you afford to loose those data? If yes, you could start with a clean data directory.
you might also want to update to a current VerneMQ release.

**Comment by robie2011** [comment]
yes, disk state is seems to be corrupt. Recreating container (resetting disk state) solves the problem. So there is no other solution than cleaning data dir ?

**Comment by ioolkos** [comment]
@robie2011 I don't know as I don't know what happened in your case.

But anyway, the question is what *should* happen. Let's suppose for the sake of the argument that Verne encounters completely garbled data files upon reboot. What should it do? silently create new ones, and load state from other cluster nodes? crash loudly like we currently do? trigger some repair mechanism (that probably wouldn't work in most cases) and block clients until done?

it's complicated :)

**Comment by robie2011** [comment]
The problem with docker container is that I can not attach it because the startup script is failing and container therefore exist immediately. So the only solution I know is to commit the container to a new image and run the newly created image in interactive mode with a shell. The newly created container don't have any states because states were external in the previous container, so I couldn't get any state-files to attach it here.

I'm not familiar with all the functionality of VerneMQ. In our case we use Verne as a simple standalone MQTT-Messaging Server, and we don't use special QoS. Therefore I expected states to be constrained to time. That means after a system crash and restart it shouldn't matter in which states it was before and system could start with new (initial) state.

By states, I think of pending undelivered messages and connected clients.

**Comment by dergraf** [comment]
@robie2011 you can start a VerneMQ container with the `/bin/sh` command instead of the default start script provided by the image e.g. `docker run -ti erlio/docker-vernemq:latest /bin/bash` and run `vernemq console` from there. Obviously you'd need to also mount the volume properly. I hope this helps in the further analysis.
