### ISSUE TITLE
import vmq_server record to elixir plugin

### ISSUE THREAD

**Issue by pewh** [vernemq/vernemq#1144]
I want to use `vmq_reg:publish` into my elixir plugin. But it need `#vmq_msg` record on the fourth argument (look at https://github.com/vernemq/vernemq/blob/1.7.1/apps/vmq_server/src/vmq_reg.erl#L302). 

Below is my plugin code.
```
defmodule ChatAcl do
  @moduledoc false
  require Logger
  require Record

  Record.defrecord(:vmq_msg, Record.extract(:vmq_msg, from_lib: "vmq_server/src/vmq_server.hrl"))

...
```

and it throw error.

```
(ArgumentError) lib file vmq_server/src/vmq_server.hrl could not be found
    (elixir) lib/record/extractor.ex:41: Record.Extractor.from_lib_file/1
    (elixir) lib/record/extractor.ex:18: Record.Extractor.from_or_from_lib_file/1
    (elixir) lib/record/extractor.ex:5: Record.Extractor.extract/2
```

I also copy this `vmq_server.hrl` file manually and update path to `/Users/name/vmq/ext/chat_acl/lib/vmq_server.hrl` and it doesn't work. Any idea how to use `vmq_reg:publish` properly?

I'm avoiding to use `{RegisterFun, PublishFun, SubscribeFun}` and prefer `vmq_reg:publish` as I need to publish to other `ClientId`.

**Comment by ioolkos** [comment]
@pewh thanks... not sure I understand the issue
pinging @dergraf: what do you reckon?

**Comment by dergraf** [comment]
@pewh `vmq_reg:publish` is internal and shouldn't be used. Use the mentioned `{RegisterFun, PublishFun, SubscribeFun}` instead. Moreover the used `vmq_msg` record is also internal and shouldn't be used. Also, the `vmq_server.hrl` is internal and shouldn't be used.

Can you elaborate more about what `vmq_reg:publish` provides that you can't do with the `PublishFun` ?

**Comment by pewh** [comment]
hello @dergraf 
my use case is if user triggered on_registered, vernemq will automatically publish to other users (some client ids). If using Publish, the code in elixir should be:
```
PublishFun("topic/xyz", "the payload", %{ qos: 1 }) # where is parameter for client id?
```

on https://github.com/vernemq/vernemq/blob/1.7.1/apps/vmq_server/src/vmq_reg.erl#L715, I cannot setup client id if using PublishFun.

**Comment by dergraf** [comment]
You don't need the client id. The PublishFun will publish a message to every subscriber that matches the provided Topic.

**Comment by pewh** [comment]
Thanks for the response. PublishFun is working as expected, except it doesn't trigger with auth_on_publish and on_publish hook. Is there a way to trigger those after PublishFun?

**Comment by dergraf** [comment]
no. that's currently not possible out of the box. You'd need to call the `vmq_plugin:all_till_ok(auth_on_publish, ListOfHookArgs)` inside your plugin but this stuff is again very much internal.
