### ISSUE TITLE
auth_on_publish:704 can't auth publish

### ISSUE THREAD

**Issue by vikas1369** [vernemq/vernemq#1145]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

    VerneMQ Version: Official Docker version
    OS: Ubuntu 18.04
    Mysql Version: Official Docker version(MySQL 8.0)
    Erlang/OTP version (if building from source):

### Expected behavior

I should be able to publish on a given topic.

### Actual behaviour

Not able to publish on the given topic

But getting following error:
auth_on_publish:704 can't auth publish [<<"test-user1">>,{[],<<"test-client1">>},1,[<<"c">>,<<"b">>,<<"vikas">>],<<"10">>,false] due to error

I am using DB Based authentication.

vmq_auth_acl table has following entry

`+------------+--------------+-------------+----------------------------------+-------------------------------------------+-------------------------------------------+
| mountpoint | client_id    | username    | password                         | publish_acl                               | subscribe_acl                             |
+------------+--------------+-------------+----------------------------------+-------------------------------------------+-------------------------------------------+
|            | cn4_lab3     | lab3cn4     | 6eff383b2ab860e9102aceb665bae3a6 | [{"pattern":"vjti/csriot/cn4/#"}]         | [{"pattern":"#"}]                         |
|            | gateway_lab3 | lab3gateway | 99c56b558acd6855445530dddfc56957 | [{"pattern";"vjti/csriot/glab3/#"}]       | [{"pattern":"#"}]                         |
|            | test-client  | test-user   | 202cb962ac59075b964b07152d234b70 | [{"pattern":"a/b/c"},{"pattern":"c/b/#"}] | [{"pattern":"a/b/c"},{"pattern":"c/b/#"}] |
|            | test-client1 | test-user1  | 202cb962ac59075b964b07152d234b70 | [{"pattern":"a/b/c"},{"pattern":"c/b/#"}] | [{"pattern":"a/b/c"},{"pattern":"c/b/#"}] |
+------------+--------------+-------------+----------------------------------+-------------------------------------------+-------------------------------------------+`

I am able to publish on the topic c/b/vikas for client-id=test-client1

But If I change the program with the credentials of client-id=lab3gateway, I am not able to publish on the topic vjti/csriot/glab3/temp

``` python
import paho.mqtt.client as paho
import time
 
def on_publish(client, userdata, mid):
    print("mid: "+str(mid))
 
client = paho.Client(client_id="gateway_lab3",clean_session=True)
client.on_publish = on_publish
client.username_pw_set("lab3gateway","g0tew0y10b3")
client.connect("<Verne-MQ_Server_Address>", 1886)
client.loop_start()
 
while True:
    temperature = 10
    (rc, mid) = client.publish("vjti/csriot/glab3/temp", str(temperature), qos=1)
    time.sleep(5)
    #print(client.getTopic())
```

**Comment by dergraf** [comment]
I think there is a bug in the JSON object of the `gateway_lab3` client. The publish ACL contains a `;` instead of a `:` see: `[{"pattern";"vjti/csriot/glab3/#"}]` ... I am actually curious how this even passed the parser. Can you check if the JSON is correct? Thanks

**Comment by vikas1369** [comment]
Where can I find the JSON?

**Comment by larshesel** [comment]
It's in the output above - the line for `gateway_lab3` looks incorrect as it contains the pattern as mentioned by @dergraf. Try to correct this and see if that helps.

**Comment by vikas1369** [comment]
Thanks @dergraf  for pointing that out. I corrected it and it's working fine now. As far as the checking of the pattern is concerned- I think it can be implemented on the client side.
