### ISSUE TITLE
clustered bridging

### ISSUE THREAD

**Issue by texasbones11** [vernemq/vernemq#1147]
I have 3 vernemq containers running in a cluster and I am trying to get them to also bridge from a mosquitto server source. I am seeing triple the amount of mosquitto traffic as expected when running the bridge as a cluster, then when I break the cluster and run the bridge from a single container. 

Is there a way to run a bridge within a cluster?

- VerneMQ Version: 1.7.1

**Comment by ioolkos** [comment]
@texasbones11 thanks for asking. Thinking in terms of topics and routing might help explain. Do you have subscribers to those topics (or to #) on all the 3 nodes?
if this doesn't make sense, what exactly would you expect instead?

**Comment by samk-mesh** [comment]
I'm working with @texasbones11  on this. 
We are getting the message counts from the clients.
Currently, we have a single client container that connects to the cluster (using a service within kubernetes). 

When we use a mosquitto based bridge (spin up a mosquitto ec2 instance, have it subscribe to the "source" in, and push to the verne cluster), we get X messages per second. 
When we use a single vernemq node with a vmq bridge plugin directly pulling from the "source" we get X messages per second. 
When we use a three node vmq cluster with the vmq bridge plugin, we get 3X messages per second. 
What appears to be happening is that each VMQ node in our cluster is bridging separately.

1555437267: New client connected from x.x.x.x as vernemq-2.br0 (c0, k60, u'XXXX').
1555437291: Socket error on client vernemq-1.br0, disconnecting.
1555437301: New connection from x.x.x.x on port 1883.
1555437301: Socket error on client vernemq-1.br0, disconnecting.
1555437301: New client connected from x.x.x.x as vernemq-1.br0 (c0, k60, u'XXXXX').
1555437310: Socket error on client vernemq-2.br0, disconnecting.
1555437310: New connection from x.x.x.x on port 1883.
1555437310: Socket error on client vernemq-2.br0, disconnecting.
1555437310: New client connected from x.x.x.x as vernemq-2.br0 (c0, k60, u'XXXXX').

**Comment by ioolkos** [comment]
@samk-mesh @texasbones11 Thansk for detailling.
So for those 3 cluster nodes, you have 3 vernemq.conf files. Do you configure a bridge in each of those config files?
regardless of that: what topics do the clients subscribe to?
