### ISSUE TITLE
Lager crashing, VerneMQ won't start

### ISSUE THREAD

**Issue by Josh798** [vernemq/vernemq#1148]
### Environment

- VerneMQ Version:  1.7.1 (built from commit [180c643](https://github.com/vernemq/vernemq/commit/180c643d3041a12b1f660f020411e7eef21dedfd))
- OS:  Ubuntu 14.04
- Architecture:  ARMv7
- OTP version:  OTP 21.3
- No changes to vernemq.conf

### The Problem

I have just successfully built VerneMQ on my system. However, when I run `bin/vernemq start` as instructed in the README, this is the output I receive:
```
vmq_cluster_node_sup
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
```
When I run `bin/vernemq console`, this is the output I receive:

```
Node undefined not responding to pings.
Error reading =CRASH REPORT==== 16-Apr-2019::13:41:50.215580 ===
  crasher:
    initial call: lager_handler_watcher:init/1
    pid: <0.96.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from lager_handler_watcher:install_handler2/3 (/home/ubuntu/vernemq/_build/default/plugins/lager/src/lager_handler_watcher.erl, line 117)
      in call from lager_handler_watcher:init/1 (/home/ubuntu/vernemq/_build/default/plugins/lager/src/lager_handler_watcher.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lager_handler_watcher_sup,lager_sup,<0.88.0>]
    message_queue_len: 0
    messages: []
    links: [<0.91.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 254
  neighbours:

 -config /home/ubuntu/vernemq/_build/rpi32/rel/vernemq/data/generated.configs/app.2019.04.16.13.41.53.config -args_file /home/ubuntu/vernemq/_build/rpi32/rel/vernemq/data/generated.configs/vm.2019.04.16.13.41.53.args -vm_args /home/ubuntu/vernemq/_build/rpi32/rel/vernemq/data/generated.configs/vm.2019.04.16.13.41.53.args 
```

So based on that, I think I have an issue with lager. But I'm very new to Erlang and VerneMQ, so I have no idea what this issue is. I greatly appreciate any help anyone has to offer.

**Comment by ioolkos** [comment]
Hi @Josh798 thanks for opening this issue. So you used the RPI target? We probably should look into whether this still works. 
pinging @dergraf, @larshesel

**Comment by Josh798** [comment]
Yes, that is corrent. I used `make rpi32` to build the project.

**Comment by ioolkos** [comment]
Ok, thanks. We'll investigate. 
(it might take some time...apologies for that)

**Comment by dergraf** [comment]
Can you run a clean build with `make rpi32` and provide us with the complete output of this process? Thanks.

**Comment by Josh798** [comment]
Here is the output from `make rpi32`. 
Note: While I am building this on an ARM device, I am not actually building on a raspberry pi. 

[vernemq_rpi32_build_output.txt](https://github.com/vernemq/vernemq/files/3093924/vernemq_rpi32_build_output.txt)

**Comment by ioolkos** [comment]
OK, thanks!
My guess is lager is not the issue here. 
Can you send us the vernemq.conf? (You say its unchanged, but we'd like to check if it has been generated completely).
Also, can you send the last generated vm.args file?
the ones that look like `vm.2019.04.16.13.41.53.args` and are autogenerated.

**Comment by Josh798** [comment]
No problem! Here are those two files. 
I've added the ".txt" extension because GitHub doesn't allow unknown file types. The names on the filesystem do not have ".txt". Also, don't be alarmed by the date on this .args file. I power cycled the device I'm using which reset the date. (No CMOS battery on this ARM device.)

[vernemq.conf.txt](https://github.com/vernemq/vernemq/files/3094743/vernemq.conf.txt)
[vm.2018.06.22.13.19.23.args.txt](https://github.com/vernemq/vernemq/files/3094754/vm.2018.06.22.13.19.23.args.txt)

**Comment by dergraf** [comment]
The files look good.

**Comment by larshesel** [comment]
Hi @Josh798 

I've run into this exact issue once as well - I believe it's an issue between erlang 21 and the version of `rebar3` which is shipped with VerneMQ. For me it worked if I used erlang 20 instead.

However, it would be interesting if it works with the master branch where we recently upgraded `rebar3`. I haven't had time to test it myself, but will give it a go soon I hope.

**Comment by dergraf** [comment]
@larshesel how could I have forgotten this... happened to me too.
Btw... I don't run into this issue with upgraded rebar3 and erlang 21 ... but let's see what josh reports.
