### ISSUE TITLE
arduino pubsub doesn't work with the proker

### ISSUE THREAD

**Issue by umitech** [vernemq/vernemq#1153]
I can't make connection with vernemq broker by pubsub client from my arduino client. Also I should mention that there's no any problem with my computer client and also I should say that my board can connect to the mosquitto broker without any problem.

### Environment

- VerneMQ Version: 1.7.1
- OS: ubuntu 18.04
- Erlang/OTP version (if building from source): Binary version
- VerneMQ configuration (vernemq.conf) or the changes from the default

anonymous is enabled
listening address changed to 0.0.0.0:1883

- Cluster size/standalone: standalone

**Comment by larshesel** [comment]
Hi, it could be a number of things. A network issue for example; is the arduino able to connect to the broker at all or is there a routing problem? If it is able to connect you could try to trace the client-id `vmq-admin trace client client-id=<insert-client-id-here>` and see what happens. If that doesn't help, perhaps you could try with wireshark or add debug logs in the arduino code which outputs the connection error to the console.

FYI I got an arduino board at home connecting to VerneMQ without any issues. I'm using this library: https://github.com/knolleary/pubsubclient/

**Comment by umitech** [comment]
Ok let me describe it better. 

1- I have a server which I started both the mosquitto and vernemq together. when I want to test with each one of them I start that service and stop another one. so the environment is the same (even the ports) 
2- I'm using exactly the library you mentioned with esp8266 processor
3- I can connect to both of the brokers with my pc client without any problem which shows that the config of the broker is correct
4- I can connect to the mosquitto with the esp board but I can't connect with vernemq
5- I checked with the tcpdump tool and found that at the connection request moment there's some packets exchanging between the broker and the board but the connection does not successfully establish.

I checked the state of the client after connection failed and it returns MQTT_CONNECT_UNAUTHORIZED. But as I said, I turned the anonymous connection on this way:

allow_anonymous = on

Is there any thing that may be important for your broker which is not important for mosquitto or any other thing which I can check for more investigation? for example I don't know if the client_id has any specification in your broker or not?

**Comment by cmnstmntmn** [comment]
@umitech hmm, as far as i know that esp client can use only `tlsv1`; 
so if you're using certificates, this might be the problem.

**Comment by larshesel** [comment]
If `allow_anonymous=on` is configured then authentication is completely disabled in VerneMQ. So either the config hasn't been properly set somehow (was VerneMQ restarted after the change) or the client isn't actually connecting to the running VerneMQ instance. What was the output of the trace command mentioned above?

**Comment by umitech** [comment]
Thanks for your answers. 
I found the problem. 
As I was tweaking the settings, I accidentally had changed the acl config in this way:

plugins.vmq_acl = off

The problem solved by turning it back on. But I still don't know why the pc client could connect to the broker while the board couldn't in that situation ?!!!

But anyway sorry for my bad mistake

And thanks for your great efforts and this neat project, keep it up

**Comment by larshesel** [comment]
Great you got it to work and thanks for the nice words!
