### ISSUE TITLE
no_matching_hook_found on VerneMQ 1.7.1

### ISSUE THREAD

**Issue by chenxinlong** [vernemq/vernemq#1154]
### Environment

- VerneMQ Version: 1.7.1
- OS: centos 7
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 3 nodes

### Behavior

This issue may refers to #1073 , but it happended on VerneMQ 1.7.1.   

### Vernemq.conf 
Related content :  
```
allow_anonymous = off 
plugins.vmq_passwd = off 
plugins.vmq_acl = off
plugins.vmq_diversity = on 
plugins.vmq_webhooks = on
vmq_diversity.auth_redis.enabled = on
```

### Detail logs  

Some sensitive content was removed. 

[console.log](https://github.com/vernemq/vernemq/files/3106192/console.log)
[error.log](https://github.com/vernemq/vernemq/files/3106195/error.log)
[crash.log](https://github.com/vernemq/vernemq/files/3106152/crash.log)
[erl_crash.dump.log](https://github.com/vernemq/vernemq/files/3106156/erl_crash.dump.log)

**Comment by larshesel** [comment]
Hi, before diving into the logs could you explain what you are doing to get to this problem?

**Comment by chenxinlong** [comment]
This problem appeared after a high server memory usage caused by another process, before this, the vmq service is normal.  

The erl_crash.dump.log may help.

**Comment by larshesel** [comment]
Hi, sorry for not getting back to this - judging from other issues I'd suppose you've found a workaround/solution for this - closing for now - feel free to reopen.

**Comment by chenxinlong** [comment]
Hi, This problem arises again.  Since it comes unpredictablely, so I can't find a way to reproduce it.

**Comment by larshesel** [comment]
Hi, without a way to reproduce it or more information helping us with this there's not much we can do here. There were some fixes done on the master branch which should make the Lua states handle errors better. Perhaps that helps.
