### ISSUE TITLE
Improve UX to configure TCP buffer sizes 

### ISSUE THREAD

**Issue by dergraf** [vernemq/vernemq#1158]
In VerneMQ one wants to configure the TCP buffer sizes for the MQTT client connections, the VMQ Inter-Cluster connections, and the Erlang distribution connections. 

The buffer sizes for the MQTT client connections are currently taken directly from the OS, to be precise VerneMQ tries to get the max allowed buffer Size from the OS. Because the OS as well as VerneMQ internally allocates memory for the buffer we often observe Out-of-Memory issues caused by too big TCP buffers. Currently the buffer size could be adjusted using a custom `auth_on_register` plugin that returns the `tcp_opts` modifier, or by globally setting the `vmq_server.tcp_listen_options` using an `advanced.config` config file. E.g. 

```erlang
[{vmq_server, [
          {tcp_listen_options,
          [{sndbuf, 4096},
           {recbuf, 4096}]}]}].
```  

The buffer sizes for the VMQ Inter-Cluster connections are by default taken directly from the OS. Those buffer sizes could be globally adjusted like above via the `advanced.config` or specifically for the cluster connections via setting the `vmq_server.outgoing_connect_opts` also in the `advanced.config` e.g.

```erlang
[{vmq_server, [
          {outgoing_connect_opts,
          [{sndbuf, 4096},
           {recbuf, 4096}]}]}].
```  

While not a direct TCP configuration the Erlang distribution buffer sizes are also important and can be adjusted in the `vernemq.conf` via `erlang.distribution_buffer_size` which will add the `+zdbbl` flag to the generated `vm.args`. Obviously, this setting doesn't affect a custom `vm.args` that you might have deployed in `/etc/vernemq/vm.args`. Note: the current Docker images rely on a custom `vm.args` file, therefore all the Erlang VM related configurations (like this one) don't work at the moment.

**Comment by larshesel** [comment]
Can we close this after #1169 was merged? /cc @dergraf

**Comment by codeadict** [comment]
Looks like this one could be closed @ioolkos ?

**Comment by ioolkos** [comment]
@codeadict jep, thanks
