### ISSUE TITLE
"Can't pass authentification" mongodb

### ISSUE THREAD

**Issue by puresilk** [vernemq/vernemq#1163]
Possibly related to #305 (Broker doesn't connect to mongo server)

### Environment
- Docker on x86 / AMD64, under Ubuntu 18.04 Bionic Beaver
- tried different VerneMQ versions, different releases (alpine / normal, latest, 1.7.0, 1.7.1-2-alpine)
- tried building using the provided Dockerfile (I understand this builds the newest release in Git)
- Erlang/OTP version (if building from source): the one specified in the Dockerfile "FROM erlang:21 AS build-env"
- VerneMQ configuration (vernemq.conf) or the changes from the default
as per the instructions to enable mongo
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = on
vmq_diversity.mongodb.host = pcp_mongo.mongo_net
vmq_diversity.mongodb.port = 27017
vmq_diversity.mongodb.login = pcp
vmq_diversity.mongodb.password = mysecretpassword

NB: I also tried to pass an IP address to the .host config entry. pcp_mongo is a container reachable under this name in the mongo_net network (set up using docker-compose). I verified that mongo is reachable under that name using ping. 
NB: Connecting to the same mongo instance from another container (my main application) is fine. I do not see a connection attempt / connection from VerneMQ using netstat in the mongo container.

- Cluster size/standalone:
standalone (in Docker container, one container being started)

### Expected behavior

- Connection to MongoDB, allowing clients to authenticate.

### Actual behaviour

- using image: erlio/docker-vernemq:latest
- setup with mongo credentials
- try to connect to mongodb

error messages:
jalpine_morpheus | =CRASH REPORT==== 5-May-2019::20:59:30.387060 ===
jalpine_morpheus |   crasher:
jalpine_morpheus |     initial call: mc_worker:init/1
jalpine_morpheus |     pid: <0.505.0>
jalpine_morpheus |     registered_name: []
jalpine_morpheus |     **exception error: <<"Can't pass authentification">>**
jalpine_morpheus |       in function  mc_auth_logic:scram_sha_1_auth/5 (/vernemq-build/_build/default/lib/mongodb/src/connection/mc_auth_logic.erl, line 55)
jalpine_morpheus |       in call from mc_worker:auth_if_credentials/5 (/vernemq-build/_build/default/lib/mongodb/src/connection/mc_worker.erl, line 218)
jalpine_morpheus |       in call from mc_worker:init/1 (/vernemq-build/_build/default/lib/mongodb/src/connection/mc_worker.erl, line 54)
jalpine_morpheus |     ancestors: [<0.452.0>,<0.448.0>,auth_mongodb,vmq_diversity_sup,
jalpine_morpheus |                   <0.435.0>]
jalpine_morpheus |     message_queue_len: 0
jalpine_morpheus |     messages: []
jalpine_morpheus |     links: [<0.452.0>,#Port<0.47>]
jalpine_morpheus |     dictionary: []
jalpine_morpheus |     trap_exit: false
jalpine_morpheus |     status: running
jalpine_morpheus |     heap_size: 987
jalpine_morpheus |     stack_size: 27
jalpine_morpheus |     reductions: 2889
jalpine_morpheus |   neighbours:

My docker-compose files
[jalpine-morpheus.zip](https://github.com/vernemq/vernemq/files/3146019/jalpine-morpheus.zip)

I believe this might not be related to docker, therefore I am opening this issue here.

**Comment by puresilk** [comment]
NB: these docker-compose files are missing the other necessary files in bin/ and files/, which are on my server, and not on the local system - have not included them in the ZIP, but they are there.

**Comment by larshesel** [comment]
Hi,

In the above config I don't see the line `vmq_diversity.auth_mongodb.enabled = on` as described in the docs: https://docs.vernemq.com/configuring-vernemq/db-auth#mongodb

Can you verify if it is present and if not add it and retest?

**Comment by puresilk** [comment]
Hi,

thank you for your quick answer. I had forgotten to paste that line. It is inside my config.
`vmq_diversity.auth_mongodb.enabled = on`

I have also discovered a mistake which I fixed - I was passing in the collection name, instead of the db name. Now the db name is set correctly, and the collection has been renamed to **vmq_acl_auth** (which is fixed, I assume?).
Unfortunately that did not solve the problem, the same crash happens during testing.
I am using the same credentials for VerneMQ as for my main application. 

I'm attaching my config file (with edited password), error.log and crash.log in the ZIP.
[config.zip](https://github.com/vernemq/vernemq/files/3147330/config.zip)

Max

**Comment by larshesel** [comment]
Just to confirm, can you see that VerneMQ is able to establish a connection to MongoDB? Btw, which version of MongoDB are you using?

**Comment by puresilk** [comment]
On the VerneMQ container, `netstat -na` will show a lot of connection attempts to Mongodb in the state TIME_WAIT:
`tcp        0      0 172.21.0.4:47907        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:47195        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:55743        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:38653        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:50021        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:53215        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:54151        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:50151        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:43677        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:34477        172.21.0.3:27017        TIME_WAIT
tcp        0      0 172.21.0.4:45373        172.21.0.3:27017        TIME_WAIT
`
on my other container (with an application), the state is shown as ESTABLISHED:
`tcp        0      0 172.23.0.2:36572        172.23.0.3:27017        ESTABLISHED`

**note that the network seems to be different one (as seen by the IP), but it is the same container.** I will try to set it to the same network to rule that out as a problem. 

I have MongoDB Version: 
`root@pcp_mongo:/# mongod --version
db version v4.0.5
git version: 3739429dd92b92d1b0ab120911a23d50bf03c412
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
`

**Comment by puresilk** [comment]
OK, it seems MongoDB is seeing log-in requests, which it is not able to fulfill. I will investigate further and comment - it might very well be that my credentials are set up incorrectly - sorry for raising a bug report before investigating thoroughly!

pcp_mongo    | 2019-05-06T14:23:03.975+0000 I ACCESS   [conn200] SASL SCRAM-SHA-1 authentication failed for pcp on pcp-201902 from client 172.21.0.4:44041 ; UserNotFound: Could not find user pcp@pcp-201902

**Comment by puresilk** [comment]
Indeed it was a wrong configuration in MongoDB. I'm sorry! Not a bug :-) 

pcp_mongo    | 2019-05-06T14:37:47.331+0000 I ACCESS   [conn568] Successfully authenticated as principal vernemq-daemon on pcp-201902

For anyone having the same difficulty as me: 
I previously created users in the db **admin**, setting rights on them for a particular db (pcp-201902). This is the way which the connector of my main application works. This is what I was expecting to work here as well, since creating a user under the db pcp-201902 failed for me with the other connector.

For VerneMQ, I created the user in the db to which VerneMQ is connecting (pcp-201902) using the mongo CLI.

Once again sorry for raising the issue before debugging thoroughly :-)

**Comment by larshesel** [comment]
No worries, just great you got it to work!
