### ISSUE TITLE
Calling endpoint failed due to econnrefused

### ISSUE THREAD

**Issue by chenxinlong** [vernemq/vernemq#1171]
### Environment

- VerneMQ Version:1.7.1
- OS:CentOS7
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration : [vernemq.conf.txt](https://github.com/vernemq/vernemq/files/3162000/vernemq.conf.txt)

- Cluster size/standalone: standalone

### Expected behavior

Auth using redis, I've reedit the `/usr/share/vernemq/lua/auth/redis.lua` and restart the vernemq using `service vernemq restart` , the modification of `redis.lua` as follow : 
```
// ...... nothing changed

function my_auth_on_publish(pub)
    print("=========test")
    return true
end

// ...... nothing changed

hooks = {
    auth_on_register = auth_on_register,
    auth_on_publish = my_auth_on_publish,
    auth_on_subscribe = auth_on_subscribe,
    on_unsubscribe = on_unsubscribe,
    on_client_gone = on_client_gone,
    on_client_offline = on_client_offline,

    auth_on_register_m5 = auth_on_register,
    auth_on_publish_m5 = my_auth_on_publish,
    auth_on_subscribe_m5 = auth_on_subscribe_m5,
}
```

When I connected to the vernemq and try to publish a message, the latest erlang.log output : 
```
(VerneMQ@127.0.0.1)1> ==========test(VerneMQ@127.0.0.1)1>
```

### Actual behaviour
When I connected to the vernemq and try to publish a message, the console.log output : 
```
2019-05-09 19:52:25.942 [error] <0.504.0>@vmq_webhooks_plugin:call_endpoint:605 calling endpoint failed due to econnrefused
```

And there's no content with `=========test` in any of the vernemq logs(error, console. erlang, etc), but the publishment was delivered successful.

**Comment by larshesel** [comment]
Hi, the error comes from the webhooks plugin which is apparently active. `econnrefused` means that the endpoint registered for the hook in the webhooks plugin isn't reachable. Please make sure only the plugin you need (redis) is enabled.
