### ISSUE TITLE
why my single node vernemq can't support beyond 64K live connections

### ISSUE THREAD

**Issue by charlie-charlie** [vernemq/vernemq#1172]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version: 
[root@ip-10-0-5-50 vernemq]# yum list vernemq
Loaded plugins: priorities, update-motd
Installed Packages
vernemq.x86_64                                                         1.7.1-1.el7                                                          installed

- OS:
[root@ip-10-0-5-50 vernemq]# cat /etc/*release*
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
cpe:2.3:o:amazon:amazon_linux:2
- Erlang/OTP version (if building from source): installed from downloaded rpm, not built from source
- VerneMQ configuration (vernemq.conf) or the changes from the default
allow_anonymous = off
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
persistent_client_expiration = 1d
max_inflight_messages = 2000
max_online_messages = 10000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 1000000
listener.nr_of_acceptors = 10000
listener.tcp.default = 10.0.5.50:1883
listener.vmq.clustering = 10.0.5.50:44053
listener.http.default = 10.0.5.50:8888
listener.mountpoint = off
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local
plugins.vmq_passwd = on
plugins.vmq_acl = off
plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = off
metadata_plugin = vmq_swc
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.mysql.password_hash_method = password
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off
log.console = file
log.console.level = info
log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = VerneMQ@10.0.5.50
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 134217727
leveldb.maximum_memory.percent = 20
erlang.process_limit = 10000000
outgoing_clustering_buffer_size = 150000
erlang.distribution.port_range.minimum = 6000
erlang.distribution.port_range.maximum = 7999
- Cluster size/standalone:
- sysctl.conf
fs.file-max = 2097152
fs.nr_open = 2097152
net.core.somaxconn = 262144
net.ipv4.tcp_max_syn_backlog = 16384
net.core.netdev_max_backlog = 16384
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 3
sysctl: setting key "net.ipv4.ip_local_port_range": Invalid argument
net.ipv4.ip_local_port_range = 1000 65535
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.optmem_max = 16777216
net.ipv4.tcp_rmem = 4096 349520 16777216
net.ipv4.tcp_wmem = 4096 349520 16777216
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_max_tw_buckets = 1048576
kernel.sched_migration_cost_ns = 5000000
vm.max_map_count = 2097152
net.core.netdev_budget = 1200
net.ipv4.tcp_sack = 0

- file/process limits
-bash-4.2$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62202
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 2097152
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2097152
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
-bash-4.2$ id
uid=998(vernemq) gid=994(vernemq) groups=994(vernemq)
### Expected behavior

- i'm running vernemq on aws ec2 m5.xlarge with 4 cpus+16Gmem+10g network. using mqtt-benchmark. running on 5 test hosts(m5.xlarge), here is my test commands:./emqtt_bench_pub -h internal-vernemq-elb-104490122.us-west-2.elb.amazonaws.com -p 1883  -c 1000 -I 30000 -s 512  -t "device" -k 8888
From 5 test machines, I ran 100 above commands.

Expected to have 100k live connections to single-node vernemq.

### Actual behaviour
 connections reached 65545, maxed out. no more connections can established.

- Please include minimal steps to reproduce the issue, if possible.
all logs clean.
Thanks

**Comment by larshesel** [comment]
This is likely because you have a single listener and the test nodes have a single local IP and not enough ports. Each TPC connection is identified using LocalIP:Port + RemoteIP:Port. So if there's a single listener, then all that's left is the LocalIP and Port, if each test node only has one IP then all that's left to for TCP connections is the local port. If the port range is limited on the test node, then this might be the limiting factor. In any case this is not a VerneMQ bug, it's a configuration issue, so I'll close this for now.

**Comment by larshesel** [comment]
Note, you should be able to mitigate this by adding extra listeners on the VerneMQ side.

**Comment by kksudo** [comment]
I have similar problems with 65k limit connections to VMQ.
I tried different ways to increase this limit ( **65523** connections ).
VerneMQ located in k8s GKE, it has enough cpu and ram.  
I have few listeners in VMQ into one pod.
Vernemq version: `vernemq/vernemq:1.10.1-alpine`

For the load tests i used emqtt, there are 4 pods with one white ip (test cluster(emqtt)  it's different cluster from VMQ).
Connect to listener one: `emqtt_bench pub -h <ip> -I 65000 -i 10 -c 25100 -t load/test/%i/%c  -u dev -P dev -p 1883 -V 4 -k 300 -q 1`
Connect to listener two: `emqtt_bench pub -h <ip> -I 65000 -i 10 -c 25100 -t load/test/%i/%c  -u dev -P dev -p 2883 -V 4 -k 300 -q 1`

Count of file descriptors : 
`fs.file-nr = 100096	0	1531742`

Some configs of  VMQ:
```
net.core.somaxconn=262144; 
sysctl -w net.core.tcp_syncookies=1; 
sysctl -w net.ipv4.tcp_max_syn_backlog=262144; 
sysctl -w net.core.netdev_max_backlog=50000; 
sysctl -w net.ipv4.ip_local_port_range='1024 65535'
```

Full VMQ config (default values in the top of config):
```
accept_eula = no
allow_anonymous = off
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
coordinate_registrations = on
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.tcp.default = 127.0.0.1:1883
listener.vmq.clustering = 0.0.0.0:44053
listener.http.default = 127.0.0.1:8888
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local
plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = off
metadata_plugin = vmq_plumtree
vmq_acl.acl_file = ./etc/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = ./etc/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = ./share/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.postgres.ssl = off
vmq_diversity.postgres.password_hash_method = crypt
vmq_diversity.auth_cockroachdb.enabled = off
vmq_diversity.cockroachdb.ssl = on
vmq_diversity.cockroachdb.password_hash_method = bcrypt
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.mysql.password_hash_method = password
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.mongodb.ssl = off
vmq_diversity.auth_redis.enabled = off
vmq_bcrypt.pool_size = 1
log.console = file
log.console.level = info
log.console.file = ./log/console.log
log.error.file = ./log/error.log
log.syslog = off
log.crash = on
log.crash.file = ./log/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = VerneMQ@127.0.0.1
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
accept_eula=yes
listener.tcp.allowed_protocol_versions=4
log.console.level=info
max_inflight_messages=10000
persistent_client_expiration=1d
max_online_messages=-1
max_message_size=1048576
max_offline_messages=-1
allow_subscribe_during_netsplit=off
listener.max_connections=infinity
systree_enabled=off
allow_publish_during_netsplit=off
vmq_passwd.password_file=/etc/vmq-auth/vmq.passwd
vmq_acl.acl_file=/etc/vmq-auth/vmq.acl
allow_unsubscribe_during_netsplit=off
log.console=console
allow_register_during_netsplit=off
listener.tcp.alternative1=0.0.0.0:2883
listener.tcp.localhost=127.0.0.1:1883
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.48.9.62:1883
listener.ws.default = 10.48.9.62:8080
listener.vmq.clustering = 10.48.9.62:44053
listener.http.metrics = 10.48.9.62:8888
```

Can you help to increase max connections ?
How many max connections can accept the one VMQ instance?
Which is additional information you need?
