### ISSUE TITLE
Lua script not triggered

### ISSUE THREAD

**Issue by chenxinlong** [vernemq/vernemq#1173]
### Environment

- VerneMQ Version:1.7.1
- OS:CentOS 7
- Erlang/OTP version (if building from source):NA
- VerneMQ configuration : see [vernemq.conf.txt](https://github.com/vernemq/vernemq/files/3164650/vernemq.conf.txt)

- Cluster size/standalone:standalone 

### Expected behavior

I've reedit the redis.lua 
```
require "auth/auth_commons"

function my_auth_on_register(reg)
    print("=====reg")
    if reg.username ~= nil and reg.password ~= nil then
        key = json.encode({reg.mountpoint, reg.client_id, reg.username})
        res = redis.cmd(pool, "get " .. key)
        if res then
            res = json.decode(res)
            if res.passhash == bcrypt.hashpw(reg.password, res.passhash) then
                cache_insert(
                    reg.mountpoint, 
                    reg.client_id, 
                    reg.username,
                    res.publish_acl,
                    res.subscribe_acl
                    )
                return true
            end
        end
    end
    return false
end

function my_auth_on_publish(pub)
    print("=====pub")
    return true
end


pool = "auth_redis"
config = {
    pool_id = pool
}


redis.ensure_pool(config)
hooks = {
    auth_on_register = my_auth_on_register,
    auth_on_publish = my_auth_on_publish,
    auth_on_subscribe = auth_on_subscribe,
    -- on_unsubscribe = on_unsubscribe,
    -- on_client_gone = on_client_gone,
    -- on_client_offline = on_client_offline,

    -- auth_on_register_m5 = auth_on_register,
    -- auth_on_publish_m5 = my_auth_on_publish,
    -- auth_on_subscribe_m5 = auth_on_subscribe_m5,
}

```

The enabled plugins as pics below : 
![image](https://user-images.githubusercontent.com/9261954/57498016-a49c0180-730c-11e9-9f9b-225108166e91.png)

vernemq.conf as : [vernemq.conf.txt](https://github.com/vernemq/vernemq/files/3164650/vernemq.conf.txt)

After restart the vernemq and connected to it, the erlang.log output `======reg` as expectly : 
![image](https://user-images.githubusercontent.com/9261954/57498074-f47ac880-730c-11e9-9ef4-e060e778848e.png)

And after I publish a message, the erlang.log outputs `======pub`.
### Actual behaviour

But there's nothing about `=====pub` in the erlang.log after I published a message. BTW, message was normally delivered.

![image](https://user-images.githubusercontent.com/9261954/57498328-014bec00-730e-11e9-8949-adc37635d92c.png)

**Comment by larshesel** [comment]
This is because of the lines:

```
                cache_insert(
                    reg.mountpoint, 
                    reg.client_id, 
                    reg.username,
                    res.publish_acl,
                    res.subscribe_acl
                    )
```

Which inserts the ACL into the cache and because this is cached the lua publish function is never called.

**Comment by chenxinlong** [comment]
Hi, thanks for your reply. It works after I commented the `cache_insert`. And there's another question which is where are these caches stored and when will these caches expire ?

**Comment by larshesel** [comment]
They are stored in an erlang ETS table and expires when the connection is closed.

**Comment by chenxinlong** [comment]
Thx

**Comment by chenxinlong** [comment]
So if the erlang ETS stored the pub/sub acl, then the auth_on_publish/auth_on_subscribe hook function  is actually triggered inside the erlang code , right ?

**Comment by larshesel** [comment]
yep

**Comment by chenxinlong** [comment]
Thanks for the reply
