### ISSUE TITLE
Documentation regarding how to disable things in conf

### ISSUE THREAD

**Issue by basickarl** [vernemq/vernemq#1179]
I'd like to know how to disable everything. Vernemq is eating up a lot of ports and I'd like to use it soley for mqtt over tcp. How does one do this?

Would listener.wss.default = off be sufficient?

**Comment by larshesel** [comment]
Hi, I'm a but surprised by this issue as by default only the MQTT TCP listener is enabled. Which ports is it you see VerneMQ eating?

**Comment by basickarl** [comment]
@larshesel Hello!
![image](https://user-images.githubusercontent.com/10507098/57693117-b9e49900-7648-11e9-95b6-ee61f9051147.png)

Ahh. Ok I understand now! I'm using the docker image, sorry for the disturbance. I'll have a look at their documentation! :D
