### ISSUE TITLE
Cannot start VerneMQ on Raspberry Pi3 (Raspbian)

### ISSUE THREAD

**Issue by licensedslacker** [vernemq/vernemq#1181]
### Environment

- VerneMQ Version: 1.7.1 (built from source)
- OS: Raspbian April 2019
- Erlang/OTP version (if building from source): 21.3.3 (Erlang solutions built for raspbian)
- VerneMQ configuration (vernemq.conf) is default
- Cluster size/standalone: standalone

Cannot get VerneMQ working on Raspberry Pi3 Model B. Using Raspbian image from April 2019. Erlang/OTP is built by erlang solutions for raspbian.

`make rpi32`

The build goes OK.
```
cd _build/rpi32/rel/vernemq
bin/vernemq console
```
Gives the following crash report.
```
Node undefined not responding to pings.
Error reading =CRASH REPORT==== 14-May-2019::13:36:20.495426 ===
  crasher:
    initial call: lager_handler_watcher:init/1
    pid: <0.96.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from lager_handler_watcher:install_handler2/3 (/home/pi/vernemq-1.7.1/_build/default/plugins/lager/src/lager_handler_watcher.erl, line 117)
      in call from lager_handler_watcher:init/1 (/home/pi/vernemq-1.7.1/_build/default/plugins/lager/src/lager_handler_watcher.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lager_handler_watcher_sup,lager_sup,<0.88.0>]
    message_queue_len: 0
    messages: []
    links: [<0.91.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 255
  neighbours:

 -config /home/pi/vernemq-1.7.1/_build/rpi32/rel/vernemq/data/generated.configs/app.2019.05.14.13.36.24.config -args_file /home/pi/vernemq-1.7.1/_build/rpi32/rel/vernemq/data/generated.configs/vm.2019.05.14.13.36.24.args -vm_args /home/pi/vernemq-1.7.1/_build/rpi32/rel/vernemq/data/generated.configs/vm.2019.05.14.13.36.24.args
```
Is the rpi32 build even funtional?

**Comment by larshesel** [comment]
yes, but it doesn't work with OTP 21, try OTP 20 instead. You could also try to build from the latest master where we've upgraded the build tool, which might solve this. If you try to build from master then let us know if that solved it for you.

**Comment by licensedslacker** [comment]
The master has the same issue. I'll try OTP 20 instead.

**Comment by licensedslacker** [comment]
> The master has the same issue. I'll try OTP 20 instead.

At least 1.7.1 works with OTP 20 on raspbian.
