### ISSUE TITLE
Lots of [warning] session stopped abnormally due to 'closed'

### ISSUE THREAD

**Issue by vytasmk** [vernemq/vernemq#1187]
### Environment

- VerneMQ Version: vernemq-1.7.1.jessie.x86_64.deb installed on Docker container with Debian Jessy
- Host OS: Ubuntu 16.04 LTS
- Cluster size/standalone: Standalone

Config is simple:
```
allow_anonymous = off

max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 0

# for internal communication
listener.tcp.internal = 0.0.0.0:1884
listener.tcp.internal.max_connections = 20000
listener.tcp.internal.mountpoint = secure

# for device handshake
listener.tcp.plain = 0.0.0.0:1883
listener.tcp.plain.max_connections = 20000
listener.tcp.plain.mountpoint = plain

# for device main communication
listener.ssl.secure = 0.0.0.0:8883
listener.ssl.secure.max_connections = 20000
listener.ssl.secure.mountpoint = secure

listener.ssl.secure.cafile = /home/certs/ca.crt
listener.ssl.secure.certfile = /home/certs/server.crt
listener.ssl.secure.keyfile = /home/certs/server.key

# disable $SYS topics
systree_enabled = off

log.syslog = off
log.console = console
log.console.level = info

# enable webhooks as acl
plugins.vmq_webhooks = on
plugins.vmq_passwd = off
plugins.vmq_acl = off

vmq_webhooks.onreg.hook = auth_on_register
vmq_webhooks.onreg.endpoint = http://another-docker-container/vernemq/register

vmq_webhooks.onsub.hook = auth_on_subscribe
vmq_webhooks.onsub.endpoint = http://another-docker-container/vernemq/subscribe

vmq_webhooks.onpub.hook = auth_on_publish
vmq_webhooks.onpub.endpoint = http://another-docker-container/vernemq/publish
```

### Problem

Need some advice how to solve problem when VerneMQ restarts and more than 4k nodes start reconnecting to the broker. Broker starts throwing messages `[warning] session stopped abnormally due to 'closed'` with near 100 msg/s in the log. At that moment CPU usage rises up to 600% (server has 8 vCPU). Only after more than 5 min all nodes are connected and CPU usage drop to about 80% ().

Nodes communication sequence:
-  node connects to the broker on plain connection (1883) and subscribes to one topic and sends request message to another topic. As response it gets CA certificate as text and then disconnects
- then it connects to SSL (8883) connection as anonymous user and introduces to the system. If everything is OK system sends login credentials and node disconnects
- then it connects again to SSL (8883) and authenticates with provided credentials. From this point node sends data periodically every 2min.

Almost all nodes are on different IP. Previously we were using Mosquitto (also in docker container with same OS version) and after restart all nodes were connected very quickly (within 1 min) so that should be not server problem but may be some Erlang settings or VerneMQ itself.

I am not familiar with Erlang and quite new to VerneMQ so looking for some help or advice how to tune this behavior.

**Comment by larshesel** [comment]
So if I understand you correctly the issue is that VerneMQ has higher load for some minutes when all the clients reconnect and that it takes longer than mosquitto? I don't really see from the log why the clients connections are closed, are there any other log messages which might reveal something?

**Comment by larshesel** [comment]
btw there's a change that the endpoint used by the webhooks isn't fast enough to handle all the incoming requests and/or the webhook pool size is too small. See this issue how to customize that: https://github.com/vernemq/vernemq/issues/1109#issuecomment-472081355

**Comment by vytasmk** [comment]
Currently log level is info I can try to enable debug for some time to get more data in logs. And tehre is no additional messages, only from time to time i see lines like this

`[info] monitor busy_port <0.14598.18> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,1}] #Port<0.118974>`

Endpoint should handle that it was used for Mosquitto authentication plugin and was working fine. i will try to increase that pool parameter and see what happens. 

By the way regarding that warning message when it is thrown? I mean what conditions should be met to receive that message.?

**Comment by vytasmk** [comment]
Increased webhook pool size but that did not help. Restarted with debug level logged one crash (UTC time)

```
09:17:15.443 [debug] transition from offline --> online because of add_session
09:17:15.448 [debug] transition from offline --> online because of add_session
09:17:15.449 [debug] transition from online --> wait_for_offline because of cleanup
09:17:15.457 [debug] transition from offline --> online because of add_session
09:17:15.458 [debug] transition from offline --> online because of add_session
=CRASH REPORT==== 16-May-2019::09:17:19.595858 ===
  crasher:
    initial call: vmq_ranch:init/5
    pid: <0.24700.5>
    registered_name: []
    exception error: no case clause matching {{error,cant_parse_client_id},
                                              <<>>}
      in function  vmq_mqtt_pre_init:data_in/2 (/opt/vernemq/distdir/1.7.1/_build/default/lib/vmq_server/src/vmq_mqtt_pre_init.erl, line 48)
      in call from vmq_ranch:handle_message/2 (/opt/vernemq/distdir/1.7.1/_build/default/lib/vmq_server/src/vmq_ranch.erl, line 174)
      in call from vmq_ranch:loop_/1 (/opt/vernemq/distdir/1.7.1/_build/default/lib/vmq_server/src/vmq_ranch.erl, line 117)
    ancestors: [<0.332.0>,<0.331.0>,ranch_sup,<0.125.0>]
    message_queue_len: 0
    messages: []
    links: [<0.332.0>,#Port<0.42794>]
    dictionary: [{bytes_received,#Ref<0.3465811162.2341339141.250545>},
                  {socket_open,#Ref<0.3465811162.2341339141.250548>}]
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 634
  neighbours:

09:17:15.469 [debug] transition from offline --> online because of add_session
=ERROR REPORT==== 16-May-2019::09:17:19.636092 ===
Ranch listener {{0,0,0,0},1883} had connection process started with vmq_ranch:start_link/4 at <0.24700.5> exit with reason: {{case_clause,{{error,cant_parse_client_id},<<>>}},[{vmq_mqtt_pre_init,data_in,2,[{file,"/opt/ve/distdir/1.7.1/_build/default/lib/vmq_server/src/vmq_mqtt_pre_init.erl"},{line,48}]},{vmq_ranch,handle_message,2,[{file,"/opt/vernemq/distdir/1.7.1/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,174}]},{vmq_rancp_,1,[{file,"/opt/vernemq/distdir/1.7.1/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,117}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

09:17:15.469 [debug] transition from offline --> online because of add_session
09:17:15.471 [debug] session normally stopped
09:17:15.473 [debug] session normally stopped
```

It looks to me that for some reason it accepts connection from node but can't handle and then just drops it...

**Comment by larshesel** [comment]
it looks like the parser can't parse the client-id. Perhaps there's an issue with the client library?

**Comment by vytasmk** [comment]
Nodes are with embedded Linux and as I know client is written in C. Of course that can be some third party clients trying to connect to the broker so that's why we use webhooks to validate nodes by client_id and username/password. 

We have tried this setup with smaller amount of nodes (~150) and we did not saw such problem they connect very fast. Only with this much larger amount we see such problem. I will think about some testing environment and how to reproduce such behavior locally.

**Comment by larshesel** [comment]
Ok, let us know if you figure out a way to reproduce. I wonder, is the client an MQTT 5.0 client?

**Comment by vytasmk** [comment]
No its not 5.0 Client was implemented somewhere in 2015 and did not changed a lot from that time. It is clear that in the near future we will need to look at whole implementation and communication procedure.

Currently I still see warning messages in the log but it is not clear if that is related to MQTT client or to the broker.

```
13:04:23.856 [warning] session stopped abnormally due to 'timeout'
13:04:24.067 [warning] session stopped abnormally due to 'timeout'
13:04:25.086 [warning] session stopped abnormally due to 'closed'
13:04:27.434 [warning] session stopped abnormally due to 'closed'
13:04:27.742 [warning] session stopped abnormally due to 'timeout'
13:04:29.805 [warning] session stopped abnormally due to 'timeout'
13:04:31.015 [warning] session stopped abnormally due to 'closed'
13:04:34.536 [warning] session stopped abnormally due to 'closed'
13:04:35.815 [warning] session stopped abnormally due to 'closed'
13:04:35.891 [warning] session stopped abnormally due to 'timeout'
13:04:35.928 [warning] session stopped abnormally due to 'timeout'
13:04:36.252 [warning] session stopped abnormally due to 'closed'
```

Also if I calculated correctly we have load somewhere 100msg/s.

**Comment by larshesel** [comment]
hmmm, the timeout could be coming from the webhooks endpoint. Are you sure the endpoint can handle the load? Do you use the exact same endpoint from mosquitto?

**Comment by larshesel** [comment]
Ok, the `cant_parse_clientid` is only returned from the MQTT 5.0 parser, so perhaps this is coming from a device which isn't yours which is trying to connect.

Are there no other warnings/error/info messages in the console.log file?

**Comment by vytasmk** [comment]
> 
> 
> hmmm, the timeout could be coming from the webhooks endpoint. Are you sure the endpoint can handle the load? Do you use the exact same endpoint from mosquitto?

if that is from webhooks endpoint then it is not very informative log messages as this does not show source where it happened is it webhook, or client i think it should include some more info, may be a `client_id` if problem is with client, or webhook name.

Of course I can try to disable authentication using webhooks and check if that changes something... just need to prepare for this a little.

Regarding Mosquitto endpoints there are the same validation functions for auth|pub|sub requests, only made separate handlers to pass data from VerneMQ requests. As that service reports some statistics it looks like both Mosquitto and VerneMQ works almost identically looking at message counts from that I can tell that when all nodes connect then they communicate as expected only the problem is when a lot of nodes reconnects at the same time.

Regarding MQTT 5.0 and that error I think that it is possible as broker is publicly accessible because our nodes come from allover the world. 

Looking at log i do not see any strange messages. Mostly those as in previous comment. From time to time I see `client {"secure",<<"clientID">>} with username <<"clientUserName">> stopped due to keepalive expired`

Found another one:
```
=INFO REPORT==== 16-May-2019::13:44:16.200199 ===
SSL: Got unexpected info: {{#Ref<0.723065818.2355363841.122194>,badarg},
                           tcp_error,#Port<0.240664>}
```
But these as i understand are not critical.
