### ISSUE TITLE
OS X install tutorial

### ISSUE THREAD

**Issue by TangMonk** [vernemq/vernemq#119]
The document seems only available Ubuntu and CentOS

**Comment by ioolkos** [comment]
Thanks! 
You are right, we'll need to document for OS X and we'll try to do this quickly. 
In principle you can try cloning and building. You may encounter a small problem related to where your SSL libs are on OS X. (I'll have to search the issues here)

**Comment by dmitriid** [comment]
```
> brew install openssl
> brew link openssl
```

you also need xcode command line tools (run XCode -> Install additional software)

After that running make should work like a charm

**Comment by ioolkos** [comment]
Yay, thanks Dmitrii :) :+1:

**Comment by dergraf** [comment]
At some point we should write a ```brew``` formula for VerneMQ.

**Comment by codeadict** [comment]
I can work on this one too, including the brew formula.

**Comment by syberkitten** [comment]
Any ideas how to proceed with this issue, I'm now using OTP 19.3 with Kerl.
Getting the same error as for OTP 20 :

```
vmq_passwd.c:32:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make[1]: *** [compile] Error 1
===> Hook for compile failed!

make: *** [rel] Error 1
```

**Comment by syberkitten** [comment]
Are you guys developing the project on Linux machines? or simply older versions for OSX ?

**Comment by ioolkos** [comment]
Yes, we develop on and for Linux.
VerneMQ always seemed to work on OS X without any problems, but with a little trickery in setting up, depending on OS X version.
@codeadict might have a homebrew version you could install:
https://github.com/codeadict/homebrew-vernemq
We should actually start hosting this, as this is very kind of @codeadict

**Comment by larshesel** [comment]
@syberkitten I responded over here: https://github.com/erlio/vernemq/issues/68#issuecomment-315735588

**Comment by syberkitten** [comment]
I've managed to solve the compile issue using the solution given in this issue:
https://github.com/erlio/vernemq/issues/88

**Comment by codeadict** [comment]
Is there any way you Erlio guys can host the vmq binaries and I can officially send a PR to homebrew. We can coordinate on that

**Comment by sebastiant** [comment]
Shamelessly adding some osx installation advice, let me know if you prefer it as a separate issue.
Installing from source on mac os 10.13.3 (high sierra) I had this:
```
$ make rel
<omitted output>
===> Unable to rewrite .app file /Users/sebastian/dev/vernemq/_build/default/rel/vernemq/lib/syntax_tools-2.1.4/ebin/syntax_tools.app due to {error, eacces}
```
referencing https://github.com/erlang/rebar3/issues/1441 (relx issue) I solved it by replacing the included rebar3 binary with version 3.5.3

**Comment by pctj101** [comment]
Had similar issue OS X High Sierra:

HEAD set to: | * 7c9996c      (HEAD -> mqtt5-preview, origin/mqtt5-preview) Some dialyzer fixes (Lars Hesel Christensen)

rebar version ->  rebar 3.3.6 on Erlang/OTP 20 Erts 9.2.1

With: Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Cloned rebar3 from git, compiled, rebar3 local install

cp .cache/rebar3/bin/rebar3 .

Now I have - rebar 3.7.0-rc1+build.4137.ref221cbf5c on Erlang/OTP 20 Erts 9.2.1

Works now.

**Comment by larshesel** [comment]
Closing this for now
