### ISSUE TITLE
"vernemq version" doesn't work

### ISSUE THREAD

**Issue by DouglasWWolf** [vernemq/vernemq#1190]
Using vernemq version 1.8.0.:

OS: Centos 7

"vernemq version" just prints a blank line.   The expected behavior is that it displays a version number.

**Comment by DouglasWWolf** [comment]
As a workaround... is there any other way to determine what version of vernemq is running?

**Comment by larshesel** [comment]
Hi @DouglasWWolf Thanks for opening the issue, this is probably something we missed while building out our new package build pipeline - we'll look into it.

On Centos 7 you should be able to get the package version using `yum info vernemq | grep Version`
