### ISSUE TITLE
Fix build when building from a .tar.gz (non-git repo)

### ISSUE THREAD

**Issue by boboxiaodd** [vernemq/vernemq#1191]
### Environment

- VerneMQ Version: 1.8.0
- OS: centos7
- Erlang/OTP version (if building from source): 22 or 21.3.8.1
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:1

### Expected behavior

- Please describe the expected behaviour.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

`./vernemq start`
```log
./vernemq: line 172: /root/vernemq-1.8.0/_build/default/rel/vernemq/bin/../erts-10.3.5.1: Is a directory
```

`./vernemq` config generate`

```log
./vernemq: line 385: /root/vernemq-1.8.0/_build/default/rel/vernemq/bin/../erts-10.3.5.1: Is a directory
```

**Comment by larshesel** [comment]
Thanks for the report. Does it still work with older versions of OTP, like OTP 21.2?

**Comment by boboxiaodd** [comment]
@larshesel 
OTP21.3 and OTP21.2 also fail

**Comment by larshesel** [comment]
what is the last commit you see for the tag? We had to bump the tag due to some package pipeline issues. Perhaps you caught the tag before we bumped it? The commit at the tag 1.8.0 should be f639ba9148a4d8d1a50c5182adbc201b0523559b

**Comment by boboxiaodd** [comment]
`make rel`
```log
===> Running cuttlefish schema generator
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /root/vernemq-1.8.0/_build/default/lib
          /root/vernemq-1.8.0/apps
          /usr/local/lib/erlang/lib
          /root/vernemq-1.8.0/_build/default/rel
===> Resolved vernemq-fatal: Not a git repository (or any of the parent directories): .git+build./bin/sh:line1:syntaxerrornearunexpectedtoken`('/bin/sh:line1:`(gitrev-list--countfatal:Notagitrepository(oranyoftheparentdirectories):.git..HEAD'.reffatal:Notagitrepository(oranyoftheparentdirectories):.git
===> Including Erts from /usr/local/lib/erlang
===> release successfully created!
```

and `_build/default/rel/vernemq/releases/start_erl.data` is bad 
```log
10.2 fatal: Not a git repository (or any of the parent directories): .git+build./bin/sh:line1:syntaxerrornearunexpectedtoken`('/bin/sh:line1:`(gitrev-list--countfatal:Notagitrepository(oranyoftheparentdirectories):.git..HEAD'.reffatal:Notagitrepository(oranyoftheparentdirectories):.git
```

so ...

**Comment by larshesel** [comment]
Can you try from a fresh clone and paste the enture output from start to finish of `make rel` ?

**Comment by larshesel** [comment]
I'm not able to replicate this, btw.

**Comment by boboxiaodd** [comment]
i download the https://github.com/vernemq/vernemq/releases/tag/1.8.0 tar.gz file
ok， i try to clone the repository

**Comment by larshesel** [comment]
It doesn't work correctly when building from the tar.gz as the build system relies on the files to be in a git repo - I think that's the problem you experience.

**Comment by boboxiaodd** [comment]
Yes ,this time ,`make rel` is correct, Thank you!
