### ISSUE TITLE
Log retention

### ISSUE THREAD

**Issue by bhagujava** [vernemq/vernemq#1203]
### Log retention
Is there any log retention config available like log4j ? DailyBaseRolling  or TimeBaseRolling log

Any document would help us a lot

I have seen configuration for crash log retention but not for error and debug log

````

## Acceptable values:
##   - a byte size with units, e.g. 10GB
log.crash.size = 10MB

## For acceptable values see https://github.com/basho/lager/blob/master/README.md#internal-log-rotation
log.crash.rotation = $D0


````

**Comment by larshesel** [comment]
Hi, I don't think it's possible via the `vernemq.conf` file at the moment, at least I couldn't see how to do that, so I'll mark this as an enhancement to be done.

For the moment you should be able to configure lager directly via the advanced config file (https://docs.vernemq.com/misc/not-a-tuning-guide#the-advanced-config-file). Then you can configure it according to the lager docs: https://github.com/erlang-lager/lager#configuration

**Comment by bhagujava** [comment]
@larshesel  Thanks for quick reply.

I see, i guess logrotate would help in this case. not sure how it can be done.
