### ISSUE TITLE
just changing mountpoint on webhook leads to errors, needs client_id as well?

### ISSUE THREAD

**Issue by puresilk** [vernemq/vernemq#1212]
# Setup

VerneMQ 1.8.0, the latest and greatest.
**auth_on_register** webhook, calling my code in my application via POST request
if my code returns

```
{"result": "ok"}
```
authentication works. (I'm setting status code to 200)

Now I want to change the mountpoint, using modifiers. The following return works:
```
{"result": "ok", "modifiers": {"mountpoint": "mountpoint_new", "client_id": "vogelwild"}}
```

However, **I only want to change the mountpoint.** The client_id can stay the same. The following does not work for me.

```
{"result": "ok", "modifiers": {"mountpoint": "mountpoint_new"}}
```

# Expected result
Only changing mountpoint in modifiers works

# Actual result
Only changing the mountpoint in modifiers does not work. The client_id would have to be passed in as well.
(possibly, if this is by design, it would be good to document it)

```
MQTT connection failed (6): AMQJS0006E Bad Connack return code:5 Connection Refused: not authorized.
```

VerneMQ log output:
```
19:30:03.425 [warning] can't authenticate client {"jsclient",<<"kebab">>} from 172.18.0.4:53162 due to error
```

vmq-admin trace client:
```
No sessions found for client "kebab"
New session with PID <8263.3178.0> found for client "kebab"
<8263.3178.0> MQTT RECV: CID: "kebab" CONNECT(c: kebab, v: 4, u: 66e25fbd90ab2d72485589afba3e134f--079750483e8b9c07c8955fb1b95f1fc5084fb9aa57377ce326e1ec9ca5e292c9, p: BsjcrEoX2YcPzrjNF5pTXHwfqwSXFkFhpdU6zr5G8A, cs: 1, ka: 60)
<8263.3178.0> Calling auth_on_register({{172,18,0,4},53094},{"jsclient",
                                                             <<"kebab">>},66e25fbd90ab2d72485589afba3e134f--079750483e8b9c07c8955fb1b95f1fc5084fb9aa57377ce326e1ec9ca5e292c9,BsjcrEoX2YcPzrjNF5pTXHwfqwSXFkFhpdU6zr5G8A,true)
<8263.3178.0> Hook returned {error,error}
<8263.3178.0> MQTT SEND: MP: "jsclient" CID: "kebab" CONNACK(sp: 0, rc: 5)
<8263.3178.0> Trace session for kebab stopped
```

**Comment by ioolkos** [comment]
@puresilk thanks for your question! we'll look to provide an answer/discussion.

**Comment by larshesel** [comment]
Hi, this case is actually documented in the note here: https://docs.vernemq.com/plugin-development/webhookplugins#webhook-specs

**Comment by larshesel** [comment]
Perhaps we can improve that somehow?

**Comment by puresilk** [comment]
Oh my God, I completely overlooked that one. Would have saved me hours of debugging. 

I suggest to put mountpoint and client-id in bold in this info box, so they draw more attention. 

Can a mountpoint be overriden also for published messages? Otherwise, if this modification is only applicable to auth_on_register, I suggest to move the box into the auth_on_register part.

**Comment by larshesel** [comment]
It can be overriden for other hooks as well. We haven't documented all modifiers everywhere, though.

**Comment by puresilk** [comment]
That's really nice! I want to say that I really love the flexibility and design of VerneMQ! The documentation is also quite good, to get a start. I'm happy that I have gone with VerneMQ over RabbitMQ or other solutions. And am contributing in the way I can :-)

**Comment by larshesel** [comment]
> I suggest to put mountpoint and client-id in bold in this info box, so they draw more attention.

I've done that in the docs. I guess we can close this one for now.
