### ISSUE TITLE
Not able to restart VerneMq after crash

### ISSUE THREAD

**Issue by natrajT** [vernemq/vernemq#1215]
[vernemq.txt](https://github.com/vernemq/vernemq/files/3276406/vernemq.txt)
Cluster size: 3

System config : 8GB RAM/ C5x.large

Server crashed when trying to connect 120000 connections to this cluster.

Not able to restart after crash. Tried reboot still same   problem.

Crash Report is attached
[crash_report.txt](https://github.com/vernemq/vernemq/files/3276381/crash_report.txt)

Gettign below erro when  trying to start

service vernemq start
Redirecting to /bin/systemctl start vernemq.service
Job for vernemq.service failed because the control process exited with error code. See "systemctl status vernemq.service" and "journalctl -xe" for details.
[root@ip-15-0-50-64 ec2-user]# systemctl status vernemq.service
● vernemq.service - VerneMQ Server
   Loaded: loaded (/etc/systemd/system/vernemq.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-06-11 12:09:48 UTC; 4s ago
  Process: 15715 ExecStart=/usr/lib64/vernemq/bin/vernemq start (code=exited, status=1/FAILURE)
  Process: 15620 ExecStartPre=/usr/lib64/vernemq/bin/vernemq chkconfig (code=exited, status=0/SUCCESS)

Jun 11 12:09:47 ip-15-0-50-64.ec2.internal vmq[15799]: [info] <0.64.0> SIGTERM received - shutting down
Jun 11 12:09:47 ip-.ec2.internal vmq[15799]: [error] <0.148.0> gen_server disksup terminated with reason: {port_died,normal}
Jun 11 12:09:47 ip-.ec2.internal vmq[15799]: [error] <0.148.0> CRASH REPORT Process disksup with 0 neighbours exited with r...ne 751
Jun 11 12:09:47 ip-.ec2.internal vmq[15799]: [error] <0.150.0> gen_server memsup terminated with reason: {port_died,normal}
Jun 11 12:09:47 ip-.ec2.internal vmq[15799]: [error] <0.147.0> Supervisor os_mon_sup had child disksup started with disksup...inated
Jun 11 12:09:47 ip-.ec2.internal vmq[15799]: [error] <0.150.0> CRASH REPORT Process memsup with 0 neighbours exited with re...ne 751
Jun 11 12:09:47 .ec2.internal vmq[15799]: [error] <0.147.0> Supervisor os_mon_sup had child memsup started with memsup:s...inated
Jun 11 12:09:48 .ec2.internal systemd[1]: Failed to start VerneMQ Server.
Jun 11 12:09:48 .ec2.internal systemd[1]: Unit vernemq.service entered failed state.
Jun 11 12:09:48 ec2.internal systemd[1]: vernemq.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

.From the logs it is is "Worst Memory User" .

**Comment by ioolkos** [comment]
Hi @natrajT thanks... I don't think this is a VerneMQ software issue per se. We cannot really support operations and deployment via Github issues. Feel free to get in touch for support over e-mail.

Also, it doesn't really make sense to go for 120k connections when your listener is configured for only 60k. Unless you somehow want to test that? Apologies if I misunderstand things.

**Comment by natrajT** [comment]
thank you. I have googled a lot but nothing helped . Where can i get help for these type of problems. Any blog/ community?.

**Comment by larshesel** [comment]
You could try the community on slack: https://slack-invite.vernemq.com/

**Comment by larshesel** [comment]
a guess would be you ran out of memory - try to monitor your memory usage as you ramp up the connections.

**Comment by larshesel** [comment]
With VerneMQ 1.8.0 we have a new systemd file. Do you perhaps have an old one lying around somehwere?

**Comment by larshesel** [comment]
@natrajT I've just heard that this could happen if SELinux is enabled. Try disabling it to see if this is the case.

**Comment by natrajT** [comment]
> a guess would be you ran out of memory - try to monitor your memory usage as you ramp up the connections.

From the crash dump it is sayign allocated is only 1.5GB. My system has 8 GB RAM. Can we allocate memory to VerneMQ just like we do in java.

**Comment by natrajT** [comment]
> @natrajT I've just heard that this could happen if SELinux is enabled. Try disabling it to see if this is the case.
sestatus
SELinux status:                 disabled
https://cloudacademy.com/blog/selinux-aws-ec2-security/
