### ISSUE TITLE
vernemq nodes not responding to pings on a Linux VM.

### ISSUE THREAD

**Issue by gitnwana** [vernemq/vernemq#1217]
### Expected behavior

respond with "pong"
### Actual behaviour
Node didn't respond to pings

1. The Vernemq instance is running on an Ubuntu 18,04 environment hosted on Azure Virtual Machines. 
The command `sudo service vernemq start/restart` does not respond. It freezes.

**Comment by larshesel** [comment]
Hi, can you please provide a bit more context. Without knowing what led up to this we'd have no way of helping. What version of VerneMQ, how was the package deployed, what actions were done up until the point this was experienced?

**Comment by gitnwana** [comment]
VerneMQ trusty 1.8.0 is running on an Ubuntu 18.04 OS. The package was installed through standard `wget` command. 
While making necessary changes to the config file when I restart the service it does not respond anything. Just the cursor stays and it freezes there.

**Comment by larshesel** [comment]
This could happen because the nodename was changed in the config while the VerneMQ was running. To solve that change it back, stop vernemq, change the nodename again and start VerneMQ again.

**Comment by gitnwana** [comment]
That worked!! Thanks a lot for that! @larshesel
