### ISSUE TITLE
Limits on the number of subscribers

### ISSUE THREAD

**Issue by davideicardi** [vernemq/vernemq#1222]
### Environment

- VerneMQ Version: 1.8.0
- VerneMQ configuration:
  - `max_inflight_messages = 1`
  - `listener.max_connections = 30000`
- Cluster size/standalone: 3

Do you see problems if we create one client session and one subscription for each topic?

Let's say to have 10K devices that publish data. Each device publish data in a dedicated topic, composed by `{client-id}/xyz`.
It is possible to create the equivalent number of client sessions (10K) that read/subscribe each one from a single topic, specific for each device.

Es.
- device1 publish to topic `device1/xyz`
- reader1 subscribe to topic `device1/xyz`
- device1 publish to topic `device2/xyz`
- reader2 subscribe to topic `device2/xyz`
- and so on ...

Of course we will duplicate all TCP connections, but there are known limits (other than `listener.max_connections`)?

We are thinking of using this solution to ensure message ordering but increase the overall throughput of having a single subscription. Also because we cannot use shared subscriptions and wildcards (see #1219, we need message order to be guaranteed).

**Comment by larshesel** [comment]
Hi

As this question is about MQTT architecture and not really about VerneMQ I'll close it for now. Feel free to ask in the community slack channel https://slack-invite.vernemq.com/ or get in touch with us for commercial support https://vernemq.com/services.html.
