### ISSUE TITLE
Subscribers dropping messages

### ISSUE THREAD

**Issue by HsiaoH** [vernemq/vernemq#1224]
**Setup**
VerneMQ: 1.6.1 running on docker 18.09
Ubuntu: 16.04.5
Running as a cluster with 2 machines in Azure

**Settings**

    -e "DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES=1000" \
    -e "DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES=1000" \
    -e "DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES=1000" \
    -e "DOCKER_VERNEMQ_MAX_CLIENT_ID_SIZE=100" \
    -e "DOCKER_VERNEMQ_MAX_MESSAGE_RATE=0" \
    -e "DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION=never" \
    -e "DOCKER_VERNEMQ_LEVELDB__MAXIMUM_MEMORY__PERCENT=50" \
    -e "DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT=on" \
    -e "DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT=on" \
    -e "DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT=on" \
    -e "DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT=on" \

- Clients are connecting use QoS 1
- Around 80k messages/s

**Problem**

Console logs are showing that clients are regulary dropping messages together with session problems with disconnect_migration/closed:

    2019-06-20 09:34:45.807 [warning] <0.7297.443>@vmq_mqtt_fsm:connected:260 subscriber 
    {[],<<"CPG_Client_Q_7">>} dropped 3 messages
    2019-06-20 09:41:41.721 [warning] <0.7818.443>@vmq_ranch:teardown:138 session stopped 
    abnormally due to 'disconnect_migration'
    2019-06-20 09:43:11.763 [warning] <0.7974.443>@vmq_mqtt_fsm:connected:260 subscriber 
    {[],<<"CPG_Client_Q_122">>} dropped 7 messages
    2019-06-20 09:43:23.056 [warning] <0.7974.443>@vmq_ranch:teardown:138 session stopped  
    abnormally due to 'disconnect_migration'
    2019-06-20 09:44:15.109 [warning] <0.8060.443>@vmq_ranch:teardown:138 session stopped 
    abnormally due to 'disconnect_migration'
    2019-06-20 09:48:17.775 [warning] <0.8447.443>@vmq_mqtt_fsm:connected:260 subscriber 
     {[], 
     <<"CPG_Client_Q_88">>} dropped 6 messages
    2019-06-20 10:00:41.149 [warning] <0.9295.443>@vmq_ranch:teardown:138 session stopped 
    abnormally due to 'closed'
     2019-06-20 10:03:26.669 [warning] <0.9480.443>@vmq_ranch:teardown:138 session stopped 
     abnormally due to 'disconnect_migration'
     2019-06-20 10:03:46.963 [warning] <0.9531.443>@vmq_mqtt_fsm:connected:260 subscriber 
     {[],<<"CPG_Client_Q_109">>} dropped 3 messages
     2019-06-20 10:03:46.971 [warning] <0.9531.443>@vmq_ranch:teardown:138 session stopped 
     abnormally due to 'closed'
     2019-06-20 10:11:26.930 [warning] <0.10206.443>@vmq_ranch:teardown:138 session stopped 
    abnormally due to 'disconnect_migration'
    2019-06-20 10:13:00.334 [warning] <0.10326.443>@vmq_ranch:teardown:138 session stopped 
    abnormally due to 'disconnect_migration'

Error logs are empty. Any suggestions on how to fix this problem?

**Comment by larshesel** [comment]
Hi, disconnect_migration means that a client with the same client-id connected to another node, and the queue and messages for that client is terminated and migrated to the other node.

The `dropped X messages` means that the subscriber is too slow to handle the messages and there are more than `max_online_messages` (if the client is online) or `max_offline_messages` (if the client is offline) queued for delivery and it therefore has to drop messages.

**Comment by HsiaoH** [comment]
Thanks for your response. I got a question about dropped X message in combination with QoS 1/2.
1) If the limit is exceeded of online/offline messages, are the dropped messages permanently lost?
2) Are offline messages stored in LevelDB?

**Comment by rohit5ram** [comment]
@ioolkos Can you please confirm the behavior to #1 (_If the limit is exceeded of online/offline messages, are the dropped messages permanently lost?_) comment made by @HsiaoH above? I am facing the same problem.

**Comment by ioolkos** [comment]
@rohit5ram if you see dropped messages, your message scenario is not in balance. Those messages cannot "drop" and still be saved somewhere (into a resource) because the whole point is to protect resources. Yes, they are permanently lost. Note that this applies per consumer queue. That is, specific queues for specific consumers will be affected, not all the messages for all subscribers.

Most of the time this is caused by slow consumers. You can address this by increasing `max_inflight_window`, by using shared subscriptions (load balancing the consumer) and by lowering the QoS.

Of course, you can also just increase the `max_messages` settings. That's most likely just a shift of the problem but not a permanent solution. (unless you're lucky hitting the balance point with the config). 

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by rohit5ram** [comment]
@ioolkos I configured as `max_inflight_messages=20, max_online_messages=1000, max_offline_messages=-1` 
I am also working on improving the consumer performance after knowing that the messages are dropping randomly.
Cannot use shared subscriptions in K8S environment with cleanSession=false as its tricky to set a incremented clientId with HPA. I appreciate on any work arounds!

FYI
In past 3 hrs, 137 messages were dropped. I use a reactive stream 'Flowable' in the consumer side. 
For Eg: Random Message drops are noticed even at inflow rate of 82.  blue color in the below grafana graph indicates drop count.
In: 82
Out: 50
Drop: 32

![image](https://user-images.githubusercontent.com/7732595/223706793-cd7abaa1-5e99-434d-9912-9ac22413bcbf.png)

On a side note, Can you also enlighten me on this error message `ERROR c.h.c.i.m.h.p.i.MqttIncomingQosHandler: Received more QoS 1 and/or 2 PUBLISH messages (MqttStatefulPublish{stateless=MqttPublish{topic=XXXX, payload=90byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=200, dup=true, topicAlias=0, subscriptionIdentifiers=[1]}) than allowed by receive maximum (65535) `

**Comment by ioolkos** [comment]
On the error: I guess you're using MQTT v5 for that consumer. For that you have to configure `receive_max_client` in the `vernemq.conf`.  Set this to something lower than the full window of 65k messages. `max_inflight_messages` is the corresponding setting for MQTT v3/4.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by rohit5ram** [comment]
@ioolkos Yes I use MQTTv5 and QOS1 both on publisher and subscriber side.  
Can you please clarify?
`receive_max_client`  Does this specify 65K messages can be received at any point in time?
In the above case did broker send more than 65K+ messages?
How does setting it to a lower value than 65K help?

FYI
The subscriber connects to broker using cleanSession=false and noSessionExpiry() so as to never lose a message. It subscribes to a wildcard (+) topic

Whenever it entered the above state, it never exited until its rebooted. It kept printing log every 20 secs(default retry interval?) for different topics (topic contains a deviceId , so each publish is unique) until the subscriber is restarted. All those messages were lost on reboot. What could be the reason?

**Comment by ioolkos** [comment]
@rohit5ram 
yeah, the broker would be allowed to send 65k Qos>0 messages before waiting on an ACK (if it wants too... the broker is always allowed to send less than the full window). I guess what you see is some sort of message id overflow in the client. (you can probably check what the client is configured for)

In any case, it strikes me as an oversight that we have a default of 65k in case you do not configure the setting. I'll set it to something much lower.


---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by rohit5ram** [comment]
@ioolkos client has no restrictions configured. 
FYI as you advised above, I have set `max_online_messages` , `max_offline_messages`, `receieve_max_client` to 50000

**Question:**

1. Did the scenario entered into a recurring loop when broker sent 65K messages in our case? Broker replaying QOS1 messages every 20secs because client couldn't acknowledge, and this process never stopped. The circuit breaker here is client restart. 
2. Can you recommend any work arounds for shared subscriptions in K8S environment with cleanSession=false?

**Best Practice:**
Can applying restriction on client using `[restrictions.receiveMaximum](https://hivemq.github.io/hivemq-mqtt-client/docs/mqtt-operations/connect/#restrictions)` based on its capacity avoid issue 1?

**Comment by ioolkos** [comment]
@rohit5ram the client thinks it gets more messages in a receive window than allowed. It therefore disconnects. 
You should be fine, if you have a server side override (`receive_max_client`) set. Normally, you would have a receive_max set from the client. 
The receive_max is basically a performance statement of the client about itself. (I can handle X messages in a window).

With `receive_max_client` set, you should not see the issue again.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
