### ISSUE TITLE
VerneMQ fails on delivering MQTT v5 message published from within a plugin

### ISSUE THREAD

**Issue by manifest** [vernemq/vernemq#1228]
### MQTT v5: VerneMQ fails

1. Create MQTT v5 client connection
```erlang
{ok, C} = emqx_client:start_link([{proto_ver, v5}, {host, {192,168,99,100}}, {port, 1883}, {client_id, <<"v1/agents/test.john.usr.example.net">>}]),
emqx_client:connect(C).
```

2. Create a subscription and publish a message (VerneMQ node)
```erlang
ClientId = <<"v1/agents/test.john.usr.example.net">>,
Topic = [<<"foo">>, <<"bar">>],
vmq_reg:subscribe(true, {"", ClientId}, [{Topic, 1}]),
{_, Publish, _} = vmq_reg:direct_plugin_exports(mqttgw),
Publish(Topic, jsx:encode(#{<<"payload">> => <<>>}), #{qos => 1}).
```

3. VerneMQ fails
```bash
03:45:51.676 [info] Agent = 'test.john.usr.example.net' connected: mode = 'default'
03:46:06.324 [error] CRASH REPORT Process <0.807.0> with 0 neighbours crashed with reason: no function clause matching vmq_parser_mqtt5:enc_properties([{p_user_property,[]}]) line 591
03:46:06.325 [error] Ranch listener {{172,17,0,2},1883} terminated with reason: no function clause matching vmq_parser_mqtt5:enc_properties([{p_user_property,[]}]) line 591
```

### MQTT v3: Just works

1. Create MQTT v3 connection
```erlang
{ok, C} = emqx_client:start_link([{host, {192,168,99,100}}, {port, 1883}, {client_id, <<"v1/agents/test.john.usr.example.net">>}]),
emqx_client:connect(C).
```

2. Create a subscription and publish a message
```erlang
ClientId = <<"v1/agents/test.john.usr.example.net">>,
Topic = [<<"foo">>, <<"bar">>],
vmq_reg:subscribe(true, {"", ClientId}, [{Topic, 1}]),
{_, Publish, _} = vmq_reg:direct_plugin_exports(mqttgw),
Publish(Topic, jsx:encode(#{<<"payload">> => <<>>}), #{qos => 1}).
```

3. MQTT v3 client gets the message
```erlang
flush().
Shell got {publish,#{client_pid => <0.277.0>,dup => false,packet_id => 1,
                     payload => <<"{\"payload\":\"\",\"properties\":{}}">>,
                     properties => undefined,qos => 1,retain => false,
                     topic => <<"foo/bar">>}}
```

### Environment

- VerneMQ Version: 1.8.0
- OS: alpine

### Expected behavior

Message delivered to the MQTT v5 client.

### Actual behaviour

VerneMQ fails on delivering MQTT v5 message.

**Comment by manifest** [comment]
Related to the [issue](https://github.com/vernemq/vernemq/issues/1210).

**Comment by dergraf** [comment]
Hi @manifest! 
Is it possible that you're implementing a `on_deliver_m5` hook to set the user property? Otherwise I don't know where the `p_user_property` is coming from ;) If this is the case you'd need to specify at least one user property. 

Can you provide further information for debugging this case. Thanks.

**Comment by manifest** [comment]
Hi @dergraf !

Yes, we have [on_deliver_m5](https://github.com/netology-group/mqtt-gateway/blob/148bbf1784c21a84627ec848c5da84832a3284f4/src/mqttgw.erl#L714-L717) implemented and set user properties [there](https://github.com/netology-group/mqtt-gateway/blob/148bbf1784c21a84627ec848c5da84832a3284f4/src/mqttgw.erl#L579-L585) from within it. Both our v3 and v5 publishers fold payload+properties into envelope and send it in message payload. Then, we deliver such an envelope to v3 subscribers as it is and unfold it to payload+properties for v5 subscribers. That's the way how we allow both v3 and v5 clients work together on the same broker. User properties are always presented in the v5 messages.

**Comment by larshesel** [comment]
Hi, 

I just tried to reproduce this with the `paho_c_sub` mqtt 5 client and the old mosquitto_sub as a mqtt 3/4 client:

```
$ paho_c_sub -i myclient -t 'foo/bar' -q 1 -V 5 
{"payload":""}
```

```
mosquitto_sub -t 'foo/bar'
{"payload":""}
```

As you can see above both of them received the message without any issues. I published like this:

```
(VerneMQ@127.0.0.1)2> Topic = [<<"foo">>, <<"bar">>].        
[<<"foo">>,<<"bar">>]
(VerneMQ@127.0.0.1)3> {_, Publish, _} = vmq_reg:direct_plugin_exports(mqttgw).          
{#Fun<vmq_reg.15.91124053>,#Fun<vmq_reg.16.91124053>,
 {#Fun<vmq_reg.17.91124053>,#Fun<vmq_reg.18.91124053>}}
(VerneMQ@127.0.0.1)4> Publish(Topic, jsx:encode(#{<<"payload">> => <<>>}), #{qos => 1}).
{ok,{2,0}}
```

So I didn't create the subscription programatically - but other than that I don't see a difference. I also tried to connect the mqtt5 client like this which also worked:

```
$ paho_c_sub -i myclient -t 'topic' -q 1 -V 5 
{"payload":""}
```

Where I'd then subscribed to the `foo/bar` topic programatically for the `myclient` client:

```
(VerneMQ@127.0.0.1)11> ClientId = <<"myclient">>.
(VerneMQ@127.0.0.1)12> vmq_reg:subscribe(true, {"", ClientId}, [{Topic, 1}]).
{ok,[1]}
```

Not sure what the difference is , but it seems to work as expected.

**Comment by manifest** [comment]
@larshesel the problem appears only when publishing from within VerneMQ node console, publishing from the external client works just fine. I will try to reproduce the bug without any plugins later.

```erlang
{_, Publish, _} = vmq_reg:direct_plugin_exports(mqttgw),
Publish(Topic, jsx:encode(#{<<"payload">> => <<>>}), #{qos => 1}).
```

**Comment by manifest** [comment]
@larshesel The problem was in the plugin. The `p_user_property` was initialized with an empty list as @dergraf correctly noted. I just got confused by the error message. Thanks for help.
