### ISSUE TITLE
vmq_bridge unable to handle topic prefixes with multiple levels

### ISSUE THREAD

**Issue by trarbr** [vernemq/vernemq#1229]
### Environment

- VerneMQ Version: master (commit bc153a4)
- OS: macOS High Sierra
- Erlang/OTP version (if building from source): 21.3
- VerneMQ configuration (vernemq.conf) or the changes from the default:

Configured a bridge as follows:

```
listener.tcp.default = 127.0.0.1:11883
plugins.vmq_bridge = on
vmq_bridge.tcp.br0 = 127.0.0.1:1883
vmq_bridge.tcp.br0.topic.1 = * out 1 to/central from/bridge
vmq_bridge.tcp.br0.topic.2 = * in 0 from/central to/bridge
vmq_bridge.tcp.br0.try_private = on
```

- Cluster size/standalone: N/A

### Expected behavior

When clients publish a message to the topic `from/central/foo` on the central broker, clients subscribed to `to/bridge/#` on the bridge broker should receive the message.

### Actual behaviour

vmq_bridge crashes due to no function clause matching: `[error] <0.397.0>@vmq_bridge:remove_prefix:259 gen_server <0.397.0> terminated with reason: no function clause matching vmq_bridge:remove_prefix([<<"to">>,<<"bridge">>], [<<"to">>,<<"bridge">>,<<"central-says">>]) line 259`

I suppose this can be fixed by changing the function to:

```erlang
remove_prefix(undefined, Topic) -> Topic;
remove_prefix([], Topic) -> Topic;
remove_prefix([Prefix|PrefixRest], [Prefix|TopicRest]) ->  remove_prefix(PrefixRest, TopicRest).
```

But even with that change it seems messages are not being published on the bridge... I guess my Erlang skills are failing me 😁

**Comment by ioolkos** [comment]
@trarbr thanks for opening the issue!
@dergraf bug or feature :) ?

**Comment by dergraf** [comment]
This is a missing feature. ;)

**Comment by saqib-cielo** [comment]
@larshesel : Is this feature working now with 1.10.3?

**Comment by ioolkos** [comment]
@saqib-cielo yes
