### ISSUE TITLE
Websocket loses messages

### ISSUE THREAD

**Issue by solanu** [vernemq/vernemq#1231]
### Description

I am using paho client js library with the lastest version of Chrome, connecting with the Debain vernemq server (local virtual machine). Most mqtt messages are lost when I use WS but when I use TCP all mqtt messages are rececived.

### Environment

- VerneMQ Version:  vernemq-1.8.0.stretch.x86_64
- OS: Debian GNU/Linux 9.9 (stretch)
- Erlang/OTP version (if building from source): -
- VerneMQ configuration (vernemq.conf) or the changes from the default: 
  - allow_anonymous = off
  - max_client_id_size = 100
  - listener.tcp.default = 127.0.0.1:1883
  - listener.ws.default = 0.0.0.0:9123
  - plugins.vmq_passwd = on
  - plugins.vmq_acl = on
  - vmq_acl.acl_file = /etc/vernemq/vmq.acl
  - vmq_passwd.password_file = /etc/vernemq/vmq.passwd

- Cluster size/standalone: I don't know (I have no config anything so I think standalone)

### Expected behavior

- Receive all mqtt messages from ws.

### Actual behaviour

- Very few messages are received (randomly).
- TCP listener works fine.

**Comment by ioolkos** [comment]
Is there anything you can think of that would make it easier for us to help you? have you researched this a little bit more?

(btw why do you need the WS listener on 0.0.0.0 and not just one network interface?)

**Comment by solanu** [comment]
> Is there anything you can think of that would make it easier for us to help you? have you researched this a little bit more?

I do not know. I can tell you that my web environment (paho js client) works fine with _Eclipse mosquitto_.

```
    var last= new Date();

    function MQTTconnect() {
        mqtt = new Paho.MQTT.Client("192.168.2.226", 9123, "/mqtt", "clientjs");
        var options = {
            timeout: 3,
            onSuccess: onConnect,
            userName : "user",
	    password : "pass"
        };
        mqtt.onMessageArrived = onMessageArrived;
        last= new Date();
        mqtt.connect(options);
    }

    function onConnect() {
        mqtt.subscribe("test/#");
    }

    function onMessageArrived(msg) {
        console.log(msg.destinationName, msg.payloadString);
        last= new Date();
    }
    MQTTconnect();
    setInterval(function() {
        var diff = new Date().getTime() - last.getTime();
        if (diff > 15000) { // 1000 * 15 = 15 seconds
            MQTTconnect();
        }
    }, 5000);
```
As you can see I have a `setInterval `to detect if there is no new data in the last 15 seconds, then I reconnect. So I think I have a new data when I reconnect.

> (btw why do you need the WS listener on 0.0.0.0 and not just one network interface?)

I am using 0.0.0.0 because when I use the IP of my netowrk interface, it does not work: `mqttws31.min.js:36 WebSocket connection to 'ws://192.168.2.226:9123/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by boboxiaodd** [comment]
The `setInterval` may create a lot of mqtt connection with same client_id

**Comment by dergraf** [comment]
@boboxiaodd good point, thanks! :+1: 

@solanu while not obvious but the `setInterval` mentioned by @boboxiaodd is likely the problem, especially as you mention that receiving messages isn't predictable. To give you context, if you connect with the same client id multiple times, VerneMQ will kick out any previous session. This will likely result in the experienced message drop.

Please fix the `setInterval` statement and reopen if the problem persists.
