### ISSUE TITLE
Support for Mongodb Replica Set Cluster

### ISSUE THREAD

**Issue by ncpe20012003** [vernemq/vernemq#1232]
Running VerneMQ 1.8.0 w/ 3 node replica set Mongodb.

Typically the replica set would be called by mongodb: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/dbname\_?

It appears VerneMQ only support one host for mongodb. Any plans to support replica set?

**Comment by dergraf** [comment]
Closing this issue as it's on our backlog already, but unfortunately it doesn't have high priority at the moment. Get in touch with us directly if you like to promote this feature via sponsoring.

**Comment by hongkongkiwi** [comment]
I would like this feature too. Any idea when it will be on the roadmap? I think in a high availability situation this is kind of essential.
