### ISSUE TITLE
Auth client: connection to MongoDB via SSL is not working

### ISSUE THREAD

**Issue by marsianin** [vernemq/vernemq#1234]
Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version: 1.8
- OS: Docker
- VerneMQ configuration (vernemq.conf) or the changes from the default
Follow parameters are specified
```  
vmq_diversity.mongodb.login=login
vmq_diversity.mongodb.password=password
vmq_diversity.mongodb.keyfile=/etc/ssl/mongo_client.key
vmq_diversity.mongodb.certfile=/etc/ssl/mongo_client.crt
vmq_diversity.mongodb.database=db
vmq_diversity.mongodb.port=27017
vmq_diversity.auth_mongodb.enabled=on
vmq_diversity.mongodb.cafile=/etc/ssl/ca.crt
vmq_diversity.mongodb.ssl=on
vmq_diversity.mongodb.host=mongodb
```

- Cluster size/standalone: standalone

### Expected behavior

That auth client via mongoDB SSL auth-db provider is working. I.e. setup connection and working. But

`
### Actual behaviour

Connection up to mongoDb could not be setup. What i see in stdout log:
...
09:27:50.028 [warning] Could not connect to mongodb due to closed
09:27:50.028 [warning] Could not connect to mongodb due to closed
09:27:50.028 [warning] Could not connect to mongodb due to closed
09:27:50.028 [warning] Could not connect to mongodb due to closed
09:27:51.056 [warning] Could not connect to mongodb due to closed
09:27:51.056 [warning] Could not connect to mongodb due to closed
09:27:51.057 [warning] Could not connect to mongodb due to closed
09:27:51.057 [warning] Could not connect to mongodb due to closed
09:27:51.058 [warning] Could not connect to mongodb due to closed
...
`

I checked ssl-connectivity via:

`openssl s_client -connect mongodb:27017 -CAfile /etc/ssl/ca.crt -nbio -debug -msg -state -cert /etc/ssl/mongo_client.crt -key /etc/ssl/mongo_client.key`
and it is OK:

`...
04a0 - 89 3c 45 9c 39 d7 7d f5-ce 80 15 ba 83 19 66 76   .<E.9.}.......fv
    04b0 - 05 89 1e 5a 78 2b c7 09-10 4b 67 11 4d ee 8e 82   ...Zx+...Kg.M...

    Start Time: 1561713308
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no`

it means that ssl-connectivity is OK. I also could connect with the same credentials(login/password) and ssl cert+key pair to the mongoDB server.

**Comment by dergraf** [comment]
Thanks for opening the issue. Do you see any suspicious logs on the Mongo DB instance? Moreover how does your CA.crt look like? Does it contain intermediate certificates?

**Comment by marsianin** [comment]
Hello @dergraf 
1) CA.crt contains rootCA+intermediate CA(i'm testing on self-signed chains)
2) About mongo DB: 2 lines per connection: connection is opened and right after closed(by broker)

**Comment by larshesel** [comment]
Hi, have you found any other information since last ? Did you find a workaround? From the logs above I'm not sure what's going on - does it work with VerneMQ + MongoDB if you configure it to not use TLS at all at both ends?

**Comment by marsianin** [comment]
My workaround is use sidecar-container or proxy before Mongo which convert plain->ssl. 
Without TLS - it works correctly. 
What kind of debug need to add ?
I have debug with openssl_server and openssl_client and it is OK. And solution with proxy is working.

**Comment by larshesel** [comment]
>  What kind of debug need to add ?

not sure ;)

My guess is that the certs is in some format which VerneMQ (Erlang) doens't like - perhaps you can compare them to the test ones which are located here: https://github.com/vernemq/vernemq/tree/master/apps/vmq_server/test/ssl. The relevant files are all-ca.crt, server.crt, server.key and for the client client.crt and client.key. Perhaps there's some difference there?

**Comment by marsianin** [comment]
Ok I will try

**Comment by larshesel** [comment]
Hi - did you figure out the problem? I'll close this for now - feel free to reopen if more information becomes available.

**Comment by seguidor777** [comment]
> > What kind of debug need to add ?
> 
> not sure ;)
> 
> My guess is that the certs is in some format which VerneMQ (Erlang) doens't like - perhaps you can compare them to the test ones which are located here: https://github.com/vernemq/vernemq/tree/master/apps/vmq_server/test/ssl. The relevant files are all-ca.crt, server.crt, server.key and for the client client.crt and client.key. Perhaps there's some difference there?

Hello! What kind of certificates are they? Is there any guide to see how to generate them?

**Comment by marsianin** [comment]
Hello @seguidor777 it is normal SSL certificates. You could use https://mosquitto.org/man/mosquitto-tls-7.html guide i think

**Comment by seguidor777** [comment]
I just tried to convert my existing certs with `openssl x509 -in src-ca.pem -text -out dst-ca.pem` without success
@marsianin Thanks for the great help! I will take a look
