### ISSUE TITLE
how to recover clustering with 2 nodes  to 2 single nodes

### ISSUE THREAD

**Issue by FONGYEE** [vernemq/vernemq#1236]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version: 1.3.0
- OS: Ubuntu 14.04.5 LTS
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
     vernemq.conf changes are:
     1.  listener.ws.default = 172.21.85.82:8883
          listener.ws.default = 172.21.85.83:8883
     2. listener.vmq.clustering = 172.21.85.82:44053
         listener.vmq.clustering = 172.21.85.83:44053
     3. nodename = VerneMQ@172.21.85.82
        nodename = VerneMQ@172.21.85.83
     4. distributed_cookie = vmq_yeefang

- Cluster size/standalone:  cluster with 2 nodes

### Expected behavior

- Please describe the expected behaviour.
   1. first setup cluster at node VerneMQ@172.21.85.82
       vmq-admin cluster join discovery-node=VerneMQ@172.21.85.83
   2. wcsadmin@mtkmqttq01:~$ sudo vmq-admin cluster show
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@172.21.85.82| true  |
|VerneMQ@172.21.85.83| true  |
+--------------------+-------+
   3. then cancel node to make 2 nodes come back to single nodes,  Expect see no cluster exist

### Actual behaviour

- Actual:  still the cluster exist, and with only one node respectively
wcsadmin@mtkmqttq01:~$ sudo vmq-admin cluster show
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@172.21.85.82| true  |
+--------------------+-------+

wcsadmin@mtkmqttq02:~$ sudo vmq-admin cluster show
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@172.21.85.83| true  |
+--------------------+-------+

**Comment by dergraf** [comment]
What you see is actually correct. To prove that you can start a single node and then execute `vmq-admin cluster show` and you would see the same thing, this is what we call a "single-node cluster".

**Comment by dergraf** [comment]
Closing, please feel free to reopen with more input.
