### ISSUE TITLE
Share subscription : Is there any sharename limitation? Too long sharename 

### ISSUE THREAD

**Issue by nrvmodi** [vernemq/vernemq#1238]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version: erlio/docker-vernemq:1.7.1-2
- OS: UBUNTU 18.04
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 3 nodes

### Expected behavior

- I have a 3 node cluster using docker with network mode host.
The client application had subscribed multiple topics using shared subscriptions.

### Actual behavior

- $share/rayStatistics/students/#
Here 'rayStatistics' is my sharename.

I have observed that when the name is too long then subscription behavior unpredictable.
Some time Client application receives the message and sometimes not.

I had tried with multiple share name.

- $share/test/students/#
Here 'test' is my sharename.
Which is working fine.

So Is there any limitation in sharename?

**Comment by ioolkos** [comment]
@nrvmodi thanks for opening this issue. 
I think there should not be a limit on the share name. We'll check if this is a possible bug. Please let us know if you have gathered any additional information in the mean time.

**Comment by dergraf** [comment]
@nrvmodi VerneMQ doesn't apply a limit. Please provide us with the exact topic you're experiencing the issue to further investigate the issue. Thanks.

**Comment by nrvmodi** [comment]
@ioolkos I know there is no reason to make this type of limitation but I had faced with below topic names

$share/rayStatistics/ssidStats,
$share/rayStatistics/stations/#,
$share/rayStatistics/clients/websocket/#,
$share/rayStatistics/internet/#,
$share/rayStatistics/node/stats/health,
$share/rayStatistics/visitedsites/#,
$share/rayStatistics/userSessions/#

So when I used the above topic names, Paho java consumer client not receive 100% messages.
but I had renamed with the below names, It worked. 

$share/stat/ssidStats,
$share/stat/stations/#,
$share/stat/clients/websocket/#,
$share/stat/internet/#,
$share/stat/node/stats/health,
$share/stat/visitedsites/#,
$share/stat/userSessions/#

**Comment by larshesel** [comment]
Hi, thanks for the feefback - can you describe a mimimal setup/steps on how to reproduce this?

**Comment by nrvmodi** [comment]
I have created two configurations.
1. Publisher: publish data on the above topics

In our case, the publisher is a Lua based script which will publish messages on above topics.

2. Multiple shared Subscriber: subscribe data on the above topics

We have used the Paho java client library to subscribe to the topics using the shared subscription.

**Comment by nrvmodi** [comment]
In a simple way to reproduce the issue,

create a paho java client subscriber which can subscribe on any topic with long share name.

**Comment by larshesel** [comment]
Hi,

I wasn't able to reproduce this with the mosquitto clients:

```
$ mosquitto_sub -t '$share/verylongsharedsubscribergroupname/hello'  
hello
```

I published using `mosquitto_pub -t hello -m hello`. So this does not seem to be a VerneMQ issue - perhaps there are some limitations with the paho java client?

**Comment by nrvmodi** [comment]
We have faced this issue with the heavy load.

Can you try with a heavy load?

**Comment by larshesel** [comment]
Hi - my feeling is this does not have anything to do with the long shared subscriber groups names but something else then. There is nothing special about how the shared subscriber group names are handled when they are longer or shorter.

I'm afraid we can't put in the resources to set up a test-rig under load without more concrete information to support the hypothesis (that longer shared subscriber groups causes this problem) - for example are there any errors in the logs when this happens?

**Comment by nrvmodi** [comment]
No there is no error in vernemq.
May be the problems with Paho client.
Thanks

**Comment by larshesel** [comment]
ok - I'll close this for now then - feel free to reopen if more information becomes available.
