### ISSUE TITLE
vmq-admin gives Error: Usage information not found

### ISSUE THREAD

**Issue by kellycampbell** [vernemq/vernemq#1245]
### Environment

- VerneMQ Version: `erlio/docker-vernemq:1.8.0-alpine`
- OS: `kubernetes 1.11.10, kops 1.11, Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64    
docker://17.3.2`
    Note: not using vernemq k8s operator yet

- VerneMQ configuration (vernemq.conf) or the changes from the default

From statefulset yaml:
```
env:
- name: MY_POD_NAME
    valueFrom:
    fieldRef:
        fieldPath: metadata.name
- name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
    value: "1"
- name: DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR
    value: "k8s-app=gwmq"
# This listener is required to get port forwarding working
- name: DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST
    value: "127.0.0.1:1883"
```

ConfigMap env vars:
```

DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: info
DOCKER_VERNEMQ_DISTRIBUTED_COOKIE: <redacted>
DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION: 1h
DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "on"
DOCKER_VERNEMQ_VMQ_DIVERSITY__GW_AUTH_HOOK__FILE: /etc/vernemq-cfg/gw_auth_hook.lua
DOCKER_VERNEMQ_LISTENER__SSL__GW: 0.0.0.0:8883
DOCKER_VERNEMQ_LISTENER__SSL__GW__CAFILE: /ssl/ca_roots.pem
DOCKER_VERNEMQ_LISTENER__SSL__GW__CERTFILE: /ssl/mqtt-cert.pem
DOCKER_VERNEMQ_LISTENER__SSL__GW__KEYFILE: /ssl/mqtt-key.pem
DOCKER_VERNEMQ_LISTENER__SSL__GW__REQUIRE_CERTIFICATE: "on"
DOCKER_VERNEMQ_LISTENER__SSL__GW__USE_IDENTITY_AS_USERNAME: "on"
DOCKER_VERNEMQ_LISTENER__SSL__GW__MAX_CONNECTIONS: "100000"
DOCKER_VERNEMQ_LISTENER__SSL__GW__MOUNTPOINT: gw_secure
DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES: "10000"

# Increase capacity before load-shedding kicks in
DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES: "1000"
DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES: "100"

# VerneMQ stops doing stuff if any member of the cluster is missing.
# We want to go ahead and keep messaging running in that case.
# Under Kubernetes, the pod IP is used as the erlang node identifier,
# so any change to the pod causes cluster nodes to be missing.
DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT: "on"
DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT: "on"
DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT: "on"
DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT: "on"

# try new swc instead of plumtree
DOCKER_VERNEMQ_METADATA_PLUGIN: vmq_swc
```

- Cluster size/standalone: `either 1 or 2 nodes`

### Expected behavior

Expected vmq-admin to show sessions or cluster info. Also expected vernemq to keep accepting new connections.

### Actual behaviour

Vernemq got restarted by k8s (not sure of reason yet, still investigating that), and after the restart it wouldn't accept new connections. Upon execing into the pod, all vmq-admin commands give the following:

```
bash-4.4# vmq-admin session show
Error: Usage information not found for the given command
```

Restarting the pod several times, it will sometimes work, but most of the time it will continue to have the above issues. We ended up reverting to a previous version, using the old cluster technology, and erasing the state volume to get it to start ok.

**Comment by kellycampbell** [comment]
FYI, took us a little while to find this but here's where we think the error message we're seeing comes from:

https://github.com/basho/clique/blob/01a99227a4eb546a9beda763bb5aea6189285a4f/src/clique_usage.erl#L73

**Comment by larshesel** [comment]
Hi, I believe this happens when VerneMQ hasn't starting reading data from the messagestore and the CLI hasn't been initialized yet.

**Comment by kellycampbell** [comment]
Is there something about the new swc clustering or 1.8.0 that could cause it to take a longer time to initialize? We're giving it 90 seconds from pod startup to become healthy, but it's not working within that time.

**Comment by kellycampbell** [comment]
I restarted one of our test pods that was having the problem and captured the error and crash logs here:

https://gist.github.com/kellycampbell/46f44b271f97a51a8afcd6c2d2381676

**Comment by larshesel** [comment]
I don't think this is related to swc which could make vernemq load slower. Lots of messages in the messages store would - to that end we've just pushed some changes to the master branch which will make VerneMQ much faster at loading oflfine messages from the msg store.

Regarding the crashes above I'd need some more context - I just see a bunch of processes being killed, but not any reason for it - what happened before this happened? Are there any logs before this?

**Comment by kellycampbell** [comment]
It looks like I misread the crash reports. They are actually from the previous instance of the pod and are the result of terminating the pod normally. The subsequent startup is the one that took a long time and cause the pod to go into a crashloop.

This log message is a bit before the crashes:
13:37:40.352 [info] Administrative stop

We shouldn't have lots of messages left in our store, but I will check into that. Maybe we're storing stuff we didn't mean to. We will retest with the updated code when we are able to and see if it fixes the startup time.

**Comment by larshesel** [comment]
ok - I'll then close this for now. Feel free to reopen if needed.
