### ISSUE TITLE
Add `username` modifier for `auth_on_register` hooks

### ISSUE THREAD

**Issue by dergraf** [vernemq/vernemq#1246]

**Comment by dergraf** [comment]
https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_mqtt_fsm.erl#L641

**Comment by larshesel** [comment]
Note, to make it available in plugins the modifier checker should be amended to allow it: 

https://github.com/vernemq/vernemq/blob/master/apps/vmq_plugin/src/vmq_plugin_util.erl#L99
