### ISSUE TITLE
Configuring VerneMQ though ENV vars

### ISSUE THREAD

**Issue by drasko** [vernemq/vernemq#1247]
### Environment

- VerneMQ Version: 1.8.0
- OS: Docker
- Erlang/OTP version (if building from source): 21
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behavior
I have set:
```
DOCKER_VERNEMQ_PLUGINS.VMQ_PASSWD: "off"
DOCKER_VERNEMQ_PLUGINS.VMQ_ACL: "off"
```
in docker compose, and expected vars in conf file in docker to be set to "off"

### Actual behaviour
In the container:

```/mainflux $ cat /etc/vernemq/vernemq.conf | grep passwd
plugins.vmq_passwd = on
## Default: ./etc/vmq.passwd
vmq_passwd.password_file = ./etc/vmq.passwd
vmq_passwd.password_reload_interval = 10
/mainflux $ 
```

**Comment by drasko** [comment]
Additionally, is it possible to add some other vars that do not exist in the config file via ENV vars?

Point is that I would like to enable my plugin, but it does not exist in the config file.

**Comment by larshesel** [comment]
Hi, you should use double underscore for dots as described in the docker readme: https://github.com/vernemq/docker-vernemq#remarks

So use `DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD=off` to disable the `vmq_passwd` plugin.

Hope this helps.

**Comment by larshesel** [comment]
Actually the docs there says dots should work - haven't tried that - but with double underscores it worked.. will test the dot version...

**Comment by larshesel** [comment]
Looks like with the dot version that there's a bug where the plugin name isn't lowercased. So the appended part of vernemq.conf looks like: 

```
########## Start ##########
plugins.VMQ_PASSWD=off
log.console=console
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 172.17.0.2:1883
listener.ws.default = 172.17.0.2:8080
listener.vmq.clustering = 172.17.0.2:44053
listener.http.metrics = 172.17.0.2:8888
########## End ##########
```

Could you open an issue for this on the docker-vernemq repo? Thanks
