### ISSUE TITLE
vernemq performance test

### ISSUE THREAD

**Issue by jeremyLi1990** [vernemq/vernemq#1263]
#941 # Environment

- VerneMQ Version:
- OS:Centos 7
- Erlang/OTP version (if building from source): Erlang/OTP 20 [erts-9.3] [source] [64-bit]
- VerneMQ configuration (vernemq.conf) or the changes from the default (changed the maxconnections to 1000000/1 million)
- Cluster size/standalone: standalone

### Expected behavior

- I used the same machine(8 cores cpu and 32G ram), when i test with mosquitto with 6 vps, each vps makes 50000 subscribe,  and i find it can reach about 300000 connections。
but when i stop mosquitto and start vernemq to do the same test, i find the max connections is about 60000。 

I want to use vernemq broker since it is easy to build a broker cluster,  what kind of paramters need i configre to impove the performance of vernemq?  is there any solutions?  thanks！

**Comment by larshesel** [comment]
Hi,

Thanks for opening the issue - unfortunately we can't help without knowing what kind of limit it is you're running into. You might find some good advice in other older issues - the 60000 number is usually some kind of port exhaustion problem, though.

As this isn't really a bug report or feature request I'll close it for now - you're also welcome to ask on the community slack channel https://slack-invite.vernemq.com/ but more information will be needed to be able to help.

Hope this helps.
