### ISSUE TITLE
Configure number of active connections to DB

### ISSUE THREAD

**Issue by pramodhkp** [vernemq/vernemq#1269]
### Expected behavior

Have a way to configure the number of connections that VerneMQ maintains to the DB

### Actual behaviour

VerneMQ maintains 10 connections right now.

**Comment by larshesel** [comment]
I believe you can set pool_size on the database. For example `vmq_diversity.postgres.pool_size`.

**Comment by pramodhkp** [comment]
That's awesome! thank you! Looks like it's not mentioned in the docs or the config file.

**Comment by pramodhkp** [comment]
I tried it out but it doesn't seem to reduce the number of connections. It still holds 10 connections. I want to reduce it to 5.
