### ISSUE TITLE
Pattern doesn't work

### ISSUE THREAD

**Issue by iandriyanov** [vernemq/vernemq#1271]
### Environment

- VerneMQ Version: 1.8.0
- OS: Ubuntu 18.04
- Cluster size/standalone: Standalone

Vernemq.conf
`
allow_anonymous = off
allow_multiple_sessions = off
allow_publish_during_netsplit = off
allow_register_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
coordinate_registrations = on
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
graphite_enabled = off
graphite_host = localhost
graphite_interval = 20000
graphite_port = 2003
leveldb.maximum_memory.percent = 70
listener.http.default = 127.0.0.1:8888
listener.max_connections = 10000
listener.mountpoint = off
listener.nr_of_acceptors = 10
listener.tcp.default = 0.0.0.0:11883
listener.vmq.clustering = 0.0.0.0:44053
listener.ws.default = 0.0.0.0:18083
log.console = file
log.console.file = /var/log/vernemq/console.log
log.console.level = debug
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
log.crash.size = 10MB
log.error.file = /var/log/vernemq/error.log
log.syslog = off
max_inflight_messages = 20
max_message_size = 0
max_offline_messages = 1000
max_online_messages = 1000
metadata_plugin = vmq_plumtree
nodename = VerneMQ@127.0.0.1
plugins.vmq_acl = on
plugins.vmq_bridge = off
plugins.vmq_diversity = off
plugins.vmq_passwd = on
plugins.vmq_webhooks = off
shared_subscription_policy = prefer_local
systree_enabled = on
systree_interval = 20000
upgrade_outgoing_qos = off
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_bcrypt.pool_size = 1
vmq_diversity.auth_cockroachdb.enabled = off
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_redis.enabled = off
vmq_diversity.cockroachdb.password_hash_method = bcrypt
vmq_diversity.cockroachdb.ssl = on
vmq_diversity.mongodb.ssl = off
vmq_diversity.mysql.password_hash_method = password
vmq_diversity.postgres.password_hash_method = crypt
vmq_diversity.postgres.ssl = off
vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10
`

vmq.acl
`
pattern write devices/%u/#
pattern read devices/%u/#
`

I can write on topic, but can't read from it

**Comment by iandriyanov** [comment]
If i edit acl file like this:
`
pattern read|write #
`
I mean all wild topic #, it's work correctly, but it's not securely

**Comment by larshesel** [comment]
Hi, when you say you can't read from the topic I suppose you're not receiving any messages. Could you do a trace of the subscriber and show what the output is. See https://docs.vernemq.com/administration/tracing for how to do traces.

**Comment by iandriyanov** [comment]
`
<9262.469.0> MQTT RECV: CID: "client_ac82f6a7" PUBLISH(d0, q0, r0, m0, "devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test") with payload:
    ping
<9262.469.0> Calling auth_on_publish(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                           <<"client_ac82f6a7">>},0,devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test,false) with payload:
    ping
<9262.469.0> Hook returned "ok"
<9262.469.0> MQTT RECV: CID: "client_ac82f6a7" PUBLISH(d0, q0, r0, m0, "devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test") with payload:
    ping
<9262.469.0> Calling auth_on_publish(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                           <<"client_ac82f6a7">>},0,devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test,false) with payload:
    ping
<9262.469.0> Hook returned "ok"
<9262.469.0> MQTT RECV: CID: "client_ac82f6a7" PUBLISH(d0, q0, r0, m0, "devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test") with payload:
    ping
<9262.469.0> Calling auth_on_publish(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                           <<"client_ac82f6a7">>},0,devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test,false) with payload:
    ping
<9262.469.0> Hook returned "ok"

`

**Comment by larshesel** [comment]
Hi, could you do the trace for the subscriber?

**Comment by iandriyanov** [comment]
It's the same

**Comment by iandriyanov** [comment]
`# cat etc/vmq.acl 
user backoffice
topic #
topic read $SYS/#

pattern read devices/%u/#
pattern write devices/%u/#

`

**Comment by larshesel** [comment]
there are no SUBSCRIBE frames captured in the trace  - so your client isn't subscribing and hence will never receive any messages.

**Comment by iandriyanov** [comment]
> New session with PID <9262.655.0> found for client "client_123321"
<9262.655.0> MQTT RECV: CID: "client_123321" CONNECT(c: client_123321, v: 4, u: f370dd42-b96b-4f5b-8b39-7bd4c068ad4f, p: ct4GQZHMvyyeFDNUVymiZcRIUFMq2k0F, cs: 1, ka: 60)
<9262.655.0> Calling auth_on_register({{176,59,38,80},41366},{[],
                                                              <<"client_123321">>},f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,ct4GQZHMvyyeFDNUVymiZcRIUFMq2k0F,true) 
<9262.655.0> Hook returned "ok"
<9262.655.0> MQTT SEND: CID: "client_123321" CONNACK(sp: 0, rc: 0)
<9262.655.0> MQTT RECV: CID: "client_123321" SUBSCRIBE(m1) with topics:
    q:0, t: "#"
<9262.655.0> Calling auth_on_subscribe(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                             <<"client_123321">>}) with topics:
    q:0, t: "#"
<9262.655.0> Hook returned {error,chain_exhausted}
<9262.655.0> MQTT SEND: CID: "client_123321" SUBACK(m1, qt[not_allowed])
<9262.655.0> MQTT RECV: CID: "client_123321" SUBSCRIBE(m2) with topics:
    q:0, t: "$SYS/#"
<9262.655.0> Calling auth_on_subscribe(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                             <<"client_123321">>}) with topics:
    q:0, t: "$SYS/#"
<9262.655.0> Hook returned {error,chain_exhausted}
<9262.655.0> MQTT SEND: CID: "client_123321" SUBACK(m2, qt[not_allowed])
<9262.655.0> MQTT RECV: CID: "client_123321" PUBLISH(d0, q0, r0, m0, "devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test") with payload:
    ping
<9262.655.0> Calling auth_on_publish(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                           <<"client_123321">>},0,devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test,false) with payload:
    ping
<9262.655.0> Hook returned "ok"
<9262.655.0> MQTT RECV: CID: "client_123321" PUBLISH(d0, q0, r0, m0, "devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test") with payload:
    ping
<9262.655.0> Calling auth_on_publish(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                           <<"client_123321">>},0,devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test,false) with payload:
    ping
<9262.655.0> Hook returned "ok"

**Comment by iandriyanov** [comment]
> there are no SUBSCRIBE frames captured in the trace - so your client isn't subscribing and hence will never receive any messages or the trace isn't complete - try to start the trace before connecting the client.

This client (with login and password) uses for both operations: pub and sub. And as i see auth_on_sub (# and $SYS/#) it gets, And on devices/f370dd42-b96b-4f5b-8b39-7bd4c068ad4f/test no

**Comment by larshesel** [comment]
The username specified in the acl file is `backoffice` so the non-pattern rules doesn't apply for the username you're using which is `f370dd42-b96b-4f5b-8b39-7bd4c068ad4f` - so only the pattern rules apply for the username you're connecting with.

See https://docs.vernemq.com/configuration/file-auth#managing-the-acl-entries for the details.

Hope this helps.

**Comment by iandriyanov** [comment]
> The username specified in the acl file is `backoffice` so the non-pattern rules doesn't apply for the username you're using which is `f370dd42-b96b-4f5b-8b39-7bd4c068ad4f` - so only the pattern rules apply for the username you're connecting with.

How to apply rules for all user? U mean i must define all my 100k devices?

**Comment by larshesel** [comment]
From the docs:

```
Pattern ACLs apply to all users even if the user keyword has previously been given.
```

Hope this helps.
