### ISSUE TITLE
Hash/pound character in topic causes `chain_exhausted` error

### ISSUE THREAD

**Issue by adamcharnock** [vernemq/vernemq#1272]
### Environment

- VerneMQ Version: `1.8.0` (docker)
- OS: Docker, connecting from macOS and Linux
- Erlang/OTP version (if building from source): Not building from source
- [vernemq.conf.txt](https://github.com/vernemq/vernemq/files/3438067/vernemq.conf.txt) (txt extension to force GitHub to accept upload). Extracted from docker container.
- Cluster size/standalone: Standalone

#### /etc/vernemq/vmq.acl

```
topic #
```

#### /etc/vernemq/vmq.passwd

(passwords are `test_password`)

```
test_user:$6$MHbMvdlJIZV7IA7g$mrV9ADFxlTQRPruAhGV8wojL4uNfC4n3hiHjlQOrxllVZplev1CJ/Tx0oTV7kxN0mRSe5l0tuDjvUqNtaT/PUQ==
debugging_user:$6$pP8Zyl9YGHPSINjh$yJhWxNf9VLQGBWSaT1SynlZjR0puEhpTwaQaN9Y71tO4YRZQeJALYQGRT8Q2KZiC1/ZKEgGr8rQthJULdZZIWA==
```

### Expected behavior

Subscribing to a topic such as `device/#/data` should be possible. I normally see the hash/pound (`#`) character used at the end of a topic, but I haven't seen an explicit statement that it cannot be used within a topic. Of course I may have missed this, I confess I haven't read the spec in detail.

### Actual behaviour

MQTT client (python, [paho-mqtt](https://pypi.org/project/paho-mqtt/)) hangs on attempt to subscribe. The vernemq log reports:

```
vernemq_1  | 10:27:37.311 [warning] can't authenticate client {[],<<"test_user">>} from 192.168.224.1:60660 due to chain_exhausted
```

**Comment by larshesel** [comment]
Hi, having the `#` wildcard in the middle of a topic isn't allowed. From the MQTT spec section:
```
4.7.1.2 Multi-level wildcard

The number sign (‘#’ U+0023) is a wildcard character that matches any number of levels within a topic. The multi-level wildcard represents the parent and any number of child levels. The multi-level wildcard character MUST be specified either on its own or following a topic level separator. In either case it MUST be the last character specified in the Topic Filter [MQTT-4.7.1-2].
``

**Comment by adamcharnock** [comment]
Ah ok, thank you for pointing this out to me @larshesel. Hopefully this issue will save someone else some time in the future.
