### ISSUE TITLE
acl doesn't work again

### ISSUE THREAD

**Issue by iandriyanov** [vernemq/vernemq#1276]
The username specified in the acl file is `backoffice` so the non-pattern rules doesn't apply for the username you're using which is `f370dd42-b96b-4f5b-8b39-7bd4c068ad4f` - so only the pattern rules apply for the username you're connecting with.

See https://docs.vernemq.com/configuration/file-auth#managing-the-acl-entries for the details.

Hope this helps.

_Originally posted by @larshesel in https://github.com/vernemq/vernemq/issues/1271#issuecomment-516047319_

**Comment by iandriyanov** [comment]
> New session with PID <9262.461.0> found for client "client_123321"
<9262.461.0> MQTT RECV: CID: "client_123321" CONNECT(c: client_123321, v: 4, u: f370dd42-b96b-4f5b-8b39-7bd4c068ad4f, p: ct4GQZHMvyyeFDNUVymiZcRIUFMq2k0F, cs: 1, ka: 60)
<9262.461.0> Calling auth_on_register({{176,59,38,80},42208},{[],
                                                              <<"client_123321">>},f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,ct4GQZHMvyyeFDNUVymiZcRIUFMq2k0F,true) 
<9262.461.0> Hook returned "ok"
<9262.461.0> MQTT SEND: CID: "client_123321" CONNACK(sp: 0, rc: 0)
<9262.461.0> MQTT RECV: CID: "client_123321" SUBSCRIBE(m1) with topics:
    q:0, t: "#"
<9262.461.0> Calling auth_on_subscribe(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                             <<"client_123321">>}) with topics:
    q:0, t: "#"
<9262.461.0> Hook returned {error,chain_exhausted}
<9262.461.0> MQTT SEND: CID: "client_123321" SUBACK(m1, qt[not_allowed])
<9262.461.0> MQTT RECV: CID: "client_123321" SUBSCRIBE(m2) with topics:
    q:0, t: "$SYS/#"
<9262.461.0> Calling auth_on_subscribe(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                             <<"client_123321">>}) with topics:
    q:0, t: "$SYS/#"
<9262.461.0> Hook returned {error,chain_exhausted}
<9262.461.0> MQTT SEND: CID: "client_123321" SUBACK(m2, qt[not_allowed])





<9262.461.0> MQTT RECV: CID: "client_123321" PUBLISH(d0, q0, r0, m0, "devices/123/test") with payload:
    test
<9262.461.0> Calling auth_on_publish(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                           <<"client_123321">>},0,devices/123/test,false) with payload:
    test
<9262.461.0> Hook returned "ok"
<9262.461.0> MQTT RECV: CID: "client_123321" PINGREQ()
<9262.461.0> MQTT SEND: CID: "client_123321" PINGRESP()

>vernemq# cat etc/vmq.acl 
user f370dd42-b96b-4f5b-8b39-7bd4c068ad4f
topic devices/#

**Comment by iandriyanov** [comment]
Is it ACL:
> user f370dd42-b96b-4f5b-8b39-7bd4c068ad4f
topic devices/#

Is it trace of TCP connection from mqtt-admin:
`New session with PID <9262.673.0> found for client "client_123321"
<9262.673.0> MQTT RECV: CID: "client_123321" CONNECT(c: client_123321, v: 3, u: f370dd42-b96b-4f5b-8b39-7bd4c068ad4f, p: ct4GQZHMvyyeFDNUVymiZcRIUFMq2k0F, cs: 1, ka: 60)
<9262.673.0> Calling auth_on_register({{176,59,38,80},34470},{[],
                                                              <<"client_123321">>},f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,ct4GQZHMvyyeFDNUVymiZcRIUFMq2k0F,true) 
<9262.673.0> Hook returned "ok"
<9262.673.0> MQTT SEND: CID: "client_123321" CONNACK(sp: 0, rc: 0)
<9262.673.0> MQTT RECV: CID: "client_123321" SUBSCRIBE(m1) with topics:
    q:0, t: "devices/test"
<9262.673.0> Calling auth_on_subscribe(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                             <<"client_123321">>}) with topics:
    q:0, t: "devices/test"
<9262.673.0> Hook returned "ok"
<9262.673.0> MQTT SEND: CID: "client_123321" SUBACK(m1, qt[0])
`

Is it WS connection:
`
New session with PID <9262.733.0> found for client "client_123321"
<9262.733.0> MQTT RECV: CID: "client_123321" CONNECT(c: client_123321, v: 4, u: f370dd42-b96b-4f5b-8b39-7bd4c068ad4f, p: ct4GQZHMvyyeFDNUVymiZcRIUFMq2k0F, cs: 1, ka: 60)
<9262.733.0> Calling auth_on_register({{176,59,38,80},42444},{[],
                                                              <<"client_123321">>},f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,ct4GQZHMvyyeFDNUVymiZcRIUFMq2k0F,true) 
<9262.733.0> Hook returned "ok"
<9262.733.0> MQTT SEND: CID: "client_123321" CONNACK(sp: 0, rc: 0)
<9262.733.0> MQTT RECV: CID: "client_123321" SUBSCRIBE(m1) with topics:
    q:0, t: "#"
<9262.733.0> Calling auth_on_subscribe(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                             <<"client_123321">>}) with topics:
    q:0, t: "#"
<9262.733.0> Hook returned {error,chain_exhausted}
<9262.733.0> MQTT SEND: CID: "client_123321" SUBACK(m1, qt[not_allowed])
<9262.733.0> MQTT RECV: CID: "client_123321" SUBSCRIBE(m2) with topics:
    q:0, t: "$SYS/#"
<9262.733.0> Calling auth_on_subscribe(f370dd42-b96b-4f5b-8b39-7bd4c068ad4f,{[],
                                                                             <<"client_123321">>}) with topics:
    q:0, t: "$SYS/#"
<9262.733.0> Hook returned {error,chain_exhausted}
<9262.733.0> MQTT SEND: CID: "client_123321" SUBACK(m2, qt[not_allowed])
`
@larshesel 
As you see, no one define topic from ACL list are not sub.

**Comment by larshesel** [comment]
Hi, I'm not sure what the question is here. Please follow the issue template and show what you do, what the expectation was and what the actual result was.
