### ISSUE TITLE
vmq-admin shows session is online ,but no this session when trace this client

### ISSUE THREAD

**Issue by chenxinlong** [vernemq/vernemq#1277]
### Environment

- VerneMQ Version: 1.7.1
- OS: CentOS 7 
- Erlang/OTP version (if building from source): 
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 5 nodes

### Expected behavior

What I expected is :   

1. The result of `vmq-admin session show` show full text. 
2.  As the pic below, the client `06fc9d8f7e3f2f576d5f9257e4e6` (actually the full client-id is `06fc9d8f7e3f2f576d5f9257e4e655e1`) is online in the result of `vmq-admin session show` ,  and when I trace this client-id, there should be existed a session. 

![image](https://user-images.githubusercontent.com/9261954/62104216-84f3f400-b2d1-11e9-88ad-b9c191abe429.png)

### Actual behaviour

1. The result of `vmq-admin session show` does not show the full text even the table header.    
2.  As the pic above, the client `06fc9d8f7e3f2f576d5f9257e4e6` (actually the full client-id is `06fc9d8f7e3f2f576d5f9257e4e655e1`) is online in the result of `vmq-admin session show` , but the result is `No sessions found` in `vmq-admin trace client`.

**Comment by larshesel** [comment]
Hi,

The truncated entries in `vmq-admin session show` is a known issue, currently
without a good workaround, see https://github.com/vernemq/vernemq/issues/1200.

Alternatively you can filter out less information - for instance `vmq-admin
session show --client_id --is_online` to give more room to the client id.

Hope this help

**Comment by chenxinlong** [comment]
Hi, except the truncated entries problem, is there anyway to solve the second problem?  

![image](https://user-images.githubusercontent.com/9261954/62106401-b66fbe00-b2d7-11e9-8346-b0b57607d007.png)

**Comment by larshesel** [comment]
Aha, I didn't realize there was a second question in there :-) please only ask one question per issue. Anyway, are you in a cluster? Note if the client isn't connected to the node where the trace is being done then it won't work. You can see the nodename by passing `vmq-admin session show --client_id --node`.

**Comment by chenxinlong** [comment]
Thanks, `vmq-admin session show --client_id --node` solved my problem.
