### ISSUE TITLE
Will Message is not published when client sends Disconnect Notification with Reason Code 0x04 (Disconnect with Will Message)

### ISSUE THREAD

**Issue by wlisac** [vernemq/vernemq#1291]
### Environment

- VerneMQ Version: 1.9.0
- Docker: erlio/docker-vernemq:latest
- VerneMQ configuration (vernemq.conf) default, with this env var set:
    - `DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=3,4,5`
- Cluster size/standalone: Single docker container

### Expected behavior

I'm expecting the client's Will Message to be published when the client sends a Disconnect Notification with Reason Code 0x04 (Disconnect with Will Message).

### Actual behaviour

- Connect to VerneMQ broker with a Will Message (and Will Delay Interval of 0) using version 5.0 of the MQTT protocol
- Send Disconnect Notification with [Reason Code 0x04](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901208) (Disconnect with Will Message)
- Close network connection

The server does not publish the Will Message.

### Additional Notes

Note that if the client closes the connection and doesn't send the Disconnect Notification with Reason Code 0x04, the Will Message is published.

I'm working on writing an MQTT client and I'm hoping to understand if this might be a bug in VerneMQ. 

cc @larshesel 

Happy to provide more details as needed.

Thanks,
Will

**Comment by ioolkos** [comment]
@wlisac thanks for reporting... interesting, I think you're correct and the will message should be published in that case.
Pinging @larshesel for an expert opinion.

**Comment by wlisac** [comment]
It looks like mosquitto recently had the opposite issue – the LWT was being published on a clean disconnect. https://github.com/eclipse/mosquitto/issues/1367

**Comment by larshesel** [comment]
Hi, sounds like something we missed. We'll look into it.

**Comment by larshesel** [comment]
Hi @wlisac, I'm working on a fix for this and will hopefully have a PR ready later today. It's clear from the spec that if the client sends DISCONNECT with 0x00 normal disconnect, then the server must not send the LWT. And it's clear what the meaning is when the client sends a DISCONNECT with 0x04 Disconnect Notification with Will Message. It's not completely clear to me what should happen if the client sends a DISCONNECT with other reason codes. I'm leaning towards that the LWT should be sent then as well.

If that's the case then on DISCONNECT the only case where we should not send is if the reason code is 0x00 and in all other cases we send/schedule the LWT.

Does that make sense with your interpretation?

**Comment by larshesel** [comment]
@wlisac, would you be able to test out the PR and if it works as expected?

**Comment by wlisac** [comment]
@larshesel yep – I interpret it the same way.

I had a chance to test out the branch and it's now working as expected, thank you!

As a side note, I've noticed that the will delay interval is not working as expected, but I'm happy to open a separate issue for that.

Thanks again for the quick response :)

- Will

**Comment by wlisac** [comment]
Opened #1298 as a follow up for the Will Delay Interval.
