### ISSUE TITLE
Subscription Identifier is missing from Publish Messages for Shared Subscriptions

### ISSUE THREAD

**Issue by wlisac** [vernemq/vernemq#1294]
### Environment

- VerneMQ Version: 1.9.0
- Docker: erlio/docker-vernemq:latest
- VerneMQ configuration (vernemq.conf) default, with this env var set:
    - `DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=3,4,5`
- Cluster size/standalone: Single docker container

### Expected behavior

I'm expecting a Subscription Identifier to be included in Publish Messages for Shared Subscriptions.

### Actual behaviour

- Connect to VerneMQ broker using version 5.0 of the MQTT protocol
- Send a Subscribe Request with a Subscription Identifier and a Shared Subscription Topic Filter
    ```
    MQ Telemetry Transport Protocol, Subscribe Request
        Header Flags: 0x82, Message Type: Subscribe Request
            1000 .... = Message Type: Subscribe Request (8)
            .... 0010 = Reserved: 2
        Msg Len: 39
        Message Identifier: 1
        Properties
            Total Length: 2
            ID: Subscription Identifier (0x0b)
            Value: 1
        Topic Length: 31
        Topic: $share/hey/test-subscribe-topic
        Subscription Options: 0x00, Retain Handling: Send msgs at subscription time, QoS: At most once delivery (Fire and Forget)
            00.. .... = Reserved: 0x0
            ..00 .... = Retain Handling: Send msgs at subscription time (0)
            .... 0... = Retain As Published: Not set
            .... .0.. = No Local: Not set
            .... ..00 = QoS: At most once delivery (Fire and Forget) (0)
    ```
- Publish a message to a topic that will match the Topic Filter
    ```
    MQ Telemetry Transport Protocol, Publish Message
        Header Flags: 0x30, Message Type: Publish Message, QoS Level: At most once delivery (Fire and Forget)
            0011 .... = Message Type: Publish Message (3)
            .... 0... = DUP Flag: Not set
            .... .00. = QoS Level: At most once delivery (Fire and Forget) (0)
            .... ...0 = Retain: Not set
        Msg Len: 35
        Topic Length: 20
        Topic: test-subscribe-topic
        Properties
            Total Length: 2
            ID: Payload Format Indicator (0x01)
            Value: 1
        Message: 74657374207075622031
    ```

- The server does not include the Subscription Identifier in the Publish Message (not expected)
    ```
    MQ Telemetry Transport Protocol, Publish Message
        Header Flags: 0x30, Message Type: Publish Message, QoS Level: At most once delivery (Fire and Forget)
            0011 .... = Message Type: Publish Message (3)
            .... 0... = DUP Flag: Not set
            .... .00. = QoS Level: At most once delivery (Fire and Forget) (0)
            .... ...0 = Retain: Not set
        Msg Len: 35
        Topic Length: 20
        Topic: test-subscribe-topic
        Properties
            Total Length: 2
            ID: Payload Format Indicator (0x01)
            Value: 1
        Message: 74657374207075622031
    ```

### Additional Notes

Note that if the client subscribes to a non-shared Topic Filter, the Subscription Identifier is included in the Publish Message as expected.

I'm working on writing an MQTT client and I'm hoping to understand if this might be a bug in VerneMQ. 

Here are some relevant notes from the MQTT 5.0 protocol spec:
>If the Server sends a single copy of the message it MUST include in the PUBLISH packet the Subscription Identifiers for all matching subscriptions which have a Subscription Identifiers, their order is not significant [MQTT-3.3.4-4]. If the Server sends multiple PUBLISH packets it MUST send, in each of them, the Subscription Identifier of the matching subscription if it has a Subscription Identifier [MQTT-3.3.4-5].
>
>…
>
>If the subscription was shared, then only the Subscription Identifiers that were present in the SUBSCRIBE packet from the Client which is receiving the message are returned in the PUBLISH packet.

I'm happy to provide more details as needed.

Thanks,
Will

**Comment by larshesel** [comment]
Hi, thanks for reporting! We'll look into it :)

**Comment by larshesel** [comment]
Hi @wlisac, we just created a PR for this in #1308. would you be able to test it out?

**Comment by wlisac** [comment]
I tested it out and it works as expected 🎉 Thanks for the quick fix!
