### ISSUE TITLE
VerneMQ refuses new connections (cant_parse_connect_fixed_header)

### ISSUE THREAD

**Issue by aka-rider** [vernemq/vernemq#1304]
### Environment

- VerneMQ Version: erlio/docker-vernemq:1.8.0 
- OS: K8s cluster running on Docker (Linux vernemq-0 4.4.0-150-generic #176-Ubuntu SMP Wed May 29 18:56:26 UTC 2019 x86_64 GNU/Linux)
- Cluster size/standalone: 1 node

### Expected behavior
- New clients should be able to connect

### Actual behaviour

- Clients can not connect due to "Network Error : dial tcp 10.235.31.35:1883: i/o timeout"
- Server accuses clients of protocol violation:

```
14:59:05.809 [warning] subscriber {[],<<"the-subscriber[231680d2-e8fe-4e43-8a61-792d6b335499]">>} dropped 21 messages
14:59:05.869 [info] monitor busy_port <0.15650.7> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.73567>
14:59:35.859 [warning] session stopped abnormally due to '{send_failed,{error,timeout}}'
14:59:38.212 [info] monitor busy_port <0.15680.7> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.73575>
14:59:39.153 [info] monitor busy_port <0.15680.7> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.73575>
14:59:40.204 [info] monitor busy_port <0.15680.7> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.73575>
14:59:41.103 [info] monitor busy_port <0.15680.7> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,1}] #Port<0.73575>
14:59:42.402 [info] monitor busy_port <0.15680.7> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.73575>
14:59:43.301 [info] monitor busy_port <0.15680.7> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.73575>
15:23:45.897 [warning] client {[],<<"9aeb04f97b69efa500280cf48b0d8be8">>} with username <<"the_username">> stopped due to keepalive expired
15:45:34.300 [warning] session stopped abnormally due to '{cant_parse_connect_fixed_header,<<"\r\n">>}'
15:45:36.257 [warning] session stopped abnormally due to '{cant_parse_connect_fixed_header,<<"\r\n">>}'
15:46:17.394 [warning] session stopped abnormally due to '{cant_parse_connect_fixed_header,<<"\r\n">>}'
15:46:22.737 [warning] session stopped abnormally due to '{cant_parse_connect_fixed_header,<<"\r\n">>}'
```

This is fresh client connections, so they shouldn't send any garbage, I suspect VerneMQ reads 
leftovers from a buffer, and it's not able to parse legitimate protocol messages because of that.

[Full log](https://github.com/vernemq/vernemq/files/3560691/vernemq.log.gz)

**Comment by ioolkos** [comment]
@aka-rider thanks. Ok, that's a whole lot of `busy_ports`.
What do you actually test there? how many connections, setup rate, message rate?

**Comment by aka-rider** [comment]
Hi @ioolkos 
>What do you actually test there? 

It's not a test. We have some problems running VerneMQ.

Symptoms are:

- Subscriber may stop receiving messages, or receiving rate may drop tenfold. From the client's point of view, everything as usual - there are just no new messages, VerneMQ complains on busy port. For Subscriber to start receiving normaly again, it should reconnect.
- Subscriber may come to infinite reconnect loop, complaining that it didn't received PINGRESP, VerneMQ is silent in this case
- Publisher may stop publish, complaining on network errors: TCP connections closed, TCP timeout. 

All the problems above disappear upon breaking TCP connection. I never could find any useful information in VerneMQ logs that could help to narrow down the problem. This case is the closest I could get.

It only happens in topics under a moderate load (~1k messages / sec), each message is ~8-10Kb, and only once in while.

The load rate is the key here, because we used to have VerneMQ handling 30k messages / sec, ~150B each and the problems above were happening routinely. Eventually, we switched from VerneMQ to direct TCP connections, leaving only moderate load topics in VerneMQ.

Now this problems happen less often. The main issue is: when it happens, from logs/metrics that VerneMQ reports we cannot get any useful information to file a proper bug report.

Clients that we're using are:

- Python3: paho-mqtt==1.4.0
- Golang github.com/eclipse/paho.mqtt.golang v1.2.0
- JS: mqtt@^2.18.3


Again, I suspect that VerneMQ leaves some leftover data in buffers, and that that brings connection session to inconsistent state, because reconnecting cures all the problems above.

**Comment by ioolkos** [comment]
Are there any additional components on the TCP path to VerneMQ? How are the VerneMQ TCP buffer sizes configured, and do you have made any observations regarding that?

**Comment by aka-rider** [comment]
Hi @ioolkos .
I'm sorry. We just figured out that connectivity issue was caused by our fault.
Thank you for your help.

**Comment by iotindustries** [comment]
@aka-rider can you please tell more about the connectivity issue you had?
I have a simmiliar problem (https://github.com/vernemq/vernemq/issues/1285) the client stops receiving messages but everything seems okay. Only client restart helps. Yet i dont know why. Thank you.

**Comment by aka-rider** [comment]
Hi @iotindustries 
Sorry for not responding earlier. In our case, the last time it was because one of our kubernetes  nodes lost connectivity to the node where VerneMQ was.
