### ISSUE TITLE
VerneMQ can't start on Rpi4

### ISSUE THREAD

**Issue by tibor-vavra** [vernemq/vernemq#1305]
### Environment
- VerneMQ Version: 1.9.1
- OS: Raspbian Buster Lite (2019-07-10)
- Erlang/OTP version (if building from source): Erlang/OTP 21 [erts-10.2.4] (installed from repository by sudo apt install erlang)
- VerneMQ configuration (vernemq.conf): default
- Cluster size/standalone: standalone

VerneMQ is build from source code of version 1.9.1
When I try run broker:
./bin/vernemq start
result is:
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
vmq_cluster_node_sup
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

and for ./bin/vernemq console
result is:
Node undefined not responding to pings.
Error reading =CRASH REPORT==== 3-Sep-2019::10:04:32.467891 ===
  crasher:
    initial call: lager_handler_watcher:init/1
    pid: <0.94.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from lager_handler_watcher:install_handler2/3 (/home/pi/projects/vernemq/_build/default/plugins/lager/src/lager_handler_watcher.erl, line 117)
      in call from lager_handler_watcher:init/1 (/home/pi/projects/vernemq/_build/default/plugins/lager/src/lager_handler_watcher.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lager_handler_watcher_sup,lager_sup,<0.86.0>]
    message_queue_len: 0
    messages: []
    links: [<0.89.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 256
  neighbours:

 -config /home/pi/projects/vernemq/_build/rpi32/rel/vernemq/data/generated.configs/app.2019.09.03.10.04.33.config -args_file /home/pi/projects/vernemq/_build/rpi32/rel/vernemq/data/generated.configs/vm.2019.09.03.10.04.33.args -vm_args /home/pi/projects/vernemq/_build/rpi32/rel/vernemq/data/generated.configs/vm.2019.09.03.10.04.33.args

Thanks for the help.

**Comment by larshesel** [comment]
We're aware of this and don't currently have a workaround. However, rpi has a quite low priority at the moment, so it will likely take a while until we get around to fix this. Contributions/PRs are of course very welcome.

**Comment by tibor-vavra** [comment]
That's sad, I made tests with Rpi3 and VerneMQ 1.7.1 and everything was nice working. So when I was creating a production environment I used Rpi4(more cores, higher network performance) but running VerneMQ was a problem and I didn't find the combination of version VerneMQ and Erlang/OTP which can run together.

**Comment by larshesel** [comment]
You could always stay with VerneMQ 1.7.1 and the Erlang/OTP version you used to compile it back then. That would work on Rpi4 as well.

**Comment by tibor-vavra** [comment]
It's strange but I tried this option. VerneMQ 1.7.1 on Rpi3 it's working and on Rpi4 is not.

**Comment by larshesel** [comment]
Hi, I found some time to look at this yesterday - can you try the branch in the PR #1323 ? Works for me on my rpi with OTP 22.

**Comment by tibor-vavra** [comment]
Hi @larshesel, thanks for the help. I tried with OTP 22.1(build from source) and have the same result.

./bin/vernemq console
Node undefined not responding to pings.
Error reading =CRASH REPORT==== 20-Sep-2019::14:06:36.183115 ===
  crasher:
    initial call: lager_handler_watcher:init/1
    pid: <0.96.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from lager_handler_watcher:install_handler2/3 (/home/pi/projects/vernemq_r/_build/default/plugins/lager/src/lager_handler_watcher.erl, line 117)
      in call from lager_handler_watcher:init/1 (/home/pi/projects/vernemq_r/_build/default/plugins/lager/src/lager_handler_watcher.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lager_handler_watcher_sup,lager_sup,<0.88.0>]
    message_queue_len: 0
    messages: []
    links: [<0.91.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 251
  neighbours:

 -config /home/pi/projects/vernemq_r/_build/rpi32/rel/vernemq/data/generated.configs/app.2019.09.20.14.06.36.config -args_file /home/pi/projects/vernemq_r/_build/rpi32/rel/vernemq/data/generated.configs/vm.2019.09.20.14.06.36.args -vm_args /home/pi/projects/vernemq_r/_build/rpi32/rel/vernemq/data/generated.configs/vm.2019.09.20.14.06.36.args

**Comment by larshesel** [comment]
Can you either try to build from a fresh clone and branch or remove the `_build` folder?

**Comment by tibor-vavra** [comment]
Oh, my fault. I cloned your fork but still building master branch :-/ 

It's working now!!! Thank you

It is possible to create .deb package from the build?

**Comment by larshesel** [comment]
great that it works! 

You can't build a deb package for the rpi32 out of the box - but it should be relatively simple to change the Makefile to combine the deb and rpi32 targets...

**Comment by larshesel** [comment]
This fix will be included in either the 1.9.3 or, if we skip the bugfix release then in 1.10.0.
