### ISSUE TITLE
Question - How do I access the IP Address of the client in the plugins(Lua Scripts).

### ISSUE THREAD

**Issue by aurabhi** [vernemq/vernemq#1311]
I am following this doc: https://docs.vernemq.com/plugindevelopment/luaplugins  to develop a custom plugin. I see that the IP address of the client can be accessed in **auth_on_register** hook. 

How do I do the same in other hooks like **on_client_wakeup**, **auth_on_publish** etc.

**Comment by larshesel** [comment]
Hi @aurabhi, that information is not available in those hooks. If you need later you could store it in the (undocumented) in-memory kv store. There's an example here: https://github.com/vernemq/vernemq/blob/master/apps/vmq_diversity/test/ets_test.lua
