### ISSUE TITLE
Unable to get SSL working.

### ISSUE THREAD

**Issue by phenri00** [vernemq/vernemq#1318]
### Environment

- VerneMQ Version: erlio/docker-vernemq
- OS: macOS Mojave
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf):

vernemq.conf.local:

listener.ssl.default = 127.0.0.1:8883
listener.ssl.default.cafile = /etc/vernemq/ssl/all-ca.crt
listener.ssl.default.certfile = /etc/vernemq/ssl/server.crt
listener.ssl.default.keyfile = /etc/vernemq/ssl/server.key

Using following test certs:

https://github.com/vernemq/vernemq/tree/master/apps/vmq_server/test/ssl

- Cluster size/standalone:

standalone

### Expected behavior

Get SSL working

### Actual behaviour

ernemq@a9372057d1fb:~$ openssl s_client -connect 127.0.0.1:8883
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1568453641
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

- Please include minimal steps to reproduce the issue, if possible.

docker run -itd -p 8883:8883 --mount type=bind,source=/Users/xxx/tmp/vernemq/vernemq.conf.local,target=/vernemq/etc/vernemq.conf.local --mount type=bind,source=/Users/xxx/tmp/vernemq/mqtt/certs,target=/etc/vernemq/ssl    erlio/docker-vernemq

openssl s_client -connect 127.0.0.1:8883

**Comment by phenri00** [comment]
Found faulty character in private key. Seems to work now. 

This guide is really good when it comes to troubleshot TLS-issues:
https://www.rabbitmq.com/troubleshooting-ssl.html

Ok to close issue.

**Comment by ioolkos** [comment]
@phenri00 thanks for your effort and feedback!
