### ISSUE TITLE
Configure per-webhook response timeout

### ISSUE THREAD

**Issue by kag0** [vernemq/vernemq#1321]
I've got auth on register webhooks that hash passwords rather excessively (takes a couple seconds). Sometimes when that webhook is invoked I'll get a 
> 00:09:11.039 [error] calling endpoint failed due to timeout
error. The request does complete just fine, so I just need verne to wait a bit longer for the response to come back. However all my other webhooks complete within the normal timeout. 

Is there a way to change the response timeout for just one webhook?

**Comment by larshesel** [comment]
Hi, there isn't as far as I can tell, but would likely make sense. As far as I can tell from the code the default is either 5s or 8s... Note, that if your password verification takes that long, then the arrival rate you can handle (new clients connecting) will be quite low. For example, if it takes 5s to verify the password, you can, if this is a single core, only handle a new client every 5 seconds (or 0.2/second).  Even with 4 cores which can be fully utilized you'd the rate would be less than one per second (0.8/second). I'm of course not saying that you shouldn't use so thorough password verification hashes, but that it comes at a cost. If you have very few clients connecting then this is fine! It's always a tradeoff ;)

**Comment by larshesel** [comment]
Created a PR for it in #1322 - let's see if it passes review.

**Comment by kag0** [comment]
Good point
It should be OK in my case since the hashing is only for when a "super user" connects which is an exceptional case.

Just to clarify one thing: the one login/5s number is assuming that the webhook server is running on the same machine as the verne node and that the cluster has only one node right? Put another way, the cluster isn't processing auth attempts serially and the auth attempt rate should also scale with the number of nodes, right?

**Comment by larshesel** [comment]
> It should be OK in my case since the hashing is only for when a "super user" connects which is an exceptional case.

ok


> Just to clarify one thing: the one login/5s number is assuming that the webhook server is running on the same machine as the verne node and that the cluster has only one node right? Put another way, the cluster isn't processing auth attempts serially and the auth attempt rate should also scale with the number of nodes, right?

No, the cluster isn't processing auth attempts serially. The each webhooks hook/endpoint pair have a default connection pool of 100 connections (this can also be configured), so from a VerneMQ perspective 100 simultaneous authentication requests can be ongoing for each node at any one time. But how many can of those 100 that will be served/second depends on the speed of the endpoint. If the endpoint is the same for the entire cluster and it only can handle one at at time, then the endpoint would effectively serialize the authentications.

**Comment by kag0** [comment]
gotcha, that's what I thought, just wanted to double check
