### ISSUE TITLE
Postgres Error invalid_authorization_specification

### ISSUE THREAD

**Issue by swappyc7** [vernemq/vernemq#1324]
### Environment

- VerneMQ Version: 1.8
- OS: Cent OS
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) : Modified for connecting with PostgreSQL
- Cluster size/standalone: standalone
- VerneMQ is install on Server 1 and PostgreSQL is install on Server 2

### Expected behavior
PostgesSQL should connect with Vernemq Broker, which will allow me to connect using Webhook

### Actual behaviour
When checked in Console log getting following error message
vmq_diversity_worker_wrapper:handle_info:166 Could not connect to postgresql due to invalid_authorization_specification

Followed the exact steps specified in auth using db.

vmq_diversity.auth_postgres.enabled = on
vmq_diversity.postgres.host = IP Server 2
vmq_diversity.postgres.port = 5432
vmq_diversity.postgres.user = vernemq
vmq_diversity.postgres.password = vernemq
vmq_diversity.postgres.database = vernemq_db
vmq_diversity.postgres.password_hash_method = crypt

configure database and table as mention in the document
![image](https://user-images.githubusercontent.com/8447663/65323205-5eae4e80-dbc6-11e9-93fd-7ae712e29fc8.png)

Unable to identify why it is giving postgresql error. If I try to connect from PGadmin to the database it is working fine.

I have check telnet is also working properly from vernemq server to postgresql server

What can else I check to resolve this issue.

**Comment by larshesel** [comment]
From the log line it is indicated that the problem is that for some reason the postgresql client cannot connect to the postgres server. Either this has to do with credentials or perhaps TLS. Often tools like `pgadmin` aren't connecting the same way as a client - I would try to test if it is possible to connect to the database from a remote node using another client or perhaps `pgadmin` is it would have to connect via tcp.

Hope this helps.

**Comment by DerrickNgigi** [comment]
When you install a PostgreSQL server, it is only accessible locally through the loopback IP address of your machine. However, you may change this setting in the PostgreSQL configuration file to allow remote access.

To configure IDENT authentication, add entries to the `/etc/postgresql/12/main/pg_ident.conf file.` There are detailed comments in the file to guide you.
To enable other computers to connect to your PostgreSQL server, edit the file `/etc/postgresql/12/main/postgresql.conf`
Locate the line `#listen_addresses = ‘localhost’ `and change it to:
`listen_addresses = '*'`

to restart Postgresql `sudo /etc/init.d/postgresql restart`
