### ISSUE TITLE
集群中有节点意外停止，服务将无法使用

### ISSUE THREAD

**Issue by LeiyuanBlog** [vernemq/vernemq#1331]
VerneMQ1.9.2
操作系统：CentOS7
问题：
 三个集群节点中有一个节点意外退出，则所有节点无法继续提供服务。
错误信息：
 Connection Refused: broker unavailable.
求助求助！！！
有没有大佬帮帮忙

**Comment by larshesel** [comment]
` Connection Refused: broker unavailable.` would imply that the broker is not running or something similar - without more information I'm afraid we cannot help you. Feel free to open a new issue and please write in english, we unfortunately do not understand chinese.

**Comment by chenxinlong** [comment]
> 三个集群节点中有一个节点意外退出，则所有节点无法继续提供服务。    

It means: One node in the cluster exited unexpectedly, all nodes stopped serving.  

Guess it's a netsplit problem. 

[This doc](https://docs.vernemq.com/clustering/netsplits) and #938 may be helpful.  @LeiyuanBlog
