### ISSUE TITLE
A node in the cluster stops service

### ISSUE THREAD

**Issue by LeiyuanBlog** [vernemq/vernemq#1332]
VerneMQ1.9.2
OS：CentOS7
The problem：
 If one of the three nodes exits unexpectedly, all nodes cannot continue to provide services.
 There are three nodes in my cluster, one of which unexpectedly exits, and all the nodes are unable to provide services.
error：
 Connection Refused: broker unavailable.
Ask for help!!!
I need god's help

**Comment by LeiyuanBlog** [comment]
<0.7288.0>@vmq_mqtt_fsm:check_user:587 can't register client {[],<<"mosq/oun46Qb9mdlEbZlRqS">>} due to reason not_ready

**Comment by ioolkos** [comment]
@LeiyuanBlog 
you need to configure your cluster for availability in case of netsplits. Look at all the `allow` options like `allow_register_during_netsplit = on`.

Pretty sure god's help is not necessary here ;)

**Comment by larshesel** [comment]
There's more on netsplits and the configuration here: https://docs.vernemq.com/clustering/netsplits

**Comment by LeiyuanBlog** [comment]
@ioolkos @larshesel This problem has been solved, but I have a new problem that my Java code cannot connect in a cluster. When my first node is broken, the connection will fail. Can you help me?

**Comment by larshesel** [comment]
Hi @LeiyuanBlog the VerneMQ issue list is for VerneMQ bug reports and enhancement proposals. We cannot help you with your Java code here - but it sounds like the issue you started out with - if there is a netsplit and the netsplit settings are not correctly configured then the connection will be rejected. If you need commercial support please get in touch with us via the form on the web-site - for VerneMQ related questions you're more than welcome to ask on the community slack.
