### ISSUE TITLE
HTTP Bridge messages using VerneMQ

### ISSUE THREAD

**Issue by WBorsato** [vernemq/vernemq#1339]
Hello,

Is it possible to receive any JSON via HTTP and redirect to another endpoint using HTTPS? Is it a VerneMQ feature or some kind of programming? Can you give me some advice on how to manage a large amount of redirects?

I'm running VerneMQ on Ubuntu14.04 just for MQTT for while in a small application.

**Comment by larshesel** [comment]
Hi,

I'm not sure I really understand your question, but perhaps you can use the `vmq_webhooks` plugin (see https://docs.vernemq.com/plugindevelopment/webhookplugins for details) to forward MQTT messages to HTTP endpoints. 

Hope that helps
