### ISSUE TITLE
unable to re join a cluster after leaving.

### ISSUE THREAD

**Issue by sfoutrel** [vernemq/vernemq#1342]
### Environment

- VerneMQ Version: 1.9.2 (from https://github.com/vernemq/vernemq/releases/download/1.9.2/vernemq-1.9.2.stretch.x86_64.deb)
- OS: Debian
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 2 nodes in the same L2

### Expected behavior

Leave cluster then be able to join it.

### Actual behaviour

Unable to join after leaving a cluster.

from node ecsi-mqtt-01:

> vmq-admin cluster leave node=ecsi-mqtt-01@ecsi-mqtt-01.ecritel.net -k

(leave the cluster and stop node, had to do a systemctl restart vernemq)

> vmq-admin cluster join discovery-node=ecsi-mqtt-02@ecsi-mqtt-02.ecritel.net

(reply Done and log says : 

ecsi-mqtt-01:
> 2019-10-10 13:51:12.433 [info] <0.447.0>@plumtree_peer_service:attempt_join:50 Sent join request to: 'ecsi-mqtt-02@ecsi-mqtt-02.ecritel.net'
> 2019-10-10 13:51:12.447 [info] <0.316.0>@vmq_cluster_mon:handle_info:126 cluster node 'ecsi-mqtt-02@ecsi-mqtt-02.ecritel.net' UP

ecsi-mqtt-02:
> 2019-10-10 13:50:55.406 [info] <0.214.0>@vmq_cluster:init:141 cluster event handler 'vmq_cluster' registered
> 2019-10-10 13:51:12.447 [info] <0.319.0>@vmq_cluster_mon:handle_info:126 cluster node 'ecsi-mqtt-01@ecsi-mqtt-01.ecritel.net' UP

but 
> vmq-admin cluster show
shows only local node on each nodes.
Nothing in /var/log/vernemq/error.log on both nodes.

**Comment by larshesel** [comment]
Hi,

On which node did you run the cluster join command?  Are you sure you're not trying to join a node with itself (and hence it has no effect).

I just tried to do this a few times and had no problems, in other words I was not able to reproduce.
