### ISSUE TITLE
Documentation on "sharename" component for shared subscriptions

### ISSUE THREAD

**Issue by zxtwonder** [vernemq/vernemq#1344]
On [the shared subscription doc page](https://docs.vernemq.com/configuration/shared_subscriptions), it is said that a shared subscription is on topics in the form of `$share/sharename/topic` and the corresponding publishing topic is `topic`.

- What is the use of the `sharename` part in the subscription topic?
- Are subscriptions on `$share/onename/topic` and `$share/othername/topic` effectively the same?

Thank you!

**Comment by larshesel** [comment]
Hi, thanks for the question - we'll see if we can improve the text there. 

For your questions. The share name is the identifier of the share. So for two subscribers to share a subscription the sharename and the topic has to be the same. Having different sharenames makes it possible to have multiple distinct groups sharing a subscription. So for your second question the answer is: no.

Hope this helps

**Comment by zxtwonder** [comment]
Thank you for the response. It really helps and made me realize this is actually part of [MQTT 5.0 standard](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901250).
