### ISSUE TITLE
Topic param in on_offline_message function has delimiters removed

### ISSUE THREAD

**Issue by rahulwinzo** [vernemq/vernemq#1345]
### Environment

- VerneMQ Version: 1.92.
- OS: Ubuntu 18.04
- Erlang/OTP version (if building from source): 20
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: standalone

### Expected behavior

- Topic string in the param of on_offline_message function is expected to have `/` hierarchy delimiter, i.e. if the offline message is published to a topic say `a/b/c` the topic received inside the function should be `a/b/c`.

### Actual behaviour

- If the message is published to topic `a/b/c`, the topic received inside the function is `abc`.

It can be reproduced by simply logging the topic param inside the `on_offline_message` function.

**Comment by larshesel** [comment]
Hi,

The topic passed to the `on_offline_message` is as expected. For example the topic `a/b/c` is passed in as `[<<"a">>, <<"b">>, <<"c">>]` and is specified by the `topic()` type (https://github.com/vernemq/vernemq_dev/blob/master/src/on_offline_message_hook.erl#L8) defined here https://github.com/vernemq/vernemq_dev/blob/master/include/vernemq_dev.hrl#L12.

Hope this helps.

**Comment by rahulwinzo** [comment]
Ok. Thanks for the help. Will check this.
