### ISSUE TITLE
QoS 2 Messages Received by VerneMQ Re-Published Before QoS 2 Handshake Completes

### ISSUE THREAD

**Issue by csheaupdesigns** [vernemq/vernemq#1349]
I did find one similar issue (QOS 2 messages duplicated #946 ).  However, the description did not seem to describe exactly what I am seeing.  But, perhaps it is the same issue.

# Environment

- VerneMQ Version: 1.8
- OS: Ubuntu 18.04.3 LTS
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf): 
[vernemq_conf.txt](https://github.com/vernemq/vernemq/files/3756147/vernemq_conf.txt)

- Cluster size/standalone:  Standalone

### Expected behavior

QoS 2 messages should not be re-published until after the QoS 2 handshaking completes.

### Actual behaviour

I am noticing that VerneMQ is publishing QoS 2 messages to subscribers prior to the completion of the QoS 2 handshake.  It is my understanding that the QoS 2 message should not be marked as received until the handshake sequence completes and, thus, should not be re-transmitted in cases in which it does not complete.  I have attached a Wireshark text export of one instance of the issue. As can be seen, the PUB with ID=9 is received and then a PUBREC is sent back to the sender.  The next item that goes out is a PUB with ID=24066.  This PUB is actually just a transmission of the previously received message to a second device that is subscribed to the same topic.  The handshaking of the second message actually completes before the handshaking of the first message does.

[wireshark_dump.txt](https://github.com/vernemq/vernemq/files/3756097/wireshark_dump.txt)

**Comment by larshesel** [comment]
According to the spec (see http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718102) a QoS 2 message can either be (stored and) forwarded when the broker receives the PUBLISH (Method B) or when the broker receives the PUBREL (Method A). VerneMQ implements method B.

Hope this helps!

**Comment by larshesel** [comment]
We use method B because this makes it easier to handle netsplits. Method B also ensures exactly once delivery as it is only forwarded once per QoS 2 message flow. The rest of the handshake is needed to ensure that the broker knows that the client knows the message was processed, so the broker is sure the client will not try to resend.

Out of curiosity, why is the method used important for your use-case?

**Comment by csheaupdesigns** [comment]
In my system, the clients are sensors pushing data to the broker.  There is also a client that subscribes to the topic which the data is being pushed to whose responsibility is to parse the data and write it to a database.  My hope was to ensure that duplicate data records are not sent by using QoS 2.  The clients would only resend data records if the QoS 2 handshake did not complete.  However, when thinking about it more, even if you were to use Method A, there are still holes in which duplicate data records would be written to the database.  For example, if the broker waited until the PUBREL to store the data and initiate onward forwarding, there still is the case in which the PUBCOMP is never received by the client.  In my implementation, the client would render the transaction a failure and attempt to resend the data at a later time.  However, the broker would've already pushed the received packet out to subscribing clients which would result in the data being written to the database.

I've come to realize that the best way to handle this is by checking for duplicates when writing to the database.

Thank you for your help!

**Comment by larshesel** [comment]
VerneMQ does not forward the message a second time the if you retry a qos2 PUBLISH frame, it will simply see that there is an open qos2 flow and respond with a PUBREC frame. So I think it should work. But a good design which can handle duplicates is always a good thing - and if you can handle duplicates you could settle for the faster and simpler QoS 1 flow.
