### ISSUE TITLE
Some questions about plugins

### ISSUE THREAD

**Issue by DmitriiTrofimov** [vernemq/vernemq#1350]
Hi!

I have a few questions about plugins.
1. Calling of `on_publish` hook is synchronous or not?
2. In cluster mode `on_publish` hook calling only for message published on current node or for all published messages on all nodes?

**Comment by larshesel** [comment]
It is called in the context of the connection process for the client publishing the message and is synchronous. Therefore it is only called one per message published by a client on the node where the client is connected.
