### ISSUE TITLE
[question][plugin] How to accept and drop message on auth_on_publish ?

### ISSUE THREAD

**Issue by estin** [vernemq/vernemq#1351]
Hello! 
Any right way to accept incoming message and drop it?

It special case for some messages from specific clients:
 - authorized to publish it
 - some internal checks and processing
 - and don't publish this message for subscribers at all

```
auth_on_publish(UserName, SubscriberId, QoS, Topic, Payload, IsRetain) ->
  %% do whatever you like with the params, all that matters
  %% is the return value of this function
  %%
  %% 1. return 'ok' -> PUBLISH is authorized
  %% 2. return 'next' -> leave it to other plugins to decide
  %% 3. return {ok, NewPayload::binary} -> PUBLISH is authorized, but we changed the payload
  %% 4. return {ok, [{ModifierKey, NewVal}...]} -> PUBLISH is authorized, but we might have changed different Publish Options:
  %%     - {topic, NewTopic::string}
  %%     - {payload, NewPayload::binary}
  %%     - {qos, NewQoS::0..2}
  %%     - {retain, NewRetainFlag::boolean}
  %% 5. return {error, whatever} -> auth chain is stopped, and message is silently dropped (unless it is a Last Will message) 
```

It is normal to `return {error, "alright, message proccessed but not published"}` in this case?
Or may needs some changes to Qos and queue length by settings?

**Comment by larshesel** [comment]
I already wrote you on the slack channel, but perhaps you missed it. There is no way to simply drop a message. You can rewrite the topic to something unused or do the same for the mountpoint. Kind of redirecting to `/dev/null` in unix parlance. Returning an error will work, but *only* for MQTT 3.1, for MQTT 3.1.1 or higher the connection will be dropped.

Hope this helps.

**Comment by estin** [comment]
Thanks! Its help me to decide which way to choose )
