### ISSUE TITLE
MySQL Authentication is not working : VerneMQ

### ISSUE THREAD

**Issue by vkc2019** [vernemq/vernemq#1352]
### Environment

- VerneMQ Version: 1.9.2
- OS: Ubuntu 18.04 
- Erlang/OTP version (if building from source): 
- VerneMQ configuration (vernemq.conf) or the changes from the default

allow_anonymous = off
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
coordinate_registrations = on
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.tcp.default = 127.0.0.1:1883
listener.vmq.clustering = 0.0.0.0:44053
listener.http.default = 127.0.0.1:8888
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = on
plugins.vmq_webhooks = off
plugins.vmq_bridge = off
metadata_plugin = vmq_plumtree
vmq_acl.acl_file = ./etc/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = ./etc/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = ./share/lua
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.mysql.host = localhost
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = root
vmq_diversity.mysql.password = Hidden@123s
vmq_diversity.mysql.database = vernemq
vmq_diversity.mysql.password_hash_method = sha256
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off
vmq_bcrypt.pool_size = 1
log.console = console
log.console.level = debug
log.console.file = /var/log/vernemq/console.log
log.error.file = ./log/error.log
log.syslog = on
log.crash = on
log.crash.file = ./log/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = VerneMQ@127.0.0.1
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
listener.ssl.require_certificate=off

- Cluster size/standalone: **Standalone**

### Expected behavior
the client must be authenticated 

### Actual behaviour
00:36:54.503 [warning] can't authenticate client {[],<<"test-client">>} from 127.0.0.1:39096 due to chain_exhausted

setup the MySQL database and configure the same. 
Inserted an entry in the database.
INSERT INTO vmq_auth_acl 
    (mountpoint, client_id, username, 
     password, publish_acl, subscribe_acl)
VALUES 
    ('', 'test-client', 'test-user', PASSWORD('123'), 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');

When we try to connect a client with clientId: test-client and username: test-user and password as 123

It was giving the following error. 
00:36:54.503 [warning] can't authenticate client {[],<<"test-client">>} from 127.0.0.1:39096 due to chain_exhausted

**Comment by larshesel** [comment]
You config looks good as far as I can tell. Are there any errors earlier to the one you see? Any errors indicating the plugin isn't active? Or did you restart VerneMQ after setting these changes? Perhaps try to do a trace and see if the client is really connecting with what you think it is `vmq-admin trace client client-id=<client-id>`

Hope this helps.

**Comment by vkc2019** [comment]
Please check the Log for client trace: 

No sessions found for client "test-client"
New session with PID <8962.450.0> found for client "test-client"
<8962.450.0> MQTT RECV: CID: "test-client" CONNECT(c: test-client, v: 4, u: test-user, p: 123, cs: 1, ka: 60)
<8962.450.0> Calling auth_on_register({{127,0,0,1},54644},{[],
                                                           <<"test-client">>},test-user,123,true) 
<8962.450.0> Hook returned {error,chain_exhausted}
<8962.450.0> MQTT SEND: CID: "test-client" CONNACK(sp: 0, rc: 5)
<8962.450.0> Trace session for test-client stopped
New session with PID <8962.451.0> found for client "test-client"
<8962.451.0> MQTT RECV: CID: "test-client" CONNECT(c: test-client, v: 3, u: test-user, p: 123, cs: 1, ka: 60)
<8962.451.0> Calling auth_on_register({{127,0,0,1},54646},{[],
                                                           <<"test-client">>},test-user,123,true) 
<8962.451.0> Hook returned {error,chain_exhausted}
<8962.451.0> MQTT SEND: CID: "test-client" CONNACK(sp: 0, rc: 5)
<8962.451.0> Trace session for test-client stopped

**Comment by vkc2019** [comment]
plugins

`+-------------+-----------+--------------------+-------------------------------------------+
|   Plugin    |   Type    |      Hook(s)       |                   M:F/A                   |
+-------------+-----------+--------------------+-------------------------------------------+
|vmq_diversity|application|  auth_on_register  |  vmq_diversity_plugin:auth_on_register/5  |
|             |           |  auth_on_publish   |  vmq_diversity_plugin:auth_on_publish/6   |
|             |           | auth_on_subscribe  | vmq_diversity_plugin:auth_on_subscribe/3  |
|             |           |    on_register     |    vmq_diversity_plugin:on_register/3     |
|             |           |     on_publish     |     vmq_diversity_plugin:on_publish/6     |
|             |           |    on_subscribe    |    vmq_diversity_plugin:on_subscribe/3    |
|             |           |   on_unsubscribe   |   vmq_diversity_plugin:on_unsubscribe/3   |
|             |           |     on_deliver     |     vmq_diversity_plugin:on_deliver/4     |
|             |           |auth_on_register_m5 |vmq_diversity_plugin:auth_on_register_m5/6 |
|             |           | auth_on_publish_m5 | vmq_diversity_plugin:auth_on_publish_m5/7 |
|             |           |auth_on_subscribe_m5|vmq_diversity_plugin:auth_on_subscribe_m5/4|
|             |           |   on_register_m5   |   vmq_diversity_plugin:on_register_m5/4   |
|             |           |   on_publish_m5    |   vmq_diversity_plugin:on_publish_m5/7    |
|             |           |  on_subscribe_m5   |  vmq_diversity_plugin:on_subscribe_m5/4   |
|             |           | on_unsubscribe_m5  | vmq_diversity_plugin:on_unsubscribe_m5/4  |
|             |           |   on_deliver_m5    |   vmq_diversity_plugin:on_deliver_m5/5    |
|             |           |     on_auth_m5     |     vmq_diversity_plugin:on_auth_m5/3     |
|             |           | on_offline_message | vmq_diversity_plugin:on_offline_message/5 |
|             |           |  on_client_wakeup  |  vmq_diversity_plugin:on_client_wakeup/1  |
|             |           | on_client_offline  | vmq_diversity_plugin:on_client_offline/1  |
|             |           |   on_client_gone   |   vmq_diversity_plugin:on_client_gone/1   |
+-------------+-----------+--------------------+-------------------------------------------+`

**Comment by larshesel** [comment]
Then my guess would be that you're using the wrong database or table or something like that. Try to debug on the mysql side what the query actually calls into and what is returned

**Comment by vkc2019** [comment]
I found the issue from the configuration. I just comment out the following line from the **vernemq.conf**
**# vmq_diversity.script_dir = ./share/lua**

And now it's working as expected for the MySQL Authentication. 

I got this clue from one of the old threads: **https://github.com/vernemq/vernemq/issues/930**

But, I  change the configuration to use mongo as a database. 

And I am getting the following error:
No sessions found for client "test-client"
New session with PID <8962.799.0> found for client "test-client"
<8962.799.0> MQTT RECV: CID: "test-client" CONNECT(c: test-client, v: 4, u: test-user, p: 123, cs: 1, ka: 60)
<8962.799.0> Calling auth_on_register({{127,0,0,1},45336},{[],
                                                           <<"test-client">>},test-user,123,true) 
<8962.799.0> Hook returned {error,invalid_credentials}
<8962.799.0> MQTT SEND: CID: "test-client" CONNACK(sp: 0, rc: 4)
<8962.799.0> Trace session for test-client stopped
New session with PID <8962.800.0> found for client "test-client"
<8962.800.0> MQTT RECV: CID: "test-client" CONNECT(c: test-client, v: 3, u: test-user, p: 123, cs: 1, ka: 60)
<8962.800.0> Calling auth_on_register({{127,0,0,1},45338},{[],
                                                           <<"test-client">>},test-user,123,true) 
<8962.800.0> Hook returned {error,invalid_credentials}
