### ISSUE TITLE
Unlimited session show

### ISSUE THREAD

**Issue by chenxinlong** [vernemq/vernemq#1354]
### Environment

- VerneMQ Version:1.8.1
- OS:CentOS 7
- Erlang/OTP version (if building from source): N/A  
- Cluster size/standalone:4

I want to record the online session num of each node of cluster every 30 minutes, so I request the api  `http://key@example.com:1900/api/v1/session/show?--client_id&--node&--is_online=true` and count the num of the result and store the result into MySQL every 30 minutes.

According to the `vmq-admin session show --help`   I can't find a way to set `--limit` as unlimited. My question is : 

1. Is there a more elegant way to record the real-time online session num? 
2. If the answer of question 1 is no, is there any way to set `--limit` as unlimited?    
3. If the answer of question 2 is yes, is it safe to get all sessions? Will it affect the performance of the service?

**Comment by ioolkos** [comment]
@chenxinlong 
the short answer is to export metrics to Prometheus, where you'd have the realtime metrics.

If that's not an option, the API call is kind of cumbersome. (apart from the actual issue with `--limit`)
I'm afraid I don't have a better idea here. If someone else has, please chime in.

**Comment by dergraf** [comment]
At this point you have to use the metrics. It's as simple as doing the subtraction of `socket_open - socket_close` counters. Obviously this has to be done on every cluster node, which is where Prometheus comes extremely handy.

Please get in touch over Slack if you need further assistance with setting up the Prometheus queries. 

Closing this.

**Comment by chenxinlong** [comment]
Ok, thx.

**Comment by chenxinlong** [comment]
Hi, I have 2 question :  

1. will webhook connection count into `socket_open` and `socket_close` ?  
2. Will vmq keep retrying  request webhook if the last webhook request timeout  ？
