### ISSUE TITLE
Unknown synch event in drain state errors

### ISSUE THREAD

**Issue by KotaiVictor** [vernemq/vernemq#1355]
### To help us save time and help you faster
We keep seeing the following errors on our nodes, fairly often:
```
10:13:39.910 [error] got unknown sync event in drain state {migrate,<14029.31518.1>}
10:13:42.528 [error] got unknown sync event in drain state {migrate,<14029.31530.1>}
10:13:45.154 [error] got unknown sync event in drain state {migrate,<14029.31550.1>}
```
This usually happens after a node goes down and comes back up. 

### Environment

- VerneMQ Version: 1.9.1 
- VerneMQ configuration (vernemq.conf) or the changes from the default:
```
erlang.distribution.port_range.minimum=9100
leveldb.maximum_memory=104857600
max_inflight_messages=100
persistent_client_expiration=24h
listener.nr_of_acceptors=100
max_online_messages=10000
leveldb.write_buffer_size_max=20971520
allow_subscribe_during_netsplit=on
listener.ws.localhost=127.0.0.1:1884
listener.http.localhost=127.0.0.1:1885
leveldb.write_buffer_size_min=10485760
allow_publish_during_netsplit=on
erlang.distribution.port_range.maximum=9109
allow_unsubscribe_during_netsplit=on
log.console=console
allow_register_during_netsplit=on
listener.tcp.localhost=127.0.0.1:1883
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.233.96.248:1883
listener.ws.default = 10.233.96.248:1884
allow_anonymous = on
outgoing_clustering_buffer_size = 10000000
listener.vmq.clustering = 10.233.96.248:1886
listener.http.metrics = 10.233.96.248:1885
```
- Cluster size: 3 nodes, kubernetes deployment

**Comment by dergraf** [comment]
Thanks for opening this issue. Can you share some insights about the status of the deployment when you started to see those errors? E.g. were one or more nodes maxing out CPU at that point?

**Comment by KotaiVictor** [comment]
We see them all the time now days. Each of our 3 nodes has 2 cpus and 2 gb or ram assigned.
From our monitoring, the pods are sitting somewhere at 0.5 cpus and 600 mb of ram, throughout the day.

**Comment by dergraf** [comment]
Do you experience some netsplits? Could you post the output of `vmq-admin metrics show | grep netsplit` ?

**Comment by KotaiVictor** [comment]
It seems so: 
Node-0:
`counter.netsplit_resolved = 1`
`counter.netsplit_detected = 1`
Node-1:
`counter.netsplit_resolved = 1`
`counter.netsplit_detected = 1`
We can see the error messages on node-1.
Node-2:
`counter.netsplit_resolved = 0`
`counter.netsplit_detected = 0`
We can see the error messages on node-2.
