### ISSUE TITLE
VerneMQ 1.9.2 crashes on reconnect to a persistent session with offline messages waiting

### ISSUE THREAD

**Issue by MacPatric** [vernemq/vernemq#1357]
I'm using the HiveMQ MQTT 5 client to connect to a dockerized VerneMQ (1.9.2).
The client has a **persistent shared subscription** with offline messages waiting for the client to reconnect.

When the connection is established (CONNACK is received), the broker should send any offline messages to the client, but immediately crashes and disconnects.

When using a normal (not shared) subscription, the messages are delivered to the client as expected.

### Environment

- VerneMQ Version: 1.9.2 (Docker image `erlio/docker-vernemq:latest`)
- OS: `Linux 89eafc044293 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 GNU/Linux`
- VerneMQ configuration from docker-compose:
      - `DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on`
      - `DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=3,4,5`
- Cluster size/standalone: standalone

### Expected behavior

- mqtt5 client has a persistent session (cleanStart=false, sessionExpiryInterval=172800) with a shared(!) subscription
- mqtt5 client disconnects
- broker receives messages with qos=1 or qos=2 and puts them into the offline_messages queue
- mqtt5 client reconnects
- broker sends offline messages to client

### Actual behaviour

mqtt5 client reconnects

broker crashes with:

```log
2019-10-31 13:19:48.897 [error] <0.1392.0>@vmq_parser_mqtt5:serialise:389 CRASH REPORT Process <0.1392.0> with 0 neighbours crashed with reason: bad argument in vmq_parser_mqtt5:serialise/1 line 389
2019-10-31 13:19:48.898 [error] <0.1392.0>@vmq_parser_mqtt5:serialise:389 Ranch listener {{172,19,0,5},1883} terminated with reason: bad argument in vmq_parser_mqtt5:serialise/1 line 389
```

crash.log:

```log
2019-10-31 13:19:48 =CRASH REPORT====
  crasher:
    initial call: vmq_ranch:init/4
    pid: <0.1392.0>
    registered_name: []
    exception error: bad argument: [{vmq_parser_mqtt5,serialise,1,[{file,"/vernemq-build/apps/vmq_commons/src/vmq_parser_mqtt5.erl"},{line,389}]},{vmq_mqtt5_fsm,prepare_frame,2,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,1395}]},{vmq_mqtt5_fsm,handle_messages,5,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,1353}]},{vmq_mqtt5_fsm,connected,2,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,454}]},{vmq_mqtt5_fsm,in,3,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,246}]},{vmq_mqtt5_fsm,msg_in,2,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,234}]},{vmq_ranch,handle_message,2,[{file,"/vernemq-build/apps/vmq_server/src/vmq_ranch.erl"},{line,242}]},{vmq_ranch,loop_,1,[{file,"/vernemq-build/apps/vmq_server/src/vmq_ranch.erl"},{line,138}]}]
    ancestors: [<0.323.0>,<0.322.0>,ranch_sup,<0.134.0>]
    message_queue_len: 0
    messages: []
    links: [<0.323.0>,#Port<0.154>]
    dictionary: [{rand_seed,{#{jump => #Fun<rand.16.10897371>,max => 288230376151711743,next => #Fun<rand.15.10897371>,type => exsplus},[285848900126158635|1547444473287239]}},{request_problem_information,true},{max_outgoing_msg_size,undefined},{max_incoming_msg_size,0},{atomics_ref,#Ref<0.545497354.404881412.57744>}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 1469
  neighbours:
2019-10-31 13:19:48 =ERROR REPORT====
Ranch listener {{172,19,0,5},1883} had connection process started with vmq_ranch:start_link/4 at <0.1392.0> exit with reason: {badarg,[{vmq_parser_mqtt5,serialise,1,[{file,"/vernemq-build/apps/vmq_commons/src/vmq_parser_mqtt5.erl"},{line,389}]},{vmq_mqtt5_fsm,prepare_frame,2,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,1395}]},{vmq_mqtt5_fsm,handle_messages,5,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,1353}]},{vmq_mqtt5_fsm,connected,2,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,454}]},{vmq_mqtt5_fsm,in,3,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,246}]},{vmq_mqtt5_fsm,msg_in,2,[{file,"/vernemq-build/apps/vmq_server/src/vmq_mqtt5_fsm.erl"},{line,234}]},{vmq_ranch,handle_message,2,[{file,"/vernemq-build/apps/vmq_server/src/vmq_ranch.erl"},{line,242}]},{vmq_ranch,loop_,1,[{file,"/vernemq-build/apps/vmq_server/src/vmq_ranch.erl"},{line,138}]}]}
```

**Comment by ioolkos** [comment]
@MacPatric thanks for reporting! ;)
A note on wording: the session crashes, not the broker. 
The parser stumbles here, so could this have to do with DUP flag? https://github.com/vernemq/vernemq/blob/00f57bfe00d3e1a2f33a02030260c1ff81976a82/apps/vmq_commons/src/vmq_parser_mqtt5.erl#L389
@dergraf can you look into this?

**Comment by ioolkos** [comment]
@MacPatric to make sure this is an Verne issue (which I think it is as it happens in serialising): can you confirm the error which other clients too? (like the Mosquitto tools or similar)

**Comment by dergraf** [comment]
This issue should be fixed by https://github.com/vernemq/vernemq/pull/1356.
