### ISSUE TITLE
Question: timestamp publish arrives 

### ISSUE THREAD

**Issue by mprevide** [vernemq/vernemq#1358]
Hi
Is it possible to get the timestamp when the publish arrives in vernemq before any process? 

I could find anything in documentation. 
Thank you very much

**Comment by dergraf** [comment]
Hi there.
Such a timestamp doesn't exist in an 'accessible' form. Now, if you require such a timestamp you would need to implement this in a VerneMQ plugin and there the earliest possible plugin hook would be `auth_on_publish`  (see https://docs.vernemq.com/plugindevelopment/publishflow#auth_on_publish-and-auth_on_publish_m5).

Closing this issue for now, please feel free to reach out over Slack to discuss your use case further.

**Comment by mprevide** [comment]
Thank you

**Comment by mprevide** [comment]
Hi :)
@dergraf
If I use webhook is the same thing? Or is   auth_on_publish in webhook reached after then plugin?
