### ISSUE TITLE
How to test fire on_offline_message webhook?

### ISSUE THREAD

**Issue by whisper-bye** [vernemq/vernemq#1359]
- VerneMQ Version: 1.9.1
- OS: macOS
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

I've tried some combinations，like change the qos, retained, cleanSession, etc. but still not worked for me.

**Comment by larshesel** [comment]
Hi, to use the on_offline_message hook you have to use a plugin which implements the hook, like for example a webhook (see https://docs.vernemq.com/plugindevelopment/webhookplugins#on_offline_message) or using a native plugin written in Erlang. For more details about hooks and the plugin system see https://docs.vernemq.com/plugindevelopment/introduction

Hope this helps,
Lars

**Comment by whisper-bye** [comment]
yes I did, I have tested all of the webhooks yet without on_offline_message, I don't known how to trigger it.

**Comment by larshesel** [comment]
The client must have connected with clean_session=false, it must be subscribed to the topic with QoS > 0 and then disconnect. Any message with QoS > 0 published which matches the topic will trigger the hook.
