### ISSUE TITLE
Prometheus metrics are failing with 500 error

### ISSUE THREAD

**Issue by sarunask** [vernemq/vernemq#1361]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version: 1.9.2
- OS: Alpine
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
########## Start ##########
vmq_bridge.ssl.sbr0=mqtt.zodiac.iot.drydock.studio:8883
vmq_bridge.ssl.sbr0.certfile=/etc/ssl/vernemq/bridge_tls.crt
listener.ssl.default=0.0.0.0:8883
vmq_bridge.ssl.sbr0.keyfile=/etc/ssl/vernemq/bridge_tls.key
listener.ssl.keyfile=/etc/ssl/vernemq/tls.key
listener.ssl.require_certificate=on
vmq_bridge.ssl.sbr0.tls_version=tlsv1.2
allow_subscribe_during_netsplit=on
vmq_bridge.ssl.sbr0.topic.2=v1.zodiac.openocean.studio/+/bridge/* out 1
vmq_bridge.ssl.sbr0.topic.3=v1.zodiac.openocean.studio/+/app/* out 1
vmq_bridge.ssl.sbr0.topic.1=v1.zodiac.openocean.studio/+/ecr/* out 1
listener.ssl.certfile=/etc/ssl/vernemq/tls.crt
vmq_bridge.ssl.sbr0.insecure=off
listener.ssl.allowed_protocol_versions=3,4,5,131
allow_publish_during_netsplit=on
allow_anonymous=on
listener.ssl.cafile=/etc/ssl/vernemq/ca.crt
allow_unsubscribe_during_netsplit=on
plugins.vmq_bridge=on
listener.ssl.use_identity_as_username=on
vmq_bridge.ssl.sbr0.max_outgoing_buffered_messages=10000
log.console=console
allow_register_during_netsplit=on
listener.tcp.localhost=127.0.0.1:1883
vmq_bridge.ssl.sbr0.cafile=/etc/ssl/vernemq/bridge_ca.crt
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.4.96.83:1883
listener.ws.default = 10.4.96.83:8080
listener.vmq.clustering = 10.4.96.83:44053
listener.http.metrics = 10.4.96.83:8888
- Cluster size/standalone:

### Expected behavior

- Please describe the expected behaviour.
Prometheus metrics should be exported to via http://10.4.96.83:8888/metrics

### Actual behaviour
No metrics. In logs I see such messages:
17:29:09.243 [error] CRASH REPORT Process <0.723.0> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size("The number of dropped messages (queue full)") in vmq_metrics_http:prometheus_output/2 line 77
17:29:09.244 [error] Cowboy stream 1 with ranch listener {{10,4,96,83},8888} and connection process <0.722.0> had its request process exit with reason: bad argument in call to erlang:byte_size("The number of dropped messages (queue full)") in vmq_metrics_http:prometheus_output/2 line 77

- Please include minimal steps to reproduce the issue, if possible.
1. Launch VerneMQ 1.9.2 with configuration provided.
2. Observe issues in logs.

**Comment by dergraf** [comment]
Thanks for opening this issue. This is a bug in the vmq_bridge metrics code. A PR is ready and has to wait for review. 

Thanks again!

**Comment by dergraf** [comment]
Fixed. Will be released with 1.10
