### ISSUE TITLE
VerneMQ in bridge mode fails to get data from it's upstream peer

### ISSUE THREAD

**Issue by sarunask** [vernemq/vernemq#1362]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version: 1.9.2
- OS: Alpine
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
########## Start ##########
vmq_bridge.ssl.sbr0=mqtt.zodiac.iot.openocean.studio:8883
vmq_bridge.ssl.sbr0.certfile=/etc/ssl/vernemq/bridge_tls.crt
listener.ssl.default=0.0.0.0:8883
vmq_bridge.ssl.sbr0.keyfile=/etc/ssl/vernemq/bridge_tls.key
listener.ssl.keyfile=/etc/ssl/vernemq/tls.key
listener.ssl.require_certificate=on
vmq_bridge.ssl.sbr0.tls_version=tlsv1.2
allow_subscribe_during_netsplit=on
vmq_bridge.ssl.sbr0.topic.2=v1.zodiac.openocean.studio/+/bridge/* in
vmq_bridge.ssl.sbr0.topic.3=v1.zodiac.openocean.studio/+/app/* in
vmq_bridge.ssl.sbr0.topic.1=v1.zodiac.openocean.studio/+/ecr/* in
listener.ssl.certfile=/etc/ssl/vernemq/tls.crt
vmq_bridge.ssl.sbr0.insecure=off
listener.ssl.allowed_protocol_versions=3,4,5,131
allow_publish_during_netsplit=on
allow_anonymous=on
listener.ssl.cafile=/etc/ssl/vernemq/ca.crt
allow_unsubscribe_during_netsplit=on
plugins.vmq_bridge=on
listener.ssl.use_identity_as_username=on
vmq_bridge.ssl.sbr0.max_outgoing_buffered_messages=10000
log.console=console
allow_register_during_netsplit=on
listener.tcp.localhost=127.0.0.1:1883
vmq_bridge.ssl.sbr0.cafile=/etc/ssl/vernemq/bridge_ca.crt
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.5.109.186:1883
listener.ws.default = 10.5.109.186:8080
listener.vmq.clustering = 10.5.109.186:44053
listener.http.metrics = 10.5.109.186:8888
- Cluster size/standalone: standalone

### Expected behavior

- Please describe the expected behaviour.
VerneMQ should connect to master via bridge and start pulling data in.

### Actual behaviour
No data flowing in. Error messages are:
10:46:00.937 [error] Supervisor vmq_bridge_sup had child {vmq_bridge,"mqtt.zodiac.iot.openocean.studio",8883} started with vmq_bridge:start_link(ssl, "mqtt.zodiac.iot.openocean.studio", 8883, {vmq_reg,direct_plugin_exports,[vmq_bridge]}, [{cleansession,false},{client_id,"vernemq-0.sbr0"},{keepalive_interval,60},{restart_timeout,10},...]) at <0.573.0> exit with reason no case clause matching 0 in vmq_reg:publish/4 line 308 in context child_terminated
10:46:01.245 [error] gen_server <0.581.0> terminated with reason: no case clause matching 0 in vmq_reg:publish/4 line 308
10:46:01.245 [error] CRASH REPORT Process <0.581.0> with 2 neighbours crashed with reason: no case clause matching 0 in vmq_reg:publish/4 line 308
10:46:01.246 [error] Supervisor vmq_bridge_sup had child {vmq_bridge,"mqtt.zodiac.iot.openocean.studio",8883} started with vmq_bridge:start_link(ssl, "mqtt.zodiac.iot.openocean.studio", 8883, {vmq_reg,direct_plugin_exports,[vmq_bridge]}, [{cleansession,false},{client_id,"vernemq-0.sbr0"},{keepalive_interval,60},{restart_timeout,10},...]) at <0.581.0> exit with reason no case clause matching 0 in vmq_reg:publish/4 line 308 in context child_terminated
10:46:04.492 [error] gen_server <0.589.0> terminated with reason: no case clause matching 0 in vmq_reg:publish/4 line 308
10:46:04.492 [error] CRASH REPORT Process <0.589.0> with 2 neighbours crashed with reason: no case clause matching 0 in vmq_reg:publish/4 line 308
10:46:04.492 [error] Supervisor vmq_bridge_sup had child {vmq_bridge,"mqtt.zodiac.iot.openocean.studio",8883} started with vmq_bridge:start_link(ssl, "mqtt.zodiac.iot.openocean.studio", 8883, {vmq_reg,direct_plugin_exports,[vmq_bridge]}, [{cleansession,false},{client_id,"vernemq-0.sbr0"},{keepalive_interval,60},{restart_timeout,10},...]) at <0.589.0> exit with reason no case clause matching 0 in vmq_reg:publish/4 line 308 in context child_terminated
10:46:04.492 [error] Supervisor vmq_bridge_sup had child {vmq_bridge,"mqtt.zodiac.iot.openocean.studio",8883} started with vmq_bridge:start_link(ssl, "mqtt.zodiac.iot.openocean.studio", 8883, {vmq_reg,direct_plugin_exports,[vmq_bridge]}, [{cleansession,false},{client_id,"vernemq-0.sbr0"},{keepalive_interval,60},{restart_timeout,10},...]) at <0.589.0> exit with reason reached_max_restart_intensity in context shutdown
10:46:04.493 [info] Application vmq_bridge exited with reason: shutdown

- Please include minimal steps to reproduce the issue, if possible.

**Comment by dergraf** [comment]
Thank you for opening the issue! PR is on it's way.
