### ISSUE TITLE
Issue with shared subscription after nodes comes up again which went down earlier.

### ISSUE THREAD

**Issue by jayjamba** [vernemq/vernemq#1364]
Hi,
I am connecting to vernemq cluster through eclipse paho client(mentioned below). Our vernemq is deployed on 3 machines (192.168.0.1, 192.168.0.2 and 192.168.0.3) and is clustered.

Through my java code I am publishing message every one minute to one shared topic : $share/mygroup/My-Topic and in that application I have also subscribed to the given shared topic. 

I have started 3 instances of my application on 8081, 8082 and 8083. So the message is received on either of the ports i.e. 8081, 8082 or 8083.

Now, I turned off vernemq node of 192.168.0.1, but still my application on all 3 ports runs fine - publishing and receiving message every one minute. 

I turned off vernemq node of 192.168.0.2 and my application on all 3 ports still runs fine - publishing and receiving message every one minute.

**Now my problem starts when** I turn ON vernemq node of 192.168.0.1 (it joins the cluster back), here my application publishes to given shared topic but its not received on any of the ports i.e. 8081, 8082 or 8083.

Now, I also turned ON vernemq node of 192.168.0.2 (this also joins the cluster back), here again my application still publishes to given shared topic but its not received on any of the ports i.e. 8081, 8082 or 8083.

The above issue is not observed if the topic is normal topic and not the shared one. Not sure if I am missing some config changes in my vernemq.conf or in eclipse paho java client.

My Eclipse paho java client is :
public MqttClient getClient() throws MqttException {
	final MqttClient mqttClient = new MqttClient("tcp://192.168.0.1:1883", MqttClient.generateClientId());
	final MqttConnectOptions connectOptions = new MqttConnectOptions();
	connectOptions.setCleanSession(false);
	connectOptions.setAutomaticReconnect(true);
	connectOptions.setServerURIs(new String[] { "tcp://192.168.0.1:1883", "tcp://192.168.0.2:1883", "tcp://192.168.0.3:1883" });
	mqttClient.connect(connectOptions);
	return mqttClient;
}

Changes done in my vernemq.conf in all 3 machines are mentioned below, rest all values of properties are the default ones :
1) allow_anonymous = on

2) listener.tcp.default = 0.0.0.0:1883

3) nodename=vernemq1@192.168.0.1 (on 192.168.0.1), 
   nodename=vernemq2@192.168.0.2 (on 192.168.0.2),
   nodename=vernemq2@192.168.0.3 (on 192.168.0.3)
   
4) listener.vmq.clustering = 192.168.0.1:44053 (on 192.168.0.1), 
   listener.vmq.clustering = 192.168.0.2:44053 (on 192.168.0.2), 
   listener.vmq.clustering = 192.168.0.3:44053 (on 192.168.0.3) 

5) 
erlang.distribution.port_range.minimum = 6000
erlang.distribution.port_range.maximum = 7999

6)
allow_register_during_netsplit=on
allow_publish_during_netsplit=on
allow_subscribe_during_netsplit=on
allow_unsubscribe_during_netsplit=on

7) max_last_will_delay = 1h

8) listener.tcp.allowed_protocol_versions = 3,4,5

**Comment by dergraf** [comment]
Thanks for opening the issue. We've heard of similar issues before. Most of the time the issue was that there was a 'forgotten' offline session present. Could you double check with the `vmq-admin session show` command and see if there are no suspicious offline session present? 

Are you using 'random' client ids? e.g. creating a new client id on every (re-)connect?

**Comment by jayjamba** [comment]
I verified vmq-admin session show and it showed all 3 nodes in cluster up and running.
+----------------------+-------+
|         Node         |Running|
+----------------------+-------+
|vernemq2@192.168.0.2| true  |
|vernemq1@192.168.0.1 | true  |
|vernemq3@192.168.0.3| true  |
+----------------------+-------+

I am using random client ids as shown below in my java client code:
public MqttClient getClient() throws MqttException {
final MqttClient mqttClient = new MqttClient("tcp://192.168.0.1:1883", **MqttClient.generateClientId()**);
final MqttConnectOptions connectOptions = new MqttConnectOptions();
connectOptions.setCleanSession(false);
connectOptions.setAutomaticReconnect(true);
connectOptions.setServerURIs(new String[] { "tcp://192.168.0.1:1883", "tcp://192.168.0.2:1883", "tcp://192.168.0.3:1883" });
mqttClient.connect(connectOptions);
return mqttClient;
}

**Comment by jayjamba** [comment]
Hi Andre,
Did you get a chance to look into this issue ?

**Comment by dergraf** [comment]
I would recommend to NOT use random client ids with cleanSession=false... as this makes it more difficult to debug the system later on.

My guess is that those offline sessions have retrieved your messages and wait to deliver them as soon as those clients come back up online. You can check this hypothesis with `vmq-admin session show --client_id --is_offline --offline_messages` which will give you a count of offline messages.

For now, I would get rid of all those offline clients and try again.

**Comment by jayjamba** [comment]
okay, I will try and get back to you soon. Thanks !

**Comment by jayjamba** [comment]
Hi Andre,
I gave a try here, but specifying the same client id through the entire session - in case of publisher and subscriber both. **But the issue still persist.** :(

When I turn back ON the 2nd server it adds back 2 offline session 
 sudo vmq-admin session show
Last login: Wed Nov 20 07:25:24 EST 2019 on pts/2
+------------------+---------+----------+-------------+---------+---------+
|    client_id     |is_online|mountpoint|  peer_host  |peer_port|  user   |
+------------------+---------+----------+-------------+---------+---------+
|paho26196967209400|  true   |          |192.168.0.125|  56933  |undefined|
|paho26189316701400|  true   |          |192.168.0.125|  56932  |undefined|
**|paho26204852759200|  false  |          |    null     |  null   |  null   |**
|paho26204492937600|  true   |          |192.168.0.125|  56931  |undefined|
**|paho26197319310200|  false  |          |    null     |  null   |  null   |**
+------------------+---------+----------+-------------+---------+---------+

And when I turn back ON the 1st server it adds one more offline session, so in total we have 6 sessions, 3 offline and 3 online sessions.
 sudo vmq-admin session show
Last login: Wed Nov 20 07:27:29 EST 2019 on pts/2
+------------------+---------+----------+-------------+---------+---------+
|    client_id     |is_online|mountpoint|  peer_host  |peer_port|  user   |
+------------------+---------+----------+-------------+---------+---------+
|paho26196967209400|  true   |          |192.168.0.125|  56933  |undefined|
|paho26189316701400|  true   |          |192.168.0.125|  56932  |undefined|
**|paho26204852759200|  false  |          |    null     |  null   |  null   |**
|paho26204492937600|  true   |          |192.168.0.125|  56931  |undefined|
**|paho26189679906400|  false  |          |    null     |  null   |  null   |**
**|paho26197319310200|  false  |          |    null     |  null   |  null   |**
+------------------+---------+----------+-------------+---------+---------+

**Comment by seanwinterberger** [comment]
The client id is still being generated.

**Comment by jayjamba** [comment]
I didn't get you. How the client id is generated and where ? Below is my code, where I am passing client id, here I make sure that every time when it creates client for publishing the message same client id is passed.

public MqttClient getClient(final String clientId) throws MqttException {
		final MqttClient mqttClient = new MqttClient(getMqttBrokerUrl(), clientId);
		final MqttConnectOptions connectOptions = new MqttConnectOptions();
		connectOptions.setCleanSession(false);
		connectOptions.setAutomaticReconnect(true);
		connectOptions.setServerURIs(new String[] { getMqttBrokerUrl(), getMqttBrokerUrl2(), getMqttBrokerUrl3() });
		mqttClient.connect(connectOptions);
		return mqttClient;
	}

**Comment by jayjamba** [comment]
Hi Andre/Sean,
Did you get a chance to look into this ?

**Comment by larshesel** [comment]
Hi, I think what @seanwinterberger was hinting at was that the names of the client-ids look like they are generated by the `generateClientId()` method. The question is where does  the `clientId` above come from? 

>  And what is the command to clean up all offline sessions at once ?

Remove all VerneMQ data. I.e. likely the `/var/lib/vernemq/meta` and `/var/lib/vernemq/msgstore` folders.

Hope this helps.

**Comment by jayjamba** [comment]
clientId is the one that I am passing from my code, which I make sure that its  generated only once.
So below code (in bold) is executed once on application startup:
**String clientId = MqttClient.generateClientId();**

And this clientId is getting passed every one minute before publishing message:
mqttConnectionUtil.getClient(clientId);

MQTTConnectionUtil.java

public MqttClient getClient(final String clientId) throws MqttException {
final MqttClient mqttClient = new MqttClient(getMqttBrokerUrl(), clientId);
final MqttConnectOptions connectOptions = new MqttConnectOptions();
connectOptions.setCleanSession(false);
connectOptions.setAutomaticReconnect(true);
connectOptions.setServerURIs(new String[] { "192.168.0.1", "192.168.0.2", "192.168.0.3" });
mqttClient.connect(connectOptions);
return mqttClient;
}

**Comment by larshesel** [comment]
Right, but nevertheless it looks like you have a lot of different client-ids in the session list above. Perhaps these are left-overs from earlier sessions then which makes sense since the clean_session flag is set to false. As already mentioned earlier those offline sessions are most likely the ones which are 'stealing' your messages as they are still receiving messages if they subscribed to the shared subscription.

**Comment by jayjamba** [comment]
After cleaning up var/lib/vernemq/meta and /var/lib/vernemq/msgstore, my original issue was resolved. However I have one question, so to avoid such prob. and to avoid such clean up of the above folders, do I need to provide OR maintain one constant clientID, which will be used even if MY OWN APPLICATION restarts..is it ?
