### ISSUE TITLE
vmq listener not running but cluster shows normal ? 

### ISSUE THREAD

**Issue by chenxinlong** [vernemq/vernemq#1368]
### Environment

- VerneMQ Version: 1.7.1
- OS:CentOS 7 
- Cluster size/standalone: 5 nodes

### Expected behavior

The vmq listener(port 44053) not running, then its communication with other nodes in the cluster will fail.  And the `vmq-admin cluster show` will indicate this node not running. 

#### node : us  

![image](https://user-images.githubusercontent.com/9261954/69041115-e8916100-0a29-11ea-9438-837b37bbeb49.png)

### node : cn  

![image](https://user-images.githubusercontent.com/9261954/69041342-53429c80-0a2a-11ea-9633-63510e9ccfd3.png)

![image](https://user-images.githubusercontent.com/9261954/69042559-5d659a80-0a2c-11ea-834c-097f11650936.png)

**Comment by larshesel** [comment]
Couldn't it be that the error was ephemeral and has been resolved when running `vmq-admin cluster show`?

**Comment by chenxinlong** [comment]
Sorry it's vernemq 1.7.1

Like pic below : the left panel is VerneMQ@10.0.0.3, the vmq listener doesn't running. The right panel is another node (you can compare it from the docker container name), `vmq-admin cluster show` shows VerneMQ@10.0.0.3 is running but the log shows `mq_cluster_node:connect_async:292 can't connect to cluster node 'VerneMQ@10.0.0.3' due to econnrefused`.  

It is not a transient error, from the `date` command you can see it has been 6 hours since I create this issue, it is still happening.

![image](https://user-images.githubusercontent.com/9261954/69066560-74bc7c00-0a5c-11ea-9c0d-23ef87c06d9e.png)

**Comment by larshesel** [comment]
Ok - I know we at some point (but can't remember exactly when) strengthened the conditions for if a node is shown as running or not. Perhaps it's been fixed in one of the newer releases. In any case, without more information it's hard to know where to start. I'll close this for now, but please reopen if more information becomes available.
