### ISSUE TITLE
406 Not Acceptable when polling metrics using telegraf

### ISSUE THREAD

**Issue by sdie-idirect** [vernemq/vernemq#1374]
When trying to access the metrics endpoint using telegraf Prometheus plugin, vernemq responds with http 406 Not Acceptable

> GET /metrics HTTP/1.1
> Host: localhost:8888
> User-Agent: Go-http-client/1.1
> Accept: application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3
> Accept-Encoding: gzip
> Connection: close
> 
> HTTP/1.1 406 Not Acceptable
> connection: close
> content-length: 0
> date: Thu, 14 Nov 2019 10:45:29 GMT
> server: Cowboy

When trying to access the data via curl we get the same response for accept header text/plain;version=0.0.4, but not for accept header text/plain

> 
> $ curl -v -H "Accept:text/plain;version=0.0.4" http://localhost:8888/metrics
> * About to connect() to localhost port 8888 (#0)
> *   Trying ::1...
> * Connection refused
> *   Trying 127.0.0.1...
> * Connected to localhost (127.0.0.1) port 8888 (#0)
> > GET /metrics HTTP/1.1
> > User-Agent: curl/7.29.0
> > Host: localhost:8888
> > Accept:text/plain;version=0.0.4
> >
> < HTTP/1.1 406 Not Acceptable
> < content-length: 0
> < date: Thu, 21 Nov 2019 10:38:46 GMT
> < server: Cowboy
> <

> $ curl -v -H "Accept:text/plain" http://localhost:8888/metrics
> * About to connect() to localhost port 8888 (#0)
> *   Trying ::1...
> * Connection refused
> *   Trying 127.0.0.1...
> * Connected to localhost (127.0.0.1) port 8888 (#0)
> > GET /metrics HTTP/1.1
> > User-Agent: curl/7.29.0
> > Host: localhost:8888
> > Accept:text/plain
> >
> < HTTP/1.1 200 OK
> < content-length: 28696
> < content-type: text/plain
> < date: Thu, 21 Nov 2019 10:40:39 GMT
> < server: Cowboy
> <
> # HELP socket_open The number of times an MQTT socket has been opened.
> # TYPE socket_open counter
> socket_open{node="VerneMQ@127.0.0.1"} 0
> # HELP socket_close The number of times an MQTT socket has been closed.
> # TYPE socket_close counter

## Environment

- VerneMQ Version: 1.9.2
- OS: CentOS Linux 7
- Cluster size/standalone: stand alone

### Expected behavior

- vernemq /metrics endpoint should accept request containing accept header text/plain

### Actual behaviour

- vernemq /metrics endpoint returns 406 Not Acceptable when any other accept headers are also sent

**Comment by dergraf** [comment]
interesting... the Accept header seems to mess it up. we'll look at it

**Comment by dambrisco** [comment]
@dergraf We're running into this same issue with the datadog prometheus scraper in after upgrading from 1.8.0 to 1.10.2-1

From the datadog logs:
```json
{
  "message":"406 Client Error: Not Acceptable for url: http://<scrubbed>:8888/metrics",
  "traceback":"Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 820, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/prometheus/base_check.py\", line 105, in check\n    scraper.process(\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/prometheus/mixins.py\", line 398, in process\n    for metric in self.scrape_metrics(endpoint):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/prometheus/mixins.py\", line 362, in scrape_metrics\n    response = self.poll(endpoint)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/prometheus/mixins.py\", line 549, in poll\n    response.raise_for_status()\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/requests/models.py\", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: http://<scrubbed>:8888/metrics\n"
}
```
