### ISSUE TITLE
Sessions stopping abnormally

### ISSUE THREAD

**Issue by saranglakare** [vernemq/vernemq#1376]
### Environment

- VerneMQ Version: 1.9.2
- OS: Ubuntu
- Erlang/OTP version (if building from source):
- Cluster size/standalone: standalone

### The problem
Clients are highly unstable and don't get stable MQTT connection. The connection works for a while but then it stops abruptly.

I see the following in Erlang logs

```
10:00:54.878 [warning] stopped connected session, due to unexpected frame type {error,no_topic_provided}
10:00:54.878 [warning] session stopped abnormally due to '{error,unexpected_message,{error,no_topic_provided}}'
10:00:54.878 [debug] transition from online --> offline because of 'DOWN'
```

and the following in VerneMQ logs:
```
2019-11-23 18:58:29.285 [warning] <0.3354.25>@vmq_mqtt_fsm:connected:470 stopped connected session, due to unexpected frame type {error,no_topic_provided}
2019-11-23 18:58:29.285 [warning] <0.3354.25>@vmq_ranch:teardown:159 session stopped abnormally due to '{error,unexpected_message,{error,no_topic_provided}}'
```

Any idea why the session is stopping or how I can get more info on this problem? I searched extensively but there is no help anywhere on the `no_topic_provided` or `unexpected_message` error messages, hence opening a new issue.

Any help highly appreciated. Thanks!

**Comment by boboxiaodd** [comment]
https://github.com/vernemq/vernemq/blob/78ee43ae627ecb879c181c2df437751403716736/apps/vmq_commons/src/vmq_parser.erl#L211

i think , your client recv some bad topics message。

**Comment by saranglakare** [comment]
Yes, I am quite sure there is some issue on the client end, but my questions are:

- how to diagnose this? I want to know the client that caused this and the payload.
- why should session stop? It should raise warning, ignore and continue the session.

**Comment by larshesel** [comment]
Hi @saranglakare as @boboxiaodd mentions your client is sending invalid MQTT and this is what is logged. If the client isn't confirming to the MQTT spec VerneMQ doesn't know what to do with it and hence the session is terminated abnormally. 

To debug your client you could try to use tools such as wireshark or tcpdump. 

Hope this helps!
