### ISSUE TITLE
Auth expiry

### ISSUE THREAD

**Issue by tobdub** [vernemq/vernemq#1377]
Is there a way to cause a client's authentication to expire after a certain amount of time? I.e. disconnect the client when the authentication expires to force re-authentication, ideally using a webhook plugin.

**Comment by larshesel** [comment]
This isn't directly supported but there are various possible directions you can go. You can use the command `vmq-admin session disconnect` to disconnect a specific client (see `vmq-admin session disconnect --help` for more information). You could also use the HTTP API to invoke this command. So with this you could explicitly disconnect clients and force a reauth from your webhook implementation.

With a native erlang plugin it is possible to do the same by calling the `vernemq_dev_api:disconnect_by_subscriber_id/2` function, but to implement that it of course needs a bit of Erlang knowledge.

Some kind of reauth/auth expiration feature would be interesting, though I'm not sure how such a mechanism would work in general across the different plugins.

**Comment by tobdub** [comment]
OK, thanks, will look into it.
I was thinking something like returning an `auth_expiry: 1574760675` modifier for `auth_on_register`, and the broker could disconnect clients after expiration.
My main use case is token based authentication where tokens have a relatively short expiration time.

**Comment by himadrinath** [comment]
vernemq can also set a unique connect id or session id for each connection so we can disconnect that specific connection from our backend not by just client id. disconnecting using client id can create problem in some design. if the client connected using multiple device with same credential calling session disconnect will disconnect all connection
