### ISSUE TITLE
Clustering issue

### ISSUE THREAD

**Issue by jayjamba** [vernemq/vernemq#1384]
Scenario : Our application is running on 3 different ports 8081, 8082 and 8083. We have also deployed Vernemq broker on 3 different machines 192.168.0.1, 192.168.0.2, 192.168.0.3 and is clustered successfully. Our application is connecting to this broker.

Few Questions related to above scenario:
Q1) Since our application is running on 3 different ports, so Should we connect to different vernemq nodes from different port i.e. 8081 port should connect to 192.168.0.1; 8082 port should connect to 192.168.0.2 and 8083 port should connect to 192.168.0.3

OR Connecting to one node from all our application nodes is advisable ? i.e. connecting to 192.168.0.1 from all 3 ports 8081,8082 and 8083. And then load balance on Vernemq cluster is managed by itself ?

Q2) Any particular configuration that we need to take care of to prevent messages from getting dropped ? Coz we have been facing problem of messages getting dropped in either of the case i.e. even if we connect to one broker from all 3 ports OR connecting to different brokers from all 3 ports.

Below are the configuration we have changed in the conf file:

listener.tcp.allowed_protocol_versions = 3,4,5
max_last_will_delay = 1h
max_online_messages = 10000000
max_offline_messages = 10000000

Q3) Which is the reliable JAVA client to connect to any node in cluster ? 
Can you provide sample code to connect to one node and if that node fails or comes down, how will my application will still keep going by connecting to other node present in cluster ?

I tried with Eclipse Paho client and HiveMQ Client. The code is mentioned below. 

Eclipse Paho -

public MqttClient getClient(final String clientId) throws MqttException {
	final MqttClient mqttClient = new MqttClient("192.168.0.1", clientId);
	final MqttConnectOptions connectOptions = new MqttConnectOptions();
	connectOptions.setCleanSession(false);
	connectOptions.setAutomaticReconnect(true);
	connectOptions.setServerURIs(new String[] { "192.168.0.1", "192.168.0.2", "192.168.0.3" });
	mqttClient.connect(connectOptions);
	return mqttClient;
}

HiveMQ -

final Mqtt5BlockingClient client = Mqtt5Client.builder().identifier(UUID.randomUUID().toString())
	.serverHost("192.168.0.1").serverPort(1883).addDisconnectedListener(context -> {
		System.out.println(context.getCause());
		context.getReconnector().reconnect(true).delay(5, TimeUnit.SECONDS);
		System.out.println(context.getReconnector().getAttempts());
		if (context.getReconnector().getAttempts() > 3) {
			context.getReconnector().transportConfig().serverHost("192.168.0.2").applyTransportConfig();
		}
	}).buildBlocking();

**Comment by larshesel** [comment]
Hi Q1 depends on your use case. Mostly the cluster is put behind a load balancer which can distribute the incoming client connections over the cluster.

Q2: Where do the messages get dropped? How do you assertain that?

Q3: I know the Ecplise Paho clients are very good. I don't know the other one. you have to investigate with their respective documentation/forums how to write them to do automatic reconnects in case of server failure.

Hope this help
