### ISSUE TITLE
Cluster message passing

### ISSUE THREAD

**Issue by jasmt-us** [vernemq/vernemq#1386]
### Environment

- VerneMQ Version: 1.10.0 (and tested prior to upgrade from 1.9.2)
- OS: Ubuntu 18.04
- VerneMQ configuration (vernemq.conf) or the changes from the default:

On both nodes:

listener.tcp.default = 0.0.0.0:1883
listener.ws.default = 0.0.0.0:9001
listener.tcp.allowed_protocol_versions = 3,4,5
listener.vmq.clustering = x.x.x.x:44053  (where x.x.x.x is unique per node, and is internal address)

- Cluster size/standalone:

Two nodes:

vps-app01
vps-app02

### Expected behavior

Messages posted to either node should be delivered to those subscribed to either node.

### Actual behavior

Messages sent from one node (app01) are only received on the same node, but those sent from the second node (app02) are received by BOTH nodes.

Details:

On vps-app01, I have a node configured as VerneMQ1A@xx.xx.xx.81, where xx.xx.xx.81 is the external IP.

 
![image](https://user-images.githubusercontent.com/55640715/69658684-4a615480-1042-11ea-8052-a63b1998e50f.png)

On vps-app02, I have a node configured as VerneMQ1A@xx.xx.xx.812, where xx.xx.xx.82 is the external IP.

![image](https://user-images.githubusercontent.com/55640715/69658698-5220f900-1042-11ea-8229-11b2cb9408c4.png)

On both nodes:

listener.tcp.default = 0.0.0.0:1883
listener.ws.default = 0.0.0.0:9001
listener.tcp.allowed_protocol_versions = 3,4,5
listener.vmq.clustering = x.x.x.x:44053  (where x.x.x.x is unique per node, and is internal address)

For a client test, I am using MQTTLens from a single workstation, with two connections.
Connection one is to vps-app01, and has a client_id of “lens_cient1”.
Connection two is to vps-app02, and has a client_id of “lens_client2a”.
Connections are verified from each node:

![image](https://user-images.githubusercontent.com/55640715/69658725-5d742480-1042-11ea-8234-480916cc10b6.png)

and

![image](https://user-images.githubusercontent.com/55640715/69658753-65cc5f80-1042-11ea-8c4f-3123215fc63c.png)

Both connections are subscribed to all (#) as seen here:

![image](https://user-images.githubusercontent.com/55640715/69658773-6d8c0400-1042-11ea-9f7b-4966d3cad811.png)

When publishing to app01, to “test/topic” with message  “fromApp01Client1” it is received by app01, but not app02, as you can see here:

![image](https://user-images.githubusercontent.com/55640715/69658786-7381e500-1042-11ea-95d4-b80f17a75e91.png)

HOWEVER, when app02 published to “test/topic” with message “FromApp02Client2a”, it is received by both nodes, as seen here:

![image](https://user-images.githubusercontent.com/55640715/69658804-7ed51080-1042-11ea-9708-1dbab5074b0a.png)
 
Any ideas?

**Comment by dergraf** [comment]
Thanks for opening the issue!
Can you post a screenshot of `localhost:8888/status` (or any other http port that you have configured?

**Comment by jasmt-us** [comment]
![image](https://user-images.githubusercontent.com/55640715/69663429-d75cdb80-104b-11ea-981b-2fc9e476263b.png)

**Comment by jasmt-us** [comment]
Closing - I followed the same install, copied the same config, and all looks fine now.
