### ISSUE TITLE
trade_consistency is not working

### ISSUE THREAD

**Issue by dsboo** [vernemq/vernemq#1387]
# Environment

- VerneMQ Version: 1.5.0-1
- OS: centos 7.4
- Erlang/OTP version (if building from source): use rpm(vernemq-1.5.0-1.el7.centos.x86_64.rpm)
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: cluster is 3

### Expected behavior

vernemq start normally.

### Actual behaviour

when i use trade_consistency, vernemq can not start.

and run [vernemq console] command i can see like below.

> [irteamsu@dev-prism-msg003-ncl ~]$ sudo vernemq console
13:07:07.887 [error] You've tried to set trade_consistency, but there is no setting with that name.
13:07:07.887 [error]   Did you mean one of these?
13:07:07.925 [error]     log.console
13:07:07.926 [error]     graphite_api_key
13:07:07.926 [error]     graphite_host
13:07:07.934 [error] Error generating configuration in phase transform_datatypes
13:07:07.934 [error] Conf file attempted to set unknown variable: trade_consistency

vernemq 1.5.0-1 not support that config?

**Comment by larshesel** [comment]
Trade consistency was removed in VerneMQ 0.15.1. Use the `allow_during_XXX_netsplit` settings instead. See also our documentation concerning this: https://docs.vernemq.com/clustering/netsplits
