### ISSUE TITLE
VerneMQ crashes with port_died normal messages

### ISSUE THREAD

**Issue by shashankel** [vernemq/vernemq#1388]
### Environment

VerneMQ Version: 1.9.2
OS: Ubuntu 18.04.2 LTS
Erlang/OTP version (if building from source): 22
VerneMQ configuration (vernemq.conf) or the changes from the default

[vernemq.txt](https://github.com/vernemq/vernemq/files/3907386/vernemq.txt)

Cluster size/standalone: 3 nodes

### Expected behavior
VerneMQ should not crash

- Please describe the expected behaviour.

### Actual behaviour
2019-12-01 00:26:49 =ERROR REPORT====
** Generic server disksup terminating
** Last message in was {'EXIT',#Port<0.9>,normal}
** When Server state == [{data,[{"OS",{unix,linux}},{"Timeout",1800000},{"Threshold",80},{"DiskData",[{"/dev",7684044,0},{"/run",1539232,1},{"/",30428560,30},{"/dev/shm",7696140,0},{"/run/lock",5120,0},{"/sys/fs/cgroup",7696140,0},{"/snap/amazon-ssm-agent/1455",18432,100},{"/snap/amazon-ssm-agent/1480",18432,100},{"/snap/core/7917",91264,100},{"/snap/core/8039",91264,100},{"/run/user/1003",1539228,0},{"/run/user/1001",1539228,0}]}]}]
** Reason for termination ==
** {port_died,normal}
2019-12-01 00:26:49 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.190.0>
    registered_name: []
    exception exit: {{bad_return,{{vmq_server_app,start,[normal,[]]},{'EXIT',{shutdown,{gen_server,call,[vmq_plugin_mgr,{enable_system_plugin,vmq_plumtree,[internal]},infinity]}}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.189.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.191.0>,normal}]
    links: [<0.189.0>,<0.43.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 216
  neighbours:
2019-12-01 00:26:49 =ERROR REPORT====
** Generic server memsup terminating
** Last message in was {'EXIT',<0.158.0>,{port_died,normal}}
** When Server state == [{data,[{"Timeout",60000}]},{items,{"Memory Usage",[{"Allocated",3599863808},{"Total",15761698816}]}},{items,{"Worst Memory User",[{"Pid",<0.8.0>},{"Memory",601832}]}}]
** Reason for termination ==
** {port_died,normal}
2019-12-01 00:26:49 =CRASH REPORT====
  crasher:
    initial call: disksup:init/1
    pid: <0.156.0>
    registered_name: disksup
    exception exit: {{port_died,normal},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,751}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [os_mon_sup,<0.154.0>]
    message_queue_len: 0
    messages: []
    links: [<0.155.0>]
    dictionary: [{{disk_almost_full,"/snap/amazon-ssm-agent/1480"},set},{{disk_almost_full,"/snap/amazon-ssm-agent/1455"},set},{{disk_almost_full,"/snap/core/7917"},set},{{disk_almost_full,"/snap/core/8039"},set}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 6317
  neighbours:
2019-12-01 00:26:49 =CRASH REPORT====
  crasher:
    initial call: memsup:init/1
    pid: <0.157.0>
    registered_name: memsup
    exception exit: {{port_died,normal},[{gen_server,handle_common_reply,8,[{file,"gen_server.erl"},{line,751}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [os_mon_sup,<0.154.0>]
    message_queue_len: 0
    messages: []
    links: [<0.155.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 673979
  neighbours:
2019-12-01 00:26:49 =SUPERVISOR REPORT====
     Supervisor: {local,os_mon_sup}
     Context:    child_terminated
     Reason:     {port_died,normal}
     Offender:   [{pid,<0.156.0>},{id,disksup},{mfargs,{disksup,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]

2019-12-01 00:26:49 =SUPERVISOR REPORT====
     Supervisor: {local,os_mon_sup}
     Context:    child_terminated
     Reason:     {port_died,normal}
     Offender:   [{pid,<0.157.0>},{id,memsup},{mfargs,{memsup,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]

- Please include minimal steps to reproduce the issue, if possible.

**Comment by larshesel** [comment]
Hi, do you know what is happening/what vernemq is doing when this error occurs? We've seen this before where this was due to systemd terminating vernemq.

**Comment by larshesel** [comment]
Closing for now - let us know if more information becomes available.
