### ISSUE TITLE
VerneMQ crashes with error Bad Match

### ISSUE THREAD

**Issue by shashankel** [vernemq/vernemq#1389]
### To help us save time and help you faster

Please do not insert images of text, but insert the text instead.

### Environment

VerneMQ Version: 1.9.2
OS: Ubuntu 18.04.2 LTS
Erlang/OTP version (if building from source): 22
VerneMQ configuration (vernemq.conf) or the changes from the default
[vernemq.txt](https://github.com/vernemq/vernemq/files/3914060/vernemq.txt)

Cluster size/standalone: 3 nodes

### Expected behavior

VerneMQ should not crash

Please describe the expected behaviour.
### Actual behaviour

VerneMQ crashes with error Bad Match

2019-12-03 08:22:49 =ERROR REPORT====
** Generic server vmq_systree terminating
** Last message in was timeout
** When Server state == true
** Reason for termination ==
** {{badmatch,[]},[{vmq_cluster,netsplit_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_cluster.erl"},{line,76}]},{vmq_metrics,misc_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,951}]},{vmq_metrics,metric_values,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,628}]},{vmq_metrics,metrics,1,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,317}]},{vmq_systree,handle_info,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_systree.erl"},{line,162}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-12-03 08:22:49 =CRASH REPORT====
  crasher:
    initial call: vmq_systree:init/1
    pid: <0.273.0>
    registered_name: vmq_systree
    exception error: {{badmatch,[]},[{vmq_cluster,netsplit_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_cluster.erl"},{line,76}]},{vmq_metrics,misc_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,951}]},{vmq_metrics,metric_values,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,628}]},{vmq_metrics,metrics,1,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,317}]},{vmq_systree,handle_info,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_systree.erl"},{line,162}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [vmq_metrics_sup,vmq_server_sup,<0.198.0>]
    message_queue_len: 0
    messages: []
    links: [<0.270.0>]
    dictionary: [{vmq_metrics_scheduler_wall_time,[{1,7228582,7228582},{2,11764768,11764768},{3,12173779,12173779},{4,9458945,9458945},{5,6572749,6572749},{6,9921335,9921335},{7,7491500,7491500},{8,9224506,9224506},{9,17375,7655091373},{10,7714,7655092158},{11,9091,7655093000},{12,7286,7655093720},{13,6882,7655094446},{14,105287053,7655095182},{15,17623210,7655095915},{16,884806821,7655096730}]}]
    trap_exit: false
    status: running
    heap_size: 17731
    stack_size: 27
    reductions: 7537
  neighbours:
2019-12-03 08:22:49 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_metrics_sup}
     Context:    child_terminated
     Reason:     {{badmatch,[]},[{vmq_cluster,netsplit_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_cluster.erl"},{line,76}]},{vmq_metrics,misc_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,951}]},{vmq_metrics,metric_values,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,628}]},{vmq_metrics,metrics,1,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,317}]},{vmq_systree,handle_info,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_systree.erl"},{line,162}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,<0.273.0>},{id,vmq_systree},{mfargs,{vmq_systree,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2019-12-03 08:22:50 =ERROR REPORT====
** Generic server vmq_systree terminating
** Last message in was timeout
** When Server state == true
** Reason for termination ==
** {{badmatch,[]},[{vmq_cluster,netsplit_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_cluster.erl"},{line,76}]},{vmq_metrics,misc_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,951}]},{vmq_metrics,metric_values,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,628}]},{vmq_metrics,metrics,1,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,317}]},{vmq_systree,handle_info,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_systree.erl"},{line,162}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-12-03 08:22:50 =CRASH REPORT====
  crasher:
    initial call: vmq_systree:init/1
    pid: <0.1282.0>
    registered_name: vmq_systree
    exception error: {{badmatch,[]},[{vmq_cluster,netsplit_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_cluster.erl"},{line,76}]},{vmq_metrics,misc_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,951}]},{vmq_metrics,metric_values,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,628}]},{vmq_metrics,metrics,1,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,317}]},{vmq_systree,handle_info,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_systree.erl"},{line,162}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [vmq_metrics_sup,vmq_server_sup,<0.198.0>]
    message_queue_len: 0
    messages: []
    links: [<0.270.0>]
    dictionary: [{vmq_metrics_scheduler_wall_time,[{1,14140282,14140282},{2,15492958,15492958},{3,15550715,15550715},{4,15063029,15063029},{5,6621920,6621920},{6,16509905,16509905},{7,16048309,16048309},{8,5262724,5262724},{9,17375,8691515971},{10,7714,8691516821},{11,9091,8691517640},{12,7286,8691518320},{13,6882,8691519054},{14,332970417,8691519949},{15,17623210,8691520640},{16,896989690,8691521450}]}]
    trap_exit: false
    status: running
    heap_size: 17731
    stack_size: 27
    reductions: 7261
  neighbours:
2019-12-03 08:22:50 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_metrics_sup}
     Context:    child_terminated
     Reason:     {{badmatch,[]},[{vmq_cluster,netsplit_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_cluster.erl"},{line,76}]},{vmq_metrics,misc_statistics,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,951}]},{vmq_metrics,metric_values,0,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,628}]},{vmq_metrics,metrics,1,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_metrics.erl"},{line,317}]},{vmq_systree,handle_info,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_systree.erl"},{line,162}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,<0.1282.0>},{id,vmq_systree},{mfargs,{vmq_systree,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

**Comment by larshesel** [comment]
Hi, do you know what is happening/what vernemq is doing when this error occurs?

**Comment by shashankel** [comment]
@larshesel No. It just crashes randomly

**Comment by larshesel** [comment]
So you just start VerneMQ and then this happens without any interaction at all? I'm afraid without more information it's hard to figure out what to do.

**Comment by shashankel** [comment]
@larshesel VerneMQ had been running for 10 hours and the crash occurred suddenly

**Comment by dergraf** [comment]
Can you see if the issue persists if you disable the systree metric exporter?
In your config file set `systree_enabled = off` and/or use `vmq-admin set systree_enabled=off`.

**Comment by shashankel** [comment]
@dergraf  We have set systree_enabled = off now. We will monitor and let you know if we see the problem again

**Comment by shashankel** [comment]
@dergraf One of the nodes crashed again today.

**Comment by ioolkos** [comment]
Could you forward crash_dump, or crash_dump slogan extracted from it?

**Comment by shashankel** [comment]
[vernemq-node-1.zip](https://github.com/vernemq/vernemq/files/3971666/vernemq-node-1.zip)
[vernemq-node-2.zip](https://github.com/vernemq/vernemq/files/3971667/vernemq-node-2.zip)
[vernemq-node-3.zip](https://github.com/vernemq/vernemq/files/3971668/vernemq-node-3.zip)

**Comment by ioolkos** [comment]
From the message given in the opening issue, it seems clear that `allow_register_during_netsplit = on`.
This is still on, right?
There's too much in the logs to give a quick answer, I'll try to review more in detail later.

**Comment by ioolkos** [comment]
While we'll be working on a fix for one of the errors we see (related to requesting a queue migration from a node that is down), the questions is why there is such a long netsplit situation. Was this noted in some way? was there a network component down?
