### ISSUE TITLE
Maximum lifetime for a connection

### ISSUE THREAD

**Issue by mprevide** [vernemq/vernemq#1390]
### Expected behavior

We are using TLS and keeping the connection open  to publish, but when we revoke a certificate and the CRL is updated with the serial number of the revoke certificate, the connection must be broken, It's not needed in the exact time, but soon. The solution may be  a max lifetime of connection.
Another point is a timeout for idle on the  connection.

### Actual behaviour

The connection  to publish doesn't expire when we keep the connection open.
The connection  to publish doesn't  broken for idle.

(When we try reconnect to publish , we can't connect as expect)

**Comment by mprevide** [comment]
There is one way to configure max lifetime?
Thx

**Comment by dergraf** [comment]
VerneMQ doesn't support this. Actually I am not even sure if TLS would support it out of the box. 
What you could do however is building a plugin that forcefully disconnects the clients in such circumstances.

**Comment by mprevide** [comment]
Thank you =)

**Comment by muhamedcpqd** [comment]
@dergraf, do you have a simple example to we follow?

**Comment by dergraf** [comment]
I don't have a good example I am afraid. But basically it boils down to call the `vernemq_dev_api:disconnect_by_subscriber_id` function (see: https://github.com/vernemq/vernemq_dev/blob/master/src/vernemq_dev_api.erl#L31) 
The best way to do this is with a VerneMQ plugin.

The `disconnect_by_subscriber_id` function is also exposed as a Lua function, maybe this simplifies the implementation of the plugin in case you don't know Erlang https://github.com/vernemq/vernemq/blob/de213cb95c45766e307b8b5a4e8b9dad497e46aa/apps/vmq_diversity/test/vmq_api_test.lua.

**Comment by muhamedcpqd** [comment]
ok, thanks!

**Comment by dergraf** [comment]
@mprevide @muhamedcpqd I forgot to mention a different approach, which might be even easier to implement. 
`vmq-admin session disconnect client-id=<myclientid>` will disconnect the client, if you add the `--cleanup` flag it will also cleanup any stored subscription and offline messages for this client.

As with every `vmq-admin` command this can also be executed via the VerneMQ HTTP API. So maybe this simplifies the story for you.
Cheers!

**Comment by mprevide** [comment]
Thank you :smile_cat:

**Comment by larshesel** [comment]
I suppose we can close this for now.
