### ISSUE TITLE
Building VerneMQ in macOS Catalina

### ISSUE THREAD

**Issue by thales-gaddini** [vernemq/vernemq#1391]
Hi there, mac user here.

### Environment

- VerneMQ Version: from master
- OS: macOS Catalina version 10.15.1
- Erlang/OTP version (if building from source): 22.1.8

### Expected behavior

Being able to follow the [tutorial](https://github.com/vernemq/vernemq/wiki/Building-VerneMQ-on-OS-X) on how to build on OS-X and build VerneMQ.

### Actual behaviour

It is not possible to install the Xcode CLT (Command Line Tools) 9.4.1 on Catalina so I don't know how to get around the issues compiling the leveldb package.

```bash
.
.
.
1 warning and 1 error generated.
cc  -I /Users/thales.biancalana/Desktop/vernemq/_build/default/lib/eleveldb/c_src/system/include -I. -I./include -mmacosx-version-min=10.8 -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -DSNAPPY  -O2 -g -DNDEBUG     -fPIC -MM -E -MT db/c.d -MT db/c.o -MF db/c.d db/c.cc
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from db/c.cc:9:
In file included from ./include/leveldb/cache.h:22:
./include/leveldb/slice.h:21:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
cc  -I /Users/thales.biancalana/Desktop/vernemq/_build/default/lib/eleveldb/c_src/system/include -I. -I./include -mmacosx-version-min=10.8 -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -DSNAPPY  -O2 -g -DNDEBUG     -fPIC -MM -E -MT db/builder.d -MT db/builder.o -MF db/builder.d db/builder.cc
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from db/builder.cc:8:
In file included from ./db/builder.h:8:
./include/leveldb/status.h:16:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
g++  -I /Users/thales.biancalana/Desktop/vernemq/_build/default/lib/eleveldb/c_src/system/include -I. -I./include -mmacosx-version-min=10.8 -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -DSNAPPY  -O2 -g -DNDEBUG     -fPIC -c db/builder.cc -o db/builder.o
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from db/builder.cc:8:
In file included from ./db/builder.h:8:
./include/leveldb/status.h:16:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
make[1]: *** [db/builder.o] Error 1
```

**Comment by namjitharavind** [comment]
Same issue for me. Not possible to install Xcode CLT older version(9.4.1) without Software Manufacturer Help.

**Comment by ioolkos** [comment]
@thales-gaddini @namjitharavind thanks for opening the issue. 

We can't do much more than wait for Mac hackers to kindly look into this. In any case, it seems strange as this is just about the path to stdlibc++, so potentially an easy fix?

**Comment by thales-gaddini** [comment]
I've been looking at some proposed solutions for compiling in Catalina but I wasn't able to make it work yet (I'm not a C++ guy):
- https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15
- https://stackoverflow.com/questions/50783479/where-to-put-things-cflags-or-cxxflags-on-makefile
- https://github.com/pandas-dev/pandas/issues/23424
- https://github.com/pysathq/pysat/issues/7

For now I'll use the docker version, but I'll keep trying to compile it. Can I leave the issue open?

**Comment by codeadict** [comment]
I'm planning to upgrade to Catalina next week, so may be able to find a fix if nobody has by them.

**Comment by codeadict** [comment]
Some good stuff towards a fix on https://github.com/vernemq/eleveldb/pull/5

**Comment by anthonymeneghini** [comment]
I'm not an expert but after launching the build command:

`make rel`

I get the following error:

> ...
> ... (omitted for brevity)
> ...
> ===> Compiling c_src/eleveldb.cc
> ===> Compiling c_src/refobjects.cc
> ===> Compiling c_src/threading.cc
> ===> Compiling c_src/workitems.cc
> ===> Linking /Users/ameneghini/vernemq/_build/default/lib/eleveldb/priv/eleveldb.so
> make: *** [rel] Error 1

After that I download eleveldb from [repository](https://github.com/basho/eleveldb/archive/refs/tags/riak_kv-3.0.0.zip)  unzipped it and replaced it with the contents in the vernemq/_build/default/lib/eleveldb folder.

launched the `make rel` command again and the vernemq binary was successfully created 👍 


Just as a side note. I installed the latest version of openssl using homebrew:

**_brew update
brew install openssl_**


Make sure you export the right PATH in .zshrc  (For example):

**_export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"_**

Good luck

**Comment by bopbi** [comment]
for latest guide on how to install mac on m1

https://gist.github.com/bopbi/aded8534762e728ec9d0e7b25ddd583c
