### ISSUE TITLE
webhooks auth_on_subscribe  on_subscribe has bug?

### ISSUE THREAD

**Issue by njfanxun** [vernemq/vernemq#1394]
when i use webhooks auth_on_subscribe on_subscribe 
if auth_on_subscribe response {"result": "next"} not trigger on_subscribe
if auth_on_subscribe response {"result": { "error": "some error message" }},but sub-client is also connect to vernemq? how can i disconnect this sub-client?

**Comment by dergraf** [comment]
Hello, thank you for reaching out. This isn't a bug, this is by definition, see: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718068

VerneMQ doesn't disconnect the client in case the subscription isn't authorized, but VerneMQ sends a SUBACK with the not-allowed return code(s). This is according to the MQTT specification.
