### ISSUE TITLE
How do you access broker functions in an Elixer plugin?

### ISSUE THREAD

**Issue by damouse** [vernemq/vernemq#1396]
I am using the elixer plugin detailed in [this guide](https://github.com/vernemq/vernemq/wiki/VerneMQ-plugins-in-Elixir). I would like to be able to publish messages and access some state stored in the broker from this plugin. I didn't think this was possible at first, but when looking at [the mqtt-gateway](https://github.com/netology-group/mqtt-gateway) plugin it appears that it has this capability:

```
subscribe(ClientId, Topics) ->
    wait_til_ready(),
    CAPSubscribe = vmq_config:get_env(allow_subscribe_during_netsplit, false),
    vmq_reg:subscribe(CAPSubscribe, {"", ClientId}, Topics),
    ok.
```

I'm referring to ` vmq_reg:subscribe` here. Is this possible in the elixer plugin? I'm not very familiar with elixer/erlang, so there might be a simple way to do this I don't see.

**Comment by larshesel** [comment]
yes, you can call any Erlang function from Elixir see https://elixir-lang.org/crash-course.html#calling-functions. So calling `vmq_reg:subscribe(...)` would be `:vmq_reg.subscribe(...)`. Notice that the `vmq_reg:subscribe` function is internal and no guarantees are given that it might not change. There are also some older related issues about publishing messages from a plugin, see for example this one: https://github.com/vernemq/vernemq/issues/399

Hope this helps!

**Comment by damouse** [comment]
Thank you so much!
