### ISSUE TITLE
Activating an elixir plugin causes vmq-admin to fail to reach the broker

### ISSUE THREAD

**Issue by damouse** [vernemq/vernemq#1398]
### Environment

- VerneMQ Version: 1.10.1
- OS: Ubuntu 18.04
- Erlang/OTP version (if building from source): 1.6.6

### Expected behavior

vmq-admin should be able to reach a single broker in a docker container when an elixir plugin is loaded. 

```
vernemq@a306dd788719:~$ vmq-admin cluster show 
+------------------+-------+
|       Node       |Running|
+------------------+-------+
|VerneMQ@172.17.0.2| true  |
+------------------+-------+
```

### Actual behaviour

Commenting out the elixir plugin in vernemq.conf allows vmq-admin to work. Commenting it in causes it to stop responding with the error 

```
vernemq@7468b69d5d37:~$ vmq-admin
Node 'VerneMQ@172.17.0.2' not responding to pings.
```

And on the broker this prints repeatedly:

```
23:27:58.182 [error] Error in process #PID<0.448.0> on node :"VerneMQ@172.17.0.2" with exit value:
{:function_clause, [{:dist_util, :convert_old_hsdata, [{:hs_data, #PID<0.60.0>, :undefined, :"VerneMQ@172.17.0.2", #Port<0.19>, #PID<0.449.0>, 0, [], :undefined, :undefined, :undefined, &:inet_tcp.send/2, &:inet_tcp.recv/3, #Function<0.56818488/1 in :inet_tcp_dist.do_accept/7>, #Function<1.56818488/1 in :inet_tcp_dist.do_accept/7>, #Function<2.56818488/1 in :inet_tcp_dist.do_accept/7>, #Function<3.56818488/2 in :inet_tcp_dist.do_accept/7>, #Function<4.56818488/1 in :inet_tcp_dist.do_accept/7>, &:inet_tcp_dist.getstat/1, :normal, &:inet_tcp_dist.setopts/2, &:inet_tcp_dist.getopts/2, :undefined, :undefined, :undefined, :undefined}], [file: 'dist_util.erl', line: 339]}, {:dist_util, :handshake_other_started, 1, [file: 'dist_util.erl', line: 149]}]}
```

### Detail

I'm using a dockerized broker with a `vernemq.conf.local` and `###IPADDRESS###` placeholders. The plugin is the sample version of an elixier plugin provided [here](https://github.com/trarbr/vernemq_elixir_plugin) and has not been modified. A sample of this configuration can be found with instructions on reproducing [here](https://github.com/damouse/vernemq-issues).

In short, I'm building a broker with the unmodified elixir plugin and starting it in a docker container. I then `docker exec` into the container and run `vmq-admin`. When the elixir plugin is loaded, this fails. When it is not loaded, it succeeds. I have tried changing many of the existing configuration in vernemq.conf without success. It happens for me every time. 

Here is the top of the conf file being loaded when `vmq-admin` works:

```
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109

listener.tcp.default = ###IPADDRESS###:1883
listener.ws.default = ###IPADDRESS###:8080
listener.vmq.clustering = ###IPADDRESS###:44053
listener.http.metrics = ###IPADDRESS###:8888
listener.http.default = ###IPADDRESS###:8888

nodename = VerneMQ@###IPADDRESS###

# plugins.vernemq_elixir_plugin = on
# plugins.vernemq_elixir_plugin.path = /vernemq_elixir_plugin
```

It doesn't work when the last two lines are commented in. Occasional errors print even if vmq-admin is not run against it-- the tcp error prints pasted above print every 30 seconds or so.

I did not make this issue in the vernemq-docker repo because I assume I'm doing something wrong in the configuration-- does something in config need to change when the elixir plugin is loaded?

**Comment by larshesel** [comment]
Hi, I've never seen this error before. Could it be the Erlang version used to compile the plugin isn't compatible with version VerneMQ is running?

**Comment by damouse** [comment]
I tried other versions of erlang to compile the plugin, but most of the time I got an error like "built for a version of OTP other than X" or something like it. Note that the plugin works-- I'm able to make authorization decisions there and the broker seems happy with it. I would expect it to fail completely if there was a version mismatch, as I see when I build for very different runtime versions, but I don't have a lot of erlang experience, so I don't know.

**Comment by damouse** [comment]
I experimented with one of the sample plugins and made a little progress. I build elixir 1.6.6 from source, then set `elixir: "~> 1.1",` in `mix.exs`, I am able to load the plugin after the broker has started with:

```
vmq-admin plugin enable --name=elixir --path=/usr/local/lib/elixir
vmq-admin plugin enable --name vernemq_elixir_plugin --path /vernemq_elixir_plugin/_build/prod
```

But it still doesn't work from the conf file with 

```
plugins.vernemq_elixir_plugin = on
plugins.vernemq_elixir_plugin.path = /vernemq_elixir_plugin
```

From this I assume that there's something wrong with the version of elixir I'm using to build:

```
# Elixir
RUN set -xe \
  && ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/archive/$1.6.6.tar.gz" \
  && ELIXIR_DOWNLOAD_SHA256="74507b0646bf485ee3af0e7727e3fdab7123f1c5ecf2187a52a928ad60f93831" \
  && curl -fSL -o elixir-src.tar.gz $ELIXIR_DOWNLOAD_URL \
  && echo "$ELIXIR_DOWNLOAD_SHA256  elixir-src.tar.gz" | sha256sum -c - \
  && mkdir -p /usr/local/src/elixir \
  && tar -xzC /usr/local/src/elixir --strip-components=1 -f elixir-src.tar.gz \
  && rm elixir-src.tar.gz \
  && cd /usr/local/src/elixir \
  && make install clean
```

**Comment by damouse** [comment]
It was a bad/wrong elixir version. 1.8.0 seems to work, though I found that out by trial and error. I am an erlang/elixir newbie, but I'm not sure what the right way to determine this is.
