### ISSUE TITLE
vernemq can not restart

### ISSUE THREAD

**Issue by dsboo** [vernemq/vernemq#1403]
### Environment

- VerneMQ Version: 1.5.0-1
- OS: centos 7.4
- Erlang/OTP version (if building from source): use rpm(vernemq-1.5.0-1.el7.centos.x86_64.rpm)
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: cluster is 3

   cluster(3node) -- bridge -- cluster(3node)

### Expected behavior

vernemq restart normally.

### Actual behaviour

vernemq can not restart. (systemctl restart vernemq)

when i restarted vernemq, i got below error.
i can not undestant what happen.
just 2minute ago, vernemq restarted normally.

what's mean this log?

thanks.

error.log

> 2019-12-21 13:06:02.775 [error] <0.384.0> Supervisor vmq_bridge_sup had child {vmq_bridge,"111.209.218.26",80} started with vmq_bridge:start_link(tcp, "111.209.218.26", 80, {vmq_reg,direct_plugin_exports,[vmq_bridge]}, [{cleansession,true},{client_id,"aaaa.br0"},{keepalive_interval,10},{restart_timeout,5},{username,...},...]) at <0.448.0> exit with reason {shutdown,{gen_server,call,[vmq_cluster_node_sup,which_children,infinity]}} in context child_terminated
> 2019-12-21 13:06:05.205 [error] <0.658.0> CRASH REPORT Process <0.658.0> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_config_cache, ignore_db_config) in vmq_config:get_env/3 line 79
> 2019-12-21 13:06:05.205 [error] <0.658.0> Ranch listener {{111,104,166,44},80} terminated with reason: badarg

console.log

> 2019-12-21 13:06:02.774 [info] <0.652.0> Administrative stop
> 2019-12-21 13:06:02.775 [error] <0.384.0> Supervisor vmq_bridge_sup had child {vmq_bridge,"111.209.218.26",80} started with vmq_bridge:start_link(tcp, "111.209.218.26", 80, {vmq_reg,direct_plugin_exports,[vmq_bridge]}, [{cleansession,true},{client_id,"aaaa.br0"},{keepalive_interval,10},{restart_timeout,5},{username,...},...]) at <0.448.0> exit with reason {shutdown,{gen_server,call,[vmq_cluster_node_sup,which_children,infinity]}} in context child_terminated
> 2019-12-21 13:06:05.205 [error] <0.658.0> CRASH REPORT Process <0.658.0> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_config_cache, ignore_db_config) in vmq_config:get_env/3 line 79
> 2019-12-21 13:06:05.205 [error] <0.658.0> Ranch listener {{111,104,166,44},80} terminated with reason: badarg

crash.log

> 2019-12-21 13:06:02 =SUPERVISOR REPORT====
>      Supervisor: {local,vmq_bridge_sup}
>      Context:    child_terminated
>      Reason:     {shutdown,{gen_server,call,[vmq_cluster_node_sup,which_children,infinity]}}
>      Offender:   [{pid,<0.448.0>},{id,{vmq_bridge,"111.209.218.26",80}},{mfargs,{vmq_bridge,start_link,[tcp,"111.209.218.26",80,{vmq_reg,direct_plugin_exports,[vmq_bridge]},[{cleansession,true},{client_id,"aaaaa.br0"},{keepalive_interval,10},{restart_timeout,5},{username,"app"},{password,"app"},{try_private,false},{topics,[{"topic/#",in,0,[],[]}]}]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
> 
> 2019-12-21 13:06:05 =CRASH REPORT====
>   crasher:
>     initial call: vmq_ranch:init/5
>     pid: <0.658.0>
>     registered_name: []
>     exception error: bad argument: [{ets,lookup,[vmq_config_cache,ignore_db_config],[]},{vmq_config,get_env,3,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_config.erl"},{line,79}]},{vmq_mqtt_fsm,init,2,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,94}]},{vmq_ranch,init,5,[{file,"/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,74}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
>     ancestors: [<0.396.0>,<0.395.0>,ranch_sup,<0.63.0>]
>     messages: []
>     links: [<0.396.0>,#Port<0.10414>]
>     dictionary: [{rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,type => exsplus,uniform => #Fun<rand.9.41921595>,uniform_n => #Fun<rand.10.41921595>},[284364952784958286|76263553436772953]}}]
>     trap_exit: false
>     status: running
>     heap_size: 987
>     stack_size: 27
>     reductions: 223
>   neighbours:
> 2019-12-21 13:06:05 =ERROR REPORT====
> Ranch listener {{111,104,166,44},80} had connection process started with vmq_ranch:start_link/4 at <0.658.0> exit with reason: badarg

**Comment by ioolkos** [comment]
Could you resolve this?
Seems the bridge is causing trouble here while starting, but I haven't really been able to look into it.
Also, possibly some bridge bugs would have been fixed since version 1.5.

**Comment by larshesel** [comment]
>  Also, possibly some bridge bugs would have been fixed since version 1.5.

I've confident quite a lot of bridge bugs were fixed since VerneMQ 1.5.0 ;)

**Comment by ioolkos** [comment]
@dsboo so do you have plans to upgrade? (which is basically what we'd recommend here anyway)

**Comment by dsboo** [comment]
@ioolkos yeah we consider upgrade. thanks.

**Comment by larshesel** [comment]
ok - closing for now.
