### ISSUE TITLE
publish_acl and subscribe_acl in vmq_acl_auth collection in mongodb are not invoked

### ISSUE THREAD

**Issue by SriDurga18** [vernemq/vernemq#1406]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behavior

Clients should able to publish and subscribe to the topics as per the acl's in vmq_acl_auth collection

### Actual behaviour
I'm using DB authentication.
So I kept 
-  vmq_diversity on and
-  vmq_diversity.script1.file ./share/lua/script.lua (custom script)

I want to authenticate with certificates so I added below lines:
- ssl.require_certificate on
- ssl.use_identity_as_username on

I'm using mongodb collection "vmq_acl_auth" which has the following:
{
        "_id" : ObjectId("5e01f6297163eea0adadd25a"),
        "mountpoint" : "",
        "client_id" : "client1",
        "username" : "12345abcde",
        "publish_acl" : [
                {
                        "pattern" : "device/+"
                },
                {
                        "pattern" : "device/data/+"
                }
        ],
        "subscribe_acl" : [
                {
                        "pattern" : "device/+"
                }
        ]
}

**Note**: I didn't include password because I did't find any necessity of it because I'm using certificates The common name in the certificate is deviceID. As i kept "ssl.use_identity_as_username on" . This implies, username in db and Common name from the certificate (reg.username) is same. I'm checking for it in the auth_on_register hook. 

For each client there is a publish_acl and subscibe_acl.

Here I've some questions:
When i try to publish on some other topic which is not in the publish_acl it allowed. This shouldn't happen.

Ex: For "client1", topic "device/+" and "device/data/+" should be allowed to publish.
  But it allowed "hello/world" topic also.

My lua script is below:
require "auth/auth_commons"
function auth_on_register(reg)
    if reg.username ~= nil then
        print("in auth register")
        doc = mongodb.find_one(pool, "vmq_acl_auth", 
                                {client_id = reg.client_id})
        if doc ~= false then
            for k,v in pairs(doc.publish_acl) do
                print(k,v)
            end
            for k,v in pairs(doc.subscribe_acl) do
                print(k,v)
            end
            return true
        end
    end
    return false
end
function auth_on_publish(pub)
    if pub.username ~= nil then
        print("in auth publish")
        return true
    end
    return false
end
function auth_on_subscribe(sub) --change to sub
    if sub.username ~= nil then
        print("in auth subscribe") 
        return true
    end
    return false
end
pool = "auth_mongodb"
config = {
    pool_id = pool
}

mongodb.ensure_pool(config)
hooks = {
    auth_on_register = auth_on_register,
    auth_on_publish = auth_on_publish,
    auth_on_subscribe = auth_on_subscribe,
    on_unsubscribe = on_unsubscribe,
    on_client_gone = on_client_gone,
    on_client_offline = on_client_offline,

    auth_on_register_m5 = auth_on_register_m5,
    auth_on_publish_m5 = auth_on_publish_m5,
    auth_on_subscribe_m5 = auth_on_subscribe_m5,
} 

Can you suggest any way how will "publish_acl" and "subscribe_acl" will be checked when any client connection happens? 

Sorry for the long question.

**Comment by ioolkos** [comment]
Hi @SriDurga18 have you turned off the `vmq_acl` plugin? plugins work in a chain, if you allow anything there, it will pass.

**Comment by SriDurga18** [comment]
Hi ioolkos,

Thanks for the reply!
Here is my vernemq conf:
ALLOW_ANONYMOUS off
vmq_acl off
vmq_passwd off
vmq_diversity on
ssl.require_certificate on
ssl.use_identity_as_username on
auth_mongodb.enabled on and other mongodb related host, port, database

**Comment by SriDurga18** [comment]
How will the vmq_acl_auth collection be invoked? 
I specified mongodb host, port, database name but I have a doubt here, how will vernemq know to invoke the "vmq_acl_auth" collection and check for the allowable pub/sub topics to the respective clients? I inserted a document in the mongodb in the following way:
{
    "_id" : ObjectId("5e01f6297163eea0adadd25a"),
   "mountpoint" : "",
   "client_id" : "client1",
   "username" : "12345abcde",
   "publish_acl" : [
   {
            "pattern" : "device/+"
   },
  {
           "pattern" : "device/data/+"
  }
 ],
"subscribe_acl" : [
 {
            "pattern" : "device/+"
 }
]
}

**Comment by ioolkos** [comment]
@SriDurga18 did you make this work? Closing the issue for now.
