### ISSUE TITLE
Connect with wrong password return [WinError 10054]

### ISSUE THREAD

**Issue by Zack0421** [vernemq/vernemq#1409]
**Environment**
VerneMQ Version:1.10.1
OS: centos7

**Expected behavior**
hello!
I test the situation when connect with wrong password.
Use Python "paho.mqtt.client" modules like this:
```
import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, rc):
    #The value of rc indicates success or not:
    #        0: Connection successful
    #        1: Connection refused - incorrect protocol version
    #        2: Connection refused - invalid client identifier
    #        3: Connection refused - server unavailable
    #        4: Connection refused - bad username or password
    #        5: Connection refused - not authorised
    #        6-255: Currently unused.
    print("rc="+rc)

if __name__ == '__main__':
    client = mqtt.Client()
    client.username_pw_set('name', 'wrong password')
    client.on_connect = on_connect
    client.connect("172.16.179.120", 1883, 60)
    client.loop_forever()
```
Code should be printed "rc=5"

**Actual behaviour**
Actually，code dosen't print rc. It return error :[WinError 10054]
console.log print:
```
2020-01-09 14:01:31.618 [warning] <0.2464.0>@vmq_mqtt_fsm:check_user:567 can't authenticate client {[],<<"anon-Wr34/8iK4dtiDAlWu9sYvxKJsCs=">>} from 172.16.80.70:57079 due to invalid_credentials
```
wireshark show that vernemq rst my client:
![image](https://user-images.githubusercontent.com/59223322/72050810-fd3cf780-32fc-11ea-8054-1db0ecfb99e0.png)

When i used correct password,it print "rc=0"
I used "emqtt" to test with the same Python code,it printed ”rc=5“
wireshark show:
![image](https://user-images.githubusercontent.com/59223322/72050940-43925680-32fd-11ea-867d-6975a931a653.png)

Would you like to tell why vernemq rst my client？
Did i miss some configures？
thank you!

**Comment by ioolkos** [comment]
@Zack0421 thanks for opening the issue!
You are probably correct in the sense that for a wrong password we should not respond with RC 4 but with RC 5.
Spec says RC 4 is for "The data in the user name or password is malformed".
Which is not the same as a wrong password.
I'll investigate further.

The result is the same, of course. The server has to disconnect the client.

**Comment by Zack0421** [comment]
Hi~ @ioolkos thanks for the reply!
Maybe I didn't make it clear。
I agree with the server has to disconnect the client，but TCP should use "Fin" to  disconnect the client not "RST":
![image](https://user-images.githubusercontent.com/59223322/72119281-e34bf500-338e-11ea-8608-28cb0536048a.png)

Use "RST" to  disconnect is too faster that client cannot get the Connect ACK.

**Comment by ioolkos** [comment]
Ok. From the console.log error and the wireshark output, looking at the destination port, it doesn't seem to be about the same connection. Maybe this is relevant, maybe not.
My question is whether this could be a client connecting at the same time with the same ClientID. 
(maybe via a reconnect that the Paho client does?)

**Comment by Zack0421** [comment]
thanks for the reply!
Sorry~There was a problem with the console.log I provided.
I tried again and made sure the destination port is the same.The ClientID used for the connection is unique.
![image](https://user-images.githubusercontent.com/59223322/72229520-379ee100-35ea-11ea-88ba-6ca5f5f7d073.png)
![image](https://user-images.githubusercontent.com/59223322/72229508-2b1a8880-35ea-11ea-8bda-4e9276e5ba4f.png)

**Comment by ioolkos** [comment]
I think this is related to the `linger` socket settings. Seems we use `{linger, {true, 0}}`
https://github.com/vernemq/vernemq/blob/ffa55369cd881b13f0ccbd62be5df942722c2d2e/apps/vmq_server/src/vmq_server.app.src#L94

This protects better against TIME_WAITs, so I'm not sure we should change this.

**Comment by Zack0421** [comment]
If i want modify the socket settings, do I need to rebuild the VerneMQ?
l tried to modify the `linger` in `$VERNEMQ\usr\lib64\vernemq\lib\vmq_server-1.10.1\ebin\vmq_server.app` like `{linger, {true, 5}}`.Seems not work. 
Did I modify the wrong place？

**Comment by ioolkos** [comment]
This should work without recompiling if you do the following.

Create an `advanced.config` file in the same directory where your `vernemq.conf` file is. (for me this is in /etc/vernemq/)

Add this config (or similar) to the file:
```
[{vmq_server, [
          {tcp_listen_options,
          [{nodelay, true},
           {linger, {true, 5}},
          {send_timeout, 30000},
          {exit_on_close, true}
          ]}]}].
```
Finally, restart VerneMQ

**Comment by Zack0421** [comment]
It worked，I can get the back RC.
Thanks for your support！
