### ISSUE TITLE
Vernemq Disk Usuage increases without any upper bound.

### ISSUE THREAD

**Issue by natrajT** [vernemq/vernemq#1410]
/opt/vernemq/data/meta/trees# du -sh *
1.3M	049960.log
4.0K	CURRENT
0	LOCK
8.4M	LOG
5.1M	MANIFEST-000002
17M	sst_0
54M	sst_1
182M	sst_2
4.0G	sst_3
38G	sst_4
4.0K	sst_5
4.0K	sst_6

Vernemq disk usuage is increasing day by day without any limit.

Cluster size : 5
Connections to each node in cluster :35k
[Metrics.txt](https://github.com/vernemq/vernemq/files/4053240/Metrics.txt)
[Vernemq.txt](https://github.com/vernemq/vernemq/files/4053246/Vernemq.txt)

**Comment by natrajT** [comment]
Got the below text from LevelDB doc. Should we run compaction?
Once the SSTable is on disk, it is immutable, hence updates and deletes can’t touch the data. Instead, a more recent value is simply stored in MemTable in case of update, and a “tombstone” record is appended for deletes. Because we check the indexes in sequence, future reads will find the updated or the tombstone record without ever reaching the older values! Finally, having hundreds of on-disk SSTables is also not a great idea, hence periodically we will run a process to merge the on-disk SSTables, at which time the update and delete records will overwrite and remove the older data.

**Comment by ioolkos** [comment]
which VerneMQ release are you using?

**Comment by natrajT** [comment]
> which VerneMQ release are you using?

/opt/vernemq/bin/vernemq version
1.10.0

**Comment by ioolkos** [comment]
Can you run `sudo vernemq config effective` and show us?
Can you tell us more about what you are doing? how are you doing the subscriptions? 
what have you done historically? how long have you run release 1.10, and have you updated with a pre-existing store etc.

**Comment by natrajT** [comment]
[Effective_config.txt](https://github.com/vernemq/vernemq/files/4053556/Effective_config.txt)

Can you tell us more about what you are doing? 
We have connected the IOT devices. Which publishes the sensor details to MQTT.

-->how are you doing the subscriptions? 
Didnt get. We connect paho java client . 80 percent traffic will be to this topic /userid/device_id.
-->what have you done historically?
Modified one config allow_register_during_netsplit  to  on.  
-->how long have you run release 1.10?
1 month.
-->Publish
We publish messages with QOS=1 and retain =false.

**Comment by ioolkos** [comment]
Do you have any random, single-use parts in ClientIDs or topics?
Do you collect metrics with Prometheus? was this just a linear increase? did something "happen" at some point?
Do you have any further hypothesis?

**Comment by natrajT** [comment]
Do you have any random, single-use parts in ClientIDs or topics?
Client-ids is UUID. topics contains 24 character randomalphanumeric "v1/devices/<24character alphanumeric string>".
Do you collect metrics with Prometheus? was this just a linear increase? did something "happen" at some point?
Linear increase.If we restart disk size decreases and then increases slowly
 
![image](https://user-images.githubusercontent.com/11175886/72259362-44492680-3636-11ea-848a-2eeb878b88f7.png)

**Comment by ioolkos** [comment]
- But you do always connect Clients with the same ID? (you do not generate new UUIDs for every session?)
- By how much does disk size decrease by rebooting?

**Comment by natrajT** [comment]
> * But you do always connect Clients with the same ID? (you do not generate new UUIDs for every session?)
Each client will have fixed client-id. If will connect with same cleint-id. 
> * By how much does disk size decrease by rebooting?
![image](https://user-images.githubusercontent.com/11175886/72259793-55466780-3637-11ea-8413-61b0e411d9d6.png). drops down to 10GB and then increases to 45 GB continues

**Comment by natrajT** [comment]
[error] <0.16137.98>@vmq_queue:wait_for_offline:353 got unknown sync event in wait_for_offline state {cleanup,session_taken_over}

We get the above error whenever we try to restart the vernemq.After repeated restarts it stops. May be becasue we turned on this "allow_register_during_netsplit". Just asssuming

**Comment by ioolkos** [comment]
Ok, 30% random throwaway ClientIDs is still a lot. How many sessions do you create per such user per day?
I think this must be related (although doesn't really explain the decrease on reboot)

**Comment by dergraf** [comment]
The decrease on the reboot could be explained because of the hash-tree reset (leveldb deletion and rebuild) .

So my current guess is the plumtree tombstones.

Can you attach to the VerneMQ shell with `vernemq attach` and run the following Erlang statement?

```erlang
plumtree_metadata:fold(fun({_, ['$deleted']}, {Objs,Tombst}) -> {Objs, Tombst + 1}; (_, {Objs, Tombst}) -> {Objs + 1, Tombst} end, {0,0}, {vmq, subscriber}).
```
(don't forget the dot at the end of the statement)

This will return you a tuple of similar to `{10, 2}` describing that you have 10 objects and 2 tombstones stored.

This will do full scan of all the data, which could take some time. It will likely occupy a single CPU core doing this, especially if you have a lot of entries.

**Comment by natrajT** [comment]
> Ok, 30% random throwaway ClientIDs is still a lot. How many sessions do you create per such user per day?
Every time he install's app it will create one client_id. This client-id will be used untill he unistall app from his device.So Only initially when we deploy to prod it will be random. After that we will reuse the client-id. 
> I think this must be related (although doesn't really explain the decrease on reboot)

**Comment by natrajT** [comment]
> This will do full scan of all the data, which could take some time. It will likely occupy a single CPU core doing this, especially if you have a lot of entries.

{214446,79634} this is the response i got.

**Comment by ioolkos** [comment]
Overall, this is a case where the switch to `metadata_plugin = vmq_swc` is advised.
Note that this needs to be done from scratch, that is, it will not convert existing broker state.

Anyway, 80k tombstones here and growing.
An additional question: is the disk growth correlated with the number of subscriptions? that is, do the clients create subscriptions over that time span (versus, they pretty much create all their subscriptions after a broker reboot, and only then disk space keeps growing).

**Comment by natrajT** [comment]
![image](https://user-images.githubusercontent.com/11175886/72340060-7e293400-36ed-11ea-9a45-13eb4bff6c5f.png)

When we reboot broker, devices starts re-connecting to broker. So each device will subscribe to one topic.Devices create all their subscriptions after a broker reboot. But disk space keeps on growing

**Comment by ioolkos** [comment]
There's a delete_threshold setting for LeveldB within VerneMQ (to trigger LevelDB compaction) which has historically been kept at 1000 tombstones. 
This seemed to work most of the time, so there is not much experience changing or disabling that setting.

Can you share a literal ClientID, and topic, just to see how they look. If not possible publicly, let me know, or send per e-mail please.

**Comment by cdro-idirect** [comment]
Hi, we have basically the same problem. We are running 2 vernemq instances as a cluster and there is currently only one client connected, which publishes between 150 and 250 messages per second.

![2020-02-03-164542_1158x456_scrot](https://user-images.githubusercontent.com/60513137/73668846-c57c6200-46a6-11ea-8fe9-64b32136340e.png)

Each node has a mqtt bridge configured (to another broker that doesn't belong to this cluster).
After around 3 days the disk is just full, with the /var/lib/vernemq/meta directory being the culprit here:

40K	000247.log
4.0K	CURRENT
0	LOCK
48K	LOG
28K	MANIFEST-000002
33M	sst_0
106M	sst_1
358M	sst_2
937M	sst_3
4.0K	sst_4
4.0K	sst_5
4.0K	sst_6

![2020-02-03-164348_2521x1097_scrot](https://user-images.githubusercontent.com/60513137/73668637-6d456000-46a6-11ea-8998-76b4188a470b.png)
Note that the last 20% get filled within 30 seconds.

A snippet of console.log and effective config attached:
[config-effective.txt](https://github.com/vernemq/vernemq/files/4148810/config-effective.txt)
[console.log](https://github.com/vernemq/vernemq/files/4148811/console.log)

**Comment by ioolkos** [comment]
@cdro-idirect  
Can you run the same test with `metadata_plugin = vmq_swc`?
Can you tell me specifics on how you publish? (what are the details of the MQTT publish command?)

**Comment by dskls** [comment]
Hi,
We faced this issue today morning ! is this issue fixed ?

**Comment by natrajT** [comment]
no. But the disk space decreases after 2-3 days .Server disk space is 120 GB. Previuosly it used to use 60GB slowly it reduce to 15GB.   
![image](https://user-images.githubusercontent.com/11175886/73718285-10978300-4742-11ea-9756-9e53ccc3b61c.png)
i didnt try with metadata_plugin = vmq_swc.

**Comment by dskls** [comment]
> Disk space decreases after 2-3 days .Server disk space capcity is 120 GB. Previuosly it used to use 60GB slowly it reduce to 15GB.

Ok. but for us, all 5 nodes went 100% of disk space and VerneMQ stopped. we remove the .sst files and restarted.

**Comment by dskls** [comment]
@natrajT, 
would like to discuss with you, please dm me : dinesh.jeph@gmail.com
Thanks

**Comment by dskls** [comment]
/var/lib/vernemq/meta/trees$ du -sh *

13M	072442.log
13M	072445.log
13M	072448.log
13M	072451.log
13M	072453.log
13M	072456.log
12M	072464.log
4.0K	CURRENT
0	         LOCK
13M	        LOG
8.0M	MANIFEST-000002
142M	sst_0
221M	sst_1
686M	sst_2
4.8G	sst_3
82G	        sst_4
6.6G        sst_5
4.0K	       sst_6

Cluster size : 5
Connections to each node in cluster :4k

[effective_config.txt](https://github.com/vernemq/vernemq/files/4152053/effective_config.txt)

**Comment by codeadict** [comment]
This seems to be an issue in leveldb too https://github.com/google/leveldb/issues/603, there are many reports in several projects about it

**Comment by natrajT** [comment]
> @cdro-idirect
> Can you run the same test with `metadata_plugin = vmq_swc`?
There is no clear document how to migrate to vmq_swc .
@ioolkos 
How do we switch to metadata_plugin = vmq_swc.
Are the below steps correct:
1)  Stop the entire cluster
2) Change the metadata_plugin = vmq_swc in entire cluster.
3) Delete  the data folders in all the servers.
4) Restart the service 

Question:
1) Can we change this config 1 server at a time or on all servers at same time?
2) should we delete the data folders?

**Comment by ioolkos** [comment]
@natrajT switching to SWC metadata exchange protocol is not backward compatible. Particularly, you cannot run a mixed cluster (where there are nodes configured for plumtree mixed with SWC ones).

In general, your procedure is correct, but I'd be conservative about the data folders. (I'd back them up). SWC will generate its own "swc_meta" folders, so subscriber state will not mix. 

Safest & recommended way to test this is with a new test cluster, obviously, instead of "updating" production cluster.

**Comment by natrajT** [comment]
> Safest & recommended way to test this is with a new test cluster, obviously, instead of "updating" production cluster.

thank you

**Comment by ioolkos** [comment]
@cdro-idirect quick test you could do: if your publisher does not use the retain feature for your messages, is the situation the same?

**Comment by cdro-idirect** [comment]
@ioolkos I'm currently testing with vmq_swc (since yesterday). Currently the directory size is around 279MB. The retain flag for messages is not set.
Our topics look something like that /abc/8/494451/xyz/data
It took around 3 days for the issue to appear, so I will follow up with the results later.

**Comment by ioolkos** [comment]
@cdro-idirect ok, cool.
- what is your per node disk size?
- are there randomly generated parts in the topics?

**Comment by cdro-idirect** [comment]
@ioolkos 
* currently vernemq is installed on the 4GB rootfs (in a VM).
* there is nothing really random generated in the topics, if you take my previos example:
/abc/8/494451/xyz/data
 abc is like a static main topic
 the numbers are ids that identify more or less a region and a instance
 the letters behind the numbers are indentifiers for what kind of information is provided
So all in all a limited number of possible topcis.

**Comment by cdro-idirect** [comment]
So far it seems disk usage has levelled out for my setup. It's running since Tuesday with vmq_swc and directory size fluctuated between 160MB and 280MB, here are the disk graphs for my 2 nodes (vernemq uses / partition here):
![Screenshot_2020-02-07 Host metrics - Grafana](https://user-images.githubusercontent.com/60513137/74012624-fa303800-498a-11ea-81df-0557b29efa41.png)
![Screenshot_2020-02-07 Host metrics - Grafana(1)](https://user-images.githubusercontent.com/60513137/74012634-ff8d8280-498a-11ea-8341-a73a785246c3.png)

I guess it's ok for me to keep using vmq_swc.

@ioolkos Do you maybe know how the size of this directory scales, if I add more clients and topics, will this get significantly bigger? Is there any "maximum size" or is there no upper limit in theory? Would be nice to know how I should scale the disks of my VMs.

**Comment by ioolkos** [comment]
@cdro-idirect is the test still running ok for you?

**Comment by cdro-idirect** [comment]
@ioolkos Still looking good. vmq_swc seems to work well for me.

> @ioolkos Do you maybe know how the size of this directory scales, if I add more clients and topics, will this get significantly bigger? Is there any "maximum size" or is there no upper limit in theory? Would be nice to know how I should scale the disks of my VMs.

Is this somethong you can answer?

**Comment by natrajT** [comment]
@ioolkos SWC fixes the disk issue. Modified it 1 month back on prod and monitored. The disk usuage is very minimal.So closing this ticket

**Comment by natrajT** [comment]
Did anyone face issues when adding new node to already running cluster after switiching to "metadata_plugin = vmq_swc"

**Comment by ioolkos** [comment]
Can you provide more context? what did you do exactly? does the node start, or not? from where is the log snippet? which node is VerneMQ@10.0.2.118?

**Comment by natrajT** [comment]
Cluster size :6
Connections: 320000
Use case:
We tried to add one more node to cluster then the entire cluster is going down. We tried this 5 times. 
Use case 2:
Connection count :1000
Again try to add new node it brings the cluster down.
Use case 3: Delete the data folder in all the node. Add new node now. It works without any issues

**Comment by ioolkos** [comment]
Can you forward more extended logs on this (via e-mail)?

**Comment by natrajT** [comment]
sent to mail

**Comment by natrajT** [comment]
Hi ,
PFA crash.log.

Thanks,
Nataraj T

**Comment by ioolkos** [comment]
no attachment. please include your normal e-mail address, so that I can answer.

**Comment by natrajT** [comment]
natrajreddyis@gmail.com

**Comment by cypaul** [comment]
Hi guys, we've just hit the same issue. Two-node VerneMQ cluster, pretty much basic configuration. This is df of our vernemq/meta directory:

[root@cloud-2118 meta]# du -sh * 
282M    meta  
4,0K    peer_service  
16G    trees  
[root@cloud-2118 meta]# cd trees/ 
[root@cloud-2118 trees]# du -sh * 
4,0K    CURRENT 
0    LOCK 
5,3M    LOG 
6,7M    MANIFEST-000002 
1,2M    sst_0 
796K    sst_1 
206M    sst_2 
5,3G    sst_3 
10G    sst_4 
0    sst_5 
0    sst_6 
2,3M    031058.log 

Similarly to what @cdro-idirect posted, once the disk usage hit 80%, it skyrocketed real fast.

![du](https://user-images.githubusercontent.com/16902057/80755334-e5e67c00-8b30-11ea-9845-09c6acaa7573.png)

After reboot, we're down to 6% disk usage.

**Comment by sesky4** [comment]
@ioolkos Hi, I just hit the same issue.
In my understanding, the meta/ stores all the metadata like clientID, topic name... right?
I have a 2-node cluster, the cluster has been running for about 8 months.
Node 1 have a very big sst_4(39GB now), but  Node 2 is just 161MB.

My question is:
1. Is there any way to dump/export/see the content of those sst files? So it can helps me find out the reason.
2.If I have constant number of clientID, topic, will the size of meta/ keep constant?
3.Can I delete those unused metadata(maybe through vernemq attach?)

Thanks! :D

**Comment by ATAKing1023** [comment]
> @ioolkos
> Hi, I just hit the same issue.
> In my understanding, the meta/ stores all the metadata like clientID, topic name... right?
> I have a 2-node cluster, the cluster has been running for about 8 months.
> Node 1 have a very big sst_4(39GB now), but Node 2 is just 161MB.
> 
> version: 1.10.1
> 
> My question is:
> 
> ```
> 1. Is there any way to dump/export/see the content of those sst files? So it can helps me find out the reason.
> 
> 2.If I have constant number of clientID, topic, will the size of meta/ keep constant?
> 
> 3.Can I delete those unused metadata(maybe through vernemq attach?)
> ```
> 
> Thanks! :D

+1
