### ISSUE TITLE
econnrefused in gen_server:handle_common_reply/8 line 751

### ISSUE THREAD

**Issue by nachten** [vernemq/vernemq#1411]
### Environment

- VerneMQ Version: 1.10.1
- OS: macOS Mojave 10.14.6
- Erlang/OTP version (if building from source): Not applicable
- VerneMQ configuration (vernemq.conf) or the changes from the default

--env "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
--env "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off"
 --env "DOCKER_VERNEMQ_PLUGINS__VMQ_ACL=off"
 --env "DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=on"
 --env "DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD=off"
 --env "DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED=on"
 --env "DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST=localhost"
 --env "DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT=5432"
 --env "DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER=test"
 --env "DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD=test"
 --env "DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE=devices"
 --env "DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD=crypt"
 --env "DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE=off"
 --env "DOCKER_VERNEMQ_LISTENER__SSL__USE_IDENTITY_AS_USERNAME=off"
 --name "vernemq_test"
 -p "1883:1883"

- Cluster size/standalone: standalone
- PostgreSQL version: 11.5

### Expected behavior

- Please describe the expected behaviour.

VerneMQ docker instance running but keeps prompting the following log information:

14:23:29.894 [error] gen_server <0.932.0> terminated with reason: econnrefused
14:23:29.894 [warning] Could not connect to postgresql due to econnrefused
14:23:29.894 [error] CRASH REPORT Process <0.932.0> with 0 neighbours exited with reason: econnrefused in gen_server:handle_common_reply/8 line 751
14:23:29.895 [error] gen_server <0.931.0> terminated with reason: econnrefused
14:23:29.897 [error] CRASH REPORT Process <0.931.0> with 0 neighbours exited with reason: econnrefused in gen_server:handle_common_reply/8 line 751
14:23:29.897 [error] gen_server <0.933.0> terminated with reason: econnrefused
14:23:29.897 [error] CRASH REPORT Process <0.933.0> with 0 neighbours exited with reason: econnrefused in gen_server:handle_common_reply/8 line 751
14:23:29.941 [warning] Could not connect to postgresql due to econnrefused
14:23:29.941 [error] gen_server <0.934.0> terminated with reason: econnrefused
14:23:29.941 [error] CRASH REPORT Process <0.934.0> with 0 neighbours exited with reason: econnrefused in gen_server:handle_common_reply/8 line 751
14:23:29.949 [warning] Could not connect to postgresql due to econnrefused
14:23:29.949 [error] gen_server <0.935.0> terminated with reason: econnrefused
14:23:29.950 [error] CRASH REPORT Process <0.935.0> with 0 neighbours exited with reason: econnrefused in gen_server:handle_common_reply/8 line 751

Followed the following instructions to create table:

`CREATE EXTENSION pgcrypto;
CREATE TABLE vmq_auth_acl
 (
   mountpoint character varying(10) NOT NULL,
   client_id character varying(128) NOT NULL,
   username character varying(128) NOT NULL,
   password character varying(128),
   publish_acl json,
   subscribe_acl json,
   CONSTRAINT vmq_auth_acl_primary_key PRIMARY KEY (mountpoint, client_id, username)
 );`

And inserted test data:

`WITH x AS (
    SELECT
        ''::text AS mountpoint,
           'test-client'::text AS client_id,
           'test-user'::text AS username,
           '123'::text AS password,
           gen_salt('bf')::text AS salt,
           '[{"pattern": "a/b/c"}, {"pattern": "c/b/#"}]'::json AS publish_acl,
           '[{"pattern": "a/b/c"}, {"pattern": "c/b/#"}]'::json AS subscribe_acl
    ) 
INSERT INTO vmq_auth_acl (mountpoint, client_id, username, password, publish_acl, subscribe_acl)
    SELECT 
        x.mountpoint,
        x.client_id,
        x.username,
        crypt(x.password, x.salt),
        publish_acl,
        subscribe_acl
    FROM x;`

**Comment by ioolkos** [comment]
@nachten thanks...where is PostGres running?
'econnrefused' basically means Verne can't reach a listener on the configured IP:port.

**Comment by nachten** [comment]
VerneMQ is running in docker on my development machine
PostgreSQL is running as a local service on my development machine

**Comment by ioolkos** [comment]
:) Well, jep, or you need to find out how to reach the local service on the docker host, from the running docker image.
Don't know what the best way is, but as you say, probably not using "localhost".

**Comment by nachten** [comment]
Replacing "localhost" with "host.docker.internal" dit the trick for me ! Anyway thanks for kicking me in the right direction (stupid mistake my end)
