### ISSUE TITLE
SSL certificate reload without restart

### ISSUE THREAD

**Issue by apapacy** [vernemq/vernemq#1414]
We using Lets Encrypt certificates on the hosts being used for vernemq. LE certificates, by design, need to be renewed at least every 90 days. Our renewal process is automated and we can extend that automation process to restart vernemq when a new certificate is obtained.

It is necessary to provide soft certificate reloading, for example, using the command  vmq-adm

**Comment by ioolkos** [comment]
Need to look into the clues here, similar situation: https://github.com/ninenines/cowboy/issues/1233

**Comment by apapacy** [comment]
Tthanks

**Comment by micw** [comment]
May I asked, why this is closed?

**Comment by jforge** [comment]
> May I asked, why this is closed?

Concerning the related issue [ninenines/cowboy/issues/1233](https://github.com/ninenines/cowboy/issues/1233) this may be considered to be enough, but I also would like to see an update here; currently we seem to have just 2 options without a full restart(?):

- waiting for the cache TTL that seems to be a 120sec default (erlang ssl docs) - does this actually work?
- stopping and restarting listeners (i see no suspend/resume options or the like as mentioned in the related issue).

The feature request here should be to support 
- PEM cache TTL settings in the live reconfiguration (https://docs.vernemq.com/administration/config_values) using the bypass_pem_cache / clean_cache capabilities of the underlying ssl library (http://erlang.org/doc/man/ssl.html#clear_pem_cache-0)
- And/or suspending/resuming listeners

If I've missed anything or there is already some other existing solution, some note about this would be nice.

Currently I use VerneMQ in a docker container, and for updates on the CA certs or the server certs I would appreciate any method to avoid restarts.

**Comment by micw** [comment]
> * waiting for the cache TTL that seems to be a 120sec default (erlang ssl docs) - does this actually work?

I don't think so. Is there even code that checks the file for modification?

**Comment by ioolkos** [comment]
Okay, thanks, I'm re-opening the issue.
I agree the way to go or experiment with is the ranch suspend and resume functions for the MQTT listeners. I'm not going to look into this for now, though.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq

**Comment by micw** [comment]
Wouldn't a suspend/resume of the listeners ake the service unavailable for a period of time (and even terminate existing connections)? Is there a way to use new certs on new connections only and keep existing connections running?

**Comment by ioolkos** [comment]
@micw Suspending a listener will not disrupt existing connections, but it will stop accepting ones. So unless you have configured other MQTT listeners, you can't accept new clients for a short window.

**Comment by micw** [comment]
I think that's acceptable for most cases. So the solution could be to monitor the cert files and suspend/resume the listeners if the file has changed.
Ideally that would be done by a process within the broker - otherwise it would need to be scripted separately which might be quite error prone. What do you think?

**Comment by ioolkos** [comment]
@micw such a monitoring process would have to be a broker process, yes. 

Listener handling is here:
https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_ranch_config.erl

But the point is that so far we do not use the ranch `suspend/resume` interface in Verne. So basically, a first step would be an investigation on what the current implementation does or does not allow. 

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by micw** [comment]
This is great, thank you.
I got a bit confused by a comment in the linked PR:

> The clear-pem-cache is more of a convenience function, as after some time (some sources say 2 minutes, in my case it was longer) the new certificates are picked up by erlang anyway

I am very sure that when I commented in the issue here in 2021, VerneMQ dit _not_ pick up a change in the certificate/key file and we had to restart it after every certificate re-new. Has this behaviour changed meanwhile?

**Comment by ioolkos** [comment]
@micw I think the automatic PEM cache invalidation has been in OTP for a while. We also seem to see that it might take longer than the configured default interval. I do not know why this would be the case.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by micw** [comment]
Thank you. I could not find anything about this on the changelog. How is it configured? What is the default interval? And does "might take longer" mean it takes a bit longer or is it significant?
Because if that works and automatically picks up new certs after a few minutes or so, it should be good enough for let's encrypt cert rotation.

**Comment by ioolkos** [comment]
@micw the default is 2 minutes: https://www.erlang.org/doc/man/ssl_app#configuration
But `ssl:clear_pem_cache/0` can be called anytime. There's also `vmq-admin tls clear-pem-cache` for the same purpose now.
Regarding how high the delays are: please resolve by testing, I don't know why the 2 minutes would not apply.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
