### ISSUE TITLE
[QUESTION] Backend authentication

### ISSUE THREAD

**Issue by Paic** [vernemq/vernemq#1417]
Hi, I have a quick question about authentication.

I'm using VerneMQ inside a Kubernetes cluster with the diversity plugin enabled and configured to use MongoDB as the auth mechanism (`vmq_acl` and `vmq_passwd` are both `off`).
This works well for the devices authentication but now I need my backend, a stateless service with multiple replicas to connect to the broker and subscribe to a shared subscription.

I'm using the pod hostname as the clientId, but it would be complicated to add a document in MongoDB for each new pod.
I thought about making a small `vmq_diversity` plugin with custom rules to authenticate this service. Do you think this is the right way to go ?

### Environment

- VerneMQ Version: 1.10.1
- OS: Alpine 3.9
- Erlang/OTP version (if building from source): 22

**Comment by ioolkos** [comment]
@Paic Thanks ... please don't expect extended consulting on usage questions here.

But I guess you can do that with your idea. Or possibly adapting the MongoDB script directly, it's a fairly thin wrapper. You have access to the reg.client_id object there, and can add all kind of magic to the script. (like pattern matching those special client ids, etc)

**Comment by Paic** [comment]
Thanks for the feedback. I guess I could also do that, it does effectively looks quite simple.
