### ISSUE TITLE
How to store all messages in DB?

### ISSUE THREAD

**Issue by miptildar** [vernemq/vernemq#1418]
### Environment

- VerneMQ Version:  1.8.0
- OS: Ubuntu
- Erlang/OTP version (if building from source): 
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 1 node only

`vmq_diversity` is enabled.

### Expected behavior

- I am working on Android applicaition that should contain a  built-in messenger. The app can't lose any messages and should store all messages in some DB (in my case - PostgreSQL). 
I tried to add a hook to `on_publish` that saves all messages to PostgreSql

### Actual behaviour

- Getting the following error:

>  can't call function on_publish with args [..some arguments..] in "/usr/share/vernemq/lua/save.lua" due to {error,function_clause}

This is what `save.lua` file looks like

```lua
require "auth/auth_commons"
require "auth/postgres_cockroach_commons"

function save_message(reg)
    log.info("save_message() was called")
    results = postgres.execute(pool,
            [[INSERT INTO raw_messages  VALUES (?,?,?)]],
            reg.topic,
            reg.payload,
            reg.username)

        log.info(result)
end

pool = "my_pool_id"
config = {
        pool_id = pool,
        user="postgre_username",
        password="postgre_pass",
        host="aws rds hostname",
        port=5432,
        database="my_db"
}

postgres.ensure_pool(config)
hooks = {
        on_publish = save_message
}
```

And `raw_message` table has the following structure
```sql
topic varchar(256)
payload varchar(256)
username varchar(128)
```

I tried to use a code from this [discussion](https://github.com/vernemq/vernemq/issues/668), but it didn't help.

Using LevelDb is not an option.

Debugging is difficult, because I don't receive enough information about this error.
Maybe you have a ready lua code that allows to save messages in DB? Do you have erlang plugin for that?

**Comment by milgner** [comment]
Did you solve this? I'm just passing by while evaluating MQTT brokers, don't have any experience with VerneMQ - but from what I saw [here](https://github.com/vernemq/vernemq_dev/blob/master/src/on_publish_hook.erl) it seems to me like the function signature for `save_message` should have more arguments?
