### ISSUE TITLE
Can vernemq specify the vernemq.conf file path at startup?

### ISSUE THREAD

**Issue by Zack0421** [vernemq/vernemq#1425]
Environment
VerneMQ Version:1.10.1
OS: centos7

Hello!
Can vernemq specify the vernemq.conf file path at startup?

**Comment by ioolkos** [comment]
Hi @Zack0421 nope, the `vernemq` start script only has options to validate the conf file, no direct setting of load path. VerneMQ expects a couple of conf files in the default dir (vernemq.conf and advanced.conf if needed) and mixes together a generated conf file for everytime you boot VerneMQ.

Do you run into a specific issue that would make setting a path necessary?

**Comment by Zack0421** [comment]
Thank you for your reply @ioolkos 
We have different services and may need to start multiple VerneMQs to listen to different segments of the port. Because the authentication and permission control of different services are different

**Comment by ioolkos** [comment]
So then you would run multiple Verne instances on the same host? Yeah, that's tricky if not impossible, at least using the packages. We have the `make dev1 dev2 dev3` command to build and pre-configure multiple releases on the same host, but that's meant for development.

What you could do is configure mountpoints (each service having its own MQTT listener). You have access to the Mountpoint in the auth plugin hooks, so you could match on the Mountpoint and then do authentication accordingly. That's just a suggestion, of course, not knowing your exact architecture.

**Comment by Zack0421** [comment]
Thanks for your advice. I will try
