### ISSUE TITLE
i don't get the acl mechanism

### ISSUE THREAD

**Issue by stapel-tv** [vernemq/vernemq#1428]
- VerneMQ Version: 1.10.1
- OS: Ubunti 18.04
- VerneMQ configuration
allow_anonymous = off
plugins.vmq_passwd = on
plugins.vmq_acl = on
- Cluster size/standalone: standalone

I have 2 users, 'admin' and 'visitor' 

In my vmq.acl i have:
user admin 
topic read /#
topic write /#

user visitor
topic read /#

What i want is a read-only user and one that can publish

But when i publish something to, let's say /test, i get disconnected. The log says:
can't auth publish [<<"admin">>,{[],<<"MQTT_FX_Client">>},0,[<<>>,<<"all">>],<<"asdasd">>,false] due to chain_exhausted

What am i missing?

**Comment by ioolkos** [comment]
vmq.acl readable? is it where it's configured to be? trailing newline at the end of file? double spaces somewhere?

**Comment by stapel-tv** [comment]
ioolkos: thank you for your reply.
```
ls -la /etc/vernemq/
total 64
drwxr-xr-x   2 root root  4096 feb 15 10:32 .
drwxr-xr-x 149 root root 12288 feb 14 14:24 ..
-rw-r--r--   1 root root 39230 feb 14 16:50 vernemq.conf
-rw-r--r--   1 root root    67 feb 15 10:32 vmq.acl
-rw-r--r--   1 root root   232 feb 14 17:16 vmq.passwd
```
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_passwd.password_file = /etc/vernemq/vmq.passwd

there was no trailing newline at the end, there is now.
no double spaces in acl or passwd file

Same result. I can connect with the admin user (not with admin2, so that seems to work)
but i cannot subscribe to, say,  /test and publishing something means disconnection.

Any more info i can supply to give you a better insight?

thanks

**Comment by ioolkos** [comment]
@stapel-tv the acl file parser is super minimal. I forgot all the issues it might have, there were certainly a number issues opened on this in the past. Can you try 0, 1, 2 newlines between your user blocks? do you have comment lines in the file?

**Comment by stapel-tv** [comment]
No comments. And i tried0, 1m 2 and 3 newlines in between my user blocks. and 0, 1 and 2 newlines at the end.I will look through the old issues to find similar issues, and see if there was a solution then.

**Comment by ioolkos** [comment]
Note that at least vmq.acl and vernemq.conf show as owned by the vernemq user, not root, for me.

**Comment by stapel-tv** [comment]
I've given up on using acl, i am now using webhooks.

That works great, but i hope it doesn't impact performance too much.

Thanks for your efforts, you can close this ticket.

**Comment by ioolkos** [comment]
re: performance. what's your througput? (msg/s?)
