### ISSUE TITLE
client connects and offline messages get sent before subscribe happens

### ISSUE THREAD

**Issue by qubi-dev** [vernemq/vernemq#1432]
**- VerneMQ Version: 1.9.2**
**- OS: Ubuntu 18.04.3**
**- Cluster size/standalone: standalone**

**Clean sessions is false, I see messages building in the queue by using this command:**
**vmq-admin session show --client_id=mqttTest1 --offline_messages**

+----------------+
|offline_messages|
+----------------+
|       11       |
+----------------+

**Using MQTTBox I connect to the broker and then subscribe to the endpoint but I get no messages** **from the queue. Only the retain message if there is one.**

**Using the vmq-admin trace client client-id=mqttTest1 command I see that the messages in the** **queue are sent to the clientId BEFORE I subscribe to the topic to receive the data.** 

No sessions found for client "mqttTest1"
New session with PID <8962.21111.0> found for client "mqttTest1"
<8962.21111.0> MQTT RECV: CID: "mqttTest1" CONNECT(c: mqttTest1, v: 4, u: mqttTest1, p: mqttTest, cs: 0, ka: 10)
<8962.21111.0> Calling auth_on_register({{SOME IP ADDRESS},57411},{[],
                                                                   <<"mqttTest1">>},mqttTest1,mqttTest,false)
<8962.21111.0> Hook returned "ok"
<8962.21111.0> MQTT SEND: CID: "mqttTest1" CONNACK(sp: 1, rc: 0)
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m34, "/devices/10000") with payload:
    {'hello':'world'}
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m33, "/devices/10000") with payload:
    {'hello':'world'}
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m32, "/devices/10000") with payload:
    {'hello':'world'}
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m31, "/devices/10000") with payload:
    {'hello':'world'}
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m30, "/devices/10000") with payload:
    {'hello':'world'}
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m29, "/devices/10000") with payload:
    {'hello':'world'}
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m28, "/devices/10000") with payload:
    {'hello':'world'}
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m27, "/devices/10000") with payload:
    {'hello':'world'}
<8962.21111.0> MQTT SEND: CID: "mqttTest1" PUBLISH(d0, q2, r0, m26, "/devices/10000") with payload:
    {'hello':'world'}

**What am I doing wrong?**

**Comment by ioolkos** [comment]
@qubi-dev when a client sets clean_session false it asks for session persistence, including the subscriptions. That's kind of the point.

**Comment by qubi-dev** [comment]
> @qubi-dev when a client sets clean_session false it asks for session persistence, including the subscriptions. That's kind of the point.

I know that, what I dont understand is why the messages in the queue are being sent on client.connect() rather than client.subscribe(/devices/10000). If the offline messages are sent on connect and not subscribe, I didnt actually get the messages on the other end. I need to wait for client.subscribe before the offline messages are sent

**Comment by ioolkos** [comment]
Apologies, I don't understand.
I'll close this issue, as this is about client side and/or basic MQTT concepts.

If you feel there is a reproducible VerneMQ issue, please provide more context.
