### ISSUE TITLE
Shared subscription with all offline client

### ISSUE THREAD

**Issue by apapacy** [vernemq/vernemq#1434]
### Environment

- VerneMQ Version: 1.6.0
- OS: Linux Mint 19.2 Tina
- Erlang/OTP version (if building from source): Erlang/OTP 21 [erts-10.3.5.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

- VerneMQ configuration (vernemq.conf) or the changes from the default

```
allow_multiple_sessions = off
persistent_client_expiration = 1w
max_inflight_messages = 1
max_online_messages = -1
max_offline_messages = -1
max_message_size = 0
upgrade_outgoing_qos = off
```

- Cluster size/standalone: standalone

### Expected behavior

When all clients are disconnected, messages in a shared subscription are placed to the share group store (not the client store). After connecting, all the messages are placed to the share group store are delivered to available clients.

### Actual behaviour

When all clients are disconnected, messages in a shared subscription are placed to the client store  (not the share group store). All pending messages await the connection of the same client, a message was saved to the client store, during the absence of the connected clients.

### Step to reproduce
1. Make share subscription to topic with clientId = "1" and qos=2, then disconnect from server.
2. Make share subscription to topic with clientId = "2" and qos=2, then disconnect from server.
3. Send 10 messages to same topic.
4. Connect and make share subscription to topic with clientId = "1" and qos=2.

The server delivered part of the messages (not all messages)

**Comment by ioolkos** [comment]
@apapacy there's no concept of "share group store" or "client store" in VerneMQ.

Messages for shared subscribers will be routed to a queue, regardless whether the queue is in online or offline status (well, depending on the policies here: https://docs.vernemq.com/configuration/shared_subscriptions).
In general, if you feel, you found an issue for VerneMQ, try with the latest versions.
