### ISSUE TITLE
Cannot authenticate with postgres and bcrypt "minor b" ($2b$)

### ISSUE THREAD

**Issue by selarep** [vernemq/vernemq#1435]
### Environment

- VerneMQ Version: 1.10.1
- OS: Ubuntu 18.04
- Cluster size/standalone: standalone

### Expected behavior
The authentication should work properly.

### Actual behaviour
I was trying to configure authentication with postgres.
Everything is configured like in the documentation:
plugins.vmq_passwd=off
plugins.vmq_acl=off
plugins.vmq_diversity=on
vmq_diversity.auth_postgres.enabled=on
vmq_diversity.postgres.host=localhost
vmq_diversity.postgres.port=5432
vmq_diversity.postgres.password_hash_method=bcrypt

After being bumping into a wall for hours, i have thought that maybe there was a problem with bcrypt itself.
I have discovered that there is more than one bcrypt version.
So, the implementation I am using (on Node.js), by default uses bcrypt minor b (with $2b$ prefix in the result hashes). This doesn't work with this plugin.
Then I have tried setting the minor a (with $2a$ prefix) in my node.js code when saving users to database, and now it works!! :D

I write this issue for 2 things mainly:
- Help other people with similar problem.
- Inform about this incompatibility. If possible, someone could fix it, or at least, inform about this in the docs to prevent other people to loss time to debug this issue.

Thank you for the effort you all make to keep vernemq beeing as great as it is.

**Comment by ioolkos** [comment]
@selarep thanks for "documenting".
I guess only `$2a$` prefix is supported in Verne overall, for bcrypt.

**Comment by selarep** [comment]
Well, I have been reading further and seems like the implementation of 2a and 2b is the same. Just the version name was changed due to bug on specific implementations of bcrypt (in php and perl).
Also tried to change the starting part of password hash from $2b$ to $2a$ in a database register and vernemq authentication works exactly the same than creating the hash with the b as option.
I'm closing the issue, as it was more an extra documentation for a specific use case, than a bug.
I hope it helps somone.

@ioolkos Thanks :)
