### ISSUE TITLE
Build error on Debian testing

### ISSUE THREAD

**Issue by alishir** [vernemq/vernemq#1438]
### Environment

- VerneMQ Version: `master`
- OS: `Debian Testing`
- Erlang/OTP version (if building from source): `Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]`
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: `standalone`

### Expected behavior

- Build project from source without error

### Actual behaviour

I got error when try building from source, here is the output of `make rel` command:
[make_rel.log](https://github.com/vernemq/vernemq/files/4253034/make_rel.log)

**Comment by ioolkos** [comment]
Can't really help, looks like some linking issue maybe? 
What if you use `DEBUG=1 make rel`?

**Comment by codeadict** [comment]
On the master branch you may need to install the snappy headers. In Debian should be `sudo apt-get install libsnappy-dev`. This is a very recent change, need to update the docs about building from source today.

**Comment by alishir** [comment]
Thanks @codeadict.
The master branch compiled successfully after installing `libsnappy-dev`.
