### ISSUE TITLE
Is there any vernemq client library for erlang?

### ISSUE THREAD

**Issue by alishir** [vernemq/vernemq#1441]
Hi all,

Thanks for your great project. I want to implement an Erlang client for publishing data. Is there any vernemq library to publish data from Erlang?

Regards,
Ali

**Comment by ioolkos** [comment]
@alishir no, we have no Erlang client library of our own, other than the internal MQTT client used in the bridge.

**Comment by alishir** [comment]
@ioolkos Thanks a lot.
