### ISSUE TITLE
Store information o client Session

### ISSUE THREAD

**Issue by arroyoht** [vernemq/vernemq#1442]
I'm writing an auth plugin (erlang) for vernemq using JWT tokens,

Currently I can authenticate clients by verifying JWT token using `auth_on_register` hook,
which is passed using the `password` field

My problem is that I also need to validate permissions by checking the token `Claims` during `auth_on_publish` and `auth_on_subscribe` hooks, but I don't have access to the `password` field.

I'd like to know if there is some way of storing the `Claims` information on client session during `auth_on_register` hook, so I can later use this info to validate access during publish and subscribe.

Thanks.

**Comment by ioolkos** [comment]
@arroyoht not sure what the best approach is. I guess you could implement a cache as part of the plugin, similar to the diversity or webhooks cache.
@dergraf any comment?

**Comment by arroyoht** [comment]
I managed to adapt the webhooks cache for my use case, it is working as expected so I think I'll move forward with this solution. 
Thanks for the help!
