### ISSUE TITLE
How to avoid offline message lose when one vernemq node is down but never come back.

### ISSUE THREAD

**Issue by trevorjiang** [vernemq/vernemq#1443]
Hi,

This is a general question regarding scenario when one client subscribe to broker but then later, offline. When it come back online, we expect it will still receive messages that it has missed. According to documentation you provided, I know you stored offline messages but it looks like those offline messages are stored in that specific node that the client has subscribed to. So my question is, what if that node goes down and never come back. In this case, does that mean we lose those offline messages ? It seems like you only do data replication when you explicit want to make a live node leave cluster. 

So when this happen, how can we avoid data loss here ? 

Thanks

**Comment by ioolkos** [comment]
@trevorjiang thanks, your assessment is correct, you will loose access to offline messages, in case a node never comes back. It's quite simply an implementation tradeoff.

Note that implementations using mirrored queue concepts or similar, still might loose messages. Also note that we're always looking at an end to end architecture. What if, for instance, your clients with persistent subscriptions never come back? Their queues will fill up... until you run into the configured maximum and then the broker will start dropping messages to protect itself. 

I'm not saying Verne should never implement this kind of replication to increase persistence guarantees. I'm just providing context.

**Comment by ioolkos** [comment]
Closing issue due to no feedback.

**Comment by ynigoreyes** [comment]
Hello @ioolkos , to build off of @trevorjiang 's question, is it possible to store the offline messages into an external data store to read from later after a node failure? I understand that we can store offline messages anywhere using the `on_offline_message` hook, but I'm getting stuck on how we can send those offline messages that we saved externally to the clients that just reconnected after the node failure. Are there any issues/discussions open on increasing persistence for VerneMQ?
