### ISSUE TITLE
What is the significance of unhandled messages counter?

### ISSUE THREAD

**Issue by aurabhi** [vernemq/vernemq#1446]
Hi, 

We see the following counter growing to a large number. What exactly does this counter mean? 

queue_message_unhandled{app_kubernetes_io_instance="vernemq",app_kubernetes_io_managed_by="Tiller",app_kubernetes_io_name="vernemq",helm_sh_chart="vernemq-1911.0-20200220085046422",instance="192.168.86.152:8888",job="kubernetes-service-endpoints",kubernetes_io_hostname="dcmdb104-edge1",kubernetes_name="vernemq-headless",kubernetes_namespace="default",node="VerneMQ@vernemq-0.vernemq-headless.default.svc.cluster.local"} **6542895**

**Comment by ioolkos** [comment]
@aurabhi it's a counter, so the value it has is a total. It's the total number of messages thrown away, when you connect with clean_session=true (because then the broker has to delete all state from previous sessions).
