### ISSUE TITLE
VerneMQ on single node  can't support beyond 65K online connections

### ISSUE THREAD

**Issue by kksudo** [vernemq/vernemq#1451]
### Question

**How i can increase amount connections, for ex. above 100k ?**

### Description fo case
I tried some different ways to increase connection limit ( 65523 connections ).
VerneMQ located in k8s GKE, it has enough cpu and ram.
I have few listeners in VMQ into one pod.
Emqtt (load-testing tool) and VMQ are located in different clusters.

For the load tests i used emqtt, there are 4 pods with one white ip (test cluster(emqtt) it's different cluster from VMQ).
- 2 pods with emqtt for connect to vmq listener number  one: `emqtt_bench pub -h <ip> -I 65000 -i 10 -c 25100 -t load/test/%i/%c -u dev -P dev -p 1883 -V 4 -k 300 -q 1`
- 2 pods with emqtt for connect to vmq listener number two: `emqtt_bench pub -h <ip> -I 65000 -i 10 -c 25100 -t load/test/%i/%c -u dev -P dev -p 2883 -V 4 -k 300 -q 1`

Count of file descriptors (in the vmq pod, when i had 65k conn):
```fs.file-nr = 100096 0 1531742```
Count fo socket connections (in the vmq pod, when i had 65k conn):
`ss -s` `65532`

### Environment

- VerneMQ Version: 1.10.1
- OS: debian and alpine ( tried both )
`vernemq/vernemq:1.10.1-alpine`
`vernemq/vernemq:latest`
- The cluster is located in k8s GKE.
- Cluster size: 1 node
- Sysctl configs
```
net.core.somaxconn=262144; 
sysctl -w net.core.tcp_syncookies=1; 
sysctl -w net.ipv4.tcp_max_syn_backlog=262144; 
sysctl -w net.core.netdev_max_backlog=50000; 
sysctl -w net.ipv4.ip_local_port_range='1024 65535
```
- VerneMQ configuration (vernemq.conf)
```
accept_eula = no
allow_anonymous = off
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
coordinate_registrations = on
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.tcp.default = 127.0.0.1:1883
listener.vmq.clustering = 0.0.0.0:44053
listener.http.default = 127.0.0.1:8888
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local
plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = off
metadata_plugin = vmq_plumtree
vmq_acl.acl_file = ./etc/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = ./etc/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = ./share/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.postgres.ssl = off
vmq_diversity.postgres.password_hash_method = crypt
vmq_diversity.auth_cockroachdb.enabled = off
vmq_diversity.cockroachdb.ssl = on
vmq_diversity.cockroachdb.password_hash_method = bcrypt
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.mysql.password_hash_method = password
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.mongodb.ssl = off
vmq_diversity.auth_redis.enabled = off
vmq_bcrypt.pool_size = 1
log.console = file
log.console.level = info
log.console.file = ./log/console.log
log.error.file = ./log/error.log
log.syslog = off
log.crash = on
log.crash.file = ./log/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = VerneMQ@127.0.0.1
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
accept_eula=yes
listener.tcp.allowed_protocol_versions=4
log.console.level=info
max_inflight_messages=10000
persistent_client_expiration=1d
max_online_messages=-1
max_message_size=1048576
max_offline_messages=-1
allow_subscribe_during_netsplit=off
listener.max_connections=infinity
systree_enabled=off
allow_publish_during_netsplit=off
vmq_passwd.password_file=/etc/vmq-auth/vmq.passwd
vmq_acl.acl_file=/etc/vmq-auth/vmq.acl
allow_unsubscribe_during_netsplit=off
log.console=console
allow_register_during_netsplit=off
listener.tcp.alternative1=0.0.0.0:2883
listener.tcp.localhost=127.0.0.1:1883
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.48.9.62:1883
listener.ws.default = 10.48.9.62:8080
listener.vmq.clustering = 10.48.9.62:44053
listener.http.metrics = 10.48.9.62:8888
```

### Related issues
- [1172](https://github.com/vernemq/vernemq/issues/1172)

**Comment by ioolkos** [comment]
"there are 4 pods with one white ip" what does that mean?

**Comment by kksudo** [comment]
> "there are 4 pods with one white ip" what does that mean?
I am referring to the EMQTT tool, which consists of 4 pods and have one white ip. The cluster with emqtt tools has only one ip.

EMQTT cluster ( EMQTT pod (4 units) -> k8s ingress proxy (white ip) ) -> VMQ cluster.

**Comment by ioolkos** [comment]
And how many connections can the ingress proxy open?

**Comment by kksudo** [comment]
> And how many connections can the ingress proxy open?

Much more than 100k ( already tested )

**Comment by ioolkos** [comment]
OK, if you find out more, kindly keep us posted.

**Comment by codeadict** [comment]
Isn't `sysctl -w net.ipv4.ip_local_port_range='1024 65535` effectively limiting the max number of open ports around 65k? Maybe run `ss -s` to check the used ports. Also, the syntax seems to be `sysctl -w net.ipv4.ip_local_port_range=1024 65535` without the '

**Comment by kksudo** [comment]
> Isn't `sysctl -w net.ipv4.ip_local_port_range='1024 65535` effectively limiting the max number of open ports around 65k? Maybe run `ss -s` to check the used ports. Also, the syntax seems to be `sysctl -w net.ipv4.ip_local_port_range=1024 65535` without the '

No, it's the wrong describe in this issue.

It's result of the command `ss -s`. _On the left side - the vmq pod, on the right side proxy for vmq (incoming connections). 
Incoming request -> the VMQ k8s cluster (ingress proxy(2 haproxy pods) -> vmq pod)_
![image](https://user-images.githubusercontent.com/8701324/76868575-31421500-6878-11ea-9cb9-019711c30a2a.png)

**Comment by codeadict** [comment]
Seems like the VMQ one has reached the limit, can you increase the limit using something like `sysctl -w net.ipv4.ip_local_port_range=1024 200000` and see what happens?

**Comment by ioolkos** [comment]
@codeadict I don't think ports can be increased like that. (65535 is "16bit" limit, and actually imposed by TCP, not by OS level).

This is most likely not a VerneMQ limit, but limit of client or network/OS components on the path (possibly exhausting *their* local_port_range). If a server has a destination port of IP:1883, you can connect a million (as an example) TCP connections, supposed the source IPs and ports are all different.

@kksudo What is the conntrack configuration of the VerneMQ host here, btw?

**Comment by ioolkos** [comment]
It just hit me that it might be this: ERL_MAX_PORTS
https://github.com/vernemq/docker-vernemq/pull/199/files

**Comment by codeadict** [comment]
Very nice @ioolkos , that must be it `+Q N` is what i have in my env. One approach RabbitMQ takes it to monitor the ports/fd used vs available https://github.com/rabbitmq/rabbitmq-common/blob/379bbf7e7a6deafb88c49c8d0c200ae31d314e1c/src/file_handle_cache.erl#L1095. Would be a nice thing to have as a metric so users are aware or alert  when they hit the limit

**Comment by ioolkos** [comment]
@kksudo if you try latest docker builds, ERL_MAX_PORTS should be increased to 256k. 
Hope you can test it, thanks for your patience!

**Comment by ioolkos** [comment]
I'm considering this resolved, as we know how to configure for ERL_MAX_PORTS.
