### ISSUE TITLE
Unsupported Protocol Version when connect via SSL verison 5

### ISSUE THREAD

**Issue by rcaceiro** [vernemq/vernemq#1452]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version: 1.10.1
- OS: Alpine in Kubernetes
- Erlang/OTP version (if building from source):---
- VerneMQ configuration (vernemq.conf) or the changes from the default
```
accept_eula = yes
allow_anonymous = off
listener.nr_of_acceptors = 25
listener.tcp.allowed_protocol_versions = 5
allow_multiple_sessions = off
shared_subscription_policy = prefer_local
max_message_rate = 0

plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_webhooks = on
vmq_webhooks.webhook1.hook = auth_on_register
vmq_webhooks.webhook1.endpoint = https://ontrack.rcaceiro.eu/auth
vmq_webhooks.webhook2.hook = auth_on_register_m5
vmq_webhooks.webhook2.endpoint = https://ontrack.rcaceiro.eu/auth

erlang.distribution.port_range.minimum = 65535
erlang.distribution.port_range.maximum = 65435
listener.vmq.clustering = 0.0.0.0:44053
discovery_node = vernemq-0.service-vernemq.ns-database.svc.cluster.local
nodename = $(VERNE_POD_NAME).service-vernemq.ns-database.svc.cluster.local
distributed_cookie = <random value at configuration>

listener.ssl.cafile = /vernemq/certs/cacerts.crt"
listener.ssl.certfile = /vernemq/certs/tls.crt"
listener.ssl.keyfile = /vernemq/certs/tls.key"
listener.ssl.default = 0.0.0.0:8883"
listener.https.default.cafile = /vernemq/certs/cacerts.crt"
listener.https.default.certfile = /vernemq/certs/tls.crt"
listener.https.default.keyfile = /vernemq/certs/tls.key"
listener.https.default = 0.0.0.0:8443"
listener.http.default = 127.0.0.1:8888"
listener.ws.default = 127.0.0.1:8080"
listener.tcp.default = 0.0.0.0:1883"
```
- Cluster size/standalone: 2

### Expected behavior
Expect to connect with the protocol version 5 with SSL

### Actual behaviour
VerneMQ server throws a Unsupported Protocol Version error.

I tried the hivemq-mqtt-client library for JAVA and Android to establish connection with VerneMQ server when I try connect to connect via mqtt:// it works perfectly, buy if I try use the mqtts:// throws the Unsupported Protocol Version error. The same thing if I use the MQTTX client.

I tried the protocol 3.1.1 with and without SSL and connect as expected.

**Comment by ioolkos** [comment]
You need to configure the allowed_protocol version for the SSL listener. Also, all those end-line ", are those in config file?

**Comment by ioolkos** [comment]
@rcaceiro have you been able to resolve this?

**Comment by rcaceiro** [comment]
@ioolkos sorry, for the delay how I can add this allowed_protocol to SSL listener? Is it the same as TCP? And why with version 3 and 3.1.1 ins't need to add the allowed_protocol to SSL listener?
At last the " is because this config is configured in a kubernetes cluster and them escape!

**Comment by rcaceiro** [comment]
> @ioolkos sorry, for the delay how I can add this allowed_protocol to SSL listener? Is it the same as TCP? And why with version 3 and 3.1.1 ins't need to add the allowed_protocol to SSL listener?
> At last the " is because this config is configured in a kubernetes cluster and them escape!

@ioolkos thank you so much! In the VerneMQ documentation doesn't refer this subject, so thank you!
