### ISSUE TITLE
Do on_client_gone/on_client_offline plugin hooks work in the case of broker hard disconnect?

### ISSUE THREAD

**Issue by tsturzl** [vernemq/vernemq#1453]
This is less of a formal issue and more of a question. So we're writing a plugin to handle auth of IoT devices. We're also starting to use these sessions to tell whether or not an IoT device is online/available or not, we do this by tracking client sessions. What I'm wondering is if a broker were to hard crash(eg lose power) will all the client sessions connected to the broker that crashed still trigger an `on_client_gone` or `on_client_offline` on another broker? It's my assumption that vernemq keeps track of all clients and their respective brokers across all brokers in the verne cluster, so to me it seems like there should be a way to do this even if on_client_gone/offline do not already handle the case I'm outlining.

**Comment by ioolkos** [comment]
Hi @tsturzl thanks.
Plugin hooks are only triggered locally. If a node crashes, the remaining cluster does not trigger the gone/offline hooks. The remaining cluster also does not have an idea whether this is a netsplit or a crash.

There's a lot to say about the complexity of all this ;)

The need here is to know when a device is online or not (connected to the broker). I don't know whether it is worth the complexity to architect for the failure path. For the happy path multiple components are working together: the client device (which is supposed to re-connect!), the load balancer (which will forward the re-connecting device to another node, supposing it detects the state of the cluster), and the broker. 
This might to lead to 'stale' state for presence information during short periods, I guess.

**Comment by tsturzl** [comment]
This is something we've just been exploring. It seems to scale better than heartbeats. The net split issue is something I was also wary of, and now thinking of it more in depth it sounds like it's going to be a nonstarter. I also had the idea that if a broker goes down that all it's clients should reconnect, but there still remains the edgecase that clients could legitimately go offline before reestablishing a connection, and also what happens if the entire cluster goes down? Seems like you're probably right that the complexity is probably higher than it's worth. Seemed like a worthy thing to explore here.

**Comment by tsturzl** [comment]
So our current system uses LWT to notify when a device goes offline. LWT are provided as a connection setting so they can't be changed to hold a timestamp of when the LWT was sent. What we're thinking now is to used the plugin to timestamp LWT's. But this brings up the question, are LWT's replicated? For example, if I have a client with an LWT connected to a broker, and they go down at the same time will that LWT still get sent? Is there a window of uncertainty here where an LWT might not gets sent because the broker it was connected to wasn't available?

**Comment by tsturzl** [comment]
After digging through the docs, I think it's reasonable to assume LWT is reliable during broker failure, and to some extend netsplits. I'll go ahead and close this ticket. Thanks for the quick response. I think our newer approach should address most of the issues, if not I'll open a new ticket.

**Comment by ioolkos** [comment]
Well, test your assumptions. I don't know what exactly you mean by LWT being reliable during broker failure.
