### ISSUE TITLE
Could not connect to mongodb due to nxdomain

### ISSUE THREAD

**Issue by himadrinath** [vernemq/vernemq#1454]
trying to connect mongodb atlas sendbox 
### Environment

- VerneMQ Version: 1.10.1
- OS:  Ubuntu 18.04.3 LTS (bionic)
- configured 
```
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = on
vmq_diversity.auth_mongodb.enabled = on
vmq_diversity.mongodb.host = mongodb+srv://test-abcd.mongodb.net
vmq_diversity.mongodb.port = 27017
vmq_diversity.mongodb.login = readonly
vmq_diversity.mongodb.password = mysecretpassword
```

- Cluster size/standalone: standalone

### Expected behavior

should be able to connect to mongodb

### Actual behaviour

- error.log

> <0.4385.0>@mc_connection_man:recv_all:102 CRASH REPORT Process <0.4385.0> with 0 neighbours crashed with reason: no match of right hand value {error,closed} in mc_connection_man:recv_all/4 line 102

- console.log

>  [warning] <0.490.0>@vmq_diversity_worker_wrapper:handle_info:166 Could not connect to mongodb due to nxdomain

**Comment by ioolkos** [comment]
nxdomain error means that the domain is "not existing". So this is clearly about the Mongodb hostname in your config.
Note that the plugin currently does not support DNS seedlist connection format.

**Comment by himadrinath** [comment]
Thnaks

**Comment by himadrinath** [comment]
@ioolkos  i tried with azure cosmosdb with mongo api when i tried to connect with mongo shell with

`mongo --username myusername --password mypassword --host cosmos.host.azure.com --port 10255 --tls`

its working

but not working in vernemq  with 

```
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = on
vmq_diversity.auth_mongodb.enabled = on
vmq_diversity.mongodb.host = cosmos.host.azure.com
vmq_diversity.mongodb.port = 10255
vmq_diversity.mongodb.login = readonly
vmq_diversity.mongodb.password = mysecretpassword
vmq_diversity.mongodb.ssl = on
vmq_diversity.mongodb.cafile = /etc/letsencrypt/live/domain/fullchain.pem
vmq_diversity.mongodb.certfile = /etc/letsencrypt/live/domain/cert.pem
vmq_diversity.mongodb.keyfile = /etc/letsencrypt/live/domain/privkey.pem
```

geting this error msg

`[error] <0.823.0> CRASH REPORT Process <0.823.0> with 0 neighbours crashed with reason: <<"Can't pass authentification">> in mc_auth_logic:scram_sha_1_auth/5 line 55`

**Comment by ioolkos** [comment]
https://github.com/vernemq/vernemq/issues/1163 ?

**Comment by himadrinath** [comment]
in cosmos db 
`Error: couldn't add user: Command createUser not supported. :`

i think add user not supported in cosmos

**Comment by himadrinath** [comment]
any way thanks

**Comment by johnnytolengo** [comment]
the same problem here, how did you solve it?
what config did you use?
