### ISSUE TITLE
Can't connect to cluster node due to no_config

### ISSUE THREAD

**Issue by MichelJansen91** [vernemq/vernemq#1456]
### Environment

- VerneMQ Version: Docker image: erlio/docker-vernemq:latest
- VerneMQ configuration (vernemq.conf):
```
accept_eula = yes

allow_anonymous = off
plugins.vmq_diversity = on
plugins.vmq_passwd = off
plugins.vmq_acl = off

vmq_diversity.auth_postgres.enabled = on
vmq_diversity.postgres.host = BLURRED
vmq_diversity.postgres.port = 5432
vmq_diversity.postgres.user=BLURRED
vmq_diversity.postgres.password=BLURRED
vmq_diversity.postgres.database=BLURRED
vmq_diversity.postgres.ssl=off
vmq_diversity.postgres.password_hash_method = crypt

allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = on

max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
message_size_limit = 0
upgrade_outgoing_qos = off

listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.tcp.default = 0.0.0.0:1883

erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109

listener.mountpoint = off
systree_interval = 20000
graphite_interval = 15000
graphite_prefix = vernemq
graphite_port = 2003
graphite_host = carbon.hostedgraphite.com
graphite_api_key = UNDEFINED
log.console = console
log.console.level = debug
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5

nodename = VerneMQ

distributed_cookie = broker

erlang.async_threads = 64
erlang.max_ports = 65536
```
- Cluster size/standalone: Cluster of 2+ nodes

### Expected behavior

I am trying to setup a cluster with Docker containers (first on my local machine, then planning to use Amazon ECS). I have created my local image (based on `erlio/docker-vernemq:latest`) that only adds the custom config file that is shown above to the container. I am starting the first node with:
`docker run -e "DOCKER_VERNEMQ_LISTENER_VMQ_CLUSTERING=172.17.0.2:44053" --name testVernemq CUSTOM_VERNEMQ_IMAGE`
The first container will launch, and I can publish and subscribe to it. The ipaddress that it works on is 172.17.0.2, so then I am starting a second container that will be active on 172.17.0.3 with:
`docker run -e "DOCKER_VERNEMQ_DISCOVERY_NODE=172.17.0.2" -e "DOCKER_VERNEMQ_LISTENER_VMQ_CLUSTERING=172.17.0.3:44053" --name testVernemq2 CUSTOM_VERNEMQ_IMAGE`

Both nodes are now up, as is shown when I execute `docker exec testVernemq2 vmq-admin cluster show`:
```
+------------------+-------+
|       Node       |Running|
+------------------+-------+
|VerneMQ@172.17.0.2| true  |
|VerneMQ@172.17.0.3| true  |
+------------------+-------+
```
I expect that both nodes are working together, and that it does not matter to which broker I am subscribed (on AWS a load balancer will be in front of the cluster). So I should be able to subscribe on the first node, and publish on the second:
`mosquitto_sub -h 172.17.0.2 -p 1883 -t "test" -u "test-user" -P "123" -i "test-client" `
and in another terminal:
`mosquitto_pub -h 172.17.0.3 -p 1883 -t "test" -m "test publishing" -u "test-user" -P "123" -i "test-client"`

### Actual behaviour

However,the console log of both nodes give the following warning:
```
17:35:38.919 [info] cluster node 'VerneMQ@172.17.0.3' UP
17:35:38.921 [info] writing state {[{[{actor,<<178,152,34,116,173,67,75,220,141,123,154,19,25,83,133,248,232,145,92,207>>}],1},{[{actor,<<212,167,154,123,195,138,0,141,118,183,223,79,12,38,44,226,237,72,223,140>>}],1}],{dict,2,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[['VerneMQ@172.17.0.2',{[{actor,<<178,152,34,116,173,67,75,220,141,123,154,19,25,83,133,248,232,145,92,207>>}],1}]],[['VerneMQ@172.17.0.3',{[{actor,<<212,167,154,123,195,138,0,141,118,183,223,79,12,38,44,226,237,72,223,140>>}],1}]],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}} to disk <<75,2,131,80,0,0,1,114,120,1,203,96,206,97,96,96,96,202,96,2,81,140,25,76,41,12,172,137,201,37,249,69,185,64,174,200,166,25,74,37,107,157,189,239,244,86,207,18,150,12,110,253,241,98,98,204,249,172,68,160,42,108,138,175,44,159,85,125,184,139,161,183,108,251,125,127,30,53,157,71,111,61,238,247,0,21,103,101,112,166,48,176,164,100,38,151,36,50,37,10,0,33,71,98,64,162,65,134,64,22,26,200,96,4,137,129,13,6,187,40,133,65,40,44,181,40,47,213,55,208,193,208,220,72,207,208,92,207,64,207,8,187,205,56,156,73,200,52,99,236,166,225,242,7,138,123,17,158,98,32,236,41,20,157,89,0,127,112,116,89>>
17:35:39.927 [warning] can't connect to cluster node 'VerneMQ@172.17.0.3' due to no_config
17:35:40.180 [info] completed metadata exchange with 'VerneMQ@172.17.0.3'. repaired 0 missing local prefixes, 1 missing remote prefixes, and 0 keys
17:35:40.928 [warning] can't connect to cluster node 'VerneMQ@172.17.0.3' due to no_config
17:35:41.929 [warning] can't connect to cluster node 'VerneMQ@172.17.0.3' due to no_config
17:35:42.930 [warning] can't connect to cluster node 'VerneMQ@172.17.0.3' due to no_config
17:35:43.931 [warning] can't connect to cluster node 'VerneMQ@172.17.0.3' due to no_config
```
It seems that they are connected, but not working together. Probably I misconfigured something, but I don't know what. I took this [config file](https://github.com/ThingMesh/docker-vernemq/blob/master/vernemq.conf.default) as a starting point, and tried to modify it to my own example.

**Comment by ioolkos** [comment]
Can your docker images reach each other on the listener.vmq.clustering port?

**Comment by MichelJansen91** [comment]
Ok I further analyzed the problem, but it turns out that the environment variable that I add to Docker is not added to the configuration file. Temporarily I created two separate images with both the `listener.vmq.clustering` port hardcoded to the ipaddress that the container gets (luckily that is constant all the time). With the two separate images the nodes connect successfully to each other.

When I start a container with the old image with following command:
`docker run -e "DOCKER_VERNEMQ_LISTENER_VMQ_CLUSTERING=172.17.0.2:44053" --name testVernemq CUSTOM_VERNEMQ_IMAGE`
Then I try to print the variables in the config file with:
`docker exec testVernemq cat /etc/vernemq/vernemq.conf | grep vmq`
The output is nothing. So apparently the script that adds all environment variables with prefix DOCKER_VERNEMQ does not work properly for me. I will look into that a bit more.

**Comment by MichelJansen91** [comment]
I found the error and it was my own mistake. I misunderstood the start_vernemq script, so i thought I had to copy my own configuration to `/etc/vernemq/vernemq.conf.local`. That disables the environment variables however. I now removed the `.local` extension and now it works fine.
Sorry for bothering!
