### ISSUE TITLE
can't authenticate client due to chain_exhausted

### ISSUE THREAD

**Issue by rajenpal033** [vernemq/vernemq#1462]
Hello,

I have configured everything according to official document to enable mysql authentication but unable to connect broker due the following warning in console.log

> [warning] <0.650.0>@vmq_mqtt_fsm:check_user:573 can't authenticate client {[],<<"593d16de-335c-49f4-b3e1-056c72b69b351585812976068">>} from 47.15.174.228:54281 due to chain_exhausted

But nothing in crash.log or error.log, I am using the same lua scripts given with this official repository. I have tried to find solution over here in previous issues, but nothing worked, Please help me on this.

Regards.

**Comment by ioolkos** [comment]
It's not an error. The plugin system tells you that it hasn't found any authentication plugin that can authenticate your user. (that's what meant by "chain exhausted", Verne went through the chain of plugins and hasn't found any able to authenticate your connecting client).

You need to review (in the `vernemq.conf` file) what auth plugins are activated.

**Comment by rajenpal033** [comment]
@ioolkos thanks for your quick reply my configuration for diversity

`plugins.vmq_diversity = on
plugins.vmq_passwd = off
plugins.vmq_acl = off
allow_anonymous = off
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.mysql.host = 127.0.0.1
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = username
vmq_diversity.mysql.password = password
vmq_diversity.mysql.database = db_name
vmq_diversity.mysql.password_hash_method = md5
`

I have checked the values many times, all are ok

**Comment by rajenpal033** [comment]
Well, I had some config issue, so mysql connection was failing from vernemq, now it's solved, and on vernemq restart, I can't see any error in log, but from mqtt client it still unable to connect and no error in console this time.

**Comment by ioolkos** [comment]
Maybe MySQL password issues: https://docs.vernemq.com/configuration/db-auth#mysql
Not everything is supported by Verne plugin.

**Comment by codeadict** [comment]
Also - what version of MySQL do you use? We do not support 8.x yet.

**Comment by rajenpal033** [comment]
@codeadict @ioolkos MySQL version I checked is, 5.7.29. All I can see is a continuous debug message in console.log as follows:

> [debug] <0.227.0>@plumtree_broadcast:schedule_lazy_tick:720 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms

also, is there any way to determine whether the connection requests are passing to Lua or not?

**Comment by tianmaxingkonggrant** [comment]
vmq_diversity.mysql.host = 127.0.0.1 may be error. in docker may be can't find the ip 127.0.0.1，use `ip addr` show your network segments

**Comment by hzlijianjun** [comment]
I guess you were using the mqtt client from eclipse paho, and which version is not "org.eclipse.paho.client.mqttv3", but "org.eclipse.paho.mqttv5.client" , the .mqttv5.client is not compatible with Vernemq until 1.13.0.  
I replace the mqttv5.client with mqttv3 resolved my problem as yours today.
