### ISSUE TITLE
Questions about listeners and clustering

### ISSUE THREAD

**Issue by Erlandys** [vernemq/vernemq#1464]
Hello,
I would like to ask couple questions about VerneMQ, tried to look for such information, but haven't found it:

1. If you launch one node with couple listeners, are they separate processes, which has separate resources, or just one process, which just listens on different ports? I mean, is it the same as two different brokers, or just one with two ports to listen?
2. If you make Cluster, with for example 3 Nodes, on 3 different servers. 2 nodes are reachable for clients and one node is only for backend services and you have XXX clients on two reachable nodes, does node for backend services (with couple clients(backend services)) gets alot of load, since clustering is made with other two nodes?

Thanks for your answers and time!

Ps. Sorry if this is not the place for such questions, since I haven't found other place where to ask them.

**Comment by ioolkos** [comment]
Hi @Erlandys 
1. Two listeners are separate processes (within an Erlang architecture), configured for different listening ports. They do not share resources, but obviously, they still run in the same broker. If your question has specific context, please add more information.
2. Well, the 3rd node would potentially want to see all incoming messages, right? So those backend services would create subscriptions to get all messages, which means the cluster will route all messages to 1 node. That might have some potential for load, I guess.
Test it.

**Comment by Erlandys** [comment]
> Hi @Erlandys
> 
>     1. Two listeners are separate processes (within an Erlang architecture), configured for different listening ports. They do not share resources, but obviously, they still run in the same broker. If your question has specific context, please add more information.
> 
>     2. Well, the 3rd node would potentially want to see all incoming messages, right? So those backend services would create subscriptions to get all messages, which means the cluster will route all messages to 1 node. That might have some potential for load, I guess.
>        Test it.

Hi, and thanks for quick response.
1. Well the question basically is for resources distribution in VM, will 2 listeners, would perform better than 1. The question mainly rises, from using Mosquitto broker, since usually in one VM, couple brokers with distributed clients perform alot better than one broker with all clients.
2. If we have several nodes created in same cluster, backend services will connect only to one node, so by the idea, that connected node will receive more load, than the ones without backend services, so in this point, as your answer, I think it's to still have separate node for backend services, to not load nodes with clients.

**Comment by ioolkos** [comment]
1. I don't think 2 Listeners would automatically perform better than 1 (also: define performance). Each MQTT client ends up having it's own TCP session and MQTT state machine on the broker. So basically the same concurrency, with 1 or with multiple Listeners. For connects, you can increase concurrency by increasing the number of Acceptors a Listener has.
Multiple listeners are interesting for various reasons though (configureing different mountpoints, or configuring different TCP buffer sizes for corresp. needs, for instance).
2. Trade-offs. The node would not handle clients but you'd have increased inter-node traffic towards a single node.
