### ISSUE TITLE
Questions about file based auth

### ISSUE THREAD

**Issue by jdavis74** [vernemq/vernemq#1470]
We are evaluating using file based authentication in a VerneMQ deployment and have a few questions.  We would prefer to use it due to its simplicity but have a few questions.

1. How scalable is file based auth vs. using a database?  Would file based auth with 10000 user accounts be feasible?
2. vmq-password seems to use SHA512 for password hashing.  This means if you were using file based auth and decided to move to using a database, you couldn't use a script to build the database from the password file since none of the database backends support that hash method, correct?
3. Can you mix file based and database auth?  Will wildcard ACL's in vmq.acl apply to database read users?

Thanks for the help.

**Comment by ioolkos** [comment]
@jdavis74 Thank, I don't have answers for all your questions.
1. "feasible" is probably more a question of how practical this is to manage than loading the password file with 10k users.
2. Good point. I don't know whether there's an easy way to import the SHA512 password file into DBs. Would need to research that.
3. You can chain authorization plugins, and vmq.acl will just be the first being called. (if it can't authorize a client, it will hand the authorization attempt over to the next plugin). 
In general, the database plugins are built to do both authentication and authorization. To use authentication only, you'd have to adapt the Lua scripts. Probably not what you want to do.
