### ISSUE TITLE
vmq-admin plugin enable doesn't work as expected

### ISSUE THREAD

**Issue by cdro-idirect** [vernemq/vernemq#1477]
Hi all!

I'm trying to enable/disable a mqtt bridge without restarting VerneMQ. When looking at the documentation for the vmq-admin tool this seems to be achievable with just enabling/disabling the bridge plugin.

### Environment

- VerneMQ Version: 1.10.2
- OS: CentOS 8

### Behavior 
So, in my config I have configured a bridge, but I've set: plugins.vmq_bridge = off
Now I tried: vmq-admin plugin enable -n vmq_bridge
It displays "Done" and the bridge plugin is loaded, but the bridge that is configured is not connecting, so either I'm missing something here or there is a bug? Could someone please clarify?

(Actually it would be a nice feature for the vmq-admin to just have something like "vmq-admin bridge start/stop <name>" or something)

A little bit of context, in case you are wondering why I'm trying that: I'm trying to set up a cluster with multiple nodes that should connect via bridge to another broker/cluster. The thing is, I can only have one bridge active at a time, otherwise every node in the cluster will forward the message over it's own bridge, so I receive the same message multiple times in the other cluster.

**Comment by ioolkos** [comment]
@cdro-idirect I think the plugin enable command should start any bridge that is pre-configured in the `vernemq.conf` file, yes. Do you see any errors logged?

I agree that having more options for bridge administration in `vmq-admin` would be nice. Certainly open to ideas and PRs.

**Comment by cdro-idirect** [comment]
@ioolkos There is no error in the logfile. I changed the loglevel to debug and the only thing of interest that appears in the logfile is:
> 2020-04-27 06:28:01.076 [debug] <0.198.0>@vmq_plugin_mgr:load_app_modules:674 loading modules: [vmq_bridge,vmq_bridge_app,vmq_bridge_cli,vmq_bridge_sup]

`vmq-admin bridge show` gives no output:
> sudo vmq-admin bridge show
> Last login: Mon Apr 27 06:36:32 UTC 2020 on pts/1

The bridge config itself works. When I enable it in the config file and then restart vernemq, it automatically connects.

**Comment by ioolkos** [comment]
@cdro-idirect ok, thanks. The "loading modules" debug log tells us that the bridge is actually correctly starting. 
So there seems to be some form of bootstrap issue in getting the bridge configs.

What happens if you do the following sequence: 
1. Start VerneMQ with `plugins.vmq_bridge = on`, 
2. Disable the plugin
3. Enable the plugin again. 

Are the bridges started/connected at this point?

**Comment by cdro-idirect** [comment]
@ioolkos Just tried that, sadly this doesn't change anything:

> sudo vmq-admin bridge show
> Last login: Mon Apr 27 09:29:58 UTC 2020 on pts/1
> +-----------------+-----------+----------+-------------------+
> |    endpoint     |buffer size|buffer max|buffer dropped msgs|
> +-----------------+-----------+----------+-------------------+
> |10.68.10.202:8883|     0     |    0     |         0         |
> +-----------------+-----------+----------+-------------------+
> 
> sudo vmq-admin plugin disable --name vmq_bridge
> Last login: Mon Apr 27 09:30:11 UTC 2020 on pts/1
> Done
> 
> sudo vmq-admin bridge show
> Last login: Mon Apr 27 09:30:23 UTC 2020 on pts/1
> RPC to 'VerneMQ@10.68.10.203' failed: {'EXIT',
>                                        {noproc,
>                                         {gen_server,call,
>                                          [vmq_bridge_sup,which_children,
>                                           infinity]}}}
> sudo vmq-admin plugin enable --name vmq_bridge
> Last login: Mon Apr 27 09:30:30 UTC 2020 on pts/1
> Done
> 
> sudo vmq-admin bridge show
> Last login: Mon Apr 27 09:30:47 UTC 2020 on pts/1
> 

The log:
> 2020-04-27 09:30:01.761 [debug] <0.194.0>@vmq_plugin_mgr:load_app_modules:674 loading modules: [vmq_acl,vmq_acl_app,vmq_acl_cli,vmq_acl_reloader,vmq_acl_sup]
> 2020-04-27 09:30:01.846 [debug] <0.194.0>@vmq_plugin_mgr:load_app_modules:674 loading modules: [vmq_bridge,vmq_bridge_app,vmq_bridge_cli,vmq_bridge_sup]
> 2020-04-27 09:30:01.930 [debug] <0.194.0>@vmq_plugin_mgr:load_app_modules:674 loading modules: [vmq_passwd,vmq_passwd_app,vmq_passwd_cli,vmq_passwd_reloader,vmq_passwd_sup]
> 2020-04-27 09:30:01.998 [debug] <0.398.0>@vmq_queue:state_change:1092 transition from offline --> online because of add_session
> 2020-04-27 09:30:02.136 [debug] <0.396.0>@vmq_bridge:handle_info:134 connected to: 10.68.10.202:8883
> [...]
> 2020-04-27 09:30:23.539 [info] <0.43.0> Application vmq_bridge exited with reason: stopped
> 2020-04-27 09:30:23.539 [debug] <0.194.0>@vmq_plugin_mgr:purge_app_modules:669 purging modules: [vmq_bridge,vmq_bridge_app,vmq_bridge_cli,vmq_bridge_sup]
> [...]
> 2020-04-27 09:30:47.496 [debug] <0.194.0>@vmq_plugin_mgr:load_app_modules:674 loading modules: [vmq_bridge,vmq_bridge_app,vmq_bridge_cli,vmq_bridge_sup]

**Comment by ioolkos** [comment]
Ok, thanks for testing.

**Comment by ioolkos** [comment]
Thanks. Okay, I need to find out what the original intent was. There's a `change_config` hook that is implemented in the bridge. (It's an internal hook of the VerneMQ plugin system).
When I force a reconfiguration of the whole node (`vmq_config:configure_node().`), then the `change_config` hook is called and all the bridge components are restarted.

So, I need to find out whether the fact that enabling the bridge plugin does not trigger the change config hook is an omission or a bug.

**Comment by ioolkos** [comment]
@cdro-idirect added a start command in PR https://github.com/vernemq/vernemq/pull/1490
This is somewhat of a quick hack. It just allows to start the bridges after you have enabled the plugin. (`vmq-admin bridge start`).
