### ISSUE TITLE
Can't publish due to no matching hook found on anonymous mode

### ISSUE THREAD

**Issue by martinnp12** [vernemq/vernemq#1479]
### Environment
- VerneMQ Version: 1.10.1
- OS: Ubuntu 18.04.4 LTS
- VerneMQ configuration (vernemq.conf) changes from the default:
       -allow_anonymous = yes
       -plugins.vmq_passwd = off 
       -plugins.vmq_acl = off
- Cluster size/standalone: 1 node

### Expected behavior

I'm trying to send data from the MQTT client FRED to VernMQ, without any authentification to test the broker.

### Actual behaviour

Can't publish due to no matching hook found. 

`2020-04-25 17:48:15.802 [error] <0.423.0>@vmq_mqtt_fsm:auth_on_publish:728 can't auth publish [undefined,{[],<<"mqtt_d55bc94a.f55b48">>},0,[<<>>,<<"testtopic">>],<<"{\$$,<<"{\"temperature\":50}">>,false] due to no_matching_hook_found`

**Comment by ioolkos** [comment]
@martinnp12 Hi, thanks, you need *some* form of authorization in any case, even if it's just switching on `vmq_acl` (you can use some form of allow anything pattern there, if you really don't want to do any authorization for who can subscribe and publish to topics).

**Comment by martinnp12** [comment]
Thanks for your answer. I tried activating the `vmq_acl`, but it doesn't work yet.  I wrote the next line in the file `vmq.acl`:  `topic testtopic`

**Comment by ioolkos** [comment]
The ACL file parser stumbles upon a couple of things. Check the ACL file for end of file/newlines, delete the comment too, to reduce.
Verne found your auth plugin, but is telling you that it was looking for another plugin in the plugin chain as vmq_acl could not authenticate your user. (and then fails with `chain_exhausted` as there is no additional auth plugin, of course).

Also note that "testtopic" and "/testtopic" are not the same topics (just making sure)

**Comment by martinnp12** [comment]
It's finally working. Thank you so much!
