### ISSUE TITLE
Vernemq Auth using Database : Mongo Connection issue

### ISSUE THREAD

**Issue by anpjavatech** [vernemq/vernemq#1480]
Hi
I'm getting mongo connection issue while trying to do Auth using database.
Using Vernemq docker and Mongo 3.6.17 version.

![image](https://user-images.githubusercontent.com/6368801/80300315-2359ab00-87b9-11ea-9a7f-337ce83de201.png)

In vernemq Im getting the following log

![image](https://user-images.githubusercontent.com/6368801/80300327-45532d80-87b9-11ea-91b5-8ca960287931.png)

Any help is deeply appreciated.

_Originally posted by @anpjavatech in https://github.com/vernemq/vernemq/issues/436#issuecomment-619496751_

**Comment by ioolkos** [comment]
ECONNREFUSED should give you a hint.

**Comment by anpjavatech** [comment]
I checked in the crash log. It gives something like this. Is it because of the old mongo version ?

![image](https://user-images.githubusercontent.com/6368801/80300499-0625dc00-87bb-11ea-9cdc-6f6eecf2946b.png)

**Comment by ioolkos** [comment]
https://github.com/vernemq/vernemq/issues/1163

**Comment by anpjavatech** [comment]
Thanks a lot @ioolkos for the quick response and for showing the right path.
It sounds like I need to upgrade mongo to the latest.
