### ISSUE TITLE
Metrics counter for individual topics / topics wildcard.

### ISSUE THREAD

**Issue by robputt796** [vernemq/vernemq#1484]
Hello,

This isn't really an issue more of a feature request. We are running VerneMQ for a number of tenants and are performing multitenancy via an ACL and users restricting each tenant to topics under their name e.g. TENANT_A/#, TENANT_B/#. We are getting a few noisy tenants who probably need to be moved to their own mini-cluster as they are outgrowing a shared environment although we have no metrics per wildcarded topic. 

Is there a way to do this already? If so I couldn't find any docs for it, I'd be happy to write a PR for the docs if someone can explain how these metrics can be gathered. Or if it isn't already a feature is this something that could be done either in the main project and optionally turned on in config, or via a plugin of some sort?

Sorry if this isn't the right forum to ask such a question. Your advice is appreciated.

Best Regards,

Rob

**Comment by ioolkos** [comment]
@robputt796 thanks. the question is metrics per topic?
(can you get in touch with me on contact at octavolabs com for details?)

**Comment by robputt796** [comment]
Closing this as implemented what I needed using a webhook and stashing the counts in InfluxDB.

**Comment by ioolkos** [comment]
Great, thanks for letting us know.
