### ISSUE TITLE
how to enable slave_ok in vernemq diversity mongodb

### ISSUE THREAD

**Issue by nithinkd-geon** [vernemq/vernemq#1494]
hello

is there any way to change/or set slave_ok option in mongodb plugin?

i tried with custom vernemq diversity plugin with Mongo data 
pool = "auth_mongodb_custom"
config = {
    pool_id = pool,
    r_mode = 'slave_ok'
}
but r_mode = 'slave_ok' is not working still trying to read from master ,I need to allow vernemq to read master as well as secondary

**Comment by ioolkos** [comment]
@nithinkd-geon thanks, jep, that's currently not supported.
