### ISSUE TITLE
REST API for Filebased authentication

### ISSUE THREAD

**Issue by achandana** [vernemq/vernemq#1495]
I am looking for Any REST Api available for the File based authentication. I have checked vmq-admin have the HTTP api like that do we have for vmq-passwd. Can any one help on this.

**Comment by ioolkos** [comment]
@achandana thanks, the file based authorization has no command line or REST interface.
You can look into doing authorization with a database based plugin.

Note that `vmq_acl` (file based authorization) gives you the most value when you can define authorization with a few simple patterns (using a clientID placeholder, for instance).
