### ISSUE TITLE
Using time -v to measure memory and CPU usage

### ISSUE THREAD

**Issue by NewBermuda** [vernemq/vernemq#1499]
# Environment

- VerneMQ Version: 1.10.2
- OS: Ubuntu 18.04.4 (VM)
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
allow_anonymous = on
- Cluster size/standalone standalone

# Expected behaviour:
I'm using Apache Jmeter and the Use time -v command to measure CPU and memory usage for various network scenarios. Right now I'm testing how the resource usage changes if a single client connects to VerneMQ and subscribes to an increasing numbe of topics (1 topic to 100000 topics).
I'd like to use time -v to measure the usage:

```
sudo time -v timeout 60 vernemq console -noshell -noinput 2>> $local/server_results/test1/verne_$b.txt &

# process for load testing
sleep 10
sudo timeout 60 ~/Downloads/apache-jmeter-5.2.1/bin/jmeter -n -t $local/testplans/csv.jmx -Jport=$a & : 

sleep 75 && kill %!
```

As you can see, I added the console -noshell -noinput arguments, so that VerneMQ would start as a foregound process that time can measure

# Actual behaviour:
It seems like VerneMQ is still running a background process for the load, and the time commands measure only a resource consumption of 4 MB RAM for all scenarios. How can I make sure that vernemq can be measured using the time command? Is this not possible therefore I have to change to use something like [Syrupy](https://github.com/jeetsukumaran/Syrupy)? 
Please keep in mind I like to test various brokers that's why I'd like a controllable environment that I can plug various brokers into. 

Would be thankful for any help!

**Comment by ioolkos** [comment]
Hi @NewBermuda I've never used the time command in this fashion, so can't really help.
Can you post an output?
Aren't you essentially measuring startup time/ressources that the Erlang VM takes to boot? Though maybe that's what you want.
Keep us posted.

**Comment by NewBermuda** [comment]
Hi there, thanks for the response

Yeah, sure! This is the time output no matter what the topic load is
```
Command being timed: "timeout 60 vernemq console -noshell -noinput"
	User time (seconds): 0.11
	System time (seconds): 0.07
	Percent of CPU this job got: 49%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.38
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 4080
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 11144
	Voluntary context switches: 235
	Involuntary context switches: 128
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```
It could be very well the case that this is only the resource usage of the start up process.
So basically there is no other way than starting Vernemq, finding the PID, start Apache JMeter and then measure the resource usage of that PID?

**Comment by ioolkos** [comment]
> So basically there is no other way than starting Vernemq, finding the PID, start Apache JMeter and then measure the resource usage of that PID?

I don't know how the `time` command works. I'm not saying it *only* measures boot time, I guess it somehow measures what you want as a total (accounting for multicore system, I suppose?).
Did you have any further insights?

**Comment by NewBermuda** [comment]
Thank you for your input.
In the end I used the sysstat package to measure the resource usage.
Time was not a good option for measuring resource usage of erlang-based software

**Comment by ioolkos** [comment]
@NewBermuda makes sense, thanks for your feedback.
