### ISSUE TITLE
Unable to build on MacOS catalina, bcrypt dependecy linking failed

### ISSUE THREAD

**Issue by blisssan** [vernemq/vernemq#1500]
### Environment

- VerneMQ Version: directly checkedout master
- OS: MacOS Catalina
- Erlang/OTP version (if building from source): Erlang OTP 22
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behavior

sudo make rel,  Build successful

### Actual behaviour

> cat vars.config > vars.generated
echo "{app_version, \"1.10.2-30-g9a328f0\"}." >> vars.generated
/Volumes/Wizard/Library/vernemq/rebar3  release
===> "/Volumes/Wizard/Library/vernemq/_build/default/lib/riak_dt/ebin/riak_dt.app" is missing description entry
===> "/Volumes/Wizard/Library/vernemq/_build/default/lib/riak_dt/ebin/riak_dt.app" is missing description entry
===> Verifying dependencies...
===> "/Volumes/Wizard/Library/vernemq/_build/default/lib/riak_dt/ebin/riak_dt.app" is missing description entry
===> Compiling bcrypt
===> Compiling c_src/async_queue.c
===> Compiling c_src/bcrypt.c
===> Compiling c_src/bcrypt_nif.c
===> Compiling c_src/bcrypt_port.c
===> Compiling c_src/blowfish.c
===> Compiling c_src/bcrypt_port.c
===> Compiling c_src/bcrypt.c
===> Compiling c_src/blowfish.c
===> Linking /Volumes/Wizard/Library/vernemq/_build/default/lib/bcrypt/priv/bcrypt
make: *** [rel] Error 1

I believe its because bcrypt dependency is not compatible with erlang otp 22
I tried running make command inside the bcrypt directory but it fails with the following

> cc  -I/usr/local/Cellar/erlang/22.3.3/lib/erlang/lib/erl_interface-3.13.2/include  bcrypt_port.c bcrypt.o blowfish.o  -L/usr/local/Cellar/erlang/22.3.3/lib/erlang/lib/erl_interface-3.13.2/lib -lpthread -o ../priv/bcrypt
bcrypt_port.c:105:14: warning: 'erl_format' is deprecated [-Wdeprecated-declarations]
    result = erl_format("{~i, ~w, ~s}", cmd, pid, res);
             ^
/usr/local/Cellar/erlang/22.3.3/lib/erlang/lib/erl_interface-3.13.2/include/erl_interface.h:407:32: note: 'erl_format' has been explicitly marked deprecated
      here
ETERM *erl_format(char*, ... ) EI_DEPRECATED_ATTR;
                               ^
/usr/local/Cellar/erlang/22.3.3/lib/erlang/lib/erl_interface-3.13.2/include/ei.h:64:43: note: expanded from macro 'EI_DEPRECATED_ATTR'
#define EI_DEPRECATED_ATTR __attribute__((EI_DEPRECATED_ATTR_NAME))
                                          ^
/usr/local/Cellar/erlang/22.3.3/lib/erlang/lib/erl_interface-3.13.2/include/ei.h:63:33: note: expanded from macro 'EI_DEPRECATED_ATTR_NAME'
#define EI_DEPRECATED_ATTR_NAME deprecated
                                ^
36 warnings generated.
Undefined symbols for architecture x86_64:
  "_erl_decode", referenced from:
      _process_command in bcrypt_port-a2ab16.o
  "_erl_encode", referenced from:
      _process_reply in bcrypt_port-a2ab16.o
  "_erl_format", referenced from:
      _process_command in bcrypt_port-a2ab16.o
      _process_encode_salt in bcrypt_port-a2ab16.o
      _process_hashpw in bcrypt_port-a2ab16.o
      _process_reply in bcrypt_port-a2ab16.o
  "_erl_free", referenced from:
      _process_reply in bcrypt_port-a2ab16.o
  "_erl_free_term", referenced from:
      _process_command in bcrypt_port-a2ab16.o
      _process_encode_salt in bcrypt_port-a2ab16.o
      _process_hashpw in bcrypt_port-a2ab16.o
      _process_reply in bcrypt_port-a2ab16.o
  "_erl_init", referenced from:
      _main in bcrypt_port-a2ab16.o
  "_erl_iolist_to_binary", referenced from:
      _process_hashpw in bcrypt_port-a2ab16.o
  "_erl_malloc", referenced from:
      _process_reply in bcrypt_port-a2ab16.o
  "_erl_match", referenced from:
      _process_command in bcrypt_port-a2ab16.o
      _process_encode_salt in bcrypt_port-a2ab16.o
      _process_hashpw in bcrypt_port-a2ab16.o
  "_erl_term_len", referenced from:
      _process_reply in bcrypt_port-a2ab16.o
  "_erl_var_content", referenced from:
      _process_command in bcrypt_port-a2ab16.o
      _process_encode_salt in bcrypt_port-a2ab16.o
      _process_hashpw in bcrypt_port-a2ab16.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../priv/bcrypt] Error 1

I have cut down the deprecated warning list. here is the full error message
[https://gist.github.com/blisssan/be839e6b5500a00b284b311610028123](https://gist.github.com/blisssan/be839e6b5500a00b284b311610028123)

I added these flags **_-lerl_interface -lei_**
and the error message 

> Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _ei_writev_fill_ctx_t__ in libei.a(ei_portio.o)
      _ei_connect_ctx_t__ in libei.a(ei_portio.o)
      _ei_accept_ctx_t__ in libei.a(ei_portio.o)
      _ei_read_fill_ctx_t__ in libei.a(ei_portio.o)
      _ei_write_fill_ctx_t__ in libei.a(ei_portio.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by blisssan** [comment]
I was able to bypass the error and successfully build the release by going into the **_build/default/lib/bcrypt/c_src** directory and modify the Makefile as follows

first made sure that $ERL_CFLAGS is set to

> I/<erlang path>/lib/erl_interface-<version>/include

and set ERL_LDFALGS to

> -L/<erlang path>/lib/erl_interface-<version>/lib -bundle -flat_namespace -undefined suppress -lerl_interface -lei

after this ran make rel which compiled successfully.
extracted the above information from rebar.config within bcrypt for some reason the rebar failed to set the flags so had to do it manually.

**Comment by codeadict** [comment]
Thanks for the info, I need to upgrade to Catalina to reflect these changes in the makefile. Every new OSX version is a journey :(

**Comment by codeadict** [comment]
@blisssan can you pleae test the master branch again on Catalina?

**Comment by codeadict** [comment]
This is due to an issue in the bcrypt library when you have some LDFLAGS available in your environment, which you definitely need for other things like OpenSSL headers. Submitted a pull request on https://github.com/erlangpack/bcrypt/pull/17. CC @ioolkos
