### ISSUE TITLE
Fatal - Insufficient Security - no_suitable_ciphers

### ISSUE THREAD

**Issue by anpjavatech** [vernemq/vernemq#1501]
Environment

- VerneMQ Version: erlio/docker-vernemq
- OS: Cent OS
- VerneMQ configuration (vernemq.conf) :

accept_eula = yes
allow_anonymous = off
plugins.vmq_diversity = on
plugins.vmq_passwd = off
plugins.vmq_acl = off

vmq_diversity.auth_postgres.enabled = on
vmq_diversity.postgres.ssl = on
vmq_diversity.postgres.cafile = #####/caroot.cer
vmq_diversity.postgres.certfile = ####/client-cert.cer
vmq_diversity.postgres.keyfile = ######/client-key.pem
vmq_diversity.postgres.host = #####-temp.com
vmq_diversity.postgres.port = ####
vmq_diversity.postgres.user = #####
vmq_diversity.postgres.password = #####
vmq_diversity.postgres.database = ######
vmq_diversity.postgres.password_hash_method = #####

listener.ssl.cafile = ###/CA.crt
listener.ssl.certfile = ####/server.crt
listener.ssl.keyfile = ###/server.pem
listener.ssl.default = 0.0.0.0:8883
listener.ssl.tls_version = tlsv1.2
listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on

listener.ssl.max_connections = 10
listener.ssl.allowed_protocol_versions = 3,4
listener.ssl.ciphers = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-DES-CBC3-SHA:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA384:DHE-DSS-AES256-GCM-SHA384:DHE-DSS-AES256-SHA256:AES256-GCM-SHA384:AES256-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-DSS-AES128-SHA256:AES128-GCM-SHA256:AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:ECDH-ECDSA-AES256-SHA:ECDH-RSA-AES256-SHA:AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:ECDH-ECDSA-AES128-SHA:ECDH-RSA-AES128-SHA:AES128-SHA

##listener.ssl.crlfile =

max_message_rate = 2
max_client_id_size = 23
max_message_size = 5000
retry_interval = 620
max_inflight_messages = 0
max_online_messages = 1000
max_offline_messages = 1000
listener.max_connections = 10000
listener.nr_of_acceptors = 10

log.crash = on
log.crash.file = ./log/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.console = file
log.console.level = info
log.console.file = ./log/console.log
log.error.file = ./log/error.log

### Expected behavior

- IoT Device should be able to connect with the mentioned ciphers in the configuration.

### Actual behavior

- I have tested the configuration with Java Paho client and it's successfully connected and was able to publish and subscribe data.
But when we tried to integrate with the IoT device, we are getting an issue on ciphers and was not able to integrate with the device. Adding issue screenshot of the docker log for the same:

![image](https://user-images.githubusercontent.com/6368801/81572322-b0f3e800-93c0-11ea-989d-69e012ce2b0b.png)

**14:09:43.643 [info] TLS server: In state hello at tls_handshake.erl:200 generated SERVER ALERT: Fatal - Insufficient Security - no_suitable_ciphers**

Crash Log:
![image](https://user-images.githubusercontent.com/6368801/81573163-be5da200-93c1-11ea-800d-d3c913de7d9d.png)

Error Log:
![image](https://user-images.githubusercontent.com/6368801/81573324-f1079a80-93c1-11ea-8b9e-c299d748ba15.png)

Can someone help me to understand the issue? Thanks in Advance.

**Comment by anpjavatech** [comment]
To add on to the existing question, please find the cipher list which the device supports

"TLS_RSA_WITH_AES_128_CBC_SHA:TLS_RSA_WITH_AES_128_CBC_SHA256:TLS_RSA_WITH_AES_256_CBC_SHA:TLS_RSA_WITH_AES_256_CBC_SHA256:TLS_RSA_WITH_3DES_EDE_CBC_SHA:TLS_PSK_WITH_AES_128_CBC_SHA:TLS_PSK_WITH_AES_256_CBC_SHA:TLS_PSK_WITH_3DES_EDE_CBC_SHA:TLS_RSA_PSK_WITH_AES_128_CBC_SHA:TLS_RSA_PSK_WITH_AES_256_CBC_SHA:TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA:TLS_PSK_WITH_AES_128_CBC_SHA256:TLS_PSK_WITH_AES_256_CBC_SHA384:TLS_RSA_PSK_WITH_AES_128_CBC_SHA256:TLS_RSA_PSK_WITH_AES_256_CBC_SHA384"

But when I add all these ciphers in vernemq.conf then we are getting an exception as follows:

![image](https://user-images.githubusercontent.com/6368801/81642165-6ade6900-9440-11ea-9128-9d309a1392c7.png)

Any supports are very much appreciated. Thanks in advance.

**Comment by ioolkos** [comment]
@anpjavatech thanks, apologies for asking a formality. It's almost impossible to parse the output as pictures for my eyes, could you post those as quotes normally? just for  future reference, sorry about that & thanks.
Can you gradually reduce the set of ciphers in the VerneMQ listener to see which one is causing issues here?

**Comment by anpjavatech** [comment]
@ioolkos thanks for the response. 
It was actually an issue because of the ca certificate. A new certificate with the expected encryption details helped us to resolve the issue.

Sorry for the bad format while posting details, for future references will definitely use the format which u mentioned.
