### ISSUE TITLE
vernemq build fails on IBM Power LE (ppc64le) architecture

### ISSUE THREAD

**Issue by seth-priya** [vernemq/vernemq#1504]
### Environment

- VerneMQ Version: master
- OS: Ubuntu 18.04, ppc64le
- Erlang/OTP version (if building from source): maint-21
- VerneMQ configuration (vernemq.conf) or the changes from the default None
- Cluster size/standalone: NA

### Expected behavior

Build should succeed

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.
apt-get update -y
apt-get install -y git build-essential libtool autoconf gcc make sed libncurses5-dev libncursesw5-dev libcurl4-openssl-dev xsltproc fop openssl libxml2-utils python-wxgtk3.0 python-wxgtk3.0-dev openssl libssl-dev default-jre default-jdk g++ python-wxgtk-media3.0 unixodbc-dev libwxgtk3.0-dev default-jdk libutil-freebsd-dev

git clone -b maint-21 https://github.com/erlang/otp.git
cd otp
./otp_build autoconf
./configure
make
make install

git clone https://github.com/vernemq/vernemq
cd vernemq/
make rel

The build is failing with the below error
./port/atomic_pointer.h:143:2: error: #error Please implement AtomicPointer for this platform.
#error Please implement AtomicPointer for this platform.
  ^~~~~
Makefile:190: recipe for target 'db/db_iter.o' failed
make[1]: *** [db/db_iter.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from db/db_impl.cc:5:0:
./db/db_impl.h:169:9: error: 'AtomicPointer' in namespace 'leveldb::port' does not name a type
   port::AtomicPointer shutting_down_;
         ^~~~~~~~~~~~~
./db/db_impl.h:174:9: error: 'AtomicPointer' in namespace 'leveldb::port' does not name a type
   port::AtomicPointer has_imm_;  // So bg thread can detect non-NULL imm_
         ^~~~~~~~~~~~~
In file included from ./db/memtable.h:11:0,
                 from db/db_impl.cc:24:
./db/skiplist.h:125:9: error: 'AtomicPointer' in namespace 'leveldb::port' does not name a type
   port::AtomicPointer max_height_;   // Height of the entire list
         ^~~~~~~~~~~~~
./db/skiplist.h: In member function 'int leveldb::SkipList<Key, Comparator>::GetMaxHeight() const':
./db/skiplist.h:129:36: error: 'max_height_' was not declared in this scope
         reinterpret_cast<intptr_t>(max_height_.NoBarrier_Load()));
                                    ^~~~~~~~~~~
./db/skiplist.h:129:36: note: suggested alternative: 'tailHeight_'
         reinterpret_cast<intptr_t>(max_height_.NoBarrier_Load()));
                                    ^~~~~~~~~~~
                                    tailHeight_
./db/skiplist.h: At global scope:
./db/skiplist.h:213:9: error: 'AtomicPointer' in namespace 'leveldb::port' does not name a type
   port::AtomicPointer next_[1];
         ^~~~~~~~~~~~~
./db/skiplist.h: In member function 'leveldb::SkipList<Key, Comparator>::Node* leveldb::SkipList<Key, Comparator>::Node::Next(int)':
./db/skiplist.h:192:36: error: 'next_' was not declared in this scope
     return reinterpret_cast<Node*>(next_[n].Acquire_Load());
                                    ^~~~~
./db/skiplist.h:192:36: note: suggested alternative: 'Next'
     return reinterpret_cast<Node*>(next_[n].Acquire_Load());
                                    ^~~~~
                                    Next
./db/skiplist.h: In member function 'void leveldb::SkipList<Key, Comparator>::Node::SetNext(int, leveldb::SkipList<Key, Comparator>::Node*)':
./db/skiplist.h:198:5: error: 'next_' was not declared in this scope
     next_[n].Release_Store(x);
     ^~~~~
./db/skiplist.h:198:5: note: suggested alternative: 'Next'
     next_[n].Release_Store(x);
     ^~~~~
     Next
./db/skiplist.h: In member function 'leveldb::SkipList<Key, Comparator>::Node* leveldb::SkipList<Key, Comparator>::Node::NoBarrier_Next(int)':
./db/skiplist.h:204:36: error: 'next_' was not declared in this scope
     return reinterpret_cast<Node*>(next_[n].NoBarrier_Load());
                                    ^~~~~
./db/skiplist.h:204:36: note: suggested alternative: 'Next'
     return reinterpret_cast<Node*>(next_[n].NoBarrier_Load());
                                    ^~~~~
                                    Next
./db/skiplist.h: In member function 'void leveldb::SkipList<Key, Comparator>::Node::NoBarrier_SetNext(int, leveldb::SkipList<Key, Comparator>::Node*)':
./db/skiplist.h:208:5: error: 'next_' was not declared in this scope
     next_[n].NoBarrier_Store(x);
     ^~~~~
./db/skiplist.h:208:5: note: suggested alternative: 'Next'
     next_[n].NoBarrier_Store(x);
     ^~~~~
     Next
./db/skiplist.h: In member function 'leveldb::SkipList<Key, Comparator>::Node* leveldb::SkipList<Key, Comparator>::NewNode(const Key&, int)':
./db/skiplist.h:220:35: error: 'AtomicPointer' is not a member of 'leveldb::port'
       sizeof(Node) + sizeof(port::AtomicPointer) * (height - 1));
                                   ^~~~~~~~~~~~~
./db/skiplist.h: In constructor 'leveldb::SkipList<Key, Comparator>::SkipList(Comparator, leveldb::Arena*)':
./db/skiplist.h:411:7: error: class 'leveldb::SkipList<Key, Comparator>' does not have any field named 'max_height_'
       max_height_(reinterpret_cast<void*>(1)),
       ^~~~~~~~~~~
./db/skiplist.h: In member function 'void leveldb::SkipList<Key, Comparator>::Insert(const Key&)':
./db/skiplist.h:458:5: error: 'max_height_' was not declared in this scope
     max_height_.NoBarrier_Store(reinterpret_cast<void*>(height));
     ^~~~~~~~~~~
./db/skiplist.h:458:5: note: suggested alternative: 'tailHeight_'
     max_height_.NoBarrier_Store(reinterpret_cast<void*>(height));
     ^~~~~~~~~~~
     tailHeight_
Makefile:190: recipe for target 'db/builder.o' failed
make[1]: *** [db/builder.o] Error 1
db/db_impl.cc: In constructor 'leveldb::DBImpl::DBImpl(const leveldb::Options&, const string&)':
db/db_impl.cc:187:7: error: class 'leveldb::DBImpl' does not have any field named 'shutting_down_'
       shutting_down_(NULL),
       ^~~~~~~~~~~~~~
db/db_impl.cc:204:3: error: 'has_imm_' was not declared in this scope
   has_imm_.Release_Store(NULL);
   ^~~~~~~~
db/db_impl.cc:204:3: note: suggested alternative: 'imm_'
   has_imm_.Release_Store(NULL);
   ^~~~~~~~
   imm_
db/db_impl.cc: In destructor 'virtual leveldb::DBImpl::~DBImpl()':
db/db_impl.cc:229:3: error: 'shutting_down_' was not declared in this scope
   shutting_down_.Release_Store(this);  // Any non-NULL value is ok
   ^~~~~~~~~~~~~~
db/db_impl.cc: In member function 'leveldb::Status leveldb::DBImpl::WriteLevel0Table(volatile leveldb::MemTable*, leveldb::VersionEdit*, leveldb::Version*)':
db/db_impl.cc:792:17: error: 'shutting_down_' was not declared in this scope
   if (s.ok() && shutting_down_.Acquire_Load()) {
                 ^~~~~~~~~~~~~~
db/db_impl.cc: In member function 'leveldb::Status leveldb::DBImpl::CompactMemTable()':
db/db_impl.cc:810:17: error: 'shutting_down_' was not declared in this scope
   if (s.ok() && shutting_down_.Acquire_Load()) {
                 ^~~~~~~~~~~~~~
db/db_impl.cc:825:5: error: 'has_imm_' was not declared in this scope
     has_imm_.Release_Store(NULL);
     ^~~~~~~~
db/db_impl.cc:825:5: note: suggested alternative: 'imm_'
     has_imm_.Release_Store(NULL);
     ^~~~~~~~
     imm_
db/db_impl.cc: In member function 'void leveldb::DBImpl::MaybeScheduleCompaction()':
db/db_impl.cc:913:8: error: 'shutting_down_' was not declared in this scope
   if (!shutting_down_.Acquire_Load())
        ^~~~~~~~~~~~~~
db/db_impl.cc: In member function 'void leveldb::DBImpl::BackgroundCall2(leveldb::Compaction*)':
db/db_impl.cc:957:8: error: 'shutting_down_' was not declared in this scope
   if (!shutting_down_.Acquire_Load()) {
        ^~~~~~~~~~~~~~
db/db_impl.cc: In member function 'void leveldb::DBImpl::BackgroundImmCompactCall()':
db/db_impl.cc:1014:8: error: 'shutting_down_' was not declared in this scope
   if (!shutting_down_.Acquire_Load()) {
        ^~~~~~~~~~~~~~
db/db_impl.cc:1038:7: error: 'shutting_down_' was not declared in this scope
   if (shutting_down_.Acquire_Load()) {
       ^~~~~~~~~~~~~~
db/db_impl.cc:1044:5: error: 'has_imm_' was not declared in this scope
     has_imm_.Release_Store(NULL);
     ^~~~~~~~
db/db_impl.cc:1044:5: note: suggested alternative: 'imm_'
     has_imm_.Release_Store(NULL);
     ^~~~~~~~
     imm_
db/db_impl.cc: In member function 'leveldb::Status leveldb::DBImpl::BackgroundCompaction(leveldb::Compaction*)':
db/db_impl.cc:1144:14: error: 'shutting_down_' was not declared in this scope
   } else if (shutting_down_.Acquire_Load()) {
              ^~~~~~~~~~~~~~
db/db_impl.cc: In member function 'leveldb::Status leveldb::DBImpl::DoCompactionWork(leveldb::DBImpl::CompactionState*)':
db/db_impl.cc:1551:29: error: 'shutting_down_' was not declared in this scope
   for (; input->Valid() && !shutting_down_.Acquire_Load(); )
                             ^~~~~~~~~~~~~~
db/db_impl.cc:1593:22: error: 'shutting_down_' was not declared in this scope
   if (status.ok() && shutting_down_.Acquire_Load()) {
                      ^~~~~~~~~~~~~~
db/db_impl.cc: In member function 'leveldb::Status leveldb::DBImpl::MakeRoomForWrite(bool)':
db/db_impl.cc:2020:12: error: 'shutting_down_' was not declared in this scope
       if (!shutting_down_.Acquire_Load())
            ^~~~~~~~~~~~~~
db/db_impl.cc:2028:12: error: 'shutting_down_' was not declared in this scope
       if (!shutting_down_.Acquire_Load())
            ^~~~~~~~~~~~~~
db/db_impl.cc:2046:7: error: 'has_imm_' was not declared in this scope
       has_imm_.Release_Store((MemTable*)imm_);
       ^~~~~~~~
db/db_impl.cc:2046:7: note: suggested alternative: 'imm_'
       has_imm_.Release_Store((MemTable*)imm_);
       ^~~~~~~~
       imm_
Makefile:190: recipe for target 'db/db_impl.o' failed
make[1]: *** [db/db_impl.o] Error 1
make[1]: Leaving directory '/vernemq/_build/default/lib/eleveldb/c_src/leveldb'
===> Hook for compile failed!
Makefile:24: recipe for target 'rel' failed
make: *** [rel] Error 1

**Comment by seth-priya** [comment]
I understand that vernemq uses vernemq/eleveldb which in turn are the Erlang APIs for https://github.com/basho/leveldb. The build for both vernemq/eleveldb and basho/leveldb fail with errors similar to above. So essentially, the issue originates from the basho/leveldb, which is a clone of google/leveldb and does not look like it is maintained actively.

Note that google/leveldb is ported and builds (and all community tests pass) on ppc64le and specifically the above error may have been fixed by https://github.com/google/leveldb/commit/7d8e41e49b8fddda66a2c5f0a6a47f1a916e8d26#diff-901555fb06e346cb065ceb9808dcfc25

Just trying to understand what are the alternatives if in case we want to make vernemq work on Power?

**Comment by codeadict** [comment]
There is experimental work being done in https://github.com/vernemq/vernemq/tree/feature-rocksdb-messagestore to support alternative storage backends, in this case RocksDB. You may compile that branch with `make with_rocksdb`, some configurations are still needing the advance.config file as described on https://github.com/vernemq/vernemq/blob/feature-rocksdb-messagestore/apps/vmq_generic_msg_store/README.md. Note this is something not recommended for production scenarios yet but you may be helping a lot by testing on that architecture, the goal is to provide support for more architectures and OSes on upcoming versions.

**Comment by seth-priya** [comment]
thanks @codeadict sound like that would be great! I'll give that a try and get back soon, also looks like there is an open PR that add multi arch support to basho/leveldb at https://github.com/basho/leveldb/pull/235 but looks like there has not been much activity in that community recently.

**Comment by seth-priya** [comment]
@codeadict I did try the new branch with the make with_rocksdb command, however, build fails with the same error, will check more, maybe I am missing something?

git clone  https://github.com/vernemq/vernemq --branch=feature-rocksdb-messagestore
cd vernemq/
make with_rocksdb

db/db_impl.cc:2020:12: error: 'shutting_down_' was not declared in this scope
       if (!shutting_down_.Acquire_Load())
            ^~~~~~~~~~~~~~
db/db_impl.cc:2028:12: error: 'shutting_down_' was not declared in this scope
       if (!shutting_down_.Acquire_Load())
            ^~~~~~~~~~~~~~
db/db_impl.cc:2046:7: error: 'has_imm_' was not declared in this scope
       has_imm_.Release_Store((MemTable*)imm_);
       ^~~~~~~~
db/db_impl.cc:2046:7: note: suggested alternative: 'imm_'
       has_imm_.Release_Store((MemTable*)imm_);
       ^~~~~~~~
       imm_
Makefile:190: recipe for target 'db/db_impl.o' failed
make[1]: *** [db/db_impl.o] Error 1
make[1]: Leaving directory '/root/new-branch/vernemq/_build/default/lib/eleveldb/c_src/leveldb'
===> Hook for compile failed!

Makefile:29: recipe for target 'rel' failed
make: *** [rel] Error 1
root@6702f1063b66:~/new-branch/vernemq# git branch
* feature-rocksdb-messagestore

**Comment by codeadict** [comment]
Ahh I guess it still compiles the leveldb dependency, we need to change that

**Comment by ioolkos** [comment]
Yep, it has to do with the way Verne is building a release, because it's first building a 'default' release and then linking project dependencies.
I was thinking I managed to delete all traces of LevelDB but obviously not ;)

**Comment by seth-priya** [comment]
@codeadict , @ioolkos thanks for the additional information, would patching eleveldb in the short term be an option to work around the issues, I have something here that works https://github.com/vernemq/eleveldb/compare/develop...seth-priya:develop

All the tests are passing for me now, except one related to redis which I am trying to debug,


The current results are

 
EXPERIMENTAL: Writing retry specification at /home/travis/vernemq-seth-priya/vernemq/_build/all_tests+test/logs/retry.spec
              call rebar3 ct with '--retry' to re-run failing cases.
Failed 1 tests. Skipped 8 (8, 0) tests. Passed 392 tests.
Results written to "/home/travis/vernemq-seth-priya/vernemq/_build/all_tests+test/logs/index.html".
===> Failures occurred running tests: 1
 
The last failure is related to redis (redis-server is already installed and running)

 %%% vmq_diversity_provider_SUITE ==> {{badmatch,
     {error,
         {{{badmatch,
               {error,
                   {normal,
                       {child,undefined,
                           {vmq_diversity_script_state,1},
                           {vmq_diversity_script_state,start_link,
                               [1,
                                "/home/travis/vernemq-seth-priya/vernemq/_build/all_tests+test/lib/vmq_diversity/test/redis_test.lua",
                                <0.23978.0>]},
                           permanent,5000,worker,
                           [vmq_diversity_script_state]}}}},
           [{vmq_diversity_script,setup_lua_states,3,
                [{file,
                     "/home/travis/vernemq-seth-priya/vernemq/apps/vmq_diversity/src/vmq_diversity_script.erl"},
                 {line,254}]},
            {vmq_diversity_script,init,1,
                [{file,
                     "/home/travis/vernemq-seth-priya/vernemq/apps/vmq_diversity/src/vmq_diversity_script.erl"},
                 {line,93}]},
            {gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},
            {gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},
          {child,undefined,
              {vmq_diversity_script,
                  "/home/travis/vernemq-seth-priya/vernemq/_build/all_tests+test/lib/vmq_diversity/test/redis_test.lua"},
              {vmq_diversity_script,start_link,
                  ["/home/travis/vernemq-seth-priya/vernemq/_build/all_tests+test/lib/vmq_diversity/test/redis_test.lua"]},
              permanent,5000,worker,
              [vmq_diversity_script]}}}},
[{vmq_diversity_provider_SUITE,redis_test,1,
      [{file,
           "/home/travis/vernemq-seth-priya/vernemq/apps/vmq_diversity/test/vmq_diversity_provider_SUITE.erl"},
       {line,101}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1545}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1063}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,995}]}]}

**Comment by ioolkos** [comment]
@seth-priya thanks! what is the patch to LevelDB doing, essentially? Obviously the main concern here is to not break the build on other systems.

I haven't seen the redis-test fail like that, I think. Would need to look into it.

**Comment by seth-priya** [comment]
@ioolkos thanks and yes I understand the concern. At this point, I am essentially re-using a patch from a PR that is already open in the basho/leveldb community, but if you are generally fine with the idea of patching eleveldb, I will work on refining it and make it more specific to Power and then minimally test it out on Intel and ensure the Travis job succeeds, do let me know if any additional testing would be needed.

On the redis failure, I found that the redis-sever was actually not running in my container (though it did not complain at startup time) because IPv6 is disabled, I worked around the issue for now and though the server is now running the test still fails, I am debugging it more on this side ..

Thank you!

**Comment by seth-priya** [comment]
I am seeing the redis failure even on Intel, is there any special configuration, setup, steps required to be followed?

**Comment by ioolkos** [comment]
@seth-priya thanks for your testing! it's not immediately clear to me what why the Redis test fails.

**Comment by ioolkos** [comment]
Just for reference, there was a patch for ARM64 here. I don't think this is merged. https://github.com/dergraf/eleveldb/commit/44c41a2c8e4a6c453b407d00e6a0eb2b3db9b72a

Maybe useful for comparison.

**Comment by seth-priya** [comment]
@ioolkos yes, thanks - I have been referring to this patch as well. The one issue that I am looking at currently is that one leveldb test case fails on Power. I want to be sure that all automated tests pass for leveldb, eleveldb and vernemq or are atleast consistent with/without changes on both Intel and Power before a submit a PR.

Thanks for the pointer, though!!

**Comment by ioolkos** [comment]
Oh, okay, thanks. I haven't yet had the time to look into your patch. Is some LevelDb related test failing, or still the Redis one?

**Comment by seth-priya** [comment]
The redis one is still there and is reproducible on Intel, so its likely that I am missing some configuration or such. 

Besides this one there is one leveldb test failure i.e. one of the automated tests in basho/leveldb fail with my patch on Power
db/skiplist_test.cc:273: Assertion failure (gen(pos) == 0) || (gen(pos) > initial_state.Get(key(pos))) key:  3 ; gen:  1 ; initgen:  72
This is with the latest patch that I have and it does pass on Intel

**Comment by seth-priya** [comment]
@ioolkos  @codeadict just a quick update, the leveldb failure on Power is resolved with this patch that I pushed for review and acceptance today
https://github.com/basho/leveldb/pull/238
Basically, the build and all tests pass for basho/leveldb pass with this change

I was able to use this here https://github.com/seth-priya/eleveldb
to confirm that the build and tests for eleveldb pass for Power as well with the above change.

No further changes are needed besides this to get vernemq build and automated tests working as per the testing I have done so far.

**Comment by codeadict** [comment]
Does this fixes ARM as well right?

**Comment by ioolkos** [comment]
@seth-priya great to see. So, if I understand correctly, VerneMQ builds for you with both patches on LevelDB and eleveldb applied.

**Comment by seth-priya** [comment]
@ioolkos yes that is correct
@codeadict - no, this fix is only for ppc64le, I don't have an ARM test environment.

**Comment by seth-priya** [comment]
@ioolkos @codeadict there does not seem to be much activity on the basho/leveldb community and hence I have raised the above PR to eleveldb, could you please take a look as per your convenience and let me know if it would be acceptable or if you have other suggestions? Thanks in advance!

**Comment by ioolkos** [comment]
@seth-priya allright, thanks for raising a PR on the repo here. I'll see I can look into it soon.

**Comment by seth-priya** [comment]
Fixed with https://github.com/vernemq/eleveldb/pull/6, thanks @ioolkos @codeadict for your guidance and review!
