### ISSUE TITLE
Allow multiple bridges to the same IP:Port endpoint

### ISSUE THREAD

**Issue by ioolkos** [vernemq/vernemq#1505]
We stupidly identify bridges by their IP/Port combination at the other broker. This means that you have to open an extra listener on the remote broker when you want to set up multiple bridges to the same remote broker. (let's say for concurrency reason).
For instance, you can't configure 2 outgoing bridges like this:
```
vmq_bridge.ssl.sbr0 = 127.0.0.1:1889
vmq_bridge.ssl.sbr1 = 127.0.0.1:1889
```
OTOH, the extra listener could be used for adapted TCP buffer configuration.

**Comment by codeadict** [comment]
What is the idea here? The identifier to be `sbr0`, `sbr0` and allow them to use the same ip:port?

**Comment by ioolkos** [comment]
Yes, the bridge name is probably the best identifier. I was just wondering why this shouldn't be possible, and I think it should be. (Mosquitto allows configs like this without problem). I don't see this as urgent though, just wanted to document it.
