### ISSUE TITLE
Webhook name in the vmq-admin webhook/show GET API response

### ISSUE THREAD

**Issue by narioinc** [vernemq/vernemq#1507]
### Environment

- VerneMQ Version: 1.10
- OS: Ubuntu 18/.04
- Erlang/OTP version (if building from source): N/A (Using binaries)
- Cluster size/standalone: standalone

Hi Team,

First, I would like to like to share my humble appreciation to the vernemq team for putting together such a wonderful project and bringing enterprise grade mqtt broker to the masses.

I am currently working on a totally open source version of a vernemq admin UI app here:
https://github.com/narioinc/vmqadmin-ui ( took this up as a fun work during quarantine :) )

One of the features that I am trying to integrate is registering webhooks either runtime (vmq-admin) or persistent (allowing permanent addition to vernemq.conf)

While approaching this feature I found there to a small issue that I though the team could enhance in the vmqadmin-api.

**ISSUE**
When I allow the editing of the vernmq.conf file in my UI app, the conf file expects a webhook name when declaring the webhook. for e.g. vmq_webhooks.**mywebhook1**.hook
However when vmqadmin returns a list of webhooks, it does so without specifying the name of the webhooks in the response, and now if this GET request is used to create a page in angular/react, I don't have an idea which webhook params belongs to which weebhook name and hence operation like editing, deleting webhooks becomes ambiguous

For example
if vernemq.conf file has two webhooks like this
```
vmq_webhooks.mywebhook1.hook=on_publish
vmq_webhooks.mywebhook1.endpoint=http://localhost:7777/webhooks/test1
vmq_webhooks.mywebhook2.hook=on_auth_m5
vmq_webhooks.mywebhook2.endpoint=http://localhost12
```

then the vmqadmin REST api give back this

```
({
    "table": [
        {
            "hook": "on_publish",
            "endpoint": "http://localhost:7777/webhooks/test1",
            "base64payload": true,
            "response_timeout": 5000
        },
        {
            "hook": "on_publish",
            "endpoint": "http://localhost:7777/webhooks/test2",
            "base64payload": true,
            "response_timeout": 5000
        }
    ],
    "type": "table"
})
```

Now because I don't know which webhook name these configs are present against, other CRUD operation get affected.

### Expected behavior

I can handle this association outside of the vmqadmin API (by storing it in the sq-lite db i hold in my app) but I was thinking that can the vmq-admin API also return the webhook name as stored in the conf file if possible

**Comment by ioolkos** [comment]
@narioinc thanks for your nice feedback & wow, great project! :) (btw do you have some Quickstart guide for it, so that I can check it out?)

Ok, so this is basically about returning the webhookname in vmq-admin and the HTTP API. Quick question: could the WebHook endpoint be used as the primary key for uniqueness?

I'll have to check how the webhookname can be added (best case without breaking existing Webhook plugins).

**Comment by narioinc** [comment]
hi @ioolkos 

I am happy (and humbled :) !! ) to have got the attention from the vernemq team !!. My project will soon be getting its docker images and kubernetes deployment yamls (which are already in progress)
Let me update the readme update to some getting started guides (localhost-based) today !!

regarding the uniqueness of the webhooks entries, its a coincidence that I also started looking at the idea of just using the combination of hook and endpoint as 'sort-of' composite key and then determine which entries to remove. I have updated my express local API service with this implementation and mostly seems to work as expected. 

I think I can get away with just the URL as the key, because I dont think anyone will have the same URL for different hooks (the payload doesn't differentiate the hook for which it was intended for)

**Comment by narioinc** [comment]
@ioolkos 

Also, I was mindful of the fact that the vmq-admin Rest APIs (on which my app integration depends on) can always change and will strive to keep the integration with my project as up-to-date as possible !! 
I would love to hear any suggestion in this regard and critical code review from the team. 

(I am currently also addressing some security issues as I ran sonar code scan and the code will undergo some big changes in the coming weeks to address these and much needed code comments :) !! )

**Comment by narioinc** [comment]
Closing this issue as the webhook URL and hook provide the opportunity to create a composite key to avoid ambiguity while adding and removing webhooks in vernemq.conf file
