### ISSUE TITLE
Build on Erlang/OTP 23

### ISSUE THREAD

**Issue by codeadict** [vernemq/vernemq#1511]
Add support for Building in Erlang/OTP 23. Some users using Homebrew and OSX will soon have erlang upgraded in their system and we should make VerneMQ compile on OTP so a lot of support tickets don't flow here, also we can always benefit from some of the new improvements. 

Fist task for this will be https://github.com/vernemq/vernemq/issues/1506 and others may need to follow, creating this ticket to track the whole process.

**Comment by ioolkos** [comment]
- [x] https://github.com/vernemq/plumtree/pull/26

**Comment by codeadict** [comment]
- [ ] Fix compilation of `bcrypt` which uses deprecated `erl_interface.h`. Filed a ticket on https://github.com/erlangpack/bcrypt/issues/9 and working on submitting a fix for it.
