### ISSUE TITLE
Offline messages don't get delivered when using direct_plugin_exports

### ISSUE THREAD

**Issue by rbino** [vernemq/vernemq#1516]
### Environment

- VerneMQ Version: 1.10.2-1
- OS: Debian Bullseye (VerneMQ was running inside docker)
- VerneMQ configuration (vernemq.conf) or the changes from the default: default docker image launched with
```
docker run -p 1883:1883 -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d vernemq/vernemq:1.10.2-1 
```

### Expected behavior

Publishing with `direct_plugin_exports` functions using QoS 2 should deliver messages to offline clients that have a persistent session when they reconnect.

### Actual behaviour

Offline messages don't get delivered when they're published from `direct_plugin_exports`.

### Steps to reproduce

- Launch a clean vernemq instance with
```
docker run -p 1883:1883 -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d vernemq/vernemq:1.10.2-1 
```
- Connect to the vernemq shell and obtain direct plugin exports. Then, call `RegisterFun`.
```
$ docker exec -it vernemq1 /bin/bash
vernemq@6bd9cd3a771b:~$ ./bin/vernemq attach
Remote Shell: Use "Ctrl-G q" to quit.
q() or init:stop() will terminate the vernemq node.
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.6  (abort with ^G)
(VerneMQ@172.17.0.2)1> {RegFun, PubFun, _} = vmq_reg:direct_plugin_exports(myplugin).
{#Fun<vmq_reg.17.87141211>,#Fun<vmq_reg.18.87141211>,
 {#Fun<vmq_reg.19.87141211>,#Fun<vmq_reg.20.87141211>}}
(VerneMQ@172.17.0.2)2> RegFun().
ok
```

- Subscribe a client with a persistent session and debug messages using `mosquitto_sub`:
```bash
$ mosquitto_sub -c -i subclient -t "foo" -q 2 -d
Client subclient sending CONNECT
Client subclient received CONNACK (0)
Client subclient sending SUBSCRIBE (Mid: 1, Topic: foo, QoS: 2, Options: 0x00)
Client subclient received SUBACK
Subscribed (mid: 1): 2
```

- In the VerneMQ shell, publish a message with QoS 2 using PublishFun:
```bash
(VerneMQ@172.17.0.2)3> PubFun([<<"foo">>], <<"hi from direct">>, #{qos => 2}).
{ok,{1,0}}
```

The return value indicates that one local match is present and the client correctly receives the message with QoS 2:
```bash
Client subclient sending PINGREQ
Client subclient received PINGRESP
Client subclient received PUBLISH (d0, q2, r0, m1, 'foo', ... (14 bytes))
Client subclient sending PUBREC (m1, rc0)
Client subclient received PUBREL (Mid: 1)
Client subclient sending PUBCOMP (m1)
hi from direct
```

- Publish a message with QoS 2 using `mosquitto_pub`:
```bash
$ mosquitto_pub -t "foo" -m "hello from the outside" -q 2 -d
Client mosq-RUX5vAgtJuxBHVpC0M sending CONNECT
Client mosq-RUX5vAgtJuxBHVpC0M received CONNACK (0)
Client mosq-RUX5vAgtJuxBHVpC0M sending PUBLISH (d0, q2, r0, m1, 'foo', ... (22 bytes))
Client mosq-RUX5vAgtJuxBHVpC0M received PUBREC (Mid: 1)
Client mosq-RUX5vAgtJuxBHVpC0M sending PUBREL (m1)
Client mosq-RUX5vAgtJuxBHVpC0M received PUBCOMP (Mid: 1, RC:0)
Client mosq-RUX5vAgtJuxBHVpC0M sending DISCONNECT
```

Again, the client correctly receives the message:
```bash
Client subclient sending PINGREQ
Client subclient received PINGRESP
Client subclient received PUBLISH (d0, q2, r0, m2, 'foo', ... (22 bytes))
Client subclient sending PUBREC (m2, rc0)
Client subclient received PUBREL (Mid: 2)
Client subclient sending PUBCOMP (m2)
hello from the outside
```

- Disconnect the sub client (Ctrl-c in the `mosquitto_sub` terminal)
- In the VerneMQ shell, publish another message with QoS 2 using PublishFun:
```
(VerneMQ@172.17.0.2)4> PubFun([<<"foo">>], <<"hi from direct, you're away">>, #{qos => 2}).
{ok,{1,0}}
```

The return value is still 1, so the message should get redelivered when the device reconnects.

- Publish another message with QoS 2 using `mosquitto_pub`:
```bash
$ mosquitto_pub -t "foo" -m "hello from the outside, you're offline" -q 2 -d
Client mosq-4maEpntjBpqcvUAW3E sending CONNECT
Client mosq-4maEpntjBpqcvUAW3E received CONNACK (0)
Client mosq-4maEpntjBpqcvUAW3E sending PUBLISH (d0, q2, r0, m1, 'foo', ... (38 bytes))
Client mosq-4maEpntjBpqcvUAW3E received PUBREC (Mid: 1)
Client mosq-4maEpntjBpqcvUAW3E sending PUBREL (m1)
Client mosq-4maEpntjBpqcvUAW3E received PUBCOMP (Mid: 1, RC:0)
Client mosq-4maEpntjBpqcvUAW3E sending DISCONNECT
```

- Reconnect the subscriber:
```bash
$ mosquitto_sub -c -i subclient -t "foo" -q 2 -d
Client subclient sending CONNECT
Client subclient received CONNACK (0)
Client subclient sending SUBSCRIBE (Mid: 1, Topic: foo, QoS: 2, Options: 0x00)
Client subclient received SUBACK
Subscribed (mid: 1): 2
Client subclient received PUBLISH (d0, q2, r0, m3, 'foo', ... (38 bytes))
Client subclient sending PUBREC (m3, rc0)
Client subclient received PUBREL (Mid: 3)
Client subclient sending PUBCOMP (m3)
hello from the outside, you're offline
```

As you can see only the message that was published from `mosquitto_pub` gets redelivered, while the one that was published using `direct_plugin_exports` gets lost.

**Comment by ioolkos** [comment]
Hi @rbino yes, that's currently expected, as the direct plugin exports do not behave like fat MQTT clients. Taking the SubscribeFun as an example, you see that a couple of MQTT flags are decided at compile time in vmq_reg:
https://github.com/vernemq/vernemq/blob/9a328f053b7ee0d8e3fe4aadf9629d0fed2ea567/apps/vmq_server/src/vmq_reg.erl#L806
For a given topic, it's just ensured that there is a subscription (with QoS 0, there you go).

I think it was always the idea, that one could have multiple 'register' modules, optimised for different load scenarios. (but only vmq_reg was ever developed).

Whether the behaviour of the direct plugin exports is a design flaw or not... well, arguably :)

**Comment by ioolkos** [comment]
I guess what you could do is copy paste the vmq_reg, create a vmq_reg2, and adapt the plugin export funs, and then configure your plugin to use that module and those functions.

**Comment by rbino** [comment]
@ioolkos I see that some parameters are initialized at compile-time, but after some investigation I think that what's happening here is that PublishFun is not reading the correct options after https://github.com/vernemq/vernemq/pull/1302.

I've opened https://github.com/vernemq/vernemq/pull/1518 and I verified that with that the publish effectively goes through even to offline devices
