### ISSUE TITLE
Messages being queued

### ISSUE THREAD

**Issue by gloffreda** [vernemq/vernemq#1528]
Hi there

I just setup a new cluster that handles around 400msgs/minute and looking at status page got it:

![image](https://user-images.githubusercontent.com/8357905/83652247-c8259000-a590-11ea-91e8-03ea78865a57.png)

Msgs Queued is growing very slow, but never seen it before.
Is there a way to understand why some messages are being queued ?

Thanks

**Comment by ioolkos** [comment]
@gloffreda look at the Javascript to see the definition of Msg Queued.
Maybe it's your 2 persistent sessions getting some messages in their offline queues?

**Comment by gloffreda** [comment]
Hi @ioolkos interesting. Didn't realize the JS before. Thanks
Is there a way to get who are those in offline status ?
The number of queued messages is growing and I'm afraid it will take, eventually, all resources if not stoped.
Thanks

**Comment by ioolkos** [comment]
`sudo vmq-admin session show --help`

**Comment by gloffreda** [comment]
Awesome @ioolkos thanks.
I'm dealing with something new then. 
We have a topic named /downstream. 
On version 1.9.2 single node it works normally. No message enqueued when publishing on same topic /downstream
The message is well delivered to client which is subscribed on it.

On version 1.10.1, using single cluster or 3 nodes as image above, every single publish on /downstream generates 4 Msgs Queued.

Even thought, the message is well delivered to client which is subscribed on it too.

The number of queued messages grows by 4 every time a pub is made on that topic.

At first, I suspected about slash, but for my surprise I can sub/pub in any topic name as /topic /down /stream or any other "name" after slash and message is delivered without increasing the Msgs Queued

Anything about /downstream topic ? 
Why messages are queued AND delivered ?

If you need to investigate the case I can supply all access as this server is under test yet.

Thanks

**Comment by ioolkos** [comment]
`sudo vmq-admin session show --client_id --offline_messages --topic --qos --statename --clean_session`

**Comment by gloffreda** [comment]
Hi @ioolkos 

Don't know if I'm still doing or reading something wrong, but here we go

Momentum Zero
![image](https://user-images.githubusercontent.com/8357905/83881837-a0146900-a717-11ea-8825-214c24d81bf9.png)

![image](https://user-images.githubusercontent.com/8357905/83881899-b7535680-a717-11ea-9a97-218fd1f6d2c7.png)

Sub:
`mosquitto_sub -h myserver -u "usertest" -t "/downstream"  -i test-queued-msgs -q 2 -c`
![image](https://user-images.githubusercontent.com/8357905/83882443-8162a200-a718-11ea-97ea-550664623d84.png)

Pub:
`mosquitto_pub -h myserver -u "usertest" -t "/downstream" -m "teste" -i test-pub-queued  -c -q 2`
![image](https://user-images.githubusercontent.com/8357905/83885820-40b95780-a71d-11ea-8476-0bfaae8cfa80.png)
Everything looks fine, no messages queued and went well to subscriber.

Then, subscriber went offline
![image](https://user-images.githubusercontent.com/8357905/83886468-7b22f480-a71d-11ea-80e0-d58e8c479db2.png)

Pub:
`mosquitto_pub -h myserver -u "usertest" -t "/downstream" -m "teste" -i test-pub-queued  -c -q 2`

![image](https://user-images.githubusercontent.com/8357905/83886653-c0472680-a71d-11ea-9a54-f5d113da04a4.png)


![image](https://user-images.githubusercontent.com/8357905/83886616-b0c7dd80-a71d-11ea-97a2-3de1968c0bba.png)

All good. message was successfully enqueued.

Sub become online again:
`mosquitto_sub -h myserver -u "usertest" -t "/downstream"  -i test-queued-msgs -q 2 -c`
![image](https://user-images.githubusercontent.com/8357905/83886759-ea004d80-a71d-11ea-8896-1b4bc08b5629.png)

![image](https://user-images.githubusercontent.com/8357905/83886877-0bf9d000-a71e-11ea-9947-12a5f716a293.png)

Perfect ! The queued was cleaned and subscriber well received the offline message.

Then, subscriber went offline again:
![image](https://user-images.githubusercontent.com/8357905/83887082-4d8a7b00-a71e-11ea-8fb8-dddf396a8736.png)

**Here the magic happens:**
At this time, publisher downgrade QoS, and send a message using **QoS=0**
`mosquitto_pub -h myserver -u "usertest" -t "/downstream" -m "teste" -i test-pub-queued  -c -q 0`

![image](https://user-images.githubusercontent.com/8357905/83887292-a0643280-a71e-11ea-9d7f-17c4d905e658.png)

In my understanding we should't have any message on the queue and in fact, if we look at below image we haven't.

![image](https://user-images.githubusercontent.com/8357905/83887433-ce497700-a71e-11ea-8456-b9eec213161b.png)

Subscriber become online again:
`mosquitto_sub -h myserver -u "usertest" -t "/downstream"  -i test-queued-msgs -q 2 -c`

![image](https://user-images.githubusercontent.com/8357905/83887645-1a94b700-a71f-11ea-9137-436fecfc1ce2.png)

![image](https://user-images.githubusercontent.com/8357905/83887718-36985880-a71f-11ea-8d6c-3a390839b724.png)

No messages receive when reconnecting subscriber as expected, but on webpage it still having one queued message.

Publishing messages using **QoS=0** while subscriber is offline keeps the Msg Queued growing if subscriber had clean-session false in its last session.
Even reconnecting subscriber, it keeps the value.

The only way to clean it up is restarting the server.

Am I doing it right ?
Thanks

**Comment by ioolkos** [comment]
then please compare the metrics to this. (`vmq-admin metrics show`)

**Comment by gloffreda** [comment]
I have:
`counter.queue_message_out = 1`

But my question is: Why a QoS = 0 published message got queued ?

**Comment by gloffreda** [comment]
Hi @ioolkos 
Sorry to push it, but I'm afraid we are mistaken something and having some messages being lost.

We have a node app running in QoS = 2 subscription, clean-session=false.
Once I restart this app, some messages get queued. 
Once the app gets back, same client-id as before, the msgs queued keeps the value.

as you can see below:
![image](https://user-images.githubusercontent.com/8357905/84088279-86e31500-a9c2-11ea-87e6-93219c66049b.png)

Looking on sessions we have:

![image](https://user-images.githubusercontent.com/8357905/84088696-7a12f100-a9c3-11ea-9d66-3b71bc200211.png)

Those are our app in a cluster, 2 instances.

The metrics are:

```
counter.client_keepalive_expired = 0
counter.client_expired = 0
counter.cluster_bytes_received = 227111954
counter.mqtt_connack_sent = 5285
counter.cluster_bytes_dropped = 0
counter.mqtt_connect_received = 5285
counter.system_context_switches = 69908354
gauge.vm_memory_system = 136978400
counter.cluster_bytes_sent = 85624066
counter.mqtt_connack_accepted_sent = 0
gauge.system_process_count = 384
gauge.system_utilization_scheduler_3 = 0
counter.mqtt_publish_error = 5
counter.queue_message_drop = 0
gauge.system_utilization = 26
counter.mqtt_pubrec_sent = 0
counter.mqtt_pubrec_invalid_error = 0
counter.system_io_out = 694473369
counter.system_reductions = 30197752232
gauge.system_utilization_scheduler_1 = 2
counter.netsplit_detected = 2
gauge.vm_memory_total = 187612880
counter.mqtt_disconnect_received = 51
counter.system_exact_reductions = 29670797597
counter.mqtt_subscribe_received = 3699
gauge.queue_processes = 5
counter.netsplit_resolved = 2
counter.mqtt_pubcomp_sent = 0
counter.mqtt_unsubscribe_error = 0
gauge.system_utilization_scheduler_4 = 0
counter.socket_close = 5444
counter.system_words_reclaimed_by_gc = 63161030509
counter.system_io_in = 7249516848
counter.mqtt_connack_identifier_rejected_sent = 0
counter.queue_message_out = 466512
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_publish_sent = 466426
counter.bytes_received = 150226217
counter.mqtt_pubcomp_received = 457183
counter.socket_open = 5449
counter.mqtt_pingresp_sent = 62034
counter.mqtt_puback_sent = 291039
counter.router_matches_remote = 101870
gauge.vm_memory_atom_used = 922085
counter.mqtt_subscribe_error = 0
counter.queue_message_expired = 0
counter.mqtt_publish_auth_error = 3808
counter.bytes_sent = 256480427
gauge.retain_messages = 0
counter.mqtt_connack_unacceptable_protocol_sent = 0
counter.mqtt_pubrel_sent = 457188
gauge.vm_memory_atom = 941017
counter.mqtt_subscribe_auth_error = 3364
counter.system_gc_count = 32152706
counter.mqtt_unsuback_sent = 1
counter.mqtt_connack_not_authorized_sent = 0
counter.queue_initialized_from_storage = 0
gauge.vm_memory_processes_used = 50629368
gauge.system_utilization_scheduler_2 = 100
counter.system_runtime = 4615971
counter.socket_error = 0
counter.mqtt_pubrec_received = 457188
gauge.retain_memory = 11344
counter.mqtt_pubcomp_invalid_error = 0
gauge.vm_memory_processes = 50634480
counter.mqtt_unsubscribe_received = 1
counter.system_wallclock = 263344800
counter.mqtt_invalid_msg_size_error = 0
counter.queue_setup = 3786
counter.mqtt_pubrel_received = 0
gauge.vm_memory_ets = 63232976
counter.router_matches_local = 206419
gauge.vm_memory_binary = 51894224
gauge.vm_memory_code = 13392937
counter.mqtt_auth_received = 0
gauge.router_memory = 33176
counter.mqtt_puback_invalid_error = 0
counter.mqtt_publish_received = 308048
gauge.system_run_queue = 0
counter.queue_teardown = 3781
gauge.router_subscriptions = 15
counter.mqtt_auth_sent = 0
counter.socket_close_timeout = 10
counter.mqtt_connack_bad_credentials_sent = 0
counter.queue_message_unhandled = 0
counter.mqtt_puback_received = 0
counter.queue_message_in = 466517
counter.mqtt_pingreq_received = 62034
counter.mqtt_suback_sent = 335
counter.mqtt_disconnect_sent = 0
```

Shouldn't it send the queued messages and clear the queue once the client re-subscribe to the topic ?

Can you help me clarify and work to avoid message lost during app restart ?

Thanks

**Comment by parikshittyagi** [comment]
Hey, I am also facing the same problem. 
![verneMQMessageQueue_1](https://user-images.githubusercontent.com/32409255/89991379-658ff500-dca1-11ea-8a16-1bd9d18aa05f.png)

I use this command

>  sudo vmq-admin session show --client_id --offline_messages --topic --qos --statename --clean_session

to checkout the offline sessions and then I started a new session with "clean" as true.

**Comment by brunohorta82** [comment]
I have the same problem 
Clean session = true
QOS= 0
<img width="1215" alt="Screenshot 2020-10-07 at 21 39 53" src="https://user-images.githubusercontent.com/9153126/95385303-af820980-08e5-11eb-9ca2-855f98daad19.png">

**Comment by An0nymous0** [comment]
Same problem

**Comment by tomasgareau** [comment]
I've also been experiencing the same issue but in our case, we didn't have any persistent sessions...

What I found is that the "msg queued" number corresponded instead to *online* messages:

`sudo vmq-admin session show --client_id --online_messages --topic --qos --statename --clean_session`

gave us:

```
+---------------+-----------------------------------+-----------------+-----+-----------+
| clean_session | client_id                         | online_messages | qos | statename |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | anon-zcYLi34BI79iq5WPOk2FaHr/rNo= | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| false         | vernemq-0.br0                     | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | anon-h0os2ksu8Z5NaIOONIth2Q0Pl3w= | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | anon-MKfLIuBMgCfSDNNsJVOg8QFhjYw= | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | loc-ki4ilBWN2Mz3VVLe9dF           | 3201            | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | anon-7CdpLfXvig7D6wyiwmn8gnCP+/c= | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | anon-79OtYnJra5y5M54l78NIQogYD/I= | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | loc-at4TgYjd30QmxRkfSGn           | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | anon-tj5WxU2zUU+CjtkEl7E8+uf4DjM= | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | loc-fYdDrxT5yvyFLGW7AOa           | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | anon-GbW6I8ZxOn4N0rEsuhsJ2vLwMkQ= | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | loc-CGQc82vDdw81jnCqdju           | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | loc-nB66mxAa1IP8VoCk3si           | 3287            | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | btw-0C0yB7yIuHMYKGrsqrP           | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+
| true          | mosqsub|2040-bedford-of           | 0               | 0   | online    |
+---------------+-----------------------------------+-----------------+-----+-----------+

```

The clients with the queued online messages are subscribed to the same shared topic. Interestingly enough, it seems that only 2 of the 5 shared subscribers are queuing messages...

Not sure if this is necessarily the same behaviour seen in this issue and I don't know of a resolution yet but thought I would mention it in case it helps anyone else with debugging.

**Comment by tomasgareau** [comment]
We are now seeing this issue without any clients reporting either `online_messages` or `offline_messages`...

![image](https://user-images.githubusercontent.com/10787950/121225862-2ee62500-c847-11eb-9605-d74ddce8362e.png)

At an impressive 3 trillion messages and counting but no indication that any connected client has offline or online messages being queued (client IDs and topic omitted):

```
+---------------+------------------+-----------------+-----+-----------+
| clean_session | offline_messages | online_messages | qos | statename |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| false         | 0                | 0               | 0   | offline   |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| false         | 0                | 0               | 0   | offline   |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| false         | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| false         | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
| false         | 0                | 0               | 0   | offline   |
+---------------+------------------+-----------------+-----+-----------+
| true          | 0                | 0               | 0   | online    |
+---------------+------------------+-----------------+-----+-----------+
```

Any ideas how we could determine where these "queued messages" are coming from? My concern is that this is causing dropped messages somewhere in a way that's difficult for us to pin down.

**Comment by ioolkos** [comment]
@tomasgareau what are your counters, and how do they change?

`sudo vmq-admin metrics show | grep message`

**Comment by tomasgareau** [comment]
Hi @ioolkos -- not 100% sure what you mean by "how do they change". Do you mean the per-minute/hour/day change in the values of these counters? That command gets me the following output on a one-off command:

```bash
counter.queue_message_unhandled = 63969
counter.queue_message_out = 1164011401
counter.queue_message_drop = 0
counter.queue_message_expired = 0
counter.queue_message_in = 2278078959
gauge.retain_messages = 0
```

I'm pretty sure we don't actually have any queued messages (or at least certainly not in the billions) -- in a 3-node cluster we're using about ~400MiB of RAM total, and ~150MiB of disk space total.

**Comment by ioolkos** [comment]
@tomasgareau yeah, see what the counters do in a certain time window. Call that command twice in 5 minutes and see whether only `queue_message_in` inreases.

I know nothing about your use case, but am I correct assuming this is all about Shared subscribers?

------
https://github.com/sponsors/vernemq

**Comment by tomasgareau** [comment]
I see -- here's output from that command, 5 minutes apart:
```
counter.queue_message_unhandled = 63969
counter.queue_message_out = 1221516005
counter.queue_message_drop = 0
counter.queue_message_expired = 0
counter.queue_message_in = 2348420712
gauge.retain_messages = 0
```

```
counter.queue_message_unhandled = 63969
counter.queue_message_out = 1222059600
counter.queue_message_drop = 0
counter.queue_message_expired = 0
counter.queue_message_in = 2349852382
gauge.retain_messages = 0
```

We _are_ using shared subscribers, yes. A rough overview of our use-case: we fan-in data from ~1300 IoT devices. One event might see anywhere from ~1-15 `raw` messages coming in. These `raw` messages get aggregated, enriched, and re-published as `aggregated` messages representing that one event. Finally, the `aggregated` messages are placed on a work queue for processing. It's _only_ the subscribers to the `aggregated` messages that are using a shared subscription.

```
IoT Devices -----> Aggregator -----> Work Queue Client ----> Work Queue
              ^                 ^                        ^
              |                 |                        ∟ not MQTT
              |                 | 
              |                 ∟ MQTT, "aggregated", shared subscribers
              |
              ∟ MQTT, "raw", normal subscribers

```

**Comment by ioolkos** [comment]
So, yes, there's a big difference between the queue_in and queue_out 5-min deltas. This would normally be seen when offline queues collect messages.

---
https://github.com/sponsors/vernemq

**Comment by tomasgareau** [comment]
Interesting... would there be a way that I can identify where those messages are being queued/who's queuing them? When I run:

`vmq-admin session show --client_id --online_messages --offline_messages --topic --qos --statename --clean_session`

I don't see any clients with either `offline_messages` or `online_messages` messages greater than 0.

**Comment by ioolkos** [comment]
@tomasgareau you're right, that's interesting. I have no better idea atm, and to come up with an explanation I'd need to allocate time to go/think through this.

Note that the session show command only pages 100 rows, check `vmq-admin session show --help` to see how to increase that, or ask for a specific ClientID to check.
Do you know ClientIDs of potential offline message collectors? it seems you said that you don't have `clean_session=false` Clients but are you sure about that?
are your subscriber IDs random?

---
https://github.com/sponsors/vernemq

**Comment by kedarundale17** [comment]
@ioolkos Same issue observed. 
I read and understand the context being discussed here. 
To add more details, I faced the issue when a client with client id 'CENSYS' failed to connect and is not online.
The qos is 0, topic is #, clean_session is false, offline_message is 0
Additionally the client connect fails when webhooks are enabled to auth register, publish and subscribe.
The msg queued size increase is directly proportinal to the number of clients connected on one specific node(as i observed).

For example if 2 clients are connected the msg queued on the status page increases by 2.

When we load the node with around 50k connections the msg queued increase rapidly. The publish/subscribe works ok.
But the msg queued number which reaches around 13 billion in 3 days time troubles me. 

Any help/lead will be helpful. 
Thank you.

**Comment by ioolkos** [comment]
@kedarundale17
I just had this idea: have you maybe had a subscription to `$SYS/#` (subscribing to the whole SYSTREE) that was `clean_session false`, now offline but still collecting messages in a queue?

(is SYSTREE enabled at all in `vernemq.conf`? if yes, with what export time interval?)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by kedarundale17** [comment]
> @ioolkos 
> I just had this idea: have you maybe had a subscription to `$SYS/#` (subscribing to the whole SYSTREE) that was `clean_session false`, now offline but still collecting messages in a queue?

I think yes, by the looks of it. Although not 100 % sure.


> (is SYSTREE enabled at all in `vernemq.conf`? if yes, with what export time interval?)

Yes SYSTREE is enabled in the vernemq.conf 
systree_enabled = on
systree_interval = 20000

**Comment by mths1** [comment]
I was playing with vmq_queue this evening and noticed the same. At least one case, is quite easily to reproduce:
- Start a session with clean_session = false / QoS1 listening to a topic 
- Disconnect the session
- Send "QoS 0" messages  to the topic

What happens is this:
- The queue_message_in is increased
- Code wants to add message, only at that point it realizes that all sessions are offline
- It discards the message without modifing any queue and without setting 

One solution would be to increase the queue_unhandeld, or a new metric capturing the ignore case. This seems to work, and has only minimal impact. An other option would be to rework the whole code so that the metric is only increased if it is actually added to a queue, although this would slightly change the meaning of the metric. One could reason for both (or maybe a third). In case the queue_unhandeled is the choosen solution: I have a branch ready for PR :-)

The general problem here is, similar to the one with the online/offline clients this trying of figuring out the actual state of the system based on this metrics, which is very error prone.

**Comment by ioolkos** [comment]
+1 for counting this towards unhandled messages. It's at least an improvement and easier to explain:
- unhandled messages intentionally dropped by a re-connecting client that had a persistent session before but now requests a fresh session
- unhandled QoS 0 messages in offline queues.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
