### ISSUE TITLE
Crash During Shutdown: bad argument in call to io_lib:format("Listeners are not ready: ~p", [mqtt,mqtt])

### ISSUE THREAD

**Issue by ertanden** [vernemq/vernemq#1529]
### Environment

- VerneMQ Version: 1.10.2
- OS: Docker Alpine 3.9
- Erlang/OTP version (if building from source): 21.3
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 

### Expected behavior

- No crash

### Actual behaviour

Issue happens when shutting down the node:
```
vmq-admin cluster leave node=VerneMQ@$VERNEMQ_KUBERNETES_HOSTNAME
vmq-admin cluster leave node=VerneMQ@$VERNEMQ_KUBERNETES_HOSTNAME -k -i 5 -t $VERNEMQ_TERMINATION_GRACE_PERIOD_SECONDS
```

```
The following console output is seen with crashes:
07:35:17.925 [info] all queues offline: 0 draining, 0 offline, 0 msgs
07:35:18.283 [error] CRASH REPORT Process <0.5844.17> with 0 neighbours crashed with reason: bad argument in call to io_lib:format("Listeners are not ready: ~p", [mqtt,mqtt]) line 187 in vmq_health_http:listeners_status/0 line 82
07:35:18.286 [error] Cowboy stream 1 with ranch listener {{10,130,16,75},8888} and connection process <0.5843.17> had its request process exit with reason: bad argument in call to io_lib:format("Listeners are not ready: ~p", [mqtt,mqtt]) line 187 in vmq_health_http:listeners_status/0 line 82
07:35:20.683 [error] CRASH REPORT Process <0.5848.17> with 0 neighbours crashed with reason: bad argument in call to io_lib:format("Listeners are not ready: ~p", [mqtt,mqtt]) line 187 in vmq_health_http:listeners_status/0 line 82
07:35:20.683 [error] Cowboy stream 1 with ranch listener {{10,130,16,75},8888} and connection process <0.5846.17> had its request process exit with reason: bad argument in call to io_lib:format("Listeners are not ready: ~p", [mqtt,mqtt]) line 187 in vmq_health_http:listeners_status/0 line 82
```

Probably crash happens because listeners were stopped but the health check is still polling during the Grace Period when deleting the POD.

**Comment by ioolkos** [comment]
@ertanden thanks... does this have any operational impact? That is, does the crashing process escalate in any way? If at all this is probably bounded in escalation to a crashed Cowboy app.

**Comment by ioolkos** [comment]
Oh, I see, it's actually a bug in the format call.

**Comment by ertanden** [comment]
@ioolkos I'm not sure if this has operational impact. My wild guess would be no, but still I'm not exactly sure if this crash could cause a wrong behavior in cluster leave scenario.

We still are experiencing the issue in #1363. Basically when there are cluster leaves and joins after a while Messages don't get routed between publishers and subscribers on different nodes.
