### ISSUE TITLE
Bridging Between VerneMQ Clusters

### ISSUE THREAD

**Issue by ssmiller25** [vernemq/vernemq#1542]
#942 # Environment

- VerneMQ Version: 1.10.2
- OS: Linux (Kubernetes)
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 3 nodes (both clusters)

### Expected behavior

Bridge connection can be made between one cluster and another, which can fail over but does not result in duplicate messages.

### Actual behaviour

We have two VerneMQ clusters in which we wish to establish a bridge.  In our first configuration we configured each node on one cluster to setup the bridge connection - but with that configuration, we received duplicate messages.  Our workaround was to only establish the bridge on one of the nodes.  Our concern is if that one node goes down, the bridge connections will be lost.

**Comment by ioolkos** [comment]
Yes, a bridge is always a point to point MQTT bridge. You could start 2 bridges but use shared subscription topics locally, so that messages are load balanced. You can also start the bridges from cluster 1 to cluster 2 (push), or from cluster 2 to cluster 1 (pull), and see what suits you better.

**Comment by ssmiller25** [comment]
Thanks!  We will look at leveraging shared subscription topics to load balance across bridges.

**Comment by chetniks** [comment]
Hello @ssmiller25 ,

Can you please advise if you were able to leverage shared subscription topics to load balance and if so could you please share an example? 
We are experiencing same issue and we were not able to get it working with the configuration below :

vmq_bridge.tcp.br0.topic.1 = +/a in 0 topic1 $share/bridge/topic1/something
vmq_bridge.tcp.br0.topic.2 = +/u in 0 topic1 $share/bridge/topic1/something
vmq_bridge.tcp.br0.topic.3 = +/s out 0 $share/bridge/topic2 topic2/something
vmq_bridge.tcp.br0.topic.4 = +/s out 0 $share/bridge/topic2 topic2/something
vmq_bridge.tcp.br0.topic.5 = +/u out 0 $share/bridge/topic2 topic2/something

**Comment by ssmiller25** [comment]
Hi @chetniks 

The project actually spun down, so we never had a chance to test this configuration.  Perhaps @ioolkos could help you with your example.

**Comment by chetniks** [comment]
Hi @ioolkos,

Could you share any working example of bridge configuration with remote/local prefix that is using shared subscription ? 
We tried a lot simpler examples than the ones above and we are not able to get shared subscriptions to work in bridged configuration with any combination of remote and local prefixes, its only being able to work when prefixes are not used.

In case that is not possible please let us know so we could investigate an alternative solution and maybe it would be good to point out in your documentation.

Thank you in advance,
