### ISSUE TITLE
Can't get VerneMQ to accept more than 10k connections.

### ISSUE THREAD

**Issue by NewBermuda** [vernemq/vernemq#1546]
### Environment

- VerneMQ Version: vernemq-1.10.2.stretch.x86_64
- OS: Debian-Stretch
- VerneMQ configuration (vernemq.conf): see below
- Cluster size/standalone: standalone

### Expected behavior
I'm deploying Debian Stretch on a remote testbed node and installing VerneMQ on it. On another testbed node on the same network I'm deploying Apache Jmeter and it's MQTT plugin to loadtest VerneMQ.
All the configuration on the nodes is done remotely by using bash scripts and SSH.
I'm configuring VerneMQ like this:
```
dpkg -i vernemq-1.10.2.stretch.x86_64.deb
sed -i 's/accept_eula = no/accept_eula = yes/g' /etc/vernemq/vernemq.conf
sed -i 's/allow_anonymous = off/allow_anonymous = on/g' /etc/vernemq/vernemq.conf
sed -i 's/listener.tcp.default = 127.0.0.1:1883/listener.tcp.default = 172.16.2.1:1940/g' /etc/vernemq/vernemq.conf
sed -i 's/listener.max_connections = 10000/listener.max_connections = infinity/g' /etc/vernemq/vernemq.conf
sed -i 's/listener.nr_of_acceptors = 10/listener.nr_of_acceptors = 100000/g' /etc/vernemq/vernemq.conf
sed -i 's/max_inflight_messages = 20/max_inflight_messages = 0/g' /etc/vernemq/vernemq.conf
sed -i 's/allow_multiple_sessions = off/allow_multiple_sessions = on/g' /etc/vernemq/vernemq.conf
sed -i 's/max_online_messages = 1000/max_online_messages = 10000/g' /etc/vernemq/vernemq.conf
sed -i 's/max_offline_messages = 1000/max_offline_messages = 10000/g' /etc/vernemq/vernemq.conf

echo 'session    required   pam_limits.so' >> /etc/pam.d/common-session
echo '*      soft   nofile      1048576' >> /etc/security/limits.conf
echo '*      hard   nofile      1048576' >> /etc/security/limits.conf
echo 'vernemq      soft   nofile      1048576' >> /etc/security/limits.conf
echo 'vernemq      hard   nofile      1048576' >> /etc/security/limits.conf


# increase ulimit
ulimit -n 100048 

systemctl restart vernemq
```

### Actual behaviour
I'm using an Apache Jmeter testplan where 20000 clients connect to the broker and subscribe to the same topic.
Then there is one single client connecting that publishes 200 messages to that topic.
I'm measuring the latency distribution over these messages, so there are 200*20000 latency samples.
This setup works for Mosquitto, EMQ X and HiveMQ. But for VerneMQ I'm having some connection problems.
After receiving around 70000 successful latency samples, new clients fail to subscribe, 
I'm getting the jmeter error message: Subscribe failed because connection is not established.
Can you point out to me where the error is in my VerneMQ configuration?
It seems like out of 20000 connections, the broker fails after accepting 10409 of them.
This testplan works for other brokers, so I'm pretty sure this is about my VerneMQ configuration.

**Comment by ioolkos** [comment]
Slow down connection setup rate. You're probably stalling the registration synchronisation on plumtree.
Try the following configs:
don't set `allow_multiple_sessions`. It's a deprecated option, and might interfere.

`listener.nr_of_acceptors = 100` (no need for 100k acceptor processes!) 
`coordinate_registrations = off` (if you know your ClientIDs will be ensured to be unique anyway)
`metadata_plugin = vmq_swc`

**Comment by NewBermuda** [comment]
> 
> 
> Slow down connection setup rate. You're probably stalling the registration synchronisation on plumtree.
> Try the following configs:
> don't set `allow_multiple_sessions`. It's a deprecated option, and might interfere.
> 
> `listener.nr_of_acceptors = 100` (no need for 100k acceptor processes!)
> `coordinate_registrations = off` (if you know your ClientIDs will be ensured to be unique anyway)
> `metadata_plugin = vmq_swc`

I applied your suggestions to the .conf file, but unfortunately it still crashes after 10k connection. 
Have tried a lot of different settings, but nothing seems to work yet

**Comment by ioolkos** [comment]
What crashes after 10k connections? :smiley: 
(logs?)

**Comment by ioolkos** [comment]
look at metrics and IP:8888/status page too, or post here.
Do you restart Verne between test runs? do you delete state?

**Comment by NewBermuda** [comment]
Hi there, after looking closely at my results again I concluded that I should close this Issue.
It turns out, this was a JMeter issue where JMeter ran out of free memroy after creating 10k threads.
So actually, this problem was also coming up for the other brokers.
But your advice helped me uncover this problem and I can run my other tests for VerneMQ better now.

**Comment by ioolkos** [comment]
Okay, hier werden Sie geholfen. :)

Philosophical comment: you never test a SUT alone, you performance test every single component in the test setup (and their interactions).
