### ISSUE TITLE
Understanding routing score

### ISSUE THREAD

**Issue by gloffreda** [vernemq/vernemq#1547]
Hi There

I'm trying to better understand and tune our system and getting the definition of Routing Score on Release Notes we have:
"First, we added a couple of new metrics that allow us to show you a "routing score" for every cluster node on the VerneMQ cluster status page. The routing score consists of two percentages similar to 75 / 25 indicating that 75% of the received MQTT publish frames were routed to local subscribers and 25% were forwarded to subscribers on different cluster nodes. The routing score can be used to detect imbalances in a VerneMQ cluster and optimize your traffic and client partition."

Based on that, why our routing score is always 100/0 or 0/100 ?
Is it means that is not balanced ?

What can I do to balance it better ?

We are using clean_session = false, every client subscriber has the own client_id, always the same for same client. They are NodeJS applications.

![image](https://user-images.githubusercontent.com/8357905/85582762-13711280-b614-11ea-8fcf-da50ab59b286.png)

Thanks

**Comment by ioolkos** [comment]
I think it's a live score for the last 10 seconds.

**Comment by gloffreda** [comment]
it is always like that.Never gets other numbers. Just 0 and 100.
I have always a bigger number on publish in on 1 node, in that case VerneMQ@10.42.117.247. Is it normal ?
By seeing the entire panel, does it looks normal for you ?

**Comment by ioolkos** [comment]
Okay, this is based on the Javascript here: https://github.com/vernemq/vernemq/tree/master/apps/vmq_server/priv/static/js

And 8888/status.json should give the values this is based on. Issues with Javascript or Browsers not excluded...

**Comment by codeadict** [comment]
Yeah, it's a live score for the last 10 seconds. Can you please check the values of `matches_local` and `matches_remote`  from `host:8888/status.json`? That would give us an idea of whether there is an issue in the web UI calculation or if calculating correct from the metrics.

**Comment by kedarundale17** [comment]
Hello, 
Use Case : 
Cluster : 8 Nodes
Routing Score on 1 node : 80/20
Routing Score on other 7 nodes : 99/1
Client publish to Shared topic 
6 server Clients subscribe to Shared topic 

Is it possible to receive a client published message 2 times on a topic if the routing score is 80/20 ?
