### ISSUE TITLE
Subscribe to topic?

### ISSUE THREAD

**Issue by Fossil01** [vernemq/vernemq#1553]
I am using MySQL to auth users, which is working fine. For testing I had this set for pub and sub ACL:

`[{"pattern":"bla/cmd/#"},{"pattern":"bla/anc/#"},{"pattern":"bla/ping/#"},{"pattern":"bla/rsp/#"},{"pattern":"#"}]`

Now when I remove the `{"pattern":"#"}` part I cannot see stuff like: bla/ping/123

What am I doing wrong?

**Comment by ioolkos** [comment]
@Fossil01 were you able to resolve this? if not, we'd need to keep this open and investigate.

**Comment by Fossil01** [comment]
Sorry for the late reply. No, I resorted to just allowing every topic for now.

**Comment by Fossil01** [comment]
So, coming back to this. Still running 1.10.3 with MySQL ACL. Logging in works fine, but limiting pub/sub does not work, only allowing the wildcard works `{"pattern":"#"}`

We are using shared topics. Something like: `\$share\company\ping` and `\$share\company\card` which then show up in the queue as `ping` and `card` (using MQTT Explorer to check this).

Things I have tried in the subscribe ACL:

`[{"pattern": "$share/company/#"}]`
`[{"pattern": "\$share/company/#"}]`
`[{"pattern": "company/#"}]`
`[{"pattern": "ping"}]`
`[{"pattern": "card"}]`

After changing it and disconnecting/logging in again with my client nothing shows up.

Any idea?

**Comment by Fossil01** [comment]
I think I got it sort of working now. MQTT Explorer was set to subscribe to #, me thinking it would get everything it was allowed to get but that's not the case. I need to specifically subscribe to the topics listed in the ACL.

But, I am not sure how this works with shared subscriptions now. When I publish something now it gets received by both my test client and our "middleware/production" client so it looks like it's not being pushed on the shared topic (obviously). But when publishing to $share/company/card for example I get nothing in both clients.

**Comment by ioolkos** [comment]
@Fossil01 ok, so we need to determine whether shared topic work as expected for the Subscribe ACL. Can you exclude that you don't see any messages only because you have other offline Shared subscribers collecting those messages? (this can be non-intuitive)

**Comment by Fossil01** [comment]
I only just now saw this paragraph in the docs about shared subscriptions:

> Publishing Note: When publishing to a shared topic, do not include the prefix $share/group/ as part of the publish topic name

So I guess that's why I got confused. Now... what do I enter in the ACL for publishing? Just the topic or the full $share/group/topic?
