### ISSUE TITLE
Failed to connect with Vernemq Container through mqttnet client

### ISSUE THREAD

**Issue by Pooja-ui566** [vernemq/vernemq#1566]
Hi,
     I'm new to vernemq, facing issue to connect with vernemq running container inside ubuntu 18.04

Environment
- VerneMQ Version: 1.10.3

-Created the Vernemq container using : docker run -it -p 1886:1883 -v shared:/mnt -d --name vernemq1 -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes"  vernemq/vernemq

The container is up and running

-Configuration Changes are as follow:
accept_eula=yes
allow_anonymous = off
listener.ssl.cafile = ./etc/cacerts.pem
listener.ssl.certfile =./etc/cert.pem
listener.ssl.keyfile = ./etc/key.pem
listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on
listener.ssl.tls_version = tlsv1.2

plugins.vmq_passwd = off
plugins.vmq_acl = on
plugins.vmq_diversity = off

I have deployed a dotnet code (core 3.1) inside ubuntu machine which uses mqttnet library. Its working fine with allow_anonymous=on for connecting without any authentication.
But when tried to connect with authorization and authentication with above mentioned configuration its giving the error like this:  "Authentication failed because the remote party has closed the transport stream."  when tried to catch exception. Generated the certificates using openssl.

And i have tried to connect to port using curl as well - curl -vvv https://localhost:1886 got the error as:
* Rebuilt URL to: https://localhost:1886/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1886 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:1886
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:1886

Please help me out in solving this ASAP. 
Attaching  the mqttnet client code
[Program.zip](https://github.com/vernemq/vernemq/files/4917161/Program.zip)

**Comment by ioolkos** [comment]
@Pooja-ui566 
You need to use TLS 1.2. You also need to provide a client cert if you configure the server to require those.

(Please note: this is not a support channel, so I can't review your application code).

**Comment by Pooja-ui566** [comment]
@ioolkos 
i have used TLS 1.2 only. 
This is mqttnet client code:

using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Client.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Authentication;

namespace WithCertificate
{
    class Program
    {
        public static void Main(string[] args)
        {
             var factory = new MqttFactory();
            var mqttClient = factory.CreateMqttClient();
    
            X509Certificate caCert = new X509Certificate(new X509Certificate(@"./ca.crt").Export(X509ContentType.SerializedCert));
            X509Certificate clientCert = client.GetCertificate(File.ReadAllText(@"./client.crt"),
File.ReadAllText(@"./client.key"));

            X509Certificate clientCert_Key = new X509Certificate(clientCert.Export(X509ContentType.Pfx));

            List<X509Certificate> lstcertificate = new List<X509Certificate>() { caCert, clientCert_Key };
  
           var url = "XXXXXX";
            var port = 1883;
            TimeSpan time = TimeSpan.FromMinutes(60);
            var options = new MqttClientOptionsBuilder()
                .WithClientId(Guid.NewGuid().ToString())
                .WithTcpServer(url, port)
                .WithCommunicationTimeout(time)
                .WithTls(new MqttClientOptionsBuilderTlsParameters()
                {
                    AllowUntrustedCertificates = false,
                    UseTls = true,
                    SslProtocol = SslProtocols.Tls12,
                    Certificates = lstcertificate,
                    CertificateValidationHandler = delegate { return true; },
                    IgnoreCertificateChainErrors = false,
                    IgnoreCertificateRevocationErrors = false
                })
                .WithCleanSession()
                .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V311)
                .Build();

            try
            {

                await mqttClient.ConnectAsync(options);
                Console.WriteLine("Connected to broker with certificate authentication");
            }
            catch(Exception ex)
            {
                Console.WriteLine("Could not connect to broker:" + ex.Message);
            }
            if (mqttClient.IsConnected)
            {
                var message = new MqttApplicationMessageBuilder()
                        .WithTopic("house")
                        .WithPayload("Hello")
                        .WithExactlyOnceQoS()
                        .WithRetainFlag()
                        .Build();
                try
                {
                    await mqttClient.PublishAsync(message);
                    Console.WriteLine("Message Published");
                    Console.ReadLine();
                }
                catch(Exception ex)
                {
                    Console.WriteLine("Could not Publish the message: " + ex.Message);
                }
            }
        }

       public X509Certificate2 GetCertificate(string publicCertificate, string privateKey)
        {
            X509Certificate2 certificate = new X509Certificate2(GetBytes(publicCertificate, StringType.Certificate));
            var privateKeyBytes = GetBytes(privateKey, StringType.RsaPrivateKey);
            using var rsa = RSA.Create();
            rsa.ImportRSAPrivateKey(privateKeyBytes, out _);
            X509Certificate2 certificateWithKey = certificate.CopyWithPrivateKey(rsa);
            return certificateWithKey;
        }
       private static byte[] GetBytes(string _String, StringType type)
        {
            string header, footer;

            switch (type)
            {
                case StringType.Certificate:
                    header = "-----BEGIN CERTIFICATE-----";
                    footer = "-----END CERTIFICATE-----";
                    break;
                case StringType.RsaPrivateKey:
                    header = "-----BEGIN RSA PRIVATE KEY-----";
                    footer = "-----END RSA PRIVATE KEY-----";
                    break;
                default:
                    return null;
            }

            int start = _String.IndexOf(header) + header.Length;
            int end = _String.IndexOf(footer, start) - start;
            return Convert.FromBase64String(_String.Substring(start, end));
        }

        private enum StringType
        {
            Certificate,
            RsaPrivateKey
        }
    }
}

Same client code is working with mosquitto broker. 
Should i add anything else in vernemq configuration ?

**Comment by pooja405** [comment]
what should be vernemq configuration
