### ISSUE TITLE
on_session_expired does not work

### ISSUE THREAD

**Issue by rubengees** [vernemq/vernemq#1571]
### Environment

- VerneMQ Version: 1.10.3 / 61c52f90f91860f9c0ca4f9138cd9d3974ba9ee6
- OS: Linux / Docker
- Erlang/OTP version (if building from source): 22
- Cluster size/standalone: Single docker container

### Expected behavior

The `on_session_expired` webhook should be called when the client's keepalive expires.

### Actual behaviour

The container does not start when setting the option (in our case via docker environment `DOCKER_VERNEMQ_VMQ_WEBHOOKS__EXPIRED__HOOK=on_session_expired`):

```
[error] "on_session_expired" is not a valid enum value, acceptable values are: auth_on_register, auth_on_publish, auth_on_subscribe, on_register, on_publish, on_subscribe, on_unsubscribe, on_deliver, on_offline_message, on_client_wakeup, on_client_offline, on_client_gone, auth_on_register_m5, auth_on_publish_m5, auth_on_subscribe_m5, on_register_m5, on_publish_m5, on_subscribe_m5, on_unsubscribe_m5, on_deliver_m5, on_auth_m5
```

We then tried to fork, add the value to the enum in `vmq_webhooks.schema` and build from source. VerneMQ is then able to start, but the webhook does not get called.

We get the `on_client_gone` call and we see the relevant log:

```
[warning] client {[],<<"clientId">>} with username <<"username">> stopped due to keepalive expired
```

Is this feature not yet meant for use or is our configuration wrong?

All options we set:

```
DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES=-1
DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES=0
DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=3,4,5
DOCKER_VERNEMQ_LISTENER__SSL__CAFILE=/opt/ssl/server.crt
DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE=/opt/ssl/server.crt
DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE=/opt/ssl/server.key
DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT=0.0.0.0:8883
DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT=0.0.0.0:1883
DOCKER_VERNEMQ_LISTENER__WS__DEFAULT=0.0.0.0:9999
DOCKER_VERNEMQ_LISTENER__VMQ__CLUSTERING=0.0.0.0:44053
DOCKER_VERNEMQ_LISTENER__HTTP__METRICS=0.0.0.0:8888
DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=off
DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED=off
DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS=on
DOCKER_VERNEMQ_VMQ_WEBHOOKS__REGISTER__HOOK=on_register
DOCKER_VERNEMQ_VMQ_WEBHOOKS__REGISTER__ENDPOINT=http://localhost:8094
DOCKER_VERNEMQ_VMQ_WEBHOOKS__GONE__HOOK=on_client_gone
DOCKER_VERNEMQ_VMQ_WEBHOOKS__GONE__ENDPOINT=http://localhost:8094
DOCKER_VERNEMQ_VMQ_WEBHOOKS__OFFLINE__HOOK=on_client_offline
DOCKER_VERNEMQ_VMQ_WEBHOOKS__OFFLINE__ENDPOINT=http://localhost:8094
DOCKER_VERNEMQ_VMQ_WEBHOOKS__EXPIRED__HOOK=on_session_expired
DOCKER_VERNEMQ_VMQ_WEBHOOKS__EXPIRED__ENDPOINT=http://localhost:8094
DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MINIMUM=9100
DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MAXIMUM=9109
```

**Comment by ioolkos** [comment]
@rubengees thanks... I think the hook doesn't do what you expect it to do. It is meant for server side session expiry in case a session expiry interval was set. So, it should apply to this case (MQTT v5) and also to the case where persistent sessions expire (which is a global config value). I'll double check.

But it certainly doesn't apply for the client keepalive timing out, which is just a client not keeping it's promise to send regular ping requests. But at least what you can use for that case is the `on_client_gone` hook.

**Comment by rubengees** [comment]
Ah, I see! Then this is just a bug report for VerneMQ no starting when enabling that hook.

**Comment by rubengees** [comment]
Sorry for hijacking this issue with a usage question, but what would you recommend for this use case: We want to distinguish the case in which the client disconnected cleanly and in which the client fails to respond to the ping requests (e.g. when network is down). `on_client_gone` only tells us that a client is now offline, but not in which way. Would it be possible to add this info to `on_client_gone` or is this not the correct approach altogether?

**Comment by ioolkos** [comment]
Just to make sure (it's probably a typo from your side): the client does not respond to ping reqs. It sends out ping reqs.

Anyway, you are correct `on_client_gone` doesn't give you details on how the disconnect happened. While it might make sense for your use case right now, consider you'll get the notification in a million scale. Does it still make sense? can you still use the information?
It could probably be added to `on_client_gone` but tbh I have low prio considering this. You might think whether this is not better implemented as client side logic? (you could loop through some control message)

I'll look into the WebHooks related question later.

**Comment by rubengees** [comment]
> it's probably a typo from your side

Yes, right, thanks.

> Can you still use the information?

Hmm, yes our applications would still work without that information, but it's valuable for us to know if a client disconnected when we did not expect it to, since the expected case is for all clients to stay connected always. It is (hopefully) not very frequent that a client connects or disconnects and when it happens, we want to know as much as possible.

> It could probably be added to on_client_gone but tbh I have low prio considering this

That is fine, thank you for considering :)

> You might think whether this is not better implemented as client side logic?

That is what we currently have. The client sends a control message every x seconds. We had problems with race conditions though and found the idea of having the mqtt layer handle this way more elegant. Also, in our case, the clients are developed by a third party and it would have been cool if they had to do nothing on their side, except from simply connecting.

**Comment by ioolkos** [comment]
@rubengees I added the `on_session_expired` to the webhooks schema. Thanks for catching this!
