### ISSUE TITLE
Reload Auth and ACL Cache

### ISSUE THREAD

**Issue by saeidakbari** [vernemq/vernemq#1576]
Hi,
We have an IoT system that controls and communicate with many devices each day and we are using Vernemq as our main MQTT broker and it works fine. everything except caching mechanism that forces us to reconnect devices on each policy or authentication credentials change.
I noticed in the past issues and Auth document [here](https://docs.vernemq.com/configuration/db-auth) that caching is only reloaded when devices dis/re-connect to the broker.
As long as the devices are in remote locations and there is no access to them for reconfiguring, this becomes our main problem. writing custom plugin also is not to be expected because of rewriting almost everything (except caching mechanism) of `vmq_diversity` plugin.

Let me know if there is any technical difficulty that Vernemq was not implementing it in the main plugin or even in administration APIs.

**Comment by ioolkos** [comment]
Hi @saeidakbari maybe `sudo vmq-admin session reauthorize --help` does enough for you?

**Comment by saeidakbari** [comment]
@ioolkos As the doc says its only reauthorize `subscriptions` and the main problem is you can run command line on a microservice environment becuse there is no HTTP API for it.

**Comment by ioolkos** [comment]
You can wrap all CLI commands into HTTP: https://docs.vernemq.com/administration/http-administration

Of course, PRs are always welcome on any of this.
