### ISSUE TITLE
Issues on small node load

### ISSUE THREAD

**Issue by Erlandys** [vernemq/vernemq#1586]
### Environment

- VerneMQ Version: 1.10.3
- OS:
```
AWS CentOS 7
1 VM - 4GB of RAM / 2 cores
2 VM - 10GB of RAM / 4 cores
```
- Erlang/OTP version (if building from source): Erlang/OTP 21
- VerneMQ configuration (vernemq.conf) changes from the default:

```
leveldb.maximum_memory.percent = 30
allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = on
max_online_messages = 50000
max_offline_messages = -1
listener.max_connections = 40000
listener.nr_of_acceptors = 100
listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = on
vmq_diversity.auth_mysql.enabled = on
log.syslog = on
erlang.process_limit = 1000000
```

- Cluster size/standalone: 2 standalone brokers

### Expected behavior

- Clients successfully logs in to brokers.

### Actual behaviour
Online clients varies 10-20k overall.

Problem is, that when there is load for when clients are logging in, alot of errors appears and brokers cannot get stable online amount, goes up to 8k~ and starts going down and so on.

Errors:
```
vmq_mqtt_fsm:check_user:557 can't register client {[],<<"client-id">>} with username <<"client-username">> due to action_timeout
vmq_ranch:teardown:159 session stopped abnormally due to 'closed'
vmq_queue:wait_for_offline:353 got unknown sync event in wait_for_offline state {cleanup,session_taken_over}
```

**Comment by ioolkos** [comment]
@Erlandys thanks, you seem to encounter some form of overload. Do you see queue migration for reconnecting clients?
You'll need to collect more information in case you want to find out why, and possibly you'll need to switch to better server specs.

For usage issues/questions, I'll routinely point to the Mailing list in the future: https://groups.google.com/g/vernemq-users (created only yesterday)

**Comment by Erlandys** [comment]
> Do you see queue migration for reconnecting clients?

@ioolkos what output should indicated queue migration for reconnecting clients?

You see, the problem is that, clients are constantly connected to brokers and when connections are already made, VM usage is really small (5-10% CPU usage, 2GB of RAM~). This problem occurs only if we restart all VerneMQ brokers and after restart it's hard to connect all the clients, since all of those errors appears and all the clients start to connect and disconnect, this happens like broker clients goes up to for example 8k of clients, then drops to several hundred, after some time again goes up to 6k and again drops.

Also I've noticed that there still are issues with clustering (thats why we use 2 standalone nodes, without clustering), since if more messages are pushed through clusters, one cluster node starts dropping messages and disconnects from cluster, after some time reconnects, same issue as #1468

**Comment by ioolkos** [comment]
Okay, so it happens when you restart, that was the missing information. Then you overload client registration with the old plumtree protocol. There's different things you can do, one is managing the connect rate, one is switching to SWC protocol.
Do the clients always use the same clientIDs, or do they use 1-time clientIDS?

I'd be interested in your second issue. Please open a new Github issue with information. Unfortunately, the user in the issue you mention did not follow up in the investigation.

**Comment by Erlandys** [comment]
Clients always uses same clientIDs, those are constant and never changing and also, there cannot be more than 1 client with same client ID, each client uses own unique constant ID. I thought there may be some problems, since I've updated diversity plugin abit (added ability to auto subscribe from broker), also there were problems with auth_cache, if insert were made in 'on_register' lua hook and broker restarted, somehow cache were not cleared and insert were made again, errors occured. If necessary it's possible to test this issue also.

Btw, which config allows to change to SWC protocol or control connect rate (or connect rate must be controlled from 3rd party?)

**Comment by nguyenduybinh** [comment]
Hi,

I have the same issue last night with cluster 2 node and Vernemq version is 1.10.3. The resource usage of server isn't too busy, but client can't register and subcribe to the topic to receive messages

**Comment by nguyenduybinh** [comment]
I can reproceduce this issue with emqtt-bench tools.

I use emqtt-bench to stresstest my vernemq 2 node cluster. I create 10000 connected clients to my vernemq cluster, and then disconnected these clients from cluster. When disconnect clients from cluster, cluster was busy with high CPU load. 
When all client disconnected, the cluster back to normal.

I repeat above step many times, and sometimes you can see that, the connected client can't disconnect from cluster, the number of offline client is 10k offline clients stuck in cluster. At that time, the cluster is hang, new client can't connect and subcribe to topic, can't run query with vmq-admin command .......

I think this is a bug of version 1.10.3. I tested in cluster 2 node version 1.10.1 and didn't see the same issue.

**Comment by nguyenduybinh** [comment]
@ioolkos do you have any idea for this issue?

**Comment by ioolkos** [comment]
@nguyenduybinh what's in your logs? how did you disconnect the clients?

**Comment by Erlandys** [comment]
@ioolkos changing to SWC protocol trully helped to reduce CPU usage and increase connection rate after restart.

Now with SWC this error appears pretty often (this appears all the time, not only after restart):
```
vmq_swc_store:handle_info:422 Replica meta4: Can't initialize AE exchange due to no peer available
```

**Comment by ryandmello1198** [comment]
> AE

Do you know what does this error signify?

**Comment by ryandmello1198** [comment]
> @ioolkos changing to SWC protocol trully helped to reduce CPU usage and increase connection rate after restart.
> 
> Now with SWC this error appears pretty often (this appears all the time, not only after restart):
> 
> ```
> vmq_swc_store:handle_info:422 Replica meta4: Can't initialize AE exchange due to no peer available
> ```

Do you know what does this error signify?

**Comment by ioolkos** [comment]
@ryandmello1198  What this log means is that AE (anti entropy) tries to select a random peer to verify/sync data for partition `meta4`.  
What actually fails is the selection of a random node, based on `nodes()` call to get a list of peers. I'm not 100% sure why this can happen, though. Note that AE is working in the background all the time, so the exchange will be retried.

AE is a background repair layer for synchronisation. It complements the initial full broadcast that happens for events like registers or subscribes.
We're talking about a cluster btw, right?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
