### ISSUE TITLE
client forcefully disconnected by vernemq on request response call .

### ISSUE THREAD

**Issue by tharoldD** [vernemq/vernemq#1590]
### Environment
- VerneMQ Version: 1.10.4.1
- OS: 
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

Current Docker Configuration:
```
#!/bin/bash
if [ "$1" == "start" ]; then
    EXISTING=$(docker ps -a|grep ps-vernemq)
    if [ "$EXISTING" == "" ]; then
        echo "initializing instance..."
        docker run -p 1883:1883 \
		-e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" \
		-e "DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS=on" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REGISTER_M5__HOOK=auth_on_register_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REGISTER_M5__ENDPOINT=http://192.168.24.130:8080/mqtt-api/auth_on_register_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUBLISH_M5__HOOK=auth_on_publish_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUBLISH_M5__ENDPOINT=http://192.168.24.130:8080/mqtt-api/auth_on_publish_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_SUBSCRIBE_M5__HOOK=auth_on_subscribe_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_SUBSCRIBE_M5__ENDPOINT=http://192.168.24.130:8080/mqtt-api/auth_on_subscribe_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_PUBLISH_M5__HOOK=on_publish_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_PUBLISH_M5__ENDPOINT=http://192.168.24.130:8080/mqtt-api/on_publish_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_SUBSCRIBE_M5__HOOK=on_subscribe_m5" \
		-e "DOCKER_VERNEMQ_VMQ_WEBHOOKS__ON_SUBSCRIBE_M5__ENDPOINT=http://192.168.24.130:8080/mqtt-api/on_subscribe_m5" \
		-e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off" \
		-e "DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=5" \
		--name=ps-vernemq -d vernemq/vernemq:latest-alpine
        sleep 30
    else
        EXISTING=$(docker ps|grep ps-vernemq)
        if [ "$EXISTING" == "" ]; then
            docker start ps-vernemq
        fi
    fi
elif [ "$1" == "stop" ]; then
    docker stop ps-vernemq
else
    echo "Valid arguments are start and stop"
fi
```

### Expected Behavior on Request Response 
Response topic is triggered 

### Actual Behavior
2:20:44.145 [error] Ranch listener {{172,17,0,3},1883} terminated with reason: no function clause matching vmq_webhooks_plugin:enc_topic(<<"v1/responses/integration-hub-1">>) line 913
12:21:41.017 [error] CRASH REPORT Process <0.989.0> with 0 neighbours crashed with reason: no function clause matching vmq_webhooks_plugin:enc_topic(<<"v1/responses/integration-hub-1">>) line 913
12:21:41.018 [error] Ranch listener {{172,17,0,3},1883} terminated with reason: no function clause matching vmq_webhooks_plugin:enc_topic(<<"v1/responses/integration-hub-1">>) line 913

**Comment by ioolkos** [comment]
@tharoldD thanks, this immediately looks like a bug to me.

The weird thing is, this function expects the topic as a list, so obviously has no case clause for the binary string.
https://github.com/vernemq/vernemq/blob/32542ffa55e0adfb62e1a667f9f1492445766414/apps/vmq_webhooks/src/vmq_webhooks_plugin.erl#L913

Can you maybe look in the `crash.log` for a more complete stacktrace on that error?

**Comment by tharoldD** [comment]
[crash.log](https://github.com/vernemq/vernemq/files/5021860/crash.log)

**Comment by ioolkos** [comment]
If you like, you can check whether PR https://github.com/vernemq/vernemq/pull/1591 fixes this.
I don't 100% understand what you do though (this might come from a topic name in your JSON, or sth like that)

**Comment by ioolkos** [comment]
Issue was closed by merge. Feel free to re-open or comment.
