### ISSUE TITLE
Hot Reload with Hashicorp Vault

### ISSUE THREAD

**Issue by hongkongkiwi** [vernemq/vernemq#1599]
Hi there,

I'm planning to use VerneMQ with Hashicorp Vault to have dynamic database credentials.

At some point the database credentials will expire and need rotation, I would like to be able to hot reload vernemq so that downtime is minimized and I don't disconnect existing connections.

Is there any way to do this at the moment? I have an external script which can send a reload signal to VerneMQ, but I want to make sure that it can be done without downtime.

**Comment by ioolkos** [comment]
@hongkongkiwi Thanks, interesting. I suppose this is for one of the Lua scripts? (for which of the DBs?). 
To be honest, I don't know the answer from the top of my head. But this should be easily testable. Best case would be that disabling/enabling the plugin would be enough - this wouldn't touch existing connections.

**Comment by hongkongkiwi** [comment]
At the moment I'm using the Diversity plugin with MySQL.

That's a good idea, do you have an example of how I could disable and enable using the admin tool? This could be a good reload command.

Generally, how does Vernemq behave when it receives the SIGHUP term signal?
