### ISSUE TITLE
invalid_response_code,413

### ISSUE THREAD

**Issue by djsakisd** [vernemq/vernemq#1600]
Hi 

Each time i try to publich a large payload > 8 MB client get's disconnected , vernemq throws this in error.log : `@vmq_mqtt_fsm:auth_on_publish:727 can't auth publish [<<"sam">>,{[],<<"testing-client-id-paho-mqtt">>},0,[<<>>,<<"test">>,<<"test-sub-topic">>],<<73,68,51,3,32,32,32,2,95,124,84,65,76,66,32,32,32,61,32,32,1,239,163,187,207,142,66,32,97,32,100,32,32,32,66,32,111,32,121,32,115,32,32,32,70,32,111,32,114,32,32,32,76,32,105,32,102,32,101,32,32,32,83,32,111,32,117,32,110,32,100,32,116,32,114,32,97,32,99,32,107,32,32,32,84,80,69,49,32,32,32,71,32,32,1,239,163,187,207,142,74,32,97,32,100,32,101,32,110,32,44,32,32,32,66,32,108,32,97,32,99,32,107,32,32,32,69,32,121,32,101,32,100,32,32,32,80,32,101,32,97,32,115,32,32,32,38,32,32,32,74,32,32,32,66,32,97,32,108,32,118,32,105,32,110,32,32,32,84,80,69,50,32,32,32,71,32,32,1,239,163,187,207,142,74,32,97,32,100,32,101,32,110,32,44,32,32,32,66,32,108,32,97,32,99,32,107,32,32,32,69,32,121,32,101,32,100,32,32,32,80,32,101,32,97,32,115,32,32,32,38,32,32,32,74,32,32,32,66,32,97,32,108,32,118,32,105,32,110,32,32,32,84,80,79,83,32,32,32,5,32,32,32,49,47,49,32,84,67,79,78,32,32,32,25,32,32,1,239,163,187,207,142,83,32,111,32,117,32,110,32,100,32,116,32,114,32,97,32,99,32,107,32,32,32,84,73,84,50,32,32,32,71,32,32,1,239,163,187,207,142,82,32,73,32,84,32,77,32,79,32,32,32,40,32,66,32,97,32,100,32,32,32,66,32,111,32,121,32,115,32,32,32,70,32,111,32,114,32,32,32,76,32,105,32,102,32,101,32,41,32,32,32,40,32,82,32,101,32,109,32,105,32,120,32,41,32,32,32,84,82,67,75,32,32,32,7,32,32,32,49,48,47,49,48,32,84,89,69,82,32,32,32,6,32,32,32,50,48,50,48,32,65,80,73,67,32,32,194,171,8,32,32,32,105,109,97,103,101,47,106,112,103,32,3,32,239,163,187,206,168,239,163,187,206,176,32,16,74,70,73,70,32,1,1,32,32,1,32,1,32,32,239,163,187,206,171,32,67,32,10,7,7,8,7,6,10,8,8,8,11,10,10,11,14,24,16,14,10,10,14,29,21,22,17,24,35,31,37,36,34,31,34,33,38,43,55,47,38,41,52,41,33,34,48,65,49,52,57,59,62,62,62,37,46,68,73,67,60,72,55,61,62,59,239,163,187,206,171,32,67,1,10,11,11,14,10,14,28,16,16,28,59,40,34,40,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,...>>,...] due to {invalid_response_code,413}` 

If i try with a sligthly smaler payload ~7.4MB it works fine.

Max payload size is set to default (0) in conf.

Tried changing max-message-size to 50MB - same
Tried also with websockets - same
Tried from version 1.9.2 to 1.10.4.1 - same
Tried with allow anonymous - same
Tried with webhooks disabled - same

No idea whats causing it, any help would be gratly apreciated.

### Environment

- VerneMQ Version: 1.9.2 ~ 1.10.4.1
- OS: Ubuntu 18.04.4 LTS
- Erlang/OTP version (if building from source): Installed from official deb
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behaviour

It should send large payloads up to the 256 MB max size set.

### Actual behaviour

- Try to read a file as binary and send it over , if file size is > than 7.5 MB it should fail with same error

**Comment by ioolkos** [comment]
@djsakisd 
This is your authentication WebHook endpoint not accepting payloads > 7.5 MB.

Please re-configure the endpoint, or do not forward the payload to the auth endpoint:
`vmq_webhooks.mywebhook1.no_payload = on`

https://docs.vernemq.com/plugindevelopment/webhookplugins

**Comment by djsakisd** [comment]
@ioolkos 

Thank you for your time and help, setting no_payload = on as you suggested to all webhooks resolved the issue.
