### ISSUE TITLE
Vernemq Permission denied error 

### ISSUE THREAD

**Issue by vetriedi** [vernemq/vernemq#1604]
### Environment

- VerneMQ Version:
- OS:ubuntu 16.04
- Erlang/OTP version (if building from source):Erlang/OTP 22 [erts-10.6.4] 
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:standalone

make rel cmd successfully  created the release

===> Including Erts from /usr/lib/erlang
===> release successfully created!

root@ubuntu-listener:/option/_build/default/rel/vernemq# bin/vernemq start

bin/vernemq: 172: bin/vernemq: /option/_build/default/rel/vernemq/bin/../erts-10.6.4: Permission denied
vmq_cluster_node_sup
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

**Comment by nitan2001** [comment]
Hello vetriedi,

Have you resolved this issue?
Could you share it?
Thank you.
