### ISSUE TITLE
Is it possible to use 'on_publish' hook in Lua script?

### ISSUE THREAD

**Issue by ammma** [vernemq/vernemq#1608]
### Environment
- Docker: vernemq/vernemq:latest

### Expected behavior

My goal is to make VerneMQ send published data to Redis. And looks like using hooks and Lua scripting is a right way to go.

### Actual behaviour
 I've registered following Lua script:

```
function on_publish(pub)
    redis.cmd(pool, "RPUSH clients:events test_event")
    return true
end

pool = "auth_redis"
config = {
    pool_id = pool
}

redis.ensure_pool(config)
redis.cmd(pool, "RPUSH clients:events lua_script_loaded")
hooks = {
    on_publish = on_publish,
    on_publish_m5 = on_publish,
}
```

I can see that script was loaded and connection to redis made. It successfully executes `redis.cmd(pool, "RPUSH clients:events lua_script_loaded")`, but it looks like `on_publish` function is never called when i publish.
I didn't find any information in official documentation saying that some hooks are not available for Lua scripts, but for Erlang plugins only.
Could you tell me please if my scenario is possible or i have to look for other options?
Thanks.

**Comment by ioolkos** [comment]
Test example here: https://github.com/vernemq/vernemq/blob/4f0bbab8de80bb3b55497471c88d59d4e7de5eb0/apps/vmq_diversity/test/plugin_test.lua#L88
`on_publish` is called for side effect. don't return true.

Maybe this helps too: https://github.com/vernemq/vernemq/issues/1497

**Comment by ammma** [comment]
@ioolkos that helped, thanks a lot.

**Comment by kalyanijivrakh** [comment]
How to execute the script in docker vernemq ?

**Comment by ioolkos** [comment]
@kalyanijivrakh general Docker principles apply. You want to load a custom script, so you have to do that from a dir mounted into Docker.
You can either point the full script directory to the mount (using the `vmq_diversity.script_dir` setting) and copy all the scripts including your plugin there; or you can have an additional mount for your diversity plugin, and then point to the script file directly (`vmq_diversity.my_plugin.file`)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
