### ISSUE TITLE
Ranch listener {{0,0,0,0},8883} terminated with reason: no match of right hand value {error,{options,{socket_options,sndbuf,einval}}}

### ISSUE THREAD

**Issue by spalagu** [vernemq/vernemq#1609]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version:1.10.0
- OS:CentOS7
- Erlang/OTP version (if building from source):22.2.5-1
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:standalone

### Expected behaviour
no error

### Actual behaviour
from the prometheus monitor, it was observed that the connect/disconnect rate increased from 5/s to 20/s, and then a lot of the following information appeared in the error log and crash log,it lasted about 1 minute.
```
2020-08-12 03:07:04.592 [error] <0.24864.3430>@vmq_ranch:init:59 CRASH REPORT Process <0.24864.3430> with 0 neighbours crashed with reason: no match of right hand value {error,{options,{socket_options,sndbuf,einval}}} in vmq_ranch:init/4 line 59
2020-08-12 03:07:13.830 [error] <0.24864.3430>@vmq_ranch:init:59 Ranch listener {{0,0,0,0},8883} terminated with reason: no match of right hand value {error,{options,{socket_options,sndbuf,einval}}} in vmq_ranch:init/4 line 59
```
```
2020-08-12 03:07:05 =CRASH REPORT====
  crasher:
    initial call: vmq_ranch:init/4
    pid: <0.24864.3430>
    registered_name: []
    exception error: {{badmatch,{error,{options,{socket_options,sndbuf,einval}}}},[{vmq_ranch,init,4,[{file,"/usr/local/src/vernemq/apps/vmq_server/src/vmq_ranch.erl"},{line,59}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.360.0>,<0.359.0>,ranch_sup,<0.156.0>]
    message_queue_len: 0
    messages: []
    links: [<0.360.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 927
  neighbours:
```

**Comment by ioolkos** [comment]
@spalagu thanks, that's a new one...
It seems that the sndbuf settings triggers an invalid argument ('einval') lower in the system/OS.

Have you adapted any settings, especially the TCP buffer settings?

**Comment by spalagu** [comment]
thanks for reply, here is my settings
```
allow_anonymous = on
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
coordinate_registrations = on
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.vmq.clustering = 0.0.0.0:44053
listener.mountpoint = off
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local
plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = off
metadata_plugin = vmq_plumtree
vmq_acl.acl_file = ./etc/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = ./etc/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = ./share/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.postgres.ssl = off
vmq_diversity.postgres.password_hash_method = crypt
vmq_diversity.auth_cockroachdb.enabled = off
vmq_diversity.cockroachdb.ssl = on
vmq_diversity.cockroachdb.password_hash_method = bcrypt
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.mysql.password_hash_method = password
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.mongodb.ssl = off
vmq_diversity.auth_redis.enabled = off
vmq_bcrypt.pool_size = 1
log.console = file
log.console.level = info
log.console.file = ./log/console.log
log.error.file = ./log/error.log
log.syslog = off
log.crash = on
log.crash.file = ./log/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
distributed_cookie = vmq_xxx
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
listener.tcp.default=0.0.0.0:1883
listener.ssl.default=0.0.0.0:8883
listener.http.default=0.0.0.0:8888
listener.ssl.cafile=xxx
listener.ssl.certfile=xxx
listener.ssl.keyfile=xxx
nodename = VerneMQ@127.0.0.1

```

**Comment by spalagu** [comment]
and the sysctl settings
```
net.ipv4.tcp_max_tw_buckets = 60000
net.ipv4.tcp_sack = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_rmem = 4096 87380 4194304
net.ipv4.tcp_wmem = 4096 16384 4194304
net.ipv4.tcp_mem = 94500000 915000000 927000000
net.ipv4.tcp_max_syn_backlog = 8192
net.core.netdev_max_backlog = 32768
net.core.somaxconn = 32768
net.core.wmem_default = 8388608
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_fin_timeout = 20
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_max_orphans = 3276800
net.ipv4.tcp_keepalive_time = 120
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.ip_local_port_range = 1024 65000
```

**Comment by ioolkos** [comment]
@spalagu can't see an obvious problem in configs.
How exactly do you connect clients? are you sure they use the correct transport (TCP/SSL)?

The error here happens when Verne asks the socket for its buffer sizes, and then chooses the biggest of those to allocate an internal buffer.

**Comment by spalagu** [comment]
the clients and server communicate only through SSL, and 
I speculate that this error is caused by the instantaneous increase a lot of vernemq connections triggered by my other service failure

**Comment by spalagu** [comment]
@ioolkos this issue can be reproduced with the following script of vmq_mzbench
`#!benchDL

make_install(git = "https://github.com/erlio/vmq_mzbench.git",
             branch = "master")

include_resource(cacertsfile, "cacert.pem", binary)
include_resource(certfile, "cert.pem", binary)
include_resource(keyfile, "key.pem", binary)

pool(size = 200,
     worker_type = mqtt_worker,
     worker_start = poisson(200 rps)):
        loop(time = 8640 h, rate = 1 rps):
            connect(host = "xxx",
                    port = 8883,
                    client = fixed_client_id("mzbench", worker_id()),
                    clean_session = true,
                    keepalive_interval = 60,
                    proto_version = 4,
                    reconnect_timeout = 10,
                    transport = t(ssl, [t(reuse_sessions, false),
                                        t(key, load_client_key(resource(keyfile))),
                                        t(cacerts, load_cas(resource(cacertsfile))),
                                        t(cert,load_client_cert(resource(certfile)))])
                    )
`
it caused by connection kicked with fix client id and connect vernemq with ssl connection

**Comment by ioolkos** [comment]
> it caused by connection kicked with fix client id and connect vernemq with ssl connection

Please explain. I don't understand what you say.

**Comment by spalagu** [comment]
if a device is already connect to vernemq, once it create another connection to vernemq, vernemq will kill the old connection.
if a lot of this disconnections occur, the listener of vernemq will not work in few seconds.

**Comment by rohansingh** [comment]
We see this error logged a lot when the Google Cloud load balancer connects to VerneMQ to perform a health check. I believe what's happening is that the load balancer successfully opens the connection, decides VerneMQ is healthy, and quickly closes the connection.

At some point later, VerneMQ attempts to set socket options for a connection that doesn't exist any more.

**Comment by xiaolingtc** [comment]
We are having the same issue. Does Vernemq have a plan to fix this?

**Comment by ioolkos** [comment]
@xiaolingtc supposing it's the same issue (like the one noted about Google load balancer above), we should be able to do something about it, if only just catching the exception.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by xiaolingtc** [comment]
@ioolkos Our cluster indeed is behind an AWS ELB, but does this issue lead Vernemq to crash and reject connections? And is catching the exception enough to fix this when this error keeps happening?

In our situation, when this happens, restarting the cluster will not help and the cluster crashes again

**Comment by ioolkos** [comment]
@xiaolingtc it be surprising to me if this error would show as the cause of your cluster/restart issues.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by xiaolingtc** [comment]
It looks like our restart issues were caused by the combination of the exception and the overflows of the `accept queue` which is set to 1024 by default. 

I'd like to submit a pull request to catch the exception, where do I need to provide my GitHub name to request access?

**Comment by ioolkos** [comment]
@xiaolingtc Interesting, thanks. You don't need to request access to open a PR. You'd fork Verne into your Github account and then open a PR from your branch there.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by xiaolingtc** [comment]
@ioolkos Yes, I just catch the exception and the application will not crash anymore even if there is an `accept queue` overflow. Then we fixed the overflow issue and everything works fine now.
