### ISSUE TITLE
Building from source 1.10.4 is failing with error "Makefile:24: recipe for target 'rel' failed"

### ISSUE THREAD

**Issue by natrajT** [vernemq/vernemq#1612]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: 1.10.4
- OS:Ubuntu 18.04.3 LTS
- Erlang/OTP version (if building from source): 22
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:1

### Expected behaviour
Make rel should succesfully build and create rel folder in _build. In the same server i am able to build and run 1.10.0

### Actual behaviour
it is failign with below error
make[1]: Leaving directory '/opt/vernemq_1.10.4/vernemq/_build/default/lib/eleveldb/c_src/leveldb'
===> Compiling /opt/vernemq_1.10.4/vernemq/_build/default/lib/eleveldb/c_src/eleveldb.cc
===> Compiling /opt/vernemq_1.10.4/vernemq/_build/default/lib/eleveldb/c_src/refobjects.cc
===> Compiling /opt/vernemq_1.10.4/vernemq/_build/default/lib/eleveldb/c_src/threading.cc
===> Compiling /opt/vernemq_1.10.4/vernemq/_build/default/lib/eleveldb/c_src/workitems.cc
===> Linking /opt/vernemq_1.10.4/vernemq/_build/default/lib/eleveldb/priv/eleveldb.so
Makefile:24: recipe for target 'rel' failed
make: *** [rel] Error 1

- Please include minimal steps to reproduce the issue, if possible.
1) checkout 1.10.4 
2)   make rel

**Comment by ioolkos** [comment]
sorry, forgot comment yesterday: cannot reproduce this & therefore don't know how to help.
