### ISSUE TITLE
Is it possible to disable auth_on_publish webhook separately?

### ISSUE THREAD

**Issue by ATAKing1023** [vernemq/vernemq#1618]
### Environment

- VerneMQ Version: 1.9.2
- OS: CentOS 7
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
    - `plugins.vmq_webhooks = on`
    - webhooks configured
- Cluster size/standalone: standalone

### Expected behaviour

We'd like to disable the auth_on_publish webhook while enabling others (auth_on_register etc.), is it possible? 

### Actual behaviour

Here is the error logs when we tried to publish a message without auth_on_publish webhook configured:

```
2020-09-07 16:36:22.970 [error] <0.549.0>@vmq_mqtt_fsm:auth_on_publish:724 can't auth publish [<<"ankang">>,{[],<<"PC@@ankang-mqtt">>},0,[<<"test">>],<<"{\n  \"key\": 1\n}">>,false] due to chain_exhausted
```

**Comment by ioolkos** [comment]
I think this is documented here. You don't need to configure or dynamically register webhooks you don't need. https://docs.vernemq.com/plugindevelopment/webhookplugins#configuring-webhooks.

You still need another plugin to authorize the publishs.

**Comment by ATAKing1023** [comment]
> I think this is documented here. You don't need to configure or dynamically register webhooks you don't need. https://docs.vernemq.com/plugindevelopment/webhookplugins#configuring-webhooks.
> 
> You still need another plugin to authorize the publishs.

Thanks. 

Is it possible to benefit from the auth_on_register webhook while leaving auth_on_publish blank?
Is it possible to publish messages to VerneMQ when our webhook service is down?

**Comment by ATAKing1023** [comment]
It would be nice if there is something like `vmq_webhooks.mywebhook1.disabled = true`

**Comment by ATAKing1023** [comment]
@ioolkos any update for this issue? thanks

**Comment by ioolkos** [comment]
@ATAKing1023 I don't have an update and not 100% what update is expected :)
"is it possible" questions should easily be testable, at least for the most part I guess.

**Comment by ATAKing1023** [comment]
> I think this is documented here. You don't need to configure or dynamically register webhooks you don't need. https://docs.vernemq.com/plugindevelopment/webhookplugins#configuring-webhooks.
> 
> You still need another plugin to authorize the publishs.

This issue is addressed via a lua script authorizing the publishes. Thanks.
