### ISSUE TITLE
VMQ-Diversity: Passwords are logged in connection error message

### ISSUE THREAD

**Issue by Goost91** [vernemq/vernemq#1619]
### Environment

- VerneMQ Version: using docker image vernemq/vernemq:latest 
- OS: Debian 9
- Erlang/OTP version (if building from source):
- Cluster size/standalone: standalone
- VerneMQ configuration (vernemq.conf) or the changes from the default
> accept_eula=yes
allow_anonymous=off
log.console=console
log.console.level=debug
plugins.vmq_acl=off
plugins.vmq_diversity=on
plugins.vmq_passwd=off
vmq_diversity.postgres.user=dbuser
vmq_diversity.postgres.password=dbpassword
vmq_diversity.postgres.port=5432
vmq_diversity.postgres.host=db_ip
vmq_diversity.postgres.password_hash_method=crypt
vmq_diversity.postgres.database=test
vmq_diversity.auth_postgres.enabled=on
### Expected behaviour

When a database connection error occurs, the log message detailing the error should not contain any user-supplied details that were used to set up the connection.

### Actual behaviour

Whenever the following error occurs due to an issue we're resolving internally, the user-supplied details are logged in plain text, like the username and password.
 
> [error] can't call function auth_on_register with args [{addr,<<"10.244.0.1">>},{port,58896},{mountpoint,<<>>},{client_id,<<"foo-client">>},{username,<<"foo">>},{password,<<"bar">>},{clean_session,true}] in "./share/lua/auth/postgres.lua" due to {throw,{error,not_connected}}

Since our logs are collected in a centralised storage I'd like to prevent this from happen to prevent leaking security-critical details. 
I've looked in several places to see if this is perhaps something that can be configured, but I couldn't find anything indicating as such.

**Comment by ioolkos** [comment]
@Goost91 thanks, I agree this needs to be adressed. We either try to sanitize stuff in the logs, or take out those logs manually if this is possible.

This is currently not configurable as you have found already.

**Comment by codeadict** [comment]
This circles back to https://github.com/vernemq/vernemq/issues/1017
