### ISSUE TITLE
Handle list of websocket subprotocols

### ISSUE THREAD

**Issue by blokovi** [vernemq/vernemq#1620]
### Environment

- VerneMQ Version: 1.10.4.1
- OS: Official docker image
- Erlang/OTP version (if building from source): Official docker image
- VerneMQ configuration (vernemq.conf) or the changes from the default: No changes
- Cluster size/standalone: standalone

### Expected behaviour

Using [gorilla](github.com/gorilla/websocket
) websocket package to connect vernemq with following parameters:
```
	dialer := &websocket.Dialer{
		Subprotocols: []string{"mqttv3.1", "mqtt"},
	}
```
When I have subprotocols list with just one element: just `"mqttv3.1"` or just `"mqtt"` it succesfully connect. But when it's both of them, like in code above, it doesn't.

### Actual behaviour

```
$ cat crash.log
2020-09-09 21:57:20 =CRASH REPORT====
  crasher:
    initial call: cowboy_clear:connection_process/4
    pid: <0.494.0>
    registered_name: []
    exception error: {{badrecord,state},[{vmq_websocket,add_socket,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_websocket.erl"},{line,194}]},{vmq_cowboy_websocket,takeover,7,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_cowboy_websocket.erl"},{line,52}]},{cowboy_http,loop,2,[{file,"/opt/vernemq/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,233}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.341.0>,<0.340.0>,ranch_sup,<0.142.0>]
    message_queue_len: 0
    messages: []
    links: [#Port<0.21>,<0.341.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 1835
  neighbours:
2020-09-09 21:57:20 =ERROR REPORT====
Ranch listener {{172,17,0,2},8080} had connection process started with cowboy_clear:start_link/4 at <0.494.0> exit with reason: {{badrecord,state},[{vmq_websocket,add_socket,2,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_websocket.erl"},{line,194}]},{vmq_cowboy_websocket,takeover,7,[{file,"/opt/vernemq/apps/vmq_server/src/vmq_cowboy_websocket.erl"},{line,52}]},{cowboy_http,loop,2,[{file,"/opt/vernemq/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,233}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

$ cat error.log
2020-09-09 21:57:20.456 [error] <0.494.0>@vmq_websocket:add_socket:194 CRASH REPORT Process <0.494.0> with 0 neighbours crashed with reason: bad record state in vmq_websocket:add_socket/2 line 194
2020-09-09 21:57:20.456 [error] <0.494.0>@vmq_websocket:add_socket:194 Ranch listener {{172,17,0,2},8080} terminated with reason: bad record state in vmq_websocket:add_socket/2 line 194
```

I found almost same issue #1149  that is resolved, but can you please check if this bug has reappeared in the meantime.

**Comment by ioolkos** [comment]
@blokovi thanks, I wouldn't think this is a regression, as the error is different (badrecord in state).
Let me understand and fix this.

**Comment by ioolkos** [comment]
@blokovi is the way the Gorilla websocket client sets up the Subprotocols compatible to non-Gorilla server?
Cowboy and Verne should both be able to handle lists of protocols. But it's weird, it's like the Socket is somehow faulty or gone already when we come to adding it to the session.

For reference, Cowboy doc:
https://github.com/ninenines/cowboy/blob/3977f2b96fb8cc2164bfe28ee094b3e661a2fad9/doc/src/guide/ws_handlers.asciidoc

**Comment by blokovi** [comment]
@ioolkos  In my case, same gorilla client with list of subprotocols successfully connected with mosquitto broker. Have you tested any other client with list of subprotocols to connect to VerneMQ over ws?

**Comment by ioolkos** [comment]
Ok, guess must be a Verne side issue then. Haven't tested any WS clients lately for this though.

**Comment by blokovi** [comment]
I really don't know erlang, so I apologize in advance if this doesn't make sense, but can you check this line of code:
https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_websocket.erl#L171

So, when SubProtocols is list then `select_protocol` should be called, but to me it doesn't look like it is called in that case.

**Comment by ioolkos** [comment]
@blokovi that's what's called a guard sequence, 2 conditions ORed (";") together, so this should work.

**Comment by varnerac** [comment]
I think I found the bug. The code [here](https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_websocket.erl#L171-L178) needs to split the `sec-websocket-protocol` header value on `,` to break down the list. I am working on a patch and tests.

**Comment by varnerac** [comment]
PR up
