### ISSUE TITLE
How to config the user name and password

### ISSUE THREAD

**Issue by nitan2001** [vernemq/vernemq#1621]
Good day,

I am configuring my local mqtt broker in debian.
Could anyone give some advice of how to config the user name and password?

I check the link of it as below, but it only supports of how to create a new user, but no password configuration.
Thank you.

https://docs.vernemq.com/configuration/file-auth

**Comment by ioolkos** [comment]
@nitan2001 example:
`vmq-passwd -c /etc/vernemq/vmq.passwd henry` will ask you for a password to add for user henry.

**Comment by nitan2001** [comment]
Thank you @ioolkos.
It makes sense.
