### ISSUE TITLE
The client can't be connected to the MQTT broker over TLS with the self-signed cert file.

### ISSUE THREAD

**Issue by nitan2001** [vernemq/vernemq#1622]
### Environment

- VerneMQ Version: Latest
- OS: debian 

SSL: enabled
name/password: enabled

### Actual behaviour
- The client can't be connected to the MQTT broker over TLS with the self-signed cert file.

I can see the message from wireshark:
1) client hello
2) server hello, certificate
3) alert: fatal, description: handshake failure

What I have done:
I tried to add my cert to be trusted by openssl.

Thank you!!

**Comment by ioolkos** [comment]
@nitan2001 Thanks, I don't really see an effective way of helping out here. Can you open a connection to the server with the same cert using openssl's client?

**Comment by nitan2001** [comment]
@ioolkos Thanks for your hint. 
The openssl is a little bit confused.
It works now, while the failure before was caused by the incorrect certificate.
