### ISSUE TITLE
High-Availability Support and Assumptions

### ISSUE THREAD

**Issue by Ju-Ru** [vernemq/vernemq#1628]
Hello, I posted the following questions as part of an old issue (https://github.com/vernemq/vernemq/issues/1577), but did not get an answer. So I wanted to bring them up again...

Just to verify my assumptions, here some statements and questions:
- Sessions are not synchronized among nodes to cope with ungraceful leaves. Having such a feature would mean some kind of copy of sessions that would be kept at other nodes or a backend that could be used to take over in case of node failures or netsplits. This is not the case currently as far as I understand your documentation and comments above. This implies that any undelivered QoS 1/2 messages of a session are lost if the node is gone forever. 
- However, if a node returns from a time of absence (let us assume all clients connected to other nodes in the meantime with all allow_*_during_netsplit options being enabled and clean_session=false), the session information is synced among the nodes and eventually becomes consistent.  

What does consistent in the second case mean? 
- Would all QoS 1/2 messages be eventually delivered? I understood that this cannot be guaranteed in all cases because of the "window of uncertainty" between failure and detection of the failure. But besides that, would all messages be delivered if the window is very small?
- Obviously, ordering of messages would not be maintained, right? Some offline messages that were kept by the temporally offline node would be delivered just out of sequence once the node is online again.  
- What would actually happen to merge two sessions? (the old and the new one) 

Thanks a lot in advance for your answers! It seems that high-availability settings are not in the focus of most MQTT cluster designs. Do you have any plans to extend VerneMQ in this respect?

_Originally posted by @Ju-Ru in https://github.com/vernemq/vernemq/issues/1577#issuecomment-680079981_

**Comment by jhhurwitz** [comment]
Really interested in the replication aspect of the question above. We are in the midst of comparing MQTT brokers, and it seems that VerneMQ could really benefit from a feature like https://www.hivemq.com/docs/hivemq/4.4/user-guide/cluster.html#replication to better cope with node failure (unless I'm misunderstanding that feature)

**Comment by ioolkos** [comment]
@jhhurwitz I'd be quicker in answering if you provide information what you mean by "a feature like" and providing a link that is btw more or less unclear on how replication is done (is it to all cluster nodes? is it to 2 cluster nodes?)

VerneMQ replicates everything except delivered offline messages. (for those it has queue migration). And yes, something like mirrored queues or quorum queues might come in the future. (Mind you, those have their own drawbacks).

**Comment by jhhurwitz** [comment]
@ioolkos, I was referring to a feature like mirrored queues, glad to hear you're thinking about it already. Thanks!
