### ISSUE TITLE
Improve Bridge internal publish for Pull bridges

### ISSUE THREAD

**Issue by ioolkos** [vernemq/vernemq#1632]
A pull bridge will pull messages from another broker and re-publish them to local topics. The Bridge plugin uses the `vmq_reg` `direct_plugin_exports`. The bridge plugin does not configure the PublishFun with a specific QoS, so it basically uses QoS 0 for internal publishs. This might come as a surprise to offline consumers on that broker, who will not see incoming messages stored in their queues.

We could solve this by doing one of the following:

- Select a QoS globally for a pull bridge.
- Publish with the same QoS that the bridge is subscribing to the remote broker
- Publish with the same QoS as the original Publish

Implementation complexity increases as listed.

**Comment by elduds** [comment]
This is a major issue for our deployment and means vernemq is effectively unviable for our requirements.

1.     Select a QoS globally for a pull bridge.
2.     Publish with the same QoS that the bridge is subscribing to the remote broker
3.     Publish with the same QoS as the original Publish

I think most administrators would expect the default behaviour to be 3, in combination with the normal rules for QoS resolution  ie. 
- if publish q=0, subscribe q=0, then local publish q=0
- if publish q=1, subscribe q=0, then local publish q=0
- if publish q=0, subscribe q=1, then local publish q=0
- if publish q=1, subscribe q=1, then local publish q=1

1 & 2 would be sufficient in the meantime

**Comment by ioolkos** [comment]
@elduds I'm evaluating all options. From what I understand, the Mosquitto bridge as an example implements behaviour 2.

Intuitively, it might be the best approach. It gives control to the subscriber and takes into account the bridge as a special MQTT pub/sub component.

**Comment by ioolkos** [comment]
Did a quick verification with https://github.com/vernemq/vernemq/pull/1629
This works, messages are stored offline on target broker, in case the bridge subscription is configured with QoS > 1. 
This implements option 2 above.

One remaining thing: if the original Publisher sends a QoS = 0 message, the message will also be stored offline on the bridge target broker. It's quite debatable whether this should happen or not. I think not.

**Comment by ioolkos** [comment]
Resolved by https://github.com/vernemq/vernemq/pull/1629.
This implements behaviour 2 above, effectively normalising all messages to the QoS that the bridge subscriber wants for that topic.
As the subscriber doesn't have access to the Publisher QoS, this is the easiest to implement.
