### ISSUE TITLE
Debugging bridge connections

### ISSUE THREAD

**Issue by steve999lee** [vernemq/vernemq#1640]
More of a question than an issue so apologies if this is not the right place...

I'm having a few issues connecting 2 vernemq instances (on the same machine) via a bridge.
I have log-level debug but I am seeing no messages to tell me if the bridge connection was successful - I assume not as messages are not being received.

./bin/vmq-admin bridge show - tells me there is a bridge but I dont see any session on the remote broker.

Defining a bridgebetween mosquitto and vernemq works fine and I see the session on the remote broker (although still no debug)

Any tips for how I can find out what is going on?

**Comment by ioolkos** [comment]
@steve999lee what's the bridge configuration? what's your VerneMQ release version?

**Comment by steve999lee** [comment]
Thanks for the swift reply 
Version was 1.10.2

Actually its working now - naturally it was my misconfiguration of the bridge.
When it did connect I saw this....

12:26:56.983 [debug] connected to: 127.0.0.1:20103

and then did see the session on the remote machine

The misconfig...

I had a mixture of settings for the same bridge

vmq_bridge.tcp.br0
vmq_bridge.ssl.br0

Fantastic broker - thankyou
