### ISSUE TITLE
Plugins not chaining

### ISSUE THREAD

**Issue by rubengees** [vernemq/vernemq#1642]
### Environment

- VerneMQ Version: `1.10.5`
- OS: Linux
- Erlang/OTP version (if building from source): `erlang:23-alpine`
- Cluster size/standalone: 1

### Expected behaviour

(Lua) plugins to chain when one of them returns `false`.

### Actual behaviour

Plugins do no chain and only have the behaviour of the plugin first loaded.

### Details

I wrote a `custom.lua` plugin that should add some additional logic to the postgres auth plugin. I want this plugin to run before the postgres plugin and if it does not match continue with the normal postgres auth flow.

My plugin looks like this (while playing around):

```lua
log.info("Plugin loaded!")

function auth_on_register(reg)
    if reg.client_id == "test" then
        return true
    else
        return false
    end
end

function auth_on_publish(pub)
    return true
end

function auth_on_subscribe(sub)
    return true
end

hooks = {
    auth_on_register = auth_on_register,
    auth_on_publish = auth_on_publish,
    auth_on_subscribe = auth_on_subscribe,
    auth_on_register_m5 = auth_on_register,
    auth_on_publish_m5 = auth_on_publish,
    auth_on_subscribe_m5 = auth_on_subscribe
}
```

That plugin is loaded as well as the postgres plugin, which I verified by looking at the logs:

```
14:44:02.859 [info] Plugin loaded!
14:44:02.860 [info] enable auth script for postgres "./share/lua/auth/postgres.lua"
```

Due to the custom plugin being loaded first, no clients which are known in the db but not being "test" can be authenticated. If I remove the custom plugin, the postgres auth works as expected (but now of course not allowing "test").

I read [this](https://docs.vernemq.com/plugindevelopment/introduction#chaining) part of the docs as if I return false, the next plugin is tried.

Does this work in another way, am I loading my script wrong or is there something broken in VerneMQ?

**Comment by ioolkos** [comment]
Hi @rubengees 
https://github.com/vernemq/vernemq/issues/1199#issue-448993989 but you have to thank the investigation of @puresilk here.

I was under the impression you'd have to "return next" in Lua script, but as per the above analysis it works when you return... nothing.
Can you check both cases?

**Comment by rubengees** [comment]
I tried both and both work (I prefer `return next` though)! Thanks @puresilk and @ioolkos.

It would be _really_ great if this could be added to the docs. Would you be interested in a PR for this?

**Comment by ioolkos** [comment]
>It would be really great if this could be added to the docs. Would you be interested in a PR for this?

@rubengees jep, thanks! :)
