### ISSUE TITLE
Wrong config parameter mentioned in comment in vmq_diversity.schema

### ISSUE THREAD

**Issue by micw** [vernemq/vernemq#1643]
Hello,
in https://github.com/vernemq/vernemq/blob/master/apps/vmq_diversity/priv/vmq_diversity.schema#L377-L390
The comment tells about `vmq_diversity.<name>.plugin` but the code says `vmq_diversity.<name>.file`. The comment needs to be fixed.

**Comment by ioolkos** [comment]
@micw thanks! (fixed it)
