### ISSUE TITLE
VerneMQ concurrency model

### ISSUE THREAD

**Issue by carpino** [vernemq/vernemq#1654]
I'm interested in knowing what is the concurrency model in VerneMQ. I don't have found information in the documentation on how the concurrency is managed. It is used a thread for each connection, it is used a thread pool with fixed size? Tide to this, does publishing influence the receiving? That is, in case of high number of publishing per second is the receiving throughput influenced by this? Thanks for answering

**Comment by ioolkos** [comment]
Let us know when you need more information. I'm closing this in favour of discussion on Googlegroups.
