### ISSUE TITLE
Postgres max pool size option not honored

### ISSUE THREAD

**Issue by rubengees** [vernemq/vernemq#1656]
### Environment

- VerneMQ Version: 1.11.0
- OS: Linux
- Erlang/OTP version (if building from source): `erlang:23-alpine`
- Cluster size/standalone: 1

### Expected behaviour

VerneMQ should use the given `vmq_diversity.postgres.pool_size` or `DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__POOL_SIZE` option to limit the database connections to the specified value.

### Actual behaviour

Upon setting `DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__POOL_SIZE` to 1, VerneMQ uses 10 connections to the database (which is already weird because I only see 5 everywhere in the code). Verified by running `SELECT * FROM pg_stat_activity` and looking through the result.

I suspected the option to be written incorrectly, but `cat /etc/vernemq/vernemq.conf | grep "pool_size"` shows `vmq_diversity.postgres.pool_size=1`.

Is this not currently supported properly (I did not found documentation on that apart from [this in the schema](https://github.com/vernemq/vernemq/blob/537049242c8bb30a9dafe77c48e0af67d9ef12b5/apps/vmq_diversity/priv/vmq_diversity.schema#L68)) or is the config wrong?

**Comment by ioolkos** [comment]
Thanks, this is a duplicate for https://github.com/vernemq/vernemq/issues/1269 which got closed without further investigation.
But, ok, so we got double confirmation that this gets 10 connection as a default.
Now the question is whether 10 is just the minimal number (for instance enforced by the PG library), or whether this doesn't respect configs at all (also for config value > 10).

**Comment by rubengees** [comment]
I tried around a bit and it seems the config is not respected at all. When I set it to 20, there were still 10 connections.

I also tried overriding this directly in a lua plugin (by copying the default postgres plugin and adding `size = 1`):

```lua
require "auth/auth_commons"
-- import shared database query logic
require "auth/postgres_cockroach_commons"

function auth_on_register(reg)
    return auth_on_register_common(postgres, reg)
end

pool = "auth_postgres"
config = {
    pool_id = pool,
    size = 1
}

postgres.ensure_pool(config)
```

This also does not change the behaviour.

One interesting effect I saw though is, that my plugin is now run 10 times. I have a log statement at top which normally has been printed only once but now 10 times. Not sure if that connected to the issue.

Is there any known workaround or do you have any idea how I can investigate this further?

**Comment by rubengees** [comment]
Looks like the 10 comes from here: https://github.com/vernemq/vernemq/blob/master/apps/vmq_diversity/src/vmq_diversity_sup.erl#L109

I can't really read erlang, but it seems that this file is the culprit.

**Comment by ioolkos** [comment]
Technically, it's in the function clause for postgres: https://github.com/vernemq/vernemq/blob/0b4dc58686dc2b72f781d430b72aaf682f202ef9/apps/vmq_diversity/src/vmq_diversity_sup.erl#L74

But your totally right. The ProviderConfig there comes in over the `vmq_diversity_postgres.erl`, but `size` simply gets reset to default.

Do you want to have a go at it? Can fix it myself, but low prio ;)

**Comment by ioolkos** [comment]
Note to self: we could upgrade to and test `epgsql 4.4.0`, instead of `4.3.0`
https://github.com/epgsql/epgsql/tags

**Comment by rubengees** [comment]
Did a PR [here](https://github.com/vernemq/vernemq/pull/1657). Seems to work in my environment, but not sure if this has any unintended side effects.
