### ISSUE TITLE
Unexpected behavior when using 2 listeners with different configuration

### ISSUE THREAD

**Issue by mladen-djordjevic** [vernemq/vernemq#1658]
As stated in the documentation, besides global broker configuration, there is a configuration **per listener** as well.
I am trying to use 2 listeners with different config:
- first one (name _client_, port _8888_) should use client certificates for authentication
- second one (name _basic_, port _8889_) should **NOT** use client certificates but username and password for authentication

### Environment

- VerneMQ Version: 1.10.2 and 1.10.4.1
- OS: any
- Erlang/OTP version (if building from source): /
- VerneMQ configuration (vernemq.conf) or the changes from the default:
...
listener.ssl.client=0.0.0.0:8888
listener.ssl.basic=0.0.0.0:8889
listener.ssl.client.keyfile=/vernemq/data/certs/vernemq-localhost.key
listener.ssl.client.certfile=/vernemq/data/certs/vernemq-localhost.crt
listener.ssl.client.cafile=/vernemq/data/certs/vernemq-chain.pem
listener.ssl.client.require_certificate=on
listener.ssl.basic.require_certificate=off
...
- Cluster size/standalone: standalone

### Expected behaviour

Clients on port 8888 should authenticate with client certificates, clients on port 8889 should authenticate with username and password

### Actual behaviour

For both listeners client certificate is required

**Comment by ioolkos** [comment]
@mladen-djordjevic thanks... how do you actually see that the client cert is required for second case?

**Comment by ioolkos** [comment]
Actually, I see that you haven't configured server certs for the 'basic' listener at all, so this shouldn't even work.

**Comment by mladen-djordjevic** [comment]
In addition to the previous configuration, I have tried with server certs for 'basic' listener as well:
...
listener.ssl.basic.keyfile=/vernemq/data/certs/vernemq-localhost.key
listener.ssl.basic.certfile=/vernemq/data/certs/vernemq-localhost.crt
listener.ssl.basic.cafile=/vernemq/data/certs/octopus-chain.pem
...

But the outcome is the same.

**Comment by ioolkos** [comment]
@mladen-djordjevic what is your measure for the outcome? A Verne log line?

**Comment by mladen-djordjevic** [comment]
I am testing the above scenario from 2 places:
- using MQTTFX application as MQTT client
- using custom-developed Java application as MQTT client (with paho library)

So, when I try to connect to the listener that doesn't require client certificate (_basic_) in both scenarios I am receiving:
**unable to find valid certification path to requested target**

**Comment by ioolkos** [comment]
I guess you have done the same and googled that. seems to indicate that Java does not want to connect to a service with a self-signed server cert. 
But then why would your first listener work, but not the second.

**Comment by mladen-djordjevic** [comment]
And the final outcome is that both listeners require client certificate for authentication and I can authenticate it on both of them. But my desired state is that I can connect to the _basic_ listener without a client certificate, but I cannot make it work on this way (yet)

**Comment by ioolkos** [comment]
Ok. That server certs are self-signed though, right?
Can you try with the `--insecure` option of `mosquitto_sub`?

I think what you want to do should work. Be aware of an additional catch: there is no per-listener configuration of authentication. Authentication is switched off or on globally, with `allow_anonymous`. 

So for your second listener, you'd need that on `off`. This means for your first listener that you still have to provide a username/password (but the server will check the client cert, of course).

**Comment by mladen-djordjevic** [comment]
Hi again.

At the moment I cannot answer on the questions above, since we gave up the solution with 2 listeners and using only 1 listener with client certificates.

This issue can be closed.

**Comment by ioolkos** [comment]
@mladen-djordjevic Okay, thanks for your feedback!
