### ISSUE TITLE
Python loss message when on_message function handling message too much time

### ISSUE THREAD

**Issue by ducpx** [vernemq/vernemq#1660]
I used the default config on the one vernemq server with the latest version.
The python worker subscribes to all topics. Publishers publish a message to the topic itself. In on_message of the worker to spend a long time handling message. If other publishers send a message while the worker handles, the worker will lose the message.
Do you have any idea about the issue?

**Comment by ioolkos** [comment]
@ducpx thanks, I'm not sure how to help here, as `on_message` is a callback in the client library, not the server. You're likely using the Paho Python client, so maybe investigating this over here https://github.com/eclipse/paho.mqtt.python will be quicker.

**Comment by ducpx** [comment]
@ioolkos yep, I use paho lib to test publisher and subscriber. The worker is the subscriber.
