### ISSUE TITLE
Changed MongoDB lua script need confirmation on the impact of it

### ISSUE THREAD

**Issue by achandana** [vernemq/vernemq#1661]
### Environment

- VerneMQ Version:vernemq/vernemq:1.10.3
- OS:Kubernate
- Erlang/OTP version (if building from source):N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default:
- Cluster size/standalone:3nodes (as tested)

We have enabled the DB authentication for Vernemq. As per the document for DB authentication client id is mandatory. 
We are using Fiware IoT agent to receive measurements, like from device to Vernemq and vernemq will send measurements to IoT agent. So for IoT agent there is no option to give client id but having option to configure username and password .

To bypass the validating IoT agent client id, we have changed the mongodb.lua file in share folder as below : 
```lua
 local iotagentflag
    if reg.username ~= nil and reg.username == "username" then
       iotagentflag = true
    end
    if reg.username ~= nil and reg.password ~= nil then
        if iotagentflag == true then
           doc = mongodb.find_one(pool, "vmq_acl_auth",
                                {mountpoint = reg.mountpoint,
                                 username = reg.username})
           log.info("ignoring iotagent client *********")
        else
           doc = mongodb.find_one(pool, "vmq_acl_auth",
                                {mountpoint = reg.mountpoint,
                                 client_id = reg.client_id,
                                 username = reg.username})
           log.info("normal flow *********")
        end
```
We want confirmation that with this changes,is there any impact on Vernemq functionality.

**Comment by ioolkos** [comment]
Functionally VerneMQ doesn't care what you do in an auth plugin. The broker component just needs an answer whether some action is allowed or not.
