### ISSUE TITLE
Broker drops messages for clients with offline queue > max_online_messages

### ISSUE THREAD

**Issue by elduds** [vernemq/vernemq#1663]
This is a continuation of the discussion on vernemq-users mailing list:

(https://groups.google.com/g/vernemq-users/c/H59b4ygcbm8/m/2z_9Ygv2AgAJ)

### Environment

- VerneMQ Version: 1.11.0
- OS: Ubuntu 18.04 amd64
- Erlang/OTP version (if building from source): all
- VerneMQ configuration (vernemq.conf) or the changes from the default
max_online_messages = 75000
max_offline_messages = 76276800

### Expected behaviour

When a client with a large number of messages in their offline queue (> max_online_messages) reconnects after some time, all offline messages should be reliably delivered to the client.

### Actual behaviour

When the client comes online, *all* of their offline messages are loaded into the online queue. If the number of messages in their offline queue exceeds the broker's max_online_message value, then they receive max_online_messages quantity of messages however the remaining messages are all dropped.

This effectively means that the size of the offline queue is constrained to the size of the broker's RAM (max_online_messages) rather than the size of the broker's disk (max_offline_messages).

**Comment by ioolkos** [comment]
Thanks, @elduds.

We have a blog post here on improving startup time after a broker reboot: https://vernemq.com/blog/2019/07/31/vernemq-startup-time-improvements.html
This is not the same situation as described in the current issue, but somewhat related. It seems that there is one more optimisation we should do. We do batch or "stream" the delivery from the loaded online queue to the re-connecting consumer as described in the blog post, but we do not "stream" the loading of the online queue from the offline queue.

**Comment by rtuin** [comment]
Hi, I'm running into exactly the problem described by @elduds.

How can this be solved within verneMQ, would the "stream" from offline into online queues be hard to implement?
And is there a sensible work-around?

**Comment by ioolkos** [comment]
@rtuin thanks, the only existing workaround currently is that `max_online_messages` is not configured to a lower value than `max_offline`.
A streaming approach is not that low-hanging, in my opinion. What we can do is to specifically look into the state change from offline to online, and kind of exceptionally allow larger online queues. (if enough RAM available).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by rtuin** [comment]
@ioolkos agreed that the amount of available RAM remains the limited factor here. I find it tricky to calculate an appropriate amount of RAM to reserve for this case. The best I can think of is to do the math based on over-the-wire message size but this is not realistic.
Can the size of the offline messages be found somewhere in vmq-admin, stats or filesystem maybe? This would help calculate the required setup.

**Comment by dometec** [comment]
Same issue here. Why don't move messages from offline queue to online queue in chunks?

**Comment by ioolkos** [comment]
> Same issue here. Why don't move messages from offline queue to online queue in chunks?

Because so far, there's no actual implemented code doing that. :wink:

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
Fixed by https://github.com/vernemq/vernemq/pull/2143
