### ISSUE TITLE
vmq-admin not working on an IPv6 cluster

### ISSUE THREAD

**Issue by joliver82** [vernemq/vernemq#1664]
I've setup a cluster with two nodes using ipv6 

### Environment

**VerneMQ Version**: 1.10.0
**OS**: Dockerized alpine 3.9.4
**Cluster size**: 2 nodes

**VerneMQ configuration**:

Just changed listeners to the proper IPv6 addresses and added "-proto_dist inet6_tcp" to vm.args for erlang distribution to listen to ipv6

Node1 vernemq.conf:
listener.tcp.default = 2f01::8:1883
listener.vmq.clustering = 2f01::8:44053
listener.http.default = 2f01::8:8888
listener.ws.default = 2f01::8:8080

Node1 vm.args:
+P 256000
-env ERL_MAX_ETS_TABLES 256000
-env ERL_CRASH_DUMP /erl_crash.dump
-env ERL_FULLSWEEP_AFTER 0
-env ERL_MAX_PORTS 65536
+A 64
-setcookie vmq
-name VerneMQ@2f01::8
+K true
+W w
-smp enable
+zdbbl 32768
-proto_dist inet6_tcp

Node2 vernemq.conf:
listener.tcp.default = 2f01::d:1883
listener.vmq.clustering = 2f01::d:44053
listener.http.default = 2f01::d:8888
listener.ws.default = 2f01::d:8080

Node2 vm.args:
+P 256000
-env ERL_MAX_ETS_TABLES 256000
-env ERL_CRASH_DUMP /erl_crash.dump
-env ERL_FULLSWEEP_AFTER 0
-env ERL_MAX_PORTS 65536
+A 64
-setcookie vmq
-name VerneMQ@2f01::d
+K true
+W w
-smp enable
+zdbbl 32768
-proto_dist inet6_tcp
-eval "vmq_server_cmd:node_join('VerneMQ@2f01::8')"

### Expected behaviour

vmq-admin cluster show to work properly showing something like
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@2f01::8| true  |
|VerneMQ@2f01::d| true  |
+--------------------+-------+

And every other vmq-admin command to work

### Actual behaviour

When running any vmq-admin command it just states that the node you're running it is not responding to pings:

node1# vmq-admin cluster show
Node 'VerneMQ@2f01::8' not responding to pings.

Anything you try with vmq-admin just fails with the same error
node1# vmq-admin bad-command
Node 'VerneMQ@2f01::8' not responding to pings.

Everything is listening either to the proper ipv6
node1# netstat -nalp |grep 126 |grep LISTEN
tcp        0      0 2f01::8:8080            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:44053           :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:8888            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1883            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1884            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1885            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1886            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1887            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1888            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1889            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1890            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1891            :::*                    LISTEN      126/beam.smp
tcp        0      0 2f01::8:1892            :::*                    LISTEN      126/beam.smp
tcp        0      0 :::9100                 :::*                    LISTEN      126/beam.smp

or in the case of port 4369 to all ipv4 and ipv6 addresses
node1# netstat -nalp |grep 205
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      205/epmd
tcp        0      0 :::4369                 :::*                    LISTEN      205/epmd

The nodes linked properly on boot:

Logs on node1:

17:16:32.106 [info] successfully connected to cluster node 'VerneMQ@2f01::d'
17:16:32.267 [info] completed metadata exchange with 'VerneMQ@2f01::d'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 2 keys

Logs on node2:

17:16:32.111 [info] successfully connected to cluster node 'VerneMQ@2f01::8'

In fact publishing and subscribing to any node works as it should. It's just the admin tool which fails

**Comment by ioolkos** [comment]
@joliver82 thanks, good catch. Need to see how to make the `vmq-admin` script and the RPCs it's doing understand IPv6.

**Comment by joliver82** [comment]
Thanks @ioolkos If you need any further testing just ask. Just in case it helps you, each vmq-admin execution generates traffic to 127.0.0.1:4369 (not ::1), the connection is established but I altough don't know what happens inside, I think the issue could be there...

**Comment by ioolkos** [comment]
Need something similar, so that CLI (`vmq-admin`) can work over IPv6
https://www.rabbitmq.com/networking.html#distribution-ipv6

**Comment by ioolkos** [comment]
@joliver82 could you test PR https://github.com/vernemq/vernemq/pull/1666?
ie. check if calls like this work:

`sudo vmq-admin session show -kernel proto_dist inet6_tcp`

**Comment by joliver82** [comment]
Just tested it and I'm getting the same response (not responding to pings)

**Comment by ioolkos** [comment]
@joliver82 thanks for testing. okay... so this was the wrong approach :)

**Comment by ioolkos** [comment]
Update in PR: you can now add `erlang.distribution.proto_dist = inet6_tcp` to the `vernemq.conf` file. This is mainly to not have to use a separate `vm.args` file.
The RPC (ie `vmq-admin`) still does not work automatically though.

**Comment by ioolkos** [comment]
In theory this commit  https://github.com/vernemq/vernemq/pull/1666/commits/465277d36d2558a7086a3f6d6fa671caf4f51848 should pull the `proto_dist` config from the current environment (via `env.sh`) and add it to `nodetool`.
In practice it doesn't work, but I don't know why yet.

**Comment by AmnaSnene** [comment]
I'm facing a similar issue. When I change the name of the node to `vernemq@ipv6_addr`, the node fails to start. I added `erlang.distribution.proto_dist = inet6_tcp ` to the `vernemq.conf` file but it's not working. What I should do?

**Comment by ioolkos** [comment]
@AmnaSnene does the node log anything useful at boot?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
