### ISSUE TITLE
Retained messages are not kept on restart

### ISSUE THREAD

**Issue by rubengees** [vernemq/vernemq#1674]
### Environment

- VerneMQ Version: `1.11.0`
- OS: `erlang:23-alpine`
- Erlang/OTP version (if building from source): `23`
- Cluster size/standalone: 3

### Expected behaviour

If all VerneMQ instances in a Kubernetes cluster are restarted, retained messages should be kept.

### Actual behaviour

If I restart all VerneMQ instances in my Kubernetes cluster (either by rolling release or manually by `kubectl rollout restart statefulset vernemq`) retained messages are lost.

We do not have a persistent volume, but are using cluster leave (which works properly for normal offline messages). The retained messages are published with QoS 2 and work as expected until a restart.

Is this expected behaviour? If yes, is there anything we can do to retain messages even after restarts?

**Comment by ioolkos** [comment]
@rubengees thanks, that's strange. Retained messages should be there as part of the metadata state.
But it's strange in two ways: the offline messages shouldn't be there either. You mention you don't have persistent volumes at all?
Note that I do not know whether there's any possible isuses with the `rollout` command currently (and the question of cluster leave etc).

**Comment by rubengees** [comment]
Yes, that's really weird. Offline messages are synced on cluster leave from what I see (note we do only rolling releases. That means at least one instance is available at all times during the release. That is also exactly what the rollout command does/simulates).

I tested that by sending a message to an offline client and ran the command above. The order of events was as follows:

- vernemq-1 terminated
- vernemq-1 started
- vernemq-0 terminated
- vernemq-0 started

Once I started the client again it received the message.
The same test consitently loses retained messages.

One interesting thing I noticed though is that if the client subscribed on the topic for the retained message would be offline, it would receive the retained message after the broker restarts. But only this one time and after that the retained message is lost.

We do not have persistent volumes since that does not work with autoscaling.

**Comment by ioolkos** [comment]
Please check that the behaviour is within the semantics of retained messages. When you say "after that the retained message is lost", you're making sure you test with new subscribers?

**Comment by rubengees** [comment]
Okay, so I tested this further.

The same case as above, but with different subscribers. No matter what I do, after all instances have been restarted once, I do not get the retained message on whatever subscriber that I try. I still get it once on subscribers that were online before (due to the message being an offline message apparently).

Is there anything else that I can test or otherwise provide information? We rely on retained messages being avaiable at all times currently.

**Comment by ioolkos** [comment]
Are we talking lots of retained messages? what does `sudo vmq-admin retain show` tell?
Does the status page (or the metrics show matching numbers on retain messages?).

I'm thinking towards state replication here. Let's say the last node has state and it takes time to replicate.

**Comment by rubengees** [comment]
No, I am testing with a single message (everytime reproducable) and in our real environment we also have less than 100.

`vmq-admin retain show` before restart:

```
bash-5.0$ vmq-admin retain show
+---------+----------------+
| payload | topic          |
+---------+----------------+
| xyz     | internal/test2 |
+---------+----------------+
```

Status page before restart:
![Bildschirmfoto von 2020-11-17 16-44-22](https://user-images.githubusercontent.com/8021265/99412193-bd6b7700-28f4-11eb-90a9-ae23e0e70129.png)

`vmq-admin retain show` after restart has no output.

Status page after restart:
![Bildschirmfoto von 2020-11-17 16-47-54](https://user-images.githubusercontent.com/8021265/99412209-c2c8c180-28f4-11eb-8be5-3f312c8b28eb.png)

**Comment by ioolkos** [comment]
Ok, so that's confirmed by you. Could be another effect of that leave/stop issue with Verne/Kubernetes.
We should stop the nodes here only, not make them leave.

**Comment by ioolkos** [comment]
To be more specific: can you test without this line?
https://github.com/vernemq/docker-vernemq/blob/f3f5b794abe827eeb2ebb4cfbc1722d4f3aa6645/bin/vernemq.sh#L160

**Comment by rubengees** [comment]
Yes, just tried that. I see the same behaviour in regard to retained messages.

Same scenario as above and verified by connecting with a client and checking `vmq-admin retain show`.

I can also setup a simple reproducer if that helps.

**Comment by ioolkos** [comment]
Okay, yes please do.

**Comment by rubengees** [comment]
Here it is: https://github.com/rubengees/vernemq-retained-messages

**Comment by ioolkos** [comment]
@rubengees thanks! I could not yet look at your test but I had done a test with a local script as follows (which works).

Not sure it represents exactly what you do in K8s. Here:
- start node 0 and 1 and cluster them
- PUBLISH a retain message
- check retain message is there with `vmq-admin retain show`
- stop and start node 0
- stop and start node 1
- check retain message is there with `vmq-admin retain show`
- have 2 SUBSCRIBERS connect to the nodes and get the retain message
- check in status page for 2 subscriptions and 1 retain message.

```shell
#!/bin/bash

VMQ_SRC=$PWD
NODE_0="dev0@127.0.0.1"
NODE_1="dev1@127.0.0.1"

# initial cleanup
pkill mosquitto_sub

cd $VMQ_SRC/_build/dev0/rel/vernemq
./bin/vernemq stop
rm -rf data
cd $VMQ_SRC/_build/dev1/rel/vernemq
./bin/vernemq stop
rm -rf data

sleep 10

# running node 0
cd $VMQ_SRC/_build/dev0/rel/vernemq
./bin/vernemq start

sleep 3

# running node 1 and creating a cluster
cd $VMQ_SRC/_build/dev1/rel/vernemq
./bin/vernemq start
./bin/vmq-admin cluster join discovery-node=$NODE_0

sleep 5

# publish a retained message

mosquitto_pub -d -i c2 -p 10053 -t hello -m "Hello with Retain" -r -q 2 &

# check the retained message is stored
./bin/vmq-admin retain show

# stop node 0
sleep 5
cd $VMQ_SRC/_build/dev0/rel/vernemq
./bin/vernemq stop

sleep 15

# start node 0
./bin/vernemq start

cd $VMQ_SRC/_build/dev1/rel/vernemq

sleep 25

# stop node 1
./bin/vernemq stop

sleep 15

# start node 1
./bin/vernemq start

sleep 25

# check for retain message
./bin/vmq-admin retain show

# subscribe on both nodes to get retain message
mosquitto_sub -d -i c0 -p 10053 -t hello &
sleep 10

mosquitto_sub -d -i c1 -p 10003 -t hello &

# check status page for 2 subscribers and 1 retain message

echo "Finished. Check Status page http://localhost:10020/status"
```

**Comment by rubengees** [comment]
This looks like the exact same that is happening on k8s. What could be the difference?

**Comment by ioolkos** [comment]
Yes, for a local stop and restart, state will be read from disk. I don't know what happens in your K8s case regarding persistent volumes but that' be interesting to know.

But let's say we'd stop a node, delete it's state, and then start again AND rejoin the other node (rejoining should be idempotent anyway). This is an unusual procedure, but I guess this will still synchronise.

**Comment by ioolkos** [comment]
I just tested that the script above also works when state is deleted. As only 1 broker is down at any point in time, this is re-syncronised correctly. The starting broker have to re-join (as deleting state also deletes their cluster awareness), and I threw in ample sleep times to ensure synchronisation.

It's clear there's lots of room for improvement here. Notably some form of API on the state of synchronisation, or at least a 'fully synced' state API. With that, a Kubernetes operator could handle the rolling in a more controlled way. 
Regardless of that, keeping state around on persistent volumes seems safer and faster in any case.

**Comment by rubengees** [comment]
Ah, I see! So this is this issue right? https://github.com/vernemq/docker-vernemq/issues/255

> Keeping state around on persistent volumes seems safer and faster in any case.

I agree, but I was having problems in this case:

Three instances of VerneMQ running. One instance is shut down (for example by a `HorizontalPodAutoscaler`) and never started again. The messages on that node will never be delivered.

If it were restarted, but after a significant amount of time would the database be out of sync?
I had problems of VerneMQ not starting when having cluster leave and persistent volumes which is why I am not having persistent volumes in the first place.

**Comment by ioolkos** [comment]
I guess that's the same issue, yes.

It's all related anyway. Operational model of Kubernetes and Stateful sets vs Verne operational model. K8s terminates pods. Offers you a timeout before SIGKILL, and offers you to keep state or not. Well, okay, but we'd like to differentiate between a stop (rescheduling) and a leave (scale down). We'd like to synchronise.
Anyway, I decided to change that famous L160 mentioned above. At least this will not leave you with nodes that left the cluster and want to re-join with state (which is not possible, re-joins have to be done with empty state).

Thanks for your efforts on this! :)

**Comment by rubengees** [comment]
Yes, that's what makes it hard to have clustering on k8s I guess :smile:.

So the recommended approach after the change is to have persistent volumes like before and not doing cluster leave then? Does that work in the case that one instance is shut down forever or is that a separate issue?

Sure, thank you for your time also!

**Comment by ioolkos** [comment]
After the change every SIGTERM will only stop the node, yes.
To have a proper scale down, you'd have to kick out the stopped nodes after termination, in an additional step (manual for now)

**Comment by rubengees** [comment]
I see. Manual would mean:

- Run `cluster_leave`.
- Delete the persistent volume.

right?

I guess this makes autoscaling impossible until k8s implements something like the "drain pods" I have been reading about. Is it worth to add that to the docs somewhere (and remove the autoscaler from the helm chart)?

**Comment by ioolkos** [comment]
I guess so... I'm a VerneMQ expert, not a K8s expert :)

**Comment by rubengees** [comment]
I'm neither :grin:!

Thank you again for your time, this was really helpful! I guess this can be closed since the original issue is already tracked in vernemq/docker-vernemq#255 except if you want to track the possible documentation improvements with this.
