### ISSUE TITLE
Pre-shared key support

### ISSUE THREAD

**Issue by FabianGoettl** [vernemq/vernemq#1675]
Hello,
are there any plans about supporting Pre-Shared Key (TLS-PSK) encryption for MQTT clients in VerneMQ?
I have seen that PSKs are supported for MQTT bridges (vmq_bridge), but the listener config (listener) misses this feature.

PSKs have the advantage that they are easy to deploy, do support devices with low-computation power and their validity is not based on the system time. 

In the moment, we use the PSKs on Mosquitto and would like to switch to Vernemq.

**Comment by ioolkos** [comment]
@FabianGoettl thanks for your suggestion. I actually need to check what's (not) implemented.

pinging @varnerac for an opinion: is pre-shared keys a feature that's useful and widely used, from a security perspective? (I don't see it widely used, but I think it's useful)

**Comment by varnerac** [comment]
I think there are places that use it in MQTT when you have clients with minimal processing power or trying to save battery life. It looks like `crypto` supports PSK.

**Comment by ioolkos** [comment]
@varnerac good point, thanks!

**Comment by michael-sayapin** [comment]
+1 for this feature, we connect to MQTT from an embedded device with <50K free memory, and adding full-fledged SSL would not fit. Currently have to connect to mosquitto and bridge `#` in `both` directions.

**Comment by moorchegue** [comment]
Is there any development in this direction?

**Comment by ioolkos** [comment]
First version of TLS-PSK support was implemented by @mths1, so I'm closing this issue.
Let us know if anyone is going to test/use this.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
