### ISSUE TITLE
Support for encrypted ssl private key

### ISSUE THREAD

**Issue by ursathi** [vernemq/vernemq#1676]
First of all thank you for providing such a wonderful package. 

Here is my issue

I configured for certificate authentication and it works perfectly fine. However, when I decided to encrypt my server key, couldn't find the configuration entry (in vernemq.conf) to key-in the data. 

Tried opening the source code [https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_ssl.erl](vmq_ssl) and found no properties are read. [https://erlang.org/doc/man/ssl.html](Erlang) has the option to get the password

I am just wondering whether such feature is not included with vernemq or I am missing something. Any help would be greatly appreciated

### Environment (details aren't significant. Just filling up)

- VerneMQ Version: 1.10.3
- OS: Ubuntu 20.04
- VerneMQ configuration (vernemq.conf) or the changes from the default: 
listener.ssl.cafile = ./etc/vernerootca.pem
listener.ssl.certfile = ./etc/verneserver.pem
listener.ssl.keyfile = ./etc/verneserver.key
- Cluster size/standalone: standalone

### Expected behaviour
If the SSL key file is encrypted with password, there should be way to specify the password in the config file

### Actual behaviour
Entry to provide the password for the SSL key file is not found in the config file

**Comment by ioolkos** [comment]
@ursathi thanks, I see.
The question is what we do here. Password in `vernemq.conf`, okay, but would that be considered best practice? (or separate password file? or adding password at boot command, probably highly impractical?)
cc @varnerac

**Comment by ursathi** [comment]
Thanks @ioolkos for a quick reply. 

I would suggest to have multiple options, rather than sticking with just the best practices. Like what OpenSSL is doing... While creating the key, it will
1. let the user to provide the password as a parameter
2. allow the user to enter the password during the generation of file
3. accept password from a separate file (best practice)

All the above options may not be directly applicable/possible for vernemq. Just sharing to get some idea

Anyway, is it possible to provide a quick workaround (like getting the password directly from config) before coming up with the final design?

**Comment by ioolkos** [comment]
@ursathi quickest workaround would probably be to add this to the `vernemq.conf` file, by adding a value to the `vmq_server.schema`: https://github.com/vernemq/vernemq/tree/master/apps/vmq_server/priv, and then get the password where needed and do the decryption.
No promises... open to PRs!

**Comment by varnerac** [comment]
Mosquitto has config values for `PSK_FILE` and `PSK_HINT`

**Comment by ursathi** [comment]
Thanks for the updates. Let me hope for the best
