### ISSUE TITLE
VerneMQ Diversity Mongo Authentication Problem

### ISSUE THREAD

**Issue by dtodor** [vernemq/vernemq#1678]
With VerneMQ 1.11.0 (Docker `vernemq/vernemq:1.11.0-alpine`) we are unable to authenticate against a Mongo DB using the Diversity plugin. The problem does NOT exist with VerneMQ 1.10.3 and the same VerneMQ configuration (s. below).

Note: in both cases we use the same Mongo DB version 4.2.7 and database.

### Environment

- VerneMQ Version: 1.11.0
- OS: Docker for macOS
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default

```
ENV DOCKER_VERNEMQ_ACCEPT_EULA="yes"
ENV DOCKER_VERNEMQ_ALLOW_ANONYMOUS="off"
ENV DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST="0.0.0.0:1883"
ENV DOCKER_VERNEMQ_LISTENER__TCP__TEST="0.0.0.0:1884"
ENV DOCKER_VERNEMQ_LISTENER__TCP__TEST__MOUNTPOINT="mp-test"
ENV DOCKER_VERNEMQ_LOG__CONSOLE="console"
ENV DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL="debug"
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_ACL="off"
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY="on"
ENV DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD="off"
ENV DOCKER_VERNEMQ_SHARED_SUBSCRIPTION_POLICY="prefer_local"
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_MONGODB__ENABLED="on"
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__DATABASE="devices"
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__HOST="mongo"
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__LOGIN="******"
ENV DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__PASSWORD="******"
```

- Cluster size/standalone: standalone
- Mongo DB version: 4.2.7

### Expected behaviour

The diversity Mongo plugin can authenticate against the DB and retrieve the ACL records. This is the behavior on VerneMQ 1.10.3.

Note: the Mongo DB version is 4.2.7.

### Actual behaviour

We get the following error:

`
vernemq_1  | 13:30:20.040 [error] gen_server <0.609.0> terminated with reason: {bad_query,#{<<"$err">> => <<"not authorized for query on devices.vmq_acl_auth">>,<<"code">> => 13,<<"ok">> => 0.0}} in mc_connection_man:process_error/2 line 123
vernemq_1  | 13:30:20.041 [error] CRASH REPORT Process <0.609.0> with 0 neighbours crashed with reason: {bad_query,#{<<"$err">> => <<"not authorized for query on devices.vmq_acl_auth">>,<<"code">> => 13,<<"ok">> => 0.0}} in mc_connection_man:process_error/2 line 123
vernemq_1  | 13:30:20.042 [error] Supervisor {<0.466.0>,poolboy_sup} had child vmq_diversity_worker_wrapper started with {vmq_diversity_worker_wrapper,start_link,undefined} at <0.609.0> exit with reason {bad_query,#{<<"$err">> => <<"not authorized for query on devices.vmq_acl_auth">>,<<"code">> => 13,<<"ok">> => 0.0}} in mc_connection_man:process_error/2 line 123 in context child_terminated
vernemq_1  | 13:30:20.043 [error] can't execute find_one [{<<"mountpoint">>,<<"mp-test">>},{<<"username">>,<<"DEV000001">>}] due to exit:{{{bad_query,#{<<"$err">> => <<"not authorized for query on devices.vmq_acl_auth">>,<<"code">> => 13,<<"ok">> => 0.0}},[{mc_connection_man,process_error,2,[{file,"/opt/vernemq/_build/default/lib/mongodb/src/connection/mc_connection_man.erl"},{line,123}]},{mc_connection_man,read_one,2,[{file,"/opt/vernemq/_build/default/lib/mongodb/src/connection/mc_connection_man.erl"},{line,37}]},{vmq_diversity_worker_wrapper,handle_call,3,[{file,"/opt/vernemq/apps/vmq_diversity/src/vmq_diversity_worker_wrapper.erl"},{line,126}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{gen_server,call,[<0.609.0>,{apply,mc_worker_api,find_one,[<<"vmq_acl_auth">>,#{<<"mountpoint">> => <<"mp-test">>,<<"username">> => <<"DEV000001">>},#{}]},infinity]}}
`

**Comment by ioolkos** [comment]
@dtodor thanks, I can't think of direct change that would possibly cause that. It's exactly the same MongoDB, right? And, obviously, user/pw are the same I guess.

**Comment by dtodor** [comment]
Yes, we are using exactly the same Mongo DB version, database and credentials. It seems that the Mongo Erlang driver has been updated and the new version has many changes related to the SCRAM SHA-1 authentication:

[https://github.com/comtihon/mongodb-erlang/compare/9b53c4dcd931c48c5474dcdb8825e4b0afa2bff5...8d8b03ec572dda3f3b3cf16bcaa44d9afd5f5033](https://github.com/comtihon/mongodb-erlang/compare/9b53c4dcd931c48c5474dcdb8825e4b0afa2bff5...8d8b03ec572dda3f3b3cf16bcaa44d9afd5f5033)

**Comment by ioolkos** [comment]
oh... bingo! now how do we actually test this? could you create a specific MongoDB user with newly created password, or sth similar?

**Comment by dtodor** [comment]
I will send you later today a docker-compose project to test with. You can then just change the VerneMQ version and verify the behavior.

**Comment by dtodor** [comment]
Please use the atatched Docker Compose setup to test both versions 1.11.0 and 1.10.3:
[vernemq-mongo-test.tar.gz](https://github.com/vernemq/vernemq/files/5584963/vernemq-mongo-test.tar.gz)


Start with:
```
docker-compose up --build
```
(the DB will be created on the first start).

Test with:
```
mosquitto_sub -h localhost -p 1884 -i 'O4axb5Hd7UjD1T' -u 'DEV001005' -P 'MCDC-static-test-password' -t 'topic/a/DEV001005'
```

You can change the VerneMQ version inside the `vernemq/Dockerfile`.

**Comment by ldue** [comment]
@ioolkos experienced the same issue and was able to reproduce using the setup suggested by @dtodor

**Comment by ioolkos** [comment]
@ldue @dtodor okay, thanks, but do you have an idea on cause and/or solution?

**Comment by ldue** [comment]
I had a superficial look at the changes from the versions 1.10.3 and 1.11.0, nothing popped up to me in that regard, except a change in the dependency management on the erlang mongo driver.
It seems as there have been some changes on the payloads for SCRAM, but could not really work out more and I do not know erlang it is just a suspicion.

**Comment by ioolkos** [comment]
Thanks. Oh, the joy of dependencies.

**Comment by ioolkos** [comment]
@ldue which change "in the dependency management" did you mean, btw?

It seems that we always used "mongdb-erlang" master, so this can't be caused by changes in the MongoDB driver.
cc @dtodor

**Comment by ldue** [comment]
> @ldue which change "in the dependency management" did you mean, btw?

If I look for all changes between release 1.11.0 and 1.10.3 i found this [change](https://github.com/vernemq/vernemq/compare/1.10.3...1.11.0#diff-54d206794bbd7299616a51ef468c2aa8a076534de1d98d1786b1ea5abe7776f0L65).
From my understanding it changes the mongo dependency reference from commit a to commit b.

If you look at  [the diff](https://github.com/comtihon/mongodb-erlang/compare/9b53c4dcd931c48c5474dcdb8825e4b0afa2bff5...8d8b03ec572dda3f3b3cf16bcaa44d9afd5f5033) between these two commits, there are some changes regarding SCRAM communication. (e.g. [here](https://github.com/comtihon/mongodb-erlang/compare/9b53c4dcd931c48c5474dcdb8825e4b0afa2bff5...8d8b03ec572dda3f3b3cf16bcaa44d9afd5f5033#diff-e48d54a37b914d03a24e3cdf65b866c28f1b5786ec6572c0b812ce8be4d3e59bR64)
Thats all I can make out of that, I guess somebody who knows erlang could make more sense out of that 😄 

> It seems that we always used "mongdb-erlang" master, so this can't be caused by changes in the MongoDB driver.

yeah fits my observation. what was kind of a suprise to me last commit on "mongdb-erlang" master was in october 2018...

**Comment by ioolkos** [comment]
@ldue ah yes, we were locked to another older ref in the rebar.lock file, that's right! (locked to a PR that even came from Verne).
I guess `mongodb-erlang` is in maintenance-only mode by its maintainer. This was once the official MongoDB Erlang driver, and we were even in contact with MongoDB folks about this. 
What I certainly cannot do is take over further development of the MongoDB driver. It's probably also not necessary as long as it's in a working state and feature complete (for some defined set of features or MongoDB versions).

Anyway, so it seems we either manage to understand and fix this from Verne side, or revert to the old commit point.

**Comment by varnerac** [comment]
I've got a [pending PR](https://github.com/comtihon/mongodb-erlang/pull/237) on the MongoDB driver. Once it's accepted, I'll bump the MongoDB driver and see if I can get an integration test in GitHub Actions.
