### ISSUE TITLE
Can I enable logging of TLS Handshake errors?

### ISSUE THREAD

**Issue by steve999lee** [vernemq/vernemq#1680]
### Environment

- VerneMQ Version: 1.11.0
- OS: Ubuntu
- Erlang/OTP version (if building from source): 22
- VerneMQ configuration (vernemq.conf) or the changes from the default N/A
- Cluster size/standalone: N/A

### Expected behavior

I would like to see log entries for TLS handshake failures

### Actual behaviour

I cant find any log entries for TLS handshake failures.  ARe they available anywhere?

**Comment by ioolkos** [comment]
@steve999lee I suppose you see some handshake failures logged from the TLS Erlang layer. If those are not expressive enough, I normally switch to OpenSSL s_client in the hope for more handshake info.

**Comment by steve999lee** [comment]
@ioolkos  I can see them in the client and debug using the s:client/server. This is not for debug though but to be able to log cyber attacks in production. 

The TLS Erlang layer sounds promising though if I can find out how to enable its logging or where its logs are written

**Comment by steve999lee** [comment]
I still cant find any errors logged from the TLS Erlang layer.
Do I need to build vernemq with specific options or is there some erlang config required?

Sorry I'm not very familiar with erlang.

**Comment by ioolkos** [comment]
So you see nothing on this in server logs?
Even if we'd find a way to enable debug log for TLS app only, it'd be probably way too much.

**Comment by steve999lee** [comment]
Nothing in the server logs or on console.
From what I can tell the default level is notification and I would expect handshake errors to be at least this level.

**Comment by steve999lee** [comment]
@ioolkos - I'd appreciate any advice on where I should start in figuring out how to get these errors logged?

**Comment by steve999lee** [comment]
@ioolkos - any suggestions? Is it possible?

**Comment by ioolkos** [comment]
@steve999lee there is no config switch in VerneMQ that enables or disables what you want to see.
I would expect certain info to be logged but as you've said it doesn't seem to be. I suppose it's possible to enable debug logging for the Erlang SSL app only, if necessary in the `advanced.config` file.
This is stuff I'd need to test out myself to be able to give you a definitive answer, apologies for that.

**Comment by steve999lee** [comment]
@loolkos - I  found that if I change line 47 of ./vmq_server/src/vmq_ranch.erl

```
init(Ref, Parent, Transport, Opts) ->
    {ok, Socket} = ranch:handshake(Ref, Opts),
```

and adding 

   `  {log_level, debug}` in `./vmq_server/src/vmq_ssl.erl`
 
 I get a whole load of  debug but it seems to be all or nothing and if I change it to info I get nothing

**Comment by steve999lee** [comment]
I'm starting to think this isn't going to be what I need. Even if we do enable debug, we're going to get a dump not  just for the handshake but for all mqtt messages as well I think. 

I'm now thinking it might be easier to provide logging through tcpdump/wireshark where at least we can filter out the application messages.

**Comment by ioolkos** [comment]
Another option might be to use a proxy like https://github.com/mainflux/mproxy or HAProxy. You'd probably have to do TLS termination on HAProxy in that case. (which is fine for Verne, and often done).
Those proxies might have more options related to audit logging.

**Comment by steve999lee** [comment]
Yes that looks promising.
I'm closing this issue anyway - I don't think there's anything to be done.

Thanks for your help
