### ISSUE TITLE
Publish with no subscriber : return Success instead of NoMatchingSubscribers (0x10)

### ISSUE THREAD

**Issue by patafx** [vernemq/vernemq#1681]
### Environment

- VerneMQ Version: 1.11.0
- OS: Linux (Docker / K8S)
- VerneMQ configuration (vernemq.conf) or the changes from the default
Allow Anonymous : "on"
Allowed_Version = 3,4,5

- Client :
Developped in C# with MQTTnet Library (3.0.13)
Client connected in TCP with protocol version 5

### Expected behaviour

When publishing a message with QoS 1 or 2 on topic without subscribers. 
The server respond with reason code : 0x10 (NoMatchingSubscribers)

See : [Specifications MQTT 5.0](http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs02/mqtt-v5.0-cs02.html)

### Actual behaviour

When publishing a message with QoS 1 or 2 on topic without subscribers. 
The server respond with reason code : 0x00 (Success)

**Comment by ioolkos** [comment]
@patafx Thanks, you're correct about behaviour and spec. Note that 0x00 is a valid response as per the spec (in other words 0x10 is not mandatory).

**Comment by patafx** [comment]
Okay, but do you know if this feature will be implemented ?

**Comment by ioolkos** [comment]
With enough use cases and users asking for it, I might decide it's useful :)
But tbh I'm not too convinced that we should wait for the routing decision to be able to PUBACK.

**Comment by ioolkos** [comment]
@patafx I'll label this as 'discussion', but closing for now.
