### ISSUE TITLE
Unable to connect to Websocket listener

### ISSUE THREAD

**Issue by swapnilbb** [vernemq/vernemq#1683]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: 1.10.2
- OS: Ubuntu 16.04.6 LTS
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default

`
accept_eula = yes
allow_anonymous = off
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
coordinate_registrations = on
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.ws.default = 0.0.0.0:9000
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = A.B.C.D:44053
listener.http.default = 0.0.0.0:8888`

- Cluster size/standalone: 2 nodes

### Expected behaviour

+------+-------+------------+-----+----------+---------+
| type |status |     IP     |port |mountpoint|max_conns|
+------+-------+------------+-----+----------+---------+
| http |running|  0.0.0.0   |8888 |          |  10000  |
| vmq  |running|X.Y.Z.W|44053|          |  10000  |
|mqttws|running|  0.0.0.0   |9000 |          |  10000  |
| mqtt |running|  0.0.0.0   |1883 |          |  10000  |
+------+-------+------------+-----+----------+---------+

- Please describe the expected behaviour.

My websocket clients should be able to connect over WebSocket using: **ws://publicIp:9000/mqtt**

### Actual behaviour

But when I am trying I am unable to connect to the websocket from chrome extension, getting this error:

**vmq_websocket:add_socket:194 CRASH REPORT Process <0.22661.0> with 0 neighbours crashed with reason: bad record state in vmq_websocket:add_socket/2**

- Please include minimal steps to reproduce the issue, if possible.

Given everything already

**Comment by ioolkos** [comment]
@swapnilbb that seems to be a bug fixed here: https://github.com/vernemq/vernemq/pull/1635 (that is, in release 1.11.0)
Problem was that a list of multiple WSS subprotocols would not work, but only 1 named protocol. Look at the "sec-websocket-protocol" header of your request.

**Comment by swapnilbb** [comment]
Thanks.
