### ISSUE TITLE
custom response for client with expired certificate  

### ISSUE THREAD

**Issue by Roydon** [vernemq/vernemq#1684]
### To help us save time and help you faster

I have VerneMQ running with TLS authentication. With valid client certificate, client is able to connect to server. But for expired certificate it print following error

``` 
# mosquitto_pub -h mqtt.dev.example.com -p 8883 -t "test" -m "test" --cafile ca.pem --cert cert.pem --key key.pem
--tls-version tlsv1.2 -d
Client mosq-OLyNWDS1QCPpY0iyrF sending CONNECT
Error: Unknown error.
```

### Environment

- VerneMQ Version: vernemq/vernemq:1.11.0
- OS: 
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: standalone

### Expected behaviour

Client application need to understand why connection failed. based on this client can initiate other procedure.

How can I customize response received by client on unsuccessful connection. I would like to cover invalid/expired/revoked certificates.

**Comment by ioolkos** [comment]
Could you check with another SSL client, and the expired cert? 
I guess (from https://tools.ietf.org/html/rfc5246) the server should send a `certificate_expired` alert within the handshake. So maybe the "Error: unknow error" is a mosquitto client interpretation of the handshake error?

**Comment by ioolkos** [comment]
Feel free to update information, or re-open. Closing for now.
