### ISSUE TITLE
Live reconfiguration of bridge

### ISSUE THREAD

**Issue by andnig** [vernemq/vernemq#1686]
### Environment

- VerneMQ Version: latest
- OS: Centos 7.8

I'm currently testing the vernemq bridge capabilities and I'm highly satisfied. 
One thing however I can't find out: Is there a way to live-reconfigure a bridge (eg. adding an additional topic configuration to a bridge)?

**Comment by ioolkos** [comment]
@andnig thanks. I think the closest to reconfiguring live right now is to disable the plugin, start the plugin and then issue the `bridge start` command (if I remember correctly).

But it's actually a good point: adding bridges/topics via `vmq-admin` seems like a relatively low hanging feature to add, as there's reconfigure logic in the supervisor of the bridge already.

**Comment by andnig** [comment]
Hey @ioolkos, thanks for the very fast reply!
I'll close the issue than, thanks for pointing me to the workaround. +1
For having the dynamic topic configuration in the future - count me in :-)
