### ISSUE TITLE
Tell the client disconnect reason when the same client_id login.

### ISSUE THREAD

**Issue by dcy** [vernemq/vernemq#169]
Hi!
When the same clinet_id login, the old client disconnect. I want to tell the old client disconnect reason "the same client_id login".
I can do it by my way:
In my plugin, i use `on_register` and `on_client_offline` to sync the online state to my another server. So i have the client online state, I can publish a topic(the client sub) with something "another login" in `auth_on_register` when the client is online.
But it is not perfect. It is possible that the new client get the msg "another login".

Maybe you can add a plugin `before_disconnect_by_same_client_id` to do it before: https://github.com/erlio/vmq_server/blob/master/src/vmq_queue.erl#L204

In `before_disconnect_by_same_client_id`, if it return ok, it do nothing, if it return {Topic, Payload},It will publish Payload to the Topic.

Maybe there is other better way to do it i don't know. What is your opinion of this issue?

**Comment by ioolkos** [comment]
@dergraf, @larshesel opinions? sounds kind of useful to me.

**Comment by dergraf** [comment]
I think it's useful to have this information. However it might be better to include the disconnect reason inside the on_client_gone hook instead of implementing a new hook.

**Comment by larshesel** [comment]
Tagged this 2.0 as this is something we might wanna think about then.

**Comment by larshesel** [comment]
Closing the issue until work on VerneMQ 2.0 begins and we'll discuss this then.
