### ISSUE TITLE
Shared subscription java paho 

### ISSUE THREAD

**Issue by carpino** [vernemq/vernemq#1696]
Hi, i'm trying to use the shared subscription feature with the paho mqtt java client, 
following the documentation page at https://docs.vernemq.com/configuration/shared_subscriptions, gives me problems, in particular subscribing at "$share/group/test" and publish at "test" makes no message arrive to the consumers.

I'm missing something? 
Thanks

**Comment by ioolkos** [comment]
`sudo vmq-admin session show --client_id --topic`

**Comment by carpino** [comment]
> sudo vmq-admin session show --client_id --topic

The command return without showing anything

**Comment by ioolkos** [comment]
So you don't have a subscription. Please check whether the client supports shared subscriptions.
(https://github.com/eclipse/paho.mqtt.java/issues/367)
