### ISSUE TITLE
VerneMQ Cluster randomly fails after restart

### ISSUE THREAD

**Issue by micw** [vernemq/vernemq#1698]
### Environment

- VerneMQ Version: 1.11.0
- OS: Linux
- Erlang/OTP version (if building from source): 23.0-r0
- VerneMQ configuration (vernemq.conf) or the changes from the default

```
########## Start ##########
plugins.vmq_diversity=on
max_offline_messages=-1
listener.tcp.default.mountpoint=default
listener.ssl.demo.certfile=/etc/ssl/vernemq/demo/tls.crt
listener.ssl.default.certfile=/etc/ssl/vernemq/default/tls.crt
allow_register_during_netsplit=on
allow_unsubscribe_during_netsplit=on
shared_subscription_policy=random
listener.ssl.demo.keyfile=/etc/ssl/vernemq/demo/tls.key
listener.ssl.demo.mountpoint=demo
vmq_diversity.auth_http.file=/vernemq/share/lua/auth/auth_http.lua
listener.ssl.kehag=0.0.0.0:12040
plugins.vmq_passwd=off
listener.tcp.default=0.0.0.0:1883
listener.ssl.demo=0.0.0.0:12000
listener.ssl.default.cafile=/etc/ssl/vernemq/default/tls.crt
allow_publish_during_netsplit=on
listener.ssl.default=0.0.0.0:8883
max_client_id_size=100
listener.ssl.default.keyfile=/etc/ssl/vernemq/default/tls.key
log.console=console
max_online_messages=10000
listener.ssl.demo.cafile=/etc/ssl/vernemq/demo/tls.crt
allow_anonymous=off
listener.ssl.default.mountpoint=default
plugins.vmq_acl=off
allow_subscribe_during_netsplit=on
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.ws.default = 10.42.0.88:8080
listener.vmq.clustering = 10.42.0.88:44053
listener.http.metrics = 10.42.0.88:8888
########## End ##########
```

- Cluster size/standalone: 3 Nodes

### Expected behaviour

Cluster should run stable.

### Actual behaviour

When redeploying the cluster / restarting nodes, the cluster often fails. It's not always but ~ in 7/10 cases. Deleting /vernemq/data/meta and restarting the failing node usually solves the issue.

### Details

I run a 3-node cluster on kubernetes. The cluster basically works but in many cases after a restart or a re-deployment (e.g. when changing listeners), a node starts but fails to communicate with the cluster. I have manually checked the connectivity while this happens and it seems to be fine.

Symptoms are very similar to other issues reported here, but since we have no solution yet, I create a new one to track this down.

The failing node prints this warning every second:

```
14:42:11.848 [info] successfully connected to cluster node 'VerneMQ@broker-vernemq-2.broker-vernemq-headless.testing.svc.cluster.local'
14:42:11.849 [warning] connection to node 'VerneMQ@broker-vernemq-2.broker-vernemq-headless.testing.svc.cluster.local' has been closed, reconnect in 1000ms
14:42:11.853 [info] successfully connected to cluster node 'VerneMQ@broker-vernemq-1.broker-vernemq-headless.testing.svc.cluster.local'
14:42:11.855 [warning] connection to node 'VerneMQ@broker-vernemq-1.broker-vernemq-headless.testing.svc.cluster.local' has been closed, reconnect in 1000ms
```

The remaining nodes logs:

```
14:43:41.292 [warning] terminate due to remote_node_not_available
14:43:42.297 [warning] terminate due to remote_node_not_available
14:43:43.302 [warning] terminate due to remote_node_not_available
14:43:44.307 [warning] terminate due to remote_node_not_available
14:43:44.709 [info] completed metadata exchange with 'VerneMQ@broker-vernemq-0.broker-vernemq-headless.testing.svc.cluster.local'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 3 keys
14:43:45.310 [warning] terminate due to remote_node_not_available
14:43:46.315 [warning] terminate due to remote_node_not_available
14:43:47.320 [warning] terminate due to remote_node_not_available
14:43:48.324 [warning] terminate due to remote_node_not_available
```

**Comment by micw** [comment]
I have also tried version 1.10.5 - behaves exactly the same.

**Comment by ioolkos** [comment]
@micw thanks.
Interesting. What's happening here is this, it seems: the first node (where you see the 'reconnects' logged), thinks it's part of the cluster and wants to open data connections to the other nodes (those are additional TCP connections for inter-node MQTT message delivery).
The other nodes seem to think the first node is not part of the cluster, and actively refuse to accept data connection setup from that node.
So either some form of race condition between the 2 clustering layers, or much more likely a metadata issue due to a node trying to re-join the cluster with old state (after it has left the cluster before)
This could happen namely on Kubernetes where the start script was pretty dumb so far (always doing cluster leave), but see this PR: https://github.com/vernemq/docker-vernemq/pull/264

**Comment by micw** [comment]
ioolkos: thank you for the response. I wonder why it still works sometimes. How should a node behave if it's restarting? Maybe not leave the cluster at all? But how to deal with up/down scaling then?
