### ISSUE TITLE
Load test on VerneMQ

### ISSUE THREAD

**Issue by Akashlv7** [vernemq/vernemq#1713]
Hi,
Please give a document or an input on how to run load test on Vernemq with MQTT as client.

**Comment by ioolkos** [comment]
@Akashlv7 Thanks. I'm afraid you're going to have to research this. 
We have a very old blog post regarding `vmq_mzbench` here, it's potentially outdated: http://vernemq.com/blog/2016/08/26/loadtesting-mqtt-brokers.html
But this is by no means your only option. There's many options for MQTT loadtesting.
