### ISSUE TITLE
[New Feature] Server Side Events support in addition to Websocket

### ISSUE THREAD

**Issue by tjunussov** [vernemq/vernemq#1718]
Mqtt broker supports awesome **Websockets**, but sometimes it is overused, so there is place for technology **SSE ( Server Side Events )** in browser world

The **major difference between WebSockets and Server-Sent Events** is that **WebSockets are bidirectional** (allowing communication between the client and the server) while **SSEs are mono-directional** (only allowing the client to receive data from the server)

Here is [Stackoverflow discussion](https://stackoverflow.com/questions/5195452/websockets-vs-server-sent-events-eventsource)

Think it could be realized easily, maybe as Plugin ? 
I came from FrontEnd world, and SSE for push updates is perfect way for doing that, rather then long polling

On client.js side code would be something like

```
  var e = new EventSource('https://sse.verne.mq/myTopic');
  e.onmessage = function(event) {
     console.log(event.data);
  }
```

**Comment by ioolkos** [comment]
@tjunussov Thanks for bringing in ideas! :)

I think the reason that only WebSockets is supported is that SSE is one-directional as you mention. So the MQTT couldn't do even a PINGRequest on the same channel. 
The other challenge I can think of is that SSE is basically text-only while MQTT is a binary protocol/transport.
But maybe you have ideas on that.

**Comment by codeadict** [comment]
This sounds like a good idea for a notification like plugin
