### ISSUE TITLE
Can webhook auth_on_subscribe have multiple topics in response?

### ISSUE THREAD

**Issue by Gustu** [vernemq/vernemq#1720]
How can I handle `#` topic subscription in webhook for users who can only subscribe to e.g. `a/#` and `b/#`?

I'm not able to rewrite one subscription to multiple subscriptions - the number of topics needs to match. In the above example, I have only one topic - `#`. How can I tell VerneMQ that a user can view only `a/b` and `c/b` without a direct subscription from the client? 

I'd like to subscribe to everything I can on the client-side. The backend (webhooks) would decide what topics I can subscribe to.

**Comment by Gustu** [comment]
In other words, I need to know what I can subscribe to on the client-side.

To give you more context, currently, I'm implementing authorization in the system where I have a hierarchy of users. Users who are higher in the hierarchy can see more. At the top, admins can view everything.

That's why I need to change the context when I'm subscribing. The easiest thing would be just to subscribe to `a/#`  and let the backend decide what I can see.

**Comment by Gustu** [comment]
Example:

That's the beginning of the topic name: 
```
v1/asd/sda/:idA/:idB/blabla/:idC/....
v1/qwe/sda/:idA/:idB/blabla/:idC/....
v1/yhw/sda/:idA/:idB/blabla/:idC/....
```
Some users can do `#` <- this doesn't work since I don't know the final topic they are subscribing to. I need to use `v1/asd/#`
Some users can do `v1/asd/sda/:idA/#`
Some user can do `v1/asd/sda/:idA/:idB/blabla/#`

**Comment by Gustu** [comment]
I'd like to subscribe to `v1/#` to get everything under `v1/asd`, `v1/qwe`, `v1/yhw`, but I can't since I can only rewrite one topic when subscribing to one topic

**Comment by ioolkos** [comment]
> Some users can do # <- this doesn't work since I don't know the final topic they are subscribing to. I need to use v1/asd/#
Some users can do v1/asd/sda/:idA/#
Some user can do v1/asd/sda/:idA/:idB/blabla/#

You confuse me there :)

If a user is allowed to subscribe to #, then it will get messages matching **all** topics. There's no need to know the routing key, or subscribe to any other topic for that.
Same applies to the 2 other examples.

I understand you want to implement a group or role based ACL approach. Maybe you also want to reduce topic subscriptions. But if you want to subscribe to a/# and b/# that's going to be 2 topic filters (subscriptions), there's no way around that.
