### ISSUE TITLE
vernemq coordinate_registrations keeps client connect/disconnect

### ISSUE THREAD

**Issue by pijain** [vernemq/vernemq#1722]
### Environment

- VerneMQ Version: 1.11.0
- OS: ubuntu
- Erlang/OTP version (if building from source): NA
- VerneMQ configuration: [vernemq.conf.txt](https://github.com/vernemq/vernemq/files/5918057/vernemq.conf.txt)
- Cluster size/standalone: 2 nodes

### Expected behaviour

- Clients with same client_id should remain connected

### Actual behaviour

- clients with same client_id disconnect/connect every second with error: 
`Connected with result code 0
failed to receive on socket: [Errno 54] Connection reset by peer
Connected with result code 0
failed to receive on socket: [Errno 54] Connection reset by peer
Connected with result code 0
failed to receive on socket: [Errno 54] Connection reset by peer`

**Comment by ioolkos** [comment]
@pijain make sure that ClientIDs are unique. Multiple Clients cannot have the same ClientID, they will kick each other off the broker, which is what you are probably seeing.

**Comment by pijain** [comment]
@ioolkos thanks for the update. Yes I was using same client ID was under the perception that cordinate_registrations will also support multiple session, like it used to work in allow_multiple_session.

Is there a way where a client ID can get offline messages from queue of another offline queue of another client_id.

**Comment by ioolkos** [comment]
@pijain 
`coordinate_registrations` does not allow multiple sessions for the same clientID. It only reimplements a side-effect of that, which is the more performant registers in a cluster (because it won't synchronise the registers in realtime).

You cannot access given session state (ie offline messages) under a different ClientID. (it would break MQTT spec)
