### ISSUE TITLE
Can't find mqtt messages sent to vernemq server

### ISSUE THREAD

**Issue by vacquah** [vernemq/vernemq#1724]
### Environment

- VerneMQ Version: 1.11.0
- OS: Ubuntu 20.04 
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
  allow_anonymous = on
- Cluster size/standalone: standalone

### Expected behaviour

I expect to see the data pushed from my IoT device in on the metrics page.
### Actual behaviour
I only see system info

- Please include minimal steps to reproduce the issue, if possible.
I am sending data from a temp sensor to a freshly installed vernemq server.  I can see the server is up and running. I can also see the mqtt data coming in when i subscribe to it using mqttbox.  I can also see the data coming in when in I do a trace client. Its starts coming in then it times out with the message : 

`root@vernemq:~# vmq-admin trace client client-id=aqm_argon_01
2021-02-04T00:46:40Z Starting trace for 1 existing sessions for client "aqm_argon_01" with PIDs
    [<9491.379.0>]
2021-02-04T00:46:51Z <9491.379.0> MQTT RECV: CID: "aqm_argon_01" PINGREQ()
2021-02-04T00:46:51Z <9491.379.0> MQTT SEND: CID: "aqm_argon_01" PINGRESP()
2021-02-04T00:47:08Z <9491.379.0> MQTT RECV: CID: "aqm_argon_01" PINGREQ()
2021-02-04T00:47:08Z <9491.379.0> MQTT SEND: CID: "aqm_argon_01" PINGRESP()
2021-02-04T00:47:18Z <9491.379.0> MQTT RECV: CID: "aqm_argon_01" PUBLISH(d0, q0, r0, m0, "airquality/argon_01") with payload:
    {"readtime": 1612399635000, "deviceID":"e00fce68d5301cd073f6c999", "deviceLocation":"master", "deviceName":"aqm_argon_01","deviceType":"argon","tempC": 21.17, "tempF": 70.11, "relative_humidity": 34.3 (truncated)
2021-02-04T00:47:18Z <9491.379.0> Calling auth_on_publish(victor,{[],
                                                                  <<"aqm_argon_01">>},0,airquality/argon_01,false) with payload:
    {"readtime": 1612399635000, "deviceID":"e00fce68d5301cd073f6c999", "deviceLocation":"master", "deviceName":"aqm_argon_01","deviceType":"argon","tempC": 21.17, "tempF": 70.11, "relative_humidity": 34.36,"tvoc":19.00, "eco2":419.00
2021-02-04T00:47:18Z <9491.379.0> Hook returned "ok"
2021-02-04T00:47:26Z <9491.379.0> MQTT RECV: CID: "aqm_argon_01" PINGREQ()
2021-02-04T00:47:26Z <9491.379.0> MQTT SEND: CID: "aqm_argon_01" PINGRESP()
RPC to 'VerneMQ@127.0.0.1' failed: timeout`

I have also pointed my prometheus instance to this server. Nothing is making it into prometheus too.

**Comment by ioolkos** [comment]
@vacquah it seems you're saying metrics are not exported. are the counter increased though? check with `vmq-admin metrics show`. You might think the updates are not there, due to low frequency.

**Comment by vacquah** [comment]
> @vacquah it seems you're saying metrics are not exported. are the counter increased though? check with `vmq-admin metrics show`. You might think the updates are not there, due to low frequency.

Here is what I see:

`root@vernemq:~# vmq-admin metrics show
counter.mqtt_auth_received = 0
counter.bytes_received = 574294
gauge.retain_messages = 0
counter.socket_close_timeout = 0
gauge.system_utilization_scheduler_23 = 0
counter.cluster_bytes_received = 0
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingreq_received = 7738
counter.mqtt_puback_received = 0
gauge.system_utilization_scheduler_19 = 0
counter.mqtt_subscribe_received = 1
counter.socket_close = 1
counter.mqtt_subscribe_auth_error = 0
gauge.system_utilization_scheduler_14 = 2
counter.cluster_bytes_dropped = 0
gauge.system_utilization_scheduler_27 = 0
counter.system_runtime = 120482
counter.mqtt_subscribe_error = 0
gauge.system_utilization_scheduler_4 = 2
gauge.system_utilization_scheduler_2 = 2
gauge.router_memory = 13120
counter.mqtt_connack_sent = 3
gauge.system_utilization_scheduler_20 = 0
counter.mqtt_disconnect_received = 0
gauge.system_utilization_scheduler_26 = 0
counter.queue_message_out = 4
counter.mqtt_pubcomp_invalid_error = 0
gauge.system_utilization_scheduler_16 = 2
counter.system_reductions = 5493821057
gauge.system_utilization = 2
counter.bytes_sent = 16505
gauge.system_process_count = 345
counter.netsplit_resolved = 0
counter.socket_error = 0
gauge.system_utilization_scheduler_29 = 0
gauge.system_utilization_scheduler_18 = 0
counter.queue_teardown = 1
counter.system_words_reclaimed_by_gc = 703935582
gauge.system_utilization_scheduler_25 = 0
counter.mqtt_pubrel_sent = 0
counter.router_matches_local = 4
counter.mqtt_pubrec_sent = 0
counter.socket_open = 3
gauge.router_subscriptions = 0
counter.system_io_in = 3913284
gauge.system_utilization_scheduler_10 = 3
gauge.vm_memory_atom_used = 649317
counter.system_exact_reductions = 5493569878
gauge.vm_memory_system = 36794936
counter.mqtt_suback_sent = 1
gauge.vm_memory_processes = 10518008
counter.mqtt_publish_sent = 4
gauge.system_utilization_scheduler_28 = 0
counter.mqtt_pubcomp_received = 0
counter.mqtt_pubrec_received = 0
counter.mqtt_auth_sent = 0
counter.mqtt_unsubscribe_received = 0
gauge.vm_memory_total = 47312944
counter.queue_setup = 3
gauge.system_utilization_scheduler_32 = 0
counter.mqtt_publish_received = 2208
gauge.system_utilization_scheduler_24 = 0
gauge.system_utilization_scheduler_15 = 2
gauge.vm_memory_processes_used = 10517560
counter.queue_initialized_from_storage = 0
gauge.vm_memory_binary = 458152
counter.cluster_bytes_sent = 0
gauge.system_utilization_scheduler_17 = 0
gauge.system_utilization_scheduler_5 = 2
counter.mqtt_pubrel_received = 0
counter.mqtt_invalid_msg_size_error = 0
gauge.system_utilization_scheduler_30 = 0
gauge.system_utilization_scheduler_6 = 2
gauge.system_utilization_scheduler_22 = 0
counter.mqtt_pubrec_invalid_error = 0
counter.system_gc_count = 760356
gauge.system_utilization_scheduler_21 = 0
counter.system_wallclock = 65997514
gauge.system_utilization_scheduler_1 = 27
counter.system_io_out = 73075708
gauge.system_utilization_scheduler_9 = 2
counter.queue_message_drop = 0
gauge.system_run_queue = 0
counter.mqtt_puback_invalid_error = 0
gauge.system_utilization_scheduler_12 = 2
counter.mqtt_connack_identifier_rejected_sent = 0
counter.mqtt_disconnect_sent = 0
counter.mqtt_pubcomp_sent = 0
gauge.vm_memory_ets = 6473424
counter.queue_message_expired = 0
counter.mqtt_connect_received = 3
counter.mqtt_unsubscribe_error = 0
counter.client_keepalive_expired = 0
counter.netsplit_detected = 0
gauge.system_utilization_scheduler_13 = 2
gauge.system_utilization_scheduler_7 = 2
gauge.queue_processes = 2
counter.router_matches_remote = 0
counter.client_expired = 0
gauge.retain_memory = 11104
counter.mqtt_connack_accepted_sent = 0
gauge.system_utilization_scheduler_31 = 0
counter.mqtt_puback_sent = 0
gauge.system_utilization_scheduler_8 = 2
counter.mqtt_connack_bad_credentials_sent = 0
gauge.system_utilization_scheduler_11 = 2
counter.mqtt_publish_error = 0
counter.queue_message_in = 4
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_auth_error = 0
gauge.vm_memory_atom = 662433
counter.mqtt_pingresp_sent = 7738
counter.mqtt_connack_unacceptable_protocol_sent = 0
gauge.vm_memory_code = 13118458
counter.queue_message_unhandled = 0
counter.mqtt_connack_server_unavailable_sent = 0
gauge.system_utilization_scheduler_3 = 2
counter.system_context_switches = 3763077`

**Comment by ioolkos** [comment]
@vacquah ok, now you'll have to interpret the metrics/counters and see whether they make sense for your input. (I cannot do that for you, I do not know how many messages you sent etc.)
I'm closing the issue, as to me it doesn't seem like a VerneMQ issue or bug.

**Comment by vacquah** [comment]
Why is this issue closed?  I just need some guidance on how to confirm my mqtt sensor data is making it in here or why its not making it into prometheus -since the prometheus exporter is built in and I have no idea if its working or not. I dont see any of the sensor data metrics shown in the output.
