### ISSUE TITLE
If all topics are unsubscribed, will the queue be teardown automatically?

### ISSUE THREAD

**Issue by FitzLu** [vernemq/vernemq#1733]
### Environment

- VerneMQ Version: 1.11.1
- OS: AWS Linux 2

### Expected behaviour

- All client unsubscribe their topics, then all the related queues teardown, current queues count decrease.

### Actual behaviour

- All the queues still exist, after performing lots of tasks, current queues count reach a very large number, and vernemq server becomes very slow.

**Comment by ioolkos** [comment]
@FitzLu Queues live as long as the MQTT session lives. It is up to the MQTT client to decide whether the session is persistent (= lives longer than the TCP session). In the case of a persistent session, you'll have offline queue processes on the  broker. They will only be "garbage collected" by the persistent session timeout, or by a client connecting to the broker with the same ClienID requesting a non-persistent session.
You might want to check what you do client side in your case, and whether you create persistent sessions uselessly, for instance with random ClientIDs.

**Comment by FitzLu** [comment]
I set ```clean_session=true```, but this cause any current session to be removed along with its data, how to remove session safely when client disconnect from the server

**Comment by ioolkos** [comment]
I don't understand what you say. With `clean_session=true` state is removed upon disconnect.

**Comment by FitzLu** [comment]
@ioolkos Thank you for your help :)
