### ISSUE TITLE
Resource allocation in a VerneMQ cluster

### ISSUE THREAD

**Issue by karlokr-p** [vernemq/vernemq#1734]
### To help us save time and help you faster

I am monitoring a VerneMQ cluster of 3 nodes using Netdata+Prometheus and I am seeing some behavior I do not fully understand. How are resources allocated in a VerneMQ cluster? 

### Environment

- VerneMQ Version: vernemq/vernemq:latest docker image
- OS: Debian 10 using Docker (Azure VM scaleset)
- Load balancing handled by an Azure load balancer
- Cluster size: 3

### Expected behaviour

- I expect that the three nodes will all send and receive messages about equally. Each node should have a queue with about the same number of messages in it.

### Actual behaviour

- A single node is sending/receiving all messages. A single node has all of the messages in its queue while the others have none.
- I am seeing communication between nodes, and that two of the nodes which have no messages in their queues are however sending data to the one node that does have messages in its queue (via the cluster bandwidth stat).

Additionally I would like to ask what exactly does the "scheduler utilization" indicate?

I'm just trying to understand the behavior I'm observing and if it indicates, for example, that the cluster size is larger than necessary. Or perhaps I am just misunderstanding how the cluster allocates resources and this is perfectly normal? Or is it indicating a problem with the load balancer? I apologize if this is not super clear what I'm asking, please do let me know if you need clarification. Thank you in advance for the help!

**Comment by ioolkos** [comment]
@karlokr-p 
> Each node should have a queue with about the same number of messages in it.

Nodes do not "have a queue". Each consumer has a queue (which is living on the node the consumer is connected to, that's true).
The traffic for that consumer is then routed to that queue and that node.
