### ISSUE TITLE
Order of hooks seems to not be guaranteed

### ISSUE THREAD

**Issue by rubengees** [vernemq/vernemq#1741]
### Environment

- VerneMQ Version: `1.11.0`
- OS: `alpine` docker
- Erlang/OTP version (if building from source): 23
- Cluster size/standalone: 3

### Expected behaviour

We are using [webhooks](https://docs.vernemq.com/plugindevelopment/webhookplugins) to get notified when a client connects, disconnects or loses it's connection. We use this information to visualize the state and send notifications to users. All clients connect with clean session = false.

Hooks should always arive in the semantically correct order, that is: `on_client_offline`/`on_client_gone` always before `on_register`.

### Actual behaviour

This does not work reliably. Ocassionally, the `on_register` is sent _before_ `on_client_offline` in case of a reconnect of a client (the time difference is less than 10ms). VerneMQ does not seem to wait for the response from the hook implementation before allowing a new connection. This introduces a race condition which makes other components think the client is offline even though it isn't.

It is kind of hard to reproduce, but it seems to happen the most when the client disconnects abnormally (the `on_client_gnone` hook).

Is this intended behaviour (or at least not directly wrong)? If not, is this possible to fix?

### Configuration

```
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__REGISTER__HOOK
  value: "on_register"
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__REGISTER__ENDPOINT
  value: "http://localhost:1234"
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__REGISTER_M5__HOOK
  value: "on_register_m5"
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__REGISTER_M5__ENDPOINT
  value: "http://localhost:1234"
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__GONE__HOOK
  value: "on_client_gone"
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__GONE__ENDPOINT
  value: "http://localhost:1234"
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__OFFLINE__HOOK
  value: "on_client_offline"
- name: DOCKER_VERNEMQ_VMQ_WEBHOOKS__OFFLINE__ENDPOINT
  value: "http://localhost:1234"
```

The hook receiver is a basic Node.js application which logs the hook name as early as possible.

**Comment by ioolkos** [comment]
@rubengees it's an effect of the concurrency. Neither intended nor unintended.
But it's been noted before, and there's a feature request for timestamps: https://github.com/vernemq/vernemq/issues/1725 (not sure that'd solve the problem in any cases though)

**Comment by rubengees** [comment]
Ah nice, didn't see that issue, it's exactly the same as our problem. We actually already are adding timestamps but only in the hook receiver which is too late. I'll try the lua plugin approach and see if that helps.
