### ISSUE TITLE
Cluster is left in a bad state if the DNS name doesn't resolve initially

### ISSUE THREAD

**Issue by SerialVelocity** [vernemq/vernemq#1751]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: 1.11.0
- OS: Fedora CoreOS
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default
```
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
    - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
      value: "on"
    - name: DOCKER_VERNEMQ_KUBERNETES_CLUSTER_NAME
      value: "<internal domain>"
```
- Cluster size/standalone: 2

### Expected behaviour

- Use your helm chart to start up a 2-replica cluster
- See on the status page "All good! No cluster issues found!", cluster size 2, and 2 nodes

### Actual behaviour

- Cluster size is only 1 but it still shows 2 nodes. (Also says "All good")

### Additional information
So, I think what gets the cluster into a bad state is https://github.com/vernemq/docker-vernemq/issues/265, but what this bug report is about is that vernemq never recovers. It sits there with cluster size 1, allowing connections to both nodes and messages aren't propagated between them.

**Comment by ioolkos** [comment]
I think this is resolved by https://github.com/vernemq/docker-vernemq/commit/dbe19b1e4d247b189f90515635eba47fb2f9ecb2

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
