### ISSUE TITLE
Connection drops on unauthorized request 

### ISSUE THREAD

**Issue by SakibFarhad** [vernemq/vernemq#1753]
I have a vernemq setup with 3 node cluster and using redis as data storage. I have set the key value in following manner 
```bash
SET "[\"\",\"user_id\",\"user\"]" "{\"passhash\":\"$2a$12$eXaEPoYpJElVvQREMyqmc.LzsKL5.ER7AHwIOSC/ZRFLJIURfaP36\",\"subscribe_acl\":[{\"pattern\":\"topic/+/+/+\"},{\"pattern\":\"topic/+/+\"}]}"
```
Here as you can see I am not providing any `publish_acl`, when someone tries to connect using this user the connection drops showing following message

```bash
Error: The connection was lost.
```
Shouldn't it provide an unauthorized message? 

### Environment

- VerneMQ Version: 1.11.0
- OS: CentOS 7
- Erlang/OTP version: Installed using RPM
- Cluster size/standalone: 3 Node Cluster

### Expected behaviour

provide unauthorized access message

### Actual behaviour

Connection drops.

**Comment by ioolkos** [comment]
@SakibFarhad thanks, you need to be aware of QoS and MQTT protocol version. (for QoS 0 you will never get a response from broker). For MQTT v5 there are additional PUBACK response codes, compared to v3.1.1.

So, for a non-authorized PUBLISH the only thing the server could do other than disconnect the client, is to keep the connection while not informing him that he's not authorized and the message will not be processed.

**Comment by zia069** [comment]
Hi @ioolkos, How can we get this disconnection feature for unauthorised  subscription. Because we are updating acl on the fly and connected client are not aware of that updated acl. So how can we enable auto disconnect feature when trying to subscribe a unauthorised topic or acknowledge client.

**Comment by SakibFarhad** [comment]
@ioolkos Thanks a lot for your repose. Now I understand the problem. 
I have another issue.  
Initially I have an acl for pub and sub as following
```bash
SET "[\"\",\"user_id\",\"user\"]" "{\"passhash\":\"$2a$12$eXaEPoYpJElVvQREMyqmc.LzsKL5.ER7AHwIOSC/ZRFLJIURfaP36\",\"subscribe_acl\":[{\"pattern\":\"topic/+/+/+\"},{\"pattern\":\"topic/+/+\"}],\"pulish_acl\":[{\"pattern\":\"topic/+/+/+\"},{\"pattern\":\"topic/+/+\"}]}"
```

Now a user is connected using this acl and kept himself connected. in the mean time the acl was changed as following

```bash
SET "[\"\",\"user_id\",\"user\"]" "{\"passhash\":\"$2a$12$eXaEPoYpJElVvQREMyqmc.LzsKL5.ER7AHwIOSC/ZRFLJIURfaP36\",\"subscribe_acl\":[{\"pattern\":\"new_topic/+/+/+\"},{\"pattern\":\"new_topic/+/+\"}],\"pulish_acl\":[{\"pattern\":\"new_topic/+/+/+\"},{\"pattern\":\"new_topic/+/+\"}]}"
```

In this case verne broker knows about the change as it is updating from redis on 10s interval, but the user doesn't know anything about the change. Can I do any change on the vernemq server so that the user get an event trigger that the acl has changed for him?

**Comment by ioolkos** [comment]
@SakibFarhad the question is whether you should trust the client with just that information on ACL change, or rather just plainly disconnect it. (to inform, you can always send an MQTT message)

I'd opt  for the disconnect. Look up `vmq-admin session disconnect --help` on how to disconnect a client forcefully. (you can wrap the command in HTTP as described here: https://docs.vernemq.com/administration/http-administration).

This way you could call a disconnect on the client, right after you've updated the ACLs.
