### ISSUE TITLE
System requirement of installing vernemq

### ISSUE THREAD

**Issue by bearharry5c13** [vernemq/vernemq#1758]
The company I belonged to is planning to buy and set up several mini PC in the office and served as MQTT broker, but I cannot find the spec requirement of Vernemq. The only thing I know is that I cannot install it on Arm64 when I try to install it on a raspberry pi 4 with a ubuntu OS. Are there any system requirement on installing vernemq?

Also I have look through the tutorial but it doesn't tell how to start a broker cluster and only how to join a cluster. What I need to do to start a set of cluster?

**Comment by ioolkos** [comment]
@bearharry5c13 you don't start a cluster, you start nodes (and then join them to a cluster, if they are not already a cluster).
ARM is not well supported yet, yes.
Specs are load dependent, running Verne under 2 CPUs and 4GB of Ram is no fun (so consider this a minimum), and for medium load you need higher specs than that.
