### ISSUE TITLE
Custom logging in plugins

### ISSUE THREAD

**Issue by MattyCZ** [vernemq/vernemq#1759]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version:1.11.0-35-g70b0774
- OS:ubuntu 20.04
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: standalone

Can we somehow tell plugins to log to a different file than `console.log`? I could not find anything on the internet that would work. Is it even possible? 

Thanks in advance

**Comment by ioolkos** [comment]
@MattyCZ I currently don't know of a way to do that. We originally thought logging in one place would make more sense (plugins can log to the Verne logging files). But it's not a wrong question, we'd have to explore how different OTP apps within the same release can setup logging in separate fashion.
