### ISSUE TITLE
"fatal error: ei.h: No such file or directory" while building

### ISSUE THREAD

**Issue by imranrazakhan** [vernemq/vernemq#1762]
I am Building VerneMQ from sources on Alpine Linux and getting following error

```
===> Compiling /root/vernemq/c_src/syslog_drv.c
===> /root/vernemq/c_src/syslog_drv.c:29:10: fatal error: ei.h: No such file or directory
   29 | #include <ei.h>
      |          ^~~~~~
compilation terminated.

make: *** [Makefile:26: rel] Error 1
```

### Environment

- VerneMQ Version: 1.11.0
- OS: Alpine 3.13.3
- Erlang/OTP version (if building from source): 23.1.5-r0

### Expected behavior

VerneMQ build should be successfull.

### Actual behaviour

I am not able build VerneMQ, I tried same steps for CentOS and it works.

**Comment by ioolkos** [comment]
@imranrazakhan I don't remember seing this. Somehow the Makefile doesn't find all parts of your Erlang installation. Do you maybe have multiple Erlangs installed? and how do you install Erlang exactly?

**Comment by ioolkos** [comment]
@imranrazakhan I take you found a solution. Closing issue for now. Feel free to add more info or re-open.
