### ISSUE TITLE
Do I need to change the nodename before letting another node to join?

### ISSUE THREAD

**Issue by bearharry5c13** [vernemq/vernemq#1765]
I am now using a computer A on ubuntu platform run as a vernemq broker and another computer B on windows 10 running docker also as a vernemq broker. 
I want to join the computer B to computer A to from a cluster but I only get "cannot join cluster due to unreachable"
I have changed the line in vernemq.conf of computer A from "listener.vmq.clustering = 0.0.0.0:44053" to "listener.vmq.clustering = 192.168.124.113:44053" where 192.168.124.113 is computer A's IP address.
Both computer A and B are connected on the same network, what I need to do to make a cluster? Or what things I have mistaken or misunderstand?

**Comment by ioolkos** [comment]
You don't necessarily need to change the nodename to adapt to a changing IP, but nodenames cannot be the same on both nodes.

I think you simple don't have connectivity here, from within the Docker image on B.
