### ISSUE TITLE
Client not disconnecting when trying to subscribe an unauthorised topic

### ISSUE THREAD

**Issue by zia069** [vernemq/vernemq#1770]
### Environment

- VerneMQ Version: 1.11
- OS: CentOS 7.6
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) : using redis based acl authentication/authorisation 
- Cluster size/standalone: 2 Node

### Expected behaviour

Disconnect client when tried to subscribe an unauthorised topic. 

### Actual behaviour

We are mqtt client version 3.1.
At vernemq server we are using redis based authentication/authorisation. ACLs are added in realtime, so a ACL can be added for a client-id which is already connected now. If we add a ACL for publish and connected client wants to publish added topic and got disconnected, to overcome this we implemented auto reconnect feature. But if same issue occurs for subscription ACL client is not disconnecting from server and not getting updated ACL. How can we overcome this issue.

Example:

Say, my client-id is "test-client" and it is connected to server now.

adding a publish_acl for client id "test-client" to topic "a/b/c".

```SET "[\"\",\"test-client\",\"test-user\"]" "{\"passhash\":\"$2a$12$WDzmynWSMRVzfszQkB2MsOWYQK9qGtfjVpO8iBdimTOjCK/u6CzJK\",\"publish_acl\":[{\"pattern\":\"a/b/c\"}]}"```

Now if my connected client with client-id "test-client" wants to publish in topic a/b/c, it will disconnect and my application automatically reconnect and get the updated ACL and can publish in a/b/c topic.

Now i am adding a "subscribe_acl" for client id "test-client" to topic "d/e/f".

```SET "[\"\",\"test-client\",\"test-user\"]" "{\"passhash\":\"$2a$12$WDzmynWSMRVzfszQkB2MsOWYQK9qGtfjVpO8iBdimTOjCK/u6CzJK\",\"subscribe_acl\":[{\"pattern\":\"d/e/f\"}]}"```

Now if my connected client with client-id "test-client" wants to subscribe on topic d/e/f. In this case client is not disconnecting nighter getting any data because connected session don't have updated ACL info.

How can i overcome this issue? I am fully stuck here.

**Comment by ioolkos** [comment]
@zia069 your assumption is that an invalid SUBSCRIBE attempt will result in a server side disconnect. This is not the case. The server will still SUBACK with a failure code (128) but keep the connection.

As the ACL cache is set at connect time, you also don't see the updated ACL in the session. But that's exactly why there's the `vmq-admin session reauthorize` API you could call somehow after updating the ACL (in case you know for which Client).
Admittedly... this is not beautiful.

**Comment by zia069** [comment]
@ioolkos thank you for you quick response. 
Is mqtt version 3.1 support SUBACK? 
As i am thinking if client receive SUBACK with failure code (128) it will reconnect again.

**Comment by ioolkos** [comment]
@zia069 I suppose you have been able to sort this out, so closing the issue.
