### ISSUE TITLE
return user properties and response topic as part of CON ACK from redis lua plugin for MQTT5 clients

### ISSUE THREAD

**Issue by vshirol** [vernemq/vernemq#1781]
### Environment

- VerneMQ Version: 1.10.2
- OS:  Red Hat Enterprise Linux Server 7.5 (Maipo)
- Erlang/OTP version (if building from source): N.A
- VerneMQ configuration (vernemq.conf) or the changes from the default: enabled vmq_diversity plugin
- Cluster size/standalone: 1 node

### Expected behaviour

We are writing or extending out-of-the-box redis.lua plugin of vmq_diversity to support our below custom needs:
              -  Authentication and authorization based on, way we store in our redis data store.
              -  Return the user-properties and response topic if authentication is successful.
              -  Only for MQTT 5 clients, as above are only supported in MQTT5. So we use hook "auth_on_register_m5".

Below is our customized, redis.lua script for the above requirements:
```
function auth_on_register_m5(reg)
    print('auth_on_register_m5',reg.username)
    if reg.username ~= nil and reg.password ~= nil then
        unameKey = "username:"
        hashKey  = "test.client.restricted.broker.creds"
        if reg.mountpoint ~= "/restricted" then
           hashCodeVal = hashCode(reg.username)
           bucket = hashCodeVal % 512
           hashKey = "test.client.creds:"..bucket
        end
        res = redis.cmd(pool, "hget " .. hashKey .." " .. unameKey..reg.username)
        res = json.decode(res)
        if reg.password == res.passhash then
            -- properties = reg.properties
                return {properties =
                   {p_user_property =
                      {{k1 = "v1"}, {k2 = "v2"}, {k3 = "v3"}}}}
        end
    end
    return false
end
```
From the above code what we expect is MQTT5 client gets authenticated using data stored in redis and return the user-properties/response topic(its not there in the above snippet) if authentication is successful. 
And con ack packet to the client will get user-properties and response topic.

### Actual behaviour
- MQTT5 client's doesn't get user-properties/response topic in con ack, although there are no errors seen in logs and client(mqtt5) gets con ack packet as well but without user-properties and response topic fields in it.

Please let us know this is supported in vmq_diversity or not. If not then how this can be achieved, as this is from MQTT 5 specification.

**Comment by ioolkos** [comment]
@vshirol thanks, this is a duplicate of https://github.com/vernemq/vernemq/issues/1764
For context, read my answers there.

In short: VerneMQ behaviour is spec conform (it chooses not to send user properties) but exposing this to plugins (so that they can override it) is a useful addition and should be implemented.

**Comment by vshirol** [comment]
@ioolkos 
Thanks for your quick response. When you say exposing this to plugins should be is useful addition and should be implemented, any idea in which version of VMQ its going to part of?

**Comment by ioolkos** [comment]
@vshirol I have not yet decided. Feel free to propose a PR, it might even be a totally low hanging thing.
What I wanted to say is that I see the use case for this, and deem it a valuable feature.

**Comment by Jothy90** [comment]
I have create a [PR](https://github.com/vernemq/vernemq/pull/1933), Please review and merge it. 
Sample response of auth_on_register_m5 hooks is: 
`{ok, #{properties => #{p_response_info => <<"test">>}}}.`

**Comment by vshirol** [comment]
@Jothy90  Thanks for these changes, to me changes look good though I haven't tested it. I might not be correct person to review these and merge. May be @ioolkos ?

**Comment by vshirol** [comment]
Sorry I see its already reviewed and merged.  Thanks to both @Jothy90 & @ioolkos.

**Comment by vshirol** [comment]
Hi @ioolkos/@Jothy90 as code is merged for this request, can you please let me know in which upcoming version of VMQ release this will be available and tentative timeline?

**Comment by vshirol** [comment]
Hello @ioolkos @Jothy90 

We tested this feature with the latest VerneMQ 2.1.1. Although no errors are thrown with either the Lua plugin or webhook approach, the MQTT client does not receive p_response_info in the CONNACK packet (verified via Wireshark/tcpdump).Below are the return examples we tried:

Lua hook (auth_on_register_m5):
`return {ok, {properties = {p_response_info = "client/response"}}}`

Webhook response (auth_on_register_m5):
`{
  "result": "ok",
  "modifiers": {
    "properties": {
      "p_response_info": "client/response"
    }
  }
}`

Let us know if there is anything wrong in our above return's.
