### ISSUE TITLE
I can't be sure if the TLS certificates work

### ISSUE THREAD

**Issue by andygrillo** [vernemq/vernemq#1785]
I just got Vernemq running on Ubuntu 18.04, using a self-signed ca certificate to create secure connections with IOT devices (we don't plan to use client certificates also).

What is curious is I am able to connect just fine from an external device using this

`mosquitto_sub -h mqtt.mydomain.com -p 8883 --cafile ./vernemq_ca.crt -t "test" -u username -P password -d`

But I am also able to connect using MQTT Explorer on an external device without attaching any Ca certificate, if I turn `validate certificate` off:
![image](https://user-images.githubusercontent.com/6279965/116431292-44f6d380-a80d-11eb-9d95-d2808bf036c2.png)

Does this mean the connection is not secure ? 

Some settings I have in my conf:
```
allow_anonymous = off
#listener.tcp.default = 127.0.0.1:1883
listener.ssl.default = 0.0.0.0:8883
listener.ssl.cafile = /etc/vernemq/ssl/vernemq_ca.crt
listener.ssl.certfile = /etc/vernemq/ssl/vernemq.crt
listener.ssl.keyfile = /etc/vernemq/ssl/vernemq.key
#listener.ssl.require_certificate = on
```

**Comment by ioolkos** [comment]
@andygrillo I suppose this helps? https://github.com/thomasnordquist/MQTT-Explorer/issues/79

**Comment by andygrillo** [comment]
thansk @ioolkos , this seems relevant. I am not sure I understand how its possible to uncheck validate certficates ? 

MQTT Explorer is just a GUI so if its possible to bypass certificates using this, then other devices may also be able to bypass certificates also using other mqtt client methods, right ?

**Comment by ioolkos** [comment]
@andygrillo I think a Verne issue is not the most effective place to look into TLS basics, or other tools. I would guess that the "(Don't) validate cert" option in MQTT-Explorer does the same as the `--insecure` flag in the Mosquitto clients.
