### ISSUE TITLE
vernemq does not build with openssl 3.0.0

### ISSUE THREAD

**Issue by satya-rajesh** [vernemq/vernemq#1787]
### Environment

- VerneMQ Version: 1.11.0
- OS: photon OS
- Erlang/OTP version (if building from source): 23.1
- VerneMQ configuration (vernemq.conf) or the changes from the default: default
- Cluster size/standalone: Standalone Build

### Expected behaviour

- The build works with openssl 1.1.1 but the build fails with openssl 3.0.0.

### Actual behaviour

- Build vernemq with OTP 23.1, openssl 3.0.0, it fails

Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library: '/usr/lib/erlang/lib/crypto-4.8/priv/lib/crypto.so: undefined symbol: FIPS_mode'"
OpenSSL might not be installed on this system.

=WARNING REPORT==== 28-Apr-2021::12:05:10.029753 ===
The on_load function for module crypto returned:
{error,{load_failed,"Failed to load NIF library: '/usr/lib/erlang/lib/crypto-4.8/priv/lib/crypto.so: undefined symbol: FIPS_mode'"}}

escript: exception error: undefined function crypto:start/0
in function erl_eval:do_apply/6 (erl_eval.erl, line 680)
in call from escript:eval_exprs/5 (escript.erl, line 872)
in call from erl_eval:local_func/6 (erl_eval.erl, line 567)
in call from escript:interpret/4 (escript.erl, line 788)
in call from escript:start/1 (escript.erl, line 277)
in call from init:start_em/1
in call from init:do_boot/3
^[[0;31m===> ^[[1mHook for compile failed!

**Comment by ioolkos** [comment]
Referencing your opened issue here for others: https://github.com/erlang/otp/issues/4577
