### ISSUE TITLE
AMQJS0007E Socket error:undefined.

### ISSUE THREAD

**Issue by mohammdkhalilii** [vernemq/vernemq#1797]
### Environment

- VerneMQ Version: 1.10.3
- OS: ubuntu Ubuntu 20.04.2 LTS
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: standalone

listener.ws.defaault = 193.151.131.152:8081

### Expected behavior

Connect to my host with [HiveMQ Websocket Client Test](http://www.hivemq.com/demos/websocket-client/) 

### Actual behaviour

Give an error : AMQJS0007E Socket error:undefined.

**Comment by ioolkos** [comment]
@mohammdkhalilii make it a habit to check the Verne logs. Have you configured the listener for the protocol versions you want to allow?

**Comment by mohammdkhalilii** [comment]
> @mohammdkhalilii make it a habit to check the Verne logs. Have you configured the listener for the protocol versions you want to allow?

I don't know how to do that , could you please give a instruction or a documentation ?

**Comment by ioolkos** [comment]
https://docs.vernemq.com/configuration/listeners#allowed-protocol-versions

Best to use a named listener version:
`listener.ws.my_listener.allowed_protocol_versions = 3,4,5`

**Comment by mohammdkhalilii** [comment]
I found solution , it's because of domain .
I can connect via ip and if I want to connect via domain , I have to use nginx proxy pass.
