### ISSUE TITLE
CLOSE_WAIT Connections on websockets

### ISSUE THREAD

**Issue by pijain** [vernemq/vernemq#1801]
### Environment

- VerneMQ Version: 1.11.0
- OS: Ubuntu
- Erlang/OTP version (if building from source): 22.3 (Built from tag 1.11.0)
- VerneMQ configuration (vernemq.conf) or the changes from the default: Also we are using auth/gone/offline webhooks.
```
allow_anonymous = off

## Netsplits
allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = on

## Sessions
allow_multiple_sessions = on
coordinate_registrations = off
retry_interval = 20

## Client
max_client_id_size = 100
max_inflight_messages = 1
max_online_messages = 10
max_offline_messages = 0
max_message_size = 0
upgrade_outgoing_qos = off
queue_deliver_mode = balance

# Max message rate
max_message_rate = 10
max_drain_time = 20
persistent_client_expiration = 1h

## Listners
listener.max_connections = infinity
listener.nr_of_acceptors = 20000
listener.http.default = 0.0.0.0:8888
listener.ws.default = 0.0.0.0:9001
listener.tcp.default = 0.0.0.0:1883
listener.tcp.allowed_protocol_versions = 3,4,5
listener.vmq.clustering = 0.0.0.0:44053

## Systree Reporter
systree_enabled = on
systree_interval = 20000

## Graphite
graphite_enabled = off

## Shared subscription policy
shared_subscription_policy = prefer_local

## Plugins
plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = on
plugins.vmq_bridge = off
metadata_plugin = vmq_swc

## ACL
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10

## Logging
log.console = file
log.console.level = info
log.console.file = /vernemq/logs/console.log
log.error.file = /vernemq/logs/error.log
log.syslog = off
log.crash = on
log.crash.file = /vernemq/logs/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5

## Node Settings
nodename = VerneMQ
distributed_cookie = vmq
erlang.async_threads = 1024
erlang.max_ports = 524288
leveldb.maximum_memory.percent = 10
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
erlang.schedulers.compaction_of_load = true
erlang.schedulers.utilization_balancing = true
erlang.distribution_buffer_size=32MB
```
- Cluster size/standalone: 20

### Expected behaviour

Memory usage should be around 10-25% and there should be no CLOSE_WAIT connections on websockets port

### Actual behaviour

- We see the memory being exhausted and OOM killer killing up VerneMQ process(At load of 30K connected clients or even less, few times we have seen node going down with just 2K connected clients), all the VM's are 4 Core/16G
- There are piles of CLOSE_WAIT connections
- Once we start the see the close waits, particular node is not publishing anything
- We also see VerneMQ showing large number of connections on VerneMQ status page all of them are stale or not actual numbers.
- Frequently we have seen clients originally connecting with clean_session: True turns automatically to clean_session: False on vmq-admin session show command.

We see a lot of warnings for:

```
2021-05-27 11:01:35.709 [warning] <0.436.79>@vmq_websocket:handle_fsm_return:157 ws session error, force terminate due to '{cant_parse_connect_fixed_header,<<50,53,0,31,47,85,83,47,53,50,53,50,47,102,108,104,48,48,49,118,47,99,111,110,110,101,99,116,101,100,47,98,117,115,121,0,6,123,34,102,108,104,48,48,49,118,34,58,34,98,117,115,121,34,125>>}'
2021-05-27 11:01:36.265 [warning] <0.788.79>@vmq_websocket:handle_fsm_return:157 ws session error, force terminate due to '{cant_parse_connect_fixed_header,<<50,51,0,29,47,85,83,47,51,55,47,100,103,116,48,48,48,121,47,99,111,110,110,101,99,116,101,100,47,98,117,115,121,0,19,123,34,100,103,116,48,48,48,121,34,58,34,98,117,115,121,34,125>>}'
```

Another observation is most of the times we see the offline clients in -ve number, but on the nodes where this issue happens it starts to grow up in +ve.

**Comment by ioolkos** [comment]
@pijain I don't know what causes your CLOSE_WAIT states. But a note on the warnings: your client sessions get terminated because they send an MQTT Publish when the server expects an MQTT Connect. Ensure that the Clients do not do that and see whether those warnings disappear. 
(the CLOSE_WAITS might even be related to those session terminations)

**Comment by pijain** [comment]
@ioolkos can you also give us any suggestions on why do we see a lot of clients with clean session false, we have cross checked from client side are ensured we are connecting wit clean-session true.

Another thing is we have never seen any online client with clean session set to false, those are always offline clients

**Comment by ioolkos** [comment]
@pijain I have trouble understanding your remark.
if you see (how do you "see"?) lots of clients with clean_session false, then that's what the clients requested. The broker is not going to set or override that.

**Comment by pijain** [comment]
@ioolkos we will have it checked from client side again, if any of the clients are misconfigured and sending the clean session as false.

Also can you help me understand `Subquery failed due to timeout` can it be the related to issues we are facing with the VerneMQ cluster.
