### ISSUE TITLE
1.12.0 docker - after restart cannot join back to cluster

### ISSUE THREAD

**Issue by sooslaca** [vernemq/vernemq#1805]
### Environment

- VerneMQ Version: 1.12.0  (1.11.0 works fine, tested)
- OS: docker/alpine
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 2

### Expected behaviour

after docker restart 'secondary' node it should come back up

### Actual behaviour

not coming back, failing

---
Not necessary sure but this is in 1.12.0 changelog:
`Use safe mode for binary_to_term in SWC`

The fail message I get on the secondary node:
```
11:57:31.869 [error] Error in process <0.241.0> on node 'VerneMQ@1a.b.c.d' with exit value:
{badarg,[{erlang,binary_to_term,[<<131,104
```
I'm not an erlang guru but seems like badarg happens when some kind of 'unsafe' data.
https://erlang.org/doc/man/erlang.html#binary_to_term-1

I assume it cannot be unsafe if vernemq itself put that on the disk?

Replicate like this:
Have 2 nodes (docker alpine 1.12.0) use DISTRIBUTED_COOKIE
Start node 1 
Start node 2 (volume mount to /vernemq/data to persist) with proper DISCOVERY_NODE
Stop node 2  (docker stop, docker rm)
Start node 2 <<< issue happens here

Thanks

**Comment by ioolkos** [comment]
@sooslaca can you give me a source code line from the error.log?

Did you use existing on-disk SWC state? The error is clearly related to the change for binary encoding.

**Comment by sooslaca** [comment]
hi @ioolkos,

I can't see code line in error.log either
```
2021-06-01 11:56:28.437 [error] emulator Error in process <0.247.0> on node 'VerneMQ@a.b.c.d' with exit value:
{badarg,[{erlang,binary_to_term,
```

I use nothing special, I use on-disk, yes.
Also I don't know if it matters, but in `vm.args` I changed '-setcookie vmq' to something else which is unique.

**Comment by sooslaca** [comment]
ah it was in `crash.log` after the end of the binary data
```
,[safe]],[]},{vmq_swc_store,'-init_dotkeymap/1-fun-1-',4,[{file,"/src/vernemq/apps/
vmq_swc/src/vmq_swc_store.erl"},{line,763}]},{vmq_swc_db_leveldb,iterate,6,[{file,"/src/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,138}]},{vmq_swc_db_leveldb
,'-handle_call/3-fun-1-',6,[{file,"/src/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,110}]}]}
```

**Comment by ioolkos** [comment]
You can't use older SWC metadata on-disk, for 1.12.0 due to the safety changes mentioned.

Do you see these errors with fresh state? (that is, not reusing existing on disk data dirs). Then we would have a wrong encoding somewhere.

**Comment by sooslaca** [comment]
mea culpa, makes sense, working. The 'Incompatibility Note:' should be BIG and RED :) Thanks for your help

**Comment by ioolkos** [comment]
Ok, glad it worked. Funny enough is that I *tried* to make that note big and red :) (Github markdown though). I'm also still working on updating the docs for 1.12.0.
