### ISSUE TITLE
1.12.0 docker on rpi32 - after restart cannot join back to cluster

### ISSUE THREAD

**Issue by mtannertdev** [vernemq/vernemq#1807]
### Environment

- VerneMQ Version: 1.12.0
- OS: Raspberry Pi OS (Buster) / Docker 20.10.6
- Erlang/OTP version (if building from source): Erlang 22.1 on Alpine 3.11 (armhf)
- VerneMQ configuration (vernemq.conf) or the changes from the default
  - "docker-compose.yml" environment variables:
    - DOCKER_IP_ADDRESS=172.24.1.1
    - DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT=0.0.0.0:1883
    - DOCKER_VERNEMQ_LISTENER__WS__DEFAULT=0.0.0.0:8080
    - DOCKER_VERNEMQ_LISTENER__HTTP__DEFAULT=0.0.0.0:8989
    - DOCKER_VERNEMQ_LISTENER__HTTP__METRICS=0.0.0.0:8888
    - DOCKER_VERNEMQ_DISTRIBUTED_COOKIE=aaabbbcccddd
    - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
    - DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT=on
    - DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT=on
    - DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT=on
    - DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT=on
- Cluster size/standalone:
  - 2x Raspberry Pi 4 4GB (one cluster node per physical node)

VerneMQ 1.12.0 built on a Raspberry Pi 4 (`make rpi32`), using a multi-stage docker build: Alpine:3.11 for the build and Alpine:3.12 for the image. Image builds properly. Two nodes are connected via cluster. No previous data, no previous version. These are two clean v1.12.0 images with no previous data.

### Expected behaviour

When one node is restarted, it should reconnect to the cluster with no errors

### Actual behaviour

When restarting one node: the following error is printed to console:
```
Loaded NodeClock fromDisk #{{'VerneMQ@172.24.1.1',
                                <<214,20,120,201,252,2,10,107,73,247,65,191,
                                  109,240,61,228,125,157,45,37>>} =>
                                {20,0}}
21:22:49.905 [error] Error in process <0.217.0> on node 'VerneMQ@172.24.1.1' with exit value:
{badarg,[{erlang,binary_to_term,[<<131,104,2,116,0,0,0,1,104,2,104,2,100,0,18,86,101,114,110,101,77,81,64,49,55,50,46,50,52,46,49,46,49,109,0,0,0,20,214,20,120,201,252,2,10,107,73,247,65,191,109,240,61,228,125,157,45,37,97,9,104,2,104,3,98,0,0,6,86,98,0,11,118,97,98,0,2,18,63,104,4,100,0,10,114,101,116,97,105,110,95,109,115,103,109,0,0,0,6,79,110,108,105,110,101,116,0,0,0,0,100,0,9,117,110,100,101,102,105,110,101,100,116,0,0,0,1,104,2,100,0,18,86,101,114,110,101,77,81,64,49,55,50,46,50,52,46,49,46,49,109,0,0,0,20,214,20,120,201,252,2,10,107,73,247,65,191,109,240,61,228,125,157,45,37,97,9>>,[safe]],[]},{vmq_swc_store,'-init_dotkeymap/1-fun-1-',4,[{file,"/src/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,763}]},{vmq_swc_db_leveldb,iterate,6,[{file,"/src/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,138}]},{vmq_swc_db_leveldb,'-handle_call/3-fun-1-',6,[{file,"/src/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,110}]}]}
```

**Comment by ioolkos** [comment]
@mtannertdev thanks, this is interesting. It might look like we can shoot ourselves in the foot with the new safe encodings. My guess is on something else though:
I'm currently thinking whether this could be an ARM/RPI problem because I wonder how you were able to build LevelDB. Maybe the issue is related to that.

I can decode your binary, both with `binary_to_term(YourBinary)` as well as with `binary_to_term(YourBinary, [safe])`. They are both the same, and they are the expected term.

One thing you could try is whether you see similar decoding errors when you switch the metadata protocol to
`metadata_plugin=vmq_plumtree` in the `vernemq.conf`

**Comment by mtannertdev** [comment]
Added this line to "docker-compose.yml": and started both nodes clean:
```
    environment:
      - DOCKER_VERNEMQ_METADATA_PLUGIN=vmq_plumtree
```

Both nodes came up and connected to the cluster. Took down one node and brought it back up. This time it reconnected fine. The only thing I see that is interesting is the log about metadata exchange:

```
13:25:22.668 [info] successfully connected to cluster node 'VerneMQ@172.24.1.1'
13:25:30.482 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 140 keys
13:25:40.204 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 58 keys
13:25:50.190 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 58 keys
13:26:00.239 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 58 keys
13:26:10.181 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 58 keys
13:26:20.193 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 57 keys
13:26:30.198 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 57 keys
13:26:40.174 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 57 keys
13:26:50.164 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 57 keys
13:27:00.191 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 57 keys
13:27:10.174 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 57 keys
13:27:20.197 [info] completed metadata exchange with 'VerneMQ@172.24.1.1'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 57 keys
```

Is this normal, or is there something failing in the replication where it keeps trying to repair the 57 keys unsuccessfully, and therefore keeps trying to do it?

**Comment by ioolkos** [comment]
@mtannertdev good question, do those 57 keys persist, even with a cluster facing input? I would expect this to go down to "nothing repaired" or a similar log, but I'm not 100% sure right now (I haven't checked the code).

Keys here can ultimately represent SubscriberIds or Retained message ids.

**Comment by mtannertdev** [comment]
I just checked... the cluster is still up over the weekend and those log messages with keys are still being written every ten seconds. I wonder if it has anything to do with the fact that I allow new subscriptions/registrations/publications/etc during a netsplit and somehow something isn't getting reconciled when the down node rejoins the cluster.

**Comment by ioolkos** [comment]
@mtannertdev just fyi, I reverted those safe encodings in master.

**Comment by mtannertdev** [comment]
Following back up on this, I still see log messages every ten seconds after a node disconnects and rejoins the cluster:
```
14:03:52.320 [info] completed metadata exchange with 'VerneMQ@172.24.1.2'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 245 keys
14:04:02.218 [info] completed metadata exchange with 'VerneMQ@172.24.1.2'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 245 keys
14:04:12.272 [info] completed metadata exchange with 'VerneMQ@172.24.1.2'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 245 keys
14:04:22.269 [info] completed metadata exchange with 'VerneMQ@172.24.1.2'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 245 keys
14:04:32.298 [info] completed metadata exchange with 'VerneMQ@172.24.1.2'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 245 keys
14:04:42.282 [info] completed metadata exchange with 'VerneMQ@172.24.1.2'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 245 keys
```
