### ISSUE TITLE
sparkplug is support?

### ISSUE THREAD

**Issue by siaron** [vernemq/vernemq#1809]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behaviour

- Please describe the expected behaviour.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

**Comment by ioolkos** [comment]
@siaron Yes (and every MQTT broker supports Sparkplug, it just defines conventions on payload format and topics).
