### ISSUE TITLE
Avoid logging passwords when `auth_on_register` fails

### ISSUE THREAD

**Issue by mitchellrj** [vernemq/vernemq#1815]
### Environment

- VerneMQ Version: 1.12.0
- OS: GNU/Linux (Alpine 3.13)
- Erlang/OTP version (if building from source): 23
- VerneMQ configuration (vernemq.conf) or the changes from the default: N/A
- Cluster size/standalone: N/A

### Expected behaviour

When `auth_on_register` diversity calls fail, the password argument is omitted or masked.

### Actual behaviour

When `auth_on_register` diversity calls fail, all the arguments are logged out, e.g.
```
11:52:32.409 [error] can't call function auth_on_register with args [{addr,<<"172.26.0.1">>},{port,37488},{mountpoint,<<>>},{client_id,<<"admin">>},{username,<<"admin">>},{password,<<"CorrectBatteryHorseStaple">>},{clean_session,true}] in "./share/lua/auth/myscript.lua" due to {...]}
```

This is an instance of [CWE-532](https://cwe.mitre.org/data/definitions/532.html).

**Comment by ioolkos** [comment]
@mitchellrj Yes. It's not only that btw. Need a systematic approach, or obfuscation approach - maybe also with a view on what's best practice from the Erlang logger frameworks and/or community. It's a balance between what's useful for investigation and what's critical. 
For instance sometimes binaries are logged (for a crash, let's say). They can be manually parsed, and then you'll have the message payload if it was not encrypted.

---
https://github.com/sponsors/vernemq
