### ISSUE TITLE
Increased latency on session propagation on v1.12.0?

### ISSUE THREAD

**Issue by ghost** [vernemq/vernemq#1817]
We’ve noticed increased latency on session propagation for version 1.12.0. More specifically, we can't broadcast to newly connected clients that are on a different node than the receiver.

## Environment
* VerneMQ Version: 1.12.0
* OS: Docker debian:buster-slim
* Erlang/OTP version: 23.3.2.0
* K8s cluster with two VerneMQ pods/nodes for testing
* we built it using the [provided distribution](https://github.com/vernemq/vernemq/releases/download/1.12.0/vernemq-1.12.0.buster.x86_64.deb)

## vernemq.conf overrides
```
########## Start ##########
# we have a license:
accept_eula=yes
distributed_cookie=zebra_vmq_cluster_cookie
log.console.level=info
max_inflight_messages=1
listener.nr_of_acceptors=10
max_online_messages=-1
max_offline_messages=-1
listener.max_connections=infinity
allow_anonymous=on
plugins.vmq_passwd=off
metadata_plugin=vmq_swc
log.console=console
listener.tcp.localhost=127.0.0.1:1883
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.20.1.7:1883
listener.ws.default = 10.20.1.7:8080
listener.vmq.clustering = 10.20.1.7:44053
listener.http.metrics = 10.20.1.7:8888
# Enable & Persist the vmq2rmq plugin :
plugins.vmq2rmq = on
plugins.vmq2rmq.path = /vernemq/custom-plugins/vmq2rmq/
########## End ##########
```

## Expected Behavior
* Newly connected clients' messages are not dropped and make it through the system

## Test Description & Observed Behavior
* about 20 fresh/new clients were connected at once per test, which we repeated several dozen times
* about half the messages drop every time we connect a fresh set of clients to the cluster
* we traced messages in our system and on Verne to narrow down where they were being dropped, which is how we found out that:
    * everything works as it should when we scale Verne down to 1 pod/node
    * everything eventually works if we attempt to send messages for the same initially failed clients (which are no longer newly connected/their sessions are on every node when running later tests)
* additionally, we have not seen this issue on v1.11.0

## Further Info
As far as we know, our build of the `swc_4` branch that preceded v1.12.0 did not exhibit this behavior.
We re-built using v1.12.0-rc1, and that has the same issue as v1.12.0. 
Is this known/on the radar? If so, is there a workaround?

Also, is this [test](https://github.com/vernemq/vernemq/blob/d8da843913d699d7be15694a270a11b4ebaab751/apps/vmq_server/test/vmq_cluster_SUITE.erl#L15) at all related?

**Comment by ioolkos** [comment]
@akrucz-zebra Thanks for testing 1.12.0! much appreciated.

The test you mentioned is probably not related. All test suites were switched to SWC which implies some timing adaptations or rewrites of the test. Some were disabled for that reason.

Could you give me a clearer picture of what the test does? where are the publishers and the consumers? who sends messages to whom? are the sets of 20 consumers or publishers, or both?

**Comment by ioolkos** [comment]
Forgot to close it, this is fixed for a long time. In 1.12 initially, we had disabled SWC broadcast by error.
