### ISSUE TITLE
Tag v1.12 on Docker Hub

### ISSUE THREAD

**Issue by sarunask** [vernemq/vernemq#1819]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: v1.12.0
- OS: Linux
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf) or the changes from the default: N/A
- Cluster size/standalone: N/A

### Expected behaviour

- On DockerHub (https://hub.docker.com/r/vernemq/vernemq/tags?page=1&ordering=last_updated) we expect to see tags:
* 1.12.0-alpine
* 1.12.0

### Actual behaviour

- We see `latest` and `latest-alpine`. It's best to use specific tag from DockerHub when deploying VerneMQ to PROD env.

**Comment by ioolkos** [comment]
@sarunask thanks, I know.
