### ISSUE TITLE
Question: how to improve new connections per second rate

### ISSUE THREAD

**Issue by mladen-djordjevic** [vernemq/vernemq#1820]
### Environment

- VerneMQ Version: 1.10.2
- OS: Linux
- Erlang/OTP version (if building from source): Built from source
- Cluster size/standalone: standalone
- VerneMQ configuration override (vernemq.conf):
accept_eula = yes
allow_anonymous = off
max_inflight_messages = 20
max_online_messages = 1000000
max_offline_messages = 1000
listener.ssl.ssl-listener.buffer_sizes = 2048,4096,8192
listener.ssl.ssl-listener.max_connections = infinity
listener.ssl.ssl-listener.nr_of_acceptors = 1000
listener.ssl.ssl-listener = 0.0.0.0:1884
listener.ssl.ssl-listener.use_identity_as_username = on
listener.ssl.cafile = <path_to_file>
listener.ssl.certfile = <path_to_file>
listener.ssl.keyfile = <path_to_file>
listener.ssl.ssl-listener.require_certificate = on
plugins.vmq_passwd = on
plugins.vmq_diversity = on
vmq_acl.acl_file = <path_to_file>
vmq_passwd.password_file = <path_to_file>
vmq_diversity.script_dir = <path_to_file>
erlang.process_limit = 10000000

I run a bunch of load tests using a custom load testing tool, and experimenting with different VerneMQ configurations and test cases.
Different VerneMQ configurations include testing with and without SSL, playing with 'erlang' and 'messages' parameters from the provided vernemq.conf file above.
Different test cases mostly include playing with different numbers of connections and ramp-up times.
I have used Grafana for monitoring both VerneMQ as a service and hardware resources.
I managed to make a large number of concurrent connections (500K) but for a longer period (1 hour).

One of the goals of performance tests was **what is the maximum number of connections per second.** The maximum number I have reached is about 600 connections per second. I was not able to find what causes this limitation - everything looks normal (not at maximum) on hardware and vernemq metrics.

I know this may be very specific from case to case, but are there any tips and/or configuration tweaks that make improve the current rate of 600 new connections per second?

**Comment by ioolkos** [comment]
@mladen-djordjevic Registers need to be coordinated so that there is ever only 1 unique ClientID on the whole cluster.
You can turn this off with `coordinate_registrations = off`
You can also test whether `metadata_plugin = vmq_swc` gives you better register performance.
Also, note that if you use different ClientIDs for every test run, you'll end up loading the cluster with a lot of unused ClientID keys. This could end up slowing down registers too.

On `accept_eula=yes`, please read EULA, you likely need a subscription.

---
https://github.com/sponsors/vernemq

**Comment by mladen-djordjevic** [comment]
@ioolkos thank you for the suggestions, I will try it and keep you updated.
As per VerneMQ EULA, building it from a source doesn't require a subscription. Am I correct?

**Comment by ioolkos** [comment]
>  As per VerneMQ EULA, building it from a source doesn't require a subscription. Am I correct?

Yes.

---
https://github.com/sponsors/vernemq
