### ISSUE TITLE
No cluster with Istio Proxy 

### ISSUE THREAD

**Issue by rtrive** [vernemq/vernemq#1823]
### Environment

- VerneMQ Version: 1.11.0
- OS: Docker (K8s)
- VerneMQ configuration (vernemq.conf) or the changes from the default
```
########## Start ##########
accept_eula=yes
log.console.level=debug
shared_subscription_policy=random
vmq_bridge.ssl.sbr0.insecure=on
vmq_bridge.ssl.sbr0.try_private=on
vmq_passwd.password_file=/etc/vernemq/vmq.passwd
vmq_acl.acl_file=/etc/vernemq/vmq.acl
plugins.vmq_passwd=on
plugins.vmq_bridge=on
plugins.vmq_acl=on
log.console=console
listener.tcp.localhost=127.0.0.1:1883
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.56.5.45:1883
listener.ws.default = 10.56.5.45:8080
listener.vmq.clustering = 10.56.5.45:44053
listener.http.metrics = 10.56.5.45:8888
########## End ##########

```
- Cluster size/standalone: 3 nodes 

### Expected behaviour

- Every nodes join each other without problem with istio proxy

### Actual behaviour

- Nodes cannot join and with 3 nodes there is no cluster but no error on both istio and vernemq pod
- Pod name on status dashboard is wrong. There is a dot that is not correct: `vernemq-k8s-1..messaging.svc.cluster.local`.Without istio everything is fine

**Comment by ioolkos** [comment]
@rtrive thanks, seems you have to figure out what's happening regarding the node names there, because that's clearly related.

---
https://github.com/sponsors/vernemq

**Comment by rtrive** [comment]
@ioolkos this happens only with istio sidecar because without them it doesn't work. Am i the only one?

**Comment by rtrive** [comment]
Pull request on vernemq docker repo
https://github.com/vernemq/docker-vernemq/pull/288

**Comment by ioolkos** [comment]
@rtrive Thanks, can you let me know why the PR is necessary? I think the PR itself looks fine, but I'm not sure I understand why Verne has to wait for Istio. For instance, this doesn't seem to be necessary with HAProxy?

As this is the official docker repo with the subscriptions, ideally I want to keep it as slim as possible.

**Comment by rtrive** [comment]
@ioolkos sure! the problem is that on row 54, the startup script send a request to k8s api and it's rejected due to istio not ready. This cause `vernemq-k8s-1..messaging.svc.cluster.local` to have no service name between pod name and namespace and this led to impossibility to join to the cluster.

I made a raw test putting a sleep bash command before the startup and everything works fine because istio is ready to accept requests from vernemq docke

**Comment by rtrive** [comment]
any news for this PR?

**Comment by chetniks** [comment]
Hi , 

I am having the same issue.

**Comment by rtrive** [comment]
Merged into master. Issue solved

**Comment by chetniks** [comment]
Hi Guys,

When using latest image we are getting error on each node 
/usr/sbin/start_vernemq: line 50: istio_health: command not found
/usr/sbin/start_vernemq: line 51: [: !=: unary operator expected
Istio ready

I suppose the mistake is with one more space in 
Looks like you made type with 
istio_health () {
  cmd=$(curl -s http://localhost:15021/healtz/ready > /dev/null)
  status=$?
  return $status
}

Should be 
istio_health() {
  cmd=$(curl -s http://localhost:15021/healtz/ready > /dev/null)
  status=$?
  return $status
}

Can you please double check ?

Regards,
Srdjan I.

**Comment by ioolkos** [comment]
@rtrive @chetniks ah, did not see that. I suppose the official istio endpoint isn't `healtz` :)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) commercially requires a paid subscription.

**Comment by chetniks** [comment]
Hi @ioolkos ,

Right, its healthz/ready :D

Just to share my solution , hopefuly it will help anyone.
I just changed entrypoint in my deployment file as : 

        command:
        - /mnt/script/run.sh
        - 
and mounted that script via configmap as below: 

        volumeMounts:
          - name: running-script
            mountPath: /mnt/script/run.sh
            subPath: run.sh

#(OPTIONAL)
          - name: additional-config
            mountPath: /mnt/additional-config

     volumes:
        - name: running-script
          configMap:
            name: running-script
            defaultMode: 0555

Made configmap with name 'running-script" from file below : 
#!/bin/bash
# Check istio readiness
istio_health () {
  cmd=$(curl -s http://localhost:15021/healthz/ready > /dev/null)
  status=$?
  return $status
}
istio_health
status=$?
while [ $status != 0 ]; do
    istio_health
    sleep 1
done
echo "Istio ready"
NODE_NUMBER=${HOSTNAME##*-}
echo "Configuration initialization for pod number $NODE_NUMBER"
if [ -f /mnt/additional-config/additional-vernemq-$NODE_NUMBER.conf ]; then
	cat /mnt/additional-config/additional-vernemq-$NODE_NUMBER.conf >> /etc/vernemq/vernemq.conf
	echo "++++Additional configuration succesfully added into node number ${NODE_NUMBER} vernemq.conf++++" 
	cat /mnt/additional-config/additional-vernemq-$NODE_NUMBER.conf
	start_vernemq
	echo "POD ${HOSTNAME} initialization completed"
else
	echo "++++++++++No additional custom configuration set for this VerneMQ node+++++++++++++"
	start_vernemq
	echo "++++++++++++++++++++POD ${HOSTNAME} initialization completed+++++++++++++++++++++++"
fi

Script also contains possibility to add custom configuration into each node by making configmap 'additional-config' from folder which contains custom config for each node (as we had to bridge different nodes to different brokers , so most in between "if" and "fi" can deleted except "start_vernemq"

Current Logs: 
Istio ready
Configuration initialization for pod number 2
++++++++++No additional custom configuration set for this VerneMQ node+++++++++++++
10:48:34.407 [info] Sent join request to: 'VerneMQ@vernemq-0.vernemq.acquisition-featureistio.svc.cluster.local'
10:48:34.422 [info] cluster node 'VerneMQ@vernemq-0.vernemq.acquisition-featureistio.svc.cluster.local' UP
10:48:34.437 [info] cluster node 'VerneMQ@vernemq-1.vernemq.acquisition-featureistio.svc.cluster.local' UP
10:48:35.442 [info] successfully connected to cluster node 'VerneMQ@vernemq-1.vernemq.acquisition-featureistio.svc.cluster.local'
10:48:35.442 [info] successfully connected to cluster node 'VerneMQ@vernemq-0.vernemq.acquisition-featureistio.svc.cluster.local'

Regards,
Srdjan I.

**Comment by ioolkos** [comment]
@duke-bartholomew thanks so much for documenting.
Wondering whether I missed a PR on this in the past somehow? if yes, apologies.
It seems that the PR merged did resolve the original issue, though.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) commercially requires a paid subscription.

**Comment by duke-bartholomew** [comment]
just for your information:  there exists a configuration option in Istio that might render this work-around obsolete.
Apparently there is something like `holdApplicationUntilProxyStarts: true` that can be added in the `proxy.istio.io/config` annotation on the VerneMQ POD that does exactly what got patched in the VerneMQ startup script (i.e. wait for the istio proxy to be up before launching the main app).

I'll come back to this when I got the time to actually test this on our cluster.

**Comment by duke-bartholomew** [comment]
Ok, so I tested the above mentioned solution and can safely conclude that it indeed does the trick.
No need to configure VerneMQ with `DOCKER_VERNEMQ_KUBERNETES_ISTIO_ENABLED=1`.
Simply add following annotations for the istio-sidecar and VerneMQ happily waits to start until the istio proxy is ready:
```
    proxy.istio.io/config: |
      holdApplicationUntilProxyStarts: true
```
It also makes sense to use istio annotation `sidecar.istio.io/interceptionMode: TPROXY` for VerneMQ, otherwise you will loose the remote address information of the clients, because, by default, istio uses `interceptionMode: REDIRECT` which would result in seeing only the local pod address in VerneMQ, and not the actual IPs of the clients.

---

Next to above solutions I'm still trying to find out following issue:
```
10:05:43.613 [error] gen_server <0.8354.13> terminated with reason: sock_closed
10:05:43.613 [error] CRASH REPORT Process <0.8354.13> with 0 neighbours exited with reason: sock_closed in gen_server:handle_common_reply/8 line 805
```
which started to happen when activating the Istio side-car on VerneMQ and pops up (exactly) every hour.
It does not impact correct functionality however, so I'm still a little puzzled what might be causing this ...

**Comment by duke-bartholomew** [comment]
.. and as a final note on this:  the above CRASH-Report was due to Istio closing the Postgres connections because no traffic was detected on them (Istio has a 1 hour default configuration on this).

**Comment by ioolkos** [comment]
@duke-bartholomew had to be something like that :)
Thanks for update!

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) commercially requires a paid subscription.
