### ISSUE TITLE
MQTT-Explorer is gone after publish

### ISSUE THREAD

**Issue by geri777** [vernemq/vernemq#1825]
I am using VerneMQ Version 1.12.0 in a debian:buster-slim docker container.
I have added all possible vmq_webhooks to "vernemq.conf" - which cause http requests to my API, which writes into a log. 

When I connect to VerneMQ with MQTT-Explorer my log looks like this:

**CONNECT:**

```
'class' => 'On_client_gone',
'input' => '{"mountpoint":"","client_id":"oz0001"}',
'response' => '{}',

'class' => 'On_client_wakeup',
'input' => '{"mountpoint":"","client_id":"oz0001"}',
'response' => '{}',

'class' => 'On_register',
'input' => '{"peer_addr":"85.51.136.12","peer_port":23660,"mountpoint":"","client_id":"oz0001","username":null}',
'response' => '{}',

'class' => 'On_subscribe',
'input' => '{"username":null,"mountpoint":"","client_id":"oz0001","topics":[{"topic":"MYTOPIC","qos":0}]}',
'response' => '{}',

```

**PUBLISH to the topic MYTOPIC with a Json-Payload:**

(the following happens within the same second)
```
'class' => 'On_publish',
'input' => '{"username":null,"mountpoint":"","client_id":"oz0001","qos":0,"topic":"MYTOPIC","payload":"eyJoZWxsbyI6ICJ3b3JsZDIifQ==","retain":false}',
'response' => '{}',

'class' => 'On_offline_message',
'input' => '{"mountpoint":"","client_id":"CENSYS","qos":0,"topic":"MYTOPIC","payload":"eyJoZWxsbyI6ICJ3b3JsZDIifQ==","retain":false}',
'response' => '{}',

'class' => 'On_deliver',
'input' => '{"username":null,"mountpoint":"","client_id":"oz0001","qos":0,"topic":"MYTOPIC","payload":"eyJoZWxsbyI6ICJ3b3JsZDIifQ==","retain":false}',
'response' => '{"result": "ok"}',

'class' => 'On_client_gone',
'input' => '{"mountpoint":"","client_id":"oz0001"}',
'response' => '{}',

'class' => 'On_client_wakeup',
'input' => '{"mountpoint":"","client_id":"oz0001"}',
'response' => '{}',

'class' => 'On_register',
'input' => '{"peer_addr":"85.51.136.12","peer_port":23653,"mountpoint":"","client_id":"oz0001","username":null}',
'response' => '{}',

'class' => 'On_subscribe',
'input' => '{"username":null,"mountpoint":"","client_id":"oz0001","topics":[{"topic":"MYTOPIC","qos":0}]}',
'response' => '{}',
```

As you see, the client is gone and reconnects immediately. This does not happen when I use test.mosquitto.org with the same parameters. Also I don't have a clue where client-id CENSYS comes from - but I think that's another topic.

I am new to MQTT and probably I am not using the protocol correctly - your advice is much appreciated.

**Comment by ioolkos** [comment]
@geri777 in MQTT, the ClientID has to be unique. You're probably racing with the same ClientID from multiple connections.

**Comment by geri777** [comment]
Hi ioolkos, many thanks for the fast reply. No, I have just 1 client open - the client_id is 100% unique.

**Comment by ioolkos** [comment]
@geri777 ok, then I'd trace the client id, or look at the Verne logs. I'm afraid I can't help any further.

---
https://github.com/sponsors/vernemq

**Comment by geri777** [comment]
Hi @ioolkos thank you for your advice. I checked the logs of my running docker container using `docker logs <containername>` and this revealed the following error:

`Ranch listener {{172,17,0,2},1883} terminated with reason: no case clause matching undefined in vmq_webhooks_plugin:handle_response/3 line 799`

So maybe my response in the webhook for on_deliver is not correct. I am returning `{"result":"ok"}`.
I have also tried to add an empty modifiers object without any success.

**Comment by ioolkos** [comment]
@geri777 I can't see what you're doing wrong here. The JSON just has to be in the body of your HTTP response.
In the handle_response function you cited `Decoded` will look like this `[{<<"result">>, <<"ok">>}]`

```erlang
(VerneMQ@127.0.0.1)13> Decoded = [{<<"result">>, <<"ok">>}].  
[{<<"result">>,<<"ok">>}]
(VerneMQ@127.0.0.1)14> proplists:get_value(<<"result">>, Decoded).
<<"ok">>
(VerneMQ@127.0.0.1)15> proplists:get_value(<<"bla">>, Decoded).   
undefined
```
the `proplists:get_value/2` results in `undefined` in your case, that's why there's the runtime exception.

**Comment by geri777** [comment]
Ok, I am sorry - the whole issue is bullsh... I am not returning what I am logging - my http response was malformed.
