### ISSUE TITLE
Docker VerneMQ clustering in different server

### ISSUE THREAD

**Issue by sylvester-x** [vernemq/vernemq#1827]
- VerneMQ Version: latest
- OS: RHEL8
Using Docker to host the VerneMQ

### Expected behaviour
I expected the VerneMQ in a different server can do clustering

### Actual behaviour
When I do the setup and add in the discovery node for server 1, the log shows unable connect

Server 1 : docker run -d -p 1883:1883 -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" --name vernemq -d vernemq/vernemq

Server 2 : docker run -p 1883:1883 -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" -e "DOCKER_VERNEMQ_DISCOVERY_NODE=192.168.1.121" --name vernemq -d vernemq/vernemq

the logs is show on Server 2
![image](https://user-images.githubusercontent.com/45072247/122547145-4ea8f480-d062-11eb-9a20-0a45b426e8be.png)

**Comment by AndreasAmMueller** [comment]
Hi,    
sometimes it's working a bit strange...

As they are communicating with the IP Addresses, name these nodes as the IPs...

Server 1 (assuming to have `192.168.1.121`):
```
docker run --network host --name vernemq \
  -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" \
  -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" \
  -e "DOCKER_VERNEMQ_NODENAME=192.1681.121" \
  -d vernemq/vernemq
```

Server 2 (assuming to have `192.168.1.122`):
```
docker run --network host --name vernemq \
  -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" \
  -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" \
  -e "DOCKER_VERNEMQ_NODENAME=192.1681.122" \
  -e "DOCKER_VERNEMQ_DISCOVERY_NODE=192.168.1.121"
  -d vernemq/vernemq
```

You also may need to specify the `DOCKER_NET_INTERFACE` ... or when not using the host network, you need to map all ports used to enable cluster communication (using ports 4369, 44053, 9100-9109, see [the docker repository](https://github.com/vernemq/docker-vernemq/blob/3265897aed5c16b2b05f68ecb1769f8aa03d9366/Dockerfile#L28)).

**Comment by sylvester-x** [comment]
I had followed the step to setup
Now in my server 2, the VerneMQ cannot up

![image](https://user-images.githubusercontent.com/45072247/122856159-e9e2e800-d348-11eb-9b77-e77ed1fbe1da.png)

**Comment by ioolkos** [comment]
@sylvester-x interesting one, thanks. This is possibly related to some encoding changes in 1.12.0 which we will need to revert (already reverted in master).

You mention you followed steps (which ones?). And was this a deployment using existing state?

**Comment by sylvester-x** [comment]
I mean I followed the info that you provided. What is the mean deployment using the existing state?
