### ISSUE TITLE
Query VerneMQ HTTP API by clientid and topic

### ISSUE THREAD

**Issue by Arnabsinha-2684** [vernemq/vernemq#1829]
### Environment

- VerneMQ Version: 1.11
- OS: RHEL 7.7
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default: a webhook , bridge configured
- Cluster size/standalone: standalone

I am trying to use vernemq management API to retrieve the list of topics subscribed by each client-id. 
I have executed "**vmq-admin session show --topic --client_id**" and received the desired output. I am trying to get the similar output from vernemq management or HTTP API.

I executed below url but it does not return any value
curl -i "http://{api-key}@localhost:8888/api/v1/session/show\?--client_id\&--topic\"

Need your help to construct correct url

**Comment by ioolkos** [comment]
@Arnabsinha-2684 your URL looks correct. Do you use correct API key? `sudo vmq-admin api-key show`
Does Verne log anything when you issue the request?

---
https://github.com/sponsors/vernemq

**Comment by Arnabsinha-2684** [comment]
Hi,
The issue is fixed. It's due to wrong api-key I have provided. Thank you for pointing it out. You can close the issue.

**Comment by Arnabsinha-2684** [comment]
Closed
