### ISSUE TITLE
Rebar3 undefined function error under Debian 10

### ISSUE THREAD

**Issue by DB-CL** [vernemq/vernemq#1830]
### Environment

- VerneMQ Version: 1.12.0
- OS: Debian 10
- Erlang/OTP version (if building from source): 21.2.6
- VerneMQ configuration (vernemq.conf) or the changes from the default : default

### Expected behaviour

`make rel` should work

### Actual behaviour

Rebar3 crashes immediately with an error : 
```
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
```

You can try it on a docker image : 

```
sudo docker run -it debian:buster /bin/bash
apt-get update
apt-get -y install git bash curl build-essential erlang libsnappy-dev libssl-dev
git clone https://github.com/vernemq/vernemq
cd vernemq && make rel
```

The exact same snippet with `ubuntu:latest` instead of `debian:buster` works like a charm

Am I missing something ? 

Thanks

**Comment by ioolkos** [comment]
@DB-CL hm, I don't think you are missing something. What is the Erlang version on Buster, is it really `21.2.6` with apt-get?

---
https://github.com/sponsors/vernemq

**Comment by DB-CL** [comment]
Yes, everything is out of the box :

https://packages.debian.org/buster/erlang

**Comment by ioolkos** [comment]
@DB-CL I haven't checked but I guess it's a possibility that the included rebar3 binary is too new for OTP 21. 
In that case, I'm afraid you'd have to build Erlang 22 or 23 on Buster, before compiling Verne.

(but then also the question is what the default Erlang version is on Ubuntu latest, since you mention it's working on Ubuntu)

**Comment by DB-CL** [comment]
The default version in the latest Ubuntu version is : 23.2.6

If 21.2.6 is not enough then you should change the minimum Erlang version specified in the documentation (which is 21.2)

**Comment by ioolkos** [comment]
One more thing I should :)

> If 21.2.6 is not enough then you should change the minimum Erlang version specified in the documentation (which is 21.2)

**Comment by DB-CL** [comment]
Add this to your SHOULDO list :)
