### ISSUE TITLE
Undocumented breaking change in 1.12.0: default metadata plugin changed to SWC

### ISSUE THREAD

**Issue by mitchellrj** [vernemq/vernemq#1831]
See #1778 and comments on there.

Expected behaviour: the same configuration uses the same metadata plugin between 1.11 and 1.12.

Actual behaviour: unless plumtree is explicitly configured as the metadata plugin under 1.11, it is changed to SWC under 1.12.

**Comment by ioolkos** [comment]
@mitchellrj thanks, I'm a bit unlucky with release 1.12.0 it seems...

---
https://github.com/sponsors/vernemq
