### ISSUE TITLE
VernMQ responds with 5102 (Internal HTTP Mapping error) for 60% of packet 

### ISSUE THREAD

**Issue by tm-mkarya** [vernemq/vernemq#1833]
### To help us save time and help you faster

we have VernMQ deployment in Kubernetes. it has been working alright. however, for the last 45 hours, we see that this report 60% packet with 5102  error. what does mean by this error and how to fix this? we have not changed anything in deployment. it started automatically.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: 1.9.2
- OS:
   Linux dfprod-dmz-westus-dmz-master0 5.3.0-1035-azure #36-Ubuntu SMP Thu Aug 6 09:21:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
       eveldb.maximum_memory.percent=20
erlang.distribution.port_range.minimum=9100
listener.ssl.default=0.0.0.0:8883
log.console.level=info
persistent_client_expiration=3d
listener.ssl.keyfile=/etc/ssl/tls.key
listener.ssl.require_certificate=off
allow_subscribe_during_netsplit=on
listener.ssl.certfile=/etc/ssl/tls.crt
allow_publish_during_netsplit=on
erlang.distribution.port_range.maximum=9109
listener.ssl.tls_version=tlsv1.2
listener.vmq.clustering=0.0.0.0:44053
listener.ssl.cafile=/etc/ssl/tls.crt
allow_unsubscribe_during_netsplit=on
listener.ssl.depth=5
log.console=console
allow_register_during_netsplit=on
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.2.184.3:1883
listener.ws.default = 10.2.184.3:8080
listener.vmq.clustering = 10.2.184.3:44053
listener.http.metrics = 10.2.184.3:8888

- Cluster size/standalone:
      5

### Expected behaviour

- Please describe the expected behaviour.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

**Comment by ioolkos** [comment]
@tm-mkarya please post an error log example

**Comment by tm-mkarya** [comment]
below log is from subscriber 


ient apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received SUBACK
Subscribed (mid: 1): 0
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (111 bytes))
{"response_body":"","response_code":200,"timestamp":"2021-06-23 05:21:19","transaction_id":"54a528b8-f3c1a6e7"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (139 bytes))
{"response_body":"Internal HTTP Mapping Error","response_code":5102,"timestamp":"2021-06-23 05:21:34","transaction_id":"3ff613fa-fa5c5177"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (139 bytes))
{"response_body":"Internal HTTP Mapping Error","response_code":5102,"timestamp":"2021-06-23 05:21:50","transaction_id":"34c2d65d-d647f7cb"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub sending PINGREQ
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PINGRESP
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (111 bytes))
{"response_body":"","response_code":200,"timestamp":"2021-06-23 05:22:06","transaction_id":"57b639a1-b54eddbd"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (111 bytes))
{"response_body":"","response_code":200,"timestamp":"2021-06-23 05:22:22","transaction_id":"b9256882-43e17218"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (111 bytes))
{"response_body":"","response_code":200,"timestamp":"2021-06-23 05:22:38","transaction_id":"29132ee4-bb452f76"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (139 bytes))
{"response_body":"Internal HTTP Mapping Error","response_code":5102,"timestamp":"2021-06-23 05:22:54","transaction_id":"c4f11a29-4c35c48f"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub sending PINGREQ
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PINGRESP
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (111 bytes))
{"response_body":"","response_code":200,"timestamp":"2021-06-23 05:23:10","transaction_id":"929f5ad5-4cf669c9"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (139 bytes))
{"response_body":"Internal HTTP Mapping Error","response_code":5102,"timestamp":"2021-06-23 05:23:26","transaction_id":"31c83ada-31ea9c24"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (139 bytes))
{"response_body":"Internal HTTP Mapping Error","response_code":5102,"timestamp":"2021-06-23 05:23:41","transaction_id":"88e4db8f-acde3bbf"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub sending PINGREQ
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PINGRESP
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PUBLISH (d0, q0, r0, m0, 'v1/messages/truedev/trueicemachine~dev/responses/telemetry/ricktest', ... (111 bytes))
{"response_body":"","response_code":200,"timestamp":"2021-06-23 05:23:58","transaction_id":"57136285-b7483f78"}
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub sending PINGREQ
Client apiKey:dfb514a0-cd4b-11eb-9142-45b06f828ada:sub received PINGRESP

**Comment by tm-mkarya** [comment]
here is log from vernemq cluster 

5:27:15.958 [warning] can't authenticate client {[],<<"bearer=undefined">>} from 10.2.48.0:49918 due to invalid_credentials
05:27:16.123 [info] |INFO|N|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:53d42ce1-89d8b321] ** REGISTER IN ** clean_session:true
05:27:16.125 [info] |ERROR|Y|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:13275329-1f1fc48f] ** REGISTER OUT ** :: Not Authorized. Authentication Method: N/A. Transaction Payload: {"response_body":"Malformed Cliend Id","response_code":3101,"timestamp":"2021-06-23 05:27:16","transaction_id":"13275329-1f1fc48f"}
05:27:16.125 [warning] can't authenticate client {[],<<"bearer=undefined">>} from 10.2.232.0:49832 due to invalid_credentials
05:27:16.279 [info] |INFO|N|NULL|apikey=ba9xxxxxxxxxx:682X50541050009|NULL|NULL|NULL|MQTT-Broker| [client_id:apikey=ba9xxxxxxxxxx:682X50541050009][type:Uninitialized][topic:v1/messages/g2e/tank-monitor~prod/_adapter/runm/7ca481839c869/0c9a710d14b6/e82980ad75c3fab/messages/682X50541050009][tr_id:2e817636-a918182b] ** PUBLISH IN ** Publish Info: {"mountpoint":"","payload":"{\"ts\":\"2021-06-23T05:27:13Z\",\"d\":{\"TANK_TEMPERATURE\":263}}","qos":0.0,"retain":false}
05:27:16.282 [info] |INFO|N|NULL|apikey=ba9xxxxxxxxxx:682X50541050009|NULL|NULL|NULL|MQTT-Broker| [client_id:apikey=ba9xxxxxxxxxx:682X50541050009][type:publish][topic:v1/messages/g2e/tank-monitor~prod/_adapter/runm/7ca481839c869/0c9a710d14b6/e82980ad75c3fab/messages/682X50541050009][tr_id:4c7718fb-d3e8267f] ** ACL STATUS CHECK ** Operation Type: 'publish', Auth Method: 'apikey' ACL = {"allow":true,"require_auth":false}
05:27:16.282 [info] |INFO|N|NULL|apikey=ba9xxxxxxxxxx:682X50541050009|NULL|NULL|NULL|MQTT-Broker| [client_id:apikey=ba9xxxxxxxxxx:682X50541050009][type:publish][topic:v1/messages/g2e/tank-monitor~prod/_adapter/runm/7ca481839c869/0c9a710d14b6/e82980ad75c3fab/messages/682X50541050009][tr_id:4c7718fb-d3e8267f] ** AUTHENTICATION DECISION ** Approved For Publish
05:27:16.283 [info] |INFO|N|NULL|apikey=ba9xxxxxxxxxx:682X50541050009|NULL|NULL|NULL|MQTT-Broker| [client_id:apikey=ba9xxxxxxxxxx:682X50541050009][type:publish][topic:v1/messages/g2e/tank-monitor~prod/_adapter/runm/7ca481839c869/0c9a710d14b6/e82980ad75c3fab/messages/682X50541050009][tr_id:4c7718fb-d3e8267f] ** FORWARD HTTP REQUEST ** {"body":"{\"ts\":\"2021-06-23T05:27:13Z\",\"d\":{\"TANK_TEMPERATURE\":263}}","pool_id":"http_tst_client","url":"https://runm.dataflow.iot.att.com/7ca481839c869/0c9a710d14b6/e82980ad75c3fab/in/flow/_adapter/messages"}
05:27:16.838 [info] |INFO|N|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:bd1deb37-a9b7bb58] ** REGISTER IN ** clean_session:true
05:27:16.839 [info] |ERROR|Y|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:54b96bfa-f825ca91] ** REGISTER OUT ** :: Not Authorized. Authentication Method: N/A. Transaction Payload: {"response_body":"Malformed Cliend Id","response_code":3101,"timestamp":"2021-06-23 05:27:16","transaction_id":"54b96bfa-f825ca91"}
05:27:16.840 [warning] can't authenticate client {[],<<"bearer=undefined">>} from 10.2.48.0:49954 due to invalid_credentials
05:27:17.054 [info] |INFO|N|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:54f2c5b6-8d5be341] ** REGISTER IN ** clean_session:true
05:27:17.056 [info] |ERROR|Y|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:21577a3a-714e651c] ** REGISTER OUT ** :: Not Authorized. Authentication Method: N/A. Transaction Payload: {"response_body":"Malformed Cliend Id","response_code":3101,"timestamp":"2021-06-23 05:27:17","transaction_id":"21577a3a-714e651c"}
05:27:17.056 [warning] can't authenticate client {[],<<"bearer=undefined">>} from 10.2.160.0:58658 due to invalid_credentials
05:27:17.414 [info] |INFO|N|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:2a1544d9-b95ac7c5] ** REGISTER IN ** clean_session:true
05:27:17.415 [info] |ERROR|Y|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:b67f6657-dfe6ebdb] ** REGISTER OUT ** :: Not Authorized. Authentication Method: N/A. Transaction Payload: {"response_body":"Malformed Cliend Id","response_code":3101,"timestamp":"2021-06-23 05:27:17","transaction_id":"b67f6657-dfe6ebdb"}
05:27:17.415 [warning] can't authenticate client {[],<<"bearer=undefined">>} from 10.2.232.0:49874 due to invalid_credentials
05:27:17.483 [info] |INFO|N|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:c363e51e-7b9c927f] ** REGISTER IN ** clean_session:true
05:27:17.484 [info] |ERROR|Y|NULL|bearer=undxxxxxxxxxx|NULL|NULL|NULL|MQTT-Broker| [client_id:bearer=undxxxxxxxxxx][type:Uninitialized][topic:Uninitialized][tr_id:bd519644-8ff5dd47] ** REGISTER OUT ** :: Not Authorized. Authentication Method: N/A. Transaction Payload: {"response_body":"Malformed Cliend Id","response_code":3101,"timestamp":"2021-06-23 05:27:17","transaction_id":"bd519644-8ff5dd47"}
05:27:17.485 [warning] can't authenticate client {[],<<"bearer=undefined">>} from 10.2.40.0:56578 due to invalid_credentials

**Comment by ioolkos** [comment]
@tm-mkarya looks like an issue in a plugin of yours.

---
Please support the VerneMQ project: https://github.com/sponsors/vernemq

**Comment by tm-mkarya** [comment]
which plugin and do you have any guidelines to check.

**Comment by ioolkos** [comment]
@tm-mkarya 
> plugin of yours

You log INFO and ERRORs into the Verne [info] level. Even if those are in the VerneMQ console log, they are coming from your Plugin not Verne.

---
Please support the VerneMQ project: https://github.com/sponsors/vernemq
