### ISSUE TITLE
Could not connect to postgresql due to invalid_authorization_specification

### ISSUE THREAD

**Issue by phlegx** [vernemq/vernemq#1834]
Hi there!

For some reasons I get the following error (actually warning) from VerneMQ when I try to activate Postgres auth:

`[warning] Could not connect to Postgresql due to invalid_authorization_specification`

Here is my relevant configuration for Postgres:

```
plugins.vmq_diversity=on
plugins.vmq_passwd=off
plugins.vmq_acl=off
vmq_diversity.auth_postgres.enabled=on
vmq_diversity.postgres.password_hash_method=bcrypt
vmq_diversity.postgres.database=postgres
vmq_diversity.postgres.host=core-postgres-cluster.core-databases.svc.cluster.local
vmq_diversity.postgres.port=5432
vmq_diversity.postgres.password=xxxxxxxxxxxxx
vmq_diversity.postgres.user=postgres
vmq_diversity.postgres.ssl=off

```

Username and password are correct, and other clients can with the same credentials connect to the database just fine.

Any ideas what might could cause that?

### Environment

- VerneMQ Version: 1.12.0
- OS: debian buster
- Erlang/OTP version (if building from source): 23
- Cluster size/standalone: standalone

**Comment by ioolkos** [comment]
@phlegx doesn't ring a bell to me. A Postgres error, obviously. Do you need to grant that user more rights in Postgres?

---
Thank you for supporting the VerneMQ project: https://github.com/sponsors/vernemq

**Comment by phlegx** [comment]
Hi @ioolkos!

Thanks for the input!

Actually I use the Zalando Postgres Operator in my Kubernetes cluster. The user I try to connect with VerneMQ has the following "roles" in the Postgres 13.x instance:

```
        postgres = [
          "superuser",
          "createdb",
        ]
```

So as the Postgres user is superuser I think it should be fine. Or do we need additional rights in this case @ioolkos?

I also tried to start Postgres as a simple single docker container in my cluster, With that I can connect just fine. At least there are no errors/warnings anymore.

Currently checking how to enable more verbose Logging in the Zalando Postgres (Operator)

**Comment by phlegx** [comment]
The postgres logs said the following:

```
2021-06-28 19:39:18.737 UTC,"postgres","postgres",5181,"10.42.0.5:57929",60da2566.143d,2,"authentication",2021-06-28 19:39:18 UTC,10/425,0,FATAL,28000,"pg_hba.conf rejects connection for host ""10.42.0.5"", user ""postgres"", database ""postgres"", SSL off",,,,,,,,,"","client backend"
```
I found some more insight about this error here:

https://help.heroku.com/DR0TTWWD/seeing-fatal-no-pg_hba-conf-entry-errors-in-postgres

I tried to set `DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__SSL` to `on` and that solved the issue.
