### ISSUE TITLE
Doubt - Automatic reload ca certificates

### ISSUE THREAD

**Issue by mprevide** [vernemq/vernemq#1841]
### Environment

- VerneMQ Version: 1.10.0
- OS: alpine
- Erlang/OTP version (if building from source): 21.3
- VerneMQ configuration (vernemq.conf) or the changes from the default
````
metadata_plugin = vmq_swc
plugins.vmq_passwd = off
plugins.vmq_acl = off
leveldb.maximum_memory.percent = 20
log.console = console
listener.max_connections = 200000
listener.nr_of_acceptors = 100
max_inflight_messages = 20
max_online_messages = 10000
listener.ssl.default = 0.0.0.0:8883
listener.ssl.default.cafile =  /vernemq/cert/cabundle.crt
listener.ssl.default.certfile = /vernemq/cert/iotagent-mqtt.crt
listener.ssl.default.keyfile = /vernemq/cert/iotagent-mqtt.key
listener.ssl.default.crlfile =  /vernemq/cert/ca.crl
listener.ssl.default.use_identity_as_username = on
listener.ssl.default.require_certificate = on
````

- Cluster size/standalone: 1 

### Expected behavior
- When the file pointed to in ``listener.ssl.default.cafile`` is changed, this should be reflected in  vernemq.
This file is on a docker/k8s volume and I change it when a new ca is accepted, add it to the chain, as a ca bundle, without restarting vernemq.

Note: When I updated the crl this works fine... 

### Actual behaviour

The expected behavior only works when I restart the vernemq pod/container.

**Comment by ioolkos** [comment]
@mprevide Thanks, your assessment is correct. I'm not going to look into this but open to suggestions/PR's.

---
Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq

**Comment by mprevide** [comment]
> @mprevide Thanks, your assessment is correct. I'm not going to look into this but open to suggestions/PR's.
> 
> Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq

Thank you very much!

**Comment by mprevide** [comment]
Do you have any tips for implementing this? Thanks
@ioolkos
