### ISSUE TITLE
question: how to build correctly from source for further installation on system

### ISSUE THREAD

**Issue by bitgorbovsky** [vernemq/vernemq#1843]
### Environment

- VerneMQ Version: 1.12.1
- OS: Ubuntu
- Erlang/OTP version (if building from source): 22
- Cluster size/standalone: standalone

### Question

Hello! I want to figure out, how to build vernemq from sources and then install it to system by copying files to standard directories. I've examined scripts and found that they point to directory where build was performed. For example, I built broker in my home directory and all scripts (like vernemq, vmq-admin) after building point to my home directory. Should I fix them manually? I mean, variables like RUNNNER_DIR and etc..

Also I found, that I can run `make devdeb`. Is it solution?

Looking forward for your answers :)

**Comment by ioolkos** [comment]
@bitgorbovsky thanks, the `make` command builds a standard Erlang release. The idea of `make dev` is that you can build a couple of Verne nodes on a developer machine to have multiple nodes to cluster.
`make dev0 dev1` will build 2 releases with different ports pre-configured so that you can start the nodes on the same machine.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq

**Comment by bitgorbovsky** [comment]
@ioolkos Thanks for answer!

> make dev0 dev1 

It's awesome! :)


But I still don't understand, how to install erlang release built by `make rel` with correctly configured paths.. 
For example, when I get erlang release, I cannot copy it to standard linux directories, I have doubts because I see the following:

```
➜  vernemq git:(master) ✗ cat _build/default/rel/vernemq/lib/env.sh | grep CUTTLEFISH
CUTTLEFISH_SCHEMA_DIR=./share/schema
CUTTLEFISH="/Users/developer/Work/Experiments/vernemq/_build/default/lib/cuttlefish"
...
```

As you can see, CUTTLEFISH variable points to my home directory. Are there any parameters to configure paths? Or, may be, command `make install` would be perfrect :)

**Comment by ioolkos** [comment]
@bitgorbovsky Note that the creation of packages, the systemd integration, .deb/.rpm, that's what we offer as the packaged binaries, usable against a subscription. (see EULA).

In other words, that would be the part you have to replace with your own work, going from that Erlang release in the `_build` dir to a full `.deb` package (or similar)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq

**Comment by bitgorbovsky** [comment]
I got it. No questions anymore, many thanks! :)
