### ISSUE TITLE
Question on multitenancy or private topics? 

### ISSUE THREAD

**Issue by JacoFourie** [vernemq/vernemq#1845]
Hi all. 

I am sorry if this is not the correct place to ask the question. 
I am looking for a MQTT broker where different clients can not see each others topics.

So lets say I have client A connecting from 2 different devices, then client B should not see any of client A's topics being sent between the devices of client A. Lets say we use something like an API Key.
I see you have ACLs but can that be updated dynamically at runtime?  We will have 1000s of clients at some point so we can not stop and start the services. Is there an API to update the ACL at runtime or how will that work?

Regards.

**Comment by ioolkos** [comment]
@JacoFourie You can have full multi-tenancy using mountpoints (creating fully separated topic trees under different MQTT listeners). This can be used for different customers of an MQTT platform to ensure separation.

This is probably not what you want to do to just separate MQTT clients though (when you say "clients" I suppose you mean MQTT clients not "customers"). The separation there is based on ACLs.
ACLs usually are cached in per-client session on the broker. Therefore a client has to be disconnected to force an ACL reload. I do not know if that's what you mean by restarting "services" (that is, whether a "service" is an MQTT client in your case).

You can also administratively re-authorize clients (knowing their ClientID) in a "live" fashion without disconnecting, using the command line. See `vmq-admin session reauthorize --help`. This re-authorizes the subscriptions but not the publish policies for that Client.

---
:point_right: Thank you for supporting the VerneMQ project: https://github.com/sponsors/vernemq

**Comment by JacoFourie** [comment]
> @JacoFourie You can have full multi-tenancy using mountpoints (creating fully separated topic trees under different MQTT listeners). This can be used for different customers of an MQTT platform to ensure separation.
> 
> This is probably not what you want to do to just separate MQTT clients though (when you say "clients" I suppose you mean MQTT clients not "customers"). The separation there is based on ACLs.
> ACLs usually are cached in per-client session on the broker. Therefore a client has to be disconnected to force an ACL reload. I do not know if that's what you mean by restarting "services" (that is, whether a "service" is an MQTT client in your case).
> 
> You can also administratively re-authorize clients (knowing their ClientID) in a "live" fashion without disconnecting, using the command line. See `vmq-admin session reauthorize --help`. This re-authorizes the subscriptions but not the publish policies for that Client.
> 
> 👉 Thank you for supporting the VerneMQ project: https://github.com/sponsors/vernemq

Hi. Thank you for coming back to me. Let me explain a bit more. I am building a mobile app that will receive some IOT data. The data is sent from a Raspberry Pi. As the mobile app/device can be on the local network where the Pi is or outside the network on a GSM network when not at home I need to create a broker in the cloud that the Pi and mobile device will connect to. 

We will have thousands of customers and these customers should not see each others data. I see in the documentation that you can have the ACLs in the database. So do I understand correctly that if I setup the ACL with a prefix with something like an API key that I generate for each Customer then the customer will only be allowed to publish and subscribe to topics that has his API key in the start of the topics. 

As for the starting of the services what I am trying to say there is we will have a lot of customers. We will create a program that when a client signs up for the service the customer will get a account with an API key. I take it I can insert into the Postgrsql DB the user / password and the ACL for that customer. So then the Pi and the mobile app will use that username / password to connect to the broker. Do I have to restart any of the broker services once I inserted the customer into the DB or does the broker do a lookup in the DB every time we have a connect?

**Comment by ioolkos** [comment]
Yes, you can use a prefix like that for separation in the topics. You still have to fully configure the ACL based on the ClientIDs. (There's no concept of grouping Clients in the ACLs.)
Yes, the broker will lookup the ACLs at CONNECT time.

---
:point_right: Thank you for supporting the VerneMQ project: https://github.com/sponsors/vernemq

**Comment by JacoFourie** [comment]
@ioolkos this sounds great. How would the ACL look for a customer to subscribe and publish only his topics if his API key is 1234567890.

So the topic tree will be /1234567890/#

If this customer connects with any device to the broker with any number of devices. When you say based on ClientIDs does that mean for each device I have to add an entry to the DB with an unique ClientID and ACL?

**Comment by JacoFourie** [comment]
If I have a Customer with an API Key 1234567890 will these values in the DB work so that the Customers can only see its own topics?

mountpoint  = ''
client_id   = '1234567890'
usernamme   = '1234567890'
password    = 'xxxxx'
publish_acl = '[{"pattern":"1234567890/#"}]' 
subscribe_acl = '[{"pattern":"1234567890/#"}]'

I see you have to enable multiple sessions from the same ClientID.

**Comment by JacoFourie** [comment]
I see that Multiple Sessions per ClientId is deprecated. So do I understand correctly that the ACL are per clientID and not per username / password?

**Comment by ioolkos** [comment]
@JacoFourie 
It's a little complicated. Authentication is via username/password. Then authorization checks whether that username is allowed to use the ClientID. I think only MQTT spec v5 states this explicitly:


> In particular, the implementation should check that the Client is authorized to use the Client Identifier as this gives access to the MQTT Session State (described in section 4.1). This authorization check is to protect against the case where one Client, accidentally or maliciously, provides a Client Identifier that is already being used by some other Client. 

But that's the reason that in Verne (at least in the DB based auth plugins) you kind of have a mix of authentication and authorization. You have username/pw, and then the ACLs. The check whether ClientID, Username and PW alignes, is made implicitly.

So, I guess, yes for you matters you could say ACLs are per ClientID.

---
:point_right: Thank you for supporting the VerneMQ project: https://github.com/sponsors/vernemq

**Comment by JacoFourie** [comment]
@ioolkos thank you for the info and help. I got my test system up and running and I have created some records in the DB with the ACLs for pub and sub. Using the API key in the ACL works 100% the way I need it. It is clear that I will have to create a record per connected device with the same ACLs that will work in a group.
