### ISSUE TITLE
Omit / wildcard clientId for automated processes that need to connect to broker

### ISSUE THREAD

**Issue by CD-UNCC** [vernemq/vernemq#1856]
### Environment

- VerneMQ Version: mainflux/vernemq

### Expected behaviour

Simple username/password authentication where clientId can remain randomly generated. 
Right now when a new telegraf pod spins up and connected to the broker, the existing pod is kicked off because username pass word and clientId all match. What is the work around here? predefine all pods clientIds and insert 20 users for all possible pods that spin up?

### Actual behaviour
While is would be great to mix and match auth schemes, like user/pass/clientId logins for users and cert based mtls for machines, we would like to have multple clients logged in under a username/pass with no constraint on clientId which is randomly generated for a number of automated processes.

**Comment by ioolkos** [comment]
@CD-UNCC thanks, note that I don't really have the implicit environment knowledge (which auth plugin? telegraf pods?) to be of effective help on mainflux/vernemq.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
