### ISSUE TITLE
Can't open /lib/env.sh

### ISSUE THREAD

**Issue by lanbai1993** [vernemq/vernemq#1857]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version:1.12.1
- OS: mac os
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behaviour

docker run -p 1883:1883 -p 8888:8888  -e DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on -e DOCKER_VERNEMQ_ACCEPT_EULA=yes  -e "DOCKER_VERNEMQ_USER_<test>='test'"  --name vernemq1 -dit vernemq/vernemq /bin/bash

1.when i use the docker run to set up vernemq. and i use  http://localhost:8888/status to check status.but it cant be opened correctly.  then docker ps to check. it shows Up 6 minutes (unhealthy).
2. i also want set config using vmq-admin,but comes out Can't open /lib/env.sh
vernemq@3a3140c7e8d9:~/bin$ vmq-admin set max_client_id_size=45
/vernemq/bin/vmq-admin: 6: .: Can't open /lib/env.sh
vernemq@3a3140c7e8d9:~/bin$

can someone help me to solve this.

**Comment by ioolkos** [comment]
@lanbai1993 thanks, there's clearly some paths wrong in the latest Docker packages. I'm trying to fix this today.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by schaze** [comment]
Seeing this makes me think what kind of status and support the docker release of vernemq actually has. Do you support running vernemq in the official docker image? If yes how could an image be released that can not even start out of the box? Aren't there any tests? -- I'm not hating -- just worrying about his...

**Comment by ioolkos** [comment]
@schaze I deleted the tags.
I apologise things are not perfect. You can support me working towards that. (see below)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by schaze** [comment]
Hey @ioolkos, no need to apologize - you guys give me free software, I have nothing to complain about. As I wrote I just wanted to know which release of vernemq gets what kind of maturity or support. I cannot give you money and I have no idea about Erlang - but I do know docker very well - anything I can support you with to get it sorted out? PR, debugging, testing,... let me know...

**Comment by Climax777** [comment]
Any progress yet? I cannot run the bionic built ubuntu version on latest ubuntu, since it requires an old libssl. So I tried the docker version, to no avail.

**Comment by ioolkos** [comment]
1.12.1 packages are updated on Docker Hub

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
