### ISSUE TITLE
LWT messages is not delivered

### ISSUE THREAD

**Issue by urbanze** [vernemq/vernemq#1867]
- VerneMQ Version: 1.11.0
- OS: Ubuntu 20.04
- No cluster, single server.
### Expected behaviour

My products use LWT (QoS 2 and Retain 1) to know connection status:

- Online, waiting data (after mqtt connect callback).
- Online (After receive some data).
- Offline (Message in LWT topic) if microcontroller disconnect for some reason.

I've noticed several times that some boards connect to the server (that is, they update the LWT topic with "online, waiting data"), however, after removing the power from these boards, the topic "offline" is **never** published by VerneMQ. I can know this out by connecting MQTT-EXPLORER and seeing topics with retain, the last one being "online, waiting data" even though the **board shutdown for hours**...

### Actual behaviour

Rarely some LWT messages are not published.

I already use "session show" and "vmq-admin trace" (trace have bug that timeout every command after ~60sec) to check something wrong, but all is correct! I need help with this issue. In Slack, have some more messages about my tests and user helping me. (https://vernemq.slack.com/archives/C37FKK9DW/p1628259750019900)

**Comment by ioolkos** [comment]
@urbanze I see. Could you please test this against `master` branch?
I suspect that it's not LWT but the Retain cache here. (and the last retain server fix would adress that).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.

**Comment by urbanze** [comment]
@ioolkos I compiled the master branch and it is already running on the server. I'll continue analyzing the retain data in LWT and if it appears again, I'll come back here.

**Comment by ioolkos** [comment]
@urbanze any additional observations so far?

**Comment by urbanze** [comment]
@ioolkos All these days of testing, I hadn't noticed any wrong behavior, however, yesterday while doing some tests on the board, I noticed something!

When my board publishes a message, it is sent to an internal queue that processes and sends as soon as possible. There was a time when the board got 3 messages in the queue, which includes 2 with retains.

When a message is posted, the board returns the published message ID, so I know the shipping order. The order of publication was:

1. "Online, waiting data" (retain, qos1).
2. "Online" (retain, qos1).
3. (data packet from sensors).

However, the network was slightly unstable at the time and ended up taking a few seconds for messages to be published, however, they were exactly in this order as there is a publication callback with ID.

When looking in mqtt-explorer, I noticed that the last status package was "Online, waiting data", that is, the "Online" package disappeared OR was processed before by verneMQ, so the "waiting" was overwritten. But I can't say that, I just say that my board sent in the correct order, I believe the verne should process in the same order! Any idea?

**Comment by ioolkos** [comment]
@ioolkos okay, the question then remains whether it can be network related (I think it can, due to message redelivery for QoS 1), or whether the issue for the retain server still shows (maybe in a mitigated form).

Thanks for testing, in any case

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
