### ISSUE TITLE
about shared subscription for all client reconnected

### ISSUE THREAD

**Issue by lizhe19** [vernemq/vernemq#1869]
When a messages is being delivered to subscribers of a shared subscription, the message will be delivered to an online subscriber if possible, otherwise the message will be delivered to an offline subscriber.

my question is: 
when clients all offline,  why vernemq still send the msg to the offline clients ?  why not just store them? because when some clients can not online still, it means current lost some msg acturally. i think the correct method is just store that msg when all clients offline, and will send all msg when the part of clients online.

**Comment by ioolkos** [comment]
@lizhe19 thanks. Note that offline messages *are* Verne's way to store messages.

But you're right, this in part non-intuitive, especially if the expectation is around realtime delivery of messages. 
Anyway, read the spec and the "Notes on Shared Subscriptions" here: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901250
And the spec is ever only written for full consistency, with a single node. Tell me it's clear and easy :)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
