### ISSUE TITLE
[Question] When using share subscription, what's the behavior if one of the clients die?

### ISSUE THREAD

**Issue by sesky4** [vernemq/vernemq#1875]
When two clients A and B sub to the same share subscription, if A suddenly gone, will broker continues to deliver rest messages into A's queue or alive B?

**Comment by sesky4** [comment]
MQTT standard seems doesn't define the behaviour in this situation.

**Comment by sesky4** [comment]
shared_subscription_policy=prefer_local

**Comment by ioolkos** [comment]
@sesky4 if A and B are online and then B goes offline, then messages will be delivered to A only. At least this is what should happen from the perspective on that single node.
There are situations/combinations where offline consumers still collect messages, though. 

You probably have a specific setup. Shared behaviour is then easily testable.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
