### ISSUE TITLE
VerneMQ running in Openshift is crashing on a simple pub/sub test

### ISSUE THREAD

**Issue by tomaszwolek** [vernemq/vernemq#1882]
### Environment

- VerneMQ Version: 1.11.0
- OS: OpenShift 4.6
- Erlang/OTP version (if building from source): Erlang/OTP 23 [erts-11.2.2.6]
- VerneMQ configuration (vernemq.conf) or the changes from the default: 
listener.ssl.certfile=/etc/tls/cert.pem
vmq_diversity.auth_postgres.enabled=on
vmq_diversity.postgres.user=vernemq
vmq_diversity.postgres.port=5432
listener.ssl.cafile=/etc/tls/cacerts.pem
plugins.vmq_acl=off
listener.ssl.keyfile=/etc/tls/key.pem
vmq_diversity.postgres.database=vernemq_db
plugins.vmq_passwd=off
listener.ws.default=0.0.0.0:8889
vmq_diversity.postgres.password_hash_method=crypt
listener.ssl.default=0.0.0.0:8883
vmq_diversity.postgres.host=psql-vernemq-authdb.svc.cluster.local
plugins.vmq_diversity=on
vmq_diversity.postgres.password=*******
max_inflight_messages=1000
outgoing_clustering_buffer_size=100000000
shared_subscription_policy=random
allow_multiple_sessions=off
erlang.distribution.port_range.minimum=9100
log.console=console
max_online_messages=5000
allow_anonymous=off
metadata_plugin=vmq_swc
erlang.distribution.port_range.maximum=9109
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = X.X.X.X:1883
listener.ws.default = X.X.X.X:8080
listener.vmq.clustering = X.X.X.X:44053
listener.http.metrics = X.X.X.X:8888

- Cluster size/standalone:
3 node cluster running on Openshift/Kubernetes
pod resources:
        limits:
          cpu: 500m
          memory: 1000Mi
        requests:
          cpu: 100m
          memory: 100Mi

### Expected behaviour

Client SBX-QAS-TEST-000-DEV connected to node0 is publishing, Client SBX-QAS-TEST-001-DEV connected to node1 is subscribing
All cluster nodes are running

### Actual behaviour

Cluster node which has the subscriber connected is crashing.

- Please include minimal steps to reproduce the issue, if possible.

mosquitto_pub -h mq-broker-sbx.local.domain -p 443 --cafile cacert.pem --insecure -u sbx-qas-test-000-dev -P password  
-i SBX-QAS-TEST-000-DEV -t DEV/Test/burnout -f payload.json --repeat 1000000

mosquitto_sub -h mq-broker-sbx.local.domain -p 443 --cafile cacert.pem --insecure -u sbx-qas-test-001-dev -P password  -i SBX-QAS-TEST-001-DEV -t DEV/Test/burnout

Crash.log
2021-09-16 16:07:07 =ERROR REPORT====
** Generic server vmq_swc_store_meta2 terminating 
** Last message in was {batch,[{{<0.1120.0>,#Ref<0.2689859124.3208904705.124921>},{write,[{{{vmq,subscriber},{[],<<"SBX-QAS-TEST-001-DEV">>}},{{1631,808427,992671},[{'VerneMQ@vernemq-1.vernemq.svc.cluster.local',true,[]}]},#{'VerneMQ@vernemq-0.vernemq.svc.cluster.local' => 12,'VerneMQ@vernemq-1.vernemq.svc.cluster.local' => 8,'VerneMQ@vernemq-2.vernemq.svc.cluster.local' => 3}}]}}]}
** When Server state == {state,'VerneMQ@vernemq-1.vernemq.svc.cluster.local',undefined,meta2,{swc_config,'VerneMQ@vernemq-1.vernemq.svc.cluster.local',meta2,vmq_swc_db_meta2,vmq_swc_db_leveldb,vmq_swc_store_meta2,vmq_swc_store_r_o_w_meta2,vmq_swc_store_batcher_meta2,vmq_swc_group_membership_meta2,vmq_swc_edist_srv},{dkm,#Ref<0.2689859124.3209035777.117774>,#Ref<0.2689859124.3209035777.117775>,#Ref<0.2689859124.3209035777.117776>},#{'VerneMQ@vernemq-0.vernemq.svc.cluster.local' => {6,0},'VerneMQ@vernemq-1.vernemq.svc.cluster.local' => {0,128}},{#{'VerneMQ@vernemq-0.vernemq.svc.cluster.local' => #{'VerneMQ@vernemq-0.vernemq.svc.cluster.local' => 12,'VerneMQ@vernemq-1.vernemq.svc.cluster.local' => 12,'VerneMQ@vernemq-2.vernemq.svc.cluster.local' => 12},'VerneMQ@vernemq-1.vernemq.svc.cluster.local' => #{'VerneMQ@vernemq-0.vernemq.svc.cluster.local' => 9,'VerneMQ@vernemq-1.vernemq.svc.cluster.local' => 9,'VerneMQ@vernemq-2.vernemq.svc.cluster.local' => 8},'VerneMQ@vernemq-2.vernemq.svc.cluster.local' => #{'VerneMQ@vernemq-0.vernemq.svc.cluster.local' => 3,'VerneMQ@vernemq-1.vernemq.svc.cluster.local' => 3,'VerneMQ@vernemq-2.vernemq.svc.cluster.local' => 3}},#{}},['VerneMQ@vernemq-0.vernemq.svc.cluster.local','VerneMQ@vernemq-2.vernemq.svc.cluster.local'],undefined,true,true,#{{vmq,retain} => [{<0.397.0>,#Fun<vmq_swc_plugin.2.36768546>}],{vmq,subscriber} => [{<0.410.0>,#Fun<vmq_swc_plugin.2.36768546>},{<0.385.0>,#Fun<vmq_swc_plugin.2.36768546>}]},true}
** Reason for termination ==
** {{case_clause,{ok,{0,128}}},[{swc_node,event,2,[{file,"/vmq_build/vernemq/_build/default/lib/swc/src/swc_node.erl"},{line,186}]},{vmq_swc_store,process_write_op,2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,638}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,'-handle_call/3-fun-1-',2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,268}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,handle_call,3,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]}]}
** Client vmq_swc_store_batcher_meta2 stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,242}]},{vmq_swc_store_batcher,loop_accumulating,4,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store_batcher.erl"},{line,50}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]
2021-09-16 16:07:07 =CRASH REPORT====
  crasher:
    initial call: vmq_swc_store:init/1
    pid: <0.231.0>
    registered_name: vmq_swc_store_meta2
    exception error: {{case_clause,{ok,{0,128}}},[{swc_node,event,2,[{file,"/vmq_build/vernemq/_build/default/lib/swc/src/swc_node.erl"},{line,186}]},{vmq_swc_store,process_write_op,2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,638}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,'-handle_call/3-fun-1-',2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,268}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,handle_call,3,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]}]}
    ancestors: [vmq_swc_store_sup_meta2,vmq_swc_sup,<0.209.0>]
    message_queue_len: 0
    messages: []
    links: [<0.225.0>]
    dictionary: [{rand_seed,{#{bits => 58,jump => #Fun<rand.3.47293030>,next => #Fun<rand.0.47293030>,type => exsss,uniform => #Fun<rand.1.47293030>,uniform_n => #Fun<rand.2.47293030>},[126805440300206779|245895020108951813]}}]
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 28
    reductions: 15360
  neighbours:
2021-09-16 16:07:07 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_swc_store_sup_meta2}
     Context:    child_terminated
     Reason:     {{case_clause,{ok,{0,128}}},[{swc_node,event,2,[{file,"/vmq_build/vernemq/_build/default/lib/swc/src/swc_node.erl"},{line,186}]},{vmq_swc_store,process_write_op,2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,638}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,'-handle_call/3-fun-1-',2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,268}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,handle_call,3,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]}]}
     Offender:   [{pid,<0.231.0>},{id,{vmq_swc_store,meta2}},{mfargs,{vmq_swc_store,start_link,[{swc_config,'VerneMQ@vernemq-1.vernemq.svc.cluster.local',meta2,vmq_swc_db_meta2,vmq_swc_db_leveldb,vmq_swc_store_meta2,vmq_swc_store_r_o_w_meta2,vmq_swc_store_batcher_meta2,vmq_swc_group_membership_meta2,vmq_swc_edist_srv}]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-09-16 16:07:07 =CRASH REPORT====
  crasher:
    initial call: vmq_swc_store_batcher:init/1
    pid: <0.230.0>
    registered_name: vmq_swc_store_batcher_meta2
    exception exit: {{{{case_clause,{ok,{0,128}}},[{swc_node,event,2,[{file,"/vmq_build/vernemq/_build/default/lib/swc/src/swc_node.erl"},{line,186}]},{vmq_swc_store,process_write_op,2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,638}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,'-handle_call/3-fun-1-',2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,268}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,handle_call,3,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]}]},{gen_server,call,[vmq_swc_store_meta2,{batch,[{{<0.1120.0>,#Ref<0.2689859124.3208904705.124921>},{write,[{{{vmq,subscriber},{[],<<"SBX-QAS-TEST-001-DEV">>}},{{1631,808427,992671},[{'VerneMQ@vernemq-1.vernemq.svc.cluster.local',true,[]}]},#{'VerneMQ@vernemq-0.vernemq.svc.cluster.local' => 12,'VerneMQ@vernemq-1.vernemq..svc.cluster.local' => 8,'VerneMQ@vernemq-2.vernemq.svc.cluster.local' => 3}}]}}]},infinity]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,246}]},{vmq_swc_store_batcher,loop_accumulating,4,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store_batcher.erl"},{line,50}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [vmq_swc_store_sup_meta2,vmq_swc_sup,<0.209.0>]
    message_queue_len: 0
    messages: []
    links: [<0.225.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 28
    reductions: 302
  neighbours:
2021-09-16 16:07:07 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_swc_store_sup_meta2}
     Context:    child_terminated
     Reason:     {{{case_clause,{ok,{0,128}}},[{swc_node,event,2,[{file,"/vmq_build/vernemq/_build/default/lib/swc/src/swc_node.erl"},{line,186}]},{vmq_swc_store,process_write_op,2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,638}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,'-handle_call/3-fun-1-',2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,268}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,handle_call,3,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,266}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,715}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,744}]}]},{gen_server,call,[vmq_swc_store_meta2,{batch,[{{<0.1120.0>,#Ref<0.2689859124.3208904705.124921>},{write,[{{{vmq,subscriber},{[],<<"SBX-QAS-TEST-001-DEV">>}},{{1631,808427,992671},[{'VerneMQ@vernemq-1.vernemq.svc.cluster.local',true,[]}]},#{'VerneMQ@vernemq-0.vernemq.svc.cluster.local' => 12,'VerneMQ@vernemq-1.vernemq.svc.cluster.local' => 8,'VerneMQ@vernemq-2.vernemq.svc.cluster.local' => 3}}]}}]},infinity]}}
     Offender:   [{pid,<0.230.0>},{id,{vmq_swc_store_batcher,meta2}},{mfargs,{vmq_swc_store_batcher,start_link,[{swc_config,'VerneMQ@vernemq-1.vernemq.diiot-sbx.svc.cluster.local',meta2,vmq_swc_db_meta2,vmq_swc_db_leveldb,vmq_swc_store_meta2,vmq_swc_store_r_o_w_meta2,vmq_swc_store_batcher_meta2,vmq_swc_group_membership_meta2,vmq_swc_edist_srv}]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

Error.log
2021-09-16 16:07:07.993 [error] <0.231.0>@swc_node:event:186 gen_server vmq_swc_store_meta2 terminated with reason: no case clause matching {ok,{0,128}} in swc_node:event/2 line 186
2021-09-16 16:07:07.993 [error] <0.231.0>@swc_node:event:186 CRASH REPORT Process vmq_swc_store_meta2 with 0 neighbours crashed with reason: no case clause matching {ok,{0,128}} in swc_node:event/2 line 186
2021-09-16 16:07:07.994 [error] <0.225.0>@swc_node:event:186 Supervisor vmq_swc_store_sup_meta2 had child {vmq_swc_store,meta2} started with vmq_swc_store:start_link({swc_config,'VerneMQ@vernemq-1.vernemq.svc.cluster.local',meta2,vmq_swc_db_meta2,vmq_swc_db_leveldb,...}) at <0.231.0> exit with reason no case clause matching {ok,{0,128}} in swc_node:event/2 line 186 in context child_terminated
2021-09-16 16:07:07.994 [error] <0.230.0> CRASH REPORT Process vmq_swc_store_batcher_meta2 with 0 neighbours exited with reason: {{{case_clause,{ok,{0,128}}},[{swc_node,event,2,[{file,"/vmq_build/vernemq/_build/default/lib/swc/src/swc_node.erl"},{line,186}]},{vmq_swc_store,process_write_op,2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,638}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,'-handle_call/3-fun-1-',2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,268}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,handle_call,3,[{file,"..."},...]},...]},...} in gen_server:call/3 line 246
2021-09-16 16:07:07.997 [error] <0.225.0> Supervisor vmq_swc_store_sup_meta2 had child {vmq_swc_store_batcher,meta2} started with vmq_swc_store_batcher:start_link({swc_config,'VerneMQ@vernemq-1.vernemq.svc.cluster.local',meta2,vmq_swc_db_meta2,vmq_swc_db_leveldb,...}) at <0.230.0> exit with reason {{{case_clause,{ok,{0,128}}},[{swc_node,event,2,[{file,"/vmq_build/vernemq/_build/default/lib/swc/src/swc_node.erl"},{line,186}]},{vmq_swc_store,process_write_op,2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,638}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,'-handle_call/3-fun-1-',2,[{file,"/vmq_build/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,268}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{vmq_swc_store,handle_call,3,[{file,"..."},...]},...]},...} in context child_terminated

**Comment by ioolkos** [comment]
@tomaszwolek I can take a closer look at the logs if needed, but this looks like a mess up in cluster state, likely due to either restarts with empty state, or leave/join cycles taking up existing state.

Does this happen after Pod rescheduling or restarts of cluster nodes? Can you run the same scenario with 1.12.3 as a comparison?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tomaszwolek** [comment]
I've started a clean cluster of 1.12.3
It looks the same. The cluster node which has subscriber connected crash, restarts, and then after restart it goes in CrashLoop:

12:58:02.302 [info] Opening LevelDB SWC database at "./data/swc_meta/meta1"
Loaded NodeClock fromDisk #{}
12:58:02.404 [info] Opening LevelDB SWC database at "./data/swc_meta/meta2"
Loaded NodeClock fromDisk #{{'VerneMQ@vernemq-0.vernemq.svc.cluster.local',
                                <<108,112,207,13,182,209,180,134,147,132,73,
                                  50,232,60,193,149,44,91,103,208>>} =>
                                {2,0},
                            {'VerneMQ@vernemq-1.vernemq.svc.cluster.local',
                                <<100,166,180,184,88,51,53,134,67,202,173,
                                  156,94,88,1,45,253,54,203,8>>} =>
                                {9,0}}
12:58:02.484 [info] Opening LevelDB SWC database at "./data/swc_meta/meta3"
Loaded NodeClock fromDisk #{}
12:58:02.541 [info] Opening LevelDB SWC database at "./data/swc_meta/meta4"
Loaded NodeClock fromDisk #{}
12:58:02.619 [info] Opening LevelDB SWC database at "./data/swc_meta/meta5"
Loaded NodeClock fromDisk #{}
12:58:02.697 [info] Opening LevelDB SWC database at "./data/swc_meta/meta6"
Loaded NodeClock fromDisk #{{'VerneMQ@vernemq-1.vernemq.svc.cluster.local',
                                <<100,166,180,184,88,51,53,134,67,202,173,
                                  156,94,88,1,45,253,54,203,8>>} =>
                                {1,0}}
12:58:02.753 [info] Opening LevelDB SWC database at "./data/swc_meta/meta7"
Loaded NodeClock fromDisk #{{'VerneMQ@vernemq-1.vernemq.svc.cluster.local',
                                <<100,166,180,184,88,51,53,134,67,202,173,
                                  156,94,88,1,45,253,54,203,8>>} =>
                                {1,0}}
12:58:02.838 [info] Opening LevelDB SWC database at "./data/swc_meta/meta8"
Loaded NodeClock fromDisk #{}
12:58:03.011 [info] Opening LevelDB SWC database at "./data/swc_meta/meta9"
Loaded NodeClock fromDisk #{{'VerneMQ@vernemq-1.vernemq.svc.cluster.local',
                                <<100,166,180,184,88,51,53,134,67,202,173,
                                  156,94,88,1,45,253,54,203,8>>} =>
                                {1,0}}
12:58:03.064 [info] Opening LevelDB SWC database at "./data/swc_meta/meta10"
Loaded NodeClock fromDisk #{{'VerneMQ@vernemq-0.vernemq.svc.cluster.local',
                                <<108,112,207,13,182,209,180,134,147,132,73,
                                  50,232,60,193,149,44,91,103,208>>} =>
                                {1,0}}
12:58:03.209 [info] Try to start vmq_swc: ok
12:58:03.309 [info] Opening LevelDB database at "./data/msgstore/1"
12:58:03.313 [info] Opening LevelDB database at "./data/msgstore/2"
12:58:03.321 [info] Opening LevelDB database at "./data/msgstore/3"
12:58:03.329 [info] Opening LevelDB database at "./data/msgstore/4"
12:58:03.334 [info] Opening LevelDB database at "./data/msgstore/5"
12:58:03.337 [info] Opening LevelDB database at "./data/msgstore/6"
12:58:03.345 [info] Opening LevelDB database at "./data/msgstore/7"
12:58:03.348 [info] Opening LevelDB database at "./data/msgstore/8"
12:58:03.353 [info] Opening LevelDB database at "./data/msgstore/9"
12:58:03.357 [info] Opening LevelDB database at "./data/msgstore/10"
12:58:03.362 [info] Opening LevelDB database at "./data/msgstore/11"
12:58:03.366 [info] Opening LevelDB database at "./data/msgstore/12"
12:58:03.424 [info] Try to start vmq_generic_msg_store: ok
12:58:03.805 [info] loaded 1 subscriptions into vmq_reg_trie
12:58:03.982 [info] cluster event handler 'vmq_cluster' registered
12:58:03.982 [info] cluster node 'VerneMQ@vernemq-1.vernemq.diiot-sbx.svc.cluster.local' UP
12:58:03.990 [info] cluster node 'VerneMQ@vernemq-2.vernemq.diiot-sbx.svc.cluster.local' UP
12:58:05.005 [info] successfully connected to cluster node 'VerneMQ@vernemq-1.vernemq.svc.cluster.local'
12:58:05.089 [info] successfully connected to cluster node 'VerneMQ@vernemq-2.vernemq.svc.cluster.local'
/usr/sbin/start_vernemq: line 189:    97 Killed                  /vernemq/bin/vernemq console -noshell -noinput $@

**Comment by ioolkos** [comment]
Are you starting with clean state on disk? Don't reuse the state from the cluster you built before. Start clean, then verify step by step, does the cluster build, does the subscriber connect, then start publishing.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tomaszwolek** [comment]
@ioolkos that was a completely fresh cluster, i wasn't reusing the state from previous one (based on 1.11.0)

**Comment by ioolkos** [comment]
Okay, thanks. Ideally, you could narrow it down to some reproducible minimal steps (ie minimal load scenario).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@tomaszwolek one thing I just wondered: you have `--repeat 1000000` in the `mosquitto_pub` command. Do you see the issue with lower numbers? have you tried `--repeat_delay`?

Trying to determine whether this is the input that causes trouble (throwing a million JSON at fastest rate at the broker)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tomaszwolek** [comment]
> @tomaszwolek one thing I just wondered: you have `--repeat 1000000` in the `mosquitto_pub` command. Do you see the issue with lower numbers? have you tried `--repeat_delay`?
> 
> Trying to determine whether this is the input that causes trouble (throwing a million JSON at fastest rate at the broker)

I did a test with 1 second repeat delay and was not able to replicate the issue.

**Comment by ioolkos** [comment]
@tomaszwolek Thanks for testing. I think you can also use fractions of seconds with `--repeat-delay`. 
Anyway, it's still strange that this overload creates the original error posted, as it's related to registration of subscriber.

Do you want me to keep this issue open for your further investigation or do you consider it resolved for you?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tomaszwolek** [comment]
I have a case where i'm not able to throttle the publishing client message rate.
I was able to replicate the issue with mosquitto_pub and opened this thread.
I can perform couple more tests with different repeat delay to find the point where VMQ node crashes, but this information will not help me, as i said i'm not able to do any throttling.

**Comment by ioolkos** [comment]
Throttling a publisher can be implemented in an `auth_on_publish` plugin. (using `throttle` modifier). On a TCP level backpressure will apply between session and publisher. For this reason, I don't immediately see why we end up with the error in the metadata sync layer.


---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
