### ISSUE TITLE
Possible DoS Attack caused by invalid properties

### ISSUE THREAD

**Issue by Just1ceP4rtn3r** [vernemq/vernemq#1883]
### Environment

- VerneMQ Version: 1.12.3
- OS: 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behaviour

In MQTT v5.0 spec, "PUBLISH" pakcet should only contain properties as follow:

3.3.2.3.2 Payload Format Indicator

3.3.2.3.3 Message Expiry Interval`

3.3.2.3.4 Topic Alias

3.3.2.3.5 Response Topic

3.3.2.3.6 Correlation Data

3.3.2.3.7 User Property

3.3.2.3.8 Subscription Identifier

3.3.2.3.9 Content Type

### Actual behaviour

In our tests, VerneMQ violated this rule. VerneMQ support some invalid properties in PUBLISH like:

SessionExpiryInterval
AuthenticationMethod
AuthenticationData
RequestProblemInformation
WillDelayInterval
ServerReference

(1) Publisher send a PUBLISH packet with invalid properties (.e.g. Server Reference="test")

(2) The broker have no check for that and just deliver this message to subscribers with properties that publisher has set.

(3) If the client of subscriber check the validity of properties, its process will throw an exception and then exit. For example:
https://github.com/hivemq/mqtt-cli
paho.mqtt.java
...

So an adversary can publish a malformed PUBLISH packet to let victim loss the connection with broker.

**Comment by ioolkos** [comment]
@Just1ceP4rtn3r thanks, is that from an implicit reading of the V5 spec, or do you refer to a specific section/label? The question is also what the broker should do at this point. Probably disconnect the Publisher.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by Just1ceP4rtn3r** [comment]
V5 spec describes this in a table:
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901027

**Comment by ioolkos** [comment]
@Just1ceP4rtn3r I see, yes, so it'd be a Malformed Packet. Will look into fixing this.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
