### ISSUE TITLE
Clients cannot publish the data when connected. Lots of "session stopped abnormally"

### ISSUE THREAD

**Issue by tomaszwolek** [vernemq/vernemq#1884]
### Environment

- VerneMQ Version: 1.11.0
- OS: Openshift 4.6
- Erlang/OTP version (if building from source): Erlang/OTP 23 [erts-11.2.2.6]
- VerneMQ configuration (vernemq.conf) or the changes from the default
listener.ssl.certfile=/etc/tls/cert.pem
vmq_diversity.auth_postgres.enabled=on
vmq_diversity.postgres.user=vernemq
vmq_diversity.postgres.port=5432
listener.ssl.cafile=/etc/tls/cacerts.pem
plugins.vmq_acl=off
listener.ssl.keyfile=/etc/tls/key.pem
vmq_diversity.postgres.database=vernemq_db
plugins.vmq_passwd=off
listener.ws.default=0.0.0.0:8889
vmq_diversity.postgres.password_hash_method=crypt
listener.ssl.default=0.0.0.0:8883
vmq_diversity.postgres.host=psql-vernemq-authdb.svc.cluster.local
plugins.vmq_diversity=on
vmq_diversity.postgres.password=*******
max_inflight_messages=1000
outgoing_clustering_buffer_size=100000000
shared_subscription_policy=random
allow_multiple_sessions=off
erlang.distribution.port_range.minimum=9100
log.console=console
max_online_messages=5000
allow_anonymous=off
metadata_plugin=vmq_swc
erlang.distribution.port_range.maximum=9109
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = X.X.X.X:1883
listener.ws.default = X.X.X.X:8080
listener.vmq.clustering = X.X.X.X:44053
listener.http.metrics = X.X.X.X:8888

Cluster size/standalone:
3 node cluster running on Openshift/Kubernetes
pod resources:
limits:
cpu: 5000m
memory: 9000Mi
requests:
cpu: 1000m
memory: 5000Mi

### Expected behaviour

MQTT Clients can publish messages 

### Actual behaviour

Clients publish the data successfully until lots of below message appear in the log

[warning] session stopped abnormally due to '{error,{queue_down,<0.X>,normal}}' vernemq-0”

where X = different numbers 

Afterwards clients cannot publish data anymore despite still being connected
Can you please help me to decipher this error message? What is the reason of queue being down?

Can it be somehow related to an ongoing issue with cluster replication performance?
The above warning appeared after a significant amount of warning sequences like the below:

[info] successfully connected to cluster node 'VerneMQ@vernemq-0.svc.cluster.local'
[warning] can't send 114155 bytes to 'VerneMQ@vernemq-0.svc.cluster.local' due to timeout, reconnect!
[info] successfully connected to cluster node 'VerneMQ@vernemq-0.vernemq.svc.cluster.local'
[warning] can't send 843 bytes to 'VerneMQ@vernemq-0.svc.cluster.local' due to timeout, reconnect!

BTW increasing clustering buffer size doesn't help.

**Comment by ioolkos** [comment]
@tomaszwolek what is the load scenario?
And 100m to 500m CPU and 100Mi to 1000Mi is giving extremely low resources to Verne.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tomaszwolek** [comment]
> @tomaszwolek what is the load scenario?

@ioolkos payload usually from 40 to 130k, but there might be messages as big as 200k
the client which was hanging was subscribed to 40-50 topics at the same time, each 1 message per second

> And 100m to 500m CPU and 100Mi to 1000Mi is giving extremely low resources to Verne.
I gave the wrong numbers, edited the requests and limits in the original post

do i understand correctly there is no clear explanation from the warning content what's actually happening?

**Comment by ioolkos** [comment]
The MQTT session terminates, because the queue it connects to is down. I do not know why and it's not something that's frequently seen.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
