### ISSUE TITLE
haproxy-ingress ssl terminate on tcp port

### ISSUE THREAD

**Issue by itleets** [vernemq/vernemq#1888]
### Environment

- VerneMQ Version: vernemq/vernemq:1.12.3
- OS: kubernetes
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
env:
            - name: DOCKER_VERNEMQ_ACCEPT_EULA
              value: "yes"
            - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
              value: "1"
            - name: DOCKER_VERNEMQ_KUBERNETES_APP_LABEL
              value: "vernemq"
            - name: DOCKER_VERNEMQ_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DOCKER_VERNEMQ_KUBERNETES_INSECURE
              value: "1"
            - name: DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS
              value: "3,4,5"
            - name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
              value: "50"
            - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
              value: "on"
            - name: DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS
              value: "20"
            - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
              value: "2000"
            - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
              value: "2000"
            - name: DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS
              value: "20000"
            - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
              value: "on"
            - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
              value: "on"

- Cluster size/standalone: 2

### Expected behavior

- I have deployed vernemq with 2 pods on kubernetes and its working fine with direct loadbalancer without ssl now i want to add ssl and terminate it outside of vernemq I'm trying to use haproxy-ingress but can't find way for it can you please kindly give me haproxy-ingress yaml code which can accept connection on ssl and terminate it and then pass that to vernemq wihtout 

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

**Comment by itboy87** [comment]
@ioolkos @itleets 
i did it.

check here https://stackoverflow.com/questions/69488472/vernemq-port-1883-with-haproxy-ingress-and-also-ssl-termination/69508953#69508953

@ioolkos can you please check that my answer and also update it in documentation or tell me I will send a pull request. Thanks
