### ISSUE TITLE
about disconnect client

### ISSUE THREAD

**Issue by lizhe19** [vernemq/vernemq#1895]
Send a topic that does not exist, that is, the topic is in publish_acl does not exist. Why is the client disconnected?

**Comment by ioolkos** [comment]
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/mqtt-v3.1.1.html

Search for Normative Statement Number: `[MQTT-3.3.5-2]`

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
