### ISSUE TITLE
While client authentication is enabled, offline messages getting lost ? 

### ISSUE THREAD

**Issue by DeepaliLad** [vernemq/vernemq#1899]
### Environment

- VerneMQ Version: 1.2
- OS: Linux
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default

- allow_anonymous = off
- allow_multiple_sessions = on
- max_inflight_messages = 2000
- max_online_messages = 2000
- max_offline_messages = 2000
- listener.ssl.tls_version = tlsv1.2
- vmq_diversity.auth_postgres.enabled = on
- vmq_diversity.postgres.host = Ip address
- vmq_diversity.postgres.port = 5432
- vmq_diversity.postgres.user = user1
- vmq_diversity.postgres.password = pass@123
- vmq_diversity.postgres.database = db
- vmq_diversity.cockroachdb.password_hash_method = crypt
- Cluster size/standalone: standalone

### Expected behaviour
- While doing client authentication using db, offline messages getting lost.
- As subscriber OFF and publisher sends data to broker then data should be stored on vernemq broker queue.
-  but these offline messages getting lost.
- As we start subscriber, messages not received.

### Actual behaviour

- Subscriber ON and publisher send data to vernemq broker then data received at subscriber end.
- But as Subscriber stop (OFF, due to some reasons (connection lost)) and publisher sends data to broker then offline messages
lost.
- As we start subscriber after some time then these offline messages are not received. 
- So while doing client authentication above parameters are changed in vernemq config file. But offline messages not stored on broker.

**Comment by DeepaliLad** [comment]
We tried with persistent session =false and Qos =1. As we are able to subscribe online messages, but still we are not able to store offline messages on broker.
For client authentication using db, we configure following parameters,
allow_anonymous = off
allow_multiple_sessions = on
vmq_diversity.auth_postgres.enabled = on
all other parameters are mentioned above.

Is there any way, that we have to use or any parameter we are missing to configure ? We are new in this field.


Thanks in advance !!

**Comment by ioolkos** [comment]
@DeepaliLad 
Unrelated to your question, the `allow_multiple_sessions` feature is deprecated, best to not use that.

Regarding your question: you might miss a small detail. If the publisher uses QoS 0, messages won't be persisted.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
