### ISSUE TITLE
Passing some "session_id" or "peer" argument to all session's lifecycle hooks

### ISSUE THREAD

**Issue by manifest** [vernemq/vernemq#190]
I'm trying to implement a plugin limiting the amount of client's connections.
I might have accomplish that by:
- (In the `auth_on_register` hook): incrementing connections' counter and checking if its value isn't exceeding a limit (must be an atomic operation).
- (In the `on_client_offline` and `on_client_gone` hooks): decrementing the counter.

But there is a problem. While `on_client_wakeup`, `on_client_offline`, `on_client_gone` share the same process, auth_on_register is executed in another one. So that, I can't relate on hook's process **pid** as a per-peer session's key (id). I can't also check the limit in the `on_client_wakeup`, and increment the counter in the `auth_on_register` because the operation must be atomic. And I can't relate on **client_id** hooks' argument when **allow_multiple_sessions** option is enabled.

Is there a way I can solve the problem with the current implementation of hooks?

**Comment by manifest** [comment]
Relates to [that](https://github.com/erlio/vernemq/issues/182) issue.

**Comment by larshesel** [comment]
Unfortunately I was in error when I claimed that you could use the pid as an identifier as we call the hooks both from the queue and from the session processes contexts. So they can't be used in this situation.

Maybe I'm missing something, but for his case it seems to me you should be able to use the subscriber id/client_id as a key to your counters and incr/decr the counter in the hooks you mention. Then you can limit the number of client connections for specific clients or if you calculate the counter total you'd be able to limit the number of client connections in total.

Note that there are already existing ways of limiting the number of connections: you can configure the max number of clients connected to VerneMQ in the vernemq.conf file or you can control the max number of connections for specific listeners using the `vmq-admin` tool.

**Comment by manifest** [comment]
I need to count client's connections per **username** because the **username** represents a particular user (user authenticate himself by value represented in this field). While **client_id** represents user's connection. **client_id** can be identical for a particular user (when user need to enable session balancing, **allow_multiple_sessions** is enabled), or can be different (when user needs independent sessions). I would also like to have a **per-peer** (or **per-connection**) state stored in a database.

For these tasks, it looks like **client_id** is just not enough.

**Comment by larshesel** [comment]
Can't you add a relation between the client_id and the username to your stored data in the auth_on_register hook? Then you should be able to achieve what you want indirectly by using the client_id to get to the counter for a username. This I believe should work in both the allow_mutiple_sessions on/off scenarios.

But you're right - using only the client_id isn't enough to achieve this.

**Comment by manifest** [comment]
It's kind of tricky with key-value storages, but may work for counter. And it won't work for **per-peer** (or **per-connection**) state implementation.

**Comment by oakad** [comment]
Bump this issue!

In non-trivial authorization scenarios (such as authorization against a user directory of some sort), auth_on_register almost always has to establish the context which affects subscribe and publish behavior down the line. Manually managing ets entries or calling the network directory on each hook is way less convenient than having a custom user data object associated with each authenticated session.

Besides, the above will absolutely be required for challenge-response auth of MQTT-5 (which will be real handy to have right now :-)).

**Comment by ioolkos** [comment]
OK, I see the need to think about this, thanks @oakad. 
More ideas on how to do the MQTT-5 challenge-response are very welcome! :)

**Comment by larshesel** [comment]
I'm not sure I understand why the challenge-response (AuthMethod) auth of MQTT-5 will need a context to be passed around? The auth data can for the client can still be fetched in one go in the auth_on_register and (if authentication is succesful, the authorization data can be store in an ETS table or the like. Maybe there's a something I'm missing ;)

I understand it would be convenient to have a context that can be directly accessed from the hooks, but I don't think it's likely the hooks will be changed (unless we can do something which is backwards compatible and has negligible performance impact) before 2.0.

**Comment by oakad** [comment]
The idea was to avoid messing with ets on the plugin side. In particular:

1. The only key available is client id, which may not be unique. If client id is suddenly not unique, everything will suddenly be broken.

2. To avoid stale entries in the ets, client_gone/client_offline callbacks must always be present and call ets:delete. To me, this implicates a possibility of race condition: client may have changed networks (say mobile -> wifi) and as such, "gone" callback will be called on the previous client connection, while at the same time client may have already reconnected on the same client id from new address. The "_gone" callback will therefore kill a good client state in the ets.

A state object associated with the given client connection will be a much safer and easier to use object.

**Comment by larshesel** [comment]
I'm going to close this as we haven't any plans to add/change the current session lifecycle hooks due to backwards compatibility reasons. I've tagged it with the VerneMQ 2.0 label so we can come back and revisit this later. Also note that the multiple session feature is deprecated and will be removed in VerneMQ 2.0 which simplifies things a bit.
