### ISSUE TITLE
use mysql auth fail

### ISSUE THREAD

**Issue by fox-money** [vernemq/vernemq#1902]
### Environment

- VerneMQ Version:1.12.3

- Please describe the expected behaviour.
   I use mysql auth fail and remind that: 2021-11-01 15:27:31.737 [error] <0.636.0>@vmq_mqtt_fsm:check_user:571 can't authenticate client {[],<<"mqttProducer">>} from 115.206.138.137:57159 due to no_matching_hook_found, I do not know why. Or how to set hook?

**Comment by codeadict** [comment]
It will be good to know the MySQL version you are using, there are some known issues with Mysql 8+

**Comment by fox-money** [comment]
> It will be good to know the MySQL version you are using, there are some known issues with Mysql 8+

It's Mysql 8+

**Comment by codeadict** [comment]
See docs note at the end of https://docs.vernemq.com/configuring-vernemq/db-auth#mysql
