### ISSUE TITLE
VerneMQ Docker cannot connect to wss

### ISSUE THREAD

**Issue by sylvester-x** [vernemq/vernemq#1905]
### Environment
- VerneMQ Version: vernemq/vernemq:latest (Docker)
- OS: Redhat 8

I using vernemq to host in docker in Redhat 8. I had successfully connect with mqtt.fx and websocket (ws).

Is that any environment need added when run vernemq docker?

**Comment by ioolkos** [comment]
@sylvester-x thanks, you need to set up the TLS options (path to certfile etc) for the WSS listener, in `vernemq.conf` or ENV variables. After VerneMQ has booted you can check which listeners are running with `vmq-admin listener show`.
Sorry I can't be of more efficient help.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by sylvester-x** [comment]
hi, @ioolkos 
![image](https://user-images.githubusercontent.com/45072247/141256664-f9b4930c-3592-46c8-9b1b-4c290d83110c.png)

my side is setup the listener. But still cannot connect to wss

**Comment by exaland** [comment]
Hello ,

I have the same problem , i deploy with multiple environments , and impossible to get WSS works 

#1932
