### ISSUE TITLE
How to listen on IPV6?

### ISSUE THREAD

**Issue by JacoFourie** [vernemq/vernemq#1912]
Hi. 

I have all working but want to know how do I configure VERNMQ to listen on all IPV6 addresses also.

I have this set for IPV4.

listener.tcp.default = 0.0.0.0:1883

But how do you set it for V6?

**Comment by ioolkos** [comment]
IPv6 addresses should work in a listener config in the vernemq.conf file just like IPv4. (by adding an IP address:port combination):
Something like:
`listener.tcp.my_ipv6_listener = ipv6_address:1882`

In case you are specifically looking for something that corresponds to `0.0.0.0` in IPv4, can you test:
`listener.tcp.my_ipv6_listener = :::1882` (`::` being the short form of 0 address in IPv6)

You can also start a listener dynamically on the command line
`vmq-admin listener start address=:: port=1882`

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by JacoFourie** [comment]
Hi. Thank you for the reply. Can both IP4 and IP6 listen on the same port od 1883?

Like this?

listener.tcp.default = 0.0.0.0:1883
listener.tcp.my_ipv6_listener = :::1883

**Comment by ioolkos** [comment]
I think `::` should actually even start that port dualstack for both IPv4 and IPv6.
But please check with telnet or similar to be sure.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
Yes, you only configure the listener for IPv6 and it should be listening on 0.0.0.0 (IPv4) too.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by JacoFourie** [comment]
Thank you. This seems to work 100%. Now to set-up the servers to have public V6 ips.

**Comment by pitambariu** [comment]
I have tried with listener.tcp.my_ipv6_listener = :::1883 but its not working 

logs 
024-06-18T09:41:14.950256+00:00 [error] "[2406:f3]:10884" cannot be converted to a(n) UDS
2024-06-18T09:41:14.950351+00:00 [error] Error transforming datatype for: listener.tcp.internal
2024-06-18T09:41:14.950445+00:00 [error] "[24f3]:10883" cannot be converted to a(n) IP
2024-06-18T09:41:14.950533+00:00 [error] "[2406:ff3]:10883" cannot be converted to a(n) UDS
2024-06-18T09:41:14.950654+00:00 [error] Error transforming datatype for: listener.tcp.default
2024-06-18T09:41:14.950748+00:00 [error] "[2406:d3]:1883" cannot be converted to a(n) IP
2024-06-18T09:41:14.950849+00:00 [error] "[2406:ff3]:1883" cannot be converted to a(n) UDS

**Comment by ioolkos** [comment]
@pitambariu use the full IP's so that the `:` separating IP and Port can be parsed correctly.

Example: `0:0:0:0:0:0:0:0:1883`. Short version should work if the last IP item is a number: `::1:1883` would be localhost.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pitambariu** [comment]
Could you  please give examples which variable/component need to be added in vernemq.conf file to listen on ipv6 ip address 

Thanks
