### ISSUE TITLE
Building from source gives "rebar_core" error at vmq_bridge compile step

### ISSUE THREAD

**Issue by manjeera04** [vernemq/vernemq#1913]
- VerneMQ Version: 1.12.3
- OS: Debian - buster
- Erlang/OTP version (if building from source): tried with 22.3 and 23
- VerneMQ configuration (vernemq.conf) or the changes from the default: Made no changes to conf file
- Cluster size/standalone: standalone

### Expected behaviour

I have a docker file to build the image for vernemq 1.12.3. The docker file is trying to build from vernemq source. Build file should be generated after successful build.

My dockerfile:

FROM erlang:22.3
WORKDIR /vernemq
RUN apt-get update && \
    apt-get install -y git bash curl build-essential erlang libsnappy-dev libssl-dev && \
RUN git clone https://github.com/vernemq/vernemq.git .
RUN git checkout -b 1.12.3 tags/1.12.3; make rel DIAGNOSTIC=1;
RUN cd _build/default/rel/vernemq; tar -cvzf /tmp/vernemq-1.12.3.tar.gz .

### Actual behaviour

While building vernemq, it is failing while compiling vmq_bridge. This happened with both OTP 22.3 and OTP 23

This is the stack trace from the build output.

===> Port Cmd: git log -n 1 --pretty=format:"%h
" 
Port Opts: [{cd,"/vernemq/apps/vmq_ql"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/vernemq"
	cmd: git -c color.ui=false log --oneline --no-walk --tags --decorate

===> 	opts: [{use_stdout,false},return_on_error,{cd,"/vernemq/apps/vmq_ql"}]

===> Port Cmd: git -c color.ui=false log --oneline --no-walk --tags --decorate
Port Opts: [{cd,"/vernemq/apps/vmq_ql"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/vernemq"
	cmd: git rev-list --count 1.12.3..HEAD

===> 	opts: [{use_stdout,false},
               {cd,"/vernemq/apps/vmq_ql"},
               {debug_abort_on_error,"Getting rev-list of git dep failed in /vernemq/apps/vmq_ql"}]

===> Port Cmd: git rev-list --count 1.12.3..HEAD
Port Opts: [{cd,"/vernemq/apps/vmq_ql"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: badarg
===> Stack trace to the error location:
[{erlang,list_to_integer,["warning: refname '1.12.3' is ambiguous.\n0"],[]},
 {rebar_git_resource,get_patch_count,2,
                     [{file,"/home/runner/work/rebar3/rebar3/src/rebar_git_resource.erl"},
                      {line,342}]},
 {rebar_git_resource,collect_default_refcount,1,
                     [{file,"/home/runner/work/rebar3/rebar3/src/rebar_git_resource.erl"},
                      {line,315}]},
 {rebar_git_resource,make_vsn_,1,
                     [{file,"/home/runner/work/rebar3/rebar3/src/rebar_git_resource.erl"},
                      {line,268}]},
 {rebar_utils,vcs_vsn,3,
              [{file,"/home/runner/work/rebar3/rebar3/src/rebar_utils.erl"},
               {line,754}]},
 {rebar_otp_app,preprocess,3,
                [{file,"/home/runner/work/rebar3/rebar3/src/rebar_otp_app.erl"},
                 {line,125}]},
 {rebar_otp_app,compile,2,
                [{file,"/home/runner/work/rebar3/rebar3/src/rebar_otp_app.erl"},
                 {line,49}]},
 {rebar_prv_compile,compile_app_file,3,
                                    [{file,"/home/runner/work/rebar3/rebar3/src/rebar_prv_compile.erl"},
                     {line,254}]}]

**Comment by manjeera04** [comment]
update: Tried to build using OTP 23.3.2 based on the documentation from release notes for 1.12.3. But I still see the same error. Build is failing at vmq_bridge step

**Comment by ioolkos** [comment]
The issue seems to be this: `RUN git checkout -b 1.12.3 tags/1.12.3` leading to "warning: refname '1.12.3' is ambiguous."
Should work just checking out the tag, without creating a local branch of the same name.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
