### ISSUE TITLE
VerneMQ Node Periodically Crashes and Does Not Restart Automatically

### ISSUE THREAD

**Issue by csheaupdesigns** [vernemq/vernemq#1914]
### Environment

- VerneMQ Version: 1.12.3
- OS:  Ubuntu 18.04.3
- Erlang/OTP version (if building from source): Not building from source
- VerneMQ: attached (changed the file extension to .txt to allow for attachment to this interface)
- Cluster size/standalone: Standalone

### Expected behaviour

- VerneMQ runs without crashing.

### Actual behaviour

My node runs for extended periods of time.  I do see issues in the console.log file in which clients are not always behaving properly.  At this point, I am assuming this is do to network connection issues as the majority of the clients are edge devices with varying signal quality.  Periodically (maybe once every 15-20 days), I run into an issue in which VerneMQ crashes and is unable to get back to a working state without me manually restarting it.

I cannot decipher from the log or crash report what is causing this but it is an ongoing issue for me and happens on multiple instantiations of the same setup.  I'm open to the possibility that it is due to a bad configuration but I just can't tell from the messaging what in my configuration is bad.  At the same time, I'm curious if this is an actual issue within VerneMQ and my setup happens to trigger the issue for some reason.

The log file (and the previous one going back) and crash report for the most recent instance of the issue is attached.  I appreciate any help that can be provided.  Please let me know what other information will be helpful.

[console.log](https://github.com/vernemq/vernemq/files/7620308/console.log)

[crash.log](https://github.com/vernemq/vernemq/files/7620311/crash.log)

[vernemq.txt](https://github.com/vernemq/vernemq/files/7620318/vernemq.txt)

[console 0.log](https://github.com/vernemq/vernemq/files/7620328/console.0.log)

**Comment by ioolkos** [comment]
@csheaupdesigns you seem to want to start an SSL listener. You need to configure ca/cert/key to do this, in the `vernemq.conf` file.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
