### ISSUE TITLE
The queue process not terminated after the client disconnection

### ISSUE THREAD

**Issue by sreekesh93** [vernemq/vernemq#1917]
Setup:
1 verneqm node 
m54x large 

Simulated 150K load against the verneqm broker , the broker was able to handle 128K max concurrent connection, After this point we were facing service unavailable issue, connect_timeout issue, 
After some time the load simulation get stopped. After load simulation getting stopped the session process all got terminated but queue process is not getting clean state.

our understanding:
1 connection = 2 erlang process(session+ queue process)
after 128K conection , there were 256K erlang process. on termination of load we could notice 128K queue process is still pending which metrics matched with number of erlang process as both were in same numbers.

Could some one help in understanding why the queue process not getting cleared? or is there any configuration to be tweaked?

FYI:
The ERlang max port and process all sets to 512000 default was 256000

**Comment by ioolkos** [comment]
For `clean_session=false` (persistent sessions), the broker will keep the queue processes running.

Make sure you configure any needed OS settings for the load planned (file descriptors).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by sreekesh93** [comment]
I have set clean_session=true while publishing the message, open fds of venemq node is set to 1048576, We are not using persistent session on publishing message. 
Note: there is no subscriber as our AIM is to see how many open connections/ clients vernemq can support with one node setup

**Comment by ioolkos** [comment]
In general, broker resources are a function of input (load). Verne will not keep 128k queues around just like that.
Observe the disconnect phase of your test (do you send MQTT DISCONNECTS? do you just tear down the TCP connections?). Establish a clear separation between your test runs. 

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
