### ISSUE TITLE
Connection to VerneMq server works only with one connection at a time (Using Flutter Mqtt_client)

### ISSUE THREAD

**Issue by josh4500** [vernemq/vernemq#1920]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version:1.12.3
- OS: Windows
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 1

### Expected behaviour

- Please describe the expected behaviour.

### Actual behaviour
Connection to the mqtt server works on only one device at a time using the Flutter [mqtt_client](https://pub.dev/packages/mqtt_client) package. To connect with the other device, I have to disconnect the previously connected device.
 
- Please include minimal steps to reproduce the issue, if possible.
- Install [Flutter mqtt_client](https://pub.dev/packages/mqtt_client)
- And the code to connect is below
-  
```
static String server ="0.0.0.0; //Use the IP address of 127.0.0.1 if testing on iphone
static String clientIdentifier = "client_id_" + const Uuid().v4();
static int port = 1883;
static bool loggerOn = false;
final MqttServerClient _client = MqttServerClient.withPort(server, clientIdentifier, port, maxConnectionAttempts: 10);
final connMessage = MqttConnectMessage()
        .authenticateAs("admin", "Presence MQTT Server")
        .withClientIdentifier(clientIdentifier)
        .withWillTopic('lastwills')
        .withWillMessage('Will message')
        .withWillQos(MqttQos.atLeastOnce);
    _client.connectionMessage = connMessage;
try {
      await _client.connect();
      debugPrint(
          "Connecting with Client_id :: ${_client.clientIdentifier} to Server :: $server  Mqtt Client");
    } on NoConnectionException catch (e) {
      // Raised by the client when connection fails.
      debugPrint('MQTT Server::client exception - $e');
      _client.disconnect();
    } on SocketException catch (e) {
      // Raised by the socket layer
      debugPrint('MQTT Server::socket exception - $e');
      _client.disconnect();
    }
```

**Comment by ioolkos** [comment]
@josh4500 Thanks, this is very likely a client side issue, so I'm not sure how I can help efficiently.
