### ISSUE TITLE
Erlang scheduler usage

### ISSUE THREAD

**Issue by webfrank** [vernemq/vernemq#1924]
Hi, I have a three node cluster with 1000 clients and a 4000 msgs/s publish rate with 6 subscribers.

Using prometheus/grafana I noticed only one node is using  all 4 schedulers, the other two only the scheduler 1. The metrics are called system_utilization_scheduler_1|2|3|4.

Is this a normal behaviour or something should be fixed?

### Environment

- VerneMQ Version: 1.12.1
- OS: Alpine Linux
- Erlang/OTP version (if building from source): official docker image
- VerneMQ configuration (vernemq.conf) or the changes from the default
accept_eula = yes
nodename = VerneMQ@mqtt03
log.console = console
log.console.level = warning
allow_anonymous = on
listener.ssl.cafile = /etc/vernemq/vernemq_ca.crt
listener.ssl.certfile = /etc/vernemq/vernemq.crt
listener.ssl.keyfile = /etc/vernemq/vernemq.key
listener.ssl.default = 0.0.0.0:8883
listener.tcp.default.proxy_protocol = on
listener.tcp.default = 0.0.0.0:1883
listener.ws.default = 0.0.0.0:8080
listener.http.default = 0.0.0.0:8888
shared_subscription_policy = random
distributed_cookie = vernemq-cluster
listener.vmq.clustering = 172.16.199.28:44053

allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = on

metadata_plugin = vmq_swc

- Cluster size/standalone: 3 nodes cluster

### Expected behaviour

- Same scheduler usage on the three nodes

### Actual behaviour

- One node uses all 4 schedulers, the other two only one:

vmq-admin metrics show|grep scheduler

on node 01 and 03:
gauge.system_utilization_scheduler_1 = 100
gauge.system_utilization_scheduler_2 = 0

on node 02:
gauge.system_utilization_scheduler_4 = 100
gauge.system_utilization_scheduler_3 = 32
gauge.system_utilization_scheduler_1 = 19
gauge.system_utilization_scheduler_6 = 0
gauge.system_utilization_scheduler_5 = 0
gauge.system_utilization_scheduler_2 = 44
gauge.system_utilization_scheduler_8 = 0
gauge.system_utilization_scheduler_7 = 0

**Comment by ioolkos** [comment]
@webfrank Thanks. I wouldn't worry too much about the scheduler usage. Those are gauges, that is they show realtime values and can be volatile. (the `vmq-admin metrics show` command shows you the current state of gauges and counters).

One thing: if you use the 1.12 series, please use the 1.12.3 one if you want to use `vmq_swc` sync. 1.12.3 fixes a regression which can lead to increased sync times between nodes, for registers and subscribes.

Another note: commercial usage of the download packages (EULA based packages) requires a subscription. If you need more info on that, just get in touch with me, no problem.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
