### ISSUE TITLE
Cuttlefish validation broken on master

### ISSUE THREAD

**Issue by ajatprabha** [vernemq/vernemq#1926]
### Environment

- VerneMQ Version: master (41a9f14)
- OS: MacOS 11.5.2
- Erlang/OTP version (if building from source): 23.3.4.5
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: standalone

### Steps to reproduce

- Checkout to master (41a9f14)
- Run `make rel` (clean previous build, if required)
- Attemp to start node with `_build/default/rel/vernemq/bin/vernemq start`
```bash
_build/default/rel/vernemq/bin/vernemq start

!!!!
!!!! WARNING: ulimit -n is 10240; 65536 is the recommended minimum.
!!!!
vmq_cluster_node_sup
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

_build/default/rel/vernemq/bin/vernemq console

Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.

_build/default/rel/vernemq/bin/vernemq config generate -l debug

2022-01-07T10:12:33.858928+05:30 [debug] Cuttlefish log level is set to debug
2022-01-07T10:12:33.866419+05:30 [debug] Parsed arguments: [{etc_dir,"/Users/admin/Workspace/vernemq/_build/default/rel/vernemq/bin/../etc"},{schema_dir,"./share/schema"},{dest_dir,"./data/generated.configs"},{conf_file,"/Users/admin/Workspace/vernemq/_build/default/rel/vernemq/bin/../etc/vernemq.conf"},{log_level,"debug"},{max_history,3},{silent,false},{allow_extra,false}]
2022-01-07T10:12:33.876454+05:30 [info] Checking /Users/admin/Workspace/vernemq/_build/default/rel/vernemq/bin/../etc/app.config exists... false
2022-01-07T10:12:33.876559+05:30 [info] Checking /Users/admin/Workspace/vernemq/_build/default/rel/vernemq/bin/../etc/vm.args exists... false
2022-01-07T10:12:33.876608+05:30 [info] No app.config or vm.args detected in /Users/admin/Workspace/vernemq/_build/default/rel/vernemq/bin/../etc, activating cuttlefish
2022-01-07T10:12:33.879957+05:30 [debug] Generating config in: "/Users/admin/Workspace/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2022.01.07.10.12.33.config"
2022-01-07T10:12:33.880030+05:30 [debug] Generating vm.args in: "/Users/admin/Workspace/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2022.01.07.10.12.33.args"
2022-01-07T10:12:33.880330+05:30 [debug] SchemaFiles: ["./share/schema/10-vmq_server.schema","./share/schema/11-vmq_generic_msg_store.schema","./share/schema/12-vmq_plugin.schema","./share/schema/13-vmq_acl.schema","./share/schema/14-vmq_passwd.schema","./share/schema/15-vmq_diversity.schema","./share/schema/16-vmq_bcrypt.schema","./share/schema/17-vmq_webhooks.schema","./share/schema/18-vmq_bridge.schema","./share/schema/19-vmq_swc.schema","./share/schema/20-vmq_pulse.schema","./share/schema/30-vmq.schema","./share/schema/31-erlang_vm.schema","./share/schema/32-riak_sysmon.schema","./share/schema/33-eleveldb.schema"]
2022-01-07T10:12:34.004299+05:30 [debug] ConfFiles: ["/Users/admin/Workspace/vernemq/_build/default/rel/vernemq/bin/../etc/vernemq.conf"]
2022-01-07T10:12:34.392267+05:30 [debug] Adding Defaults
2022-01-07T10:12:34.394329+05:30 [debug] Right Hand Side Substitutions
2022-01-07T10:12:34.396752+05:30 [debug] Applying Datatypes
2022-01-07T10:12:34.428912+05:30 [debug] Validation
escript: exception error: undefined function vmq_schema_util:file_exists/1
  in function  cuttlefish_generator:'-run_validations/2-lc$^1/1-1-'/3 (/Users/admin/Workspace/vernemq/_build/default/lib/cuttlefish/src/cuttlefish_generator.erl, line 618)
  in call from cuttlefish_generator:'-run_validations/2-lc$^0/1-0-'/3 (/Users/admin/Workspace/vernemq/_build/default/lib/cuttlefish/src/cuttlefish_generator.erl, line 630)
  in call from cuttlefish_generator:'-run_validations/2-lc$^0/1-0-'/3 (/Users/admin/Workspace/vernemq/_build/default/lib/cuttlefish/src/cuttlefish_generator.erl, line 632)
  in call from cuttlefish_generator:run_validations/2 (/Users/admin/Workspace/vernemq/_build/default/lib/cuttlefish/src/cuttlefish_generator.erl, line 632)
  in call from cuttlefish_generator:map_validate/2 (/Users/admin/Workspace/vernemq/_build/default/lib/cuttlefish/src/cuttlefish_generator.erl, line 121)
  in call from cuttlefish_escript:engage_cuttlefish/1 (/Users/admin/Workspace/vernemq/_build/default/lib/cuttlefish/src/cuttlefish_escript.erl, line 382)
  in call from cuttlefish_escript:generate/1 (/Users/admin/Workspace/vernemq/_build/default/lib/cuttlefish/src/cuttlefish_escript.erl, line 277)
```

### Expected behaviour

- The cluster should start properly

### Actual behaviour

- Cuttlefish fails to validate generated config

**Comment by ioolkos** [comment]
@ajatprabha related: https://github.com/vernemq/vernemq/issues/1863

VerneMQ currently does not build on newer Macs.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ajatprabha** [comment]
Okay, however the Mac I use is a 2019 Intel i7 Model, is this specific to M1 chip or Macs in general?

**Comment by ioolkos** [comment]
@ajatprabha I was thinking it to be specific to M1, but I could easily be wrong with that, as I currently do not test on Mac at all.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ajatprabha** [comment]
Is there something I could help with to find what is wrong here?

The last working build on Mac was 1.11.0, I didn't test a build on 1.12.x until now.

**Comment by ioolkos** [comment]
@ajatprabha 

The error is `undefined function vmq_schema_util:file_exists/1` which either means we have an incomplete compilation from the release building; or the release build somehow configures wrong paths (ie the runner script (`vernemq`) picks up wrong paths.

But it's unclear to me why this would work any different on OS X than on Linux.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by rohansingh** [comment]
This is a total stab in the dark, but it could be something to do with a case-insensitive file system.

**Comment by whendon** [comment]
I can confirm this is an issue still on master ([85db5a1])(https://github.com/vernemq/vernemq/commit/85db5a18bb52656aee27fa9e466a0d6cbb9634c7)

Operating System:
Ubuntu 20.04.3 LTS

Erlang:
Erlang/OTP 22

erl -version
=> Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.6.4

My steps:
git clone https://github.com/vernemq/vernemq.git
make rel
sudo mv _build/default/rel/vernemq /usr/lib/vernemq
// at this point I update /usr/lib/vernemq/etc/vernemq.conf to match what I had working on 1.12.3, then:
sudo systemctl start vernemq

Results in this error:
Jun 14 19:31:22 ip-10-0-12-192 vernemq[31500]: Error generating config with cuttlefish

My service file: (located /etc/systemd/system/vernemq.service)
```
[Unit]
Description=VerneMQ Server
After=network.target epmd@0.0.0.0.socket
Wants=network.target epmd@0.0.0.0.socket

[Service]
Type=simple
User=vernemq
PIDFile=/run/vernemq/vernemq.pid
Group=vernemq
NotifyAccess=all
LimitNOFILE=infinity
Environment="WAIT_FOR_ERLANG=3600"
TimeoutStartSec=3600
RuntimeDirectory=vernemq
WorkingDirectory=/usr/lib/vernemq
ExecStartPre=/usr/lib/vernemq/bin/vernemq chkconfig
ExecStart=/usr/lib/vernemq/bin/vernemq start
ExecStop=/usr/lib/vernemq/bin/vernemq stop
ExecStop=/bin/sh -c "while ps -p $MAINPID >/dev/null 2>&1; do sleep 1; done"
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

This service file was working (using the same verne.conf and verne.service) on the 1.12.3 build (from source)

It appears to be bombing out on ExecStartPre execution, which would be the chkconfig command 

I tried downloading the 1.12.5 source code zip and building that as well, but it resulted in vernemq and all dependencies pulling down version 0.0.0, which obviously didnt work. Heres an example of that output:
```
===> Getting log of git repo failed in /home/ubuntu/vernemq/apps/vmq_ql. Falling back to version 0.0.0
===> Getting log of git repo failed in /home/ubuntu/vernemq/apps/vmq_plugin. Falling back to version 0.0.0
===> Getting log of git repo failed in /home/ubuntu/vernemq/apps/vmq_commons. Falling back to version 0.0.0
===> Getting log of git repo failed in /home/ubuntu/vernemqapps/vmq_server. Falling back to version 0.0.0
```

Using git clone instead of downloading the zip moved past that (got all correct versions), now the cuttlefish config is not generating correctly.

**Comment by bopbi** [comment]
i am able to build and run vernemq on latest mac, this is what i do :

- brew install erlang
- brew install openssl
- brew install leveldb
- brew install snappy
- cd /usr/local/lib/
- ln -s /opt/homebrew/Cellar/snappy/1.1.9/lib/libsnappy.1.dylib
- ln -s /opt/homebrew/Cellar/snappy/1.1.9/lib/libsnappy.a
- ln -s /opt/homebrew/Cellar/snappy/1.1.9/lib/libsnappy.dylib

in the middle it will fail with 
```
===> Compiling vmq_bridge
cc   -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
vmq_passwd.c:32:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [compile] Error 1
```
edit your `apps/vmq_passwd/c_src/Makefile` set the correct `OPENSSL_DIR` for me it will be `OPENSSL_DIR ?= /opt/homebrew/Cellar/openssl@3/3.0.5`

re-run the `make-rel` and it works

**Comment by codeadict** [comment]
`OPENSSL_DIR=$(brew --prefix openssl) make rel` should work

**Comment by bopbi** [comment]
@codeadict thanks for the suggestion, i have created a PR for your suggestion 

https://github.com/vernemq/vernemq/pull/2067
