### ISSUE TITLE
Mongodb bug - Can't pass authentification

### ISSUE THREAD

**Issue by johnnytolengo** [vernemq/vernemq#1928]
Confirmed Bug,  Vernemq 1.12.4 release can't connect to last Mongodb v5.0 it loops getting `Can't pass authentification`

The problem is the erlang-pbkdf2 old library used, the bug is gone upgrading  the that library to last version:
`commit: d221d66f159d75ff6cdbb95c913db3caf156a8dd`

Using that commit d221d66f159d75ff6cdbb95c913db3caf156a8dd the problem is gone.

By the way I also updated mongodb-erlang too.

My modifications were rebar.lock:
```
 {git,"git://github.com/comtihon/mongodb-erlang.git",
       {ref,"3384119c9236eda137ea34079b4ca196cbefdf27"}},
```
and
 ```
{git,"git://github.com/comtihon/erlang-pbkdf2.git",
       {ref,"d221d66f159d75ff6cdbb95c913db3caf156a8dd"}},
```

**Comment by ioolkos** [comment]
Fixed in master, as of: https://github.com/vernemq/vernemq/pull/1929
