### ISSUE TITLE
WSS Crash with Docker and Ubuntu - LetsEncrypt

### ISSUE THREAD

**Issue by exaland** [vernemq/vernemq#1932]
### Environment

- VerneMQ Version: latest with Docker
- OS: Ubuntu 18.04
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
-   - DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD=off
      - DOCKER_VERNEMQ_PLUGINS__VMQ_ACL=off
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED=on
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST=db
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT=5432
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER=postgres
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD=somepassword
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE=postgres
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD=crypt
      - "DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT=0.0.0.0:8083"
      - "DOCKER_VERNEMQ_LISTENER__WS__DEFAULT=0.0.0.0:8080"
      - DOCKER_VERNEMQ_LISTENER__WSS__CAFILE=/etc/letsencrypt/live/mydomainname.com/chain.pem
      - DOCKER_VERNEMQ_LISTENER__WSS__CERTFILE=/etc/letsencrypt/live/mydomainname.com/cert.pem
      - DOCKER_VERNEMQ_LISTENER__WSS__KEYFILE=/etc/letsencrypt/live/mydomainname.com/privkey.pem
- Cluster size/standalone: 

### Expected behaviour

- Configure WSS with letsencrypt but i got that error when i try to connect
### Actual behaviour

 [error] Cowboy stream 1 with ranch listener {{0,0,0,0},8083} and connection process <0.667.0> had its request process exit with reason: no function clause matching vmq_websocket:terminate({crash,error,function_clause}, #{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accep...">> => ...,...},...}, [{type,mqttwss},{mountpoint,[]},{allowed_protocol_versions,[3,4,131]},{buffer_sizes,undefined},{...}]) line 132
root@ubuntu-s-2vcpu-2gb-amd-sfo3-01:~/vernemq-docker# exit

**Comment by ioolkos** [comment]
Context: https://github.com/vernemq/vernemq/issues/1901

I have not yet provided Docker version 1.12.4 which should resolve this.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
