### ISSUE TITLE
ACL issue

### ISSUE THREAD

**Issue by LukasVondracek** [vernemq/vernemq#1938]
### Environment

- VerneMQ Version: docker erlio/docker-vernemq:latest
- vernemq variables
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'off'
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS: 3,4,5
      DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT: '0.0.0.0:1883'
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: 'on'
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: '/etc/ssl/ca.crt'
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: '/etc/ssl/server.crt'
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: '/etc/ssl/server.key'
      DOCKER_VERNEMQ_LISTENER__SSL__USE_IDENTITY_AS_USERNAME: 'off'
      DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE: 'off'
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: '0.0.0.0:8883'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED: 'on'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST: 'host.docker.internal'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT: '5432'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER: 'admin'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD: 'admin'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE: 'mydb'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD: 'crypt'
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: 'debug'

### Actual behaviour

I am trying to authorize clients to specific topics. SSL is working, authentication is working (when i change password to 1234 i can't connect). My setup in DB for publish_acl and subscibe_acl is both [{"pattern": "x"}] but i am able to send message to any topic i want.
`mosquitto_pub  --cafile ca.crt --cert client.crt --key client.key -h localhost -m hello -t topic -p 8883 -i test-client -u test-user -P 123 -d`
`Client test-client sending CONNECT`
`Client test-client received CONNACK (0)`
`Client test-client sending PUBLISH (d0, q0, r0, m1, 'topic', ... (5 bytes))`
`Client test-client sending DISCONNECT`

### Expected behaviour

I would expect that I can publish only to topic x

### Note

I don't know if that docker image i am using is the right one.

**Comment by ioolkos** [comment]
Are you testing with a connected subscriber?
vernemq/vernemq are the images on Dockerhub.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
The difference in the images is that the one you use is more than 2 years old. OTOH the new ones need a subscription in case you want to use commercially.

Please test with a subscriber to verify whether the Publish ACL is enforced or not. You'll see what I mean.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by LukasVondracek** [comment]
Ok, I tried [this](https://hub.docker.com/r/vernemq/vernemq) docker image and situation is same. Also with subscribing. See the result, I am able to listen on topic "topic", even it is not present in database.

`vondracekmac2:certs vondracek$ mosquitto_sub  --cafile ca.crt --cert client.crt --key client.key -h localhost  -t topic -p 8883 -i inbound -u core-user -P 123 -d`
`Client inbound sending CONNECT`
`Client inbound received CONNACK (0)`
`Client inbound sending SUBSCRIBE (Mid: 1, Topic: topic, QoS: 0, Options: 0x00)`
`Client inbound received SUBACK`
`Subscribed (mid: 1): 0`
`Client inbound sending CONNECT`
`Client inbound received CONNACK (0)`
`Client inbound sending SUBSCRIBE (Mid: 2, Topic: topic, QoS: 0, Options: 0x00)`
`Client inbound received SUBACK`
`Subscribed (mid: 2): 0`

**Comment by ioolkos** [comment]
@LukasVondracek Plugins run in chains. If you have vmq.acl switched on, it will be the first plugin to match (& wrongly authorize the subscribes)
refer to docs: https://docs.vernemq.com/configuring-vernemq/db-auth#introduction-and-general-setup

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by LukasVondracek** [comment]
It helped for subscribing, thanks. But why is it able to send (publish) messages without problem? Or is it problem of client "mosquito_pub" ? I am new to it, so maybe I just don't understand some concept....

**Comment by gitnwana** [comment]
Hi, @LukasVondracek   We are facing the same kind of [issue](https://github.com/vernemq/vernemq/issues/1945) . 

Can u please tell how it worked for you?
