### ISSUE TITLE
The message queues are not getting decreased even without no clients sending messages

### ISSUE THREAD

**Issue by pchandrasekhar210893** [vernemq/vernemq#1939]
### To help us save time and help you faster

The message queues are not getting decreased even without no clients sending messages.  The queued messages are almost 101663
[erl_crash.zip](https://github.com/vernemq/vernemq/files/7949736/erl_crash.zip)

### Environment

- VerneMQ Version: 1.11.0
- OS: ubuntu 18.04
- Erlang/OTP version:  erts-10.7
- VerneMQ configuration (vernemq.conf) 
Vernemq.conf
=============
allow_anonymous = off

## Netsplits
allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = on

## Sessions
allow_multiple_sessions = on
coordinate_registrations = off
retry_interval = 20

## Client
max_client_id_size = 100
max_inflight_messages = 1
max_online_messages = 10
max_offline_messages = 0
max_message_size = 0
upgrade_outgoing_qos = off
queue_deliver_mode = balance

# Max message rate
max_message_rate = 10
max_drain_time = 20
persistent_client_expiration = 1h

## Listners
listener.max_connections = infinity
listener.nr_of_acceptors = 20000
listener.http.default = 10.34.243.36:8888
listener.ws.default = 10.34.243.36:9001
listener.tcp.default = 10.34.243.36:1883
listener.tcp.allowed_protocol_versions = 3,4,5
listener.vmq.clustering = 10.34.243.36:44053

## Systree Reporter
systree_enabled = on
systree_interval = 20000

## Graphite
graphite_enabled = off

## Shared subscription policy
shared_subscription_policy = prefer_local

## Plugins
plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = on
plugins.vmq_bridge = off
metadata_plugin = vmq_swc

## ACL
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10

## Logging
log.console = file
log.console.level = info
log.console.file = /vernemq/logs/console.log
log.error.file = /vernemq/logs/error.log
log.syslog = off
log.crash = on
log.crash.file = /vernemq/logs/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5

## Node Settings
nodename = VerneMQ
distributed_cookie = WMT-SS-PTT-VMQ
erlang.async_threads = 1024
erlang.max_ports = 524288
leveldb.maximum_memory.percent = 10
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
erlang.schedulers.compaction_of_load = true
erlang.schedulers.utilization_balancing = true
erlang.distribution_buffer_size=32MB

- Cluster size/standalone: 9 nodes
Each Node Configuration
CPU cores : 4
Memory : 16GB

### Expected behaviour

- The number of messages in queue should be reduced.

### Actual behaviour

- The number of messages in queue are not reducing back to normal. And one of the VM restarted disturbed the other node's vernemq service.

**Comment by ioolkos** [comment]
Thanks. I cannot give this much time. (let me know in case you have a support agreement)
I see from the crash log slogan though that the system was halted by user interaction. Did you abort a shell attached to Verne, or something like that?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by abijithvjn** [comment]
@ioolkos We do not have a support plan now. 

And yes the virtual machine was restarted due to hardware issues. But is the behavior expected in that case?

Right now also we are seeing message queues in some of the nodes which are not getting consumed. 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/26138890/151537186-b11074d2-ce8e-4cc6-828a-b9f9a572033c.png">

In two of the nodes, the queued messages are high and they are not getting consumed.
