### ISSUE TITLE
vernemq queue_teardown how to fix

### ISSUE THREAD

**Issue by Konstantin2154** [vernemq/vernemq#1942]
Hello, I have 400-600 devices, they connect via tls (8883) on the first day everything was fine, but then new devices stopped connecting

- VerneMQ Version:**1.12.3**
- OS: **RHEL**
- Cluster size
- Erlang/OTP version (if building from source):   **erlang-23.3.2-1.el7.x86_64**
- VerneMQ configuration (vernemq.conf) or the changes from the default:

[vernemqtxt.txt](https://github.com/vernemq/vernemq/files/8006751/vernemqtxt.txt)
[metrix.txt](https://github.com/vernemq/vernemq/files/8006755/metrix.txt)

Based on the situation, I see that the problem is in queue_teardown{node="VerneMQ@10.113.150.226"} 9089687

**Comment by Konstantin2154** [comment]
how to fix this problem?

**Comment by ioolkos** [comment]
The Verne logs might help you find out.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by Konstantin2154** [comment]
In the logs I do not see any problems related to the problem described above.
 I don't understand why queue teardown happens
 
[error.txt](https://github.com/vernemq/vernemq/files/8008152/error.txt)
[crash.txt](https://github.com/vernemq/vernemq/files/8008153/crash.txt)
[console.txt](https://github.com/vernemq/vernemq/files/8008154/console.txt)

**Comment by ioolkos** [comment]
Console.log is full of logs similar to this issue: https://github.com/vernemq/vernemq/issues/1609

I currently do not know what the cause is.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
