### ISSUE TITLE
VerneMQ doesn't process more then 10 concurrent clients

### ISSUE THREAD

**Issue by molestinsky** [vernemq/vernemq#1952]
Hi, 

got an issue with broker:

### Environment
- VerneMQ Version: 1.12.4
- OS: CentOS 7
- VerneMQ configuration:
[vernemq.conf](https://github.com/vernemq/vernemq/files/8151508/vernemq.txt)
- Standalone mode
- 8 vCPUs, 16GB RAM
- clients use Python "paho-mqtt" library (python 3.8, paho 1.5.0)
- clients connect via SSL

### Expected behaviour
Process more then 10 concurrent clients

### Actual behaviour
VerneMQ doesn't process more then 10 concurrent SSL clients, loosing messages and throws following error:
<0.5574.6> Supervisor {<0.5574.6>,tls_dyn_connection_sup} had child sender started with {tls_sender,start_link,undefined} at <0.5575.6> exit with reason noproc in context shutdown_error

**Comment by ioolkos** [comment]
I don't think I've seen that error.
I suppose this is from a test script? If yes, try to introduce a variable approach to generate more data. Do you connect in a for-loop? What if you connect slower?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by molestinsky** [comment]
Thanks for reply.

Our logic is following:
1) Main service (Core) is permanently listenning all topics on server. For example, "/devices/+/init/in"  or "/devices/+/init/out"
2) devices connects to VerneMQ and creates unique topic with its name ans subtopics "in" and "out" and sends data into "in" topic 
3) according to the topic name (device's name) core do something and sends response to that topic into "out" subtopic

Here is our code example: [misc.py](https://github.com/vernemq/vernemq/files/8160841/misc.txt) 

Class "Listener.subscribe" - is for subscription, 
sending message via procedure "__mqtt_publish" (runs like thread from  "mqtt_publish")
receiving message via class "Listener.on_message"
connecting - class "Listener.go"

**Comment by ioolkos** [comment]
Can you determine on a TLS level whether and how you can connect to that Verne endpoint? (using openssl client, for instance). Is that endpoint supposed to work with Client certs or without Client certs?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
