### ISSUE TITLE
Unexpected behaviour of duplicate Publish in case of QoS 2

### ISSUE THREAD

**Issue by dumbpreacher** [vernemq/vernemq#1963]
While using QoS 2, we are experiencing the following issue when the following steps are performed:

1. QoS 2 message is published by client
2. PubRec is sent to the client
3. Client gets disconnected (due to possible bad network) before it can send back PubRel
4. When client connects back and publishes the same message (since QoS 2 flow is not yet complete), the broker does not treat this message as a duplicate publish. All subscribers to this topic receive the duplicate message.

### Environment

- VerneMQ Version: latest
- OS: MacOS Catalina
- Erlang/OTP version (if building from source): OTP 23
- Cluster size/standalone: standalone

### Expected behaviour
- The duplicate message published by publisher should be rejected by the broker.

### Actual behaviour
- When client connects back and publishes the same message (since QoS 2 flow is not yet complete), the broker does not treat this message as a duplicate publish. All subscribers to this topic receive the duplicate message.

We are ignoring waiting acks for QoS 2 here: https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/src/vmq_mqtt_fsm.erl#L878
Any reason why we are doing this?

**Comment by ioolkos** [comment]
@dumbpreacher does the client set the DUP flag in the re-publish?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by dumbpreacher** [comment]
@ioolkos, thanks for the quick response. Yes, we are setting DUP flag in the republish.

**Comment by ioolkos** [comment]
@dumbpreacher from your description it's unclear whether the consumers did get the message 1x or 2x. Which one is the case?

also: is this in a cluster, where the publisher is not on the same node as the consumer? (then this would be an additional place to check for issues).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by dumbpreacher** [comment]
@ioolkos, the subscribers to this topic received the republishes as well. I was subscribing using a mosquitto client with qos 2.
We were using a standalone cluster (i.e. single node only)

**Comment by ioolkos** [comment]
@dumbpreacher did the subscriber get the message 1x or 2x?

You used `mosquitto_sub?` if yes, add `-d` flag to get info what the command does exactly. 

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@dumbpreacher dup flag 0 at the outgoing end makes sense; the dup flag is only set per one client-server session, not end-to-end.
I have one last question: does the original publisher use the same PacketID for the re-sent (and flagged as duplicate) Publish as for the original message? it should!

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by dumbpreacher** [comment]
If by packet ID you mean Message Id, then yes we are using the same Message Id:
```
2022-03-21T12:25:43Z <9488.25674.36> MQTT RECV: CID: "swagat:889422:32675-2376-53732" PUBLISH(d0, q2, r0, m1, "chat/32675-2376-53732/client-events/0") with payload:
    testing2
2022-03-21T12:25:43Z <9488.25674.36> Calling auth_on_publish(889422,{[],
                                                                     <<"swagat:889422:32675-2376-53732">>},2,chat/32675-2376-53732/client-events/0,false) with payload:
    testing2
2022-03-21T12:25:43Z <9488.25674.36> Hook returned "ok"
2022-03-21T12:25:43Z <9488.25674.36> MQTT SEND: CID: "swagat:889422:32675-2376-53732" PUBREC(m1)
2022-03-21T12:26:50Z <9488.25674.36> Trace session for swagat:889422:32675-2376-53732 stopped
2022-03-21T12:26:57Z New session with PID <9488.26078.36> found for client "swagat:889422:32675-2376-53732"
2022-03-21T12:26:57Z <9488.26078.36> MQTT RECV: CID: "swagat:889422:32675-2376-53732" CONNECT(c: swagat:889422:32675-2376-53732, v: 4, u: 889422, p: password, cs: 0, ka: 360)
2022-03-21T12:26:57Z <9488.26078.36> Calling auth_on_register({{182,68,78,21},
                                                               42196},{[],
                                                                       <<"swagat:889422:32675-2376-53732">>},889422,password,false)
2022-03-21T12:26:57Z <9488.26078.36> Hook returned "ok"
2022-03-21T12:26:57Z <9488.26078.36> MQTT SEND: CID: "swagat:889422:32675-2376-53732" CONNACK(sp: 1, rc: 0)
2022-03-21T12:27:03Z <9488.26078.36> MQTT RECV: CID: "swagat:889422:32675-2376-53732" PUBLISH(d1, q2, r0, m1, "chat/32675-2376-53732/client-events/0") with payload:
    testing2

**Comment by ioolkos** [comment]
@dumbpreacher thanks, this looks like a Verne issue then.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by dumbpreacher** [comment]
@ioolkos, could you help with reviewing this PR: https://github.com/vernemq/vernemq/pull/1968

**Comment by ioolkos** [comment]
Fixed by https://github.com/vernemq/vernemq/pull/1968
