### ISSUE TITLE
include conf.d/*.conf is ignored

### ISSUE THREAD

**Issue by resmo** [vernemq/vernemq#1970]
### To help us save time and help you faster

in the packages for centos7/8, debian11, suse, there is a `include conf.d/*.conf` in the vernemq.conf but it seems vernemq does not actually read from conf.d while it does start the deamon.

probably related #1767

### Environment

- VerneMQ Version: 1.12.4
- OS: debian11, centos7, rockylinux8

### Expected behaviour

use *.conf files from conf.d

### Actual behaviour

ignores any *.conf file in conf.d

**Comment by ioolkos** [comment]
@resmo I see, I forgout about that. I should delete that line in the `vernemq.conf` file; it's something the `rebar3` builder adds, but all Verne configs need to be in the `vernemq.conf` file anyway.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
This has been hardcoded in Cuttlefish: https://github.com/basho/cuttlefish/blob/cb3df6a917ee93374de2b881e138e3dc6e9bf5cf/src/cuttlefish_conf.erl#L146
This should be configurable in Cuttlefish, but our pain with that here is not big enough for a PR over there ... so I'm closing the issue.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@resmo it seems this has always worked, or at least works now. The `conf.d` directory has to be created alongside the `vernemq.conf` file AND you have to change the owner of the directory and additional conf files (to the vernemq:vernemq user).
I guess that was the point we missed...

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by resmo** [comment]
@ioolkos let me test it again, but it should be sufficient to have read permission even with root owned conf.
