### ISSUE TITLE
Feature Requests: improve cli vmq-admin handling

### ISSUE THREAD

**Issue by resmo** [vernemq/vernemq#1971]
### To help us save time and help you faster
I have a few improvement requests for the cli `vmq-admin`

- make `vmq-admin cluster show` automation friendlier by optionally disable the table view with a param `--format=raw` (alternatively `--format=json`)
-  `vmq-admin cluster join` should exit code > 0 for any error e.g. "Couldn't join cluster due to not_reachable" 

### Environment

- VerneMQ Version: 1.12.4
- OS: n/a

**Comment by codeadict** [comment]
The JSON format is supported, most likely need to be documented better and made friendlier probably. This is how it works:

```console
 $ _build/default/rel/vernemq/bin/vmq-admin cluster show --format=json | jq '.table'
[
  {
    "Node": "VerneMQ@127.0.0.1",
    "Running": true
  }
]
```
