### ISSUE TITLE
Feature request: auth expiry

### ISSUE THREAD

**Issue by tobdub** [vernemq/vernemq#1973]
It would be nice if a plugin could set an expiration time for an authentication. After the authentication expires the server could trigger a re-auth by disconnecting the client.

**Comment by ioolkos** [comment]
@tobdub do you still use VerneMQ?

this should be implemented by https://github.com/vernemq/vernemq/pull/2107 now

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tobdub** [comment]
Nice! I implemented this in the plugin, but this looks like it could significantly simplify the plugin implementation.
