### ISSUE TITLE
reconfigure_bridges:88 CRASH REPORT Process <0.214.0> with 0 neighbours exited with reason: no match of right hand value

### ISSUE THREAD

**Issue by sxdyff** [vernemq/vernemq#1974]
Bridging problem: when I configure to use IPv6 to connect other agents, the startup fails. The error should be that I don't recognize the IPv6 address. If anyone encounters and solves this problem, please help me. Thank you very much!

plugins.vmq_bridge = on
vmq_bridge.tcp.br0 = 2001:2002:2003:2004:2005:2006:2007:2111:1882

crash.log
exception exit: {{bad_return,{{vmq_server_app,start,[normal,[]]},{'EXIT',{{badmatch,{"br0","2001","2002","2003","2004","2005","2006","2007","2111","1882"}},[{vmq_bridge_sup,reconfigure_bridges,3,[{file,"/share/build/cross-compile/x64/build/PlatformCBB_daily/o0-component/00-opensource/vernemq/apps/vmq_bridge/src/vmq_bridge_sup.erl"},{line,88}]},{vmq_bridge_sup,change_config,1,[{file,"/share/build/cross-compile/x64/build/PlatformCBB_daily/o0-component/00-opensource/vernemq/apps/vmq_bridge/src/vmq_bridge_sup.erl"},{line,82}]},{vmq_plugin_helper,all,3,[{file,"/share/build/cross-compile/x64/build/PlatformCBB_daily/o0-component/00-opensource/vernemq/apps/vmq_plugin/src/vmq_plugin_helper.erl"},{line,26}]},{vmq_server_app,start,2,[{file,"/share/build/cross-compile/x64/build/PlatformCBB_daily/o0-component/00-opensource/vernemq/apps/vmq_server/src/vmq_server_app.erl"},{line,42}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}

**Comment by ioolkos** [comment]
@sxdyff Thanks, yes, the plugins that you configure in the `vernemq.conf` file need to be startable, due to the current configuration architecture.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by sxdyff** [comment]
@ioolkos Thank you. The problem is that it can't be started. How can I configure it correctly？

**Comment by ioolkos** [comment]
Note to self: Review/implement ipv6 support for outgoing bridges.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@sxdyff On the remote chances this is still interesting to you, a draft PR to enable inet6 here: https://github.com/vernemq/vernemq/pull/2269
(although it's still somewhat untested)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
