### ISSUE TITLE
CRASH REPORT: no function clause matching vmq_websocket:terminate

### ISSUE THREAD

**Issue by tobdub** [vernemq/vernemq#1983]
### Environment
- VerneMQ Version: 1.12.4
- OS: Debian Bullseye Docker
- Erlang/OTP version: OTP 24
- VerneMQ configuration (vernemq.conf) or the changes from the default: WebSockets enabled
- Cluster size/standalone: 1 node behind load balancer

### Expected behaviour
No crash

### Actual behaviour
Crashes seen in the log:
```
03:58:29.760 [error] CRASH REPORT Process <0.6878.2> with 0 neighbours crashed with reason: no function clause matching vmq_websocket:terminate({crash,error,function_clause}, #{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accep...">> => ...,...},...}, [{type,mqttws},{mountpoint,[]},{allowed_protocol_versions,[3,4]},{buffer_sizes,undefined}]) line 132
03:58:29.761 [error] Cowboy stream 1 with ranch listener {{172,17,0,3},8080} and connection process <0.6877.2> had its request process exit with reason: no function clause matching vmq_websocket:terminate({crash,error,function_clause}, #{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accep...">> => ...,...},...}, [{type,mqttws},{mountpoint,[]},{allowed_protocol_versions,[3,4]},{buffer_sizes,undefined}]) line 132
```
Can be reproduced by:
```
curl -i https://<broker>/mqtt
```
Related to https://github.com/vernemq/vernemq/issues/1317

**Comment by tobdub** [comment]
Workaround with a HAProxy load balancer:
```
## websocket protocol validation
acl hdr_connection_upgrade hdr(Connection)                 -i upgrade
acl hdr_upgrade_websocket  hdr(Upgrade)                    -i websocket
acl hdr_valid_protocol     hdr(Sec-WebSocket-Protocol)     -i mqtt
acl hdr_websocket_key      hdr_cnt(Sec-WebSocket-Key)      eq 1
acl hdr_websocket_version  hdr_cnt(Sec-WebSocket-Version)  eq 1
http-request deny if ! hdr_connection_upgrade ! hdr_upgrade_websocket ! hdr_valid_protocol ! hdr_websocket_key ! hdr_websocket_version
```

**Comment by ioolkos** [comment]
@tobdub thanks, what is the exact cause, though?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tobdub** [comment]
If a server is exposed on the Internet there is a lot of different crawlers, scanners and hackers that sends various http requests to the server. I think VerneMQ should reject those invalid requests and not crash.

**Comment by ioolkos** [comment]
@tobdub Ok, thanks, I see and mostly agree.
For readers: `Crash` here does not mean VerneMQ crashes or anything like that. The crash is an exception terminating the session (which is what should happen in any faulty case, although you seem to say that we could send a Reject on HTTP/WS level somehow). We might want to handle the situation more silently, not logging an Error. In a situation as described this is bound to create much noise in the logs.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
