### ISSUE TITLE
Memory usage not getting reduced even after all connections are closed

### ISSUE THREAD

**Issue by Goushikaa** [vernemq/vernemq#1988]
### Environment
- VerneMQ Version: 1.11.0
- OS: Linux
- Cluster size: 1
- CPU Limit: 2 cores
- Memory limit: 512MB (For testing purpose)

### VerneMQ configuration (vernemq.conf) 
```accept_eula=yes
erlang.max_ports=800000
leveldb.maximum_memory=268435456
vmq_webhooks.pool_max_connections=5000
persistent_client_expiration=1h
plugins.vmq_webhooks=off
listener.nr_of_acceptors=10000
vmq_webhooks.pool_timeout=60000
max_online_messages=1000
leveldb.write_buffer_size_max=20971520
vmq_webhooks.authwebhook.hook=auth_on_register
max_offline_messages=1000
erlang.process_limit=800000
vmq_webhooks.authwebhook.response_timeout=30000
allow_subscribe_during_netsplit=on
listener.max_connections=infinity
leveldb.write_buffer_size_min=10485760
allow_publish_during_netsplit=on
erlang.max_ets_tables=800000
allow_anonymous=on
allow_unsubscribe_during_netsplit=on
max_client_id_size=200
metadata_plugin=vmq_swc
log.console=both
allow_register_during_netsplit=on
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
```

### Load Simulation
4500 client connections
Each connection will publish 5 messages to a specific topic and each client subscribes to the same topic it publishes 
After publishing 5 messages, the connection will be closed 

### Expected behaviour

- Container memory usage should reduce when there is no open connection

### Actual behaviour

- For each load run, we are seeing the memory increased for processing the request is getting reduced a bit and maintains in that range. The memory not getting reclaimed completely
- With first two runs, all requests processed without any issues
- On third run, we could see the verneMQ process getting stopped due to OOM error

We tried to update LEVELDB configurations, but there is no change in memory usage
 ```DOCKER_VERNEMQ_LEVELDB__MAXIMUM_MEMORY: "268435456"```

Do we need to update any other configurations to get the expected behaviour as mentioned above

**Comment by ioolkos** [comment]
Likely the webhooks cache.
Attach to Verne and call `vmq_webhooks_cache:purge_all().`

500MB will not make Verne happy.


---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by famagusta** [comment]
We are seeing similar behaviour as well on 1.11.0. The memory consumption increases with traffic and eventually crashes due to OOM kill. Have tried reducing the leveldb memory percent from 70 to 30 but it didn't work. 
We have a cluster setup with around 40-50k devices and 30-40 backend subscribers (shared subscriptions)
Below is a screenshot

<img width="1416" alt="Screenshot 2022-05-15 at 9 32 04 AM" src="https://user-images.githubusercontent.com/1617696/168456650-47b16dd1-a790-4789-9349-dbcec6e9695a.png">

**Comment by Goushikaa** [comment]
@ioolkos We have not enabled webhook for the load simulation.
```plugins.vmq_webhooks=off```

**Comment by ioolkos** [comment]
@famagusta what VerneMQ packages do you use? note that the EULA-based packages require a paid subscription for commercial use.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by famagusta** [comment]
We are using the 1.11.0 release of this repository on ec2 machines.
