### ISSUE TITLE
How to configure VerneMQ Docker container uses PostgreSQL for storage instead of Google’s LevelDB

### ISSUE THREAD

**Issue by baoquach14** [vernemq/vernemq#1989]
Hi All

Can you please let us know how to configure VerneMQ Docker container uses PostgreSQL for storage instead of Google’s LevelDB.

Thank you for your help

Regards, Bao

**Comment by ioolkos** [comment]
You cannot replace LevelDB by PostgreSQL in VerneMQ.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
