### ISSUE TITLE
No docker image for v1.12.5

### ISSUE THREAD

**Issue by nirfr** [vernemq/vernemq#1994]
The assets which were built in release 1.12.4, were not built for 1.12.5, so the Dockerfile can't be built

And - no image here for v1.12.5: https://hub.docker.com/r/vernemq/vernemq/tags

**Comment by ioolkos** [comment]
Closing as this was not built by intention.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
