### ISSUE TITLE
vernemq build output (on CentOS 7): missing functions reported. 

### ISSUE THREAD

**Issue by faiz-usmani** [vernemq/vernemq#1995]
### Environment

- VerneMQ Version: 1.12.5.x (build from master)
- OS: CentOS 7
- Erlang/OTP version (if building from source): Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] 
- VerneMQ configuration (vernemq.conf) or the changes from the default : NA
- Cluster size/standalone: NA

### Expected behavior

Would have expected the build to compile without any warnings about missing functions. 

### Actual behaviour

Cloned the VerneMQ master about a couple of weeks back, i.e. the 23rd of May. It is therefore a fairly recent clone of the repo. 
The build succeeded, but I saw what looked like warnings, as depicted below. 

```
/root/vernemq > make rel
cat vars.config > vars.generated
echo "{app_version, \"1.12.5-13-gd6644ae\"}." >> vars.generated
/root/vernemq/rebar3  release
===> Verifying dependencies...
===> Running neotoma...
===> Analyzing applications...
===> Compiling vmq_plumtree
===> Compiling vmq_webhooks
===> Compiling vmq_generic_msg_store
===> Compiling vmq_passwd
===> Compiling vmq_pulse
===> Compiling vmq_plugin
===> Compiling vmq_mqtt5_demo_plugin
===> Compiling vmq_swc
===> Compiling vmq_diversity
===> Compiling vmq_acl
===> Compiling vmq_commons
===> Compiling vmq_ql
===> Compiling vmq_server
===> Compiling vmq_bridge
make[1]: Entering directory `/root/vernemq/apps/vmq_passwd/c_src'
cc   vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
make[1]: Leaving directory `/root/vernemq/apps/vmq_passwd/c_src'
===> Running cuttlefish schema generator
===> Assembling release vernemq-1.12.5+build.13.refd6644ae...
===> There are missing function calls in the release.
===> Make sure all applications needed at runtime are included in the release.
===> vmq_ranch:mask_socket/2 calls undefined function vmq_ranch_proxy_protocol:get_csocket/1
===> vmq_swc_db_leveled:fold/5 calls undefined function leveled_bookie:book_objectfold/6
===> vmq_swc_db_leveled:init/1 calls undefined function leveled_bookie:book_start/1
===> vmq_swc_db_leveled:read/4 calls undefined function leveled_bookie:book_get/3
===> vmq_swc_db_leveled:terminate/2 calls undefined function leveled_bookie:book_close/1
===> vmq_swc_db_leveled:write/3 calls undefined function leveled_bookie:book_delete/4
===> vmq_swc_db_leveled:write/3 calls undefined function leveled_bookie:book_put/5
===> vmq_swc_db_rocksdb:fold/5 calls undefined function rocksdb:iterator/3
===> vmq_swc_db_rocksdb:fold/5 calls undefined function rocksdb:iterator_close/1
===> vmq_swc_db_rocksdb:fold/5 calls undefined function rocksdb:release_snapshot/1
===> vmq_swc_db_rocksdb:fold/5 calls undefined function rocksdb:snapshot/1
===> vmq_swc_db_rocksdb:fold_loop/5 calls undefined function rocksdb:iterator_move/2
===> vmq_swc_db_rocksdb:fold_loop/5 calls undefined function rocksdb:release_snapshot/1
===> vmq_swc_db_rocksdb:open_db/6 calls undefined function rocksdb:open_with_cf/3
===> vmq_swc_db_rocksdb:read/4 calls undefined function rocksdb:get/4
===> vmq_swc_db_rocksdb:terminate/2 calls undefined function rocksdb:close/1
===> vmq_swc_db_rocksdb:write/3 calls undefined function rocksdb:write/3
===> Release successfully assembled: _build/default/rel/vernemq

```

The questions I have are - 
- If we expect such behaviour? 
- If this leads to losing any key (or not so key) features? 
- If so, then what is the reason for the above, and how to recover from such (seemingly) warnings/issues?

**Comment by faiz-usmani** [comment]
Hello again. 

I have attempted the compilation on an Ubuntu 20.04 LTS machine as well on the code tagged 1.12.5 with the same results. 
It would be beneficial to know what these missing function calls. The fact that this is the compilation result for a released version makes it sound like it is nothing serious, but would like to understand the reason and impact of the same, if any. 

Thanks in advance.

**Comment by ioolkos** [comment]
@faiz-usmani it's maybe ugly, but nothing serious. It comes from the included RocksDB/Leveled backends to the synchronisation layer, while the actual RocksDB/Leveled packages are (intentionally) not yet part of the release.
Verne will not use those functions at runtime.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by faiz-usmani** [comment]
Many thanks for that @ioolkos. 
As long as the functionality remains uncompromised :-).
