### ISSUE TITLE
TCP max_connections not respected

### ISSUE THREAD

**Issue by furgoose** [vernemq/vernemq#1997]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: 1.12.1
- OS: Ubuntu 20.04.4 LTS
- Erlang/OTP version (if building from source): 
- VerneMQ configuration (vernemq.conf) or the changes from the default
```
allow_anonymous = on

allow_multiple_sessions = off
coordinate_registrations = on

max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_message_size = 4096

listener.nr_of_acceptors = 10

listener.tcp.default.max_connections = 2
listener.tcp.default = 127.0.0.1:1883
listener.tcp.allowed_protocol_versions = 5
```
- Cluster size/standalone: standalone

### Expected behaviour

- Please describe the expected behaviour.
- Should be limited to two connections to the broker at a time

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.
- I can connect as many clients as I want, with no observable limit

**Comment by ioolkos** [comment]
@furgoose what do the logs say? how do you test it?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@furgoose have you resolved this?

Do you might have been connecting those clients to another broker? (I see this a lot... when you test multiple MQTT brokers and have one runnning in the background. VerneMQ will log it can't start the listener on 1883 but not fail the boot). You can check listeners with `vmq-admin listener show`)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
