### ISSUE TITLE
vernemq use ssl (buy CA cert),mqtt client not connect to vernemq

### ISSUE THREAD

**Issue by jipolun** [vernemq/vernemq#1999]
- VerneMQ Version:1.12.4
- OS:ubuntu 20.04
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:1

-my web domain name is:mymqtttest.com.cn
i buy ssl cert from cloud company,so i got these files
![image](https://user-images.githubusercontent.com/16303538/172818561-d53f8b01-4397-4d13-8f9b-76277fb9c8ee.png)
so i chang the vernemq.conf:
listener.ssl.cafile = /etc/vernemq/DigiCertAssuredIDRootCA.crt
listener.ssl.certfile = /etc/vernemq/7907560_mymqtttest.com.cn.pem
listener.ssl.keyfile = /etc/vernemq/7907560_mymqtttest.com.cn.key
listener.ssl.default = 0.0.0.0:8883
i think it correct.

but this is wrong....
i use mqttx (mqtt client software)to connect the server
![image](https://user-images.githubusercontent.com/16303538/172819144-e5adfafa-c334-41d9-9fe2-0204e9a4ecaa.png)
it report error
![image](https://user-images.githubusercontent.com/16303538/172819348-45add85b-93d4-4635-b80c-37909525069c.png)
how should i do?

**Comment by jipolun** [comment]
> Please take a look at the Verne console or error logs.
> 
> 👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq 👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

thanks 
i set log.console.level = debug
so i test ssl (using CA certs)
i got these in console.log(no crash.log error.log)
`2022-06-10 08:57:40.302 [debug] <0.252.0>@vmq_swc_store:handle_info:{464,13} Replica meta3: Can't initialize AE exchange due to no peer available
2022-06-10 08:57:40.665 [debug] <0.243.0>@vmq_swc_store:handle_info:{464,13} Replica meta2: Can't initialize AE exchange due to no peer available
2022-06-10 08:57:41.194 [debug] <0.306.0>@vmq_swc_store:handle_info:{464,13} Replica meta9: Can't initialize AE exchange due to no peer available
2022-06-10 08:57:42.045 [debug] <0.234.0>@vmq_swc_store:handle_info:{464,13} Replica meta1: Can't initialize AE exchange due to no peer available
2022-06-10 08:57:42.246 [debug] <0.270.0>@vmq_swc_store:handle_info:{464,13} Replica meta5: Can't initialize AE exchange due to no peer available
2022-06-10 08:57:43.757 [debug] <0.317.0>@vmq_swc_store:handle_info:{464,13} Replica meta10: Can't initialize AE exchange due to no peer available
2022-06-10 08:57:43.800 [debug] <0.279.0>@vmq_swc_store:handle_info:{464,13} Replica meta6: Can't initialize AE exchange due to no peer available
`
（vernemq server is not work with ssl,but can work with no ssl ）

**Comment by ioolkos** [comment]
Thanks, the log you posted is unrelated to SSL and not an error.
I'm sorry I can't be of any better help.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by jipolun** [comment]
> Thanks, the log you posted is unrelated to SSL and not an error. I'm sorry I can't be of any better help.
> 
> 👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq 👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

thanks,i am try again

**Comment by ioolkos** [comment]
@jipolun could you resolve this?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
