### ISSUE TITLE
Webhook OPA Support

### ISSUE THREAD

**Issue by mr-menno** [vernemq/vernemq#2002]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

All

### Expected behaviour

- Please describe the expected behaviour.

webhook configuration option to send Open Policy Agent (OPA) compliant message. 

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

OPA enabled option will wrap the webhook in one more layer. 

`{"input": …webhook}`

**Comment by ioolkos** [comment]
@mr-menno Thanks, do you have a clear layout for the JSON request/reply, though?

I had issues aligning the JSON APis of Verne and OPA a while back, when I was looking into doing a full-blown OPA plugin.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mr-menno** [comment]
There's not requirement for specific formatting, but the top level object in the json needs to be called `input`.  The contents can be the exact same as the existing webhook.

for now, I implemented OPA with a `default_decision` which does not require the `"input":` to be part of the object.

```
package system.main

default result := "next"

# Allow admins to do anything.
# Dataset contains allowed username/passwords
result = "ok" {
    some j; data.dataset.users[j]
    data.dataset.users[j].username==input.username
    data.dataset.users[j].password==input.password
}

# For username "jwt"
result = "ok" {
    input.username == "jwt"
    response := http.send({"method": "get", "url":"https://keyserver/key", "tls_use_system_certs": true})
    io.jwt.verify_rs256(input.password,response.raw_body)
}
```

**Comment by mr-menno** [comment]
1. Correct. 
2. this would be a webhook to an OPA client running in the cluster, either as a side car container in the pod, are a daemonset service on the system. 
3. OPA can return whatever JSON needed to match MQTT.

This really means that supporting OPA, is a matter of a formatted webhook, since the webhook support in VerneMQ is already JSON. 

I can’t write erlang, but i was thinking the webhook config could be updated with a `opa_payload` option, and that should be all that’s needed. If there’s a docker image available with that option, I can put the OPA examples together for that.

**Comment by ioolkos** [comment]
@mr-menno Thanks, I think this is something I'm going to implement. 
One thing to think about is the integration into the WebHooks cache. The other whether to enable the `opa_payload` option globally, or per (named) hook.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mr-menno** [comment]
I would have it on a per named webhook option. That feels the most natural
with the current configuration.

**Comment by ioolkos** [comment]
OPA policy results and VerneMQ Webhook answers do not match, so you'll still need to generate a valid response from within your Rego script (see @mr-menno's example above). But the fix will enable sending requests to OPA with an OPA-compatible format.

OPA policy response:

```
{
    "result": true
}
```

Expected VerneMQ policy response:
```
{
    "result": "ok"
}
```
VerneMQ can also handle Webhook results like:
```
{
    "result": "next"
}
```
OR

```
{
    "result": "ok",
    "modifiers": {
        "topic": "rewritten/topic",
        "qos": 2,
        "payload": "rewritten payload",
        "retain": true
    }
```

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mr-menno** [comment]
Interesting, I’ve just been working with v1. I think it would be better to
have an integration with v1 as that is closer to what is normally expected.

I’ll try out v0 today, and connect with the OPA team on caching support.

**Comment by ioolkos** [comment]
@mr-menno Thanks, let me know if you find something on the caching support.

On, `v0`: I had missed it entirely. It's what OPA built for WebHooks:

From OPA documentation:
> Use this API if you are enforcing policy decisions via webhooks that have pre-defined request/response formats.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mr-menno** [comment]
When asked of the OPA team:

> v0 API isn't going anywhere, and v1 does not replace it. They're just
named that way 😊

> Whether to cache a decision or not, and if so for how long, is normally
for the client to decide. I guess you could provide some pointers in the
OPA response if you'd want, but HTTP headers wouldn't work I think, since
you're sending POST requests to OPA.

I’ll update with more examples tomorrow.

**Comment by mr-menno** [comment]
This might just be a documentation enhancement then.

**Comment by ioolkos** [comment]
@mr-menno thanks again for surfacing this. Yep, at this point it's basically a documentation enhancement.
Closing the issue here.
