### ISSUE TITLE
Cant build latest master on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by whendon** [vernemq/vernemq#2004]
Related issue #1991 

### Environment

- VerneMQ Version: Commit [4d08964](https://github.com/vernemq/vernemq/commit/4d08964e7f3bde4deb379fbafdb671c71a9145d2)
- OS: Ubuntu 20.04.3
- Erlang/OTP version (if building from source): Erlang/OTP 22 [erts-10.6.4]
- Cluster size/standalone: just trying to build from source on latest master (commit 4d08964)

### Expected behaviour

 - pull latest master [4d08964](https://github.com/vernemq/vernemq/commit/4d08964e7f3bde4deb379fbafdb671c71a9145d2)
 - make rel
 - vernemq builds

### Actual behaviour

- pull latest master [4d08964](https://github.com/vernemq/vernemq/commit/4d08964e7f3bde4deb379fbafdb671c71a9145d2)
- make rel
- functions are undefined and build fails
```
...
===> Compiling cowboy
===> Compiling parse_trans
===> Compiling hackney
===> Compiling c_src/syslog_drv.c
===> Linking priv/syslog_drv.so
===> Building escript for cuttlefish...
===> Compiling c_src/eleveldb.cc
===> Compiling c_src/refobjects.cc
===> Compiling c_src/threading.cc
===> Compiling c_src/workitems.cc
===> Linking /home/ubuntu/vernemq/_build/default/lib/eleveldb/priv/eleveldb.so
===> Running neotoma...
===> Analyzing applications...
===> Compiling vmq_plugin
===> Compiling vmq_webhooks
===> Compiling apps/vmq_webhooks/src/vmq_webhooks_metrics.erl failed
apps/vmq_webhooks/src/vmq_webhooks_metrics.erl:50: function atom_to_binary/1 undefined
apps/vmq_webhooks/src/vmq_webhooks_metrics.erl:51: function atom_to_binary/1 undefined
apps/vmq_webhooks/src/vmq_webhooks_metrics.erl:53: function binary_to_atom/1 undefined

make: *** [Makefile:26: rel] Error 1
```

**Comment by ioolkos** [comment]
@whendon I can build on OTP 24, but yes, last merged PR needs some minor fixing.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by varnerac** [comment]
@ioolkos See: https://github.com/vernemq/vernemq/pull/2006

**Comment by varnerac** [comment]
Actually, let me check this. May be another issue.

**Comment by varnerac** [comment]
I see why @whendon’s build fails. The `atom_to_binary/1` and `binary_to_atom/1` calls are in Erlang 23 and later. I don’t mind putting a patch up to move those to `/2` if VMQ intends to support Erlang 22 for a while.

**Comment by ioolkos** [comment]
@varnerac I see, let's add support for 22 then if it's a small effort. (then we can stay with the 3 supported release schema). Should we see additional problems with 22, we can drop support though.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by varnerac** [comment]
@ioolkos do you want me to go in and add Erlang 22 to the CI matrix?

**Comment by ioolkos** [comment]
@varnerac consequently, we should add 22 to the matrix, yes. Thanks so much.

**Comment by whendon** [comment]
Looks like that did the trick - for that specific error. Now, trying to build latest master is resulting in this:

`===> Analyzing applications...
=ERROR REPORT==== 5-Jul-2022::15:32:45.024215 ===
Error in process <0.1931.0> with exit value:
{{nocatch,
     {error,
         {rebar_compiler_erl,
             {cannot_read_file,
                 "/home/ubuntu/vernemq/_build/default/lib/plumtree/src/plumtree_peer_service.erl",
                 {redefine,nowarn_gen_fsm}}}}},
 [{rebar_compiler_erl,dependencies,4,
      [{file,"/home/runner/work/rebar3/rebar3/src/rebar_compiler_erl.erl"},
       {line,125}]},
  {rebar_compiler_dag,'-prepopulate_deps/5-fun-0-',5,
      [{file,"/home/runner/work/rebar3/rebar3/src/rebar_compiler_dag.erl"},
       {line,415}]}]}

===> Failed to get dependencies for /home/ubuntu/vernemq/_build/default/lib/plumtree/src/plumtree_peer_service.erl
{{nocatch,
     {error,
         {rebar_compiler_erl,
             {cannot_read_file,
                 "/home/ubuntu/vernemq/_build/default/lib/plumtree/src/plumtree_peer_service.erl",
                 {redefine,nowarn_gen_fsm}}}}},
 [{rebar_compiler_erl,dependencies,4,
      [{file,"/home/runner/work/rebar3/rebar3/src/rebar_compiler_erl.erl"},
       {line,125}]},
  {rebar_compiler_dag,'-prepopulate_deps/5-fun-0-',5,
      [{file,"/home/runner/work/rebar3/rebar3/src/rebar_compiler_dag.erl"},
       {line,415}]}]}
make: *** [Makefile:26: rel] Error 1`

**Comment by varnerac** [comment]
Maybe this? https://github.com/vernemq/vernemq/commit/6bd08a9b7d12de91870173f5f32dbb6aabccf343

Also, if Plumtree won’t support 22, it’s probably worth pulling 22 out of the matrix and setting/bumping the minimum version in the rebar3 config.

**Comment by whendon** [comment]
I do not think that commit is the issue, because I can successfully build 37d6b1d121d486e4243b369de5531a8b1f727528

What OTP version do you recommend?

**Comment by whendon** [comment]
I just updated Erlang/OTP to 25.0.2

Here is the new output from ```make rel```
```
===> Analyzing applications...
===> Compiling vmq_plumtree
===> Compiling vmq_webhooks
===> Compiling vmq_pulse
===> Compiling vmq_mqtt5_demo_plugin
===> Compiling vmq_diversity
===> Compiling vmq_plugin
===> Compiling vmq_generic_msg_store
===> Compiling vmq_swc
apps/vmq_swc/src/vmq_swc_peer_service_manager.erl:102:31: Warning: variable 'K' is unused

apps/vmq_swc/src/vmq_swc_store.erl:488:60: Warning: variable 'DKM' is unused
apps/vmq_swc/src/vmq_swc_store.erl:550:16: Warning: variable 'W' is unused

===> Compiling vmq_acl
===> Compiling vmq_passwd
===> Compiling vmq_commons
apps/vmq_commons/src/gen_mqtt_client.erl:166:5: Warning: gen_fsm:sync_send_all_state_event/3 is deprecated; use the 'gen_statem' module instead
apps/vmq_commons/src/gen_mqtt_client.erl:168:21: Warning: gen_fsm:sync_send_all_state_event/3 is deprecated; use the 'gen_statem' module instead

===> Compiling vmq_ql
===> Compiling vmq_server
===> Compiling vmq_bridge
make[1]: Entering directory '/home/ubuntu/vernemq/apps/vmq_passwd/c_src'
cc   vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
make[1]: Leaving directory '/home/ubuntu/vernemq/apps/vmq_passwd/c_src'
===> Running cuttlefish schema generator
===> Assembling release vernemq-1.12.5+build.20.reff08eb14...
===> There are missing function calls in the release.
===> Make sure all applications needed at runtime are included in the release.
===> vmq_ranch:mask_socket/2 calls undefined function vmq_ranch_proxy_protocol:get_csocket/1
===> vmq_swc_db_leveled:fold/5 calls undefined function leveled_bookie:book_objectfold/6
===> vmq_swc_db_leveled:init/1 calls undefined function leveled_bookie:book_start/1
===> vmq_swc_db_leveled:read/4 calls undefined function leveled_bookie:book_get/3
===> vmq_swc_db_leveled:terminate/2 calls undefined function leveled_bookie:book_close/1
===> vmq_swc_db_leveled:write/3 calls undefined function leveled_bookie:book_delete/4
===> vmq_swc_db_leveled:write/3 calls undefined function leveled_bookie:book_put/5
===> vmq_swc_db_rocksdb:fold/5 calls undefined function rocksdb:iterator/3
===> vmq_swc_db_rocksdb:fold/5 calls undefined function rocksdb:iterator_close/1
===> vmq_swc_db_rocksdb:fold/5 calls undefined function rocksdb:release_snapshot/1
===> vmq_swc_db_rocksdb:fold/5 calls undefined function rocksdb:snapshot/1
===> vmq_swc_db_rocksdb:fold_loop/5 calls undefined function rocksdb:iterator_move/2
===> vmq_swc_db_rocksdb:fold_loop/5 calls undefined function rocksdb:release_snapshot/1
===> vmq_swc_db_rocksdb:open_db/6 calls undefined function rocksdb:open_with_cf/3
===> vmq_swc_db_rocksdb:read/4 calls undefined function rocksdb:get/4
===> vmq_swc_db_rocksdb:terminate/2 calls undefined function rocksdb:close/1
===> vmq_swc_db_rocksdb:write/3 calls undefined function rocksdb:write/3
===> Release successfully assembled: _build/default/rel/vernemq
ubuntu@ip-10-0-4-193:~/vernemq$ erl version
Erlang/OTP 25 [erts-13.0.2]
```

It appears to be successful, but there is a lot of undefined functions. I'm going to attempt to run the build now and report back

**Comment by whendon** [comment]
Both the build and the runtime is successful now after updating OTP to 25.0.2, and using the latest commit on master f08eb1405d781374bd99999068ac8f276d56fbd9.

Also, this issue (my other issue) also appears to be resolved after I fixed some issues with certs, and pointed to my certs location in verne.conf #2005 .

Which means 1.12.5 is now successfully running in my production cluster and is supporting clients.

Thank you!
