### ISSUE TITLE
vmq-admin cluster show  error 

### ISSUE THREAD

**Issue by pselvam-p44** [vernemq/vernemq#2007]
Hi Team,

Am configured 3 node vernemq cluster.  am using below commands in all three nodes. 

vmq-admin cluster show only showing specific server node only.  

http://10.142.0.45:8888/status node status below attached screenshot

![Screenshot from 2022-06-23 16-22-30](https://user-images.githubusercontent.com/99006666/175282891-bafc6324-5558-443e-85a7-20a77f322008.png)
![Screenshot from 2022-06-23 16-21-34](https://user-images.githubusercontent.com/99006666/175282899-81d61506-1ad8-47ff-8c73-592152adde6a.png)
![Screenshot from 2022-06-23 16-21-10](https://user-images.githubusercontent.com/99006666/175282902-3bba68fc-0ce6-4b45-a58e-e7f61a21dc07.png)
![Screenshot from 2022-06-23 16-19-19](https://user-images.githubusercontent.com/99006666/175282907-23dd9a48-9223-4f0e-8254-7d1db298ff79.png)

**Comment by pselvam-p44** [comment]
it is correct cluster step anyone please help me on this.. ?

**Comment by ioolkos** [comment]
Yes, the `vmq-admin cluster show` command should show all 3 nodes. I don't really have a way to help you, unfortunately. 
I suppose you have issued the cluster join command on 2 of the nodes?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pselvam-p44** [comment]
> Yes, the `vmq-admin cluster show` command should show all 3 nodes. I don't really have a way to help you, unfortunately. I suppose you have issued the cluster join command on 2 of the nodes?
> 
> point_right Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq point_right Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pselvam-p44** [comment]
Hi Ioolkos,

i have resinstall and reconfigured now my cluster shows all 3 nodes.


![Screenshot from 2022-06-26 20-34-30](https://user-images.githubusercontent.com/99006666/175820692-45e22f86-3f09-4a19-bf41-6a0a8bf1df06.png)
![Screenshot from 2022-06-26 20-34-45](https://user-images.githubusercontent.com/99006666/175820701-cbf339c6-b6f8-436a-8377-836f39b6f1c6.png)
![Screenshot from 2022-06-26 20-34-54](https://user-images.githubusercontent.com/99006666/175820708-32255f12-ff3e-4846-b2cc-20bb9979e85c.png)

**Comment by pselvam-p44** [comment]
Hi ioolkos,

I have reinstall and install vernemq now all cluster are showing below.  thanks it it scorrect ?
!
![Screenshot from 2022-06-26 20-34-54](https://user-images.githubusercontent.com/99006666/175820809-f141cc24-e46e-478e-82bd-f1d276d3aeed.png)
[Screenshot from 2022-06-26 20-38-31](https://user-images.githubusercontent.com/99006666/175820805-a7be4736-746d-4889-a0b7-3f7b63457da4.png)
![Screenshot from 2022-06-26 20-38-21](https://user-images.githubusercontent.com/99006666/175820807-bd1127bb-ebf3-46a9-97c9-d8bafb7cc2b9.png)

**Comment by pselvam-p44** [comment]
![Screenshot from 2022-06-26 20-38-31](https://user-images.githubusercontent.com/99006666/175820870-65375571-04bc-45dd-827e-a41f3f694307.png)
![Screenshot from 2022-06-26 20-38-21](https://user-images.githubusercontent.com/99006666/175820871-87b15124-e311-414c-b0f3-9a223ab48e88.png)
![Uploading Screenshot from 2022-06-26 20-40-41.png…]()
