### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by codeadict** [vernemq/vernemq#2011]
### To help us save time and help you faster

Tests consistently fail locally and in CI , they have been failing in CI for quite some time. @ioolkos not sure if this is a known issue , if there is another open one feel free to close this one. Also if you have some clues or info about when this started happening, it will be great to help fix.

### Environment

- VerneMQ Version: master branch
- OS: OSX, Ubuntu Linux
- Erlang/OTP version (if building from source): 24.1 but fails on all version in Github Actions

### Expected behaviour

- CT tests fail locally and on CI

### Actual behaviour

- Run `./rebar3 ct`, will notice failures like the following which seem to be an issue with clique?:

```erlang
vmq_cluster_SUITE ==> {{badmatch,
     {badrpc,
         {'EXIT',
             {{badarity,
                  {#Fun<vmq_config_cli.11.101367952>,
                   [["shared_subscription_policy"],"random"]}},
              [{clique_config,run_callback,3,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_config.erl"},
                    {line,268}]},
               {clique_config,'-run_callback/1-lc$^1/1-1-',4,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_config.erl"},
                    {line,259}]},
               {clique_config,run_callback,1,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_config.erl"},
                    {line,259}]},
               {clique_config,set,2,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_config.erl"},
                    {line,142}]},
               {clique_command,run,1,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/_build/default/lib/clique/src/clique_command.erl"},
                    {line,87}]},
               {vmq_server_cli,command,2,
                   [{file,
                        "/Users/codeadict/Hack/vernemq/apps/vmq_server/src/vmq_server_cli.erl"},
                    {line,41}]},
               {vmq_server_cmd,set_config,2,[]}]}}}},
 [{vmq_cluster_SUITE,'-set_shared_subs_policy/2-fun-0-',2,
      [{file,
           "/Users/codeadict/Hack/vernemq/apps/vmq_server/test/vmq_cluster_SUITE.erl"},
       {line,904}]},
```

**Comment by ioolkos** [comment]
@codeadict Thanks, the local failings look new to me. (not talking about the CI ones). But yes, I can reproduce the local ones; something we need to investigate.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
There must have been a breaking change in the commit history, related to the ETS-stored clique Callbacks.

```
(dev0@127.0.0.1)1> vmq_server_cmd:set_config(shared_subscription_policy, "prefer_local").
** exception error: vmq_config_cli:'-fun.register_config_callback/3-'/3 called with two arguments
```

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
It's a little bit of a mess.
The reason is the updated `clique` dependency. The main differences are in `clique_config.erl`.
Old version, for which the internal VerneMQ API was built:
https://github.com/vernemq/clique/blob/rel_0.3.6-verne/src/clique_config.erl

The `run_callback` function works slightly differently in the currently locked (updated) `clique` dependency.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by codeadict** [comment]
I see now @ioolkos , i'll try fixing this before sending my formatting PR :)

**Comment by ioolkos** [comment]
@codeadict Awesome! 

I tried a simple 2-arity callback in `vmq_config_cli`:

```erlang
register_config_callback([StrKey], _) ->
    Key = list_to_existing_atom(StrKey),
    {ok, Val} = application:get_env(vmq_server, Key),
    vmq_config:set_env(vmq_server, Key, Val, false),
    vmq_config:configure_node().
```
Ultimately, the "set" will be handled by this clique command spec:

```erlang
-define(SET_CMD_SPEC, {["_", "set"], '_', clique_config:config_flags(),
                       fun (_, SetArgs, SetFlags) ->
                               clique_config:set(SetArgs, SetFlags)
                       end}).
```
but somehow the clique printer trips over the `[ok,ok,ok]` below (no clue where it comes from):
```
(VerneMQ@127.0.0.1)55> MM = clique_config:do_set([{"shared_subscription_policy", "prefer_local"}]).
{'VerneMQ@127.0.0.1',[["shared_subscription_policy",32,115,
                       101,116,32,116,111,32,"\"prefer_local\""],
                      10,
                      [ok,ok,ok]]}
```

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by codeadict** [comment]
The ok ok ok comes from each node the config is applied, this is the new behavior in clique, it run the callback in every node if -all is given to the command and returns the result for each node.

**Comment by ioolkos** [comment]
What's funny is that I did the tests on a single node, but apparently clique found 2 other Verne nodes running on my local machine (non clustered). Therefore [ok ok ok]. :)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
