### ISSUE TITLE
no_matching_hook_found error without using authentication

### ISSUE THREAD

**Issue by goat-solutions** [vernemq/vernemq#2016]
- VerneMQ Version: 1.12.4
- OS: Ubuntu 20.04.1

### Expected behaviour

Connecting and publishing topics to a server without authentication.

### Actual behaviour

I'm having a problem trying to publish a topic, causing my client to disconnect. I can successfully connect, the error only occurs when trying to publish.

I got the below error from the log which is in `/var/log/vernemq/error.log`.

> 2022-07-09 11:32:36.106 [error] <0.1050.0>@vmq_mqtt_fsm:auth_on_publish:{739,13} can't auth publish [<<>>,{[],<<"mqtt-explorer" >>},1,[<<"furnace">>],<<"1">>,false] due to no_matching_hook_found

I'm doing authentication without username and password, and I enabled the `allow_anonymous` parameter in the `vernemq.conf` file.

**Comment by ioolkos** [comment]
@goat-solutions You have disabled authentication, but this doesn't mean you do not need an authorization plugin. You can't switch off authorization actually;  VerneMQ will always need an authorization plugin running. (authorization is for `auth_on_publish` and `auth_on_subscribe`).

Enable and configure the `vmq.acl` plugin, as a minimum.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
