### ISSUE TITLE
What does it mean if you see Msq Queued

### ISSUE THREAD

**Issue by JacoFourie** [vernemq/vernemq#2017]
Hi.

Sorry for the dumb question. I see I get Msg Queued of 5 - 11 from time to time after I restart the service. What does it mean if that count is not 0 and how can I change it so that it does not become more than 0? Also, it never drops down, is that a high water mark counter?

**Comment by JacoFourie** [comment]
@ioolkos thanks for the reply. I don't understand what the metric means. I do not have any clients that should have messages queued or saved to disk. If that is not 0 what does it mean?

**Comment by JacoFourie** [comment]
@ioolkos why would that number not be 0. How does VenMQ decide to add to that counter?

**Comment by ioolkos** [comment]
@JacoFourie sorry for not responding earlier. There's a "known unknown" issue in this counter & there's other Github issues on it. 
Looks like you hit that. 
(of course, we *should* not present wrong information in a status page...)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by JacoFourie** [comment]
@ioolkos ok so I can ignore it then?

**Comment by ioolkos** [comment]
@JacoFourie I'm not omniscient & I don't know your use case :), but yes, you can very likely just ignore it at the moment.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
