### ISSUE TITLE
Publishing messages from the HTTP API

### ISSUE THREAD

**Issue by AmirOsman2020** [vernemq/vernemq#2018]
I've been using VerneMQ for a while, it's one of the best MQTT brokers I've used however the lack of publishing messages from the HTTP API is really frustrating.
I need to publish MQTT messages from my backend to the client after a specific job is done and this requires publishing messages from the HTTP API, Currently am using the open source version of emqx, it allows publishing messages from the HTTP API, We would love to have this feature in VerneMQ, since its fully open source, unlike emqx some features require the enterprise version.

**Comment by ioolkos** [comment]
@AmirOsman2020 
I'm not against improving the existing HTTP layer, or even adding specific features like a publish option. Internally, this has low priority; but I'm happy to review PR's if anyone wants to have a go at the HTTP publish call.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by drasko** [comment]
@AmirOsman2020 for multi-protocol bridge you can take a look at [Mainflux](https://github.com/mainflux/mainflux). It adds HTTP adapter on top of VerneMQ (or any other MQTT broker), as well as WebSocket, CoAP and other protocols. It also adds user management, grouping, authorization layer, storage layer, message transformation and many other features needed for an enterprise IoT system.

**Comment by AmirOsman2020** [comment]
This is interesting, I will try it out, Thanks for the help.

**Comment by boboxiaodd** [comment]
If you can use Erlang，it's very easy ,
```erlang
rpc:cast(MQTTNode, vmq_reg, subscribe, [true, SubscriberId, NewTopics]),
rpc:call(MQTTNode, vmq_reg, unsubscribe, [true, SubscriberId, NewTopics]),
rpc:call(MQTTNode, vmq_reg, publish, [true, vmq_reg_trie, VmqMsg]), 
```

**Comment by AmirOsman2020** [comment]
> If you can use Erlang，it's very easy , 
> use cowboy to create an http server , and connect to Vernemq node ,do everyting.
> ```erlang
> rpc:cast(MQTTNode, vmq_reg, subscribe, [true, SubscriberId, NewTopics]),
> rpc:call(MQTTNode, vmq_reg, unsubscribe, [true, SubscriberId, NewTopics]),
> rpc:call(MQTTNode, vmq_reg, publish, [true, vmq_reg_trie, VmqMsg]), 
> ```

I didn't know this is possible, sounds great, can you provide a full details on how to achieve this?

**Comment by boboxiaodd** [comment]
@AmirOsman2020  
https://github.com/boboxiaodd/web_agent
