### ISSUE TITLE
vernemq does not respond to pings, vmq-admin not working

### ISSUE THREAD

**Issue by henningw** [vernemq/vernemq#2020]
I have done a research in the bug tracker about that, but only found #1217. I do not think this applies here, as its a fresh installation on a new environment. Any help is appreciated. This is own docker image build from the official vernemq docker sources.

### Environment

- VerneMQ Version: :1.12.5.1 
- OS: CentOS Linux release 7.9.x (host), Debian bullseye-slim (docker image)
- Erlang/OTP version (if building from source): Erlang 24
- VerneMQ configuration:
```
   vernemq@63bb05979503:~$ grep tmp-dev2-mqtt.domain.com /vernemq/etc/*
   /vernemq/etc/vernemq.conf:nodename = VerneMQ@tmp-dev2-mqtt.domain.com
   /vernemq/etc/vernemq.conf.local:nodename = VerneMQ@tmp-dev2-mqtt.domain.com
   /vernemq/etc/vm.args:-name VerneMQ@tmp-dev2-mqtt.domain.com
```
- Cluster size/standalone: standalone

### Expected behaviour

- vmq-admin tool should work, ping and other commands should work

### Actual behaviour

- vmq-admin tool does not work, ping and other commands does not work
```
[root@tmp-dev2-mqtt1]# docker exec -it tmp-cloud-vernemq-service bash
vernemq@63bb05979503:~$ vmq-admin
Node 'VerneMQ@tmp-dev2-mqtt.domain.com' not responding to pings.
vernemq@63bb05979503:~$ vmq-admin ping
Node 'VerneMQ@tmp-dev2-mqtt.domain.com' not responding to pings.
```

### Remarks
The dev vernemq seems to work, MQTT packets are processed in the limited tests. But without the admin tool its of course not really usable, so no further tests has been done so far. Output from ps shown below:
```
vernemq@63bb05979503:~$ ps aux |grep vernemq
vernemq       1  0.0  0.0   3820   980 ?        Ss   Jul04   0:00 bash /usr/sbin/start_vernemq
vernemq      76  0.3 24.1 4858664 450100 ?      Sl   Jul04 144:59 /vernemq/bin/../erts-12.3.1/bin/beam.smp -P 256000 -A 64 -K true -W w -zdbbl 32768 -- -root /vernemq/bin/.. -progname vernemq -- -home /vernemq -- -boot /vernemq/bin/../releases/1.12.5/vernemq -config /vernemq/data/generated.configs/app.2022.07.04.07.53.42.config -setcookie XXXXXXX -name VerneMQ@tmp-dev2-mqtt.domain.com -smp enable -- -vm_args /vernemq/bin/../etc/vm.args -pa /vernemq/bin/../lib/erlio-patches -- console -noshell -noshell -noinput --
vernemq     136  0.0  0.1   5620  2420 ?        S    Jul04   0:54 /vernemq/bin/../erts-12.3.1/bin/epmd -daemon
vernemq     267  0.0  0.0   2292   356 ?        Ss   Jul04   0:00 erl_child_setup 1048576
vernemq     296  0.0  0.0   2404   644 ?        Ss   Jul04   0:00 sh -s disksup
vernemq     298  0.0  0.0   2156   356 ?        Ss   Jul04   0:03 /vernemq/bin/../lib/os_mon-2.7.1/priv/bin/memsup
vernemq     299  0.0  0.0   2288   352 ?        Ss   Jul04   5:45 /vernemq/bin/../lib/os_mon-2.7.1/priv/bin/cpu_sup
vernemq     386  0.0  0.0   3636   464 ?        Ss   Jul04   0:00 inet_gethost 4
vernemq     387  0.0  0.0   3636   300 ?        S    Jul04   0:00 inet_gethost 4

```

**Comment by ioolkos** [comment]
@henningw either a wrong cookie in vm.args; or the build itself went wrong.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by henningw** [comment]
@ioolkos thanks you for the reply. It turned out that the build was fine, and also the cookie was not the problem. The problem was the configured name for the VerneMQ, which pointed to an external IP, which was not reachable from the docker container inside. 
I have changed this name to the internal one and also added it to the docker host file. Now it works.
