### ISSUE TITLE
VerneMQ SSL Server and Client Certificate authentication

### ISSUE THREAD

**Issue by pselvam-p44** [vernemq/vernemq#2022]
Hi Team,

I have configured the VerneMQ server using Auth file & SSL.   VerneMQ Vesion 1.12.4

1. Using VerneMQ Auth files authentication vmq,passwd is working fine am able to pub/sub the server.  
    CMD :  mosquitto_pub -h IPADDRESS  -u $user -P $password -p 8883 -t driveby -m "HI!"

2. After enabling the SSL option in the VernemQ server. try to connect using the client key & vmq.passwd authentication from my device it working fine  (--cafile vernemq_ca.crt --key client.key --cert client.crt) disabled listener.ssl.use_identity_as_username = off this option in vernemq.conf configuration.

mosquitto_pub -h IPADDRESS  -u $user -P $password -p 8883 -t driveby -m "HI!" --cafile vernemq_ca.crt --key client.key --cert client.crt

3. I have disabled auth files authentication option in vernemq server. try to connect using client key from the device. (enabled listener.ssl.use_identity_as_username = on this option in vernemq.conf configuration.
 ) I got the below error vernemq server & publish.

CMD : mosquitto_pub -h serverip -p 8883 -t driveby -m "HI!" --cafile vernemq_ca.crt --key client.key --cert client.crt 

From the Device & Mosquito client error : Connection error: Connection Refused: not authorised.
From Server Logs :-  can't authenticate client {[],<<"mosq-kHrRZinW56aTbCSTPD">>} from  due to no_matching_hook_found

4. Note: Same Server and Client key working fine in Mosquitto server. am able to pub/sub the topic using SSL in mosquito. 

CMD : mosquitto_pub -h serverip -p 8883 -t driveby -m "HI!" --cafile vernemq_ca.crt --key client.key --cert client.crt 

Mosquitto Configuration :- 

pid_file /var/run/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/
log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
allow_anonymous false
port 1883
port 8883
cafile /etc/mosquitto/certs/ca.crt
keyfile /etc/mosquitto/certs/server.key
certfile /etc/mosquitto/certs/server.crt
tls_version tlsv1.2
use_identity_as_username true
require_certificate true

Below Configuration am using for VerneMQ SSL authentication:- 

accept_eula = yes
allow_anonymous = off
retry_interval = 20
max_client_id_size = 100
max_inflight_messages = 0
max_online_messages = 99999
max_offline_messages = 99999
max_message_size = 0
listener.max_connections = 10000
listener.tcp.default = 0.0.0.0:1883
listener.ssl.default = 0.0.0.0:8883
listener.tcp.allowed_protocol_versions = 3,4,5
listener.ssl.allowed_protocol_versions = 3,4,5
listener.vmq.clustering = 10.142.0.109:44053
listener.http.default = 10.142.0.109:8888
listener.ssl.cafile = /etc/vernemq/vernemq_ca.crt
listener.ssl.certfile = /etc/vernemq/vernemq.crt
listener.ssl.keyfile = /etc/vernemq/vernemq.key
listener.ssl.tls_version = tlsv1.2
listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on
plugins.vmq_passwd = off
plugins.vmq_acl = off
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
#vmq_passwd.password_file = /etc/vernemq/vmq.passwd
#vmq_passwd.password_reload_interval = 10
nodename = VerneMQDev2@10.142.0.109
distributed_cookie = vmq
log.console = file
log.console.level = debug
log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
erlang.async_threads = 64
erlang.max_ports = 262144
~

**Comment by ioolkos** [comment]
@pselvam-p44 
a couple of  hints: 
- VerneMQ always needs an authorization plugin enabled. You have switched off all authorization plugins.
- You can disable all authentication plugins, by setting `allow_anonymous=on`. To use client certs *only* (as a means of identifying your client), you actually have to disable (MQTT) authentication, or use an authentication plugin for authentication of MQTT username/password alongside the client cert. In other words: the 2-factor authentication (if I may call it that) is meant to be the default.

In master, you can set `allow_anonymous_override` to switch off authentication on a per listener basis, instead of switching it off globally.



---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pselvam-p44** [comment]
@ioolkos am using Ubuntu 20.04 Installed *.deb packages 1.12.4 version.  same version it will work ?

**Comment by ioolkos** [comment]
@pselvam-p44 `allow_anonymous_override` is not in 1.12.4. (Consult Changelog).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pselvam-p44** [comment]
@ioolkos when it includes allow_anonymous_override *.deb packages. ?

**Comment by ioolkos** [comment]
`allow_anonymous_override` was added in Release 1.12.5. 

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
