### ISSUE TITLE
How to install VerneMQ in Jetson?

### ISSUE THREAD

**Issue by Eldho1416** [vernemq/vernemq#2023]
I'm using Jetson nano with Jetpack 4.6.1 (OS I'm using is Ubuntu 18.04.6 LTS (GNU/Linux 4.9.253-tegra aarch64)) and I'm not able to install VerneMQ because of architectural change, is there any docker image for this?

**Comment by ioolkos** [comment]
@Eldho1416 There's no Docker image for aarch64 currently.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by Eldho1416** [comment]
Is there any docker image for arm64?

**Comment by ioolkos** [comment]
@Eldho1416 arm64=aarch64, so no.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
