### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by urechi** [vernemq/vernemq#2025]
Hey,

Is this project abandoned? It looks like I can't build my own docker image anymore due to several issues. I was looking for alternatives and I found [EMQX](https://github.com/emqx/emqx), I could bet that they've started by copying VerneMQ and built on top of it. Are there any connections?

**Comment by ioolkos** [comment]
@urechi LoL.
VerneMQ is alive and kicking. Completely unrelated to EMQX.
Why don't you help and fix what doesn't seem to work for you?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
