### ISSUE TITLE
Auto scaling in k8s cluster

### ISSUE THREAD

**Issue by janiu-001** [vernemq/vernemq#2030]
Hi Expert, 

Just wanna confirm how could we support auto scaling in k8s cluster? Very appreciated for your response

Br
Baoke

**Comment by ioolkos** [comment]
@janiu-001 I have no shortcut advice for you regarding autoscaling. It is possible but Verne is a stateful service, so syncronisation has to happen when a node leaves or joins a cluster.
Usually, my recommendation is to go with a fixed size cluster.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by janiu-001** [comment]
Thanks very much for your quick response.

Would you like to simple introduce the mechanism ? 

And Would you like to share the documentation about the auto scaling, the procedure, the disadvantage...etc?

**Comment by ioolkos** [comment]
@janiu-001 
Starting point:
https://docs.vernemq.com/guides/vernemq-on-kubernetes
Also, see the doc/Readme in the `docker-vernemq` repository. 

Improvements welcome.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
