### ISSUE TITLE
Feature Request: vmq_diversity.postgres table name config option

### ISSUE THREAD

**Issue by kevindierkx** [vernemq/vernemq#2032]
In our setup we manage the auth/acl with a dedicated application, for consistency our table names follow the same naming convention as our ORM models. At the moment it isn't possible to change the default table name for the `vmq_auth_acl` in VerneMQ.

### Environment

- VerneMQ Version: 1.12.4
- OS: Debian 11
- Cluster size/standalone: standalone

### Expected behaviour

- A config option for changing the default `vmq_auth_acl` table name to something else.

### Actual behaviour

- The option is not available.

**Comment by ioolkos** [comment]
@kevindierkx Thanks... not sure this is of general interest, though. You can adapt the hard coded table name in the Lua scripts anyway.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
