### ISSUE TITLE
helm installation failed on micro-k8s

### ISSUE THREAD

**Issue by gitshelmi** [vernemq/vernemq#2033]
Not sure if it's a bug or I am doing something wrong.
I have micro-k8s and helm installed.

Then followed the instructions here: https://hub.docker.com/r/vernemq/vernemq/
- first added vernemq repo to helm: `helm repo add vernemq https://vernemq.github.io/docker-vernemq`
- then tried to install it using `helm install vernemq vernemq/vernemq`

but got this error: 
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].envFrom): invalid type for io.k8s.api.core.v1.Container.envFrom: got "map", expected "array"`

**Comment by DominikBasnerSotec** [comment]
The Helm Release is broken, since the operator etc. all rely on old k8s files

**Comment by ioolkos** [comment]
I think this should work (release 1.12.6.x). Let me know if not.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
