### ISSUE TITLE
"TLS client: In state cipher received SERVER ALERT: Fatal - Handshake Failure" on a vernemq cluster

### ISSUE THREAD

**Issue by RajeshPonnusamy** [vernemq/vernemq#2039]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: 1.12.4
- OS: RHEL
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
listener.tcp.listener1 = <Node2_IP>:1893
listener.tcp.listener1.allowed_protocol_versions = 3,4,5
listener.tcp.listener1.max_connections = 10000
listener.tcp.listener1.nr_of_acceptors = 10
erlang.distribution.port_range.minimum = 6000
erlang.distribution.port_range.maximum = 7999
listener.vmqs.keyfile = /etc/vernemq/certs/server.key
listener.vmqs.certfile = /etc/vernemq/certs/server.crt
listener.vmqs.cafile = /etc/vernemq/certs/ca.crt
#listener.vmqs.crlfile
#listener.vmqs.ciphers
#listener.vmqs.eccs = [brainpoolP384r1, secp384r1, sect283k1]
listener.vmqs.require_certificate = on
listener.vmqs.tls_version = tlsv1.2
listener.vmqs.clustering = <Node2_IP>:18884
listener.ssl.cafile = /etc/vernemq/certs/ca.crt
listener.ssl.certfile = /etc/vernemq/certs/server.crt
listener.ssl.keyfile = /etc/vernemq/certs/server.key
listener.ssl.depth = 2
listener.ssl.require_certificate = on
listener.ssl.default = <Node2_IP>:8883
#listener.wss.default = <Node2_IP>:880
listener.ssl.tls_version = tlsv1.2

- Cluster size/standalone: cluster of 2 nodes

### Expected behaviour

The cluster communication has to happen after the TLS handshake is successful

### Actual behaviour

2022-09-25 22:13:55.966 [debug] <0.240.0>@plumtree_broadcast:exchange:{520,22} started plumtree_metadata_manager exchange with 'VerneMQ@<IP>' (<0.1423.0>)
2022-09-25 22:13:55.968 [debug] <0.1423.0>@plumtree_metadata_exchange_fsm:exchange:{170,21} completed metadata exchange with 'VerneMQ@<IP>'. nothing repaired
2022-09-25 22:13:55.973 [debug] <0.240.0>@plumtree_broadcast:schedule_lazy_tick:{720,13} 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
2022-09-25 22:13:56.086 [warning] <0.1435.0>@vmq_cluster_node:connect_async:{312,21} can't connect to cluster node 'VerneMQ@<IP>' due to {tls_alert,{handshake_failure,"**TLS client: In state cipher received SERVER ALERT: Fatal - Handshake Failure**\n"}}

Following are the ciphers available:

[root@ certs]# vernemq attach
Last login: Mon Sep 26 03:17:45 IST 2022 on pts/2
Remote Shell: Use "Ctrl-G q" to quit.
q() or init:stop() will terminate the vernemq node.
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Eshell V12.2  (abort with ^G)
(VerneMQ@10.99.36.252)1> rp(vmq_ssl:opts([])).
[{cacertfile,undefined},
 {certfile,undefined},
 {keyfile,undefined},
 {ciphers,["ECDHE-ECDSA-AES256-GCM-SHA384",
           "ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384",
           "ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA",
           "ECDH-ECDSA-AES256-GCM-SHA384","ECDH-RSA-AES256-GCM-SHA384",
           "ECDH-ECDSA-AES256-SHA384","ECDH-RSA-AES256-SHA384",
           "DHE-DSS-AES256-GCM-SHA384","DHE-DSS-AES256-SHA256",
           "AES256-GCM-SHA384","AES256-SHA256",
           "ECDHE-ECDSA-AES128-GCM-SHA256",
           "ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256",
           "ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256",
           "ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256",
           "ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256",
           "DHE-DSS-AES128-SHA256","AES128-GCM-SHA256","AES128-SHA256",
           "ECDHE-ECDSA-AES256-SHA","ECDHE-RSA-AES256-SHA",
           "DHE-DSS-AES256-SHA","ECDH-ECDSA-AES256-SHA",
           "ECDH-RSA-AES256-SHA","AES256-SHA","ECDHE-ECDSA-AES128-SHA",
           "ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA",
           "ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA","AES128-SHA"]},
 {eccs,[secp521r1,secp384r1,secp256k1,secp256r1]},
 {fail_if_no_peer_cert,false},
 {verify,verify_none},
 {verify_fun,{#Fun<vmq_ssl.0.79848526>,no_crl}},
 {depth,1},
 {versions,['tlsv1.2']}]
ok

Once cluster is established the above error is printed continuously on all the nodes, in our case two nodes

**Comment by ioolkos** [comment]
@RajeshPonnusamy You might want to try release 1.12.6. 
I think there was a regression/bug regarding `vmqs` introduced before (haven't looked up the details).
Alternatively, non-encrypted message exchange between the cluster nodes (`vmq`).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by RajeshPonnusamy** [comment]
Thank you for looking into the issue and sharing the details @ioolkos, I couldn't find 1.12.6 in the downloads, assuming it is upcoming, if it is available as beta could you please share the location?

**Comment by RajeshPonnusamy** [comment]
Hi @ioolkos  we are installing vernemq on RHEL but we are not able locate the RHEL/CentOS distributions in https://github.com/vernemq/vernemq/releases/tag/1.12.6, appreciate you help on this regard!

**Comment by ioolkos** [comment]
@RajeshPonnusamy Rocky is the new Centos ;)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
