### ISSUE TITLE
metrics error after upgrade to 1.12.6 with webhook plugin enabled

### ISSUE THREAD

**Issue by andrewsaputra** [vernemq/vernemq#2040]
### Environment

- VerneMQ Version: 1.12.6
- OS: Ubuntu 20.04
- Erlang/OTP version (if building from source): 24.3.3
- VerneMQ configuration (vernemq.conf) or the changes from the default
```
allow_anonymous = off
allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = on
persistent_client_expiration = 1w
listener.max_connections = 1000000
listener.nr_of_acceptors = 1000
listener.tcp.allowed_protocol_versions = 5
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 127.0.0.1:44053
listener.http.default = 0.0.0.0:8888
metadata_plugin = vmq_swc
distributed_cookie = tvlk-vmq
leveldb.maximum_memory.percent = 60
nodename = VerneMQ@127.0.0.1
erlang.distribution.port_range.minimum = 6000
erlang.distribution.port_range.maximum = 7999
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_webhooks = on
vmq_webhooks.verify_peer = off
vmq_webhooks.register.hook = auth_on_register_m5
vmq_webhooks.register.endpoint = <url>
vmq_webhooks.publish.hook = auth_on_publish_m5
vmq_webhooks.publish.endpoint = <url>
vmq_webhooks.subscribe.hook = auth_on_subscribe_m5
vmq_webhooks.subscribe.endpoint = <url>
```
- Cluster size/standalone: standalone

### Expected behaviour
Metrics shown when  `localhost:8888/metrics` is invoked

### Actual behaviour
error with log :
> 2022-09-28 20:19:11.107 [error] <0.2555.0>@vmq_metrics_http:prometheus_output:105 Cowboy stream 1 with ranch listener {{0,0,0,0},8888} and connection process <0.2554.0> had its request process exit with reason: bad argument in call to erlang:atom_to_binary(<<"Number of bytes sent to on_client_gone webhooks">>, utf8) in vmq_metrics_http:prometheus_output/2 line 105

The webhook url itself seems to still be invoked properly.
Metrics works again if `plugins.vmq_webhooks` setting is set to `off` .

This used to work on 1.12.5 .

**Comment by ioolkos** [comment]
@andrewsaputra Thanks. Webhooks metrics collection was added in 1.12.6. (@varnerac might be of interest to you, since you implemented it).
I'll look into it too; seems to be a format issue as we call a `to-binary` function on a binary.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by varnerac** [comment]
I'll look this afternoon

**Comment by varnerac** [comment]
See https://github.com/vernemq/vernemq/pull/2043

**Comment by ioolkos** [comment]
Fixed by https://github.com/vernemq/vernemq/pull/2043

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
