### ISSUE TITLE
Is there a way in VerneMQ to add delay between sending messages to different topics one by one?

### ISSUE THREAD

**Issue by maajidz** [vernemq/vernemq#2044]
I want to be able to send a message eg "New Ride" to Topic 1, Topic 2, and Topic 3 one by one with a delay of lets say 3 seconds in between them. Is there a way in VerneMQ inbuilt that can deal with this?

**Comment by ioolkos** [comment]
@maajidz This definitely looks like client-side logic to me, not something a server should enable. The use case (and maybe ordering guarantees) you are looking at is unclear to me.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by maajidz** [comment]
I'm planning to send the drivers the new ride notification, but each of them gets this notification after a delay of 3 seconds in between in the order of the ascending distance from the customer. That's the use case.

**Comment by ioolkos** [comment]
@maajidz I see. That's not something Verne would support. Client side business logic (sending the messages individually).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
