### ISSUE TITLE
VerneMQ Webhook Unsubscribe not working

### ISSUE THREAD

**Issue by syedzahidulla** [vernemq/vernemq#2051]
I have configured vernemq with webhooks everyhting works as expected apart from unsubscribe hook.

<img width="693" alt="error" src="https://user-images.githubusercontent.com/38484785/200243924-15d1b296-77fe-434f-9a4e-b8336e611ed2.PNG">
[
<img width="762" alt="error1" src="https://user-images.githubusercontent.com/38484785/200244143-e43644be-8dd3-42d6-916e-1b09b17bbd94.PNG">
](url)

**Comment by ioolkos** [comment]
Closing in favour of: https://github.com/vernemq/vernemq/issues/2036
