### ISSUE TITLE
Password file not reloading

### ISSUE THREAD

**Issue by andygrillo** [vernemq/vernemq#2055]
### Environment

- VerneMQ Version:   1.12.6.1
- OS: ubuntu 20.04
- VerneMQ configuration (vernemq.conf):
```
allow_anonymous = off
plugins.vmq_passwd = on
plugins.vmq_webhooks = on
plugins.vmq_acl = on
vmq_passwd.password_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
```

When I add a user:password to the file ` /etc/vernemq/vmq.passwd` and wait 10 or more seconds, the user is not authenticated. I need to run `sudo service vernemq restart`, and then the user is able to authenticate on restart.

How do I get VerneMQ to read the file without restarting ?

**Comment by ioolkos** [comment]
@andygrillo do you add a user like this: `vmq-passwd  /etc/vernemq/vmq.passwd henry` ? Do you see the users added to the file when you `cat` it? maybe file permissions?

The reload should work, it'd be a weird regression if not.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
