### ISSUE TITLE
vmq-admin set leads to RPC failed

### ISSUE THREAD

**Issue by bbergshaven** [vernemq/vernemq#2060]
### Environment

- **VerneMQ Version:** 
    1.12.6.2
- **OS:** 
    macOS Monterey Docker Engine 20.10.12
- **Erlang/OTP version:** 
    ARG VERNEMQ_VERSION="1.12.6.2"
    FROM erlang:23.0 as BUILD
- **VerneMQ configuration (vernemq.conf) or the changes from the default**
      - DOCKER_VERNEMQ_PLUGINS.vmq_acl=off
      - DOCKER_VERNEMQ_PLUGINS.vmq_webhooks=on
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS.auth_register.hook=auth_on_register
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS.auth_register.endpoint=http://host.docker.internal:8090/
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS.auth_subscribe.hook=auth_on_subscribe
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS.auth_subscribe.endpoint=http://host.docker.internal:8090/
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS.auth_publish.hook=auth_on_publish
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS.auth_publish.endpoint=http://host.docker.internal:8090/ 
- **Cluster size/standalone:**
    Standalone
### Expected behaviour
Config set for single node

### Actual behaviour
```

vernemq@35602f04f6a3:/$ vmq-admin set persistent_client_expiration=1h
RPC to 'VerneMQ@172.27.0.2' failed: {'EXIT',
                                     {badarg,
                                      [{io,format,
                                        [<0.65.0>,"~ts",
                                         [[["persistent_client_expiration",32,
                                            115,101,116,32,116,111,32,
                                            "\"1h\""],
                                           10,
                                           [ok,ok],
                                           10]]],
                                        []},
                                       {clique,print,3,
                                        [{file,
                                          "/build/vernemq/_build/default/lib/clique/src/clique.erl"},
                                         {line,120}]},
                                       {clique,print,2,
                                        [{file,
                                          "/build/vernemq/_build/default/lib/clique/src/clique.erl"},
                                         {line,95}]},
                                       {vmq_server_cli,command,1,[]}]}}
```

**Comment by ioolkos** [comment]
Can confirm we broke the function of dynamically setting values (`vmq-admin set`). This is also in the official binary package.
Will see how to best fix this, it's a `clique` thing.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@bbergshaven note that the actual values will still get set. It is only the printing of output to the console that fails here.

You can verify by `vmq-admin show persistent_client_expiration`, as an example.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
