### ISSUE TITLE
Vernemq storing data inconsistently across all nodes in cluster.

### ISSUE THREAD

**Issue by jibsonline1** [vernemq/vernemq#2063]
### To help us save time and help you faster

Before opening a new issue, please make sure that there isn't already an open (or closed/resolved) issue reporting the same problem. Please always open a new issue rather than posting to a closed one - but please reference the possibly related old issue.

Please do not insert images of text, but add the text instead.

### Environment

- VerneMQ Version: 1.11.0
- OS: DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default

`allow_anonymous = off

## Netsplits
allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = on

## Sessions
allow_multiple_sessions = on
coordinate_registrations = off
retry_interval = 20

## Client
max_client_id_size = 100
max_inflight_messages = 1
max_online_messages = 10
max_offline_messages = 0
max_message_size = 0
upgrade_outgoing_qos = off
queue_deliver_mode = fanout

# Max message rate
max_message_rate = 10
max_drain_time = 20
persistent_client_expiration = 1h

## Listners
listener.max_connections = infinity
listener.nr_of_acceptors = 20000
listener.http.default = 10.28.232.223:8888
listener.ws.default = 10.28.232.223:9001
listener.tcp.default = 10.28.232.223:1883
listener.tcp.allowed_protocol_versions = 3,4,5
listener.vmq.clustering = 10.28.232.223:44053

## Systree Reporter
systree_enabled = on
systree_interval = 20000

## Graphite
graphite_enabled = off

## Shared subscription policy
shared_subscription_policy = prefer_local

## Plugins
plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = on
plugins.vmq_bridge = off
metadata_plugin = vmq_swc

## ACL
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10

## Logging
log.console = file
log.console.level = info
log.console.file = /vernemq/logs/console.log
log.error.file = /vernemq/logs/error.log
log.syslog = off
log.crash = on
log.crash.file = /vernemq/logs/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5

## Node Settings
nodename = VerneMQ
distributed_cookie = WMT-SS-PTT-VMQ
erlang.async_threads = 1024
erlang.max_ports = 524288
leveldb.maximum_memory.percent = 10
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
erlang.schedulers.compaction_of_load = true
erlang.schedulers.utilization_balancing = true
erlang.distribution_buffer_size=32MB

## WEBHOOKS
vmq_webhooks.offlinehook.hook = on_client_offline
vmq_webhooks.offlinehook.endpoint = <url>/offline

vmq_webhooks.gonehook.hook = on_client_gone
vmq_webhooks.gonehook.endpoint = <url>/offline

vmq_webhooks.authhook.hook = auth_on_register
vmq_webhooks.authhook.endpoint =  <url>authenticate`

- Cluster size/standalone: 9 nodes

### Expected behaviour

- Please describe the expected behaviour.

data should be distributed equally across all nodes.

### Actual behaviour

in some of the nodes, data directory is having data in the range of 50-300 mb where as in other it is having 1GB to 2GB

- Please include minimal steps to reproduce the issue, if possible.

**Comment by ioolkos** [comment]
@jibsonline1 Thanks, it's hard to tell whether this points to any issue or not here. Those directories do not necessarily have to be of the exact same size. OTOH maybe the difference in size is big enough to warrant an investigation, based on the fact that you do not seem to use persistent messages/queues (those messages would be on one node only).

How much of "a history" does that cluster have? that is, how long does it go back, have you run test loads on it without cleaning the created state?
There was also an issue with sync and `vmq_swc` in `1.11.0` in specific situation (cluster leaves and joins).
And btw: when you go down that `data` directory: which ones of those folders do actually differ in size?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@jibsonline1 

> Can the sync issue you mentioned be the reason for node not able to join back in the cluster after a restart. It tries to join for around 5 minutes and then fails.

Hm, I guess I cannot exclude that. The issue was around a known node leaving and then joining a cluster with clean state (which it *should* always do, to be clear). 

Do you use the EULA binary packages? (ie are you with a use case I know?)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@jibsonline1 any more comments/info on this?

What I can recommend in general is to use newer packages than `1.11.0`.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
