### ISSUE TITLE
Config file in compiled vernemq

### ISSUE THREAD

**Issue by LuanneZati** [vernemq/vernemq#2064]
### where is the configuration file (plugins, input and output, ports...)

Hello community! I built and compiled my grafana code on my ubuntu and it worked fine, it's running! However, I don't find the configuration file to adjust the ip address, port, acl document, all that we have when we download the binary package. I would like to know where this file is, if I can configure my vernemq, because I need security in my mqtt broker.

### Environment

- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default

### Expected behavior

- Config File

### Actual behaviour

total 1332
drwxr-xr-x  9 root root   4096 Dec 14 15:10 .
drwx------  8 root root   4096 Dec 14 15:06 ..
-rw-r--r--  1 root root    387 Dec 14 14:23 .editorconfig
drwxr-xr-x  8 root root   4096 Dec 14 14:23 .git
-rw-r--r--  1 root root    469 Dec 14 14:23 .git-blame-ignore-revs
drwxr-xr-x  4 root root   4096 Dec 14 14:23 .github
-rw-r--r--  1 root root    158 Dec 14 14:23 .gitignore
-rw-r--r--  1 root root    119 Dec 14 14:23 .gitmodules
-rw-r--r--  1 root root    844 Dec 14 14:23 .travis.yml
-rw-r--r--  1 root root 198500 Dec 14 14:23 3rd-party-licenses.txt
-rw-r--r--  1 root root    320 Dec 14 14:23 ADOPTERS.md
-rw-r--r--  1 root root   3213 Dec 14 14:23 CODE_OF_CONDUCT.md
-rw-r--r--  1 root root   1564 Dec 14 14:23 CONTRIBUTING.md
-rw-r--r--  1 root root  10910 Dec 14 14:23 LICENSE.txt
-rw-r--r--  1 root root    953 Dec 14 14:23 Makefile
-rw-r--r--  1 root root   3458 Dec 14 14:23 PROMISES.md
-rw-r--r--  1 root root   6997 Dec 14 14:23 README.md
-rw-r--r--  1 root root    362 Dec 14 14:23 SECURITY.md
-rw-r--r--  1 root root    810 Dec 14 14:23 THANKS
drwxr-xr-x  3 root root   4096 Dec 14 14:23 _build
drwxr-xr-x 16 root root   4096 Dec 14 14:23 apps
-rw-r--r--  1 root root  70030 Dec 14 14:23 changelog.md
-rw-r--r--  1 root root    873 Dec 14 14:23 docker-compose.yml
drwxr-xr-x  2 root root   4096 Dec 14 14:23 files
-rwxr-xr-x  1 root root    660 Dec 14 14:23 gen_dev
drwxr-xr-x  3 root root   4096 Dec 14 14:23 metrics_scripts
-rw-r--r--  1 root root   1529 Dec 14 14:23 pkg.vars.config
-rw-r--r--  1 root root   6003 Dec 14 14:23 rebar.config
-rw-r--r--  1 root root   8032 Dec 14 14:23 rebar.lock
-rwxr-xr-x  1 root root 942316 Dec 14 14:23 rebar3
drwxr-xr-x  2 root root   4096 Dec 14 14:23 vars
-rw-r--r--  1 root root   1415 Dec 14 14:23 vars.config
-rw-r--r--  1 root root   1453 Dec 14 15:00 vars.generated

**Comment by ioolkos** [comment]
@LuanneZati The config file is in `/etc/vernemq/vernemq.conf` on Ubuntu
https://docs.vernemq.com/installing-vernemq/debian_and_ubuntu#default-directories-and-paths

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by LuanneZati** [comment]
@ioolkos Hello friend! Actually when you download the package and install vernemq the path is /etc/vernemq/vernemq.conf but in my case, I built the file through a source, where my vernemq is in ~/vernemq. My question is, is there no config file for compiled vernemq?
