### ISSUE TITLE
Configuration of vernemq built through sources

### ISSUE THREAD

**Issue by LuanneZati** [vernemq/vernemq#2065]
Hello community! I'm new to vernemq, today I built vernemq from sources. Is there any manual or documentation or at least something that teaches me how to move and configure the broker? It's running on my ubuntu, I know there are some commands like: vmq-passwd -c /etc/vernemq/vmq.passwd henry for password setting, but it doesn't work on my command, it returns "vmq-passwd: command not found ", could you help me with this? I need to configure TCP HTTP port and define user and password for my broker, I don't know how to do that!

NOTE: It Is a VerneMQ built from sources

**Comment by ioolkos** [comment]
Building a release will pack everything in a `_build` directory so you'll have to explore that. (for config file, start script etc)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by LuanneZati** [comment]
@ioolkos Thank u!! I managed to find the configuration file, in case anyone has doubts the 'vernemq.conf' file is in the path ./vernemq/_build/default/rel/vernemq/etc here is also the acl file. 
If you want to run vernemq or pause or pass a command go to $./vernemq/_build/default/rel/vernemq: bin/vernemq command, if you want to create a user and password, it's the same thing bin/vmq-passwd command
