### ISSUE TITLE
VMQ Cluster - published message not delivered if subscription made in another node

### ISSUE THREAD

**Issue by lucacox** [vernemq/vernemq#2066]
### Environment

- VerneMQ Version: 1.12.3
- OS: Kubernetes + Docker (image vernemq/vernemq:1.12.3-alpine) with custom plugin to consume & produce from/on Apache Kafka
- VerneMQ configuration: changes from the default (config taken from 1 of nodes, other config are similar)
########## Start ##########
max_inflight_messages=100
plugins.vmq_diversity=off
vmq_diversity.postgres.password_hash_method=crypt
plugins.vmq_kafka_bridge=on
allow_register_during_netsplit=on
listener.max_connections=infinity
log.console.level=debug
allow_unsubscribe_during_netsplit=on
accept_eula=yes
vmq_diversity.postgres.database=mqtt
vmq_diversity.postgres.host=db.postgres
allow_publish_during_netsplit=on
vmq_kafka_bridge.bootstrap_broker_host=kafka-bootstrap.kafka
systree_enabled=off
vmq_kafka_bridge.producer_topic=protocol.mqtt.upstream
erlang.max_ports=10000000
erlang.process_limit=10000000
listener.nr_of_acceptors=5000
listener.vmq.clustering=127.0.0.1:44053
vmq_diversity.postgres.port=5432
vmq_kafka_bridge.producer_partition=6
vmq_diversity.postgres.password=************
queue_deliver_mode=fanout
allow_multiple_sessions=off
log.console=console
listener.tcp.localhost=127.0.0.1:1883
vmq_diversity.auth_postgres.enabled=off
allow_anonymous=on
vmq_kafka_bridge.bootstrap_broker_port=9092
vmq_kafka_bridge.consumer_group=vmq_kafka_bridge_consumer_group
plugins.vmq_acl=on
allow_subscribe_during_netsplit=on
vmq_diversity.postgres.user=vernemq
vmq_kafka_bridge.consumer_topic=protocol.mqtt.downstream
plugins.vmq_kafka_bridge.path=vmq_kafka_bridge/default
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 10.4.2.118:1883
listener.ws.default = 10.4.2.118:8080
listener.http.metrics = 10.4.2.118:8888
########## End ##########
- Cluster size/standalone: cluster with 3 nodes behind an instance of HAProxy that does the TLS termination

### Description

Each node in the cluster is running the plugin (name: vmq_kafka_bridge) which connect to Kafka and subscribe to an input topic divided in 4 partitions, this topic provides messages for remote clients every message carries the data and the topic where to send the data.

### Expected behaviour

Given a cluster with 3 nodes named:
- node-0
- node-1
- node-2

Events:
* A client connects to node-0 and subscribes to MQTT topic-1, 
* On node-1 the vmq_kafka_bridge plugin  receive a message from Kafka meant to be sent on MQTT topic-1
* plugin in node-1 publish the message on MQTT topic-1
* client should receive the message

### Actual behaviour

The published message is received only if the node publishing it, is the same the client has made the subscription. The above sequence does not produce a publish event (I used `vmq-admin trace client` command to see messages sent/received)

### Cluster status:

```
+---------------------------------------------------------------+---------+
| Node                                                          | Running |
+---------------------------------------------------------------+---------+
| VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local | true    |
+---------------------------------------------------------------+---------+
| VerneMQ@vernemq-1.vernemq-headless.protocol.svc.cluster.local | true    |
+---------------------------------------------------------------+---------+
| VerneMQ@vernemq-0.vernemq-headless.protocol.svc.cluster.local | true    |
+---------------------------------------------------------------+---------+
```

the command `vmq-admin session show` reports the same sessions in all nodes.

**Comment by ioolkos** [comment]
@lucacox `listener.vmq.clustering=127.0.0.1:44053` will not work. This is the listener to set up the MQTT delivering connections between cluster node (as an additional layer of TCP connections). A node will literally make an RPC to find out that config on the other node and then just plainly connect to that IP/Port. 
Configure this to `0.0.0.0` or an IP you know is internally reachable. (you might have to resolve this on the level of a Docker network).

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by lucacox** [comment]
Thank you @ioolkos for the fast response. I've corrected that setting (now I have `listener.vmq.clustering=0.0.0.0:44053`), but the result is the same as before, only messages published by the node where is the subscription get to the client.

Watching the logs of the 3 nodes I see that 2 of them working normally, the third instead logs these lines

```
...
13:47:26.630 [info] successfully connected to cluster node 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local'
13:47:26.630 [debug] connect request from unknown cluster node 'VerneMQ@vernemq-0.vernemq-headless.protocol.svc.cluster.local'
13:47:26.630 [warning] terminate due to remote_node_not_available
13:47:26.630 [warning] connection to node 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' has been closed, reconnect in 1000ms
13:47:26.852 [info] vmq_kafka_bridge: Client message - Topic: biomaxcmg27a0cee10eb82abb16302bff3b9963e22001AC00B0-21-21300423live, QoS: 1
13:47:26.853 [info] vmq_kafka_bridge: producing on Topic:"protocol.mqtt.upstream"
13:47:26.970 [info] vmq_kafka_bridge: Client message - Topic: biomaxcmg27a0cee10eb82abb16302bff3b9963e22001AC00B0-21-21300423live, QoS: 1
13:47:26.970 [info] vmq_kafka_bridge: producing on Topic:"protocol.mqtt.upstream"
13:47:27.135 [info] successfully connected to cluster node 'VerneMQ@vernemq-1.vernemq-headless.protocol.svc.cluster.local'
13:47:27.136 [debug] connect request from unknown cluster node 'VerneMQ@vernemq-0.vernemq-headless.protocol.svc.cluster.local'
13:47:27.136 [warning] terminate due to remote_node_not_available
13:47:27.137 [warning] connection to node 'VerneMQ@vernemq-1.vernemq-headless.protocol.svc.cluster.local' has been closed, reconnect in 1000ms
13:47:27.633 [info] successfully connected to cluster node 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local'
13:47:27.633 [debug] connect request from unknown cluster node 'VerneMQ@vernemq-0.vernemq-headless.protocol.svc.cluster.local'
13:47:27.633 [warning] terminate due to remote_node_not_available
13:47:27.633 [warning] connection to node 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' has been closed, reconnect in 1000ms
13:47:27.817 [debug] Replica meta5: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' successfully acquired local lock
13:47:27.821 [debug] Replica meta5: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' successfully requested remote node clock
13:47:27.822 [debug] Replica meta5: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' successfully requested remote watermark
13:47:27.887 [info] Replica meta5: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' synced 68 objects
13:47:27.887 [debug] Replica meta5: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' terminates with reason normal in state local_sync_repair
13:47:27.942 [debug] Replica meta7: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' successfully acquired local lock
13:47:27.943 [debug] Replica meta7: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' successfully requested remote node clock
13:47:27.944 [debug] Replica meta7: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' successfully requested remote watermark
13:47:27.981 [info] Replica meta7: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' synced 67 objects
13:47:27.981 [debug] Replica meta7: AE exchange with 'VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local' terminates with reason normal in state local_sync_repair
...
```

The 2 node that seems ok are named: 
- VerneMQ@vernemq-1.vernemq-headless.protocol.svc.cluster.local
- VerneMQ@vernemq-2.vernemq-headless.protocol.svc.cluster.local

The one logging the above is:
- VerneMQ@vernemq-0.vernemq-headless.protocol.svc.cluster.local

**Comment by ioolkos** [comment]
Maybe that `0.0.0.0` was the wrong idea here, but yes, the issue is on connectivity/network level.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by lucacox** [comment]
OK, seems working fine now. I changed the listen IP of `vmq.clustering` to the ClusterIP of the node and cleaned the data directory of the nodes.

closing the issue.

Thank you @ioolkos
