### ISSUE TITLE
vernemq crashed

### ISSUE THREAD

**Issue by dbsd11** [vernemq/vernemq#2074]
### To help us save time and help you faster

Before opening a new issue, please make sure that isn't already an open (or
closed/resolved) issue concerning the problem. If unsure if older issues are
about the exact same thing, just open a new issue rather than posting in the old
one - but please reference the possibly related issues in the new issue.

Please do not insert images of text, but insert the text instead.

### Environment

- VerneMQ Version:1.10.0
- OS:CentOS7
- Erlang/OTP version (if building from source):22.2.5-1
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:2 node

### Expected behavior

- run ok

### Actual behaviour

- When we try to restart the cluster, the vernemq crashed again, and the client can't pub and sub any more.
[crash.log](https://github.com/vernemq/vernemq/files/10529619/crash.log)
[error.log](https://github.com/vernemq/vernemq/files/10529622/error.log)

**Comment by ioolkos** [comment]
@dbsd11 Apologies that Github issues are not an effective way to get incident support.
Verne possibly just run out of OS resources here.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
