### ISSUE TITLE
VerneMQ cluster allows connect with duplicated client id 

### ISSUE THREAD

**Issue by adam-prohack** [vernemq/vernemq#2075]
### Environment

VerneMQ Version: 1.12.6.2
OS: Amazon Linux 2 as base OS and debian as docker image OS
VerneMQ configuration (vernemq.conf) or the changes from the default:
```
########## Start ##########
max_inflight_messages=30
plugins.vmq_diversity=on
vmq_diversity.postgres.password_hash_method=crypt
max_offline_messages=500
allow_register_during_netsplit=off
retry_interval=20
allow_unsubscribe_during_netsplit=off
accept_eula=yes
vmq_diversity.postgres.database=vernemq_db
shared_subscription_policy=prefer_local
leveldb.maximum_memory.percent=60
vmq_diversity.postgres.host=hidden
listener.tcp.allowed_protocol_versions=3,4,5
plugins.vmq_passwd=off
listener.tcp.proxy_protocol=on
distributed_cookie=hidden
listener.tcp.default=0.0.0.0:1883
allow_publish_during_netsplit=off
vmq_diversity.postgres.port=5432
vmq_diversity.postgres.password=hidden
allow_multiple_sessions=off
erlang.distribution.port_range.minimum=9100
log.console=console
coordinate_registrations=on
persistent_client_expiration=1d
vmq_diversity.auth_postgres.enabled=on
plugins.vmq_acl=off
allow_subscribe_during_netsplit=off
nodename=vernemq-userpass-0.vernemq-sd.connect-1.internal
vmq_diversity.postgres.user=vernemq_user
erlang.distribution.port_range.maximum=9110
listener.ws.default = 10.130.204.91:8080
listener.vmq.clustering = 10.130.204.91:44053
listener.http.metrics = 10.130.204.91:8888
########## End ##########
```
Cluster size/standalone: 2 nodes

### Expected behaviour

When I am trying connect to VerneMQ from different device but with duplicated client id (with clear session enabled), I am expecting VerneMQ should remove previous connected session and connect only the newest one.
- Please describe the expected behaviour.

### Actual behaviour

Currently, when I try to connect to VerneMQ from a single device (peer_host) but multiple sessions with the same client_id (multiple instances of the client application), VerneMQ works correctly and deletes previous sessions, allowing only the most recent connection.
When I try to connect to VerneMQ from 2 different devices (peer_host) but with the same client_id, VerneMQ allows this connection, even though it is not compatible with the MQTT protocol

**Comment by ioolkos** [comment]
@adam-prohack Thanks, yeah, that's not the idea. Can you share more info about the connecting client and the overall network components (proxy?). What do you see with `vmq-admin session show`?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@adam-prohack let's be more precise, though.
In your second case, VerneMQ accepts the new connection (that's OK, and is what's supposed to happen). You seem to see that the previous session is not immediately terminated?
How do you issue the CONNECT commands and how do you observe VerneMQ status?

This is a single VerneMQ node, right?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by adam-prohack** [comment]
@ioolkos  thanks for your answer. Today have tried to repeat the conditions and  I can't. Maybe the problem was caused by a netsplit or a misconfigured device. We can close this topic

**Comment by adam-prohack** [comment]
![image](https://user-images.githubusercontent.com/11619086/221938909-94e8e425-ee41-4021-9aca-7191a9682867.png)
Unfortunately, when I was on holiday the situation repeated itself. Unfortunately, we had to completely reinstall the cluster but I managed to get a screenshot (anonymized).

**Comment by ioolkos** [comment]
@adam-prohack Do you have access to the client side logs?

Are those MQTT v5 clients with QoS > 0 subscriptions?
I've seen a somewhat similar issue when no `receive_max_client` was set (say to something like 10000, or lower.) when there was a message id overflow at the client.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
This might happen in another situation as well, when a ClientId is racing against itself, ie. both instances always reconnect and kick each other off the broker. The Verne logs should help.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by Nowogrodzki** [comment]
@ioolkos Hello :)
I'm facing the same problem, and I think that the problem is related to the client ID racing against itself. What solution do you suggest in this case?
