### ISSUE TITLE
Feature Request: Time to live for connected clients and automatic disconnect

### ISSUE THREAD

**Issue by mths1** [vernemq/vernemq#2083]
### Describe your issue or feature request

Currently, there is no integrated way of disconnecting clients after a specified period of time. I'd like to see an option that the authorization/authentication plugins can return a custom client lifetime.

Reason-why: (for me) This is a prerequisite for any serious token based authentication.

### Describe the solution you'd like

My suggestion would be as follows:

MVP:
- Add a maximum lifetime configuration token after which each client is disconnented (default unlimited)
- Add an implementation similar to the existing keep_alive (using erlang:send_after) that disconnects clients once fired
- Use the modifiers of auth_on_register to return a custom client lifetime.

### Describe alternatives you've considered

- Externally trigger disconnects (not nice)

### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@mths1 yes, that can be a feature. The important point is that it is only settable via the hook modifier, and not in the `vernemq.conf` file or as a live setting. As a global config it would interrupt other MQTT clients (possibly authenticated over other plugins) otherwise.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
@ioolkos : Would a global setting really be a bad thing? As an MQTT broker operator I might want clients to disconnect/reconnect after a certain period of time (regardless of who autenticated it). The default could be "unlimited", which would mean no regression. 

What do you think about the implementation similar to keep alive via erlang:send_after? As an alternative, it could be checked whenever a client interacts with the broker. I am not sure what is better, performance-wise. I have the feeling that send_after is both more performant and more readable, but I am lacking experience here.

**Comment by ioolkos** [comment]
@mths1 the problem of a global config is that we apply a setting for a subset of MQTT clients to *all* clients. This has bitten us in the past.

We can discuss implementation details anytime but we need to establish our options and then choose the generic one that enables the JWT token use case as well. (Do we set a timer automatically based on extracted token information? Do we cache that information etc.)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
This is interesting to think about; but somewhat tricky to find the best approach.
Regarding token expiry as an example: how precise would a disconnect have to be? A global config would not be precise but set an upper limit.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
I prototyped a solution that implements according to MQTT "5.4.9 Other security considerations" the following:
·         Servers may close the Network Connection of Clients and require them to re-authenticate with new credentials.

so what I thought of
- we have global setting max_connection_livetime (which can be unlimited by default)
- the global setting can be overriden on a listener level (e.g. to seperate trusted and untrusted clients)
- the global/listener setting can be overriden by the authentication plugins
- Each level can decrease the lifetime, not increase
- With MQTTv5 we can disconnect with reason "Maximum connect time "

this should work for all authentication methods. For Token based ones the authentication plugin would set the max connection livetime to the token expiry.

Currently, the prototype works just as keep_alive, so it is based on erlang:send_after (I do not think that millisecond accuracy is necessary)

**Comment by ioolkos** [comment]
This sounds good. It covers the cases where we have:

- multiple listeners to separate MQTT clients 
- multiple plugins to separate MQTT clients

If we don't want to interrupt a class of clients (let's say backend applications) then we'd have to keep to global setting at unlimited, working with the fine-grained restrictions for other clients. But that's acceptable.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
Implemented by https://github.com/vernemq/vernemq/pull/2107
