### ISSUE TITLE
ECONNRESET on clean disconnect using MQTT.js

### ISSUE THREAD

**Issue by fpagliughi** [vernemq/vernemq#2092]
### Environment

- VerneMQ Version: 1.12.6.2
- OS: Linux Mint 20
- Erlang/OTP version (if building from source): (.deb package)
- Cluster size/standalone: Standalone, testing across localhost
- Node version: v16.19.0

I know almost nothing about TypeScript/JavaScript, but have a business customer starting to use it for MQTT client with MQTT.js, so I tried to create some small examples to get them started. 

Using VerneMQ as the broker, when I attempt a clean disconnect at the end of a script, I get a ECONNRESET error in the client.

As a matter of course, I tend to test my MQTT stuff against several brokers, and this behavior is only happening with VerneMQ, and not the other brokers (Mosquitto and RabbitMQ).

This behaviour was reported on the MQTT.js repo a while back, but the issue was closed without resolution, so I thought I might post it here to get some thoughts on it.
https://github.com/mqttjs/MQTT.js/issues/1179

### Current Behavior

The small example posted with the MQTT.js issue mentioned above does produce the error, although the example has a small typo. Here is the slightly modified version that I used:

```
var mqtt = require('mqtt')
var client = mqtt.connect('mqtt://localhost:2883')

client.on('connect', function() {
  client.subscribe('presence', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  })
})

client.on('message', function (topic, message) {
  console.log(message.toString())
  client.end()
})

client.on('error', function(err) {
  console.log(err)
})
```

And I get the output to the console:
```
$ node testconn.js 
Hello mqtt
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

### Expected behaviour

No error reported.

### Configuration, logs, error output, etc.

```markdown
$ diff -u vernemq.conf.org vernemq.conf
--- vernemq.conf.org	2023-02-18 09:42:14.035149039 -0500
+++ vernemq.conf	2023-02-18 11:03:12.196389894 -0500
@@ -6,7 +6,7 @@
 ## 
 ## Acceptable values:
 ##   - one of: yes, no
-accept_eula = no
+accept_eula = yes
 
 ## Allow anonymous users to connect, default is 'off'. !!NOTE!!
 ## Enabling this completely disables authentication of the clients and
@@ -17,7 +17,8 @@
 ## 
 ## Acceptable values:
 ##   - on or off
-allow_anonymous = off
+#allow_anonymous = off
+allow_anonymous = on
 
 ## Allow new client connections even when a VerneMQ cluster is inconsistent.
 ## 
@@ -305,6 +306,9 @@
 ##   - an IP/port pair, e.g. 127.0.0.1:10011
 listener.vmq.clustering = 0.0.0.0:44053
 
+# (fmp)
+listener.tcp.default = 127.0.0.1:2883
+
 ## listener.http.default is the IP address and TCP port that
 ## the broker will bind to accept HTTP connections
 ## - listener.http.default = 0.0.0.0:8888
@@ -315,7 +319,8 @@
 ## 
 ## Acceptable values:
 ##   - an IP/port pair, e.g. 127.0.0.1:10011
-listener.http.default = 127.0.0.1:8888
+#listener.http.default = 127.0.0.1:8888
+listener.http.default = 127.0.0.1:2888
 
 ## The cafile is used to define the path to a file containing
 ## the PEM encoded CA certificates that are trusted. Set the cafile
```

The broker does not appear to write anything to the log when this occurs.
```


### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@fpagliughi Can you try setting the TCP linger option to something other than 0 and see whether this helps? You can do this by adding the following line to the `vernemq.conf` file.

```
tcp_listen_options = [{nodelay, true}, {linger, {true, 6}}, {send_timeout, 30000}, {send_timeout_close, true}]
```

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by fpagliughi** [comment]
Yes, that fixes the error. Thank you!
