### ISSUE TITLE
where download aarch64 of vernemq abount ubuntu?

### ISSUE THREAD

**Issue by kervin521** [vernemq/vernemq#2095]
### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Current Behavior

VerneMQ Version:latest
OS: Ubuntu 20.04 aarch64
Erlang/OTP version (if building from source): 25.0
Cluster size/standalone: 3 nodes

### Expected behaviour

VerneMQ Version:latest
OS: Ubuntu 20.04 aarch64
Erlang/OTP version (if building from source): 25.0
Cluster size/standalone: 3 nodes

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@kervin521 There's no official ARM binary yet. Our next release will likely enable it.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
