### ISSUE TITLE
MQTT Bridge buffer on disk?

### ISSUE THREAD

**Issue by alan-mat** [vernemq/vernemq#2098]
### Describe your issue or feature request

In Issue #1563 it was stated that VerneMQ only supports an in-memory buffer for bridge messages. Is that still the case? Does this mean that there is no way to buffer bridge messages on disk? I wasn't able to find a definitive answer in the documentation. 

 Our push bridge node is running in a Docker container. After something happened to the bridge connection VerneMQ started buffering messages and quickly filled up its RAM. When the memory consumption was at a critical level, we were forced to restart the Docker container, in turn losing all data. I'm guessing this was intended behaviour?

### Describe the solution you'd like

Buffer MQTT Bridge messages on disk.

### Environment

- VerneMQ Version: 1.12.5
- OS: Debian GNU/Linux 11
- Erlang/OTP version (if building from source): 25
- Cluster size/standalone: standalone

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
Yes, buffer is RAM-based (this buffers the outgoing side of the push bridge, that is the MQTT publisher of that bridge). You need to configure `vmq_bridge.tcp.$name.max_outgoing_buffered_messages` to a value that allows the node to survive.

`vmq-admin bridge show` will show you the current buffered messages per bridge.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.--

**Comment by alan-mat** [comment]
Thank you. I'd like to know if bridge buffer on disk is a feature planned for the near future or not? If not, then we cannot use VerneMQ for Bridge Nodes, due to data loss concerns.

**Comment by ioolkos** [comment]
For options/discussion, please send a mesage to info @ vernemq com

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
