### ISSUE TITLE
Is there any plan to support Aarch64？

### ISSUE THREAD

**Issue by kervin521** [vernemq/vernemq#2109]
### Describe your issue or feature request

VerneMQ Version: 1.12.6.2
OS: Ubuntu 20.04
Arch: Aarch64
Erlang/OTP version (if building from source): 25.0
Cluster size/standalone: 3 nodes

### Describe the solution you'd like

VerneMQ Version: 1.12.6.2
OS: Ubuntu 20.04
Arch: Aarch64
Erlang/OTP version (if building from source): 25.0
Cluster size/standalone: 3 nodes

### Describe alternatives you've considered

VerneMQ Version: 1.12.6.2
OS: Ubuntu 20.04
Arch: Aarch64
Erlang/OTP version (if building from source): 25.0
Cluster size/standalone: 3 nodes

### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
Yes. PR pending, https://github.com/vernemq/vernemq/pull/2078

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
