### ISSUE TITLE
Support for Redis user

### ISSUE THREAD

**Issue by goldyfruit** [vernemq/vernemq#2110]
### Describe your issue or feature request

My Redis Cluster is using ACL which means I have user and a password but from what I saw, there is no `DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__USERNAME` variable available which forces me to use the `default` Redis user.

Is there any way to use a Redis username?

### Describe the solution you'd like

Addind `DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__USERNAME` as supported variable

### Environment

- VerneMQ Version: `master`
- OS: Kubernetes 1.26
- Cluster size/standalone: 3 nodes

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@goldyfruit Thanks. Seems we open a pool with different options like db name, password, host etc. but not a username. So, a username is a ACL thing that's normally not used? (need to read up on this)

https://github.com/vernemq/vernemq/blob/72b565d20defbc2339d4c2cb8f19daba80357305/apps/vmq_diversity/src/vmq_diversity_redis.erl#L250

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by goldyfruit** [comment]
@ioolkos thanks for your reply.

Yes, the default user is `default`, so if you leave the `--user` option blank from the `redis-cli` it implies that you want to use this user.

With ACL you can create users with different password and less permissions.

````
root@redis-cluster-0:/# redis-cli --user admin -a XXXXXX
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
127.0.0.1:6379> cluster nodes
NOAUTH Authentication required.
127.0.0.1:6379> 
root@redis-cluster-0:/# redis-cli --user default -a XXXXX
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> cluster nodes
f1fb6951069b69418a71560c5250ed66c68ebc7e 10.233.75.48:6379@16379 slave ddd444821ce0c89c8d6a821ff8c8fb31b6c985ca 0 1678378137000 3 connected
ddd444821ce0c89c8d6a821ff8c8fb31b6c985ca 10.233.110.177:6379@16379 master - 0 1678378137229 3 connected 10923-16383
055ebac2f7d0f72d0bbc8a1850f2c4110be615e8 10.233.110.141:6379@16379 slave a1f895036eab1ee0d3c46f4dcd9db54b39b5f901 0 1678378139000 1 connected
55b924a58aef2fe2e208af3918eb2537852d2661 10.233.75.49:6379@16379 slave d4c7b77aab5975607f87c9a64e6548223f703d88 0 1678378137000 2 connected
a1f895036eab1ee0d3c46f4dcd9db54b39b5f901 10.233.110.183:6379@16379 myself,master - 0 1678378138000 1 connected 0-5460
d4c7b77aab5975607f87c9a64e6548223f703d88 10.233.75.47:6379@16379 master - 0 1678378139242 2 connected 5461-10922
127.0.0.1:6379> 
root@redis-cluster-0:/# redis-cli --user vernemq -a XXXXX
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> keys *
(error) NOPERM this user has no permissions to run the 'keys' command
```

**Comment by ioolkos** [comment]
`eredis` supports giving a Username:
https://github.com/Nordix/eredis/blob/7d9f67fe9e11b3a696b9e10e55ec7fcac99d4973/src/eredis.erl#L51

So, I think the feature would be pretty straightforward to add, beginning with adding the redis.username setting to the `vmq_diversity` schema.

Who wants to do it? :)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by goldyfruit** [comment]
> Who wants to do it? :)

@ioolkos I tried but I was not able to make it work :/

**Comment by ioolkos** [comment]
Use `{username, User}` not `{user, User}` in NewOpts. If this does not work, I can take a look.
Thanks for giving it a try! :1st_place_medal:

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
