### ISSUE TITLE
[Bug]: HTTP2 not properly working for TLS connections

### ISSUE THREAD

**Issue by mths1** [vernemq/vernemq#2117]
### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Current Behavior

`curl --request GET --http2-prior-knowledge  --url https://broker:443/metrics  -vv`

```
*  SSL certificate verify ok.
> GET /metrics HTTP/1.1

```
Will not upgrade to HTTP2... 

`curl --request GET --http2-prior-knowledge  --url https://broker:443/metrics  -vv`

=> curl: (16) Error in the HTTP2 framing layer

For a test a changed to cowboy:start_tls instead of ranch:start_listener and it worked.

`curl --request GET --http2-prior-knowledge  --url https://broker:443/metrics  -vv`
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200
< content-length: 40048
< content-type: text/plain
< date: Fri, 17 Mar 2023 22:59:30 GMT
< server: Cowboy

```
`curl --request GET --http2-prior-knowledge  --url https://broker:443/metrics  -vv`

=> Works

### Expected behaviour

HTTP2 works with --http2-prior-knowledge and does an upgrade with --http2. MQTT over Websockets might also be affected. Didn't test.

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@mths1 thanks, we started out with Cowboy < version 2.0. Cowboy only had HTTP2 support starting with 2.0.
We could've/should've done this back when upgrading to the 2.x series. 

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
