### ISSUE TITLE
[Bug]: Frequent cluster failures

### ISSUE THREAD

**Issue by adam-prohack** [vernemq/vernemq#2148]
### Environment

We currently have VerneMQ installed on an AWS ECS cluster (Fargate) with an AWS EFS persistent storage connected. VerneMQ is installed in the ECS task and in the same task is the HAProxy to which the AWS Network Load Balancer is connected.
![VerneMQ drawio](https://user-images.githubusercontent.com/11619086/234909718-d513944b-5e09-41fb-aca2-04183b244f92.png)

### Current Behavior

Unfortunately, from time to time the nodes reboot and the cluster crashes and requires reinstallation. Is our approach to installing the cluster on AWS ECS correct, or is it better to abandon the persistent storage. We do not use persistent functionality in MQTT.

### Expected behaviour

Reduce cluster failures requiring reinstallation

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@adam-prohack can you send a message to info at vernemq.com?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
