### ISSUE TITLE
Make VerneMQ compile on OTP 26.0

### ISSUE THREAD

**Issue by ioolkos** [vernemq/vernemq#2155]
To have a go at this, you'll need OTP 26.0 on your system. The easiest way is to use kerl, so that you can switch between multiple OTP versions.

```
kerl update releases
kerl build 26.0 26.0 
kerl install 26.0 .kerl/Erlangs/26.0
```

**Comment by mths1** [comment]
Just for fun I tried to make this compile with OTP 26. It needed:

- Update bcrypt to 1.2.1
- Update cowboy to 2.10.0
- Update cowlib to 2.12.1

In plumtree rebar.config and vmq_server rebar.config remove warnings_as_errors (as well get some new deprecation warnings)

and it compiles. 

To make it work you need also to replace erlang:port_command with gen_tcp:send 

See: https://github.com/erlang/otp/issues/7130

and it starts working for tcp connections. SSL might, or might not, have some more surprises according to the OTP 26 changelog...

**Comment by mths1** [comment]
Here is the rabbidmq version of the fix:
https://github.com/rabbitmq/rabbitmq-server/pull/7927/files

**Comment by ioolkos** [comment]
@mths1 Thanks for looking into this! great stuff, let's see about those SSL suprises in OTP 26 :)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
@ioolkos : Any change that we can add OTP 26 to the integration tests?

**Comment by ioolkos** [comment]
@mths1 I don't want to test 4 OTP releases but I'm fine dropping 23 in favour of 26.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
