### ISSUE TITLE
[Bug]: Not able to install vernemq aws linux 2023

### ISSUE THREAD

**Issue by syedzahidulla** [vernemq/vernemq#2166]
### Environment

- VerneMQ Version: 1.13.0
- OS: Linux

### Current Behavior

 **When i run this command**
 
 yum install vernemq-1.13.0.amzn2.x86_64.rpm
 
 
 **Iam getting below error**
 
Last metadata expiration check: 2:06:19 ago on Fri Jun 16 05:06:54 2023.
Error:
 Problem: conflicting requests
  - nothing provides libcrypto.so.10()(64bit) needed by vernemq-1686126158:1.13.               0-1.x86_64
  - nothing provides libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit) needed by vernemq-               1686126158:1.13.0-1.x86_64
  - nothing provides libcrypto.so.10(OPENSSL_1.0.2)(64bit) needed by vernemq-168               6126158:1.13.0-1.x86_64
  - nothing provides libcrypto.so.10(libcrypto.so.10)(64bit) needed by vernemq-1               686126158:1.13.0-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
[root@ip-172-31-33-213 ec2-user]

### Expected behaviour

It should install vernemq

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@syedzahidulla Thanks, ugh, an issue with the linked libcrypto. Let me investigate this.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@syedzahidulla in the amz2 builder for the package, we `yum install` a couple packages, namely `openssl openssl-devel snappy-devel`. Please check whether OpenSSL is installed in your Linux 2 instance.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by syedzahidulla** [comment]
Seems like it was missing openssl openssl-devel and snappy-devel in this new version.
So, thanks
