### ISSUE TITLE
extra info for packet_exceeds_max_size

### ISSUE THREAD

**Issue by nirfr** [vernemq/vernemq#2184]
### Describe your issue or feature request

Once in a while we get a lot of these messages:

session stopped abnormally due to 'packet_exceeds_max_size'

I guess its a faulty client, but I can't tell which...

### Describe the solution you'd like

Printing the client id with the error message would help tracking the origin/source of the problem

### Environment

- VerneMQ Version: vernemq/vernemq:1.12.3-alpine
- OS: k8s
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@nirfr Thanks, I see your point. We probably should get the session state here and get the subscriber_id for logging.
https://github.com/vernemq/vernemq/blob/de87dad923ad7a1cb26f4df842e0381ee4ead61c/apps/vmq_server/src/vmq_ranch.erl#L187

Right now, if you cannot conclude state information from one of the logs (console.log/error.log/crash.log) the client information is lost. You can maybe check for this in your log files, but I'll label this as an enhancement.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
Here is a patch I wrote some time ago to fix this
https://github.com/mths1/vernemq/tree/feature/print-subscriber-on-log

unfortunately, I did not yet test it to the end...
