### ISSUE TITLE
[Bug]: Unexpected behaviour of vmq-admin session disconnect --cleanup (bug or feature?)

### ISSUE THREAD

**Issue by mths1** [vernemq/vernemq#2185]
### Environment

Hello

vmq-admin session disconnect --cleanup client-id=client_id does not disconnect the client_id, a mosquitto_sub just continues. A disconnect without --cleanup really disconnects. Is this the expected behaviour, that it just does a cleanup without a disconnect, or should it also disconnect?

### Current Behavior

The subscriber is not disconnected.

### Expected behaviour

From the help text, I would expect the command to disconnect the client.

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@mths1 We would want it to disconnect in both cases but mosquitto is a re-connecting client.

Can you add the debug option  (`-d) to `mosquitto_sub`  to see the different behaviour?

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
On one hand, it seems I am really observing some implementation detail of mosquitto sub, on the other hand VerneMQ closes the session differently with (-c and without):


**vmq-admin session disconnect client-id=test1**

```
mosquitto_sub -t test -d -i test1 -V 5
Client test1 sending CONNECT
Client test1 received CONNACK (0)
Client test1 sending SUBSCRIBE (Mid: 1, Topic: test, QoS: 0, Options: 0x00)
Client test1 received SUBACK
Subscribed (mid: 1): 0
Received DISCONNECT (152)
```

**vmq-admin session disconnect client-id=test1 -c**


```
mosquitto_sub -t test -d -i test1 -V 5
Client test1 sending CONNECT
Client test1 received CONNACK (0)
Client test1 sending SUBSCRIBE (Mid: 1, Topic: test, QoS: 0, Options: 0x00)
Client test1 received SUBACK
Subscribed (mid: 1): 0
Client test1 sending CONNECT
Client test1 received CONNACK (0)
Client test1 sending SUBSCRIBE (Mid: 2, Topic: test, QoS: 0, Options: 0x00)
Client test1 received SUBACK
Subscribed (mid: 2): 0
```

**MQTTv3 always reconnects**
```
Client test1 sending CONNECT
Client test1 received CONNACK (0)
Client test1 sending SUBSCRIBE (Mid: 1, Topic: test, QoS: 0, Options: 0x00)
Client test1 received SUBACK
Subscribed (mid: 1): 0
Client test1 sending CONNECT
Client test1 received CONNACK (0)
Client test1 sending SUBSCRIBE (Mid: 2, Topic: test, QoS: 0, Options: 0x00)
Client test1 received SUBACK
Subscribed (mid: 2): 0
```

**Comment by ioolkos** [comment]
Thanks, so it's about whether the `DISCONNECT` is received or not.
We can check if it's the network or the implementation.

Can you add something like the following options to `vernemq.conf`: (the point is to set the linger option to something other than 0):

```
tcp_listen_options = [{nodelay, true}, {linger, {true, 6}}, {send_timeout, 30000}, {send_timeout_close, true}]
```
---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq.
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
I close this, as it is an implementation detail of mosquitto. The tcl_listen_options did not change the behaviour.
