### ISSUE TITLE
Environment variables for erlang configuration

### ISSUE THREAD

**Issue by mths1** [vernemq/vernemq#2188]
### Describe your issue or feature request

What about introducing some environment variables allowing to configure erlang without having to copy/modify vm.args (which has dependencies to config which is not that nice)?

RABBITMQ uses two flags:

- RABBITMQ_SERVER_ERL_ARGS allows all VM flags to be overridden, including the defaults set by RabbitMQ scripts
- RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS allows a set of flags to be appended to the defaults set by RabbitMQ scripts

What about having something similar for VerneMQ?

### Describe the solution you'd like

Environment variables...

### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@mths1 sounds interesting, yes.
Also note that we expose the subset of VM setting as exposed in cuttlefish:
https://github.com/basho/cuttlefish/blob/cb3df6a917ee93374de2b881e138e3dc6e9bf5cf/priv/erlang_vm.schema
I suppose we could just also add additional erlang mappings to the vmq-server schema file.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
@ioolkos : Could also be an option, although I would be unsure if it is possible to add things from vmq-server to vm.args. 

My main argument against adding them as single config values would be: Is it worth the effort? We would most likely never be complete, and if you are looking for advice on google etc. you'll find stuff like try +abcdefg which then you'd have to match to the VerneMQ config somehow. I'd consider those "expert" settings.

**Comment by ioolkos** [comment]
Schema files are not limited to "their own" app. We could, as an example, add mappings to the `vmq_server.schema` file like this:

```
{mapping, "erlang.max_atoms", "vm_args.+t", [
  {datatype, integer},
  {default, 1048576},
  hidden
]}.
```
and then we should be able to do
`erlang.max_atoms = 500000` 
in the `vernemq.conf` file.

But it's true that we need to have the mappings in place. I have no objection to an additional way à la RabbitMQ if it doesn't change too much inner workings. (for now, I haven't reviewed how Rabbit implements this)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
