### ISSUE TITLE
[Bug]: Caching for auth_on_xxx_m5 hooks is not working

### ISSUE THREAD

**Issue by ben-fussell** [vernemq/vernemq#2199]
### Environment

- VerneMQ Version: 1.13
- OS: Debian Bullseye
- Erlang/OTP version (if building from source): 25
- Cluster size/standalone: 2

### Current Behavior

We register the `auth_on_register`, `auth_on_publish`, `auth_on_subscribe`, `auth_on_register_m5`, `auth_on_publish_m5`, `auth_on_subscribe_m5` webhooks to leverage external authentication/authorization. The webhook response on success is ```res.header('cache-control', `max-age=3600`).status(200).json({ result: 'ok' })```. When connecting/publishing/subscribing from a v3.1.1 client, the first request logs a miss and an entry. Subsequent requests log hits. When connecting/publishing/subscribing from a v5 client, all requests are logged as misses. No entries get created in the cache and therefore no hits.

Cache after publishing messages from a v3.1.1 client

<img width="809" alt="image" src="https://github.com/vernemq/vernemq/assets/24559106/2bf0f830-f0d6-491f-9f4a-6f282d15368a">

Cache after publishing messages from a v5 client

<img width="818" alt="image" src="https://github.com/vernemq/vernemq/assets/24559106/0424dfe0-f00a-4b03-b77a-b2c0bfa66d19">

### Expected behaviour

I would expect the auth webhook cache to function the same regardless of client version.

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@ben-fussell Thanks for reporting. Ugh, do we miss this insert in v5?:
https://github.com/vernemq/vernemq/blob/52ec9e27c8f31094255baf839bd32319ecdeee29/apps/vmq_webhooks/src/vmq_webhooks_plugin.erl#L828

We also need to check whether this is covered by the Webhooks test_suite.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@ben-fussell fixed by @mths1 with PR #2200 
Please test & let us know!

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ben-fussell** [comment]
@ioolkos v5 webhook caching is working as expected. Thanks!

When do you plan on cutting a new release that includes the last few months of changes? We build the VerneMQ source based on release tags, so I'm just curious.

**Comment by ioolkos** [comment]
@ben-fussell Thanks for confirming that the feature works.

I'll cut a new release within weeks.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ben-fussell** [comment]
@ioolkos I see there was a version 2 beta release, but would it be possible to release a version 1 minor that includes this change? I'd like to take advantage of mqttv5 webhook caching without migrating to v2.

**Comment by ioolkos** [comment]
First I apologise the release took longer than announced in this thread.
Since you compile your version of Verne, you can always just compile from that (or any) commit. Also note that the breaking changes for 2.0 are really minor: https://docs.vernemq.com/v/master/guides/migration-to-2-0

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
@ioolkos : FWIW, the obfusication is missing from the migration guide...

**Comment by ioolkos** [comment]
@mths1 ah thanks, yes, folks with their own plugins should know about it.
 
---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
