### ISSUE TITLE
[Question]: Does VerneMQ support RocksDB in 1.13.0?

### ISSUE THREAD

**Issue by stepcheunghk** [vernemq/vernemq#2206]
Hi everyone, it seems VerneMQ doesn't support RocksDB in 1.13.0. Is there any fork/ branch with RocksDB support which I can refer to?

Because I see some forks with RocksDB support are there for 1.10.1.
https://github.com/ioolkos/vernemq/tree/rocksdb-messagestore/apps/vmq_generic_msg_store

**Comment by ioolkos** [comment]
@stepcheunghk RocksDB is not "compiled in" in 1.13.0.

If you want to reconcile branches and look into this, use:
https://github.com/vernemq/vernemq/tree/new-feature-rocksdb-messagestore

It's straightforward to build a Verne-RocksDB release. The only thing is that the RocksDB settings are currently not exposed to the `vernemq.conf` file, so you have to do all RocksDB configuration in the `advanced.config` file. I'm starting to think that this is okay or even preferable. (I viewed it as a blocking issue in the past).

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by stepcheunghk** [comment]
Hello Sir @ioolkos, thank you for your prompt response ! Let me have a look first.

**Comment by stepcheunghk** [comment]
Sure. Thanks for your help. Will let you know if there is any finding.

**Comment by stepcheunghk** [comment]
Hello @ioolkos, I was able to compile Vernemq 1.13.0 with RocksDB support by picking the diff from _new-feature-rocksdb-messagestore_. 

However, when I tried to define the directory of msg_store in **_vernemq.conf_**, it didn't take effect. It still pointed to _./data/msgstore_. But I can confirm the value has been set to _/var/lib/vernemq/data/msgstore_ with the following command. Also other configs did take effect (e.g. _vmq_swc.db_backend_, _vmq_swc.directory_ etc.)

Do you have any idea why? Thanks!

```
# bin/vernemq config describe vmq_generic_msg_store.directory
Documentation for vmq_generic_msg_store.directory

   Valid Values:
     - the path to a directory
   Default Value : ./data/msgstore
   Set Value     : /var/lib/vernemq/data/msgstore
   Internal key  : vmq_generic_msg_store.msg_store_opts.store_dir
```

**Comment by ioolkos** [comment]
@stepcheunghk Thanks, that setting seems to need some fixing then. 
If you need to set a different directory for now, you can change it in the `vmq_generic_msg_store.app.src` file and recompile.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by stepcheunghk** [comment]
@ioolkos Thanks again for your prompt response!

**Comment by ioolkos** [comment]
@stepcheunghk since I want to merge RocksDB support eventually, I'm interested even if it'd be only anecdotical feedback.
Did you run Verne a bit on RocksDB? any observations so far?
I'll leave the issue closed here.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by stepcheunghk** [comment]
@ioolkos Hi! I Have been working on other projects recently. Didn't have time to take a deep look at it.
I will spend some time on it and get back to you later.

**Comment by ioolkos** [comment]
@stepcheunghk No problem! It is your time and interest and very appreciated here.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@stepcheunghk Thanks for the feedback! Of course, yes, the advanced.config file is an option for the directory setting. And we need to have an advanced config for RocksDB anyway.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
