### ISSUE TITLE
[Bug]: Issues with the correct CPU quota detection on k8s v1.26

### ISSUE THREAD

**Issue by ilpanich** [vernemq/vernemq#2207]
### Environment

- VerneMQ Version: 1.12.6.2/1.13.0
- OS: VerneMQ docker image (built using vernemq/docker-vernemq github repo) deployed on kubernetes v1.26
- standalone

### Current Behavior

Once VerneMQ starts, it deploy several scheduler threads (1 for each node CPU), despite its k8s behaviour restricts it (e.g.: 400m available for the container).
Container CPU reaches quickly 95-100%.
This didn't happened on kubernetes v1.25 (we see just 1 scheduler thread at starts that it might scale up if load becomes heavier), and the only difference is that v.126 enforces cgroups v2 usage while v1.25 use the old cgroups.

### Expected behaviour

We expect VerneMQ to correctly detect its own CPU quota on k8s v1.26 and keep the same behavior observed with the previous kubernetes version (k8s v1.25).
We noticed that in Erlang 26/OTP 14.1 a fix to a bug in the correct detection of the CPU quota is reported in the changelog, I don't know if it might be helpful to solve our issue,

### Configuration, logs, error output, etc.

```markdown
We added:
+S 2:1
In order to try to replicate the previous behavior, but we fear we might have issue on heavy loads.
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@ilpanich Thanks, can you link to the fix in OTP 26? (can't seem to quickly find it)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ilpanich** [comment]
Hi @ioolkos,
  I found this one: https://www.erlang.org/doc/apps/erts/notes#erts-14.1

> Fixed a bug where the emulator was unable to determine the current cgroup CPU quota.
Own Id: OTP-18645 Aux Id: GH-7401

As I said, I don't know if it will fix our issue, but maybe you can check.

**Comment by ioolkos** [comment]
The corresponding Github issue is: https://github.com/erlang/otp/issues/7401
Reads very much like the issue at hand.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ilpanich** [comment]
Can you please give us an ETA to have this fix in VerneMQ?
Some public cloud providers are forcing to move to k8s v1.26 before Oct. 31st.

**Comment by ioolkos** [comment]
@ilpanich No VerneMQ source code has to be fixed. I haven't checked whether the OTP fix is already backported to OTP 25. You could look into that since you use self-compiled packages. Or compile with OTP 26 (see https://github.com/vernemq/vernemq/pull/2157)
For the Verne subscription-based binaries, we'll have to do something similar. (they are obviously compiled with a specific OTP release).

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ilpanich** [comment]
Hi @ioolkos:

>  I haven't checked whether the OTP fix is already backported to OTP 25

To me it seems that it has not been backported, but I'm not really expert with erlang/OTP, so maybe if you can check it could be better.
If it has been backported and this is included in the VerneMQ versions I put in this ticket... then there is another issue with the CPU detection different from the one mentioned.
I tried to build with OTP 26 but the build has failed and as far as I can see in [#2157](https://github.com/vernemq/vernemq/pull/2157) some tests fail and I cannot put in my production enviroment something that is not really stable.

**Comment by ilpanich** [comment]
Hi @ioolkos. I have built an image using Erlang 26 and it seems ok.
By the way I'll wait VerneMQ to offically merge [#2157](https://github.com/vernemq/vernemq/pull/2157) to close this issue.

**Comment by ioolkos** [comment]
@ilpanich OTP 26 support is now  merged.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ilpanich** [comment]
@ioolkos got it.
I will build and try in our environments, if it is ok I will close the issue.
Thank you!

**Comment by ilpanich** [comment]
Yes, we can close it.
Thank you @ioolkos  for the support.
