### ISSUE TITLE
[Bug]: vmq_http_pub plugins apis not restricted by api key and bounded to default http listener  

### ISSUE THREAD

**Issue by ashishislive** [vernemq/vernemq#2222]
### Environment

- VerneMQ Version: 1.13.0
- OS: Ubuntu 20.04
- Erlang/OTP version : 26.1.2
- Cluster size/standalone: 1 node

### Current Behavior

As per [Documentation](https://github.com/vernemq/vmq-docs/blob/1.13.0/configuration/http-pub.md) **vmq_http_pub** plugin is not bound to any listener. But it is not the case, when _plugins.vmq_http_pub_ enabled, it is allowing to publish message without api key restriction with default http listener.

## Tested Api Endpoint
Message payload posted on following endpoint, while **vmq_http_pub** plugin is enabled. No apiKey supplied response is still success.
`http://127.0.01:8888/restmqtt/api/v1/publish`

Seems like security issue, if plugin enabled it allow any authenticated user to publish messages over rest api.

### Expected behaviour

Following is expected :

* By default the plugin(vmq_http_pub) should not bound to any listener.
* Api must be restricted through Api Keys. 

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by mths1** [comment]
Thank you very much for reporting this. If the plugin is disabled (which it is by default) it is impossible to send data through the rest api. It it is enabled, I can confirm that vmq_http_pub is part of the default listerners, which is different than what is documented. I also consider to enforce API Keys as a best practice, so that there are secure defaults.

**Comment by mths1** [comment]
@ashishislive : It is merged to main. Would be great if you could test again.

**Comment by ioolkos** [comment]
@ashishislive 
Can you try adding an API key for your http_pub listener: `vmq-admin api-key create scope=httppub` and then use that in the request?
(docs: https://docs.vernemq.com/v/master/live-administration/http-administration)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ashishislive** [comment]
The issue is resolved after using `scope=httppub`, apikey created without scope does not work (expected as it belong to different module). Although I did not find any document about httppub scope. I think there is room for improvement in documentation.

**Comment by ashishislive** [comment]
Original issue is resolved hence closing the issue with following notes:

* Default http listener no longer part of **vmq_http_pub** (expected)
* Scope specific (**httppub**) Api key required for authentication (expected) 

There is room for improvement in documentation for the same.

**Comment by ioolkos** [comment]
@ashishislive Thanks for testing & apologies for the missing docs.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
