### ISSUE TITLE
[Bug]: <title>HIGH CPU for VerneMQ (beam.smp)

### ISSUE THREAD

**Issue by nicolas8517** [vernemq/vernemq#2258]
### Environment

- VerneMQ Version: 1.13.0
- OS: Ubuntu 20.04.6 LTS
- Cluster size/standalone: 2

### Current Behavior

![image](https://github.com/vernemq/vernemq/assets/160510806/6f6be34a-c387-48a9-96ca-b510216ab05f)

I have no idea the reason of this High CPU usage

last logs from error.log

2024-02-19 13:53:58.232 [error] <0.25176.0>@vmq_queue:wait_for_offline:{379,5} got unknown sync event in wait_for_offline state {cleanup,session_taken_over}
2024-02-19 13:53:59.338 [error] <0.25176.0>@vmq_queue:wait_for_offline:{379,5} got unknown sync event in wait_for_offline state {cleanup,session_taken_over}
2024-02-19 13:53:59.902 [error] <0.25176.0>@vmq_queue:wait_for_offline:{379,5} got unknown sync event in wait_for_offline state {cleanup,session_taken_over}
2024-02-19 13:59:49.817 [error] <0.3514.1>@vmq_queue:wait_for_offline:{379,5} got unknown sync event in wait_for_offline state {cleanup,session_taken_over}
2024-02-19 14:42:43.458 [error] <0.3063.3>@vmq_queue:wait_for_offline:{379,5} got unknown sync event in wait_for_offline state {cleanup,session_taken_over}
2024-02-19 14:42:46.826 [error] <0.3063.3>@vmq_queue:wait_for_offline:{379,5} got unknown sync event in wait_for_offline state {cleanup,session_taken_over}

from console.log

*4-02-19 15:13:25.872 [info] <0.17513.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta9: AE exchange with 'VerneMQ@*.*.*.*' synced 2 objects
*4-02-19 15:13:32.013 [info] <0.17594.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta6: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:13:36.082 [info] <0.17693.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta2: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:13:44.717 [info] <0.178*.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta*: AE exchange with 'VerneMQ@*.*.*.*' synced 3 objects
*4-02-19 15:13:46.163 [info] <0.17801.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta6: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:14:12.936 [info] <0.18112.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta9: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:14:41.520 [info] <0.19*0.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta2: AE exchange with 'VerneMQ@*.*.*.*' synced 3 objects
*4-02-19 15:14:41.600 [info] <0.19057.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta1: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:14:55.163 [info] <0.19578.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta*: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:14:56.302 [info] <0.19540.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta5: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:14:57.739 [info] <0.19600.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta7: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:15:12.223 [info] <0.19754.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta5: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:15:41.999 [info] <0.20880.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta1: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects
*4-02-19 15:15:45.157 [info] <0.20922.4>@vmq_swc_exchange_fsm:teardown:{187,13} Replica meta9: AE exchange with 'VerneMQ@*.*.*.*' synced 1 objects

### Expected behaviour

normal cpu usage

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@nicolas8517 First possibility is clients racing themselves (re-connecting before they get a CONNACK, ending up on the other broker node, triggering queue migration etc.)

The second possibility is that you had a restart or "cluster leave" of one node with an unclean boot later. (example: node leaves the cluster, starts with previous state independently, re-joins the cluster. It should not do that, it should re-join empty. Second example: node stops, deletes state on disk, and then restarts)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by nicolas8517** [comment]
VerneMQ was working properly as standalone , but every time i did mount in cluster , CPU go high

But yes i did uninstall/reinstall and clean disk , for each node and mount as cluster looking good now will see
