### ISSUE TITLE
Support Alternative TCP listener with proxy protocol enabled by default 

### ISSUE THREAD

**Issue by ashtonian** [vernemq/vernemq#2263]
### Describe your issue or feature request

I'm using vernemq in a cluster behind an LB with the helm chart. The LB supports proxy protocol. The goal is to have external clients go through the proxy leveraging proxy protocol while internal services, primarily an ingest services, hit the cluster directly without proxy protocol. The technical desired use case is something like clients -> lb -> cluster <- ingest services 1:1 (vernemq container:ingest service).

This is currently difficult to do out of the box with the given default config and given helm chart. If I enable an alternative listener with proxy protocol on the docker image, because the helm chart leverages [a vernemq.sh](https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh#L204-L225) script that writes the IP address for each listener to the conf file, this would need modification to support this use case.

### Describe the solution you'd like

I would like the default vernemq config to expose a 2nd TCP listener that supports proxy protocol on port 1884 by default. The base docker image would need to expose this port. The helm chart would need an additional port on the statefulset, headless service, and the listener address written to the conf in the vernemq.sh. 

The removal of the dependency of the vernemq.sh for writing the IP to the config for listeners would be a better solution as right now I don't think it supports adding additional listeners via docker env variables.  

### Describe alternatives you've considered

Forking the docker-vernemq repo and handling it all there, which is the current solution. See [PR](https://github.com/vernemq/docker-vernemq/pull/381).

### Environment

- VerneMQ Version: Latest
- OS: k8s
- Erlang/OTP version (if building from source): latest
- Cluster size/standalone: 3

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@ashtonian Thanks again for your suggestion. A question here, since you mention adding a listener over ENV vars is not possible. (which, I think, is not correct but maybe not convenient... or possibly not working as intended?)
The original idea was to allow for arbitrary additional config settings here: https://github.com/vernemq/docker-vernemq/blob/6608f86bfa9482fb7193827b9aed962cbc4006be/helm/vernemq/values.yaml#L227
Do you see this not working for listeners?

**Comment by ashtonian** [comment]
Thanks for looking at it!

You can add listeners over ENV however I think it breaks clustering without a corresponding entry [here](https://github.com/vernemq/docker-vernemq/blob/6608f86bfa9482fb7193827b9aed962cbc4006be/bin/vernemq.sh#L204-L226).

I think you need something like:
```
    if [ -z "$DOCKER_VERNEMQ_LISTENER__TCP__NEW" ]; then
 		echo "listener.tcp.new = ${IP_ADDRESS}:1884" >> ${VERNEMQ_CONF_FILE}
    fi
```

**Comment by ioolkos** [comment]
Ok, so basically this is about having the correct dynamic IP address for a listener in the vernemq.conf file.

For non-Helm deployments we have the option of a `vernemq.conf.local file`:

> If using an vernemq.conf.local file, you can insert a placeholder (`###IPADDRESS###`) in your config to be replaced (at POD creation time) with the actual IP address of the POD vernemq is running on, making VMQ clustering possible.

That's probably currently not compatible with Helm (but might be worth looking into). The thing is that we need some sort of general solution to adding listeners in a Helm deployment. Adding single additional services/ports/edits to `vernemq.sh` does not seem sufficiently generic. It's a bit strange... we can't be the first with that problem, can't we :)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
I've just seen that HAProxy uses an approach with a literal config in `values.yaml`. Just want to note the idea here.
https://github.com/haproxytech/helm-charts/blob/595ce873c59d281d13aa212c252f76b414f4a701/haproxy/values.yaml#L222

Another idea for additional "free" listeners is to enable them dynamically.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ashtonian** [comment]
What would you think about adding a env variable that contains commands for the vernemq.sh to parse and execute? Alternatively could also adjust that script to follow the convention established by the broker and look for listeners with the same pattern and if it sees one, write the ip address line.

**Comment by ioolkos** [comment]
Patterns (If we can make it work) looks like a logical and valid approach too. 

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
