### ISSUE TITLE
Seeing various messages in the logs when under load

### ISSUE THREAD

**Issue by wernermorgenstern** [vernemq/vernemq#2274]
### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Current Behavior

We see log messages similar to below.

This is what we are doing:
25 Clients sending messages.  Each has 1000 Devices, sending at a rate of every 10 seconds (6 per minute).
So combined, 25000 every 10 seconds (each Device is a different time when it sends the message)

2 Clients, subscribing to the topic.

### Expected behaviour

What can we do to fine-tune?

### Configuration, logs, error output, etc.

```markdown
monitor busy_port <0.6696.48> [{initial_call,{vmq_ranch,init,4}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.432131>  

monitor got {suppressed,port_events,2} 

[warning] Subquery failed due to timeout
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@wernermorgenstern This is likely coming from the ports of your outgoing sessions (the 2 consumers).
You're probably not yet getting disconnects, though.
I cannot give you an elaborated recipe here, but a couple of keywords to look into:
- configuring adapted TCP buffers (`buffer_sizes`, `tcp_listen_options`, maybe increasing `high_watermark` setting using `tcp_listen_options`)
- increasing the non-acked inflight window (but only if your messages use QoS > 0)
- using shared subscriptions to have consumer side load balancing between multiple consumer instances

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by wernermorgenstern** [comment]
Thank you.  
We do use shared subscriptions.  So that is good.

Here is our config:
DOCKER_VERNEMQ_MAX_MESSAGE_RATE = 0
DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES = 0
DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES = 1000
DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES = 1000
DOCKER_VERNEMQ_SHARED_SUBSCRIPTION_POLICY = prefer_local
DOCKER_VERNEMQ_UPGRADE_OUTGOING_QOS = off
DOCKER_VERNEMQ_COORDINATE_REGISTRATIONS = on
DOCKER_VERNEMQ_QUEUE_TYPE = lifo
DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS = 400
DOCKER_VERNEMQ_TCP_LISTEN_OPTIONS = [{sndbuf, 32768}, {recbuf, 32768}, {buffer, 65536}, {nodelay, true}, {linger, {true, 10}}, {send_timeout, 30000}, {send_timeout_close, true}]

systree_enabled = on
systree_interval = 20000
graphite_interval = 100000
plugins.vmq_bridge = off
plugins.vmq_webhooks = off
vmq_bcrypt.pool_size = 1
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 20


Our QoS is 1.

How would I configure these two options:
```
- configuring adapted TCP buffers (buffer_sizes, tcp_listen_options, maybe increasing high_watermark setting using tcp_listen_options)
- increasing the non-acked inflight window (but only if your messages use QoS > 0)
```
