### ISSUE TITLE
[Bug]: VerneMQ Certificates for testing expired

### ISSUE THREAD

**Issue by mths1** [vernemq/vernemq#2276]
### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Current Behavior

Integration broken due to expired certificates. The client.crt and server.crt used for testing need a renewal. (Good news is: The testing of the validity works :-) )

Unfortunately, I do not have time at the moment to fix this right away, so maybe someone else does...

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=CH, ST=Basel-Town, O=Erlio MQTT Project, OU=Testing, CN=Signing CA
        Validity
            Not Before: Apr  8 08:18:22 2019 GMT
            Not After : Apr  6 08:18:22 2024 GMT
```

### Expected behaviour

vmq_ssl_SUITE works

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@mths1 Thanks, I'll fix it :)
