### ISSUE TITLE
vernemq-1.13.0.bullseye.arm64.tar.gz support Ubuntu aarch64?

### ISSUE THREAD

**Issue by 805728578** [vernemq/vernemq#2279]
### Describe your issue or feature request

vernemq-1.13.0.bullseye.arm64.tar.gz support Ubuntu aarch64?

### Describe the solution you'd like

it support Ubuntu aarch64

### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Add any other context, code samples or screenshots about the issue report here.

```markdown
VerneMQ Version:1.13.0
OS: Ubuntu 20.04 aarch64
Cluster size: 3 nodes
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@805728578 Thank you for expressing an interest in ARM64 Ubuntu packages. For `1.13` we have ARM support in the Docker image. If the need for users is there, we'll certainly build ARM `.deb` and `rpm``s as well in the future. I'll see what to do about `1.13`, maybe the Docker image can help in the meantime.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by JoeBlackZ** [comment]
Hopefully an Ubuntu focal arm version or a generic Linux version will be available. @ioolkos

**Comment by 805728578** [comment]
When is the plan to build ARM .deb？

**Comment by ioolkos** [comment]
@JoeBlackZ yes, a Focal ARM version will be included
@805728578 builder scripts/infra are adapted... will upload as the binaries come in. (it takes forever... our ARM infra is on the slower side, but all should be up in the coming days)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@JoeBlackZ @805728578 I've now pushed Ubuntu Focal (& more) ARM64 versions for 2.0.0: https://github.com/vernemq/vernemq/releases/tag/2.0.0

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by JoeBlackZ** [comment]
> @JoeBlackZ @805728578 I've now pushed Ubuntu Focal (& more) ARM64 versions for 2.0.0: https://github.com/vernemq/vernemq/releases/tag/2.0.0
> 
> 👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq 👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

That's great. Thanks. @ioolkos
