### ISSUE TITLE
Log format "JSON" also for Console Logging

### ISSUE THREAD

**Issue by hsudbrock** [vernemq/vernemq#2295]
### Describe your issue or feature request

Currently, the JSON log format can be configured for file-based logging, but not for console/stdout logging. As kubernetes expects logs on stdout, and log management systems usually ingest logs structured as JSON, it would be useful if the JSON log format could also be configured for console/stdout logging (for systems where vernemq is run inside a kubernetes cluster).

### Describe the solution you'd like

A new configuration parameter for setting the log format for console logging could be introduced (similar to the parameters `log.console.file.format` and `log.error.file.format`); the value of this config parameter would be used [here](https://github.com/vernemq/vernemq/blob/main/files/vmq.schema#L228-L243) for configuring the console logger.

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@hsudbrock Thanks, makes sense to me as well.
@mths1 back when you added this, did you see specific issues with logging JSON directly to console? (just to be sure... I guess we just did not need it or think of it)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
No objections. Want to give it a try @hsudbrock ? There should be not much more to do than add a Parameter to the config schema and adjust the Code you have already found :)

**Comment by hsudbrock** [comment]
I will, thanks @mths1.
