### ISSUE TITLE
500 server error in publish response (vmq_http_pub)

### ISSUE THREAD

**Issue by ioolkos** [vernemq/vernemq#2296]
User reported issue: the following log lines happening for every Rest publish, using `vmq_http_pub`

>  "2024-05-24T17:17:46.947Z","""DELETED""","""DELETED""","Ranch listener {{0,0,0,0},8110}, connection process <0.21389.1>, stream 1 had its request process <0.21390.1> exit with reason badarg and stacktrace [{persistent_term,get,[vmq_http_pub_sup],[{error_info,#{module => erl_erts_errors}}]},{vmq_http_pub_sup,incr_metric,2,[{file,""/opt/vernemq/apps/vmq_http_pub/src/vmq_http_pub_sup.erl""},{line,57}]},{vmq_http_pub,publish,4,[{file,""/opt/vernemq/apps/vmq_http_pub/src/vmq_http_pub.erl""},{line,88}]},{vmq_http_pub,process_post,2,[{file,""/opt/vernemq/apps/vmq_http_pub/src/vmq_http_pub.erl""},{line,490}]},{cowboy_rest,call,3,[{file,""/opt/vernemq/_build/default/lib/cowboy/src/cowboy_rest.erl""},{line,1583}]},{cowboy_rest,process_content_type,3,[{file,""/opt/vernemq/_build/default/lib/cowboy/src/cowboy_rest.erl""},{line,1096}]},{cowboy_rest,upgrade,4,[{file,""/opt/vernemq/_build/default/lib/cowboy/src/cowboy_rest.erl""},{line,284}]},{cowboy_stream_h,execute,3,[{file,""/opt/vernemq/_build/default/lib/cowboy/src/cowboy_stream_h.erl""},{line,306}]}]"
"2024-05-24T17:17:46.947Z","""DELETED""","""DELETED""","exception error: bad argument: [{persistent_term,get,[vmq_http_pub_sup],[{error_info,#{module => erl_erts_errors}}]},{vmq_http_pub_sup,incr_metric,2,[{file,""/opt/vernemq/apps/vmq_http_pub/src/vmq_http_pub_sup.erl""},{line,57}]},{vmq_http_pub,publish,4,[{file,""/opt/vernemq/apps/vmq_http_pub/src/vmq_http_pub.erl""},{line,88}]},{vmq_http_pub,process_post,2,[{file,""/opt/vernemq/apps/vmq_http_pub/src/vmq_http_pub.erl""},{line,490}]},{cowboy_rest,call,3,[{file,""/opt/vernemq/_build/default/lib/cowboy/src/cowboy_rest.erl""},{line,1583}]},{cowboy_rest,process_content_type,3,[{file,""/opt/vernemq/_build/default/lib/cowboy/src/cowboy_rest.erl""},{line,1096}]},{cowboy_rest,upgrade,4,[{file,""/opt/vernemq/_build/default/lib/cowboy/src/cowboy_rest.erl""},{line,284}]},{cowboy_stream_h,execute,3,[{file,""/opt/vernemq/_build/default/lib/cowboy/src/cowboy_stream_h.erl""},{line,306}]}]"
"2024-05-24T17:17:45.625Z","""DELETED""","""DELETED""","Cowboy stream 1 with ranch listener {{0,0,0,0},8110} and connection process <0.21389.1> had its request process exit with reason: bad argument in call to persistent_term:get(vmq_http_pub_sup) in vmq_http_pub_sup:incr_metric/2 line 57"

The configuration is:

>    DOCKER_VERNEMQ_PLUGINS__VMQ_HTTP_PUB: 'on'
      DOCKER_VERNEMQ_LISTENER__HTTP__HTTP_PUB: '0.0.0.0:8110'
      DOCKER_VERNEMQ_LISTENER__HTTP__HTTP_PUB__HTTP_MODULE__VMQ_HTTP_PUB__AUTH__MODE: 'apikey'
      DOCKER_VERNEMQ_LISTENER__HTTP__HTTP_PUB__HTTP_MODULES: 'vmq_http_pub'
      DOCKER_VERNEMQ_LISTENER__HTTP__HTTP_PUB__HTTP_MODULES__VMQ_HTTP_PUB__MQTT_AUTH__MODE: 'on-behalf-of'

The publishs use basic auth with an httppub scoped API key and setting the Content-Type header to `application/octet-stream`
The post uses headers for retain, QoS, topic, user, password, client_id and the body of the request is the binary blob.

Maybe this is some sort of race conditions in the metrics accounting in the `vmq_http_pub_sup` module. I need to set up a test to try to reproduce this.

@mths1 does this ring any bell with you?

**Comment by mths1** [comment]
Hello  @ioolkos , this is the typical error when oneforgets to set vmq_http_pub on. Can you check that it is really enabled?

The error can be reproduced with

```
#plugins.vmq_http_pub = on
listener.http.http_pub = 127.0.0.1:3001
listener.http.http_pub.http_module.vmq_http_pub.auth.mode = noauth
listener.http.http_pub.http_modules = vmq_http_pub
allow_anonymous = on

```

with

`curl --request POST \
  --url http://127.0.0.1:3001/restmqtt/api/v1/publish \
  --header 'Authorization: Basic ...' \
  --header 'Content-Type: application/json' \
  --data '{
	"topic": "T1",
	"user": "myuser",
	"password": "test123",
	"client_id": "myclient",
	"qos": 1,
	"retain": false,
	"payload": "asddsadsadas22dasasdsad",
	"user_properties": [{"a":"b"}]
}'`

**Comment by ioolkos** [comment]
@mths1 Thanks! Was thinking the same and checked what happens with a disabled plugin (but not seeing the exact same error). If this reoccurs, we can investigate logs hopefully. If it's not a config thing, then something must have crashed the application.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
@ioolkos : Did this happen in production or when setup the node? Never seen that in production - the supervisor itself doesn't do much.

**Comment by ioolkos** [comment]
@mths1 it was captured in integration testing. If at all, we could catch the caller of `persistent_term:get/1` and log that the plugin is not running. This will still spam the logs, of course.
Let's see if more will be discovered on this. I think for now we can leave it as is.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
Closing for now, as the issue seems to have been that  `vmq_http_pub` plugin was not running.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
