### ISSUE TITLE
 MQTT Client  Authentication getting failed due to plugin_chain_exhausted 

### ISSUE THREAD

**Issue by lakshmisivareddy** [vernemq/vernemq#2302]
### Environment

docker-compose yaml:

version: '3.5'
services:
  mosquitto:
    container_name: vernemq
    image: vernemq/vernemq
    volumes:
      - ./vernemq.conf:/vernemq/etc/vernemq.conf
      - ./certs:/etc/vernemq/certs
    ports:
      - '8884:8883'
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_PLUGINS.vmq_diversity=off

vernemq.conf:

listener.ssl.default = 0.0.0.0:8883
listener.ssl.cafile = /etc/vernemq/certs/ca.crt
listener.ssl.certfile = /etc/vernemq/certs/server.crt
listener.ssl.keyfile = /etc/vernemq/certs/server.key
listener.ssl.default.require_certificate = on
listener.ssl.default.use_identity_as_username = on
log.console = console
log.console.level = info
plugins.vmq_diversity = on
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off
vmq_diversity.auth_cockroachdb.enabled = off

Error :
vernemq      | 2024-05-27T03:49:11.752627+00:00 [info] <0.309.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/1"
vernemq      | 2024-05-27T03:49:11.755971+00:00 [info] <0.310.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/2"
vernemq      | 2024-05-27T03:49:11.757827+00:00 [info] <0.311.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/3"
vernemq      | 2024-05-27T03:49:11.759431+00:00 [info] <0.312.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/4"
vernemq      | 2024-05-27T03:49:11.761667+00:00 [info] <0.313.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/5"
vernemq      | 2024-05-27T03:49:11.763090+00:00 [info] <0.314.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/6"
vernemq      | 2024-05-27T03:49:11.765078+00:00 [info] <0.315.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/7"
vernemq      | 2024-05-27T03:49:11.766908+00:00 [info] <0.316.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/8"
vernemq      | 2024-05-27T03:49:11.770097+00:00 [info] <0.317.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/9"
vernemq      | 2024-05-27T03:49:11.771873+00:00 [info] <0.318.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/10"
vernemq      | 2024-05-27T03:49:11.773864+00:00 [info] <0.319.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/11"
vernemq      | 2024-05-27T03:49:11.775576+00:00 [info] <0.320.0> vmq_storage_engine_leveldb:open_db/4:146: Opening LevelDB database at "./data/msgstore/12"
vernemq      | 2024-05-27T03:49:11.796440+00:00 [info] <0.202.0> vmq_message_store:start/0:32: Trying to start vmq_generic_msg_store: ok
vernemq      | 2024-05-27T03:49:11.856317+00:00 [info] <0.409.0> vmq_reg_trie:handle_info/2:256: loaded 0 subscriptions into vmq_reg_trie
vernemq      | 2024-05-27T03:49:11.857591+00:00 [info] <0.212.0> vmq_cluster:init/0:165: cluster event handler 'vmq_cluster' registered
vernemq      | 2024-05-27T03:49:14.554343+00:00 [warning] <0.608.0> vmq_mqtt_fsm:check_user/2:735: can't authenticate client {[],<<"IOT-MQTT-CLIENT">>} from 192.168.65.1:45631 due to plugin_chain_exhausted
vernemq      | 2024-05-27T03:49:15.576070+00:00 [warning] <0.612.0> vmq_mqtt_fsm:check_user/2:735: can't authenticate client {[],<<"IOT-MQTT-CLIENT">>} from 192.168.65.1:45632 due to plugin_chain_exhausted
vernemq      | 2024-05-27T21:52:26.699041+00:00 [warning] <0.6241.0> vmq_mqtt_fsm:check_user/2:735: can't authenticate client {[],<<"IOT-MQTT-CLIENT">>} from 192.168.65.1:50249 due to plugin_chain_exhausted
vernemq      | 2024-05-27T21:52:27.727119+00:00 [warning] <0.6245.0> vmq_mqtt_fsm:check_user/2:735: can't authenticate client {[],<<"IOT-MQTT-CLIENT">>} from 192.168.65.1:50250 due to plugin_chain_exhausted
c

### Current Behavior

MQTT Client not able to connect with broker 

### Expected behaviour

MQTT Client Should Connect to broker and publish messages 

### Configuration, logs, error output, etc.

```markdown
listener.ssl.default = 0.0.0.0:8883
listener.ssl.cafile = /etc/vernemq/certs/ca.crt
listener.ssl.certfile = /etc/vernemq/certs/server.crt
listener.ssl.keyfile = /etc/vernemq/certs/server.key
# listener.ssl.default.use_identity_as_username = on
listener.ssl.default.require_certificate = on
listener.ssl.default.use_identity_as_username = on


## Log configuration
log.console = console
log.console.level = info

plugins.vmq_diversity = on


vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off
vmq_diversity.auth_cockroachdb.enabled = off
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@lakshmisivareddy which of the auth plugins do you want to use, though? it is unclear from your snippets.

Should you want to use no authentication plugin (because you use client certs), you'll have to make sure you have the following lines in your config.

```
allow_anonymous = off
listener.ssl.default.allow_anonymous_override = on
```
The second line should only be used in combination with listeners that require a client certificate. In that case, you can decide to shortcut the MQTT authentication because the SSL client cert is enough of proof of identity. This is what `allow_anonymous_override` does.
Note that you'll still need an _authorization_ plugin, I assume this is `vmq_acl` in your case here.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by lakshmisivareddy** [comment]
Thanks for the help @ioolkos 
it worked for me

**Comment by lakshmisivareddy** [comment]
issue got resolved
