### ISSUE TITLE
[Bug]: plugins.vmq_webhooks is on but not triggering HTTP endpoint

### ISSUE THREAD

**Issue by SameerTi** [vernemq/vernemq#2309]
### Environment

- VerneMQ Version: 1.9.2
- OS: RHEL 7
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Current Behavior

I have following set in my vernemq.conf file:

plugins.vmq_webhooks = on
plugins.vmq_diversity = on
plugins.vmq_acl = off

vmq_webhooks.webhook1.hook = auth_on_register_m5
vmq_webhooks.webhook1.endpoint = http://localhost:7033/uspauth/verify

I have written my HTTP endpoint in java and works well when triggered from mozzila's REST Client, it does not require username/password to trigger this endpoint.

However, my endpointId is not triggered when vernemq Hook "auth_on_register_m5" is getting called.

Attached my vernemq conf file for reference.
[vernemq.zip](https://github.com/user-attachments/files/15605408/vernemq.zip)

I tried tcpdump on my endpoint"s port "7033" however I see no trace about this being called.

### Expected behaviour

Expecting my endpoint "http://localhost:7033/uspauth/verify" to trigger when vernemq Hook "auth_on_register_m5" gets called.

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@SameerTi can you ensure plugin load priority by:

```
plugins.vmq_webhooks.priority = 1
plugins.vmq_diversity.priority = 2
```
Also, are you sure vmq_passwd is off?

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by SameerTi** [comment]
Thanks @ioolkos , setting priority helped.
Now next up is to be able to call my API over HTTP(s) to my application, that's deployed on Oracle's weblogic app server

**Comment by ioolkos** [comment]
@SameerTi I suppose I can close the issue. 

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
