### ISSUE TITLE
how to read the retain messages stored in the leveldb of vernemq

### ISSUE THREAD

**Issue by pine797** [vernemq/vernemq#2315]
### Describe your issue or feature request

Hi, I would like to ask a question, is it possible?
vernemq uses leveldb to store some data such as retain messages. 
I have a project requirement to be able to get information about the retain messages stored by vernemq, and I noticed that data/ seems to be the directory of the database, but I don't know how to read the retention messages in it, is it possible to achieve this?

### Describe the solution you'd like

I tried using Python to read the leveldb, but it doesn't seem to work

```python
import plyvel

db = plyvel.DB('/path/data/', create_if_missing=False)
print(db)

for key, value in db:
    print(f'Key: {key.decode("utf-8")}, Value: {value.decode("utf-8")}')

db.close()

```

### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Code of Conduct

- [x] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
`vmq-admin retain show --help`

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
