### ISSUE TITLE
[Bug]: Vernemq webhooks not supporting HTTP(s)

### ISSUE THREAD

**Issue by SameerTi** [vernemq/vernemq#2330]
### Environment

- VerneMQ Version: 1.9.2
- OS: Linux
- Erlang/OTP version (if building from source): n/a
- Cluster size/standalone: standalone

We are using Webhooks and have following configuration for the same:

plugins.vmq_webhooks = on                                                                                             
plugins.vmq_diversity.priority = 2                                                                                     
plugins.vmq_webhooks.priority = 1                                                                                  
vmq_webhooks.webhook1.hook = auth_on_register_m5                        
vmq_webhooks.webhook1.endpoint = http://localhost:7033/xxx/users

Everything works fine, with above and we are able to trigger out endpoint and get the job done.

However, we want to be able to call our APIs, over HTTP(s), hence we configured following:

vmq_webhooks.cafile = cacerts.pem
vmq_webhooks.tls_version = tlsv1.2
vmq_webhooks.certfile = client.pem
vmq_webhooks.keyfile = client.key.pem
vmq_webhooks.verify_peer=off

Upon adding above, we start getting following errors on start:

`
[vernemq]# systemctl status vernemq.service
* vernemq.service - VerneMQ Server
   Loaded: loaded (/etc/systemd/system/vernemq.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2024-07-10 07:46:37 CDT; 37s ago
  Process: 53834 ExecStop=/bin/sh -c while ps -p $MAINPID >/dev/null 2>&1; do sleep 1; done (code=exited, status=0/SUCCESS)
  Process: 53581 ExecStop=/usr/lib64/vernemq/bin/vernemq stop (code=exited, status=0/SUCCESS)
  Process: 18088 ExecStart=/usr/lib64/vernemq/bin/vernemq start (code=exited, status=0/SUCCESS)
  Process: 53907 ExecStartPre=/usr/lib64/vernemq/bin/vernemq chkconfig (code=exited, status=1/FAILURE)
Main PID: 18213
 
Jul 10 07:46:36 app144 vernemq[53907]: 07:46:36.486 [error] Conf file attempted to set unknown variable: vmq_webhooks.verify_peer
Jul 10 07:46:36 app144 vernemq[53907]: 07:46:36.486 [error] Conf file attempted to set unknown variable: vmq_webhooks.keyfile
Jul 10 07:46:36 app144 vernemq[53907]: 07:46:36.487 [error] Conf file attempted to set unknown variable: vmq_webhooks.certfile
Jul 10 07:46:36 app144 vernemq[53907]: 07:46:36.487 [error] Conf file attempted to set unknown variable: vmq_webhooks.tls_version
Jul 10 07:46:36 app144 vernemq[53907]: 07:46:36.487 [error] Conf file attempted to set unknown variable: vmq_webhooks.cafile
Jul 10 07:46:37 app144 vernemq[53907]: Error generating config with cuttlefish
Jul 10 07:46:37 app144 systemd[1]: vernemq.service: control process exited, code=exited status=1
Jul 10 07:46:37 app144 systemd[1]: Failed to start VerneMQ Server.
Jul 10 07:46:37 app144 systemd[1]: Unit vernemq.service entered failed state.
Jul 10 07:46:37 app144 systemd[1]: vernemq.service failed.

`

### Current Behavior

Vernemq webhooks not supporting HTTP(s)

### Expected behaviour

Vernemq webhooks should support HTTP(s)

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
HTTPS support for WebHooks was added in `1.12.0`.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by SameerTi** [comment]
Thanks @ioolkos for prompt response, If I'm not wrong, beyond vernemq 1.9.0 it's licensed? please confirm!!
If, upgrading vmq beyond 1.9.0 isn't an option, is there any alternative solution to this problem?

**Comment by ioolkos** [comment]
@SameerTi using the official binary packages from 1.10.0 requires a paid subscription, yes.
You can compile your own version from the source code.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by subhasniveus** [comment]
May i know where can we find the documentation for HTTP(s) support? @ioolkos We are facing bad key issues. I believe we are providing some invalid properties. Documentation will help.

**Comment by ioolkos** [comment]
@subhasniveus I've re-added a short section on HTTPS: https://docs.vernemq.com/plugin-development/webhookplugins
For a minimal config, you have to add a CAFile. If things do not work, please share your config.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by subhasniveus** [comment]
> @subhasniveus I've re-added a short section on HTTPS: https://docs.vernemq.com/plugin-development/webhookplugins For a minimal config, you have to add a CAFile. If things do not work, please share your config.
> 
> 👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq 👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

Thanks @ioolkos . This helps a lot. However, if we specify verify_peer to be off, still do we require CAFile? From the schema it looks it has a default "empty".

**Comment by ioolkos** [comment]
@subhasniveus oh, wait, is it possible we need to adapt to OTP 26 here *again* (for stuff like `verify_peer`/`customize_hostname_check`). Apologies if that should be the case. You can compile on OTP 25, though.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
