### ISSUE TITLE
[Bug]: vmq-diversity Lua language. The os.time function generates a current epoch timestamp when given a specific date.

### ISSUE THREAD

**Issue by rodrigoaasm** [vernemq/vernemq#2331]
### Environment

- VerneMQ Version: 1.10.0
- OS: Alpine 3.14
- Erlang/OTP version (if building from source): otp22-patched-alpine
- Cluster size/standalone: standalone

### Current Behavior

The os.time function, when provided with a specific date in Lua, generates an epoch timestamp representing the current time instead of the specified date.

```
local t_date = {
    year = 2014,
    month = 07,
    day = 01,
    hour = 10,
    min = 49,
    sec = 30,
    isdst = false
}
local timestamp = os.time(t_date)
```
The code was executed in a Lua interpreter and worked as expected.

### Expected behaviour

The os.time function should generate an epoch timestamp based on the specific date provided.

### Configuration, logs, error output, etc.

```markdown
metadata_plugin = vmq_swc
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.dojot_disconnect_plugin.path = /vernemq/dojot_disconnect_plugin/default
plugins.dojot_disconnect_plugin = off
plugins.dojot_disconnect_plugin.priority = 2
plugins.vmq_diversity = on
vmq_diversity.pailot_acl_plugin.file = /vernemq/pailot_acl_plugin/pailot_acl_plugin.lua
leveldb.maximum_memory.percent = 20
log.console = console
log.console.level= debug
listener.max_connections = 200000
listener.nr_of_acceptors = 100
max_inflight_messages = 20
max_online_messages = 10000
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@rodrigoaasm Thanks, I see you already opened an issue on Luerl, therefore I'll close it here. I don't think we use `os.time` in our Lua plugins, so I never noticed this behaviour before.

This Luerl issue has a bit more info: https://github.com/rvirding/luerl/issues/116

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by rodrigoaasm** [comment]
Ok. Thanks.
