### ISSUE TITLE
shared_subscriptions - not working Vernemq 1.9.0

### ISSUE THREAD

**Issue by SameerTi** [vernemq/vernemq#2338]
### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Current Behavior

Hi,

- VerneMQ Version: 1.9.x
- OS: Linux

I used following to publish:

:~# mosquitto_pub -h 127.0.0.1 -p 1883 -u abc -P abc -t  /dc/WG/topic/stomp/blah/ -m "This is a test message" --protocol-version mqttv5

and 2 instances of following to subscribe:
mosquitto_sub -h 127.0.0.1 -p 1883 -u abc -P abc -t /dc/WG/topic/stomp/blah/ --protocol-version mqttv5

Observation: Both subscriber instances got the message "This is a test message"

Now, I wanted to use shared subscription such that, only one subscriber gets it in one time, and next message goes to other subscriber and so on...

hence, I modified my subscriber mosquitto command as this:
mosquitto_sub -h 127.0.0.1 -p 1883 -u abc -P abc -t /$dc/WG/topic/stomp/blah/ --protocol-version mqttv5

however, It stopped delivering any message to subscriber:

I followed this link: https://docs.vernemq.com/v/1.9.0/configuration/shared_subscriptions

my vernemq conf has this:
shared_subscription_policy = prefer_local

### Expected behaviour

Expectation is:  With shared subscription topic, each message should be received by only one subscriber.

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
The doc has literal examples for mosquitto_pub and sub commands.
https://docs.vernemq.com/v/1.9.0/configuration/shared_subscriptions#examples

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by SameerTi** [comment]
Yeah, immediately after posting this issue.. I realized that 
Subscriber needs to use: \$share/group in front and published needs to remove "/" from front... only then it works
