### ISSUE TITLE
Misconfigured MYSQL2 causes badmatch error

### ISSUE THREAD

**Issue by chile12** [vernemq/vernemq#2339]
### Environment

- VerneMQ Version: 2.0.1
- OS: Ubuntu 22.04.4 LTS
- Erlang/OTP version (if building from source): 24
- Cluster size/standalone: standalone

### Current Behavior

Loading the mysql2.lua with an erroneous mysql2 configuration will cause the following error:
```log
vmq_diversity_script_state:init/1:111: can't load script "./share/lua/auth/mysql2.lua" due to {error,undef}
[error] <0.569.0> vmq_diversity_app:load_script/1:111: could not load script "./share/lua/auth/mysql2.lua" due to {{{badmatch,{error,{normal,{child,undefined,{vmq_diversity_script_state,1},{vmq_diversity_script_state,start_link,[1,"./share/lua/auth/mysql2.lua",<0.575.0>]},permanent,false,5000,worker,[vmq_diversity_script_state]}}}},[{vmq_diversity_script,setup_lua_states,3,[{file,"/vernemq-build/apps/vmq_diversity/src/vmq_diversity_script.erl"},{line,294}]},{vmq_diversity_script,init,1,[{file,"/vernemq-build/apps/vmq_diversity/src/vmq_diversity_script.erl"},{line,101}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{child,undefined,{vmq_diversity_script,"./share/lua/auth/mysql2.lua"},{vmq_diversity_script,start_link,["./share/lua/auth/mysql2.lua"]},permanent,false,5000,worker,[vmq_diversity_script]}}
```

background:
Connecting to mysql without ssl requires setting `vmq_diversity.mysql2.ssl = off` as it defaults to `on`.

Any other misconfiguration will likely cause a similar error.

### Expected behaviour

An error or log indicating an erroneous configuration, or generally more debug logs in the mysql2 extension.
I myself had to introduce additional log calls in vmq_diversity_mysql2.erl to get to the bottom of this.

### Configuration, logs, error output, etc.

```markdown
plugins.vmq_diversity = on
vmq_diversity.auth_mysql2.enabled = on
vmq_diversity.mysql2.host = mysql
vmq_diversity.mysql2.port = 3306
vmq_diversity.mysql2.user = root
vmq_diversity.mysql2.password = password
vmq_diversity.mysql2.database = db
vmq_diversity.mysql2.password_hash_method = sha256
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@chile12 Thanks for testing MySQL2! Yes, `vmq_diversity.mysql2.ssl = off` is the better default.
Also, thanks for your effort finding this, it *is* a pain to debug the scripts due to the embedded nature of the Lua interpreter.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@chile12 fyi, the specific fix (change of default) is merged. Let us know if you find additional non-intuitive combinations of the MySQL2 settings. Thanks again!

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
