### ISSUE TITLE
VerneMQ pod crash because of high cpu utilization

### ISSUE THREAD

**Issue by vshirol** [vernemq/vernemq#2341]
### Environment

- VerneMQ Version: 1.9.2
- OS: Linux
- Erlang/OTP version (if building from source):
- Cluster size/standalone:  8
- Container resources: Limits:
                                          cpu:     48
                                          memory:  192Gi
                                    Requests:
                                          cpu:      48
                                          memory:   192Gi
-  Clients Online: 520000 (across cluster and each pod has around 70k clients connected)

### Current Behavior

[crash.log](https://github.com/user-attachments/files/16562174/crash.log)
[crash.log](https://github.com/user-attachments/files/16562193/crash.log)
[crash-0.log](https://github.com/user-attachments/files/16562194/crash-0.log)
[crash-2.log](https://github.com/user-attachments/files/16562195/crash-2.log)
[error.log](https://github.com/user-attachments/files/16562196/error.log)
[error-0.log](https://github.com/user-attachments/files/16562197/error-0.log)
[error-2.log](https://github.com/user-attachments/files/16562199/error-2.log)

We observed two VerneMQ pods crashing with high CPU utilization, as indicated by the pod stats. This incident occurred on August 7, 2024, at 17:35:00 for one of the pods. Prior to the crash, there was a high connection rate across the cluster, approximately 500 connections per second, with the load distributed equally among all pods/nodes in the cluster.
I am attaching the error and crash logs from the pod that crashed on August 7, 2024, at 17:35:00, for your review. Please let us know what might have caused these VerneMQ pod crashes. If you need any additional information, such as configuration details, please feel free to ask.

### Expected behaviour

No errors in log.

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
Thanks. This is a support request for a rather big use case, running on a 5 year old VerneMQ version.
Unfortunately, we have no free bandwidth to analyse this within a Github issue. Feel free to reach out for commercial support.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
