### ISSUE TITLE
[Bug]: <title>Verneq service restart fails when there is a client connection and pending queue.

### ISSUE THREAD

**Issue by Shalimtomz** [vernemq/vernemq#2342]
### Environment

- VerneMQ Version: 1.13.0
- OS: Ubuntu 18.04
- Erlang/OTP version (if building from source):
- Cluster size/standalone: 2

### Current Behavior

Output of "vernemq restart" command

ok
=INFO REPORT==== 8-Aug-2024::04:15:01.182337 ===
Administrative stop
 vernemq failed to start within 15 seconds,
 see the output of 'vernemq console' for more information.
 If you want to wait longer, set the environment variable
 WAIT_FOR_ERLANG to the number of seconds to wait.

--------------------------------------------------------------------

when running "vernemq stop" command it prints 

ok
=INFO REPORT==== 8-Aug-2024::04:15:01.182337 ===
Administrative stop

and need to click Ctr + C to exit from the process.

--------------------------------------------------------------------

when removing "rm -rf /var/lib/vernemq/swc_meta/" directory, 
everything like
      - vernemq start
      - vernemq stop
      - vernemq restart 
works fine.

### Expected behaviour

vernemq restarts after running "vernemq restart" command.

### Configuration, logs, error output, etc.

```markdown
Output of console.log file

2024-08-08 04:13:03.945 [info] <0.168.0> alarm_handler: {set,{system_memory_high_watermark,[]}}
2024-08-08 04:15:01.182 [info] <0.403.0> Administrative stop
```

### Code of Conduct

- [x] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
If this is a cluster, you need to be aware of 2 points:
- If you stop and restart a cluster node, you need to keep it's metadata state (`swc_meta` directory)
- If you make a node leave the cluster, you can only re-join the cluster with fresh state, not the previous on-disk state

You might run into sync issues, when not observing those points. You might want to rebuild your cluster to ensure you start with a clean slate. 
A connection or a "pending queue" (not sure what you mean by that exactly) should not disallow/prevent a restart of a node, btw.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by mths1** [comment]
Additionaly, to what @ioolkos said, it sometimes make sense to just wait a little bit longer (as in increase WAIT_FOR_ERLANG) and see what happens...

**Comment by Shalimtomz** [comment]
Thanks, @ioolkos and @mths1 for your assistance.

Let me explain the issue in some more detail,

- pending queue -> messages queued.
- connections -> clients connection.

--------------------------------------------------------------------------------------------------------------------------------------------

Here, what I did is,

- I had a cluster with two nodes(node1 and node2), and clients were connected to both nodes, publishing and subscribing to the qos 2 messages.
- I disconnected one node, node2 from the cluster by running the command "vmq-admin cluster leave node=node2@<ip-addr> -k" in the terminal of node2.
- then I tried to restart the service in node1 with the command "vernemq restart". but it exists with the output,
                            ok
                            =INFO REPORT==== 8-Aug-2024::04:15:01.182337 ===
                            Administrative stop
                            vernemq failed to start within 15 seconds,
                            see the output of 'vernemq console' for more information.
                            If you want to wait longer, set the environment variable
                            WAIT_FOR_ERLANG to the number of seconds to wait.

- As @mths1 said I set WAIT_FOR_ERLANG variable to a value, 60 seconds. but the problem persists.
- Again, thank you for your assistance, I hope you understand the issue, and I am expecting your assistance in solving it.

**Comment by ioolkos** [comment]
How quickly do you restart node1 after the cluster leave? You should probably let the nodes sync before restarting node1.

You could use some command like:

```
vmq-admin cluster leave node=<NodeThatShouldGo> -k -i 5 -t 120
```
and `tail -f` to the console.log of node2 to see for how long you have queue migration going on.

How many persistent MQTT clients are we having here btw?

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
