### ISSUE TITLE
[Bug]: Cannot join a cluster, as local node if bridge plugin was enable

### ISSUE THREAD

**Issue by guillehuerta** [vernemq/vernemq#2350]
### Environment

- VerneMQ Version: 2.0.0
- OS: Linux / Kubernetes
- Erlang/OTP version (if building from source):
- Cluster size/standalone: 3 nodes

### Current Behavior

When trying to run VerneMQ in cluster mode on Kubernetes with the bridge plugin enabled, the node cannot join the current cluster because it is not empty.

[info] <0.197.0> vmq_message_store:start/0:32: Trying to start vmq_generic_msg_store: ok
[info] <0.406.0> vmq_reg_trie:handle_info/2:256: loaded 0 subscriptions into vmq_reg_trie
[info] <0.207.0> vmq_cluster:init/0:165: cluster event handler 'vmq_cluster' registered
[error] <0.422.0> vmq_ranch_config:reconfigure_listeners_for_type/4:302: can't reconfigure mqtt listener({127,0,0,1}, 1883) with Options [{max_connections,10000},{max_connection_lifetime,0},{nr_of_acceptors,10},{mountpoint,[]},{proxy_protocol,false},{allowed_protocol_versions,[3,4,5,131]},{allow_anonymous_override,false}] due to {already_started,<0.446.0>}
[info] <0.9.0> vmq_swc_peer_service:attempt_join/1:61: Cannot join a cluster, as local node 'VerneMQ@vernemq-2.vernemq-headless.namespace.svc.cluster.local' is non-empty.
[info] <0.633.0> vmq_bridge:handle_info/2:212: Bridge br0 connected to mqtt.com:8883.
[info] <0.644.0> vmq_bridge:on_subscribe/2:109: Bridge Pid <0.633.0> is subscribing to Topics: [{[<<"topic">>],0}]
[info] <0.697.0> vmq_swc_peer_service:attempt_join/1:61: Cannot join a cluster, as local node 'VerneMQ@vernemq-2.vernemq-headless.namespace.svc.cluster.local' is non-empty.
[info] <0.703.0> vmq_swc_peer_service:attempt_join/1:61: Cannot join a cluster, as local node 'VerneMQ@vernemq-2.vernemq-headless.namespace.svc.cluster.local' is non-empty.

We are unsure if this is the expected behavior, but the only solution we found was to avoid enabling the bridge initially and run the following commands after the node has joined the cluster properly:

` 
    vmq-admin plugin enable --name=vmq_bridge
    vmq-admin bridge start
`
This is the intended behavior or if there is a better approach to handle this situation?

### Expected behaviour

The node should join the cluster and the bridge should be up without additional intervention.

### Configuration, logs, error output, etc.

```markdown
Configuration:
Environment:
  MY_POD_NAME:                                                          vernemq-2 (v1:metadata.name)
  MY_POD_IP:                                                             (v1:status.podIP)
  DOCKER_VERNEMQ_DISCOVERY_KUBERNETES:                                  1
  DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR:                             app.kubernetes.io/name=vernemq,app.kubernetes.io/instance=vernemq
  DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST:                              127.0.0.1:1883
  DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT:                                $(MY_POD_IP):8883
  DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT:                                $(MY_POD_IP):8443
  DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT:                        on
  DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT:                         on
  DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT:                       on
  DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT:                     on
  DOCKER_VERNEMQ_VMQ_ACL__ACL_FILE:                                     /etc/vernemq/vmq.acl
  DOCKER_VERNEMQ_LISTENER__SSL__CAFILE:                                 /etc/ssl/vernemq/ca.crt
  DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE:                               /etc/ssl/vernemq/server.crt
  DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE:                                /etc/ssl/vernemq/server.key
  DOCKER_VERNEMQ_PLUGINS__VMQ_BRIDGE:                                   on
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0:                                  mqtt.com:8883
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__CLEANSESSION:                    off
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__CLIENT_ID:                       vernemq
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__KEEPALIVE_INTERVAL:              60
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__RESTART_TIMEOUT:                 10
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__TRY_PRIVATE:                     off
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__MAX_OUTGOING_BUFFERED_MESSAGES:  100
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__TOPIC__1:                        topic in
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__CAFILE:                          /etc/ssl/vernemq/ca.crt
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__CERTFILE:                        /etc/ssl/vernemq/server.crt
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__KEYFILE:                         /etc/ssl/vernemq/server.key
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__INSECURE:                        on
  DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__TLS_VERSION:                     tlsv1.2
  DOCKER_VERNEMQ_KUBERNETES_APP_LABEL:                                  vernemq
  DOCKER_VERNEMQ_KUBERNETES_NAMESPACE:                                  namespace (v1:metadata.namespace)
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@guillehuerta Good catch! it is expected, but of course an inconvenient situation. The self-check on the joining node ensures that the node has not seen any events (so that the cluster will not try to merge arbitrary separate history of events). And of course, the subscribing bridge plugin creates internal ClientID and subscriptions, so we already have a history before the node joins.

The clean solution is currently enabling the bridge plugin after the cluster join. You can still disable `prevent_empty_join` and see whether you'll have all the subscriptions (which is likely working).

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by guillehuerta** [comment]
@ioolkos  Thanks for the quick response!
We tried that but without success.
Could you please provide the environment property so we can test it in our Kubernetes deployment? We want to ensure we are using the correct environment settings.

**Comment by ioolkos** [comment]
The full setting is `vmq_swc.prevent_nonempty_join`, which you can translate to the ENV variable format as with your other vars.
Note:  (I made a typo in first response and corrected it)

For node joining, additional improvements are coming up which should benefit K8s use cases.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by guillehuerta** [comment]
Great, we will check it. Thanks for all your help and have a good day!
