### ISSUE TITLE
[Bug]: Duplicates not sent for MQTTv5 and QoS 1

### ISSUE THREAD

**Issue by pszafarczyk** [vernemq/vernemq#2353]
### Environment

- VerneMQ Version: 2.0.1-8-g61c1938f
- OS: Debian 12
- Erlang/OTP version (if building from source): 26.2.5
- Cluster size/standalone: standalone

### Current Behavior

MQTTv5: If a subscriber does not respond to a publish message with a ack, the broker never resends the message.
No matter how long the subscriber waits with sending the pub ack. Next messages are sent to the subscriber as they come.

MQTTv3.1.1: The message is resent with the DUP flag.

### Expected behaviour

The message should be resent for both versions.

### Configuration, logs, error output, etc.

```markdown
Connect Flags: 0xc2, User Name Flag, Password Flag, Will QoS Level: At most once delivery (Fire and Forget), Clean Session Flag
No properties

Subscription Options: 0x01, Retain Handling: Send msgs at subscription time, QoS: At least once delivery (Acknowledged deliver)
No properties

In Sub Ack: Granted QoS 1 (1)

Publish Header Flags: 0x33, Message Type: Publish Message, QoS Level: At least once delivery (Acknowledged deliver), Retain
or for not retained
Header Flags: 0x32, Message Type: Publish Message, QoS Level: At least once delivery (Acknowledged deliver)


bin/vmq-admin session show --client_id --statename --waiting_acks
+-----------+---------------------------------+--------------+
| statename | client_id                       | waiting_acks |
+-----------+---------------------------------+--------------+
| online    | mqtt-dup-test                   | 684          |
+-----------+---------------------------------+--------------+

Nothing in logs even with log.console.level = debug
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@pszafarczyk Please review the following section of the v5 spec: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901238

The behaviour has changed in v5 with the reasoning that the TCP stack already should not loose messages, although maybe the message might be waiting in a TCP buffer somewhere.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pszafarczyk** [comment]
@ioolkos Thanks. I did not know that.

What should happen with problems at an application level? What the subscriber should do?
If it sends an ACK and is not able to store all the messages coming, the messages will be lost.
Should it disconnect after any failure and reconnect (with Clean Start set to 0) to have them being resend?

**Comment by ioolkos** [comment]
@pszafarczyk MQTT is transfer or responsibility for messages. If your application has not yet seen a message from the TCP stack, there's not much use in sending it again within the same TCP session. With a new TCP session, the situation is different, therefore the requirement for the initial exchange for outstanding acks and messages.
If a consumer cannot keep up with incoming messages, you'll have to increase performance on the consumer or use consumer side load balancing (shared subscriptions).
I'm not convinced that disconnecting when the consumer has "troubles" of whatever sort is the way to go.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pszafarczyk** [comment]
@ioolkos Thanks a lot.

I meant troubles like a temporary database problem. Let's say the database is being rebooted. There is not much the subscriber can do. It just needs a moment to be able to precess the messages again.
