### ISSUE TITLE
[Bug]: NULL char in CONNECT packets

### ISSUE THREAD

**Issue by tiz314** [vernemq/vernemq#2355]
### Environment

- VerneMQ Version: 1.13.0
- OS: Debian 6.1.112-1 x86_64
- Cluster size/standalone: standalone

### Current Behavior

When sending a CONNECT packet, the broker ACKs the connection even if the clientID contains a NULL char. The client is then able to perform any expected operation like a client connected using a valid clientID. 

At the moment, no related vulnerabilities are known. 

### Expected behaviour

As stated at line 268, 274 and 3474 of the [MQTTv5 standard](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.pdf) if a packets contains an UTF-8 string that presents a NULL char it must be considered as a malformed packet, and if the broker receives a malformed packet it must close the connection. 

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@tiz314 Thanks, yes, we need to add the NULL check to the `ensure_utf8` functions in both parsers. Do you want to have a go at it? ;)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by tiz314** [comment]
Sure! If you want I'll make a PR :)
