### ISSUE TITLE
MongoDB 6 and newer removed old wire protocol

### ISSUE THREAD

**Issue by Climax777** [vernemq/vernemq#2357]
### Describe your issue or feature request

Since MongoDB 6 the old wire protocol has been removed. Therefore the MongoDB diversity plugin doesn't work with any recent MongoDB installations.

### Describe the solution you'd like

Please consider using the emqx fork https://github.com/emqx/mongodb-erlang

This fork of mongodb-erlang supports the modern database wire protocol

### Environment

- VerneMQ Version: all
- OS: any
- Erlang/OTP version (if building from source): 25.0
- Cluster size/standalone: N/A

### Add any other context, code samples or screenshots about the issue report here.

```markdown
https://github.com/comtihon/mongodb-erlang/issues/259
```

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@Climax777 Thanks, yeah, as you've probably seen the work by voluntary contributors on comtihon's MongoDB library is a bit stalled.
Have you tested the emqx fork already? Do you have options to help here (PR)?

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
I've added the `help wanted` label, especially looking for functional testing of PR https://github.com/vernemq/vernemq/pull/2358
- Do the MongoDB options still work?
- Does TLS work etc.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
