### ISSUE TITLE
[Bug]: Postgresql authentication with bcrypt doesn't work

### ISSUE THREAD

**Issue by agorunucu** [vernemq/vernemq#2360]
### Environment

- VerneMQ Version: 2.0.1
- OS: VerneMQ Docker
- Erlang/OTP version (if building from source):
- Cluster size/standalone: standalone

### Current Behavior

Postgresql authentication with bcrypt doesn't work.

### Expected behaviour

should work.

### Configuration, logs, error output, etc.

```markdown
The `method` variable in the auth_on_register_common() method changed to `local` in this commit: https://github.com/vernemq/vernemq/commit/4476607adf9c6f8ddde9a82310810db690c38ab7#diff-b0bb48cf169f144429a471fb5a175731d43c0038b2d22a94a71ffefbf9cdeaa7R145

The variable is also used in the `do_hash()` method later on. The do_hash always return false as the method becomes nil when the variable is set as local. 

Fix: removing `local` in line 145 fixes the problem. https://github.com/vernemq/vernemq/blob/a55ada8dfb6051362fcc468d888194bdcd6eb346/apps/vmq_diversity/priv/auth/postgres_cockroach_commons.lua#L145
```

### Code of Conduct

- [x] I agree to follow the VerneMQ's Code of Conduct

**Comment by agorunucu** [comment]
/cc @omar-mohamed-khallaf @ashtonian as the commit is related to you. 
Commit: https://github.com/vernemq/vernemq/commit/4476607adf9c6f8ddde9a82310810db690c38ab7

**Comment by ioolkos** [comment]
@agorunucu Thanks, wasn't aware of the regression there yet.
Do you like to provide a PR of your fix?

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by omar-mohamed-khallaf** [comment]
@agorunucu Can you please test #2361?

**Comment by agorunucu** [comment]
Tested, and working. Thanks!
