### ISSUE TITLE
Need to modify username from auth plugin (jwt webhooks)

### ISSUE THREAD

**Issue by ashtonian** [vernemq/vernemq#2366]
### Describe your issue or feature request

Hello,

I have clients with the same username and they pass a jwt in has the password. I'd like to set the username from the values of the jwt. Trying to write a plugin via the webhooks integration to enable this but I'm not sure its possible. Is there a way to modify the username on the auth hook?  What would it entail to add a field to the 'modifiers'?

I found some related issues:
https://github.com/vernemq/vernemq/issues/178, 
https://github.com/vernemq/vernemq/issues/208. 

### Describe the solution you'd like

I'd like to be able to modify more user properties from the auth hooks.

### Describe alternatives you've considered

May be able to accomplish this outside the hooks framework with a lower level plugin?, but all the auth examples I've been able to find are using the hooks. There is an option in the conf to use identify as a username which is as I understand is for using the client certificates as a username. While we don't use certificates, I'm wondering if there is a way to tap into the same mechanism. 

### Environment

- VerneMQ Version: latest
- OS: latst
- Erlang/OTP version (if building from source): latest
- Cluster size/standalone: 3 nodes

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ashtonian** [comment]
After reviewing the db auth plugins there may be another way to do this. Taking a step back the requirement is to be able to take a username and jwt as password and authenticate based on if the jwt is valid and then extract the topic acls from the jwt token. I initially went down the web hook path as that seemed like I could make the plugin external, but that is all keyed off username which is the same with my use case.

**Comment by ashtonian** [comment]
Never mind, figured that if I wanted to implement this in full I could use the client_id. 

Also figured out that because the plugins are chained, and the priority is customizable I can implement the on_register hook and use that to write to a pg/redis plugin with ttl and then use those plugins. Sorry for the issue, thanks for making verne extensible!

**Comment by ioolkos** [comment]
@ashtonian Thanks, let us know when you have additional questions or ideas!

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
