### ISSUE TITLE
Provide all metrics from status page in metrics endpoint

### ISSUE THREAD

**Issue by pellepelster** [vernemq/vernemq#2367]
### Describe your issue or feature request

For our VerneMQ setup we established monitoring via the Prometheus endpoint (http://localhost:8888/metrics) as documented here https://docs.vernemq.com/monitoring/prometheus. 

Due to the way we have structured our integration tests, we had an intermittent issue with a too high amount of offline sessions. During the cleanup of this issue we noticed that the amount of offline sessions, as well as other interesting metrics are only available via the status page 

```
{
	"0": {
		"VerneMQ@<node>": {
			"num_online": 1,
			"num_offline": 2,
			"msg_in": 3,
			"msg_out": 4,
			"queue_in": 5,
			"queue_out": 6,
			"queue_drop": 0,
			"queue_unhandled": 0,
			"num_subscriptions": 7,
			"num_retained": 8,
                        [...]
		}
	}
}
```

although `vernemq_retain_messages{node="VerneMQ@<node>"}`is available in the metrics endpoint, e.g.  `num_offline` is not. 

### Describe the solution you'd like

It would be very helpful if all metrics from the status page

* num_online
* num_offline
* msg_in
* msg_out
* queue_in
* queue_out
* queue_drop
* queue_unhandled
* num_subscriptions
* num_retained

would also be available in the metric endpoints

### Describe alternatives you've considered

We implemented an automatic scraping via cronjob, which now is a monitoring solution that runs in parallel to the metric endpoints based ones.

### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):
- Cluster size/standalone:

### Code of Conduct

- [X] I agree to follow the VerneMQ's Code of Conduct

**Comment by ioolkos** [comment]
@pellepelster Thanks. In short any exported metrics are based on the same list of metrics. You can display this with `vmq-admin metrics show`. You can also use `grep` with the command: `vmq-admin metrics show | grep queue`
Most of the metrics you mention should be there, they might have slightly different names, though. Like `gauge.retain_messages`.
`num_subscriptions` on the Status page will be `gauge.router_subscriptions`.
 
You are right about the number of offline and online clients. This is calculated in the Javascript of the Status page. We have gauges for the queue processes and gauges for online connections, so the difference must be the offline clients.
You could do this kind of queries in Prometheus as well.
Let me know if you need more info.

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by pellepelster** [comment]
Thanks for your quick response, that answers all questions

**Comment by ioolkos** [comment]
@pellepelster Good to hear, thank you for the feedback :)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
