### ISSUE TITLE
Mongo cluster support

### ISSUE THREAD

**Issue by ig0r** [vernemq/vernemq#303]
### Environment

- VerneMQ Version: 1.0.0rc2

### Expected behavior

It'd be great if the broker could support a mongo cluster/replica set.

The settings could look like:

`vmq_diversity.mongodb.host = host1:port1,host2:port2,host3:port3`

Guys, do you have any plans to support that? 

Without it, mongo support has not that much sense I guess :)

Thanks!

**Comment by larshesel** [comment]
Hi @ig0r 

Thanks for suggesting this improvement. I think this would be a good feature to support and looking at the driver we use it looks like it supports both replicasets and sharded mongodb setups.

As it's not clear how much effort is needed and what the priority of this should have compared to other tasks I can't give you any indication on if/when we'll get to work on it.

**Comment by ig0r** [comment]
ok, thanks for info!

**Comment by eiabea** [comment]
i ran into the same issue

i tried setting the host as it is suggested for the mongo cli client

`mongo --host replicaSetName/host1[:porthost1],host2[:porthost1],host3[:porthost3] databaseToConnect`

so i set this environment variable

`DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__HOST: "rs0/mongo1:27017,mongo2:27017,mongo3:27017"`

unfortunately the driver can not handle this and crashes

I don't know how a verne cluster handles the mongodb connections, but would it be a workaround to connect each verne instance in the cluster to the corresponding mongodb instance?

So

```
Node1: MongoDB1 <- VerneMQ1
            |           |
          rs0           |
            |           |
Node2: MongoDB2 <- VerneMQ2
            |           |
          rs0           |
            |           |
Node3: MongoDB3 <- VerneMQ3
```

**Comment by vichle** [comment]
Is this something that is being developed? Is this hard to do in Erlang? In the NodeJS MongoDB-driver, this is a piece of cake. Just pass a connection string instead of each parameter separately.

**Comment by larshesel** [comment]
I guess there are two things to find out: 1) does the mongodb driver used support clustering (I think it does) and 2) how to be able to configure this from the existing configuration format (possibly adding new config options.

I don't suppose it'd be very hard, but we haven't had time to look into this yet, so PRs are very welcome.

**Comment by p-mendes** [comment]
+1 for this improvement. 

Just came across this limitation now, and am trying to figure out a solution, which will probably involve using MySQL...

**Comment by thewritingdude** [comment]
+1

The issue is evident by looking at the driver used: [https://github.com/comtihon/mongodb-erlang](url).
The client used is mc_worker_api, which supports only direct connections. For this feature, it should be used this one: [https://github.com/comtihon/mongodb-erlang#mongoc----client-with-automatic-mongodb-topology-discovery-and-monitoring](url), also in the same package.

Please write also with suggestions, I would do it, but I have no experience whatsoever in Erlang.

**Comment by thewritingdude** [comment]
(Sorry for the broken link above :) )
Maybe it could be done using the mongo_api:connect method aside the mc_worker:start_link existing call, maybe giving this another name (like mongodb-shard or similar) and subsequent exclusive set of variables, other than the one already existing.
The existing part will be then unaffected and could still be used for direct connection.

**Comment by larshesel** [comment]
I'm more concerned with how to configure this in the `vernemq.conf` file. Granted, I haven't really given it any real thought yet, but that's where we have to be careful to not make backwards incompatible changes. If that can be etched out, then I think we could work on this.

**Comment by milamber-ls** [comment]
+1
any decent project that uses mongo will use a cluster. if vmq cant connect to it and needs its own authentication db then why use vmq?

**Comment by ncpe20012003** [comment]
Any progress with MongoDB cluster support in VMQ?

**Comment by larshesel** [comment]
Progress has been made, but there are some technical issues that have been identified with the connection pool the mongodb driver uses. The mongodb one is a fork of the one vernemq uses(poolboy) and we need to figure out how to reconcile these differences and/or use a different mongodb driver.

**Comment by ncpe20012003** [comment]
Checking in on MongoDB cluster support. I'm evaluating the MongoDB cloud service Atlas. All users and authentication has to be done through the admin db. The vmq_acl_auth collection is in another db which cause problems with the parameters in vernemq.conf file. Is there a way to point the authentication to the admin db but use another db where vmq_acl_auth collection resides?

**Comment by larshesel** [comment]
@ncpe20012003 as your question isn't related to the issue topic, please open a new issue to keep the discussion here focused.

**Comment by harikrishhb** [comment]
any update on mongo cluster ?

**Comment by ioolkos** [comment]
@harikrishhb work on MongoDB cluster support has stalled, at least currently. Open to contributions, but it's kind of a complex issue. But that's what I think :)

Maybe @codeadict can share some further insights, as he seemed to have taken a look into it too a while back.

**Comment by ioolkos** [comment]
@miqmago can you please check the note on SRV/replica sets in the documentation here: https://docs.vernemq.com/configuring-vernemq/db-auth#mongodb? to determine if that's  what you need.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by miqmago** [comment]
Ok, verified and working in the latest version, it can read from secondary clusters, thank you very much.
I think this is no longer an issue.
