### ISSUE TITLE
Subscribing to topics on a different mount point

### ISSUE THREAD

**Issue by oakad** [vernemq/vernemq#395]
The original MQTT implementation treated mount points as obligatory server-side topic prefixes. Thus, a client on a default mount point "" could communicate with clients having explicit mount points set:

MP0: client A publishes to `<topic>/`
"": client B subscribes to `+/<topic>` and gets messages from client A (as `MP0/<topic>`)

It appears, that vmq does something differently and the clients with empty mount points can not communicated with the ones having explicit mount points set.

Am I doing something wrong or vmq treats mount points as completely isolated namespaces?

**Comment by ioolkos** [comment]
Mount points are completely isolated namespaces, yes.

**Comment by oakad** [comment]
This breaks a major assumption people learned to have about MQTT and should probably be documented in large letters somewhere.

The original (IBM's)  approach was much more useful, I should add.

**Comment by ioolkos** [comment]
No, no :) mount points are used to separate clients. Am I missing your point?

**Comment by oakad** [comment]
There should be a way for "super clients" to reach the isolated ones. That's exactly what IBM's approach achieved: client below the mount point could not reach clients elsewhere, but clients above the mount point could.

https://www.ibm.com/support/knowledgecenter/SS9D84_1.0.0/com.ibm.mm.tc.doc/tc60522_.htm

**Comment by ioolkos** [comment]
I see. (the last sentence in the link above explains it).
@dergraf what's your take on this?
I think it's a non spec feature anyway. But I'll compare what other brokers do here.

@oakad thanks for pointing this out (& jep, I missed your point :)

**Comment by ioolkos** [comment]
OK, Mosquitto does the IBM way, obviously.
We're going to discuss this. In principle we like to have a way to completely separate topic trees. (multi tenancy)
But yeah, the questions is what the most convincing use case is. (as I said this is non MQTT spec terrain)

Surprisingly, mount points are not among the most used features, from what we see. which is a pity :)
@oakad thanks again, in any case

**Comment by dergraf** [comment]
I see some good points regarding the IBM/Mosquitto style of mount points. And of course in order to reduce misunderstandings we should clarify our understanding of mountpoints, which are rather modeled after RabbitMQs VHost.

The 'original' concept of mount point could be easily achieved via a plugin using some topic rewrites. Therefore I prefer to keep it as it is for the moment, and either be more explicit in the docs or rename our mount point to something like VHost. 

Comments?

**Comment by oakad** [comment]
@dergraf Not quite - current implementation does not allow for user implemented rewriting functionality.

To implement "mount point"-like topic rewriting one has:

1. To provide implementation for all of the "publish flow" callbacks (ok, supported)
2. Each of those callbacks must support topic rewriting ("auth_on_publish" and "on_deliver" do support this, but "auth_on_subscribe" appears to not)
3. There should be a "session state" carried around (another open issue)

Proper server side topic prefixing is simple to understand and extremely useful (essentially, it works the same as unix "chroot") - we planned to use it to constrain external unsecured clients, by putting each such client onto a separate mount point with a single line in auth_on_register. Instead we ended up with a pretty convoluted system of callback implementations (see p.2 above) and ets managed state prone to occasional race conditions.

**Comment by dergraf** [comment]
Yeah I see your point. However, I wonder how we could implement this in a backward-compatible way.

**Comment by jeremylink** [comment]
I would probably advocate for the "IBM" way of things.

Client endpoints would be connecting to the broker on different endpoints, but it seems like server-side apps would frequently pub/sub to topics across all tenants/mount points.

**Comment by kellycampbell** [comment]
We're using an auth hook script to do something like what you may be trying to do. We rewrite the mount point to the common namespace after authenticating that the client is allowed for the original mount point.

**Comment by larshesel** [comment]
As there isn't really a good way of changing this at the moment I've marked it with the VerneMQ 2.0 label so we can revisit it later. Closing for now.

**Comment by timthelion** [comment]
Would it be possible to at least rename `mount point` to `namespace` since the mount points are not actually mount points?

**Comment by ioolkos** [comment]
@timthelion Thanks for your suggestion. While I'm all for naming clarity, I think it'd be a bit too hard to change and communicate. The thing is that "mountpoints" are not part of the MQTT spec. And even if we break a convention, it's not really clear what "actual mount points" are in this context (unless we talk about mount point as in the Linux OS)

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by timthelion** [comment]
Mount points are points at which things are mounted.  How does the term relate to namespaces?
