### ISSUE TITLE
What is a MountPoint and what is it used for?

### ISSUE THREAD

**Issue by Think7** [vernemq/vernemq#533]
Hello,

What is a MountPoint and what is it used for?

I see it referenced in the docs, specifically on this page regarding ACLs:
https://vernemq.com/docs/configuration/db-auth.html

but haven't been able to figure out what it is, what it is used for, or why i would want one.

If this information is in the docs somewhere PLEASE post a link to it as i haven't been able to find an explanation anywhere.

**Comment by ioolkos** [comment]
Thank you @Think7 for bringing to our attention that the doc is not helpful.
I'll try to explain mountpoints here and then add this to the documentation:

Normally, a VerneMQ broker hosts one single topic tree. This means that all topics are accessible to all publishers and subscribers (limited by the ACL's you configured, of course).
Mountpoints are a way to host multiple topic trees in a single broker. They are completely separated. Clients from different topic trees cannot talk to each other in that case. This could be useful if you provide MQTT services to multiple separated use cases/verticals or clients, with a single broker.
Note that separated mountpoints are configured via different listeners. As a consequence, the MQTT clients will have to connect to a specific port to connect to a specific topic space (mountpoint).

Also note that currently VerneMQ implements a very restrictive version of mountpoints, somewhat modelled after RabbitMQ's vhost concept. Other MQTT brokers might implement a different model of mountpoints.

**Comment by Think7** [comment]
Thank you! This is a great explanation. 

I was considering running two separate brokers for security reasons. One that handles my applications communication between the different internal services and one that clients connect to. Mountpoints seem to solve this issue though. 

One other question:

I understand MQTT is a message broker that strictly handles pub / sub for real time data. 

How is a situation handled though where a client needs access to previous messages or historical data?

For example a chat application.

Let's say Client1 and Client2 are passing text messages on a topic. If Client2 disconnects and then joins back later, unless he has stored the conversation history locally, everything is gone. He will only have access to whatever new messages are sent. 

The only MQTT specific solution I can think of is continually updating the topics retain message with the entire conversations history so that is sent when Client2 re subscribes. This feels very wrong though. 

What about needing to select only specific parts of the conversation? Say within a specific date range. Or perform searches or other operations?

How should an application handle this case?
Does Vern have a solution or is there a general best practice?

**Comment by jeremylink** [comment]
I'd never seen a good explanation of mountpoints either - this sounds interesting.
Currently, I use the topics to filter for multi-tenancy; is there a discussion somewhere that covers the pluses/minuses of using mountpoints vs. topics for multi-tenancy?

**Comment by ioolkos** [comment]
@jeremylink yeah, we had a discussion a while back here: https://github.com/erlio/vernemq/issues/395
on the pro's and con's of IBM style mountpoints vs. our understanding. In an ideal case we could support both versions.
Regarding your remark, I think I have never seen a discussion of topics vs. mountpoints for multi-tenancy.

**Comment by jeremylink** [comment]
Good info - I didn't realize the difference when I was reading about other mountpoint implementations.

**Comment by siscia** [comment]
Hi guys,

Just got interested in the topic.

Would it be possible to set the mountpoint with a modifier on the client connection?

In particular on the auth_to_register hook?

This will allow a quite flexible and usefull model...

**Comment by siscia** [comment]
Hey there!

Thanks for the extremely fast response.

I was browsing the documentation from mobile so I didn't dig too further into all the modifiers.

Thanks!

**Comment by 1995parham** [comment]
Hi guys,

can we disable webhook authentication on specific mount point? I want to authenticate all clients except those coming from my mount point.

**Comment by larshesel** [comment]
Hi @1995parham, that's a feature we'll include in 2.0 - the idea is to have different plugin chains per listener (and hence mountpoint). Currently you'd have to rewrite the mountpoint in `auth_on_register` to work around this.

**Comment by 1995parham** [comment]
Thanks for your reply, so I looking forward to version 2.

**Comment by puresilk** [comment]
After struggling to wrap my head around Erlang, and understanding how to pass the correct values with Lua, I have come up with the following blog post and code, to allow custom mountpoints from Lua & MongoDB. The code should be easily adjustable to MySQL / Redis / CockroachDB as it is mostly about the proper formatting of the return values. 

https://pi3g.com/2019/05/12/understanding-erlang-lua-luerl-for-vernemq-mongodb-auth_on_register-hook/

**Comment by dergraf** [comment]
@puresilk cool stuff! Thanks!

**Comment by larshesel** [comment]
Of course! this is really cool!

**Comment by larshesel** [comment]
We added the explanation above to the documentation: https://docs.vernemq.com/configuring-vernemq/listeners#mountpoints. Let us know if you have any ideas for improving! Cheers!

**Comment by varunct007** [comment]
How to set vernemq mountpoint configuration using docker yaml
I tried to set a mountpoint configuration for a broker.As per the reference [https://docs.vernemq.com/configuration/listeners#], i configured the mountpoint for listener in my docker yaml file.
- name: DOCKER_VERNEMQ_LISTENER__mountpoint
value: "on"
- name: DOCKER_VERNEMQ_LISTENER__ssl.mountpoint
value: "ssl-mountpoint"
- name: DOCKER_VERNEMQ_LISTENER__tcp.listener1.mountpoint
value: "tcp-listener1"
- name: DOCKER_VERNEMQ_LISTENER__tcp.listener2.mountpoint
value: "tcp-listener2"
and i added the mount point to database mountpoint : "tcp-listener1" for corresponding cilent .But client can't connect to broker and showing authentication error in borker log
12:29:10.320 [warning] can't authenticate client {"on",<<"client1">>} from 10.244.0.48:55134 due to invalid_credentials
how to configure correct configuration ?

**Comment by ioolkos** [comment]
You need one listener per mountpoint. Does your client connect to the correct listener?

**Comment by varunct007** [comment]
@ioolkos I really don't know how to set multiple listener using docker .how to set multiple listener ?

**Comment by varunct007** [comment]
@ioolkos  how to set multiple listener using docker yaml .how to set multiple listener ?
is there any proper document for configure the mountpoint in vernemq(docker also) ??
