### ISSUE TITLE
Consider providing an in-memory datastore

### ISSUE THREAD

**Issue by picaoao** [vernemq/vernemq#554]
We currently have a use case where we are considering using a mqtt broker to implement a presence system. In that scenario we don't need to actually persist in disk the retained messages, last-will,  as well as the topic subscriptions. Everything could work in-memory, and with that provide much higher performance, since we would be emitting all messages with retain flag set to true. We are aiming at very high nr of clients, configured with last-will, so this means that using leveldb and keep updating the retained message all the time and sync between clusters would be a killer in performance.

How hard would be to have everything running in a in-memory db ?
Emqtt implementation seems to have that option with retained messages by using mnesia in ram.

**Comment by ioolkos** [comment]
Hi @picaoao thanks for your remarks, it's an interesting question.
There's 2 sides to this question:
- what is the best architecture to make the backend for persistence of any kind of state completely pluggable
- what is the fastest and simplest way for you to have everything as an in-memory DB as described

I have no easy answer to that. I think the architecture is not quite pluggable yet. And while I think the effort is low, it's probably not high-priority for us right now.

@dergraf @larshesel what do you think?

**Comment by ioolkos** [comment]
A clarification: low effort is only the message store replacement. Any involvement with the plumtree protocol (as in the subscriber replication) is rather high effort.
