### ISSUE TITLE
Better characterization of VerneMQ memory usage

### ISSUE THREAD

**Issue by originsmike** [vernemq/vernemq#591]
I'm trying to understand memory usage of a single node VerneMQ broker. I've looked at https://github.com/erlio/vernemq/issues/486, https://github.com/erlio/vernemq/issues/470, https://github.com/erlio/vernemq/issues/423, https://github.com/erlio/vernemq/issues/484, and https://github.com/erlio/vernemq/issues/511, and followed a few configuration settings through to the LevelDB source code, but I'm still missing a few hundred MB.

TL;DR: probably what's needed are ways to tell how many messages awaiting delivery are stored in the message DB and current LevelDB memory allocation (msgstore and meta), and some confirmation of the behavior of `leveldb.maximum_memory.percent` and `max_offline_messages`.

### Environment

- VerneMQ 1.2.3, single node, under Docker 17.09 as erlio/docker-vernemq:1.2.3
- Sitting behind haproxy 1.8 (which also terminates SSL) using proxy protocol v2
- OS: Ubuntu 16.04
- Server: 2 cores / 2GB RAM
- Environment: ~500 simultaneous clients online, up to ~2,000 unique clients. One Lua plugin that sometimes makes http posts.

Most clients are clean_session=false, publish about 1 msg/min and messages average about 100 bytes, and subscribe to very low traffic topics with retained messages. A couple clients on the back end essentially subscribe to # with QoS=1. Every minute an average of about 3 clients drop due to random network instability: keepalive expired, disconnect, etc... the disconnect is *always ungraceful*.

### Expected behavior

- Once the number of clients becomes stable, memory usage should level off at a predictable level.

### Actual behaviour

- My instance took about 12 hours to reach steady state. It looks like a memory leak as others have reported, but it's not a leak. This is fine, but I can't account for most of the growth, and I don't know if I have any options to reduce memory usage.

To summarize my research below, of a `top`-reported resident size of 737,068k:

- Erlang has allocated 261,380k (but it's only using 207,712k)
- LevelDB is configured to max out at 10% of 2GB = 209,715k (but I'd bet it's actually 16% or 335,544k)
- tcp buffers likely stand system-wide at 204*4k = 816k, but those aren't counted by `top` anyway
- My Lua plugin doesn't have any appreciable impact
- 140,144k comes from mystery non-Erlang stuff that isn't there at boot

vernemq.conf is:
```
allow_anonymous = off
listener.tcp.default = 0.0.0.0:1883
listener.tcp.from_haproxy = 0.0.0.0:1884
listener.tcp.from_haproxy.proxy_protocol = on

log.console = file
log.console.file = /var/log/vernemq/console.log
log.console.level = debug

leveldb.maximum_memory.percent = 10

plugins.vmq_diversity = on
vmq_diversity.script_dir = /share/lua

vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_acl.acl_file = /etc/vernemq/vmq.acl

max_client_id_size = 50
persistent_client_expiration = 1d
message_size_limit = 32768 # unused; haven't changed this to max_message_size yet
```

Metrics:
```
root@front0:/# vmq-admin metrics show
gauge.queue_processes = 866
gauge.retain_memory = 119456
gauge.retain_messages = 256
gauge.router_memory = 797520
gauge.router_subscriptions = 2193
gauge.system_utilization_scheduler_2 = 13
gauge.system_utilization_scheduler_1 = 100
gauge.system_utilization = 57
gauge.vm_memory_ets = 7455984
gauge.vm_memory_code = 11930614
gauge.vm_memory_binary = 145643032
gauge.vm_memory_atom_used = 503334
gauge.vm_memory_atom = 512625
gauge.vm_memory_system = 172601680
gauge.vm_memory_processes_used = 22558144
gauge.vm_memory_processes = 22558848
gauge.vm_memory_total = 195160528
counter.system_wallclock = 98047846
counter.system_runtime = 2681220
gauge.system_run_queue = 0
counter.system_reductions = 2939028455
counter.system_io_out = 164560422
counter.system_io_in = 200432682
counter.system_words_reclaimed_by_gc = 6339741283
counter.system_gc_count = 8074329
counter.system_exact_reductions = 2939028329
counter.system_context_switches = 24927720
counter.socket_open = 12507
counter.socket_close = 12111
counter.socket_error = 0
counter.bytes_received = 147385250
counter.bytes_sent = 154721310
counter.mqtt_connect_received = 4901
counter.mqtt_publish_received = 609180
counter.mqtt_puback_received = 621964
counter.mqtt_pubrec_received = 0
counter.mqtt_pubrel_received = 0
counter.mqtt_pubcomp_received = 0
counter.mqtt_subscribe_received = 11319
counter.mqtt_unsubscribe_received = 647
counter.mqtt_pingreq_received = 2036593
counter.mqtt_disconnect_received = 1425
counter.mqtt_connack_accepted_sent = 4661
counter.mqtt_connack_unacceptable_protocol_sent = 0
counter.mqtt_connack_identifier_rejected_sent = 240
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_sent = 647911
counter.mqtt_puback_sent = 609180
counter.mqtt_pubrec_sent = 0
counter.mqtt_pubrel_sent = 0
counter.mqtt_pubcomp_sent = 0
counter.mqtt_suback_sent = 10198
counter.mqtt_unsuback_sent = 647
counter.mqtt_pingresp_sent = 2036593
counter.mqtt_publish_auth_error = 0
counter.mqtt_subscribe_auth_error = 1121
counter.mqtt_invalid_msg_size_error = 0
counter.mqtt_puback_invalid_error = 8
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_publish_error = 0
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0
counter.queue_setup = 1318
counter.queue_teardown = 662
counter.queue_message_drop = 597691
counter.queue_message_unhandled = 239
counter.queue_message_in = 1222756
counter.queue_message_out = 1246055
counter.client_expired = 0
counter.cluster_bytes_received = 0
counter.cluster_bytes_sent = 0
counter.cluster_bytes_dropped = 0
```

### Investigation

About 1/2 hour after startup, I immediately kicked ~500 connections over, and memory usage jumped from 190MB to 270MB. (graphs at the end)

About 12 hours later, memory usage finally leveled off at ~720MB:

```
# top
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
108 vernemq   20   0 4783036 737068  99868 S   4.4 36.0  64:41.07 beam.smp

# netstat -tan | wc -l
399
```

I spent some quality time with `strace` and found that at least 80% of the growth was coming from `mmap` calls (minus the calls to `munmap`) from two child processes of `beam.smp`, which unfortunately don't show up in `ps`.

#### Erlang

Code running inside Erlang is responsible for none of the scary-looking constant memory growth.

On 1-24 at 15:41, a few hours after startup, with `top` reporting 410,720k:

```
(VerneMQ@192.168.120.57)7> erlang:memory().
[{total,212697128},
 {processes,22126488},
 {processes_used,22117840},
 {system,190570640},
 {atom,512625},
 {atom_used,501148},
 {binary,163851560},
 {code,11898467},
 {ets,7208072}]

(VerneMQ@192.168.120.57)1> recon_alloc:memory(allocated). 
292372480

(VerneMQ@192.168.120.57)2> recon_alloc:memory(usage).
0.710976463995517
```

And the next day, after steady state, when `top` was reporting 737,068k:
```
(VerneMQ@192.168.120.57)1> erlang:memory().
[{total,193892616},
 {processes,22730136},
 {processes_used,22725344},
 {system,171162480},
 {atom,512625},
 {atom_used,503301},
 {binary,144216464},
 {code,11930614},
 {ets,7451536}]

(VerneMQ@192.168.120.57)2> recon_alloc:memory(allocated). 
267653120

(VerneMQ@192.168.120.57)3> recon_alloc:memory(usage).
0.7183019573991889
```

#### LevelDB

This should be limited to 10% of total memory. Docker issue https://github.com/moby/moby/issues/20688 implies that the calculation will be based on the machine's total RAM of 2GB, not the container's hard limit of 1.2GB, so 10% of 2GB is 200MB.

Maybe 200MB is considered low, but there aren't that many messages in play here:

- max_online/offline_messages is only 1,000, though the docs aren't clear if that's per session or total
- the current value of `gauge.retain_messages` is 256, though I don't know if that's the number of messages that are currently awaiting delivery to a clean_session=false, QoS 1 client that's currently offline
- worst case, with 2k clients, that's 40k messages that need to be stored; with the average message being around 100 bytes, they should all fit into ~4MB of storage, plus some overhead

Is the overhead really at least 50x?

(This goes into a deeper question of whether VerneMQ actually needs to save/persist QoS 1 messages that are published to topics to which no QoS=1, clean_session=false clients are subscribed... hopefully not?)

The two LevelDB databases, `plumtree_metadata_leveldb_instance` and `vmq_lvldb_store`, are both partitioned into 12 shards. LevelDB's documentation says that `total_leveldb_mem_percent` is shared across all instances in the same process, but the output from `strace` suggested that they were running in two different processes and therefore may not share an instance of [FlexCache](https://github.com/basho/leveldb/blob/f52c83da332283fe9ed1b59e39aebc86ad3e22f7/util/flexcache.cc), and so the total LevelDB memory is likely `leveldb.maximum_memory.percent`, plus another 6 percent. Hopefully, write buffers are part of that `total_leveldb_mem_percent`.

#### TCP Buffers

I'm still trying to figure out exactly how to determine how much memory is being used by TCP buffers, and where that's reported. I opened [this question](https://unix.stackexchange.com/questions/419518/how-to-tell-how-much-memory-tcp-buffers-are-actually-using), but it's still open. As far as I can tell, the `mem` field of `/proc/net/sockstat` tells the number of 4k kernel pages that are currently allocated for network buffers, though that number seems low.

#### Lua Script

I had a Lua script running that uses ETS, one key per client, and sometimes makes HTTP calls in on_publish. I unloaded the script a couple hours after restarting VerneMQ, but that didn't impact the rate of memory growth.

### Pretty Pictures

Graphs are of active MQTT connections and total memory usage (container, not process; but the beam.smp process is by far the largest contributor to the container's memory usage).

I restarted the broker just before 11:00, then kicked over a bunch of connections from another broker just before 13:00. (The dip after 16:00 is because my remote `strace` session starved the network and caused a bunch of keepalives to be severely delayed, resulting in some clients being kicked)

I don't know why memory growth accelerated around 16:30, right after ~100 clients dropped.

![vmq-mem1](https://user-images.githubusercontent.com/21031936/35374338-69954ce6-01dd-11e8-80e4-db87708ed458.png)
![vmq-conn1](https://user-images.githubusercontent.com/21031936/35374357-80b4657e-01dd-11e8-919d-7a02d8f5bc55.png)
![vmq-mem2](https://user-images.githubusercontent.com/21031936/35374361-8523889c-01dd-11e8-93d4-e3c737b7517a.png)
![vmq-conn2](https://user-images.githubusercontent.com/21031936/35374368-8812e930-01dd-11e8-9483-725e370f1e8f.png)

**Comment by larshesel** [comment]
Thanks for this amazing write-up and analysis! We'll need a bit of time to go through it.

**Comment by dergraf** [comment]
Thanks for analyzing! Are all clients publishing the messages using retain=true and qos=1?

**Comment by dergraf** [comment]
And for the retained messages, how do tge routing keys look like, e.g do the contain any random/unique parts?

**Comment by originsmike** [comment]
Clients (IoT devices) are publishing messages with retain=false, qos=1. Most messages are published on topics like path1/path2/<uuid>, where uuid is unique to the client.

The only retained messages in the system are published by the server on about 200 separate topics, once per hour. About half the clients subscribe to one of these topics.

This growth is fairly easy to reproduce with just two clients, one of which simulates a thousand IoT devices and publishes messages with qos=1 on a thousand different topics, and the other which subscribes to # with qos=1. I've had 200 messages/second running for around a half hour and memory usage started at 50MB and sort of stabilized around 470MB, even though I've set leveldb.maximum_memory.percent = 1 on a VM with 4GB of RAM. Meanwhile, Erlang reports that it's allocated around 20MB.

I'm starting to suspect it's due to LevelDB's `write_buffer_size` not being counted as part of `total_leveldb_mem_percent`. This would add on average 12*(30+60)/2 = 540MB to LevelDB's max memory. But I haven't been able to confirm this from the LevelDB code yet.

**Comment by ioolkos** [comment]
Interesting hypothesis!

There are a couple of knobs to tune the eleveldb library `https://github.com/erlio/eleveldb/blob/develop/priv/eleveldb.schema` I think these can then be set in the `https://github.com/erlio/eleveldb/blob/develop/src/eleveldb.app.src` file or maybe elsewhere, I don't remember exactly.

I remember playing around with a couple of those, and I hate myself for not keeping a Lab journal for that... :)

They'd require a re-compile. Most interestingly, there is an option to set LevelDB memory absolutely as a bytesize, not percentage of RAM. Also the buffer sizes can be set etc.

**Comment by originsmike** [comment]
@ioolkos so the settings marked `hidden` can't be changed with verne.conf? I could try a recompile but it'll take a while to get set up :)

Also, do you know if the allocation given by `leveldb.maximum_memory.percent` is shared between the meta and msgstore databases, or if meta always has its own 6% separate from msgstore?

**Comment by larshesel** [comment]
You can set them directly in the `vernemq.conf` file even though they are hidden, there should be no need to recompile.

**Comment by originsmike** [comment]
That worked! For these settings:

```
leveldb.maximum_memory = 1048576
leveldb.write_buffer_size_min = 1048576
leveldb.write_buffer_size_max = 2097152
```

The experiment that reached ~500MB before is now holding steady at ~80MB.

The takeaway is that total LevelDB memory usage can be as high as 24 * (30MB+60MB)/2 = 1,080MB + 6% above what `leveldb.maximum_memory.percent` would indicate. On machines with 16GB of RAM that's a rounding error, but if you're on 4GB or less it's a big deal.

Of course, the next questions are:

- Given a certain amount of load on the broker, how far can you reduce these buffers without having to worry about death by disk i/o
- Is there a way to prevent VerneMQ from storing in the DB any messages that don't actually need to be persisted (i.e. have already been delivered with PUBBACK to all subscribed clients, or perhaps were published on topics that don't have any subscribed clients at all)

But these are separate issues.

@larshesel feel free to close this issue if you want, unless you feel like the 1GB fudge factor is something that could be called out in the docs.

**Comment by ioolkos** [comment]
Apologies for any mis-information I might have given (re: re-compiling needed). :grimacing: 

This is nice insight & information @originsmike Thanks again for the tremendous efforts!

**Comment by larshesel** [comment]
Hi @originsmike I guess the first bullet point will have to be tested to see what works, the second about not persisting messages is something we've been thinking about. We'd like to create a way to delay the writes as most messages will be written and then immediately deleted afterwards after the message was delivered. We might save massive amounts of IO for QoS1/2 messages if we postpone the delays by for example a couple of seconds. Of course this will imply there's the possibility of message loss in case of a power outage. It's definitely something to think about. So to answer the question: at the moment there isn't a way to prevent messages being delivered to subscribers from being written(unless the persistence of messages is completely disabled), but we do not write messages for which there are no subscribers.

**Comment by originsmike** [comment]
Thanks for the additional info! The delays would definitely help. But to me it feels like getting onto that happy path of no disk i/o would be fiddly (it might not be obvious which subscriber(s) are keeping disk i/o from dropping), and if one of your clients drops offline, you suddenly go from no disk/o to tons of i/o.

But maybe there's another way to think about this problem. If you're building a system and you're that worried about disk i/o, you're not subscribing with MQTT on your back end at all -- as we've observed before, subscribes to # on the back end force all your traffic through a single node. So we're already acknowledging that there's something special about those back end subscribers.

If your plan is to dump all MQTT messages into highly available storage like Kafka or Mongo or SQL, then the MQTT broker's QoS 1 guarantee is kind of redundant -- it's one more buffer between your clients and the final store. What you're really doing is treating MQTT like another interface into Mongo or Kafka, like they're part of the same system, which means it would make sense for the MQTT PUBBACK to be issued at the moment when the message has been committed to the database. (indeed, this seems to be the path that RocketMQ is moving toward, but their MQTT interface isn't ready yet)

I don't know if this is possible with the Erlang plugins right now -- and I'm new at designing distributed systems -- but to me an ideal back end fire hose plugin would be able to send a received message directly to the back end (like Kafka), and make the PUBBACK directly conditional on the back end's acceptance of that message. If/when your back end does goes down (which should happen very rarely, because if it does you're already screwed), that'll simply show up as backpressure to the external clients.

Anyway, I've been using these settings for several days now with about 400 clients:

```
leveldb.maximum_memory = 10485760
leveldb.write_buffer_size_min = 1048576
leveldb.write_buffer_size_max = 2097152
```

And memory usage is holding steady at 135MB with minimal disk i/o (about 10kB/sec). I'd call that success.

**Comment by larshesel** [comment]
Just a comment about preventing the subscribe to `#` issue where everything is routed to a single node. Using shared subscriptions using the `prefer_local` strategy (default) one can ensures that if there are local shared subscribers for a specific topic, one of the local clients is picked for the message rather than one of a remote node. This allows for massive fan-ins to be distributed over local subscribers on each node in the cluster, but little-to-none cross-node traffic.

**Comment by originsmike** [comment]
Great, thanks for the heads up. That's another option to consider.

**Comment by dergraf** [comment]
Again thank you @originsmike for this nice analysis. I am closing the issue, but labeled it as `interesting` ;) 
Please feel free to reopen it when required.

**Comment by originsmike** [comment]
No need to reopen. We've been running 1.5.0 with this setup in prod for six months with thousands of clients and millions of QoS 1 messages per day and it's been stable. Memory usage still isn't quite flat over time (it climbs at the rate of about 150MB **per month**) but it's good enough for our purposes. Thanks for all your help!
