### ISSUE TITLE
vmq_bridge auto echo things

### ISSUE THREAD

**Issue by forstef** [vernemq/vernemq#664]
### Environment

- VerneMQ Version: latest mater branch
- OS:debian 9
- Erlang/OTP version (if building from source):20.3

### Expected behavior

- Please describe the expected behaviour.

when:
vmq_bridge.tcp.br0.try_private = off
vmq_bridge.tcp.br0.topic.1 = s/a both 1 (must be both)

should work normal, no infinitely increasing in rabbitmq queues which bind topic s.a.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

when:
vmq_bridge.tcp.br0.try_private = off
vmq_bridge.tcp.br0.topic.1 = s/a **both** 1

1.vmq_bridge seems like as a mqtt client subscribe topic s/a from remote broker and  **automatic echo** what received from that topic.
Hence rabbitmq queues which bind topic s.a increase infinitely.

2.And seems like when set vmq_bridge.tcp.br0.topic.1 = s/a **out** 1 (not "both"), then no **automatic echo**, but the vmq_bridge still subscribe topic from remote broke,  is this behavior normal?

**Comment by larshesel** [comment]
Hi, sorry for the delayed response, we haven't had time to look into this issue yet. Is this still an issue or did you find a workaround in the meantime?

**Comment by kebingzao** [comment]
I have the same problem

**Comment by larshesel** [comment]
Hi, a number of fixes were recently merged to master including a bug with the
prefix handling. Please try again with either a build from master or try the
1.9.0 release when it is out in a few days.
