### ISSUE TITLE
Adding new diversity/lua libs

### ISSUE THREAD

**Issue by baranga** [vernemq/vernemq#686]
### Environment

- VerneMQ Version: 1.3.1
- OS: Linux
- Erlang/OTP version (if building from source):

### Expected behavior
Due the nature of luerl the provided libs in lua are limited to what vmq_diversity already provides. I expect some interface to inject more libs into the lua environment. Maybe via loading a custom plugin providing dependencies and erlang/lua mappings.

### Actual behaviour
I found no way to add my own libs for use in lua scripts.

**Comment by dergraf** [comment]
@baranga Thanks for reporting. This would be great of course. However, as correctly noted, this isn't possible at the moment. 
https://github.com/erlio/vernemq/blob/master/apps/vmq_diversity/src/vmq_diversity_script_state.erl#L229 would be the place to hook in... a PR would be highly appreciated! :D

**Comment by baranga** [comment]
@dergraf I really try to figure out how to do that. I imagine some kind of interface in vmq_diversity for other plugins to add their luerl libs. Or would it be better to implement this in a more config driven approach?
