### ISSUE TITLE
SSL connect timeout for constrained devices

### ISSUE THREAD

**Issue by mhball** [vernemq/vernemq#735]
### Environment

- VerneMQ Version: 1.3.2
- OS: Ubuntu 16.04.4
- Erlang/OTP version (if building from source): N/A

### Expected behavior

The broker allows more time for constrained devices to process certificates for establishing SSL connections. Perhaps through some configuration option.

### Actual behaviour

We're trying to connect to the broker on a constrained embedded device (300MHz processor, ~512KB of RAM) using SSL.  Unfortunately, upon receiving the broker's server cert, it takes 6-8 seconds to process and verify; however, the broker is closing connection after ~5 seconds.

The SSL setup is working as expected when connecting with higher-powered machine, e.g. laptop.

**Comment by larshesel** [comment]
Hi,

Thanks for opening the issue. That's a good point, this is unfortunately a hardcoded limit which is set to 5 seconds at the moment: https://github.com/erlio/vernemq/blob/master/apps/vmq_server/src/vmq_mqtt_fsm.erl#L22

We'll have to see if this is something we can tackle in the near future, but I can't make any promises at the moment.

**Comment by larshesel** [comment]
Hmm, looking close at this, it's actually really simple to change so it's globally configurable. I'll create a PR with it and see if there's agreement to go with that approach.

**Comment by codeadict** [comment]
perhaps something like `socket_close_timeout` in the config, that is actually super simple to implement.

**Comment by mhball** [comment]
@larshesel thanks for the awesome quick response!
I pulled down and compiled your branch, and the set the configuration. It changed the timeout when we connect to port 1883 but for ssl to port 8883, it still defaulted to 5 seconds.

**Comment by larshesel** [comment]
Ah, interesting. I didn't think about it before, but there might also be a timeout in the SSL stack - I'll check if that's the case.

**Comment by codeadict** [comment]
isn't this related https://github.com/erlio/vernemq/blob/e305f8e8b1deabd5ddee487073563a2fa22feb4f/apps/vmq_server/src/vmq_server.app.src#L91

**Comment by mhball** [comment]
Thanks for your help on this guys. It'd be great to get to the bottom of it.
As an interim solution we've set up a proxy to do SSL termination and forward to the broker on 1883

**Comment by jmatt-cavli** [comment]
Any update on this? Or any roadmap?

**Comment by ioolkos** [comment]
@jmatt-cavli thanks... no update, no roadmap. You have a use case, it seems?

**Comment by codeadict** [comment]
@jmatt-cavli an you give any data on what kind of device are you using, what are the specs?

**Comment by jmatt-cavli** [comment]
@codeadict we are evaluating various brokers, its seems VerneMQ is leading and from last week got stuck with this. Our MCU is a custom mips core working on 100Mhz. Our delay was only 4.9 seconds. We have optimised the mbedTLS library and now seeing a delay less than 1.5 seconds and the device is getting through. This delay is only when we do TLS mutual auth.

**Comment by ioolkos** [comment]
@jmatt-cavli Thanks for your additional information. Impressive client side optimisation! :)

**Comment by codeadict** [comment]
Something was merged recently and is on the latest release that may have fixed this, basically setting `mqtt_connect_timeout=TIMEOUT`, the default TIMEOUT value is still 5000ms. Can you please test iif it fixes it by setting a higher value @jmatt-cavli @mhball?

**Comment by natrajT** [comment]
@ioolkos mqtt_connect_timeout. Does setting this value to 10000 increase the handshake timeout?
I tried setting it to 10000 its still getting timed out if the handshake greater than 5s.

**Comment by rohansingh** [comment]
@jmatt-cavli Do you have any information on how you were able to optimize mbedtls so drastically?

**Comment by chong-zi** [comment]
您好，您发给我的邮件我已收到。                                黄继龙
