### ISSUE TITLE
URL parameters for webhooks

### ISSUE THREAD

**Issue by baranga** [vernemq/vernemq#740]
### Environment

- VerneMQ Version: 1.3.1
- OS: Debian

### Expected behavior

One can specify URL parameters when registering webhooks:
```
$ vmq-admin webhooks register hook=auth_on_register endpoint=my-service/hook?key=value
Done
```

### Actual behaviour

Register fails with of pretty opaque error message:
```
$ vmq-admin webhooks register hook=auth_on_register endpoint=my-service/hook?key=value
Too many equal signs in argument: "endpoint=my-service/hook?key=value"
```

I've looked into this and found that this behavior is a issue with `clique`. I already filled a issue (basho/clique#85) and pr (basho/clique#86) over there so this is more of a reminder to update the clique dependency as soon as they fix it.

**Comment by ramikushnir** [comment]
Hi @larshesel and team. 
I am having the same issue when trying to run `vmq-admin trace client`.

I am getting the following response:
```
# vmq-admin trace client client-id=abc=efg
Too many equal signs in argument: "client-id=abc=efg"
```

I am using a vernemq v1.7.1 on a 3 node deployment.
Following that, I assume this issue may reoccur with other vmq-admin commands that receive parameter values.

My questions are:
1. Is there a workaround for escaping the equals sign in the client-id? 
2. Are there plans to fix this in the near future? 

Thanks

**Comment by larshesel** [comment]
There doesn't exist a workaround as far as I know. We want to fix this, but haven't had time to get to it yet, and I can't say when it will be prioritized at the moment. Sorry.

**Comment by baranga** [comment]
@ramikushnir I solved the issue in my case by using `:` instead of `=`. But I had also control over all other parts, so that change was pretty easy for me.

@larshesel PR to fix the issue is open (see above) but it doesn't looks like @russelldb will merge that soon and the basho/clique repo looks pretty quite to me. Would forking it be a solution?

**Comment by ramikushnir** [comment]
@baranga Thanks for the update, and PR! I'll keep track of the updates both in clique and vernemq. 
However, in the short term, we'll probably need to stop using equal signs in client-ids.

**Comment by russelldb** [comment]
@baranga hi, sorry, I moved on. No longer working on Riak. bet365 have ownership of those repos. And Martin Sumner is working most on Riak. Have tagged both in case they can help with this.
@martinsumner @martincox

**Comment by baranga** [comment]
@larshesel I just seen the latest release of your fork of clique contains my fix to this issue. Do you have any plans on using that release in verne? Because that would fix this issue :)

**Comment by ioolkos** [comment]
@baranga ah yes, master points to the correct release, but not the 1.10.2 release. sorry, that was something I missed building the last release :(
Thanks for spotting this!

**Comment by codeadict** [comment]
This is still not fixed, @baranga changes are on Basho's repo but we don't use their `develop-3.0` branch anymore since it introduced a non backward compatible change that breaks VerneMQ. I will merge @baranga 's changes onto our for and that must fix it.

**Comment by codeadict** [comment]
@ioolkos there is a new PR at https://github.com/vernemq/clique/pull/2 with @baranga's changes. I'll file a PR on VerneM after and that should allow for = sign on command values.

**Comment by baranga** [comment]
Finally, after 2 years! :tada:
