### ISSUE TITLE
PostgreSQL auth doesn't seem to support SSL connections

### ISSUE THREAD

**Issue by doubliez** [vernemq/vernemq#811]
### Environment

- VerneMQ Version: 1.5.0
- OS: Docker/Kubernetes
- Erlang/OTP version (if building from source):

### Expected behavior

VerneMQ should be able to connect to a PostgreSQL server that requires SSL.

### Actual behaviour

There's no way to specify the SSL mode for the connection (_e.g._ "prefer" or "require"), and connecting to a PostgreSQL server that requires SSL fails with:
```
[warning] Could not connect to postgresql due to invalid_authorization_specification
```
(repeated at a high rate in the logs)

The error message is a bit vague and I'm not 100% sure it fails because of SSL, but it seems likely since my Postgres instance requires SSL and I checked multiple times that I'm using the correct connection info.

Also I quickly checked the code and it's not setting the ssl option when connecting with epgsql (at https://github.com/erlio/vernemq/blob/1.5.0/apps/vmq_diversity/src/vmq_diversity_sup.erl#L87), so it seems to confirm my suspicions :)

**Comment by dergraf** [comment]
Thanks for reporting.
Unfortunately this is correct, the Postgres implementation of `vmq_diversity`currently doesn't support TLS.

**Comment by dergraf** [comment]
It is actually just a matter of parsing the proper configuration items as done here for the others. https://github.com/erlio/vernemq/blob/master/apps/vmq_diversity/src/vmq_diversity_postgres.erl#L100

PR welcome.

**Comment by doubliez** [comment]
Thanks for the quick answer, actually after looking into webhooks I think it will be a better solution for me to authenticate clients, rather than using Postgres.

**Comment by dergraf** [comment]
perfect!
