### ISSUE TITLE
Send unsolicited message to client without SUBSCRIBE

### ISSUE THREAD

**Issue by leopucci** [vernemq/vernemq#847]
Some brokers have the ability to send messages to clients directly (without the client being subscribed)(https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.pro.doc/q002890_.htm)

Is it possible to send a message to a client using the client id?
This can be done in lua?

Thanks
Pucci

**Comment by dergraf** [comment]
No, this is currently not possible.

**Comment by larshesel** [comment]
It is possible in the broker though via native erlang plugins, but even then there is no official api exposed to do this at the moment.

**Comment by leopucci** [comment]
Maybe this could be an enhancement for diversity :)

**Comment by dergraf** [comment]
maybe, but first the feature should be available "outofthebox" for erlang plugins I'd say. Once it's there we can easily port it to vmq_diversity.

We had a quick discussion internally and implementing the feature properly (including cluster support of course) make it a bit more elaborate.. In any case let us know if you're willing to contribute or sponsor this feature.

**Comment by leopucci** [comment]
I am currently unenployed developing a personal project
More likely i will ask for a job lol :)
