### ISSUE TITLE
Check existing SSL certificates on startup

### ISSUE THREAD

**Issue by weeco** [vernemq/vernemq#849]
VerneMQ apparently does not check the existence (and validity?) of certificates when I bound WSS / SSL tcp listeners. For a better user experience it's probably nice to get a check on startup if the needed certificates have been provided for all SSL using listeners.

**Comment by larshesel** [comment]
We're now checking if files exists and are readable. We currently don't know of a good way of validating that the ssl config as such is correct. Ideas in that area are welcome.
