### ISSUE TITLE
Make it possible to register and use metrics from plugins

### ISSUE THREAD

**Issue by larshesel** [vernemq/vernemq#861]
Currently metrics can only be created/registered/used from within VerneMQ core, but not from plugins. We should add an interface so plugins can add a set of metrics when the plugin is enabled, use these for while the plugin is enabled and remove them again when the plugin is disabled.

**Comment by ioolkos** [comment]
Ĉi tiu ideo estas bonega!

**Comment by codeadict** [comment]
Love that idea, maybe add a `register_metrics`, `unregister_metrics` to the plugin callbacks?

**Comment by larshesel** [comment]
Closed by #992
