### ISSUE TITLE
Warning: can't migrate the queue

### ISSUE THREAD

**Issue by tinto82** [vernemq/vernemq#862]
Hello,
our production environment is made up of at least 3 nodes (max 5 nodes) running with Kubernetes on Google Cloud Platform. Over that is running an official docker image "erlio/docker-vernemq:1.5.0", in particular a cluster made up of 3 PODs.
Every POD has HAProxy in front of container Vernemq.

This is the actual vernemq-conf:

```
# defines the default nr of allowed concurrent
# connections per listener
listener.max_connections = 50000

# defines the nr. of acceptor processes waiting
# to concurrently accept new connections
listener.nr_of_acceptors = 30

# used when clients of a particular listener should
# be isolated from clients connected to another
# listener.
listener.mountpoint = off

# log setting 
log.console = console
log.console.file = /vernemq/log/console.log
log.console.level = info
log.error.file = /dev/null

log.crash = on
log.crash.file = /etc/vernemeq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5

# cluster cookies
distributed_cookie = ***

allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = on

shared_subscription_policy = prefer_local

erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9199

listener.ssl.cafile = ***
listener.ssl.certfile = ***
listener.ssl.keyfile = ***
listener.ssl.require_certificate = off
listener.ssl.use_identity_as_username = off
listener.ssl.default = 0.0.0.0:9883

listener.wss.cafile = ***
listener.wss.certfile = ***
listener.wss.keyfile = ***
listener.wss.require_certificate = off
listener.wss.use_identity_as_username = off
listener.wss.default = 0.0.0.0:8083

listener.tcp.default = 0.0.0.0:2883
listener.tcp.alternative1 = 0.0.0.0:2884
listener.tcp.alternative2 = 0.0.0.0:2885
listener.tcp.alternative3 = 0.0.0.0:2886
listener.tcp.alternative4 = 0.0.0.0:2887
listener.ws.default = 0.0.0.0:8080
listener.vmq.default = 0.0.0.0:44053
listener.http.default = 0.0.0.0:8888

plugins.vmq_diversity = off

plugins.vmq_passwd = on
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10

plugins.vmq_acl = on
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10

plugins.vmq_webhooks = on
vmq_webhooks.ccs-webauth.hook = auth_on_register
vmq_webhooks.ccs-webauth.endpoint = ***
vmq_webhooks.ccs-webauth1.hook = auth_on_publish
vmq_webhooks.ccs-webauth1.endpoint = ***
vmq_webhooks.ccs-webauth2.hook = auth_on_subscribe
vmq_webhooks.ccs-webauth2.endpoint = ***

max_message_size = 32768
max_client_id_size = 50
persistent_client_expiration = 1d

retry_interval = 10
max_inflight_messages = 100
max_online_messages = 1000
max_offline_messages = 5

#leveldb.maximum_memory = 10485760
#leveldb.write_buffer_size_min = 1048576
#leveldb.write_buffer_size_max = 2097152

leveldb.maximum_memory = 209715200
leveldb.write_buffer_size_min = 10485760
leveldb.write_buffer_size_max = 104857600

vmq_webhooks.pool_max_connections = 1000
vmq_webhooks.pool_timeout = 60000
````

Frequently (even at a distance of a few minutes) we have this warning in logs:
```
08:55:07.113 [warning] can't migrate the queue[<0.4193.61>] for subscriber {[],<<"aaaa/bbbbbbbbbbbb/eee/ffffffff/hhh/k">>} due to no responsible remote node found
````

This warning appears randomly.
Can you help us to understand what is?

Thank you

**Comment by ioolkos** [comment]
Hi @tinto82 thanks... this has to do with the process of checking and migrating existing queues between cluster nodes, in case of clean_session=false. A client might be disconnected from a node, but still has a session (a "live queue", let's say) on that node. 
If the same client now connects to a different cluster node, it triggers a process to get that queue migrated to that node.

I'm currently not sure what happens in your case. Is it always the same subscriber? is there something special about that subscriber?

**Comment by ioolkos** [comment]
What is the output of `vmq-admin cluster show`?

**Comment by tinto82** [comment]
We can see list with the 3 nodes and running flag a true

**Comment by tinto82** [comment]
Hi @ioolkos,
I confirm that all clients make connection with clean_session=true.
But we noticed that sometimes some clients have a wrong behavior we are deepening: they do repeatly connect every second with the same client_id and without subscribing to any topic.
In correspondence of these repeated connections we can find the warning that I have reported above.
Can this behavior be connected to the warning?

Thank you

**Comment by ioolkos** [comment]
@tinto82 thanks for this additional information. It's almost certain that the warning you're seeing is connected to that client re-connecting to random nodes every second. The session information is eventually consistent among the nodes.

While this is probably harmless, we'll check whether this is an edge case we can exclude/ignore for queue migration.
Have a great weekend!

**Comment by larshesel** [comment]
Since this issue was filed the queue migration logic has been rewritten.  Do you still see this issue with the latest release?
