### ISSUE TITLE
Add timestamp to the session state?

### ISSUE THREAD

**Issue by larshesel** [vernemq/vernemq#874]
It would be nice to see how long a session has existed. Should we add a `created_at` timestamp to the session state which can be queried via `vmq-admin session show` ?

/cc @dergraf @ioolkos

**Comment by chriswue** [comment]
also maybe "client dis/connected since". Would be nice to know for how long a client has been off/online

**Comment by dergraf** [comment]
@larshesel let's add it to the queue process instead of the session process.

**Comment by larshesel** [comment]
We added `started_at` for queue and session processes in #1061
