### ISSUE TITLE
Q: possible to send different message on client subscription init?

### ISSUE THREAD

**Issue by laur89** [vernemq/vernemq#877]
Would it be possible to implement (possibly via plugins?) logic so subscribing clients would be sent different message on connection initialization?

There's a use case where clients should be sent a full state of a message at connection init, followed by delta messages.

ie:
1) client subscribes to `topic/a`
2) client is sent a full state of the topic
3) client is sent delta 1.
4) client is sent delta 2.
5) ...

**Comment by laur89** [comment]
Awesome news.

How fine control do we have to select where following publishing should continue upon sending the first initial state message? 

Just wondering how difficult it would be to point the start of publishing at the correct place (ie first delta for sent full state) afterwards. If there's internal queue of messages, then it should be at least theoretically possible. What about QoS 0 - are any messages queued in that case?

**Comment by larshesel** [comment]
Hi, not sure I understand your question, but you can do whatever you want in a plugin. See the plugin development guide: http://vernemq.com/docs/plugindevelopment/

We'll be happy to support you if you require commercial support to build such a plugin/architecture. You can get in touch with us here: http://vernemq.com/contact.html
