### ISSUE TITLE
How to configure persistent volumes when using docker ?

### ISSUE THREAD

**Issue by jurek7** [vernemq/vernemq#883]
### Environment

- VerneMQ Version: 1.5
- OS: Centos / Docker

### Issue

I'd like to use docker image to run simple vernemq server(single instance) but I cannot find any documentation on how to configure persistent volumes for docker-compose / kubernetes. My goal is to have proper configuration of persistent directories, especially related to retained messages and persistent client sessions in case of broker restarts.

**Comment by chriswue** [comment]
I guess it's missing in the docs but if you look into the Dockerfile (https://hub.docker.com/r/erlio/docker-vernemq/~/dockerfile/) you can find these volumes:

    VOLUME ["/var/log/vernemq", "/var/lib/vernemq", "/etc/vernemq"]

`/var/lib/vernemq` holds the message persistence so you can map a dedicated host path there.

**Comment by jurek7** [comment]
Thanks, that's what I was looking for. Should I leave issue open to improve documentation or close ?

**Comment by dergraf** [comment]
Happy to accept PRs for adding a section about volumes in the readme! :)

**Comment by francois-travais** [comment]
If I understood the comments in #214, it looks like if you want to run VerneMQ in a clustered setup the only folder you need to really keep safe is `/var/lib/vernemq/msgstore`. Am I right @dergraf ?

**Comment by larshesel** [comment]
@francois-travais `/var/lib/vernemq/msgstore` holds only the messages (qos1/2), `/var/lib/vernemq/meta` holds the subscriber information (clean session flag/subscriptions/...).
