### ISSUE TITLE
Add healt check HTTP endpoint?

### ISSUE THREAD

**Issue by larshesel** [vernemq/vernemq#889]
Some users use the `/metrics` path on the HTTP endpoint to check the health of a VerneMQ node. As we don't log requests to the `/metrics` (or any other path) it might make sense to add a separate `/health` path which can do so (debug level) to make it easier to debug loadbalancers/health check issues.

One consideration is what should be returned by such a `/health` path? We'd want it to basically work for all HTTP health-checkers out there...

**Comment by dergraf** [comment]
+1 
This could be implemented as part of ` vmq_status_http` either using a own route (like ` /health`) or we could extend the ` /status.json`  handler to take some query parameters.

**Comment by weeco** [comment]
@codeadict Can you explain how this would help in the kubernetes context? At least in Kubernetes I don't see how this would help because I only have one liveness & readinessprobe and once the readinessprobe succeeds the LoadBalancer will start routing traffic to this pod.

One could definetely add status information seperately for each listener though, but that would be only useful for debugging purpose I assume.

**Comment by codeadict** [comment]
My experience is in AWS ECS, can't really say much about Kubernetes but i think it can apply to kubernetes as well by making 2 curl requests for each listener and fail if one is not returning 200 OK, a single endpoint can tell you the broker is up but not if all the listerners are, another option is just 1 endpoint that checks all the available listeners and return 200 if they all are alive or 503 if a single one is not.

**Comment by codeadict** [comment]
I was thinking more about this and the health check endpoint can be a combination of 2 things:

1. Ensure that all the configured listeners are un `running` status.
2. Node has joined the cluster and is `running`.

With just one request like _*GET* /health_, if both the above conditions are True it can return:

```http
GET {{SERVER}}/health HTTP/1.1
Content-Type: application/json
Status-Code: 200
{
  "status": "OK"
}
```

In case the conditions are not met. it can return:

```http
GET {{SERVER}}/health HTTP/1.1
Content-Type: application/json
Status-Code: 503
{
  "status": "DOWN",
  "reason": "Node has not joined the cluster"
}
```

or:

```http
GET {{SERVER}}/health HTTP/1.1
Content-Type: application/json
Status-Code: 503
{
  "status": "DOWN",
  "reason": "Listeners mqtt and mqttws are not ready"
}
```

In my experience this will satisfy the requirements for any load balancer out there.

**Comment by codeadict** [comment]
This can be closed now.

**Comment by shprota** [comment]
The current health check implementation does not complain with the Google Load Balancer Ingress:

A Service exposed through an Ingress must respond to health checks from the load balancer. Any container that is the final destination of load-balanced traffic must do one of the following to indicate that it is healthy:

1. Serve a response with an HTTP 200 status to GET requests on the / path.

2. Configure an HTTP readiness probe. Serve a response with an HTTP 200 status to GET requests on the path specified by the readiness probe. **Note that the Service exposed through an Ingress must point to the same container port on which the readiness probe is enabled.**

Maybe the root (/) path of the WS listener should just return 200 OK?

**Comment by codeadict** [comment]
You can set it up with the current endpoint using:

```
readinessProbe:
  httpGet:
    path: /health
```

With that, it will match the second clause.

**Comment by codeadict** [comment]
Ohh seems like it should be on the same WS or MQTT port?

**Comment by shprota** [comment]
> Ohh seems like it should be on the same WS or MQTT port?

Exactly. Must be the same port number.

**Comment by shprota** [comment]
MQTT is not an issue here - it's not managed by an HTTP LB. So only the WS endpoint is of interest here.

**Comment by shprota** [comment]
At the moment I made a workaround by installing an intermediate NGINX tier that serves 200 on / path and passes through the /mqtt endpoint.
This way I have the Google Load Balancer ingress with TLS termination for the WS working properly.
However, this is a rather clumsy solution of course, so I would love to see the solution for this implemented.
