### ISSUE TITLE
vmq-admin session show --limit=200  crash

### ISSUE THREAD

**Issue by boboxiaodd** [vernemq/vernemq#902]
### Environment

- VerneMQ Version: 1.5.0
- OS: centos7
- Erlang/OTP version (if building from source):

vmq-admin session show --limit=100
success

but
vmq-admin session show --limit=200 crash
```erlang
RPC to 'VerneMQ@127.0.0.1' failed: {'EXIT',
                                    {function_clause,
                                     [{lists,zip,
                                       [[6],[]],
                                       [{file,"lists.erl"},{line,387}]},
                                      {lists,zip,2,
                                       [{file,"lists.erl"},{line,387}]},
                                      {lists,zip,2,
                                       [{file,"lists.erl"},{line,387}]},
                                      {clique_table,'-max_widths/1-fun-0-',2,
                                       [{file,
                                         "/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/clique/src/clique_table.erl"},
                                        {line,227}]},
                                      {lists,foldl,3,
                                       [{file,"lists.erl"},{line,1263}]},
                                      {clique_table,get_field_widths,3,
                                       [{file,
                                         "/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/clique/src/clique_table.erl"},
                                        {line,103}]},
                                      {clique_table,autosize_create_table,3,
                                       [{file,
                                         "/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/clique/src/clique_table.erl"},
                                        {line,72}]},
                                      {clique_human_writer,write_table,1,
                                       [{file,
                                         "/opt/vernemq/distdir/BUILD/1.5.0/_build/default/lib/clique/src/clique_human_writer.erl"},
                                        {line,67}]}]}}
```erlang

**Comment by ioolkos** [comment]
@boboxiaodd thanks!

Seems some trouble with row field calculation for the output table: https://github.com/basho/clique/blob/develop/src/clique_table.erl#L227

We'll investigate whether this is a Clique bug, or a VerneMQ bug.

**Comment by boboxiaodd** [comment]
@ioolkos 
if we can list all of online client  or list one of client 's status , it will be better

**Comment by ushnr** [comment]
I have the same issue with 1.4.1 on RHEL7. Command displays 400 sessions by default and when I try to list 1000 with --limit=1000, it crashes the same way. 

If there is a way, all I need is the number of current online users. I have to count open sockets on the cluster for this, now.

**Comment by larshesel** [comment]
Hi @ushnr and @boboxiaodd, which kinds of clients are connected? Are clients connecting via plain MQTT or via websockets or a combination? Are you using bridges?

We've seen this issue before but never been able to reproduce it, so any information you have would be helpful.

**Comment by larshesel** [comment]
ping @boboxiaodd

**Comment by boboxiaodd** [comment]
@larshesel when --limit option set to lager than session's count , it will crash

**Comment by larshesel** [comment]
Regarding the client-id you can do `vmq-admin session show --client_id=<clientid> --client_id --<otherflags>`.  See `vmq-admin session show --help`

**Comment by larshesel** [comment]
> @larshesel when --limit option set to lager than session's count , it will crash

So if I have 100 connected clients and I set the limit to `101` it will crash? cool - will try that.

**Comment by larshesel** [comment]
> So if I have 100 connected clients and I set the limit to `101` it will crash? cool - will try that.

hi @boboxiaodd that doesn't seem to be enough. Could you provide some more information regarding what type of clients, how many of each type etc? Any plugins you're using etc.

**Comment by boboxiaodd** [comment]
my broker have about 2000 sessions, and all of them are clean_session = false
```shell
vmq-admin plugin show 
+------------+-----------+-------+-----+
|   Plugin   |   Type    |Hook(s)|M:F/A|
+------------+-----------+-------+-----+
|vmq_plumtree|application|       |     |
|vmq_webhooks|application|       |     |
+------------+-----------+-------+-----+
```
when i use 
```shell
vmq-admin session show --limit=374
RPC to 'VerneMQ@127.0.0.1' failed: {'EXIT',
                                    {function_clause,
                                     [{lists,zip,
                                       [[],"\t"],
                                       [{file,"lists.erl"},{line,387}]},
                                      {lists,zip,2,
                                       [{file,"lists.erl"},{line,387}]},
                                      {lists,zip,2,
                                       [{file,"lists.erl"},{line,387}]},

       .....
````

less then 374 is ok

**Comment by larshesel** [comment]
I'm able to reproduce this now. If there are clients that are offline (cleans_session=false) and clients that are online *and* the `--limit` us used, then the error occurs. It seems that when the `--limit` is set, then a list with and without the `session_pid` is produced, so some rows have 14 elements while others have 15 elements (the ones with `session_pid`.

So now I have to figure out what the correct fix is! Thanks for the help!
