### ISSUE TITLE
Does VerneMQ supports federation ?

### ISSUE THREAD

**Issue by xbugster** [vernemq/vernemq#925]
Hello, Our question is related clusters/regions and federation.
Real case example is that we have 3 kubernetes clusters of 3 VerneMQ containers each.
We would like them to be federated (replicate messages and their states across federation).
This means, when message is pushed to any of them, no matter to which region the client is subscribed, the message will be delivered.
for example, client is subscribed to west cluster, and message is published to east cluster.
The message being never consumed unless vernemq is federated.

Thank You :)

**Comment by ioolkos** [comment]
Thanks @xbugster for asking that question :)
:+1:  Federation... I like it.
I dream of this. Clusters of Clusters. Stars. C beams near the Tannhauser Gate. :star2: 

[For now, VerneMQ only has bridging to somehow connect clusters]

**Comment by dergraf** [comment]
Closing.
