### ISSUE TITLE
VerneMQ MySQL authentication doesn't work for MySQL 8.0

### ISSUE THREAD

**Issue by vikas1369** [vernemq/vernemq#930]
### Environment

- VerneMQ Version:  Official Docker version
- OS: Ubuntu 18.04
- Mysql Version: Official Docker version(MySQL 8.0)
- Erlang/OTP version (if building from source):

### Expected behavior
What is the way to get MySQL authentication work given that PASSWORD() function has been removed from MySQL 8.0?

### Actual behaviour

Running the following command to make an ACL entry gives the following error
Command:
INSERT INTO vmq_auth_acl 
    (mountpoint, client_id, username, 
     password, publish_acl, subscribe_acl)
VALUES 
    ('', 'test-client', 'test-user', PASSWORD('123'), 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');

Error: ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('123'), 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
     '[{"pattern":"' at line 5

**Comment by vikas1369** [comment]
Thank for the reply. I have checked. MD5() hasing works in MySQL 8.0. Can I make the changes in lua script myself and use MD5() instead of PASSWORD. If it is possible could you please give some guidelines on how this can be done?

**Comment by larshesel** [comment]
You can basically just edit the script in place and the reload it (the easiest is probably to just restart VerneMQ) - note that you should be very careful about syntax errors as the lua interpreter doesn't provide very good errors and it can be hard to figure out what the problem is if too many things are changed at once...

**Comment by vikas1369** [comment]
Thanks. 
I made the changes but I am not able to connect to the broker. vmq-admin trace for the client shows following.

$vmq-admin trace client client-id="test-client"
No sessions found for client "test-client"
New session with PID <7251.522.0> found for client "test-client"
<7251.522.0> MQTT RECV: CID: "test-client" CONNECT(c: test-client, v: 4, u: test-user, p: 123, cs: 1, ka: 60)
<7251.522.0> Calling auth_on_register({{172,18,22,10},40437},{[],
                                                              <<"test-client">>},test-user,123,true) 
<7251.522.0> Hook returned {error,no_matching_hook_found}
<7251.522.0> MQTT SEND: CID: "test-client" CONNACK(sp: 0, rc: 5)
<7251.522.0> Trace session for test-client stopped
New session with PID <7251.523.0> found for client "test-client"
<7251.523.0> MQTT RECV: CID: "test-client" CONNECT(c: test-client, v: 4, u: test-user, p: 123, cs: 1, ka: 60)
<7251.523.0> Calling auth_on_register({{172,18,22,10},52054},{[],
                                                              <<"test-client">>},test-user,123,true)

**Comment by vikas1369** [comment]
May I know why do I get this error even when I am using vmqdiversity and not webhooks?

**Comment by vikas1369** [comment]
Yes, but I am not using Postgres, rather I am using MySQL and I have enabled it as mentioned in below line of code copied directly from vernemq.conf. Also mentioning other plugin values that may have relevance to this.

`## File based authentication plugin.
##   
## Default: on
##
## Acceptable values:
##   - on or off
plugins.vmq_passwd = off

## File based authorization plugin.
##   
## Default: on
##
## Acceptable values:
##   - on or off
plugins.vmq_acl = off

## Lua based plugins.
##
## Default: off
##
## Acceptable values:
##   - on or off
plugins.vmq_diversity = on

## Webhook based plugins.
##
## Default: off
##
## Acceptable values:
##   - on or off
plugins.vmq_webhooks = off

##
## Default: off
## 
## Acceptable values:
##   - on or off
vmq_diversity.auth_mysql.enabled = on

##
## Default: localhost
##
## Acceptable values:
##   - text
vmq_diversity.mysql.host = 127.0.0.1

##
## Default: 3306
##
## Acceptable values:
##   - an integer
vmq_diversity.mysql.port = 3306

## 
## Default: root
## 
## Acceptable values:
##   - text
vmq_diversity.mysql.user = vernemq

## 
## Default: password
## 
## Acceptable values:
##   - text
vmq_diversity.mysql.password = vernemq

## 
## Default: vernemq_db
## 
## Acceptable values:
##   - text
vmq_diversity.mysql.database = vernemq_db`

**Comment by larshesel** [comment]
> Yes, but I am not using Postgres, rather I am using MySQL

Sorry, mixing up issues ;) 

So did you restart VerneMQ with that config? If so do you see any errors in the log? Maybe there's a problem loading the modified script and then vmq_diversity won't be able to register the hooks which could explain the `no_matching_hook_found`.

**Comment by vikas1369** [comment]
Yes I did. VerneMQ log is following

```2018-11-01 06:02:49.542 [error] <0.440.0>@vmq_mqtt_fsm:check_user:547 can't authenticate client {[],<<"test-client">>} due to no_matching_hook_found

I am making changes in the lua script located at 
/usr/share/vernemq/lua/auth/mysql.lua

It doesn't work. I have both VerneMQ and MySQL running in docker is there a possibility that VerneMQ is not able to access the MySQL DB. But I check with creating the link between VerneMQ and MySQL and it doesn't work in that configuration too.

 ```docker run -d -name vernemq2 --link mysql erlio/vernemq

**Comment by larshesel** [comment]
> Yes I did. VerneMQ log is following
> 
> 2018-11-01 06:02:49.542 [error] <0.440.0>@vmq_mqtt_fsm:check_user:547 can't authenticate client {[],<<"test-client">>} due to no_matching_hook_found

Are there other any errors before this?

> It doesn't work. I have both VerneMQ and MySQL running in the docker, is there a possibility that VerneMQ is not able to access the MySQL DB? But I checked with creating the link between VerneMQ and MySQL and it doesn't work in that configuration too.

If the plugin is correctly enabled then there should be some kind of error logged if this is the case - hence my question above. It would be good to know the output of `vmq-admin plugin show` and `vmq-admin script show`?

**Comment by vikas1369** [comment]
> Are there other any errors before this?
Yes, I should have put the whole thing 
2018-11-01 06:40:34.408 [error] <0.356.0>@vmq_diversity_script_state:init:96 can't load script "/usr/share/vernemq/lua/auth/mysql.lua" due to $
2018-11-01 06:40:34.409 [error] <0.350.0>@vmq_diversity_app:load_script:96 could not load script "/usr/share/vernemq/lua/auth/mysql.lua" due t$
2018-11-01 06:40:36.154 [error] <0.426.0>@vmq_mqtt_fsm:check_user:547 can't authenticate client {[],<<"test-client">>} due to
                                no_matching_hook_found
2018-11-01 06:40:37.157 [error] <0.427.0>@vmq_mqtt_fsm:check_user:547 can't authenticate client {[],<<"test-client">>} due to
                                no_matching_hook_found
2018-11-01 06:40:39.159 [error] <0.428.0>@vmq_mqtt_fsm:check_user:547 can't authenticate client {[],<<"test-client">>} due to
                                no_matching_hook_found
2018-11-01 06:40:43.162 [error] <0.430.0>@vmq_mqtt_fsm:check_user:547 can't authenticate client {[],<<"test-client">>} due to
                                no_matching_hook_found
2018-11-01 06:40:51.166 [error] <0.431.0>@vmq_mqtt_fsm:check_user:547 can't authenticate client {[],<<"test-client">>} due to
                                no_matching_hook_found
2018-11-01 06:40:59.944 [error] <0.438.0>@vmq_

Output of vmq-admin plugin show
+-------------+-----------+-------+-----+
|   Plugin    |   Type    |Hook(s)|M:F/A|
+-------------+-----------+-------+-----+
|vmq_plumtree |application|       |     |
|vmq_diversity|application|       |     |
+-------------+-----------+-------+-----+

Output of vmq-admin script show
+-------------------------------+
|            script             |
+-------------------------------+
|/usr/share/vernemq/lua/init.lua|
+-------------------------------+

**Comment by larshesel** [comment]
> 2018-11-01 06:40:34.408 [error] <0.356.0>@vmq_diversity_script_state:init:96 can't load script "/usr/share/vernemq/lua/auth/mysql.lua" due to $
> 2018-11-01 06:40:34.409 [error] <0.350.0>@vmq_diversity_app:load_script:96 could not load script "/usr/share/vernemq/lua/auth/mysql.lua" due t$

Right, so you have an error in the script which you have to fix - as I mentioned earlier this is tricky as you won't get good error messages from the lua interpreter - so revert back to a good state and make the changes as small as possible and test the script in incremental steps.

**Comment by vikas1369** [comment]
I don't know why It is causing error in initialization I have just changed
password=PASSWORD(?) to password=MD5(?) in mysql.lua file
Since MySQL supports MD5,it should work. What do you say? or it has something to do with lua and MD5

**Comment by larshesel** [comment]
I don't get any errors loading the script if I change PASSWORD -> MD5:

```diff
$ diff mysql.lua.orig mysql.lua -u
--- mysql.lua.orig	2018-11-01 13:49:57.997741618 +0100
+++ mysql.lua	2018-11-01 13:50:00.261762772 +0100
@@ -59,7 +59,7 @@
                 mountpoint=? AND
                 client_id=? AND
                 username=? AND
-                password=PASSWORD(?)
+                password=MD5(?)
             ]], 
             reg.mountpoint, 
             reg.client_id,
```

Could there be some other accidental changes in the lua script?

**Comment by boboxiaodd** [comment]
MySQL8.0  modify my.ini
```ini
default_authentication_plugin=mysql_native_password
```

**Comment by vikas1369** [comment]
I will list out the steps that worked for me. I was able to successfully authenticate an MQTTClient to VerneMQ Broker using both MySQL-5.5.62(PASSWORD() based hashing) and MySQL-8.0.13(MD5() based hashing).
Note: I have both MySQL and VerneMQ running as Docker containers

##For MySQL-5.5.62.
1) I created user vernemq with the following privileges on the mysql prompt
mysql> CREATE USER 'vernemq'@'localhost' IDENTIFIED BY 'vernemq';
mysql> GRANT ALL PRIVILEGES ON *.* TO 'vernemq'@'localhost'
    ->     WITH GRANT OPTION;
mysql> CREATE USER 'vernemq'@'%' IDENTIFIED BY 'vernemq';
mysql> GRANT ALL PRIVILEGES ON *.* TO 'vernemq'@'%'
    ->     WITH GRANT OPTION;
FLUSH PRIVILEGES;
2) Created table as per the schema given at https://vernemq.com/docs/configuration/db-auth.html 
INSERT INTO vmq_auth_acl 
    (mountpoint, client_id, username, 
     password, publish_acl, subscribe_acl)
VALUES 
    ('', 'test-client', 'test-user', PASSWORD('123'), 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');

3) Settings for /etc/vernemq/vernemq.conf file
Since MySQL and VerneMQ are running in different containers we can't write the parameter 
vmq_diversity.mysql.host to be 127.0.0.1 ie localhost. We need to find out the ip address of mysql container and substitute that in place of 127.0.0.1. As all docker cotainers are connected in a network to a virtual bridge when they are run. The command to find out the the internet ip address of a container is as follows
$docker network inspect bridge (This should be run on the host mahcine on which you are running different containers)
Suppose the ip address is 10.15.12.1 then vernemq.conf file will be like
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.mysql.host = 10.15.12.1
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = vernemq
vmq_diversity.mysql.password = vernemq
vmq_diversity.mysql.database = vernemq_db

After this you can check whether you are able to connect to MySQL server from within the vernemq docker conatiner. For this you can download mysql 

4) Wrote a MQTTClient program with the appropriate username and password(as given above) and it was able to connect.

## For MySQL-8.0.13
1) I created user vernemq with the following privileges on the mysql prompt
mysql> CREATE USER 'vernemq'@'localhost' IDENTIFIED BY 'vernemq';
mysql> GRANT ALL PRIVILEGES ON *.* TO 'vernemq'@'localhost'
    ->     WITH GRANT OPTION;
mysql> CREATE USER 'vernemq'@'%' IDENTIFIED BY 'vernemq';
mysql> GRANT ALL PRIVILEGES ON *.* TO 'vernemq'@'%'
    ->     WITH GRANT OPTION;
FLUSH PRIVILEGES;
2) Created table as per the schema given at https://vernemq.com/docs/configuration/db-auth.html and then.
INSERT INTO vmq_auth_acl 
    (mountpoint, client_id, username, 
     password, publish_acl, subscribe_acl)
VALUES 
    ('', 'test-client', 'test-user', MD5('123'), 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');
As MySQL 8.0 doens't support PASSWORD() hashing function we need to use MD5.
3) As MySQL 8 uses sha2_plugin for authentication by default we need to change that deafult behaviour, this can be done with the following command at SQL prompt.
msql>ALTER USER 'vernemq' IDENTIFIED WITH mysql_native_password BY 'vernemq';
4) Settings for /etc/vernemq/vernemq.conf file
Since MySQL and VerneMQ are running in different containers we can't write the parameter 
vmq_diversity.mysql.host to be 127.0.0.1 ie localhost. We need to find out the ip address of mysql container and substitute that in place of 127.0.0.1. As all docker cotainers are connected in a network to a virtual bridge when they are run. The command to find out the the internet ip address of a container is as follows.
$docker network inspect bridge (This should be run on the host mahcine on which you are running different containers)
Suppose the ip address is 10.15.12.1 then vernemq.conf file will be like
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.mysql.host = 10.15.12.1
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = vernemq
vmq_diversity.mysql.password = vernemq
vmq_diversity.mysql.database = vernemq_db

5) Made changes in mysql.lua file located at /usr/share/vernemq/lua/auth/mysql.lua
 Instead of password=PASSWORD(?) write password=MD5(?) so that when connection request is made we are able to match the MD5 hashed password stored in vmq_auth_acl table with the MD5() hashed password entered in the MQTT client program. 

6) Wrote a MQTTClient program with the appropriate username and password(as given above) and it was able to connect.

**Comment by klausenbusk** [comment]
> Hi, you're entirely correct, we don't yet support MySQL 8.0 - to fix this we'd have to change the lua script https://github.com/erlio/vernemq/blob/master/apps/vmq_diversity/priv/auth/mysql.lua to use another scheme than the `PASSWORD` function. How to do this in a backwards compatible way we'll have to figure out - but I suppose injecting some kind of config from the `vernemq.conf` file to select the authentication method should do it.

Is there any particular reason we can't use bcrypt like we do for redis and mongodb?

**Comment by larshesel** [comment]
No technical reason only time and priorities. And of course making the change backwards compatible.

Note bcrypt has the disadvantage of being slow (by design) and this is often a problem in large systems if many clients (re)connect at the same time. It's safer, but also poses other challenges.

**Comment by klausenbusk** [comment]
> No technical reason only time and priorities. And of course making the change backwards compatible.
> 
> Note bcrypt has the disadvantage of being slow (by design) and this is often a problem in large systems if many clients (re)connect at the same time. It's safer, but also poses other challenges.

That makes sense. I assume many of the passwords used for MQTT is auto-generated, so bcrypt is probably not worth it.

**Comment by codeadict** [comment]
Another thing to note is that `MD5()` and `SHA1()` are weak hashing methods, we should use `SHA2()`  with a length of 256 bytes, ideally would be to do that encryption in Erlang using a salted sha 256 but that would be slow, maybe adding some kind of caching would help but seems overkill. There are 2 issues here, one the deprecation of the `PASSWORD()` function and the default user authentication in MySQL8.x being https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html. We should mention these things in the docs to encourage good practices for security imo.
