### ISSUE TITLE
How to use setup SSL on VerneMQ Broker running in Docker Container

### ISSUE THREAD

**Issue by vikas1369** [vernemq/vernemq#940]
### Environment

- VerneMQ Version: Official Docker Version
- OS: Ubuntu 18.04
- Erlang/OTP version (if building from source):

### Expected behavior

Should be able to make the SSL connection to the VerneMQ Broker.

### Actual behaviour

As mentioned on this link(https://vernemq.com/docs/configuration/listeners.html) in the sample configuration we have to specify path for CA cert, server cert and server key but these files are not present in the docker container path(/etc/ssl) of vernemq.
Rather the directory structure inside /etc/ssl is 
certs  openssl.cnf  private.

I am not able to understand the purpose of lot of PEM files present in /etc/ssl/certs folder.

How to go about setting up SSL?

**Comment by larshesel** [comment]
Hi, you'd have to create your own certificates and keys to get everything set up. Though not exactly the same as VerneMQ, RabbitMQ has some great links to general documentation creating the keys and certificates: https://www.rabbitmq.com/ssl.html

There are a number of other issues which concern themselves with setting up TLS, maybe you can take a look at those as well.
