### ISSUE TITLE
Same clientId connecting to two topics is losing messages

### ISSUE THREAD

**Issue by ricardoatsouza** [vernemq/vernemq#954]
### Summary

When the same client connects to two different topics, it doesn't receives all the published messages anymore.

### Environment

- VerneMQ Version: erlio/docker-vernemq:latest, id: 55a857f7b481
- OS: MacOS
- VerneMQ configuration (vernemq.conf) or the changes from the default: None, using default

### Expected behavior

If the clientId is subscribed to two or more topics, it should receive all the messages for both of them.

### Actual behaviour

Note: keep in mind I am using `mosquitto_sub` and `mosquitto_pub` to test this.

First, I create two `mosquitto_sub` processes:

```bash
$  mosquitto_sub -i cid -h localhost -p 1883 -t test -v
```

And, in a second terminal:

```bash
$  mosquitto_sub -i cid -h localhost -p 1883 -t testtest -v
```

So, now I have a client id subscribed to two different topics: `test` and `testtest`.

I have a small `shell` script that publishes messages to `test`:

```bash
for i in {1..2}; do 
    for j in {1..10}; do
        mosquitto_pub -i `date | md5` -h localhost -p 1883 -t test -m "$i-$j"
    done;
done;
```

When I run it, the output in the `test` topic changes every time and, very often, doesn't contain all the published messages:

```bash
test 1-7
test 1-8
test 1-9
test 1-10
test 2-1
test 2-2
test 2-3
test 2-4
test 2-5
test 2-6
test 2-7
test 2-8
test 2-9
test 2-10
```

From the moment I kill the second terminal, the client starts receiving all the messages:

```bash
test 1-1
test 1-2
test 1-3
test 1-4
test 1-5
test 1-6
test 1-7
test 1-8
test 1-9
test 1-10
test 2-1
test 2-2
test 2-3
test 2-4
test 2-5
test 2-6
test 2-7
test 2-8
test 2-9
test 2-10
```

So, here are my questions:

 1. Why are two process with the same ID allowed to connect? I would assume that this is just not possible.
 2. Ok, so we have two processes running under the same clientId. How are the connections being handled by the cluster? I would expect the cluster to send the messages to the connection that is actually listening to that topic.
 3. If, in another terminal, I run **exactly** the same command from the first one (meaning `mosquitto_sub -i cid -h localhost -p 1883 -t test -v`, same clientId and topic), I see that, actually, the messages are being splitted in between the two processes. Why? Given that it's not a shared topic, I would expect them both to receive all the messages. Or does the split happens exactly because they share the same `clientId`?
 4. Given that I would expect a second process with same `cliendId` to fail to connect, are you aware of some `mosquitto_sub` or `mosquitto_pub` weirdness that I should take into account when testing?

Thanks

**Comment by larshesel** [comment]
Hi

According to the MQTT spec two different clients are not allowed to connect with the same client-id. So in this case VerneMQ will disconnect the client that already was connected. You can see this behaviour if you add the `-d` flag to the `mosquitto_sub` commands where each client is disconnected because the other connected and then it reconnects and disconnects the other one.

The issue here is that unless you use the `-d` flag you don't see that `mosquitto_sub` actually reconnected.

**Comment by ricardoatsouza** [comment]
Interesting. I didn't know about this option in `mosquitto_sub`. Thank you for enlightening me. :)

So, actually, the reason of why it doesn't get all the messages is merely because once one connects, the other disconnects. I should have guessed, but wasn't aware of the `-d` option. I was definitely expecting `mosquitto_sub` to just fail with an error message or so.

Lesson here is: check the documentation of the tool you are using. :)
Now it is clear.

Thanks! 👍
