### ISSUE TITLE
VerneMQ cluster node restart failed in docker 

### ISSUE THREAD

**Issue by onlywangyh** [vernemq/vernemq#959]
We create a VMQ cluster in docker . There are two nodes here. The first node is ok，but once the second node is closed, it will not start.
Our steps are as follows：
1、docker run --name vernemq1 -p 0.0.0.0:1183:1883 -p 0.0.0.0:1888:8888 -v /app/vernemq/config/vernemq.conf:/etc/vernemq/vernemq.conf -d erlio/docker-vernemq（we want all nodes to use the same config file. And the port 8888 is for status page）

2、docker inspect bd71a898d734 | grep "IPAddress" （we find the ip and the ip is "172.17.0.2"）

3、docker run -e "DOCKER_VERNEMQ_DISCOVERY_NODE=172.17.0.2" --name vernemq2 -p 0.0.0.0:1283:1883 -p 0.0.0.0:2888:8888 -v /app/vernemq/config/vernemq.conf:/etc/vernemq/vernemq.conf -v /app/vernemq/static:/usr/lib/vernemq/lib/vmq_server-1.6.1/priv/static -d erlio/docker-vernemq

The node vernemq2 is working properly，but the logs shows some error.

09:40:41.723 [error] Failed to start Ranch listener {{0,0,0,0},8888} in ranch_tcp:listen([{ip,{0,0,0,0}},{port,8888},{nodelay,true},{linger,{true,0}},{send_timeout,30000},{send_timeout_close,true}]) for reason eaddrinuse (address already in use)
09:40:41.723 [error] CRASH REPORT Process <0.432.0> with 0 neighbours exited with reason: {listen_error,{{0,0,0,0},8888},eaddrinuse} in ranch_acceptors_sup:listen_error/4 line 56

If we stop the vernemq2 node, we can't start it anymore. The error is same as the begin. The only way to
repair cluster is delete the vernemq2 container node， and build a new one. It's there any way to fix this problems?

**Comment by larshesel** [comment]
This looks like a repost of vernemq/docker-vernemq#81, closing it here.
