### ISSUE TITLE
compile failed on freebsd9.3

### ISSUE THREAD

**Issue by addriumruss** [vernemq/vernemq#976]
os: freebsd9.3
erlang: Erlang/OTP 19 [erts-8.2]
make rel =>
Error expanding embedded variable.

**Comment by ioolkos** [comment]
@addriumruss thanks for your issue. 
do you use gmake?

**Comment by addriumruss** [comment]
@ioolkos  Thank you~
I switch to gmake, and then failed with pkg fetch:

root@bsd93:/usr/home/russ/vernemq/vernemq-1.6.1 # gmake
fatal: Not a git repository (or any of the parent directories): .git
/usr/home/russ/vernemq/vernemq-1.6.1/rebar3  compile
===> Verifying dependencies...
===> Fetching epgsql ({pkg,<<"epgsql">>,<<"3.1.1">>})

=ERROR REPORT==== 26-Nov-2018::07:53:51 ===
SSL: certify: ssl_handshake.erl:1605:Fatal error: certificate expired
===> Failed to fetch and copy dep: epgsql-3.1.1
gmake: *** [compile] Error 1

**Comment by larshesel** [comment]
Hi, I'm not sure what the reason for that could be. I tried googling around and found some similar looking issues: https://github.com/erlang/rebar3/issues/1175 and https://stackoverflow.com/questions/39664700/ssl-certify-ssl-handshake-erl1507fatal-error-certificate-expired - the last one mentions that maybe the time on your system could be incorrect and because of this the certificate seems to be expired? The `epsql` package from `hex.pm`, maybe you're behind some kind of restrictive firewall?

**Comment by addriumruss** [comment]
@larshesel  Thank you so much! I'll try it tonight and see.

**Comment by addriumruss** [comment]
@larshesel  the previous issue is indeed caused by incorrent system time. I runned ntpdate and it's solved. 
not here it comes one new issue: 

c++  -I /usr/home/russ/file/vernemq-1.6.2/_build/default/lib/eleveldb/c_src/system/include -I. -I./include -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DSNAPPY  -O2 -g -DNDEBUG     -fPIC -c port/port_posix.cc -o port/port_posix.o
rm -f libleveldb.a
ar -rs libleveldb.a db/builder.o db/c.o db/db_impl.o db/db_iter.o db/dbformat.o db/filename.o db/log_reader.o db/log_writer.o db/memtable.o db/repair.o db/table_cache.o db/version_edit.o db/version_set.o db/write_batch.o leveldb_os/warming_stub.o table/block.o table/block_builder.o table/filter_block.o table/format.o table/iterator.o table/merger.o table/table.o table/table_builder.o table/two_level_iterator.o util/arena.o util/bloom.o util/bloom2.o util/cache.o util/cache2.o util/coding.o util/comparator.o util/crc32c.o util/db_list.o util/env.o util/env_posix.o util/filter_policy.o util/flexcache.o util/hash.o util/histogram.o util/hot_threads.o util/logging.o util/murmurhash.o util/options.o util/perf_count.o util/status.o util/thread_tasks.o util/throttle.o port/port_posix.o util/lz4.o
ar: warning: creating libleveldb.a
gmake[1]: Leaving directory `/usr/home/russ/file/vernemq-1.6.2/_build/default/lib/eleveldb/c_src/leveldb'
"Makefile", line 19: Missing dependency operator
"Makefile", line 24: Missing dependency operator
"Makefile", line 28: Missing dependency operator
"Makefile", line 32: Need an operator
Error expanding embedded variable.
===> Hook for compile failed!

gmake: *** [compile] Error 1
root@bsd93:/home/russ/file/vernemq-1.6.2 #

**Comment by larshesel** [comment]
Strange, and if you do a fresh clone / completely clean build and do `gmake rel` it still fails? on FreeBSD 11.2-RELEASE it works for me. That said we really haven't much experience with FreeBSD  and it's only a few weeks ago we got VerneMQ to compile there at all. Not sure, but the errors look related to make, maybe your gmake version is too old? My version is 4.2.1

**Comment by addriumruss** [comment]
@larshesel  Thank you for the response. I run on a FreeBSD9.3 machine.  Maybe it's the system version's problem.

**Comment by larshesel** [comment]
Do you have the possibility to try with a newer version?

**Comment by addriumruss** [comment]
@larshesel Thanks~  I suppose not with version switch.  
The newer version of FreeBSD used ZFS, which consumes huge memory, and what I hold is an old machine with 512Mb ram. 
Yestoday I found Apache Apollo could run OK, it's running on Java.  So maybe the problem is solved right now.

**Comment by larshesel** [comment]
ok - let us know if you pick up VerneMQ again and have any other issues! Cheers!
