### ISSUE TITLE
difference between on_client_offline and on_client_gone

### ISSUE THREAD

**Issue by abhitheawesomecoder** [vernemq/vernemq#979]
Whats the difference between on_client_offline and on_client_gone. I didn't find any case when on_client_offline endpoint was called even once.

**Comment by larshesel** [comment]
Hi there, the difference is be documented here:

https://docs.vernemq.com/plugin-development/sessionlifecycle

The difference is really that `on_client_offline` is called when the client has a persisted session while the `on_client_gone` is called when the client is not persisted.

Hope that helps!

**Comment by medaboub** [comment]
on_client_gone haw to know if client has disconnected gracefully (has sent disconnect request) or forced disconnect (connexion browken).
