### ISSUE TITLE
Target Alpine Linux for VerneMQ binary packages

### ISSUE THREAD

**Issue by manifest** [vernemq/vernemq#980]
Would be interesting to see resource efficient Alpine Linux as a target for VerneMQ binary packages along with other distributions.

**Comment by codeadict** [comment]
That would be really interesting, packages too, wondering if there will be issues with the C compiler there

**Comment by larshesel** [comment]
That would definitely be cool. Though the library (https://github.com/vernemq/node_package) we use to generate packages doesn't have support for Alpine packages as far as I know. So we would have to either add support for that to the library or switch to some other library which has support for it or roll our own.

An alternative would be docker images based on Alpine, perhaps?

**Comment by manifest** [comment]
The docker image will work for us if only the installation will be standalone, so that we will be able to use multi-stage future of docker (move entire installation of VerneMQ from one stage to another).

**Comment by larshesel** [comment]
We recently added a Dockerfile for alpine which uses multi-stage builds: https://github.com/vernemq/docker-vernemq/blob/master/Dockerfile.alpine, would that suffice?

**Comment by manifest** [comment]
It's great news. Will you have plans pushing it to Docker Hub?

**Comment by dergraf** [comment]
@manifest lars is absolutely right, we'll be having Alpine based images. Once we made the final move away from the erlio/docker-vernemq to the vernemq/vernemq dockerhub repo, you'll have the Alpine images ;)

I'm going to close this for the moment.
