### ISSUE TITLE
Webhook auth_on_publish dropping client connection

### ISSUE THREAD

**Issue by equake** [vernemq/vernemq#982]
Hi! 
I'm trying to upgrade an mosquitto installation to VerneMQ.
Clients should be able to publish only to a very restrict list of topics.

When someone try to publish anything that should be blocked, I'm getting the following message in `error.log`:

```2018-11-27 20:04:39.738 [error] <0.570.0>@vmq_mqtt_fsm:auth_on_publish:691 can't auth publish [<<"379909">>,{[],<<"marcos161859777">>},0,[<<"xtelemetry">>,<<"driver">>,<<"379909">>],<<"manzan">>,false] due to error```

Is that the expected behavior?

Thanks in advance!

**Comment by larshesel** [comment]
Hi,

No, the `error` reason should only occur when something unexpected happened. 

Is the endpoint reachable for example? Are there any other errors previously in the logs? Also which version of VerneQ are you running and which plugins do you have enabled?

**Comment by equake** [comment]
Hi @larshesel ! Thanks for the quick response.

We're using VerneMQ version `1.6.1`, downloaded just yesterday. Ubuntu 18.04.1 (bionic)
The endpoint is reachable and really simple. (python +bottlepy):

```python
@app.route('/acl', method='POST')
def acl():
    hook = request.headers.get('vernemq-hook')
    username = request.json.get('username')

    if hook == 'auth_on_publish':
        topic = request.json.get('topic')

        if topic.startswith('telemetry/driver/%s' % username):
            log.info('ACL accepted for user %s, topic %s' % (username, topic))
            response.headers.append('Cache-Control', 86400)
            return {'result': 'ok'}
        else:
            log.error('ACL denied for user %s, topic %s' % (username, topic))
            return {'result': {'error': 'not allowed'}}  # here lies the problem

    return {'result': {'error': 'Unknown hook "%s"' % hook}}
```

I get no errors when I replace the `{'result': {'error': 'not allowed'}}` with `{'result': 'ok'}`. 
Returning `{'result': {'error': 'not allowed'}}` for the `auth_on_subscribe` hook is working fine.
No other erros in the logs.

Our config file is very straightforward, as we're still learning about VerneMQ:

```properties
allow_anonymous = off
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 0.0.0.0:44053
listener.http.default = 127.0.0.1:8888
listener.mountpoint = off
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = off
plugins.vmq_webhooks = on
plugins.vmq_bridge = off
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off
vmq_webhooks.webhook1.hook = auth_on_subscribe
vmq_webhooks.webhook1.endpoint = http://localhost:8100/acl
vmq_webhooks.webhook2.hook = auth_on_publish
vmq_webhooks.webhook2.endpoint = http://localhost:8100/acl
vmq_webhooks.webhook3.hook = auth_on_register
vmq_webhooks.webhook3.endpoint = http://localhost:8100/auth
log.console = file
log.console.level = info
log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = VerneMQ@127.0.0.1
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
```

Thanks for the help! :smiley:

**Comment by larshesel** [comment]
Hi, I just quickly looked into this and this does indeed look like a bug... will try to figure out how to fix this and improve our tests. Thanks for reporting.

**Comment by larshesel** [comment]
I created #985 which should make the webhook error reasons propagate to the logs where appropriate.

**Comment by equake** [comment]
I think that would be good enough!

Thanks :+1:

**Comment by larshesel** [comment]
Great, otherwise let us know! We're always thankful for feedback!
