### ISSUE TITLE
Windows OS support

### ISSUE THREAD

**Issue by vostafil** [vernemq/vernemq#983]
On VerneMQ [download page](https://vernemq.com/downloads/) there is said that the broker doesn't support Windows yet due to LevelDB code.

On [LevelDB page](http://leveldb.org/) Windows is listed as supported platform.

Could you please suggest what is involved in implementing Windows support and how big would the effort be?

**Comment by vostafil** [comment]
Thank you @larshesel for the feedback,

I would like to ask a couple more related questions:
1. Can we run VerneMQ on Windows with persistence disabled (i.e. in-memory persistence used)?
2. How much effort would it take to implement rocks-db support for VerneMQ 1.x as opt-it?
3. How much effort would it take to implement rocks-db or some other storage support for VerneMQ 2.0? Also is VerneMQ 2.0 release scheduled?

Thanks in advance!

**Comment by SkinnySackboy** [comment]
Hi @larshesel, by any chance had anything come of this during the past year, or is Windows hosting still not an option?

**Comment by larshesel** [comment]
Windows is still not supported directly, though I've heard that it should be possible via docker.

**Comment by SkinnySackboy** [comment]
@larshesel thanks, that's what we ended up deciding.

**Comment by whatever778** [comment]
@larshesel since there hasn't been any activity here since 2019...may I ask if there are any news on this? 
Is there a chance that VerneMQ 2.0 will support Windows at all? Thanks for your help!

**Comment by ioolkos** [comment]
@whatever778 Thanks for asking, yes, there is a chance that Verne 2.0 will support Windows :)

Works on RocksDB and Leveled is happening, https://github.com/vernemq/vernemq/pull/1885, although there remains stuff to do.
Leveled is pure Erlang, RocksDB does not have the compile issues eleveled has (which is the single reason there's no Windows support, as mentioned in thread).

Note that for production deployments, there will always be the recommendation to deploy on Linux.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by whatever778** [comment]
@ioolkos cool, thanks for your answer. Is there also an estimated timeline or is it all still sort of up in the air?

**Comment by ioolkos** [comment]
@whatever778 enabling RocksDB etc is concrete & prioritised but I will not announce a time line for it just now.

If you'd want to discuss any specific context, just leave a message on Verne site.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
