### ISSUE TITLE
Topic saturation

### ISSUE THREAD

**Issue by ricardoatsouza** [vernemq/vernemq#987]
We have a VerneMQ cluster with **3 nodes** inside a kubernetes cluster. In our use case, we have a single topic that can have a maximum throughput of around 500k / s in peak hours. Sometimes, due to the traffic, the latency might change and, when that happens, sometimes the VerneMQ nodes stops "operating normally".

By "operating normally" I simply mean "stops being fast as it normally is".

We found out that a way to fix this issue is to downscale VerneMQ to 1, scale it again to 3, and restart the first instance. This, I would say, is equivalent to restart the entire cluster.

I am very aware that this is a lot of assumptions over VerneMQ. Therefore, we have been thinking on how we can optimise its usage. That's why we were wondering if this particular topic is oversaturated and if that would be a bottleneck to, not only VerneMQ, but any other MQTT broker.

(As a side note, all the messages on that particular topic are also being published to another topic, so generating more traffic).

We would like to know if there is a way to optimise VerneMQ. Thus I ask:

 - What's the maximum throughput of a topic that VerneMQ cluster can deal with?
 - Performance wise, does it change if we split the traffic into sub-topics (meaning adding a "<the-topic>/<partition>" to it)? In this case, we would subscribe several consumers on a partition basis.
 - If adding partitions to the topic doesn't change the performance of it, what VerneMQ configuration details would you recommend for our case?

### Environment

- VerneMQ Version: erlio/docker-vernemq:1.6.1
- OS: ubuntu 16.04
- Kubernetes version: 1.12
- VerneMQ configuration (vernemq.conf) or the changes from the default: 

```bash
  DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT: "on"
  DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT: "on"
  DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT: "on"
  DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT: "on"
  DOCKER_VERNEMQ_DISCOVERY_KUBERNETES: "1"
  DOCKER_VERNEMQ_ERLANG.async_threads: "1024"
  DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MAXIMUM: "9109"
  DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MINIMUM: "9100"
  DOCKER_VERNEMQ_KUBERNETES_APP_LABEL: vernemq
  DOCKER_VERNEMQ_KUBERNETES_INSECURE: "1"
  DOCKER_VERNEMQ_LISTENER__VMQ__CLUSTERING: 0.0.0.0:44053
  DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES: "-1"
  DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST: "127.0.0.1:1883"
  DOCKER_VERNEMQ_VMQ_PASSWD__PASSWORD_FILE: /etc/vernemq-passwd/vmq.passwd
```

### Expected behavior

- VerneMQ to handle a lot of traffic (few peaks up to ~500k / s).

### Actual behaviour

- VerneMQ gets slow when operating under a lot of traffic (few peaks up to ~500k / s).

Thanks

**Comment by larshesel** [comment]
Hi, that's a really interesting case - I don't think we've every tried to push that many messages/s over a single topic before - most use cases have messages flowing over several topics at that levels. So this is of course really interesting. From a vernemq handling a message is done roughly like the following:

1. A message is published the erlang process handling the session will do a lookup into the routing table to see the subscribers the message should be forwarded to and forwards the message to the queue process for the subscribing client
2. For each of the subscribing clients the message is forwarded from the queue process (if the client is online) to the session process for the subscribing client and sent out over the socket.

point 1 happens in the context of the session process of the publisher, so this is in a way completely scalable as each process can run on any core. It may be that what you're experiencing is contention when the lookup to find the subscribers is done in the routing table as this is a shared datastructure (ETS tables). Point 2 happens in the context of each subscriber and all subscribers are independent of each other and thus are theoretically completely scalable over the number of cores. 

It could certainly be the routing table lookup which is causing problems here, but before drawing any conclusions I think it would be good with some more information about the number of publishers/subscribers/qos levels/message sizes etc as well as load metrics (cpu/cores/memory/io) when the peak occurs.

**Comment by ricardoatsouza** [comment]
Hi @larshesel , thanks for the quick answer.

I have just updated my message by adding the environment information and configuration. We have several grafana charts with that information. I will share them with you soon.

**Comment by ricardoatsouza** [comment]
Hi @larshesel , here are some charts.

To give you some background about the service itself. The messages it receives are compressed. Their size, on average, is around 100 KB. The service will expand every incoming message into an array of messages and it will send each of them back to VerneMQ (back to the topic in question). During the peak hours, kubernetes scales up the service in question and the average ratio published/ received is around 500 /s per service during those hours.

In the image below, you can see two charts, one for the number of received and another for the number of published messages over time. I made some notes to highlight the events I described previously.

<img width="1631" alt="service_messages_in_out" src="https://user-images.githubusercontent.com/7985816/49223957-7b338d00-f3e0-11e8-92bc-51f96250b8d7.png">

The next image shows the CPU, memory and Net I/O charts of the VerneMQ nodes (kubernetes generated charts). I also highlighted the same events in them.

<img width="3247" alt="cpu_memory_net" src="https://user-images.githubusercontent.com/7985816/49223951-78389c80-f3e0-11e8-8379-3f995ccbb476.png">

Other things that might be of interest:
 - QoS for both subscription and publish mechanisms is 0 in the service
 - Produced messages have, on average, size equals to 0,5 KB (JSON messages only)
 - Number of services subscribed in the incoming topic is at least 2 (can go up to 30, managed by kubernetes)
 - Number of services subscribed to the outgoing topic is 2 (we are not scaling this one up, yet), sometimes 3 (due to scheduled jobs)
 - Slow means the drop (as you can see in the chart) of 200k produced messages to less than 3k on average, on all the services.

Please, let me know if you need more information.

Thanks.

**Comment by larshesel** [comment]
Hi, thanks for the data! I don't really have any obvious ideas yet, but it may be helpful to know if anything is written to the logs when (and leading up to) the drop.

**Comment by cbluth** [comment]
@larshesel do you mean the stdout logs of vernemq?
If so, we (@ricardoatsouza and i) can capture the logs and return them here the next time we see the issue.

**Comment by larshesel** [comment]
Yes, the logs from stdout. Metrics would also be helpful (maybe something looks weird?)

**Comment by ricardoatsouza** [comment]
Hi @larshesel, thanks for the answer.

We will try to catch the problem in the logs. It happened before a few times, so I would expect it to happen again. Meanwhile, if we instead use a strategy to split the traffic in a  topic-partition fashion (meaning `<topic-name>/<partition>`), do you have an idea of how it would impact the performance?

**Comment by larshesel** [comment]
If indeed the routing is the bottleneck as contemplated above then that might have an impact. But from your description and the graphs it looks like the system stalls for some reason, so I don't really think splitting the topic in that way would do much.

**Comment by larshesel** [comment]
Closing for now - let us know if more data becomes available and we can reopen. Note that there's an interesting improvement which may/may not be of interest to you on the way via https://github.com/vernemq/vernemq/issues/988#issuecomment-446597814
