### ISSUE TITLE
compile error on freebsd11.2

### ISSUE THREAD

**Issue by addriumruss** [vernemq/vernemq#993]
freebsd: 11.2 release
erlang 19.3

root@bsd11:/usr/home/russ/mqtt/vernemq-1.6.2 # gmake rel
fatal: not a git repository (or any of the parent directories): .git
/usr/home/russ/mqtt/vernemq-1.6.2/rebar3  release
===> Fetching rebar3_cuttlefish ({git,
                                         "git://github.com/vernemq/rebar3_cuttlefish",
                                         {branch,"otp21-compatibility"}})
===> Plugin {rebar3_cuttlefish,
                       {git,"git://github.com/vernemq/rebar3_cuttlefish",
                           {branch,"otp21-compatibility"}}} not available. It will not be used.
===> Verifying dependencies...
===> Compiling vmq_ql
===> Running neotoma...
===> Getting log of git dependency failed in /usr/home/russ/mqtt/vernemq-1.6.2. Falling back to version 0.0.0
===> Compiling vmq_plugin
===> Getting log of git dependency failed in /usr/home/russ/mqtt/vernemq-1.6.2. Falling back to version 0.0.0
===> Compiling vmq_commons
===> Getting log of git dependency failed in /usr/home/russ/mqtt/vernemq-1.6.2. Falling back to version 0.0.0
===> Compiling vmq_server
===> Getting log of git dependency failed in /usr/home/russ/mqtt/vernemq-1.6.2. Falling back to version 0.0.0
===> Compiling vmq_webhooks
===> Getting log of git dependency failed in /usr/home/russ/mqtt/vernemq-1.6.2. Falling back to version 0.0.0
===> Compiling vmq_acl
===> Getting log of git dependency failed in /usr/home/russ/mqtt/vernemq-1.6.2. Falling back to version 0.0.0
===> Compiling vmq_plumtree
===> Getting log of git dependency failed in /usr/home/russ/mqtt/vernemq-1.6.2. Falling back to version 0.0.0
===> Compiling vmq_passwd
===> Getting log of git dependency failed in /usr/home/russ/mqtt/vernemq-1.6.2. Falling back to version 0.0.0
make[1]: "/usr/home/russ/mqtt/vernemq-1.6.2/apps/vmq_passwd/c_src/Makefile" line 4: Missing dependency operator
make[1]: "/usr/home/russ/mqtt/vernemq-1.6.2/apps/vmq_passwd/c_src/Makefile" line 8: Need an operator
make[1]: Fatal errors encountered -- cannot continue
make[1]: stopped in /usr/home/russ/mqtt/vernemq-1.6.2/apps/vmq_passwd/c_src
===> Hook for compile failed!

gmake: *** [Makefile:64: rel] Error 1
root@bsd11:/usr/home/russ/mqtt/vernemq-1.6.2 #

**Comment by larshesel** [comment]
Hi @addriumruss did you get it to work?

**Comment by addriumruss** [comment]
@larshesel Thanks so much, I'll try it again~
