### ISSUE TITLE
Last Will (LWT) authentication error.

### ISSUE THREAD

**Issue by selarep** [vernemq/vernemq#996]
### Environment
- VerneMQ Version: 1.6.2
- OS: Official Docker image.
- VerneMQ configuration: Disallow anonymous and activate diversity and postgres plugin.

### Expected behavior
When I connect a new client with clientId and username which previously has connected with last will testament, and not clossed connection, the last will payload is posted in the last will topic without any authentication log warning.

### Actual behaviour
When I do which I explain above, I get the following errors:
[error] can't auth publish [<<"xxx">>,{[],<<"xxx">>},0,[<<"xxx">>,<<"x">>,<<"xxx">>],<<"xxx">>,false] due to not_authorized
[warning] can't authenticate last will for client {[],<<"xxx">>} due to not_allowed.

The postgres ACL and authentication is working as expected, the client has permission to publish in the last will topic, even the last will message is published as expected, but the warning is annoyoing.

Maybe it is a simple log bug or maybe I missed some configuration, but If you could check it, I will be very grateful.

Thank you :+1:

**Comment by larshesel** [comment]
Hi @selarep, thanks for reporting - we'll take a look at this!

**Comment by larshesel** [comment]
I was thinking a bit about this and looked into the code. The last will is checked when the client connects, so I would think what you see is that the last will is send for the existing connection but the last will for the new connection is rejected (did the ACLs change?).

Hope that makes sense.

**Comment by selarep** [comment]
Thanks for your answer. What you say makes sense, but ACLs remain unchanged. Even I tried with a client with pubsub wildcard (#), and the same message appears.
Maybe is a problem due to accept an entering connection, having one pending last will of previous connection?

The way I reproduced the issue is with mosquitto_sub. I generate a connection with mosquitto_sub (with proper last will info), and abort client with Ctrl+Z. Then running the same mosquitto_sub command with same username and clientId I get the error.
If I wait for last will to be published (connection closed due to timeout), and then create the new connection, there is no problem.

**Comment by larshesel** [comment]
Which plugins do you use? `vmq_passwd` and `vmq_acl`?

**Comment by selarep** [comment]
My mosquitto_sub command is: 
`mosquitto_sub -h localhost -u MYUSERNAME -i MYCLIENTID -P MYPASSWORD -t clima1/1 -k 10 -q 0 --will-topic clima1/1/status --will-qos 0 --will-payload "offline" -d`
My publish ACL is:
[{
    "pattern": "clima1/1/status"
}].

Maybe it is a plugin related issue?

**Comment by larshesel** [comment]
The `vmq_diversity` plugin caches stuff - could you unload/load the plugin or restart vernemq to make sure it's not some kind of strange caching issue, though I think it's unlikely.... Anyway it could be interesting to see what the output of `vmq-admin trace client client-id=<CLIENTID>` is when reproducing it as well as what is written to the log without obscuring client-id/topics if possible.

Are you sure you're not picking up the wrong entry in the postgresql db for some reason? The key for each query is username, password and clientid - so if any of those change then you might not fetch the data you expect.

**Comment by selarep** [comment]
Firsf of all, I have configured an environment with vmq_acl and vmq_password, and the issue is not reproducible. So the issue seems to be related to postgres or diversity plugin.

I am working with docker containers, so I have erased docker caches and rebuild vernemq container. The problem persists.

Dump of the output of vmq-admin trace:
```
No sessions found for client "agromote-1"
New session with PID <7616.511.0> found for client "agromote-1"
RPC to 'VerneMQ@172.20.0.3' failed: {'EXIT',
                                     {badarg,
                                      [{io,format,
                                        [<0.52.0>,
                                         "~p MQTT RECV: CID: \"~s\" CONNECT(c: ~s, v: ~p, u: ~s, p: ~s, cs: ~p, ka: ~p)~n    with LWT(wr: ~p, wq: ~p, wt: ~s) with payload:~n    ~s~n",
                                         [<7616.511.0>,<<"agromote-1">>,
                                          <<"agromote-1">>,3,<<"agromote-1">>,
                                          <<"password">>,1,10,0,0,
                                          <<"clima1/1/status">>,<<"offline">>,
                                          []]],
                                        []},
                                       {vmq_tracer,handle_call,3,
                                        [{file,
                                          "/vernemq-build/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,174}]},
                                       {gen_server,try_handle_call,4,
                                        [{file,"gen_server.erl"},{line,636}]},
                                       {gen_server,handle_msg,6,
                                        [{file,"gen_server.erl"},{line,665}]},
                                       {proc_lib,init_p_do_apply,3,
                                        [{file,"proc_lib.erl"},{line,247}]}]}}
```
Dump of log when reproducing while running vmq-admin trace:
```
vernemq_1   | 14:58:30.270 [error] gen_server vmq_tracer terminated with reason: bad argument in call to io:format(<17575.52.0>, "~p MQTT RECV: CID: \"~s\" CONNECT(c: ~s, v: ~p, u: ~s, p: ~s, cs: ~p, ka: ~p)~n    with LWT(wr: ~...", [<0.511.0>,<<"agromote-1">>,<<"agromote-1">>,3,<<"agromote-1">>,<<"password">>,1,10,0,0,<<"clima1/...">>,...]) in vmq_tracer:handle_call/3 line 174
vernemq_1   | 14:58:30.270 [error] CRASH REPORT Process vmq_tracer with 2 neighbours crashed with reason: bad argument in call to io:format(<17575.52.0>, "~p MQTT RECV: CID: \"~s\" CONNECT(c: ~s, v: ~p, u: ~s, p: ~s, cs: ~p, ka: ~p)~n    with LWT(wr: ~...", [<0.511.0>,<<"agromote-1">>,<<"agromote-1">>,3,<<"agromote-1">>,<<"password">>,1,10,0,0,<<"clima1/...">>,...]) in vmq_tracer:handle_call/3 line 174
vernemq_1   | 14:58:30.270 [error] CRASH REPORT Process <0.511.0> with 0 neighbours exited with reason: bad argument incall to io:format(<17575.52.0>, "~p MQTT RECV: CID: \"~s\" CONNECT(c: ~s, v: ~p, u: ~s, p: ~s, cs: ~p, ka: ~p)~n    with LWT(wr: ~...", [<0.511.0>,<<"agromote-1">>,<<"agromote-1">>,3,<<"agromote-1">>,<<"password">>,1,10,0,0,<<"clima1/...">>,...]) in vmq_tracer:handle_call/3 line 174 in gen_server:call/2 line 206
vernemq_1   | 14:58:30.271 [error] Ranch listener {{172,20,0,3},1883} terminated with reason: bad argument in call to io:format(<17575.52.0>, "~p MQTT RECV: CID: \"~s\" CONNECT(c: ~s, v: ~p, u: ~s, p: ~s, cs: ~p, ka: ~p)~n    with LWT(wr: ~...", [<0.511.0>,<<"agromote-1">>,<<"agromote-1">>,3,<<"agromote-1">>,<<"password">>,1,10,0,0,<<"clima1/...">>,...]) invmq_tracer:handle_call/3 line 174
vernemq_1   | 14:58:36.190 [error] can't auth publish [<<"agromote-1">>,{[],<<"agromote-1">>},0,[<<"clima1">>,<<"1">>,<<"status">>],<<"offline">>,false] due to not_authorized
vernemq_1   | 14:58:36.190 [warning] can't authenticate last will
vernemq_1   |                           for client {[],<<"agromote-1">>} due to not_allowed
```

I'm completely sure about the entry that I'm picking from pgsql because I have reduced the scenario to a bare minimum in which i have only one acl client entry.

I hope that the info above helps to find the issue.

**Comment by larshesel** [comment]
ok - thanks for the additional info. Is this setup something I could run locally to test? Otherwise I'd have to try to reproduce it by setting up postgres etc which would take a while. 

Btw - seems like you found a bug in the tracer - seems there's a problem formatting the lwt.

**Comment by larshesel** [comment]
@dergraf to reproduce this: a client is already connected and creates a second connection with the same client-id and lwt. The second LWT is then rejected due to authorization issues (even thought it worked the first time). My hypothesis is this is a racy interaction between the teardown of the old client (which will get kicked out) and the removal of the acl rules and the new client. Likely the new client will cause authentication rules to be fetched and overwrite the old ones and in the meantime the old client is kicked out and the authentication rules are deleted from the cache and then the new client tries to authenticate the LWT and fails?

**Comment by dergraf** [comment]
@larshesel It's exactly what you've mentioned... now how to fix it? Either synchronize cache updates or use an ETS bag...
