### ISSUE TITLE
Vernemq crash error

### ISSUE THREAD

**Issue by Jooyyce** [vernemq/vernemq#999]
### Environment

- VerneMQ Version: 1.2.3 and 1.6.2
- VerneMQ configuration (vernemq.conf) :  log.console =  both

### Expected behavior
My vernemq service is started and there's no error messages shown in the journal log. However, I checked the console log, error log as well as the crash log and there're errors every minutes like:

2018-12-10 16:47:18.037 [error] <0.25656.7> CRASH REPORT Process <0.25656.7> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size([[<<0,27>>,[47,<<"xxx">>,47,<<"xxx">>,47,<<"sync">>,47,<<"server">>]],{retain_msg,<<"154411...">>,...}]) in vmq_parser:serialise/1 line 242

2018-12-10 16:47:18.037 [error] <0.25656.7> Ranch listener {{0,0,0,0},1883} terminated with reason: badarg

### Steps

- Change the vernemq.conf file : log.console =  both
- Restart the vernemq service
- Check the vernemq log files (console, crash, error)

**Comment by larshesel** [comment]
Hi,

So what you see here is an error to serialize an outgoing publish
data packet.

Can you provide a bit more information about what is going on
when you see this? Is a client publishing a message to a topic
where there's already a subscriber present or is the client
subscribing?

In any case the information from the crash.log file would be
helpful as this has more detailed information about
crashes (including stack-traces).

Can you reproduce this on 1.6.2 if you start from
scratch (removing the data folders) and what are the steps to
reproduce this?

**Comment by Jooyyce** [comment]
Thanks for your answer. Actually we don't have this problem but problem of crash report when broker stops. Here's the new issue: [https://github.com/vernemq/vernemq/issues/1004](url)
